### ISSUE TITLE
How to run multiple instances?

### ISSUE THREAD

**Issue by kolorafa** [wwmm/pulseeffects#10]
I want to auto-limit my output while doing equalizer on input.
I could just run 2times and do some routing, but looks like it prevents me from running multiple instances.

KDE Plasma
Arch Linux

BTW. Keep up the great work! It works great!

**Comment by wwmm** [comment]
Hi

There is indeed a point in running multiple instances. But I don't know if it will be possible. As the code is now all instances will try to create and delete the same pulseaudio sink. They will also try to save settings in the same dconf schema.

**Comment by kolorafa** [comment]
I did run second instance from root and it did create second record and playback, but didn't create second dummy sink like you already pointed.

Maybe i could manually add a second sink and in teory it should work. I will try to test it tommorow or over weekend, but it would be great to be able to run 2 instances.
I can always use fast_lookahead_limiter_1913 for output, but somehow the sound skips when new sound playback device is connecting.
