### ISSUE TITLE
Missing part of the UI

### ISSUE THREAD

**Issue by libasoles** [wwmm/pulseeffects#100]
Hi. I've just installed **pulseeffects** in manjaro (KDE) using **yaourt**. And I'm able to run it but there's something wrong because I don't see the main UI area.

![screenshot_20171023_205112](https://user-images.githubusercontent.com/8009070/31918656-33ca324a-b834-11e7-9762-49fe7b6ddb03.png)

Some effects are indeed working. But none displays a single thing in the right panel. Any clue about what's going on?

**Comment by libasoles** [comment]
Nevermind, it works. But you have to click on the effects labels. Clicking the switches will not show the UI content.

Anyway, some things still don't work. Like the dark theme. And the sound is not working after closing and reopening the app.

**Comment by wwmm** [comment]
Hi. It seems to me you are using kde. I am not sure if the dark theme works in this desktop as this switch changes a gtk config. Maybe it should work in ode too. But I do not know.

I didn't understand the issue with the sound. You can not hear any sound after closing and reopening the app?

**Comment by libasoles** [comment]
It turns out that the mic only works when some app is open. Like vlc, or whatever app. Even navigation with Firefox to youtube and hearing something for a second will enable the mic for a while. And then It will stop capturing. 

So, this is an odd thread but I guess it's solved. 

Great tool. Thanks.

**Comment by wwmm** [comment]
Yes. Gstreamer pipeline is put in the playing state only when an audio application is open.

I think we need some kind of first steps tutorial for new users. Unfortunately all the free time I have to work on PulseEffects is spent implementing new features and fixing bugs. So I hope a user will add this kind of tutorial in the wiki
