### ISSUE TITLE
Would it be possible to choose the spectrum color?

### ISSUE THREAD

**Issue by saltasatelites** [wwmm/pulseeffects#102]
Hello, a question or suggestion. Would it be possible to change the spectrum color? With two of the most used would be enough. White and yellow for example. In my case I use a dark theme with low contrast and practically not seen. The option "Dark Theme" in this case does not help me. Thanks for your excellent work!

**Comment by wwmm** [comment]
I will think about it.  At this moment what I do is using `color = style.lookup_color('theme_selected_bg_color')[1]` in an attempt to follow the theme colors. Maybe the key `theme_selected_bg_color` isn't the one I should be using. I will investigate.

**Comment by wwmm** [comment]
Code in latest master allows the user to choose a custom color for the spectrum
