### ISSUE TITLE
Headless or cli support?

### ISSUE THREAD

**Issue by Sudokamikaze** [wwmm/pulseeffects#103]
Hi, what to you think about running without gui? It would be good option for everyday usage since i don't need gui after first setup

**Comment by wwmm** [comment]
Hi, we have command line options that allow you to hide the window [https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options](https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options)

**Comment by Sudokamikaze** [comment]
@wwmm Oh, sorry, i missed it. Thanks for your response!
 i'll close issue
