### ISSUE TITLE
Add a function to set the output channels

### ISSUE THREAD

**Issue by ZeroDot1** [wwmm/pulseeffects#105]
An easy possibility to select stereo, mono, 5.1, 7.1 etc

**Comment by wwmm** [comment]
Hi. I don't think this will be possible as a few plugins like the limiter and the reverb are only stereo. For this reason I am forcing the gstreamer pipeline and the pulseaudio's sinks created by pulseeffects to be stereo

**Comment by ZeroDot1** [comment]
Is it at least possible to adjust mono?
That would be very good for people with only one ear.

A small example, if you only have one ear and listen to a radio play in stereo, you can't hear everything because the voices and sounds are distributed over two channels.

I can speak from experience, because I have lost my ear due to a disease. 

Except for this little detail, I like the software very much and I want to thank you for developing the software.

**Comment by wwmm** [comment]
Although the same limitation applies to mono I think you can achieve what you want by using another way. Enable the panorama plugin and move the slide all the way to the speaker you want to listen (left or right).

**Comment by wwmm** [comment]
This plugin may seem a balance control at first site but is more than that. It changes the stereo position. So moving the slide all the way to one of the sides will put all the sound in that channel.

**Comment by ZeroDot1** [comment]
Thanks for the tip, it works very good.
I use the software with Arch Linux MellowPlayer and Spotify.

https://github.com/ColinDuquesnoy/MellowPlayer

**Comment by ZeroDot1** [comment]
Thanks again for developing the software.
I am now using PulseEffects on all my Linux computers with Arch Linux.

**Comment by wwmm** [comment]
I am glad it is being useful :-)
