### ISSUE TITLE
UI doesn't scale to display size

### ISSUE THREAD

**Issue by milkmiruku** [wwmm/pulseeffects#106]
The main windows doesn't fit on my 1280x1024 monitor.

![silver_2017-11-04-39](https://user-images.githubusercontent.com/108225/32410424-7cc48d60-c1b7-11e7-9e04-0759faf383d9.png)

**Comment by wwmm** [comment]
Are other gtk applications like gedit or nautilus scaling properly? I have no problems in Gnome with a resolution of 2560x1080. As PulseEffects use client side decorations this could be related to the way kde is interacting with this.

**Comment by AsavarTzeth** [comment]
I managed to reproduce this by setting my 3840x2160 native 27" display to 1280x1024. When I launch PulseEffects it does fit, but only barely. Of course, 1280x1024 is not native to my widescreen display.

It does not surprise me that on a 5:4 display you get issues with the minimum width.

This is issue will likely affect any older display that, isn't widescreen.

**Comment by milkmiruku** [comment]
A-ha, indeed, Nautilus also wasn't using what I'd set for GTK3 font size and dpi settings. Having tried various GUI config apps, I resolved the issue by installing and using xsettingsd.

People using large fonts on old monitors for accessibility reasons would suffer, but I guess that's a generally a GTK3 thing.
