### ISSUE TITLE
Incorrect shebang

### ISSUE THREAD

**Issue by ikeydoherty** [wwmm/pulseeffects#11]
Please note that at present, PulseEffects is Arch-specific, by using the incorrect shebang:

https://www.python.org/dev/peps/pep-0394/

Note that "python" points to "python2" on every distro except Arch, so if portability is a concern,
"python3" should be explicitly requested in the shebang.

**Comment by wwmm** [comment]
Thanks for noticing this. Issue corretec on the latest version (1.2.7)

**Comment by ikeydoherty** [comment]
Thanks :)
