### ISSUE TITLE
new release 3.0.7

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#113]
Before you merged my pull request https://github.com/wwmm/pulseeffects/pull/107, I added PulseEffects to my repo and increased its version to 3.0.7 because I added Russian localisation to it (the main purpose of my repo is its internal usage to distribute software to different corporate computers, and I have plans to use PulseEffects in production)
Can you also tag a new release (new localisation, debian package, updated Readme) to sync them?
Or, otherwise, I will wait for future releases and try to sync later, that's not a big problem.

**Comment by wwmm** [comment]
No problems. Just take a look at the latest comments here #111 to make sure everything is ok

**Comment by AsavarTzeth** [comment]
Would it not have been more correct to use package revision numbers instead? You should never need to make fake releases like this. In Debian packaging that is the last number, followed by the .deb extension.

In your case you should have used 3.0.6-1, 3.0.6-2 etc..

Only upstream, i.e. @wwmm should make new application releases.

**Comment by mikhailnov** [comment]
yes, next time I will use releases)
