### ISSUE TITLE
Problem with building a .deb package on Ubuntu 17.10

### ISSUE THREAD

**Issue by robertkardos** [wwmm/pulseeffects#119]
When I run `debuild -I` the end of the output is the following:

```
...
Finished running lintian.
Now signing changes and any dsc files...
 signfile dsc pulseeffects_3.0.7.3.dsc Mikhail Novosyolov <mikhailnov@dumalogiya.ru>
gpg: skipped "Mikhail Novosyolov <mikhailnov@dumalogiya.ru>": No secret key
gpg: /tmp/debsign.tl3fM26U/pulseeffects_3.0.7.3.dsc: clearsign failed: No secret key
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1053:
running debsign failed
```

**Comment by wwmm** [comment]
@mikhailnov

**Comment by AsavarTzeth** [comment]
Please read the wiki again. I have fixed a lot of serious flaws in the build instructions and clarified a lot of things.

In this case the error message is quite clear. You cannot sign the package, since you don't have the private key. If you did, that key would not be private, but compromised.

**Comment by AsavarTzeth** [comment]
Since this issue is entirely based upon bad instructions, which I fixed, you may consider this solved.

**Comment by mikhailnov** [comment]
Made some fixes: https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source/_compare/e7d49a3dbd77fb3cdc7921dc81bb64b737253766...384c9bd4642ef6546133f581abf56973e412a1b8

**Comment by mikhailnov** [comment]
```apt install ./local_package``` will not work only in Debian <8 and old Ubuntus, which do not meet the dependencies.

**Comment by mikhailnov** [comment]
@robertkardos That's OK, proceed to the next step

**Comment by AsavarTzeth** [comment]
Can you actually install a local package with apt at all? I could not when I tried it on Ubuntu 17.10.

**Comment by mikhailnov** [comment]
yes, if you 
```apt install ./file.deb```
but not
```apt install file.deb```

**Comment by AsavarTzeth** [comment]
I see, very well I will try that then.

**Comment by AsavarTzeth** [comment]
Oh, my bad! I must have done a typo or something during testing. I think part of what confused me is that bash completion does not seem to work from a child directory.

Using `apt` in this manner works perfectly well. Nice to know in the future indeed.

**Comment by mikhailnov** [comment]
it can be closed
