### ISSUE TITLE
Need help running pulseeffects on xubuntu 16.04

### ISSUE THREAD

**Issue by kevinsmia1939** [wwmm/pulseeffects#12]
Hi, 
First I got setup.py to run
kevin@kevin-desktop:~/Desktop/Software/pulseeffects-master$ sudo python3 setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

And I just left it there...
What I do next is...
I follows the steps here.
1. git clone https://github.com/wwmm/pulseeffects.git
2. cd pulseeffects
3. glib-compile-schemas share/glib-2.0/schemas/
4. chmod +x pulseeffects
5. GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects

on the last step I got error.
kevin@kevin-desktop:~/pulseeffects$ GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects
Traceback (most recent call last):
  File "./pulseeffects", line 6, in <module>
    a = Application()
  File "/home/kevin/pulseeffects/PulseEffects/application.py", line 36, in __init__
    self.gst = GstEffects()
  File "/home/kevin/pulseeffects/PulseEffects/gst.py", line 49, in __init__
    self.pipeline = self.build_pipeline()
  File "/home/kevin/pulseeffects/PulseEffects/gst.py", line 109, in build_pipeline
    pipeline.add(self.limiter)
TypeError: Argument 1 does not allow None as a value

However, I got pulseeffect to appear on sound setting>playback>pulseeffect, but no sound.

I don't know how to install it, I don't know which python file are suppose to launch that awesome looking gui.

**Comment by wwmm** [comment]
Hi. The error:

pipeline.add(self.limiter)
TypeError: Argument 1 does not allow None as a value

suggests that you do not have swh-plugins from Ladspa installed. It is needed for the limiter and compressor stages.

**Comment by kevinsmia1939** [comment]
I check, swh-plugins is install, I update my system,I even reboot to make sure, still. 
kevin@kevin-desktop:~/pulseeffects$ sudo apt install swh-plugins
[sudo] password for kevin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
swh-plugins is already the newest version (0.4.15+1-8).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
kevin@kevin-desktop:~/pulseeffects$ GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects
Traceback (most recent call last):
  File "./pulseeffects", line 6, in <module>
    a = Application()
  File "/home/kevin/pulseeffects/PulseEffects/application.py", line 36, in __init__
    self.gst = GstEffects()
  File "/home/kevin/pulseeffects/PulseEffects/gst.py", line 49, in __init__
    self.pipeline = self.build_pipeline()
  File "/home/kevin/pulseeffects/PulseEffects/gst.py", line 109, in build_pipeline
    pipeline.add(self.limiter)
TypeError: Argument 1 does not allow None as a value
kevin@kevin-desktop:~/pulseeffects$

**Comment by kevinsmia1939** [comment]
Any way, I wil check if I got other packages.

**Comment by wwmm** [comment]
At least in Arch Linux the limiter plugin is installed in /usr/lib/ladspa. Check if you have a file named fast_lookahead_limiter_1913.so inside this folder. It seems ubuntu installs in the same place [http://packages.ubuntu.com/xenial/amd64/swh-plugins/filelist](http://packages.ubuntu.com/xenial/amd64/swh-plugins/filelist)

If you have this file then gstreamer is not finding it for some reason. Check if you installed gst-plguins-bad

**Comment by wwmm** [comment]
what is the output of:

gst-inspect-1.0 | grep -i ladspa

in your machine?

**Comment by kevinsmia1939** [comment]
It seems that I have some broken package on gstreamer, now I fix it and got.
kevin@kevin-desktop:~$ gst-inspect-1.0 | grep -i ladspa
ladspa:  ladspa-plate-1423-so-plate: Plate reverb
ladspa:  ladspa-pitch-scale-1193-so-pitchscale: Pitch Scaler
ladspa:  ladspa-notch-iir-1894-so-notch-iir: Mag's Notch Filter
ladspa:  ladspa-comb-1190-so-comb: Comb Filter
ladspa:  ladspa-tap-eqbw-so-tap-equalizer-bw: TAP Equalizer/BW
ladspa:  ladspa-tap-deesser-so-tap-deesser: TAP DeEsser
ladspa:  ladspa-highpass-iir-1890-so-highpass-iir: Glame Highpass Filter
ladspa:  ladspa-rate-shifter-1417-so-rateshifter: Rate shifter
ladspa:  ladspa-const-1909-so-const: Constant Signal Generator
ladspa:  ladspa-tap-dynamics-m-so-tap-dynamics-m: TAP Dynamics (M)
ladspa:  ladspa-gong-beater-1439-so-gongbeater: Gong beater
ladspa:  ladspa-phasers-1217-so-autophaser: Auto phaser
ladspa:  ladspa-phasers-1217-so-fourbyfourpole: 4 x 4 pole allpass
ladspa:  ladspa-phasers-1217-so-lfophaser: LFO Phaser
ladspa:  ladspa-step-muxer-1212-so-stepmuxer: Step Demuxer
ladspa:  ladspa-transient-1206-so-transient: Transient mangler
ladspa:  ladspa-matrix-st-ms-1420-so-matrixstms: Matrix: Stereo to MS
ladspa:  ladspa-dc-remove-1207-so-dcremove: DC Offset Remover
ladspa:  ladspa-valve-1209-so-valve: Valve saturation
ladspa:  ladspa-tap-echo-so-tap-stereo-echo: TAP Stereo Echo
ladspa:  ladspa-lcr-delay-1436-so-lcrdelay: L/C/R Delay
ladspa:  ladspa-sc3-1427-so-sc3: SC3
ladspa:  ladspa-giant-flange-1437-so-giantflange: Giant flange
ladspa:  ladspa-fast-lookahead-limiter-1913-so-fastlookaheadlimiter: Fast Lookahead limiter
ladspa:  ladspa-flanger-1191-so-flanger: Flanger
ladspa:  ladspa-allpass-1895-so-allpass-c: Allpass delay line, cubic spline interpolation
ladspa:  ladspa-allpass-1895-so-allpass-l: Allpass delay line, linear interpolation
ladspa:  ladspa-allpass-1895-so-allpass-n: Allpass delay line, noninterpolating
ladspa:  ladspa-vynil-1905-so-vynil: VyNil (Vinyl Effect)
ladspa:  ladspa-latency-1914-so-artificiallatency: Artificial latency
ladspa:  ladspa-tap-reflector-so-tap-reflector: TAP Reflector
ladspa:  ladspa-am-pitchshift-1433-so-ampitchshift: AM pitchshifter
ladspa:  ladspasrc-caps-so-ceo: C* CEO - Chief Executive Oscillator
ladspa:  ladspasrc-caps-so-click: C* Click - Metronome
ladspa:  ladspasrc-caps-so-fractal: C* Fractal - Audio stream from deterministic chaos
ladspa:  ladspasrc-caps-so-white: C* White - Noise generator
ladspa:  ladspasrc-caps-so-sin: C* Sin - Sine wave generator
ladspa:  ladspa-caps-so-narrower: C* Narrower - Stereo image width reduction
ladspa:  ladspa-caps-so-wider: C* Wider - Stereo image synthesis
ladspa:  ladspa-caps-so-eqfa4p: C* EqFA4p - 4-band parametric eq
ladspa:  ladspa-caps-so-eq4p: C* Eq4p - 4-band parametric shelving equaliser
ladspa:  ladspa-caps-so-eq10x2: C* Eq10X2 - Stereo 10-band equaliser
ladspa:  ladspa-caps-so-eq10: C* Eq10 - 10-band equaliser
ladspa:  ladspa-caps-so-scape: C* Scape - Stereo delay with chromatic resonances
ladspa:  ladspa-caps-so-autofilter: C* AutoFilter - Self-modulating resonant filter
ladspa:  ladspa-caps-so-phaserii: C* PhaserII - Mono phaser
ladspa:  ladspa-caps-so-chorusi: C* ChorusI - Mono chorus/flanger
ladspa:  ladspa-caps-so-spicex2: C* SpiceX2 - Not an exciter either
ladspa:  ladspa-caps-so-spice: C* Spice - Not an exciter
ladspa:  ladspa-caps-so-saturate: C* Saturate - Various static nonlinearities, 8x oversampled
ladspa:  ladspa-caps-so-platex2: C* PlateX2 - Versatile plate reverb, stereo inputs
ladspa:  ladspa-caps-so-plate: C* Plate - Versatile plate reverb
ladspa:  ladspa-caps-so-cabinetiv: C* CabinetIV - Idealised loudspeaker cabinet
ladspa:  ladspa-caps-so-cabinetiii: C* CabinetIII - Simplistic loudspeaker cabinet emulation
ladspa:  ladspa-caps-so-ampvts: C* AmpVTS - Idealised guitar amplification
ladspa:  ladspa-caps-so-tonestack: C* ToneStack - Classic amplifier tone stack emulation
ladspa:  ladspa-caps-so-compressx2: C* CompressX2 - Stereo compressor and saturating limiter
ladspa:  ladspa-caps-so-compress: C* Compress - Compressor and saturating limiter
ladspa:  ladspa-caps-so-noisegate: C* Noisegate - Attenuating hum and noise
ladspa:  ladspa-sc2-1426-so-sc2: SC2
ladspa:  ladspa-fm-osc-1415-so-fmosc: FM Oscillator
ladspa:  ladspa-tap-eq-so-tap-equalizer: TAP Equalizer
ladspa:  ladspasrc-analogue-osc-1416-so-analogueosc: Analogue Oscillator
ladspa:  ladspa-shaper-1187-so-shaper: Wave shaper
ladspa:  ladspa-foldover-1213-so-foldover: Foldover distortion
ladspa:  ladspasrc-sin-cos-1881-so-sincos: Sine + cosine oscillator
ladspa:  ladspasrc-impulse-1885-so-impulse-fc: Nonbandlimited single-sample impulses (Frequency: Control)
ladspa:  ladspa-zm1-1428-so-zm1: z-1
ladspa:  ladspa-matrix-spatialiser-1422-so-matrixspatialiser: Matrix Spatialiser
ladspa:  ladspa-pointer-cast-1910-so-pointercastdistortion: Pointer cast distortion
ladspa:  ladspa-tap-pitch-so-tap-pitch: TAP Pitch Shifter
ladspa:  ladspa-decay-1886-so-decay: Exponential signal decay
ladspa:  ladspa-pitch-scale-1194-so-pitchscalehq: Higher Quality Pitch Scaler
ladspa:  ladspa-gverb-1216-so-gverb: GVerb
ladspa:  ladspa-delay-1898-so-delay-c: Simple delay line, cubic spline interpolation
ladspa:  ladspa-delay-1898-so-delay-l: Simple delay line, linear interpolation
ladspa:  ladspa-delay-1898-so-delay-n: Simple delay line, noninterpolating
ladspa:  ladspa-foverdrive-1196-so-foverdrive: Fast overdrive
ladspa:  ladspa-delayorama-1402-so-delayorama: Delayorama
ladspa:  ladspa-single-para-1203-so-singlepara: Single band parametric
ladspa:  ladspa-satan-maximiser-1408-so-satanmaximiser: Barry's Satan Maximiser
ladspa:  ladspa-se4-1883-so-se4: SE4
ladspa:  ladspa-mbeq-1197-so-mbeq: Multiband EQ
ladspa:  ladspa-tap-doubler-so-tap-doubler: TAP Fractal Doubler
ladspa:  ladspa-dj-flanger-1438-so-djflanger: DJ flanger
ladspa:  ladspa-tap-tremolo-so-tap-tremolo: TAP Tremolo
ladspa:  ladspa-comb-splitter-1411-so-combsplitter: Comb Splitter
ladspa:  ladspa-tap-rotspeak-so-tap-rotspeak: TAP Rotary Speaker
ladspa:  ladspa-amp-so-amp-stereo: Stereo Amplifier
ladspa:  ladspa-amp-so-amp-mono: Mono Amplifier
ladspa:  ladspa-gate-1410-so-gate: Gate
ladspa:  ladspa-chebstortion-1430-so-chebstortion: Chebyshev distortion
ladspa:  ladspa-tap-dynamics-st-so-tap-dynamics-st: TAP Dynamics (St)
ladspa:  ladspa-bandpass-a-iir-1893-so-bandpass-a-iir: Glame Bandpass Analog Filter
ladspa:  ladspa-triple-para-1204-so-triplepara: Triple band parametric with shelves
ladspa:  ladspa-bode-shifter-1431-so-bodeshifter: Bode frequency shifter
ladspa:  ladspa-ringmod-1188-so-ringmod-1i1o1l: Ringmod with LFO
ladspa:  ladspa-ringmod-1188-so-ringmod-2i1o: Ringmod with two inputs
ladspa:  ladspa-matrix-ms-st-1421-so-matrixmsst: Matrix: MS to Stereo
ladspa:  ladspa-tap-vibrato-so-tap-vibrato: TAP Vibrato
ladspa:  ladspa-delay-so-delay-5s: Simple Delay Line
ladspa:  ladspa-svf-1214-so-svf: State Variable Filter
ladspa:  ladspasrc-sine-so-sine-fcac: Sine Oscillator (Freq:control, Amp:control)
ladspa:  ladspa-sine-so-sine-fcaa: Sine Oscillator (Freq:control, Amp:audio)
ladspa:  ladspa-sine-so-sine-faac: Sine Oscillator (Freq:audio, Amp:control)
ladspa:  ladspa-sine-so-sine-faaa: Sine Oscillator (Freq:audio, Amp:audio)
ladspa:  ladspa-tap-limiter-so-tap-limiter: TAP Scaling Limiter
ladspa:  ladspa-tape-delay-1211-so-tapedelay: Tape Delay Simulation
ladspa:  ladspa-sc1-1425-so-sc1: SC1
ladspa:  ladspa-butterworth-1902-so-butthigh-iir: GLAME Butterworth Highpass
ladspa:  ladspa-butterworth-1902-so-buttlow-iir: GLAME Butterworth Lowpass
ladspa:  ladspa-butterworth-1902-so-bwxover-iir: Glame Butterworth X-over Filter
ladspa:  ladspa-comb-1887-so-comb-c: Comb delay line, cubic spline interpolation
ladspa:  ladspa-comb-1887-so-comb-l: Comb delay line, linear interpolation
ladspa:  ladspa-comb-1887-so-comb-n: Comb delay line, noninterpolating
ladspa:  ladspa-lowpass-iir-1891-so-lowpass-iir: Glame Lowpass Filter
ladspa:  ladspa-dj-eq-1901-so-dj-eq: DJ EQ
ladspa:  ladspa-dj-eq-1901-so-dj-eq-mono: DJ EQ (mono)
ladspa:  ladspa-xfade-1915-so-xfade4: Crossfade (4 outs)
ladspa:  ladspa-xfade-1915-so-xfade: Crossfade
ladspa:  ladspa-tap-reverb-so-tap-reverb: TAP Reverberator
ladspa:  ladspa-retro-flange-1208-so-retroflange: Retro Flanger
ladspa:  ladspa-declip-1195-so-declip: Declipper
ladspa:  ladspa-ls-filter-1908-so-lsfilter: LS Filter
ladspa:  ladspa-alias-1407-so-alias: Aliasing
ladspa:  ladspa-revdelay-1605-so-revdelay: Reverse Delay (5s max)
ladspa:  ladspa-diode-1185-so-diode: Diode Processor
ladspa:  ladspa-sc4-1882-so-sc4: SC4
ladspa:  ladspa-smooth-decimate-1414-so-smoothdecimate: Smooth Decimator
ladspa:  ladspa-inv-1429-so-inv: Inverter
ladspa:  ladspa-decimator-1202-so-decimator: Decimator
ladspa:  ladspa-bode-shifter-cv-1432-so-bodeshiftercv: Bode frequency shifter (CV)
ladspa:  ladspa-tap-autopan-so-tap-autopan: TAP AutoPanner
ladspa:  ladspa-crossover-dist-1404-so-crossoverdist: Crossover distortion
ladspa:  ladspa-multivoice-chorus-1201-so-multivoicechorus: Multivoice Chorus
ladspa:  ladspa-divider-1186-so-divider: Audio Divider (Suboctave Generator)
ladspa:  ladspa-imp-1199-so-imp: Impulse convolver
ladspa:  ladspa-tap-tubewarmth-so-tap-tubewarmth: TAP TubeWarmth
ladspa:  ladspasrc-noise-so-noise-white: White Noise Source
ladspa:  ladspa-amp-1181-so-amp: Simple amplifier
ladspa:  ladspa-bandpass-iir-1892-so-bandpass-iir: Glame Bandpass Filter
ladspa:  ladspa-filter-so-hpf: Simple High Pass Filter
ladspa:  ladspa-filter-so-lpf: Simple Low Pass Filter
ladspa:  ladspa-harmonic-gen-1220-so-harmonicgen: Harmonic generator
ladspa:  ladspa-tap-sigmoid-so-tap-sigmoid: TAP Sigmoid Booster
ladspa:  ladspa-karaoke-1409-so-karaoke: Karaoke
ladspa:  ladspa-tap-pinknoise-so-tap-pinknoise: TAP Pink/Fractal Noise
ladspa:  ladspa-tap-chorusflanger-so-tap-chorusflanger: TAP Chorus/Flanger
ladspa:  ladspa-wave-terrain-1412-so-waveterrain: Wave Terrain Oscillator
ladspa:  ladspa-freq-tracker-1418-so-freqtracker: Frequency tracker
ladspa:  ladspa-split-1406-so-split: Mono to Stereo splitter
ladspa:  ladspa-sc4m-1916-so-sc4m: SC4 mono
ladspa:  ladspa-gong-1424-so-gong: Gong model
ladspa:  ladspa-sinus-wavewrapper-1198-so-sinuswavewrapper: Sinus wavewrapper
ladspa:  ladspa-dyson-compress-1403-so-dysoncompress: Dyson compressor
ladspa:  ladspa-sifter-1210-so-sifter: Signal sifter
ladspa:  ladspa-mod-delay-1419-so-moddelay: Modulatable delay
ladspa:  ladspa-hilbert-1440-so-hilbert: Hilbert transformer
ladspa:  ladspa-gsm-1215-so-gsm: GSM simulator
ladspa:  ladspa-surround-encoder-1401-so-surroundencoder: Surround matrix encoder
ladspa:  ladspa-fad-delay-1192-so-faddelay: Fractionally Addressed Delay Line
ladspa:  ladspa-hermes-filter-1200-so-hermesfilter: Hermes Filter
ladspa:  ladspa-valve-rect-1405-so-valverect: Valve rectifier
ladspa:  ladspa-hard-limiter-1413-so-hardlimiter: Hard Limiter

**Comment by kevinsmia1939** [comment]
I tried running 
kevin@kevin-desktop:~$ GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects
bash: ./pulseeffects: Is a directory

Is it ok?

**Comment by wwmm** [comment]
You have to run this command inside pulseeefects folder

**Comment by kevinsmia1939** [comment]
Sorry my stupid. I got it now.

**Comment by wwmm** [comment]
Is it working?

**Comment by kevinsmia1939** [comment]
Yes, works fine now, thanks.

**Comment by wwmm** [comment]
Nice :-) I will close this issue. In case of other problems please open another one.
