### ISSUE TITLE
deepin15.5 install pulseeffects

### ISSUE THREAD

**Issue by liu-lulin** [wwmm/pulseeffects#120]
## deepin15.5 install pulseeffects
wget -q -O- http://repo.dumalogiya.ru/keys/mikhailnov_pub.gpg | sudo apt-key add -
echo "deb http://repo.dumalogiya.ru/aptly/public artful main" | sudo tee /etc/apt/sources.list.d/dumalogiya-artful.list
sudo apt update
sudo apt install pulseeffects `gir1.2-gst-plugins-bad-1.0 at-spi2-core`

**Comment by wwmm** [comment]
I am not sure I understand. Is PulseEffects stopping when you change a song? Which media player are you using? Is there any message printed by PulseEffects in the terminal when this happens?

In any case this should not happen...

**Comment by liu-lulin** [comment]
Yes. I'm using deepin-music.
```
(pulseeffects:6689): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)
21:43:16.193 - PulseEffects - INFO - pulsesrc latency-time [us]: 10000
21:43:16.193 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
21:43:16.193 - PulseEffects - INFO - pulsesink latency-time [us]: 10000
21:43:16.193 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000

(pulseeffects:6689): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)

(pulseeffects:6689): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)
21:44:03.20 - PulseEffects - INFO - pulseaudio version: 10.0
21:44:03.20 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
21:44:03.20 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
21:44:17.560 - PulseEffects - INFO - created stream for sink input 37
21:44:23.576 - PulseEffects - CRITICAL - context operation failed!!

```

**Comment by mikhailnov** [comment]
Why did you install at-spi2-core ?

**Comment by wwmm** [comment]
I installed deepin-music here in Arch Linux to test and I have no problems. Everything works a expected. Something is odd in your log output. Could you post all the lines printed by pulseeffects when running it in the terminal? The lines about latency should not be before the one printing pulseaudio version. This is very strange.

**Comment by mikhailnov** [comment]
I have updated PulseEffects in the repository repo.dumalogiya.ru, please run:
```
sudo apt update
sudo apt dist-upgrade
```
It will update PulseEffects to v3.0.7.4. 

And it is built on Ubuntu 17.10, its libraries are newer than in Deepin.
Try building the deb package locally as on Debian/Ubuntu:
https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source

**Comment by mikhailnov** [comment]
@wwmm Does it link with any libraries when building?

**Comment by liu-lulin** [comment]
Deepin15.5 prompts for a lack of 'a11y. Dbus', so install at-spi2-core.

**Comment by mikhailnov** [comment]
Does pulseefects work without at-spi2-core ?

**Comment by liu-lulin** [comment]
@wwmm 
`~$ pulseeffects 
22:28:44.169 - PulseEffects - INFO - pulseaudio context started
22:28:44.169 - PulseEffects - INFO - connected to server: unix:/run/user/1000/pulse/native
22:28:44.174 - PulseEffects - INFO - server protocol version: 32
22:28:44.180 - PulseEffects - INFO - pulseaudio version: 10.0
22:28:44.180 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
22:28:44.180 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
22:28:44.180 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
22:28:44.181 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
22:28:44.181 - PulseEffects - INFO - default pulseaudio source audio format: s16le
22:28:44.181 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
22:28:44.181 - PulseEffects - INFO - loading Pulseeffects applications sink...
22:28:44.181 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
22:28:44.181 - PulseEffects - INFO - Pulseeffects apps sink index:5
22:28:44.181 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
22:28:44.182 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
22:28:44.182 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
22:28:44.182 - PulseEffects - INFO - Pulseeffects mic sink index:6
22:28:44.182 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
22:28:44.336 - PulseEffects - INFO - limiter plugin was enabled
22:28:44.336 - PulseEffects - INFO - compressor plugin was enabled
22:28:44.337 - PulseEffects - INFO - reverb plugin was enabled
22:28:44.337 - PulseEffects - INFO - highpass plugin was enabled
22:28:44.337 - PulseEffects - INFO - lowpass plugin was enabled
22:28:44.337 - PulseEffects - INFO - equalizer plugin was enabled
22:28:44.338 - PulseEffects - INFO - spectrum plugin was enabled
22:28:44.342 - PulseEffects - INFO - apps: panorama plugin was enabled
22:28:44.345 - PulseEffects - INFO - apps: compressor plugin was enabled
22:28:44.347 - PulseEffects - INFO - apps: reverb plugin was enabled
22:28:44.477 - PulseEffects - INFO - limiter plugin was enabled
22:28:44.477 - PulseEffects - INFO - compressor plugin was enabled
22:28:44.477 - PulseEffects - INFO - reverb plugin was enabled
22:28:44.478 - PulseEffects - INFO - highpass plugin was enabled
22:28:44.478 - PulseEffects - INFO - lowpass plugin was enabled
22:28:44.478 - PulseEffects - INFO - equalizer plugin was enabled
22:28:44.478 - PulseEffects - INFO - spectrum plugin was enabled
22:28:44.510 - PulseEffects - INFO - apps: spectrum plugin was enabled
22:28:44.511 - PulseEffects - INFO - mic: spectrum plugin was enabled
22:28:44.702 - PulseEffects - INFO - pipeline state: playing
22:28:44.741 - PulseEffects - INFO - pulsesrc latency-time [us]: 10000
22:28:44.742 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
22:28:44.742 - PulseEffects - INFO - pulsesink latency-time [us]: 10000
22:28:44.742 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000

(pulseeffects:11382): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)
22:28:48.871 - PulseEffects - INFO - created stream for sink input 122

(pulseeffects:11382): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)

(pulseeffects:11382): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)

(pulseeffects:11382): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)

(pulseeffects:11382): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)
`

**Comment by mikhailnov** [comment]
rerun
```
sudo apt update
sudo apt dist-upgrade
```
upd to v.3.0.7.5
to make sure you are using the latest pulseeffects

**Comment by wwmm** [comment]
@mikhailnov, there is no linking done when building. I also do not make any communication with dbus. So I see no reason why at-spi2 would be needed

**Comment by wwmm** [comment]
@liu-lulin, now the log timeline makes sense. But unfortunately I see nothing that would explain why you are having problems when changing tracks. The warns about `GtkLevelBar` are no harm and are related to a known problem in gtk

**Comment by mikhailnov** [comment]
@liu-lulin try checking ```dmesg``` for segfaults
