### ISSUE TITLE
kubuntu 16.04

### ISSUE THREAD

**Issue by descendingnerdliness** [wwmm/pulseeffects#121]
Thanks for the app.
I use kubuntu 16.04 for stability, but have the backports updates for some more recent app upgrades.  After the recent PA updates, PE tries to work, but gets noisy after a few seconds with auto volume on.  With auto volume off, nothing seems to work. 
Is there anything I can do for it?

**Comment by wwmm** [comment]
Is there any change if you disable the limiter? What Pulseeffects is printing in the terminal? Which PulseEffects version are you running? Could you post snapshots of pavucontrol window(playback, recording and output devices tabs)?

**Comment by mikhailnov** [comment]
kubuntu backports PPA does not contain anything related to sound and PulseAudio
