### ISSUE TITLE
Handle running as a service

### ISSUE THREAD

**Issue by oszi** [wwmm/pulseeffects#122]
Right now, if I have PulseEffects running in CLI mode from a systemd user service
then I open and close the GUI, the CLI instance will also exit. Which can be pretty annoying.

Flatpak run has a --gapplication-service flag that should work like this:
https://github.com/TingPing/transmission-remote-gnome/blob/master/trg/application.py#L69-L71
When this flag is set, the application should not exit and stay in the background.
This would solve auto starting issues.

Thank you for the great project!

**Comment by wwmm** [comment]
I didn't know about this flag and the hold method. They will help. But it may take some time to get this feature working because even with this option it will be necessary to do code refactoring in many places in other to open/close the window without crashes.

**Comment by mikhailnov** [comment]
```
export DISPLAY=:0
pluseeffects & sleep 3 && kdocker -b -w `wmctrl -l | grep -i pulseeffects | awk '{print $1}'`
```
try running something like this, it should override closing button to hiding into tray

**Comment by mikhailnov** [comment]
Well, I've tried, the close button makes PulseEffects exit, but minimizing the window hides it into tray.

**Comment by wwmm** [comment]
PulseEffects 3.0.8 has a service mode. A feature that has been asked many times has finally been implemented. Thank you for the tip @oszi :-)

Let me know if you find any problems

**Comment by wwmm** [comment]
Updated command line options [https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options](https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options)

**Comment by oszi** [comment]
That was quick. Thanks!

**Comment by oszi** [comment]
So I tried out the updated flatpak and something is not right:
If I close the app, the EQ stops working in a short wile (like 10 seconds) and there is no sound at all. PuleseEffects itself stays running. Then I have to switch the audio input to something other than the default and back to the default to reset it and have sound again. At this point the EQ is turned off for the app I was listening to. BTW why did you remove the --switch-on-all-apps flag?

**Comment by wwmm** [comment]
Does the problem remain when running directly from the sources? I have no problems here running with the option `--gapplication-service`. But I do not use flatpak.

I removed the `--switch-on-all-apps` option because now this is done by default when running in service mode.

**Comment by oszi** [comment]
I cannot reproduce it anymore so it was probably Gnome or PulseAudio related. :)
