### ISSUE TITLE
Can't start since update...

### ISSUE THREAD

**Issue by phineas0fog** [wwmm/pulseeffects#123]
Hello :)
Since Ive updated the package, if I try to run pulseeffects, I have this message : `(pulseeffects:3612): GLib-GIO-ERROR **: Settings schema 'com.github.wwmm.pulseeffects.sinkinputs' does not contain a key named 'output-limiter-state'`... 

Full output : https://gist.github.com/phineas0fog/f850376499b7984a1ce5d9d22fc52905

But your software is very great :D

**Comment by wwmm** [comment]
Are you running directly from source code? If yes you have to run `glib-compile-schemas data/` again in order to the knew keys to be found

**Comment by phineas0fog** [comment]
problem solved by installing from sources ;)

**Comment by m1st0** [comment]
I'm finding the same error after building v3.0.9 on Kubuntu 17.10.  I attempted the `glib-compile-schemas data/` .  Error persists. 

`(pulseeffects:5842): GLib-GIO-ERROR **: Settings schema 'com.github.wwmm.pulseeffects.sinkinputs' does not contain a key named 'output-limiter-state'
Trace/breakpoint trap (core dumped)`

My build steps I tried:

`sudo ninja -C build uninstall`
`sudo ninja -C build clean`
`glib-compile-schemas data/`
`meson build --prefix=/usr`
`sudo ninja -C build install`

**Comment by wwmm** [comment]
The command `glib-compile-schemas data/` should be used when running directly from the source code without installing. Try to run `sudo glib-compile-schemas` in a terminal and see if now the schema is compiled.

**Comment by m1st0** [comment]
Schema is compiled. I next go into the build directory and run
pulseeffects. The error still appears. No error with v3.0.6. Trying to get
v3.0.9 working.

**Comment by wwmm** [comment]
You have it compiled at the `data` folder in PE source. This is not going to help when installing to the system. I don't think that meson will do that job for you as this is usually done by the distribution package system. But it should have copied PulseEffects schemas to `/usr/share/glib-2.0/schemas/`. In order to compile schemas in the standard system location you have to run `sudo glib-compile-schemas`. Do not copy the `gschemas.compiled` from the `data` folder in PE source to `/usr/share/glib-2.0/schemas/`. This will break the settings of other apps. 

This error will not happen in version 3.0.6 because it does not have the output limiter. And as consequence of that it does not need the new gsettings keys

**Comment by m1st0** [comment]
I ran as noted `sudo glib-compile-schemas` on
`/use/share/glib-2.0/schemas/` . No improvement seen the installed app nor
in the build folder's binary of pulseeffects.

**Comment by wwmm** [comment]
Are you able to run when following the instructions to run directly from the sources? [https://github.com/wwmm/pulseeffects/wiki/Run-Directly-from-Repository](https://github.com/wwmm/pulseeffects/wiki/Run-Directly-from-Repository)

**Comment by m1st0** [comment]
So, it is compiling correctly and  `GSETTINGS_SCHEMA_DIR=data/ ./pulseeffects.in` works.  So, it seems I have to find out why it isn't respecting schema locations based on my config.  I also have it working with `GSETTINGS_SCHEMA_DIR=/usr/share/glib-2.0/schemas/ pulseeffects` .

**Comment by wwmm** [comment]
It is very strange that it makes difference to specify the standard path in `GSETTINGS_SCHEMA_DIR` variable. It should not be necessary. Could it be that you have a schema folder in `/usr/local` and it is somehow conflicting?

**Comment by m1st0** [comment]
Yes, @wwmm, that is exactly what it was.  I deleted the `/usr/local/share/glib-2.0/schemas/gschemas.compiled` after checking it had no other schema dependencies.  Now works without the standard path.  Thanks.

**Comment by wwmm** [comment]
Ok. At some point you must have made a install without giving meson the `--prefix` option. In this case you must have other PulseEffects files in `/usr/local`. Make sure you remove them too.
