### ISSUE TITLE
meson build fails on Fedora 27

### ISSUE THREAD

**Issue by Natrocx** [wwmm/pulseeffects#127]
After installing the required dependencies according to the wiki the meson _build fails due to missing native dependency 'libpulse'

The output looks something like this:

> The Meson build system
Version: 0.43.0
Source dir: /home/natrocx/packages/pulseeffects
Build dir: /home/natrocx/packages/pulseeffects/_build
Build type: native build
Project name: PulseEffects
Build machine cpu family: x86_64
Build machine cpu: x86_64
Message: Checking dependencies
Found pkg-config: /usr/bin/pkg-config (1.3.10)
Meson encountered an error in file meson.build, line 12, column 0:
Native dependency 'libpulse' not found
A full log can be found at /home/natrocx/packages/pulseeffects/_build/meson-logs/meson-log.txt

The log doesn't give any helpful information though

**Comment by wwmm** [comment]
Dependency check in meson is done through pkg-config. In Arch Linux they put everything in the same package but other distributions split libpulse in one or more packages. Try to find which of them has the file `/usr/lib/pkgconfig/libpulse.pc`

**Comment by Natrocx** [comment]
Sorry, I fear my fedora installation died pretty fast and I can't look into it right now.

**Comment by gombosg** [comment]
Let me know how the F27 installation goes because I'd like to try it, as well. This piece of software looks awesome and I really hope it'll soon be included in the default repos for most distros.

**Comment by gombosg** [comment]
pulseaudio-libs-devel has to be installed. Build in 1 second! @wwmm , please add it to the Fedora dependency list.
Unfortunately I'm not a package maintainer, but I'll look into ways how to incorporate this great app into the Fedora ecosystem. @Natrocx , do you know about anyone?

**Comment by wwmm** [comment]
ok I added it to the wiki
