### ISSUE TITLE
This is now packaged in gentoo

### ISSUE THREAD

**Issue by prometheanfire** [wwmm/pulseeffects#128]
not sure if you want to add it to the list of distros for which it's packaged

It was previously in an overlay (like a ppa, but for gentoo), but now it's in the core repo.

**Comment by wwmm** [comment]
Good to know :-)

Could you add this information to the wiki? https://github.com/wwmm/pulseeffects/wiki/Package-Repositories

**Comment by prometheanfire** [comment]
done, not sure if you want to close this or if there's something else to do.

**Comment by wwmm** [comment]
We can close this. Thanks!
