### ISSUE TITLE
equalizer levels not showing (even with application on/off switch)

### ISSUE THREAD

**Issue by trusiad** [wwmm/pulseeffects#130]
Hi. 
I'm on arch linux, up-to-date, I just installed pulseffects last build. 
THe title says it all : equalizer levels randomly show up. But most of the time, they don't. 
I attached a screenshot, just to make sure I'm clear, and the console output, which doesn't show anything wrong...
If you have any hints...
 
[pulseeffects.txt](https://github.com/wwmm/pulseeffects/files/1512992/pulseeffects.txt)

![capture d ecran de 2017-11-29 09-26-45](https://user-images.githubusercontent.com/16058952/33365196-a2db370e-d4e7-11e7-84f5-628e06277d76.png)

**Comment by wwmm** [comment]
I see no problems in your log. How are you trying to show the equalizer controls? Are you clicking over the name equalizer so its entry becomes blue like the entry that shows the applications list? Or are you just clicking over its switch? In the image you have the applications entry selected. So the equalizer controls are not going to be shown

**Comment by trusiad** [comment]
Well, I didn't get this click-on-the-name thing, and I feel kind of stupid. 
Thanks for the quick answer, and for all the great work. Pulseeffects is just what I was looking for. 
Regards,

**Comment by RichardPIS** [comment]
I finally found the solution to the same problem!
It is a bit unclear that you have to click the word instead of the button.
