### ISSUE TITLE
Can't check on or off the exciter, and bass enhancer

### ISSUE THREAD

**Issue by javery86** [wwmm/pulseeffects#136]
Can't check on or off the exciter, and bass enhancer in v3.1.1.

**Comment by wwmm** [comment]
Make sure you have Calf Studio plugins and the Lilv library installed. Without them the interface for these plugins is automatically disabled

**Comment by bargru** [comment]
I'm using pulseeffects from the AUR and have the same problem. Both required programms are installed as a dependency. Starting pulseeffects via console displays the following warnings:
`21:14:31.311 - PulseEffects - WARNING - Exciter plugin was not found. Disabling it!
21:14:31.311 - PulseEffects - WARNING - Bass Enhancer plugin was not found. Disabling it!`

**Comment by wwmm** [comment]
Does deleting the gstreamer folder inside `~/.cache` make any difference?

**Comment by bargru** [comment]
Yes it works after deleting the folder. 👍
Thank you!

**Comment by matiaszanolli** [comment]
Hello there, I'm having this issue on my local installation of PulseEffects (using Ubuntu 17.10 and the Flatpak package). 
I installed both Calf Studio plugins and the Lilv library, but nothing changed. I also tried deleting all cache folders related to gstreamer in my home directory with no results.

Is there another cache folder I should remove for Flatpak-based installations by any chance?

If there's anything else I can provide (such as logs, for example) that might help you find the cause of this issue, just let me know.

Thanks a lot in advance!

**Comment by wwmm** [comment]
I don't know if @AsavarTzeth had time to update the flatpak package. I don't think that flatpak will use the system libraries. It will probably be necessary to include Lilv, Calf and ZamAudio plugins in the flatpak package container.

**Comment by matiaszanolli** [comment]
Yeah, it makes sense that the flatpak package would require to bundle those libraries instead of using the ones provided by the system. 

Guess I'll wait for the update then, thanks a lot for your quick reply!

**Comment by AsavarTzeth** [comment]
Considering what has been mentioned so far, even when I have update the Flatpak, you might have to delete `~/.var/app/com.github.wwmm.pulseeffects/cache`.

As for the dependencies. Yes, I have to include them in the build manifest. Unfortunately my first attempt last weekend failed. I would appreciate any help I could get in the matter. You can find my current test manifest [here](https://github.com/AsavarTzeth/com.github.wwmm.pulseeffects/blob/bf87cd4fc945568c2cffc2ee957237f9ffd13bcd/com.github.wwmm.pulseeffects.json).

The main problem I have right now is that lv2 plugins is not detected by gstreamer. Interesting enough, searching the web on this made me find [this post](http://gstreamer-devel.966125.n4.nabble.com/How-to-use-lv2-plugins-td4683049.html).

**Comment by wwmm** [comment]
I never got an answer to that email to gstreamer mailing list but I had feedback to a bug report I made a few days ago [https://bugzilla.gnome.org/show_bug.cgi?id=791717](https://bugzilla.gnome.org/show_bug.cgi?id=791717). It is bug in Gstreamer and it seems they were able to fix it. Now they are deciding if they will backport the patch to the 1.12 series or if it will be in 1.13.

The only workaround I am aware of is deleting Gstreamer cache

**Comment by wwmm** [comment]
The fix is in their git repo [https://github.com/GStreamer/gst-plugins-bad/tree/master/ext/lv2](https://github.com/GStreamer/gst-plugins-bad/tree/master/ext/lv2)

**Comment by AsavarTzeth** [comment]
Well in my case I am quite confident there is some other issue as well, because I did delete my cache without getting it to work.

That bugzilla thread is interesting though. Based on the comments, I cannot exclude the possibility that one of the new dependencies does not properly support the `/app` prefix (`/app/lib/lv2` libdir) that is used in the Flatpak container.

It sure would not be the first time I experience this issue; it would seem a lot of projects suffer from this.

**Comment by wwmm** [comment]
They updated the target release for the fix in the bug report. Gstreamer 1.13.1.

It may be a path problem. They have the paths hardcoded in the source =/ [gstlv2.c](https://github.com/GStreamer/gst-plugins-bad/blob/master/ext/lv2/gstlv2.c)

**Comment by AsavarTzeth** [comment]
Nice to know the target release. Considering the pain I had in the past when I required a newer release than the runtime provided I will probably backport that patch myself until the runtime includes gstreamer 1.13.*.

Thank you! I will try patching [gstlv2.c](https://github.com/GStreamer/gst-plugins-bad/blob/master/ext/lv2/gstlv2.c) when I get home to my workstation. With any luck that is the only culprit.

**Comment by AsavarTzeth** [comment]
Doh! I found the real cause of the issue. I need to set the environment variable `LV2_PATH` to `/app/lib/lv2`. Surprising really, what one can find in the lv2 `README.md`. **:)**

It is worth noting that I never had to set `LADSPA_PATH` for the ladspa plugins. It sure would be interesting to know what difference may be causing this.

Oh and `gstlv2.c` is probably not an issue given [this line](https://github.com/GStreamer/gst-plugins-bad/blob/master/ext/lv2/gstlv2.c#L67) seem to respect a variable libdir.

**Comment by AsavarTzeth** [comment]
On a minor note. A plugin that has failed to load should probably not be marked with ✔. Currently it makes it look like it is enabled until a user discovers the issue as described.

**Comment by wwmm** [comment]
I will try to fix that in the next release

**Comment by AsavarTzeth** [comment]
Its a minor thing really.

By the way, the flathub buildbot just finished uploading a build that include all the new plugins.

**Comment by matiaszanolli** [comment]
Just gave it a try and works like a charm now, thanks a lot for the update!
