### ISSUE TITLE
Track localization changes

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#140]
PulseEffects is being developed so rapidly, that localization files require changes very often. There should be a way to conveniently track changes. The easiest way is comparing different versions of the main English localization file via diff or Meld (GUI) and porting changes to another localization file, but that will take a bit more time that it probably could.
Maybe someone will have ideas how to automate tracking changes.

**Comment by wwmm** [comment]
Supporting localization is still something new to me. So I have no ideas

**Comment by zencubic** [comment]
@wwmm Wouldn't it be great to use something like [TranslateWiki](https://translatewiki.net/)? This way everyone could work on the translations online

**Comment by mikhailnov** [comment]
@zencubic I don't like this idea because it will disable translating by just editing .po files in a text editor and using git to track changes, pull and send them etc. 

Currently lines that need attention are marked as `~fuzzy`, when I updated po/ru.po recently, it was not difficult to find and manually fix all fuzzies.

**Comment by mikhailnov** [comment]
PulseEffects is full of musical terminology, and translating it to non-latin languages, e.g. Russian, is not trivial, see https://github.com/wwmm/pulseeffects/issues/274 

We will probably add text comment to po/ru.po in the future which will explain why we decided to translate something in that specific way to make other contributors understand the reasons of the choice.
