### ISSUE TITLE
No sound when turn on

### ISSUE THREAD

**Issue by kuriot** [wwmm/pulseeffects#142]
Hello.

When I turn pulseeffects for an application I start hearing just noice, like I'm listening to mic but it's just noice and no other sounds. It's on KDEneon (which is Ubuntu 16.04 based) and Manjaro (with KDE) all the same. What info should I provide to investigate the problem?

**Comment by wwmm** [comment]
What is the output of the command `pactl list modules short`? As far as I know there are two pulseaudio modules that conflict with PulseEffects: `module-device-manager` that is used only by KDE and `module-switch-on-connect` that is loaded by default in the latest ubuntu. Pulseaudio developers are aware of the issues with these modules and have already fixed them in the latest Pulseaudio development version. But until they release Pulseaudio's next version you will have to make sure these modules are not loaded.

**Comment by wwmm** [comment]
Here #99 you can see a length discussion about the problems caused by these two modules and the feedback given by one of Pulseaudio's developers

**Comment by kuriot** [comment]
I see. Thanks for help. 

It's on Manjaro:

```
$ pactl list modules short
0       module-device-restore
1       module-stream-restore
2       module-card-restore
3       module-augment-properties
4       module-switch-on-port-available
5       module-udev-detect
6       module-alsa-card        device_id="1" name="pci-0000_01_00.1" card_name="alsa_card.pci-0000_01_00.1" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes card_properties="module-udev-detect.discovered=1"
7       module-alsa-card        device_id="0" name="pci-0000_00_1b.0" card_name="alsa_card.pci-0000_00_1b.0" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes card_properties="module-udev-detect.discovered=1"
8       module-bluetooth-policy
9       module-bluetooth-discover
10      module-bluez5-discover
11      module-esound-protocol-unix
12      module-native-protocol-unix
13      module-gconf
14      module-default-device-restore
15      module-rescue-streams
16      module-always-sink
17      module-intended-roles
18      module-suspend-on-idle
19      module-console-kit
20      module-systemd-login
21      module-position-event-sounds
22      module-role-cork
23      module-filter-heuristics
24      module-filter-apply
25      module-x11-publish      display=:0
26      module-device-manager   do_routing=1
27      module-x11-xsmp display=:0 session_manager=local/g75vx:@/tmp/.ICE-unix/873,unix/g75vx:/tmp/.ICE-unix/873
```

**Comment by wwmm** [comment]
As expected you have `module-device-manager` loaded. Is there any change if you run PulseEffects after executing the command `pactl unload-module module-device-manager`?

**Comment by kuriot** [comment]
It works fine after unloading this module. Interesting if everything will eork as should without this module. 

Hm. And Bass Enchancer and Exciter are not turning on.

**Comment by wwmm** [comment]
I imagine KDE needs this module for a reason. So it is possible that phonon applications face some kind of issue.

The Bass Enhancer and Exciter needs the package lilv and calf plugins installed. If you have them and it is still not working try to delete the folder `~/.cache/gstreamer-1.0`. I don't know if it is a but in Gstreamer but sometimes it is necessary to delete its cache

**Comment by kuriot** [comment]
It's a clean Manjaro install and lilv and calf are installed as dependencies for pulseeffects. After deleting of `~/.cache/gstreamer-1.0` Bass Enhancer and Exciter are working now. Thanks!

**Comment by wwmm** [comment]
I am glad it is working :-)

**Comment by SADAVA** [comment]
I'll just leave it here, may be it'll help someone.
Ubuntu 18.04.1, PulseEffects v4.3.4
Here's what I have done to make it work.
`$ pactl unload-module module-null-sink`
`$ pactl load-module module-null-sink`
PulseEffects crashed and after I restarted it everything worked.
