### ISSUE TITLE
Application closes after starting.

### ISSUE THREAD

**Issue by GKVM** [wwmm/pulseeffects#145]
I am able to open the application without playing audio. But when I play audio, the application is closing. An earlier version was working fine.

The application was installed on Ubuntu 16.04 using Flathub.

**Comment by wwmm** [comment]
Hi, please follow the steps here [Reporting-Bugs](https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs). Without seeing the logs it is complicated to know what is happening. If possible try also to run directly from the sources [Run-Directly-from-Repository](https://github.com/wwmm/pulseeffects/wiki/Run-Directly-from-Repository). This way we can know if it is a problem with the flatpack package. At least here in Arch Linux running PulseEffects from the sources is fine

**Comment by GKVM** [comment]
The application is working fine after reinstalling using Flathub. Thank you @wwmm for building the great application.
