### ISSUE TITLE
Can't build version 3.1.6 on Void linux

### ISSUE THREAD

**Issue by cr6git** [wwmm/pulseeffects#147]
Hi !

I guess something has changed between versions 3.1.4 and 3.1.6 ?
Can't build version 3.1.6 on Void linux:
````
=> pulseeffects-3.1.6_1: running do_build ...
ninja: Entering directory `build'
[1/2] Generating com.github.wwmm.pulseeffects.desktop_merge with a custom command.
FAILED: data/com.github.wwmm.pulseeffects.desktop 
/usr/bin/python3 /usr/bin/meson --internal msgfmthelper ../data/com.github.wwmm.pulseeffects.desktop.in data/com.github.wwmm.pulseeffects.desktop desktop ../data/../po
[2/2] Generating com.github.wwmm.pulseeffects.appdata.xml_merge with a custom command.
ninja: build stopped: subcommand failed.
=> ERROR: pulseeffects-3.1.6_1: failed to run do_build() at line 67.
````

**Comment by wwmm** [comment]
There was no change that would affect the build. Only optional plugins addition. Build is fine here on Arch Linux. The code related to the files `data/com.github.wwmm.pulseeffects.desktop ` and most of the other files in `data` folder haven't changed in months.

Did you upgrade meson or any other PulseEffects dependency?

**Comment by cr6git** [comment]
Thanks! Investigating...

**Comment by cr6git** [comment]
I guess the problem was [proot](https://github.com/voidlinux/void-packages#proot1)...

Solved now. Package built without error! 😃
