### ISSUE TITLE
Help on ElementaryOS

### ISSUE THREAD

**Issue by TCMiranda** [wwmm/pulseeffects#149]
Hey, I'm new at elementary, but I know it's based on ubuntu.
So I tried both debian .deb repository and source without success.

When I try to install from the repository:
```
The following packages have unmet dependencies:
 pulseeffects : Depends: gstreamer1.0-plugins-bad (>= 1.12) but 1.8.3-1ubuntu0.2 is to be installed
                Depends: gstreamer1.0-plugins-good (>= 1.12) but 1.8.3-1ubuntu0.4 is to be installed
                Depends: python3-scipy (>= 0.18) but 0.17.0-1 is to be installed
                Recommends: liblilv-0-0 but it is not going to be installed
                Recommends: calf-plugins but it is not going to be installed
```

When trying to build it (the output is bigger so I wont paste it all, only the part where I think the problem is reported):
```
...
Reading state information... Done

Correcting dependencies...Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) pulseeffects-build-deps [ amd64 ] < 3.0.7.3 > ( devel )
Broken pulseeffects-build-deps:amd64 Depends on libgstreamer1.0-dev [ amd64 ] < 1.8.3-1~ubuntu0.1 > ( libdevel ) (>= 1.12)
  Removing pulseeffects-build-deps:amd64 because I can't find libgstreamer1.0-dev:amd64
Done
 Done
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0

Done
The following packages will be REMOVED:
...
```

Someone could help me out?
Thanks!

**Comment by wwmm** [comment]
You are not being able to install the .deb package because your system has old libraries. Try to see if Elementary has an additional repository with newer versions of GStreamer and python-scipy

**Comment by DroWnThePoor** [comment]
@TCMiranda I have PulseEffects running on Elementary OS Loki, It's older version so only has the original functions of PE, and the spectrum visualizer does not work. I know I had to manually install some Python packages. Have you tried the Flatpak install?

**Comment by TCMiranda** [comment]
Thanks @wwmm

@DroWnThePoor I didn't, but recently I managed to make it work by adding some Zesty repos + the help of aptitude to adapt some versions.

I've also found that old version and it works here too.
For reference, it is available [here](http://www.omgubuntu.co.uk/2017/06/install-pulse-effects-ubuntu-ppa)
