### ISSUE TITLE
Cannot run in Debian SID

### ISSUE THREAD

**Issue by Ygarr** [wwmm/pulseeffects#15]
GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects

(pulseeffects:18197): dconf-WARNING **: unable to open file '/etc/dconf/db/local': /etc/dconf/db/local: invalid gvdb header; expect degraded performance
09:26:49.840 - PulseEffects - INFO - pulseaudio context started
09:26:49.840 - PulseEffects - INFO - pulseaudio version: 10.0
09:26:49.840 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
09:26:49.840 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
09:26:49.842 - PulseEffects - INFO - default pulseaudio sink sampling rate: 48000 Hz. We will use the same rate.
09:26:49.842 - PulseEffects - INFO - loading Pulseeffects sink...
09:26:49.859 - PulseEffects - INFO - sink idx: 28
09:26:49.859 - PulseEffects - INFO - Pulseeffects sink was successfully loaded
09:26:49.859 - PulseEffects - INFO - Pulseeffects sink monitor name: PulseEffects.monitor. We will process audio from this source.
Traceback (most recent call last):
  File "./pulseeffects", line 6, in <module>
    a = Application()
  File "/media/kdiv/sabayon/home/kdiv/SOFT/pulseeffects/PulseEffects/application.py", line 51, in __init__
    self.gst = GstEffects(self.pm.default_sink_rate)
  File "/media/kdiv/sabayon/home/kdiv/SOFT/pulseeffects/PulseEffects/gst.py", line 54, in __init__
    self.pipeline = self.build_pipeline()
  File "/media/kdiv/sabayon/home/kdiv/SOFT/pulseeffects/PulseEffects/gst.py", line 147, in build_pipeline
    pipeline.add(self.limiter)
TypeError: Argument 1 does not allow None as a value

N.B.: In Antergos (Arch) works fine

**Comment by wwmm** [comment]
Hi

The lines:

pipeline.add(self.limiter)
TypeError: Argument 1 does not allow None as a value

are telling that gstreamer could not find find the swh-plugins. Check if they are installed. Also check if you have gstreamer-plugins-bad 1.0 installed.

**Comment by wwmm** [comment]
When everything is ok the command `gst-inspect-1.0 | grep -i ladspa` will have a line with `ladspa-fast-lookahead-limiter-1913-so-fastlookaheadlimiter`

**Comment by Ygarr** [comment]
Thankful to you it helped!

**Comment by wwmm** [comment]
Is it working?

**Comment by Ygarr** [comment]
Yes it is)
![2017-05-29-173616_1255x868_scrot](https://cloud.githubusercontent.com/assets/14309871/26553675/66bbddb0-4495-11e7-8169-537cee08ede7.png)

**Comment by wwmm** [comment]
Nice! :-)
