### ISSUE TITLE
State of "Enable all applications" does not save

### ISSUE THREAD

**Issue by Grelek** [wwmm/pulseeffects#150]
Reopening #133 as it's still an issue on my machine.

`uname -a`: `Linux XPS 4.14.13-1-ARCH #1 SMP PREEMPT Wed Jan 10 11:14:50 UTC 2018 x86_64 GNU/Linux`

`pacman -Qs pulseeffects`:
```
Name            : pulseeffects
Version         : 3.1.6-1
Description     : Audio Effects for Pulseaudio Applications
Architecture    : any
URL             : https://github.com/wwmm/pulseeffects
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : python  python-gobject  python-cairo  gtk3  gst-plugins-good  gst-plugins-bad  gst-python  python-numpy  python-scipy  lilv
Optional Deps   : swh-plugins: limiter, output limiter and compressor plugins [installed]
                  calf: exciter, bass enhancer and stereo enhancer plugins
                  zam-plugins-git: maximizer plugin
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 928.00 KiB
Packager        : Unknown Packager
Build Date      : Wed 03 Jan 2018 07:13:44 PM CET
Install Date    : Wed 03 Jan 2018 07:13:44 PM CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

And I use KDE Plasma.

**Comment by wwmm** [comment]
Are you running PE as a service?

**Comment by Grelek** [comment]
Yes, I forgot to mention that... I tried looking up in the preset config but couldn't find such an option in there.

**Comment by wwmm** [comment]
This option is not saved to the presets. Only effects parameters are.

I found the source of the problem and it only happens when running as service. I will fix that in PE 3.1.7

**Comment by Grelek** [comment]
Thanks a lot! Looking forward for the update. :)

**Comment by wwmm** [comment]
I have just release PE 3.1.7. At least here the issue is gone. Feel free to reopen if the problem persists
