### ISSUE TITLE
Resizable window

### ISSUE THREAD

**Issue by filat0ff** [wwmm/pulseeffects#152]
Please, make window to decrease it size

**Comment by wwmm** [comment]
I don't think this is going to be possible as the widgets have a minimum size. And using scrolls at the top level does not seem an elegant solution

**Comment by servimo** [comment]
Possible to resize at least the spectrum inside de app to a fixed vertical size?

**Comment by wwmm** [comment]
I didn't understand. Do you want to keep the spectrum with the same height as you resize the window or do you want to decrease its height?

**Comment by servimo** [comment]
I want to decrease is height. When I did a resize to see all controls in a window, it proportionally to the size of the window change is height.  It's not possible to resize it. 
It occupies much of the window

**Comment by servimo** [comment]
<a href="https://i.imgur.com/10wREzG.png">
  <img src="https://imgur.com/10wREzGl.png" />
</a>

**Comment by wwmm** [comment]
Ok. Indeed it is horrible. I think I will just force the spectrum widget to keep its initial height while the window is resized. It is way easier than to offer a separate resize mode just for it

**Comment by wwmm** [comment]
The spectrum widget in master branch has fixed size. 
I don't think we can make the window smaller. Closing
