### ISSUE TITLE
How to run PulseEffects in the background without having application window opened?

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#154]
How to run PulseEffects in the background without having application window opened?

**Comment by DissCent** [comment]
You can open the settings in the upper right corner and check the option to enable the startup on login as a daemon. You may need to log out and back in after that.

**Comment by wwmm** [comment]
Something to have in mind is that this does not work in the flatpak.

![screenshot from 2018-02-03 12-10-43](https://user-images.githubusercontent.com/16225172/35767910-866862c2-08db-11e8-9787-abe06e51edbf.png)

**Comment by teneri66** [comment]
Okay, so it works in version 3.2.0 from http://ppa.launchpad.net/mikhailnov/pulseeffects/ubuntu
Thank you.
