### ISSUE TITLE
Changing sound volume causes distortions

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#155]
Changing sound volume causes distortions.
Works fine if PulseEffects disabled.

**Comment by teneri66** [comment]
How to debug to provide more details?

**Comment by wwmm** [comment]
Try to follow the steps at [Reporting-Bugs](https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs). Volume distortions could be caused by audio clipping. Do any of the plugins level meters are at their maximum values when there is distortion?
