### ISSUE TITLE
Pulseeffects drains battery when no sound is playing at all

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#158]
Pulseeffects and pulseaudio drain battery when no sound is playing at all.

Excerpt from "powertop" output:
  
      11.5 W     77,3 ms/s     602,6        Process        /usr/bin/pulseaudio --start --log-target=syslog
      11.4 W    134,3 ms/s     597,6        Process        python3 /usr/bin/pulseeffects

After I close Pulseeffects window the problem is gone.

**Comment by wwmm** [comment]
Hi. Is there any app shown in PulseEffects window when this happen? I am asking because as the code is right now gstreamer pipeline is put in the playing state whenever an app is visible in PE window. Even if the app is not playing sound

**Comment by teneri66** [comment]
Seems to be no longer an issue with PulseEffects 3.2.0 installed from http://ppa.launchpad.net/mikhailnov/pulseeffects/ubuntu repository.
I probably tried with older 1.x version.

**Comment by wwmm** [comment]
Good to know :) I made some improvements in this regard in PE 3.2.0. Now it checks if there is a least one apps playing audio before putting the pipeline in the playing state. This should save battery when the user has an application paused

**Comment by teneri66** [comment]
I can confirm that application goes away (after around 10 seconds) in PulseEffects app if it's audio was paused.

Thank you!
