### ISSUE TITLE
Request: crystality plugin

### ISSUE THREAD

**Issue by lumio83** [wwmm/pulseeffects#159]
Is it possible to include crystality plugin - to restore bad quality recordings ? It's old but I think useful.  It's there in v.0.92 http://mirror.sobukus.de/files/grimoire/audio-plugins/

**Comment by wwmm** [comment]
Unfortunately it is not possible to add xmms plugins. Only plugins that work with GStreamer can be added. Besides native GStreamer plugins you can take a look at Ladspa and LV2 plugins as most of them also work in GStreamer.
