### ISSUE TITLE
[Request] Switch presets through command line options

### ISSUE THREAD

**Issue by knochenhans** [wwmm/pulseeffects#167]
Hi,

A way to load presets on the fly via the command line would be great. I’m regularly switching between speakers and headphones with different settings and this would make is possible to automate this via a bash script.

Thanks!

**Comment by wwmm** [comment]
Hi! I will try to add this in the next version.

**Comment by wwmm** [comment]
Code in master branch is capable of loading presets from command line. Run `pulseeffects --help` to see the available options
