### ISSUE TITLE
Select "Enable All Applications" and "Start Service at Login" by default if PulseEffects installed?

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#168]
What about making "Enable All Applications" and "Start Service at Login" by default if PulseEffects is installed. Let's assume that if user installed PulseEffects then they want it enabled right away, right? No point in having those additional clicks. Just all they need to is to configure as they like.

**Comment by cshapeshifter** [comment]
That would be up to the distribution package maintainers to decide. Some distros explicitely don't want newly installed applications to be enabled by default. Me, personally, I prefer it the way it is now.

**Comment by wwmm** [comment]
I also think that this should be decided by the distribution maintainers.
