### ISSUE TITLE
Background service does not start after it's killed

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#171]
Background service does not start after it's process terminated. Does it work via systemd or implemented somehow differently?

I tried opening PulseEffects and toggle "Start Service at Login" but it does not help.

Version 3.2.0 installed from http://ppa.launchpad.net/mikhailnov/pulseeffects/ubuntu

**Comment by wwmm** [comment]
The service is started only at login by the desktop file `~/.config/autostart/pulseeffects-service.desktop`. If you want to restart it by hand you will have to execute PE as `pulseeffects --gapplication-service`

**Comment by teneri66** [comment]
Are you expecting having pulseeffects into systemd eventually? Should we add something for this into the issue queue?

**Comment by wwmm** [comment]
At this moment the workflow in PE is not a good fit to systemd. We need a running instance of Pulseaudio before starting PE but usually Pulseaudio is started per user after he/she logins. Because of this a system wide PE start service will not make sense.
