### ISSUE TITLE
No sound because "PulseEffects(mic)" is by default for some reason

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#173]
For some reason after opening PulseEffects the following happens:
![no sound because mic is by default for some reason](https://user-images.githubusercontent.com/20180419/36545470-9d928e44-17f1-11e8-9895-8bf08807b95b.png)
"PulseEffects(mic)" is enabled.

The workaround is to first change to "Built-in Audio Analog Stereo", then to "PulseEffects(apps)". If changing just to "PulseEffects(apps)" it does not help - still no sound.

What the problem could be?

Version 3.2.0 installed from http://ppa.launchpad.net/mikhailnov/pulseeffects/ubuntu repository.
Plasma 5.12.2, Kubuntu 17.10.

**Comment by wwmm** [comment]
Take a look at points `3,4, and 5` at [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ). KDE needs the module `module-device-manager` and the latest ubuntu loads by default the module `module-switch-on-connect`. At this moment both modules conflict with PE. Pulseaudio developers are aware of this issue and have already fixed these modules. But till they release Pulseaudio's next version these modules will have to be unloaded before starting PE

**Comment by teneri66** [comment]
Sorry, I have forgotten about this problem. Any ideas on how to automate this so it works on system start-up?

**Comment by wwmm** [comment]
No problems :) Module `module-switch-on-connect` can be disabled by comment or deleting its line at the file `/etc/pulse/default.pa`. Disabling the module `module-device-manager` is a little more elaborated. You can comment the relevat lines at the file `/usr/bin/start-pulseaudio-x11` or put the command `pactl unload-module module-device-manager` in you bashrc `~/.bashrc`

**Comment by teneri66** [comment]
Yeah, that makes sense. What do you think about adding the note for users on how to automate this into these FAQ items?

**Comment by wwmm** [comment]
No problems. Feel free to improve the relevant points at FAQ with this info. As I do not use ubuntu or kde I can't test this

**Comment by teneri66** [comment]
Will do. Thanks.

**Comment by teneri66** [comment]
Even after applying the workaround if I toggle the switch it does not change to default output:
![if disable app it s not reflected in audio volume](https://user-images.githubusercontent.com/20180419/36553791-f4d5a3b2-1805-11e8-9573-c639dd1d821c.png)

It only works from "Audio Volume" -> "Applications":
![audio volume works](https://user-images.githubusercontent.com/20180419/36553881-2fa30386-1806-11e8-9205-b6bde66937df.png)

**Comment by wwmm** [comment]
I didn't understand. When you turn on the switch chromium should be moved from `Built-in Audio Analog Stereo` to `PulseEffects(apps)`. Are you sure the modules were unloaded when you started PulseEffects? You can see loaded modules with the command `pactl list modules short`

**Comment by SyllableZero** [comment]
hello, i got no sound in ubuntu 20.04. modules were unloaded and i have no idea to fix it up
pulse audio version 13.xx
installed from flatpak

**Comment by wwmm** [comment]
@SyllableZero Pulseaudio `13` does not have this problem. Assuming you did not do that by mistake a third party tool is the cause. PulseEffects can not set its own virtual devices as default.

**Comment by wwmm** [comment]
>It looks llike i'm having the same problem, i'm using gnome debian 22 and everytime i remove my headphone jack the default output device are changed to pulseeffects(mic). If pulseeffects are not open the audio works as intended.

Maybe if you remove the files inside `~/.config/pulse/` and reboot Pulseaudio will forget it ever set PulseEffects sink as default. As long as you do not do this yourself it should not set PulseEffects sinks as default again.
