### ISSUE TITLE
[FAQ] "Stereo Spread" settings are disabled, why?

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#174]

**Comment by wwmm** [comment]
Assuming you have Calf Studio plugins and Lilv installed the reason is a bug in GStreamer. Take a look at point `6` at [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ).

**Comment by wwmm** [comment]
Another possibility is that your Calf package is too old. A few plugins are only available in `calf 0.90`

**Comment by daboross** [comment]
Thanks! Installing `liblilv-0-0` on Ubuntu 17.10 fixed this for my installation of pulseeffects from a PPA. Awesome tool!
