### ISSUE TITLE
problems with Flatpak package in Debian Stretch

### ISSUE THREAD

**Issue by jimcook2** [wwmm/pulseeffects#178]
I couldn't install PulseEffects in Debian Stretch from the PPA because of dependency conflicts. And so I installed the Flatpak package. 

But there were errors when I started it:

    jim@debian:~$ flatpak -v run com.github.wwmm.pulseeffects
    XA: No installations directory in /etc/flatpak/installations.d. Skipping
    XA: Disallowing network access
    XA: Allowing x11 access
    XA: Allowing wayland access
    XA: Allowing pulseaudio access
    
    ** (pulseeffects:3): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-38EiEHcoM2: Connection refused
    
    (pulseeffects:3): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
    
    [many PulseEffects INFO lines redacted]
    
    (pulseeffects:3): dconf-WARNING **: failed to commit changes to dconf: Could not connect: No such file or directory
    
    [same message repeated five more times]
    
    02:38:13.294 - PulseEffects - INFO - apps: spectrum was enabled
    02:38:13.294 - PulseEffects - INFO - mic: spectrum was enabled
    
    (pulseeffects:3): dconf-WARNING **: failed to commit changes to dconf: Could not connect: No such file or directory
    
    (pulseeffects:3): dconf-WARNING **: failed to commit changes to dconf: Could not connect: No such file or directory
    02:38:13.547 - PulseEffects - INFO - pipeline state: ready
    02:38:13.573 - PulseEffects - INFO - pipeline state: playing
    02:38:13.579 - PulseEffects - INFO - pulsesrc latency-time [us]: 10000
    02:38:13.579 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
    02:38:13.584 - PulseEffects - INFO - pulsesink latency-time [us]: 10000
    02:38:13.585 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000

But the PulseEffects GUI is up, and with Rhythmbox playing an mp3, I see a spectrum, plus new output in terminal:

    02:40:30.84 - PulseEffects - INFO - pipeline state: playing
    02:40:54.284 - PulseEffects - INFO - pipeline state: playing
    02:40:54.595 - PulseEffects - INFO - pipeline state: playing

But when I go to the Equalizer tab, and hit the ON button, I see no effect. But in terminal, I do see this:

    02:44:58.566 - PulseEffects - INFO - apps: equalizer bin was enabled
    
    (pulseeffects:3): dconf-WARNING **: failed to commit changes to dconf: Could not connect: No such file or directory
    02:44:58.571 - PulseEffects - INFO - apps: equalizer bin was disabled
    02:45:36.0 - PulseEffects - INFO - pipeline state: playing

What might I do to fix this?

**Comment by wwmm** [comment]
The dconf error messages suggest that the database file where the settings are stored does not exists. How did you install the flatpak package? Did you try to reinstall it? Are you running it as root? Do you have a `.config/dconf` folder in you home?

@AsavarTzeth may know what is happening

**Comment by jimcook2** [comment]
Thank you.

I was writing a long reply. But after rebooting, it works. The clearest test was the high pass filter. So neglecting to reboot after installing was likely the problem.

Most recently, I installed as jim:

    jim@debian:~$ flatpak install flathub com.github.wwmm.pulseeffects

And I'm running as jim. However, even though it works, I still see the dbus socket error:

    jim@debian:~$ flatpak -v run com.github.wwmm.pulseeffects
    XA: No installations directory in /etc/flatpak/installations.d. Skipping
    XA: Disallowing network access
    XA: Allowing x11 access
    XA: Allowing wayland access
    XA: Allowing pulseaudio access
    XA: Running 'bwrap --args 20 /usr/lib/flatpak/flatpak-dbus-proxy --fd=18 unix:path=/run/user/1000/bus /run/user/1000/.dbus-proxy/session-bus-proxy-WV8CFZ --filter --own=com.github.wwmm.pulseeffects --own=com.github.wwmm.pulseeffects.* --talk=ca.desrt.dconf --talk=org.freedesktop.portal.*'
    
    ** (pulseeffects:3): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-6bQY3HMTfj: Connection refused

And there's a different socket file in /tmp:

    jim@debian:~$ ls -lah /tmp
    total 56K
    drwxrwxrwt 14 root root 4.0K Feb 28 22:18 .
    drwxr-xr-x 23 root root 4.0K Feb 27 02:56 ..
    drwx------  2 jim  jim  4.0K Feb 28 22:18 firefox-esr_jim
    drwxrwxrwt  2 root root 4.0K Feb 28 22:00 .font-unix
    drwxrwxrwt  2 root root 4.0K Feb 28 22:00 .ICE-unix
    drwx------  2 root root 4.0K Feb 28 22:00 pulse-PKdhtXMmr18n
    ...

**Comment by AsavarTzeth** [comment]
Did you install `flatpak` during the same session when you experienced the dconf errors?

Sometimes when you first install flatpak itself a reboot may be required.

This issue may be relevant: https://github.com/flatpak/flatpak/issues/1256

After your reboot everything looks normal to me. The accsessibility bus can't be used because its not allowed by sandbox.

I believe you can find more information about the accessibility issue here: https://github.com/flatpak/flatpak/issues/79).

**Comment by jimcook2** [comment]
Yes, I installed flatpak, and then PulseEffects, and then tried to use PulseEffects, all in the same session. And indeed, this was my first flatpak install, so I had no clue about rebooting.

Also, thanks for pointing to the information about the accessibility bus for flatpak apps. To be honest, I just didn't realize what sort of "accessibility" this was about. Now it all makes sense.
