### ISSUE TITLE
[Request] Effects documentation

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#181]
I have never worked with sound effects before, and it is not easy to understand the purpose of each effect in Pulseeffects. I suggest to include some links to online documentation (e.g. GStreamer documentation) of the effect/plugin in the GUI. At least, understanding which e.g. gstreamer plugin is used will easify further understanding of the effect. 
Probably also print a link to the file from where the effect is loaded or not loaded in the console output (it will make it easier to find out which package each plugin belongs to and find documentation and write dependencies)

**Comment by wwmm** [comment]
I hope to have time to add this to the wiki someday. But most of the available documentation can be found in these links:

[https://calf-studio-gear.org/doc/index.html](https://calf-studio-gear.org/doc/index.html)
[https://calf-studio-gear.org/](https://calf-studio-gear.org/)
[http://lsp-plug.in/?page=manuals](http://lsp-plug.in/?page=manuals)
