### ISSUE TITLE
[Request] WebRTC audio processing

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#182]
WebRTC library can be used for audio processing in PulseAudio

https://cgit.freedesktop.org/pulseaudio/webrtc-audio-processing/tree/README.md and https://www.archlinux.org/packages/extra/x86_64/webrtc-audio-processing/ - I don't know what it is :)

Echo cancellation in PulseAudio using WebRTC library (or code taken from there): https://github.com/alfredh/baresip/wiki/Using-PulseAudio:-module-echo-cancel

https://arunraghavan.net/2016/05/improvements-to-pulseaudios-echo-cancellation/

I think that echo cancelling effect can be made from this. Echo cancelling is also used to reduce microphone static noise. I have not studies which other audio processing methods are available there.

**Comment by mikhailnov** [comment]
```
$ apt-cache rdepends libwebrtc-audio-processing1
libwebrtc-audio-processing1
Reverse Depends:
  libwebrtc-audio-processing-dev
  gstreamer1.0-plugins-bad
  pulseaudio

```

**Comment by wwmm** [comment]
As PE is right now it is better to use the GStreamer plugin [webrtcdsp](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad-plugins/html/gst-plugins-bad-plugins-webrtcdsp.html). I will try to add it in the next version. But as I didn't understand yet how its  echo cancellation probe is supposed to be used in the code this may take some time.

**Comment by wwmm** [comment]
Master branch has GStreamer's webrtcdsp plugin. There is still room for improvement in the echo probe setup but I think it is usable. At least here I can see it removes the audio feedback noise when the mic is in front of the speakers.

**Comment by mikhailnov** [comment]
Thank you very much. I will test it a bit later. Updated PPA to version 3.2.3.
