### ISSUE TITLE
Will there be AppImage?

### ISSUE THREAD

**Issue by kevinsmia1939** [wwmm/pulseeffects#184]
I'm stuck with old version of pulseeffects because I'm using ubuntu 16.04. Flatpak only let me install up to version 3.0.6 , will appimage solve this problem?

**Comment by wwmm** [comment]
Someone in the community will have to do it. Besides the fact I have never used AppImage I am already maintaining the Arch Linux package.

**Comment by mikhailnov** [comment]
18.04 is a new LTS release where pulseeffects does work from the PPA https://github.com/wwmm/pulseeffects/wiki/Package-Repositories#debian--ubuntu

**Comment by AlmightyFloppyFish** [comment]
AppImages are problematic since they bundle dependencies into the package itself, which is not the unix way. It's extremely wasteful to install programs that way
