### ISSUE TITLE
Weird, random, CPU usage

### ISSUE THREAD

**Issue by ptkato** [wwmm/pulseeffects#185]
For some reason, sometimes (seems to be random), pulseeffects grabs a whole thread for itself and only goes away if I kill it and launch it again.

![screenshot from 2018-03-14 13-50-51](https://user-images.githubusercontent.com/10677806/37417401-fd301d42-278e-11e8-8fa2-70e413c51cf3.png)

**Comment by wwmm** [comment]
This is something I never saw. Do you see anything unusual in the system log when this happens? You can try to view the log with `journalctl -b | grep -i pulse`

**Comment by wwmm** [comment]
Does it works when the cpu is at 100 % or there is no sound at all?

**Comment by ptkato** [comment]
It works fine, about the journal, didn't find anything: https://pastebin.com/S8QxQAY8.

**Comment by wwmm** [comment]
There are a few problems in your log:

`Failed to register: Unable to acquire bus name 'com.github.wwmm.pulseeffects'`
`PulseEffects - CRITICAL - context operation failed!!`

A failure in one of Pulseaudio context operation is not good. I still don't know what could have caused it but it may be a side effect of the failure in acquiring the dconf bus name. PulseEffects uses dconf everywhere to save each plugin parameters. How did you install PulseEffects? It is very strange to have errors in dconf.  

I also noticed that there are lots of lines with:

`created stream for sink input`

How many audio applications do you have open at the same time? Based on the amount of created streams it seems that there is a lot.

In any case try to follow the steps at [Reporting-Bugs](https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs). Maybe there is something else going on that is not being shown in PE logs

**Comment by ptkato** [comment]
Oh, sure, but usually I only have Firefox and GNOME-Twitch up.

I use Arch Linux + Xmonad and installed PulseEffects from the AUR. Command outputs:
[pactl list short](https://pastebin.com/hN49yiqb)
[pacmd list-sinks](https://pastebin.com/ymxL1Gp2)
[pacmd list-sink-inputs](https://pastebin.com/zdYU7iQK)
[pacmd list-sources](https://pastebin.com/W3hnMFBc)
[pacmd list-source-outputs](https://pastebin.com/KkDfA2ka)

And the pavucontrol screenshots:

![screenshot from 2018-03-14 22-59-21](https://user-images.githubusercontent.com/10677806/37440445-7dd90840-27db-11e8-869e-ea0d8fcffbd5.png)
![screenshot from 2018-03-14 22-59-34](https://user-images.githubusercontent.com/10677806/37440446-7dfb2dbc-27db-11e8-82ca-f45b691af793.png)
![screenshot from 2018-03-14 22-59-45](https://user-images.githubusercontent.com/10677806/37440447-7e21fc44-27db-11e8-87c5-7c20d5ea5dda.png)
![screenshot from 2018-03-14 22-59-53](https://user-images.githubusercontent.com/10677806/37440448-7e47a9c6-27db-11e8-83f6-5bd3d8d04b23.png)
![screenshot from 2018-03-14 23-00-02](https://user-images.githubusercontent.com/10677806/37440449-7e69bc1e-27db-11e8-910e-247ee426800c.png)

**Comment by ptkato** [comment]
It occurred twice today, any news on this issue?

**Comment by wwmm** [comment]
No news. This is one of the bugs that has been hard to catch. At least when the window is open they seem to be related to problems in the code that creates the app level meter shown in PE window. But it is not clear what could cause this when the window is closed.

At this moments my efforts are in the port of PE to c++. Hopefully it will be easier to debug these problems in this version

**Comment by wwmm** [comment]
Is this still a problem in PE 4?

**Comment by ptkato** [comment]
I can't really tell, but it didn't seem to happen after I upgraded to PE4.

**Comment by sandikata** [comment]
It happens, pulseeffects causing cpu usage.

**Comment by sandikata** [comment]
No updates yet?!?! High cpu usage at all, no matter what plugins enabled, even if disabled, -> high cpu usage.

**Comment by wwmm** [comment]
Well... I can't reproduce this issue since I removed many months ago the level meters that used to be in the application section.

I suggest you open a new issue with logs and print screens of what you mean by high cpu usage. This probably depends on the CPU model. On my ryzen 2700 PulseEffects CPU usage is around 15% in a scale that goes to 1600%

**Comment by sandikata** [comment]
FX8320, about 80% up to 100% and even choppy sound, and then sound is lost completely.

**Comment by sandikata** [comment]
![Снимка от 2019-07-27 21-37-14](https://user-images.githubusercontent.com/884699/61998315-d4120d00-b0b6-11e9-8dfe-d47014233131.png)

take a look.. this is on idle. But if there is some minimal load, it raise up to 100% and sound loss.

**Comment by wwmm** [comment]
If there is no app playing audio out pipeline should be paused. Kill the current instance `pulseefects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects` so we can see the logs.
