### ISSUE TITLE
[flatpak] Impossible to import presets

### ISSUE THREAD

**Issue by glaubersm** [wwmm/pulseeffects#195]
Hi
I installed pulseeeffects on Arch Linux (Gnome 3.28) via flatpak/flathub.
It's impossible to import presets because dialog to open files shows no file in my home and bookmarks in sidebar are missing.

![captura de tela de 2018-03-29 13-41-35](https://user-images.githubusercontent.com/15967631/38101739-900b366e-3357-11e8-8705-01d88395a13b.png)

**Comment by wwmm** [comment]
This is happening because of flatpak sandboxing. Flatpak Applications have very limited access to user files. I think it is possible to force this access permission but would weaken the security flatpak apps are supposed to have. @AsavarTzeth may know if flatpak has some kind of solution to this

**Comment by AsavarTzeth** [comment]
Actually, while all you say is true, these days this should work thanks to [Portals](https://github.com/flatpak/flatpak/wiki/Portals), also see: 

- [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal).
- [xdg-desktop-portal-gtk](https://github.com/flatpak/xdg-desktop-portal-gtk)

In this case file access is integrated with the `Gtk.FileChooser` interface (used by `Gtk.FileChooserDialog`). By selecting a file you are effectively trusting the app with that file and it is made accessible inside the sandbox. This is similar to how things work on modern Android.

In the background the portal framework has made the file you selected available somewhere under `/run/user/$UID/doc`. This makes it possible to restrict access to only that one file you need.

@wwmm The import process simply opens a file and saves a copy in the xdg config dir, right? I am not missing anything? Based on what I know it should already be working, but my programming skills are very limited.

**Comment by wwmm** [comment]
Yes. It is just opening a file and saving it in a path starting with `GLib.get_user_config_dir()`. Looking at the user image it seems that `Gtk.FileChooserDialog` is unable to see files in his home.

**Comment by AsavarTzeth** [comment]
Yes, I verified as much on my own system. For whatever reason the portal system I mentioned isn't used.

The result is that access is instead limited to inside the sandbox where $HOME is set to `~/.var/com.github.wwmm.pulseeffects`.

Perhaps asking about this on #flatpak irc would give some answers.

**Comment by AsavarTzeth** [comment]
I thought about this some more and I have a theory. The GTK implementation of the document portal is called `GtkFileChooserNativePortal`. Source code: [gtkfilechoosernativeportal.c](https://github.com/GNOME/gtk/blob/master/gtk/gtkfilechoosernativeportal.c).

Even though this is not my area of expertise, it could be that the portal can only be used via the [`GtkFileChooserNative`](https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html) API. It would make a lot of sense, since portals are supposed to integrate with other desktop environments too.

**Comment by AsavarTzeth** [comment]
I just confirmed my theory. It is clearly there in the documentation: [`GtkFileChooserNative`](https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html). Not sure how I missed it earlier.

> "When the application is running in a sandboxed environment without direct filesystem access (such as Flatpak), GtkFileChooserNative may call the proper APIs (portals) to let the user choose a file and make it available to the application."

I got a patch for this already. You can expect a pull request shortly.

**Comment by glaubersm** [comment]
Since latest flatpak update dialog to import presets is not opening on Gnome.

**Comment by AsavarTzeth** [comment]
I would say your distribution versions of `flatpak`, `xdg-desktop-portal` and `xdg-desktop-portal-gtk` might be too old. But you did say you were using Arch Linux.

On an up-to-date system everything should currently be working.

**Comment by glaubersm** [comment]
Ref: runtime/org.gnome.Platform/x86_64/3.28
ID: org.gnome.Platform
Arq.: x86_64
Ramo: 3.28
Origem: flathub
Collection ID: 
Date: 2018-04-05 03:24:17 +0000
Subject: build of org.gnome.Sdk, Thu Apr  5 01:37:22 UTC 2018
Commit: e96e5aa0280cf4415d2a6613624f9ed4177c45c66575eec796298c75099e8500
Parent: cc84d83517af38e56796b2052d9608cf783375c9208cb194e700b395cdb3da83
Localização: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.28/e96e5aa0280cf4415d2a6613624f9ed4177c45c66575eec796298c75099e8500
Tamanho instalado: 787,7 MB


Ref: app/com.github.wwmm.pulseeffects/x86_64/stable
ID: com.github.wwmm.pulseeffects
Arq.: x86_64
Ramo: stable
Origem: flathub
Collection ID: 
Date: 2018-04-03 20:41:59 +0000
Subject: pulseeffects: Use GtkFileChooserNative (34203e51)
Commit: 29533e338da6deba3fba20872dda0750a2390140f4a355fd355f1d32793de8fa
Parent: f44f0beeb10affdb88d128c6444fe0e734f7bcadedd199ff1d786b9a3481da87
Localização: /var/lib/flatpak/app/com.github.wwmm.pulseeffects/x86_64/stable/29533e338da6deba3fba20872dda0750a2390140f4a355fd355f1d32793de8fa
Tamanho instalado: 96,8 MB
Runtime: org.gnome.Platform/x86_64/3.28
