### ISSUE TITLE
Installing from source on Fedora 27 Mate/Compiz

### ISSUE THREAD

**Issue by bswarm9568** [wwmm/pulseeffects#196]
After following the Fedora instructions at https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source, pulseeffects doesn't open. I'm getting the following when running pulseeffects in a terminal...

$ pulseeffects
09:49:07.26 - PulseEffects - WARNING - Exciter plugin was not found. Disabling it!
09:49:07.27 - PulseEffects - WARNING - Bass Enhancer plugin was not found. Disabling it!
09:49:07.27 - PulseEffects - WARNING - Delay plugin was not found. Disabling it!
09:49:07.28 - PulseEffects - WARNING - Stereo Enhancer plugin was not found. Disabling it!
09:49:07.28 - PulseEffects - WARNING - Stereo Spread plugin was not found. Disabling it!
09:49:07.29 - PulseEffects - WARNING - Crossfeed plugin was not found. Disabling it!
09:49:07.32 - PulseEffects - WARNING - Maximizer plugin was not found. Disabling it!
09:49:07.58 - PulseEffects - WARNING - Pitch plugin was not found. Disabling it!
09:49:07.59 - PulseEffects - WARNING - Gate plugin was not found. Disabling it!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 236, in do_command_line
    self.do_activate()
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 212, in do_activate
    self.init_ui()
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 141, in init_ui
    self.soe.init_ui()
  File "/usr/lib/python3.6/site-packages/PulseEffects/source_output_effects.py", line 144, in init_ui
    self.gate.ui_limiter_enable.set_sensitive(False)
AttributeError: 'Gate' object has no attribute 'ui_limiter_enable'

**Comment by wwmm** [comment]
This is a bug in latest master. I will fix it now

**Comment by wwmm** [comment]
I have updated the master branch. `AttributeError: 'Gate' object has no attribute 'ui_limiter_enable'` shouldn't  happen anymore

**Comment by bswarm9568** [comment]
pulseeffects now opens and the equalizer works great, but a few others are disabled...

$ pulseeffects
10:53:14.743 - PulseEffects - WARNING - Exciter plugin was not found. Disabling it!
10:53:14.744 - PulseEffects - WARNING - Bass Enhancer plugin was not found. Disabling it!
10:53:14.745 - PulseEffects - WARNING - Delay plugin was not found. Disabling it!
10:53:14.745 - PulseEffects - WARNING - Stereo Enhancer plugin was not found. Disabling it!
10:53:14.746 - PulseEffects - WARNING - Stereo Spread plugin was not found. Disabling it!
10:53:14.746 - PulseEffects - WARNING - Crossfeed plugin was not found. Disabling it!
10:53:14.749 - PulseEffects - WARNING - Maximizer plugin was not found. Disabling it!
10:53:14.776 - PulseEffects - WARNING - Pitch plugin was not found. Disabling it!
10:53:14.776 - PulseEffects - WARNING - Gate plugin was not found. Disabling it!

**Comment by wwmm** [comment]
These plugins are optional. So this is the expected behavior when they are not installed. In case you want them take a look at the required libraries section in the [README](https://github.com/wwmm/pulseeffects) and try to find their package in fedora.
