### ISSUE TITLE
Latest master does not build

### ISSUE THREAD

**Issue by Bleuzen** [wwmm/pulseeffects#199]
I tryed building PE using makepkg on Manjaro.

Error:
`data/meson.build:2:0: ERROR: File com.github.wwmm.pulseeffects.sourceoutputs.pitch.gschema.xml does not exist.`

[meson-log.txt](https://github.com/wwmm/pulseeffects/files/1911997/meson-log.txt)

**Comment by wwmm** [comment]
A few gschema files had the wrong name. I fixed them and now meson builds.
