### ISSUE TITLE
"Start Service at Login" will not retain "on" setting

### ISSUE THREAD

**Issue by dln949** [wwmm/pulseeffects#200]
Running Ubuntu 17.10, Gnome Shell 3.26.2, x11.  

Installed PulseEffects 3.2.1 via Flatpak.  

I clicked on "Start Service at Login" to the "on" position.  However, whenever I restart my computer, PulseEffects does not start in the background, and when I open the PulseEffects window, I see that this setting is back to the "off" position.  

What is wrong, how do I fix this?  

Thanks.

**Comment by wwmm** [comment]
This only works when you installed PE using regular distribution packages like deb or rpm for example. In order to start the service at login we need to create a file in `~/.config/autostart` and flatpak apps sandboxing denies this access

**Comment by dln949** [comment]
@wwmm  Thank you for the explanation.  I uninstalled the flatpak application, and installed the debian one, and this problem no longer exists for me.

**Comment by xz-dev** [comment]
You can create a startup file yourself, as shown below.
<code>~/.config/autostart/pulseeffects-service.desktop</code>
```shell
[Desktop Entry]
Name=PulseEffects
Comment=PulseEffects Service
Exec=flatpak run com.github.wwmm.pulseeffects --gapplication-service
Icon=pulseeffects
StartupNotify=false
Terminal=false
Type=Application

```
