### ISSUE TITLE
Can't save/load preset for input limiter

### ISSUE THREAD

**Issue by pstnta** [wwmm/pulseeffects#203]
Hi,

I'm trying to save a preset on the input limiter with input gain @ 23dB, but it just won't load. I have another preset with limit @ -17dB and that one saves/loads, but boosting the input gain just won't save.

using the latest version from the arch aur.

I attached my preset, I manually edited the preset file to try and force the 23dB since it saves as 0, but it still doesn't load.

[test.preset.zip](https://github.com/wwmm/pulseeffects/files/1935052/test.preset.zip)

thanks!

**Comment by wwmm** [comment]
Indeed there is a problem when loading the input gain from the preset.  I will try to fix it

**Comment by wwmm** [comment]
fixed in PE 3.2.3
