### ISSUE TITLE
PulseEffects no sound at login

### ISSUE THREAD

**Issue by dln949** [wwmm/pulseeffects#204]
Running Ubuntu 17.10, Gnome Shell 3.26.2, x11.

Installed PulseEffects 3.2.1 via debian package.  

I selected the setting in PulseEffects to start the PulseEffects service at login.  But now, when I start my computer, there is no audio.  (Did not have that problem prior to installing PulseEffects.)  

When I start the computer and there is no audio, I go into the GNOME settings >> Sound.  In the "Output" tab I now see four devices I can choose from for sound output:  

Digital Output (S/PDIF) - Built-in Audio
Line Out - Built-in Audio
PulseEffects(apps)
PulseEffects(mic)

(The last two are new additions with the installation of PulseEffects.)  

Prior to the installation of PulseEffects, when I started my computer, the default selection was always "Line Out - Built-in Audio", and all was well.  

Now that I have installed PulseEffects, when I start the computer and there is no audio, if I look in GNOME settings >> Sound on the "Output" tab, the selected item is always "PulseEffects(mic)" - which seems wrong to me, but I don't know.  So.....  

If I switch it to "Line Out - Built-in Audio", then I do get audio - except not "through" PulseEffects.  

If instead I switch it from "PulseEffects(mic)" directly to "PulseEffects(apps)", I still get no audio.  

The only way I can get audio via PulseEffects when I start my computer is to go into the GNOME settings >> Sound >> Output, and first switch the selection from "PulseEffects(mic)" directly to "Line Out - Built-in Audio" (which enables audio, but without the benefit of PulseEffects), and then from there change the selection to "PulseEffects(apps)", which finally produces the desired audio via PulseEffects.  

Any ideas on how I can avoid having to do all that nonsense each time I start my computer?  

Thanks.

**Comment by wwmm** [comment]
Hi! This is a known problem in the latest ubuntu. Take a look at points `4 and 5` in [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ). The issue here is that ubuntu is loading by default pulseaudio's module `module-switch-on-connect`. This module has some conflicts with the null sinks PE uses. This will be fixed in the next Pulseaudio release. But until this happens you will have to unload this module or edit `/etc/pulse/default.pa` to force ubuntu to not load it

**Comment by dln949** [comment]
Thank you.  

I edited /etc/pulse/default.pa to comment out these three lines:  

#.ifexists module-switch-on-connect.so
#load-module module-switch-on-connect
#.endif

That works.....  sort of.  

Now, when I start my computer, I have sound.  But, the device that is selected is always "Line Out - Built-in  Audio".  The problem with that is if I want to hear the effects that I have selected in PulseEffects, I still need to go into GNOME settings >> Sound >> Output and change the device from "Line Out - Built-in Audio" to "PulseEffects(apps)".  

Just as a test to verify:  In PulseEffects I set the bass enhancement to some very strong values.  Then I restarted my computer.  It defaulted to the "Line Out - Built-in Audio" device, and I heard just normal bass.  When I switched the device to "PulseEffects(apps)", then I clearly heard the stronger bass effects.  

So, What might still be wrong?

**Comment by dln949** [comment]
Ok, thanks, things appear to be working now as intended.
