### ISSUE TITLE
Is the user going to be able to choose order of plugins and which ones?

### ISSUE THREAD

**Issue by zamaudio** [wwmm/pulseeffects#205]
I'm a little confused by the list in the README, for example, ZaMaximX2 is already a limiter, you dont need to put a limiter after it.  Also, if a plugin is buggy, you probably want the ability to exclude it, not to mention different people have different DSP load capacities, preferences on the order of processing and personal tastes on which plugins they want to use.

**Comment by zamaudio** [comment]
You might be better off making it a ladspa/lv2 host eg like a rack of plugins that can run any plugins that the user desires.

**Comment by wwmm** [comment]
Code in latest master allows the user to change effects order. I also removed the output limiter.
