### ISSUE TITLE
output audio has large time delay

### ISSUE THREAD

**Issue by jrudess** [wwmm/pulseeffects#207]
I am using Arch with KDE, and am back with a bizarre new problem.

All audio passing through pulseeffects is getting time-delayed by about 11s, even with all effects disabled.   As soon as I disable the program in the Applications 'tab', the audio will jump forward 11s to where the input stream is.  

This obviously makes movies unwatchable since the video and audio are so far out of sync. 

This problem started happening for me after a large update yesterday that included pulseeffects 3.2.3-1 and KDE applications 18.04.0.   I backrevved pulseeffects to 3.2.2 and 3.2.1 but the problem persists, so I believe something else I updated on arch is the culprit.

The only optional dependencies I have installed are calf and rubberband.  Do you have any suggestions on where to begin with this one?

pactl list short - https://pastebin.com/SBztAw8B
pacmd list-sinks - https://pastebin.com/X2STvnKK
pacmd list-sink-inputs - https://pastebin.com/EGv94Fms
pacmd list-sources - https://pastebin.com/ehYVxwEb
pacmd list-source-outputs - https://pastebin.com/bjYiULv6
pavucontrol screenshots - https://postimg.cc/gallery/2vr34gohi/

**Comment by wwmm** [comment]
Put here the lines printed by PE when executed as `PULSEEFFECTS_DEBUG=1 pulseeffects` too. My guess is that for some reason you have a really high value in the buffer setting found in PE main settings menu.

**Comment by jrudess** [comment]
Yeah that looks like it.  I'm not sure where the large buffer-time is coming from, because in the actual menu it displays Output Buffer = 400000us, and Input Buffer = 100000us

15:52:30.812 - PulseEffects - DEBUG - SIE - pipeline state: playing
15:52:30.812 - PulseEffects - DEBUG - PM - volume meter stream for app 27 is being created
15:52:30.813 - PulseEffects - DEBUG - PM - volume meter stream for app 27 is ready
15:52:30.821 - PulseEffects - DEBUG - SIE - pulsesrc latency-time [us]: 30000
15:52:30.822 - PulseEffects - DEBUG - SIE - pulsesrc buffer-time [us]: 11880000
15:52:30.824 - PulseEffects - DEBUG - SIE - pulsesink latency-time [us]: 30000
15:52:30.824 - PulseEffects - DEBUG - SIE - pulsesink buffer-time [us]: 11880000

**Comment by wwmm** [comment]
maybe the error recovery code I put in the latest version has bad side effects depending on user hardware. Let me know if this ever happens again even without tweaking the buffer and latency values

**Comment by jrudess** [comment]
I'm not able to change the buffer values at all from the menu so far.   Every time I reload the menu they are reset to 400000 and 100000, and the debug output still shows the 11s value.

I just upgraded my laptop from 3.2.1 straight to 3.2.3 and it now has the exact same issue.

**Comment by wwmm** [comment]
This is very strange. The dconf keys used to save buffer and latency have different names in version `3.2.1` and `3.2.3`. This buffer value should not have propagated to the older PE. Lets try something different:

- kill PE with `pulseeffects -q`
- Reset PE dconf keys with `dconf reset -f /com/github/wwmm/pulseeffects/`
- Open dconf editor and check if the buffer key has its default value:
![screenshot from 2018-04-24 23-07-26](https://user-images.githubusercontent.com/16225172/39222649-27f5cf86-4814-11e8-8460-ae3b69a275e6.png)
- Execute PE again and check if it is using the same value `PULSEEFFECTS_DEBUG=1 pulseeffects`

**Comment by wwmm** [comment]
It is very strange that you still have this large value even after resetting dconf. Maybe it somehow became the default value. When you click on the `buffer-out` key in dconf window  do you have something like this?
![screenshot from 2018-04-25 00-33-08](https://user-images.githubusercontent.com/16225172/39224940-1e1c9bc8-4820-11e8-9ed2-b9c239f7ef71.png)

You should have 100.000 as default

**Comment by jrudess** [comment]
Yeah, I do see 100 as the default.  It is only 'Current Value' that seems to be gettiung set to 11,880,000.

https://s18.postimg.cc/iartxjmex/dconf_pulseeffects.png

**Comment by jrudess** [comment]
Was going to work on debugging this more, and now I can no longer reproduce the issue with latest arch packages.
