### ISSUE TITLE
Cannot enable input limiter, compressor, excitor, bass enhancer, stereo enhancer, stereo spread, delay

### ISSUE THREAD

**Issue by kevinsmia1939** [wwmm/pulseeffects#208]
Cannot enable input limiter, compressor, excitor, bass enhancer, stereo enhancer, stereo spread, delay.
Other options work fine.
I am using Manjaro KDE and listen music with youtube.
Profile: Analog Stereo Duplex.
Is this about the audio from youtube?
Thanks

**Comment by wwmm** [comment]
is this still a problem?

**Comment by wwmm** [comment]
Which system do you have? At least here Arch Linux everything is fine. Can you see the calf plugins in the output of `gst-inspect-1.0 | grep -i calf` ?

**Comment by Paul17041993** [comment]
Running Antergos, so shouldn't be a whole lot different, but there are no calf plugins present. What specific package should I have for them?

**Comment by wwmm** [comment]
`pacman -S calf`

**Comment by Paul17041993** [comment]
mm, I half figured that's what's needed, however the description for it says it's for JACK, I'm not aware if pa-eq using that to interface with it?

**Comment by wwmm** [comment]
Calf can be used outside of JACK. And PulseEffects does not use Pulseaudio equalizer. We use GStreamer's parametric equalizer.

**Comment by Paul17041993** [comment]
woops, meant PE...
