### ISSUE TITLE
Loud Screeching

### ISSUE THREAD

**Issue by sinqbad** [wwmm/pulseeffects#209]
Ubuntu 18.04 KDE Plasma 5.12 
3.2.3-1~bionic1
https://pastebin.com/YQG3fedw
https://pastebin.com/vevUvRya
https://pastebin.com/iW7q7dvs
https://pastebin.com/SzfYM4z8
https://pastebin.com/4jYPxC7w
0 source output(s) available.

Enabled for all applications
Loading pulseeffects gives a loud screeching noise.
Headphones: when enabled screeching will always result.
Speakers: when a sound is playing and then pulseaudio is run then screeching. Running pulseeffects, enabling then loading sound eg. spotify will sometimes cause it to work.

**Comment by wwmm** [comment]
Hi. There are a few known problems with the latest ubuntu and KDE that are only going to be fixed when Pulseaudio 12 is released. until this happens you will have to apply the workarounds mentioned at points `3,4 and 5` at [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ). Maybe those problematic modules are also the source of this noise

**Comment by wwmm** [comment]
Is this still a problem?
