### ISSUE TITLE
Non-Integer Gain for Equalizer

### ISSUE THREAD

**Issue by thomasklau** [wwmm/pulseeffects#210]
Just wanting to clarify -- can the equalizer can use non-integer values of gain?

From the following config file, there are non integer values of gain but when displayed in the app, these values are rounded to the closest integer. Is this just a display thing? Pulseeffects isn't actually rounding my gain settings to integers when it is doing the equalization right?

Config file: https://github.com/gconcon/PulseEffects-presets/blob/master/Bose%20QC35.preset

**Comment by thomasklau** [comment]
![screenshot from 2018-04-25 15-39-10](https://user-images.githubusercontent.com/1696445/39276719-3e977fe2-489f-11e8-9738-e838b7922024.png)

**Comment by wwmm** [comment]
I think we can have 1 decimal place shown in the interface. I will try to remember to do that in the next release

**Comment by thomasklau** [comment]
Thanks!

**Comment by wwmm** [comment]
Implemented in latest master
