### ISSUE TITLE
Unable to launch in background with preset

### ISSUE THREAD

**Issue by ghost** [wwmm/pulseeffects#211]
Hi,

**_Latest PE from AUR_**

I'm trying to run pulseeffects in the background with a preset (vlc). Here's the error I get when i run 

pulseeffects -l vlc --gapplication-service

> Failed to register: Unable to acquire bus name 'com.github.wwmm.pulseeffects'

I also can't start the gui directly with a preset through the terminal w/ **pulseeffects -l vlc** cause I get no output, it goes right to a new prompt. If I enable debug same thing, no error..

> [p@lnx ~]$ PULSEEFFECTS_DEBUG=1 pulseeffects -l vlc

> 22:14:19.409 - PulseEffects - DEBUG - MAIN - debug logging enabled

Is there an actual log file for pulseeffects? I haven't been able to find one. Thing is, if I run it normally with the gui, the presets load and everything runs perfectly, but nothing seems to work from the terminal so I'm not too  sure where to start troubleshooting.

thanks!

**Comment by wwmm** [comment]
I am not able to reproduce the register error. Which desktop are you using? It seems like something is broken in you dconf(gsettings) installation.

Starting PE as `PULSEEFFECTS_DEBUG=1 pulseeffects` should be enough to see logs. They are printed to the terminal. At this moment they are not saved to any file.

The `-l` option is not intended to load the gui with a preset. It is used to load a preset when there is an instance of PE running as a service. In this case there is no gui available to change presets and a command line option becomes necessary. 

Any special reason to want to load the gui with a given preset? As every setting is remembered by dconf PE always loads the last used setting of every parameter when it is restarted

**Comment by pstnta** [comment]
I'm on MATE, but I also tested KDE with the same results. The problem is that the last settings are never remembered so I always have to load them, is there a way I can troubleshoot that instead? because it works when I do both separately now.

thanks for all your help :)

**Comment by wwmm** [comment]
when you execute `PULSEEFFECTS_DEBUG=1 pulseeffects` is there anything other than `Failed to register: Unable to acquire bus name 'com.github.wwmm.pulseeffects'` printed to the terminal? It may also help to run `journalctl -fb` in another terminal before starting PulseEffects to see if there are different error messages printed.

**Comment by pstnta** [comment]
this is the output of **_PULSEEFFECTS_DEBUG=1 pulseeffects_** / nothing shows up at all in **_journalctl -fb_**

07:11:22.858 - PulseEffects - DEBUG - MAIN - debug logging enabled
07:11:22.863 - PulseEffects - DEBUG - PM - pulseaudio context is connecting
07:11:22.863 - PulseEffects - DEBUG - PM - pulseaudio context is authorizing
07:11:22.863 - PulseEffects - DEBUG - PM - pulseaudio context is setting name
07:11:22.864 - PulseEffects - DEBUG - PM - pulseaudio context is ready
07:11:22.864 - PulseEffects - DEBUG - PM - connected to server: unix:/run/user/1000/pulse/native
07:11:22.864 - PulseEffects - DEBUG - PM - server protocol version: 32
07:11:22.864 - PulseEffects - DEBUG - PM - pulseaudio version: 11.1
07:11:22.864 - PulseEffects - DEBUG - PM - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
07:11:22.864 - PulseEffects - DEBUG - PM - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
07:11:22.864 - PulseEffects - DEBUG - PM - default pulseaudio sink audio format: s16le
07:11:22.864 - PulseEffects - DEBUG - PM - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
07:11:22.865 - PulseEffects - DEBUG - PM - default pulseaudio source audio format: s16le
07:11:22.865 - PulseEffects - DEBUG - PM - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
07:11:22.865 - PulseEffects - DEBUG - PM - loading Pulseeffects applications sink...
07:11:22.865 - PulseEffects - DEBUG - PM - sink owner module index: 35
07:11:22.865 - PulseEffects - DEBUG - PM - Pulseeffects apps sink was successfully loaded
07:11:22.866 - PulseEffects - DEBUG - PM - Pulseeffects apps sink index:11
07:11:22.866 - PulseEffects - DEBUG - PM - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
07:11:22.866 - PulseEffects - DEBUG - PM - loading Pulseeffects microphone output sink...
07:11:22.866 - PulseEffects - DEBUG - PM - sink owner module index: 36
07:11:22.866 - PulseEffects - DEBUG - PM - Pulseeffects mic sink was successfully loaded
07:11:22.866 - PulseEffects - DEBUG - PM - Pulseeffects mic sink index:12
07:11:22.866 - PulseEffects - DEBUG - PM - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
07:11:22.905 - PulseEffects - DEBUG - SIE - limiter wrapper was enabled
07:11:22.905 - PulseEffects - DEBUG - SIE - compressor wrapper was enabled
07:11:22.905 - PulseEffects - DEBUG - SIE - highpass wrapper was enabled
07:11:22.905 - PulseEffects - DEBUG - SIE - lowpass wrapper was enabled
07:11:22.905 - PulseEffects - DEBUG - SIE - equalizer wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - bass enhancer wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - exciter wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - stereo enhancer wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - panorama wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - stereo spread wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - reverb wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - crossfeed wrapper was enabled
07:11:22.907 - PulseEffects - DEBUG - SIE - delay wrapper was enabled
07:11:22.907 - PulseEffects - DEBUG - SIE - maximizer wrapper was enabled
07:11:22.907 - PulseEffects - DEBUG - SIE - output limiter wrapper was enabled
07:11:22.907 - PulseEffects - DEBUG - SIE - spectrum wrapper was enabled
07:11:22.921 - PulseEffects - DEBUG - SOE - gate wrapper was enabled
07:11:22.921 - PulseEffects - DEBUG - SOE - webrtc wrapper was enabled
07:11:22.921 - PulseEffects - DEBUG - SOE - limiter wrapper was enabled
07:11:22.921 - PulseEffects - DEBUG - SOE - compressor wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - highpass wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - lowpass wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - equalizer wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - deesser wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - reverb wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - pitch wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - spectrum wrapper was enabled
07:11:23.97 - PulseEffects - DEBUG - SIE - limiter bin was enabled
07:11:23.279 - PulseEffects - DEBUG - SIE - spectrum was enabled
07:11:23.279 - PulseEffects - DEBUG - SOE - spectrum was enabled
07:11:23.342 - PulseEffects - DEBUG - MAIN - using default sink
07:11:23.342 - PulseEffects - DEBUG - MAIN - using default source
07:11:23.421 - PulseEffects - DEBUG - MAIN - added sink: alsa_output.pci-0000_00_1b.0.analog-stereo
07:11:23.422 - PulseEffects - DEBUG - MAIN - output device changed: alsa_output.pci-0000_00_1b.0.analog-stereo
07:11:23.422 - PulseEffects - DEBUG - MAIN - added source: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
07:11:23.422 - PulseEffects - DEBUG - MAIN - added source: alsa_input.pci-0000_00_1b.0.analog-stereo$ PULSEEFFECTS_DEBUG=1 pulseeffects
07:11:22.858 - PulseEffects - DEBUG - MAIN - debug logging enabled
07:11:22.863 - PulseEffects - DEBUG - PM - pulseaudio context is connecting
07:11:22.863 - PulseEffects - DEBUG - PM - pulseaudio context is authorizing
07:11:22.863 - PulseEffects - DEBUG - PM - pulseaudio context is setting name
07:11:22.864 - PulseEffects - DEBUG - PM - pulseaudio context is ready
07:11:22.864 - PulseEffects - DEBUG - PM - connected to server: unix:/run/user/1000/pulse/native
07:11:22.864 - PulseEffects - DEBUG - PM - server protocol version: 32
07:11:22.864 - PulseEffects - DEBUG - PM - pulseaudio version: 11.1
07:11:22.864 - PulseEffects - DEBUG - PM - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
07:11:22.864 - PulseEffects - DEBUG - PM - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
07:11:22.864 - PulseEffects - DEBUG - PM - default pulseaudio sink audio format: s16le
07:11:22.864 - PulseEffects - DEBUG - PM - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
07:11:22.865 - PulseEffects - DEBUG - PM - default pulseaudio source audio format: s16le
07:11:22.865 - PulseEffects - DEBUG - PM - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
07:11:22.865 - PulseEffects - DEBUG - PM - loading Pulseeffects applications sink...
07:11:22.865 - PulseEffects - DEBUG - PM - sink owner module index: 35
07:11:22.865 - PulseEffects - DEBUG - PM - Pulseeffects apps sink was successfully loaded
07:11:22.866 - PulseEffects - DEBUG - PM - Pulseeffects apps sink index:11
07:11:22.866 - PulseEffects - DEBUG - PM - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
07:11:22.866 - PulseEffects - DEBUG - PM - loading Pulseeffects microphone output sink...
07:11:22.866 - PulseEffects - DEBUG - PM - sink owner module index: 36
07:11:22.866 - PulseEffects - DEBUG - PM - Pulseeffects mic sink was successfully loaded
07:11:22.866 - PulseEffects - DEBUG - PM - Pulseeffects mic sink index:12
07:11:22.866 - PulseEffects - DEBUG - PM - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
07:11:22.905 - PulseEffects - DEBUG - SIE - limiter wrapper was enabled
07:11:22.905 - PulseEffects - DEBUG - SIE - compressor wrapper was enabled
07:11:22.905 - PulseEffects - DEBUG - SIE - highpass wrapper was enabled
07:11:22.905 - PulseEffects - DEBUG - SIE - lowpass wrapper was enabled
07:11:22.905 - PulseEffects - DEBUG - SIE - equalizer wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - bass enhancer wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - exciter wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - stereo enhancer wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - panorama wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - stereo spread wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - reverb wrapper was enabled
07:11:22.906 - PulseEffects - DEBUG - SIE - crossfeed wrapper was enabled
07:11:22.907 - PulseEffects - DEBUG - SIE - delay wrapper was enabled
07:11:22.907 - PulseEffects - DEBUG - SIE - maximizer wrapper was enabled
07:11:22.907 - PulseEffects - DEBUG - SIE - output limiter wrapper was enabled
07:11:22.907 - PulseEffects - DEBUG - SIE - spectrum wrapper was enabled
07:11:22.921 - PulseEffects - DEBUG - SOE - gate wrapper was enabled
07:11:22.921 - PulseEffects - DEBUG - SOE - webrtc wrapper was enabled
07:11:22.921 - PulseEffects - DEBUG - SOE - limiter wrapper was enabled
07:11:22.921 - PulseEffects - DEBUG - SOE - compressor wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - highpass wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - lowpass wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - equalizer wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - deesser wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - reverb wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - pitch wrapper was enabled
07:11:22.922 - PulseEffects - DEBUG - SOE - spectrum wrapper was enabled
07:11:23.97 - PulseEffects - DEBUG - SIE - limiter bin was enabled
07:11:23.279 - PulseEffects - DEBUG - SIE - spectrum was enabled
07:11:23.279 - PulseEffects - DEBUG - SOE - spectrum was enabled
07:11:23.342 - PulseEffects - DEBUG - MAIN - using default sink
07:11:23.342 - PulseEffects - DEBUG - MAIN - using default source
07:11:23.421 - PulseEffects - DEBUG - MAIN - added sink: alsa_output.pci-0000_00_1b.0.analog-stereo
07:11:23.422 - PulseEffects - DEBUG - MAIN - output device changed: alsa_output.pci-0000_00_1b.0.analog-stereo
07:11:23.422 - PulseEffects - DEBUG - MAIN - added source: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
07:11:23.422 - PulseEffects - DEBUG - MAIN - added source: alsa_input.pci-0000_00_1b.0.analog-stereo
07:11:23.422 - PulseEffects - DEBUG - MAIN - input device changed: alsa_input.pci-0000_00_1b.0.analog-stereo

07:11:23.422 - PulseEffects - DEBUG - MAIN - input device changed: alsa_input.pci-0000_00_1b.0.analog-stereo

**Comment by wwmm** [comment]
I see nothing wrong in the log

**Comment by pstnta** [comment]
okay thanks

**Comment by wwmm** [comment]
Is this still a problem?
