### ISSUE TITLE
v3.2.3 Crash with Discord/RamBox

### ISSUE THREAD

**Issue by WarDogSniper** [wwmm/pulseeffects#212]
Ubuntu-MATE v17.10 

So using Flatpak all was well I had multi audio sources VLC/RamBox/Firefox and others without a problem until I upgraded that is when things went wrong. (Not sure what version I upgraded from)

I could play VLC/Firefox/Chromium without any issues. but as soon as I fired up Discord either in the app or through RamBox and went to the Voice channels that is when PulseEffects Crashed and it would not reopen until Discord was closed. 

I uninstalled Flatpak and installed via the Repo and had the same issues with crashing

I did not UpGrade PulseEffects for some time so I took a guess and built v3.2.0 & installed it and everything is back to normal. I can have multi sources again without issue.

I didn't grab any crash logs but my next step when I have time is to build the newer version and see when the problem starts to appear (v3.2.1 / v3.2.2 or if it is just 3.2.3) that gives me a problem.

not sure what logs you would need for the errors
but I thought I would let you know.
Thanks for a Great App!

**Comment by WarDogSniper** [comment]
unsure about pulseeffects --gapplication-service
Steps to Crash
1) reboot
2) load PulseEffects
3) load either Discord app or RamBox Discord
4) enter voice channel
5) crash PulseEffects
6) change my audio source back to Pulse Audio to hear anything

I currently have v3.2.0 installed and it seems to be fine (no crashes)

**Comment by WarDogSniper** [comment]
Ok More info for ya to maybe go on..

I built v3.21 & had (0)Zero problems with it then I built v3.2.2 and the problems came back
I first ran the PE app (opened MPV player playing a video & opened Rambox/Discord app)
as soon as I opened a voice channel in Discord PE Crashed

I re-ran the test the exact same way with pulseeffects --gapplication-service and it to crashed
this was the terminal output.  (Note: MPV was running at the ** mark. when I opened Discord Voice that is when it crashed)

> pulseeffects --gapplication-service
> 21:38:30.559 - PulseEffects - WARNING - Delay plugin was not found. Disabling it!
> 21:38:30.561 - PulseEffects - WARNING - Stereo Spread plugin was not found. Disabling it!
> 21:38:31.262 - PulseEffects - INFO - MAIN - Running in background
> **
> ERROR:gstspectrum.c:991:gst_spectrum_transform_ip: assertion failed: (size == 0)
> Aborted (core dumped)

so I will stick with v3.2.1 for now let me know if you need any other test run from me and I will be happy to do what I can.

**Comment by wwmm** [comment]
Which values do you have for `buffer` and `latency` times in PE settings menu? I ask because errors with `gst_spectrum_transform_ip` are usually related to forbidden latency values. Another thing that may help is executing PE as `PULSEEFFECTS_DEBUG=1 pulseeffects`. It will print more info this way.

**Comment by WarDogSniper** [comment]
v3.2.2
as fot the Values of buffer & latency are not touched so "Factory Settings"
https://kek.gg/i/4Fwphy.png 
> PULSEEFFECTS_DEBUG=1 pulseeffects
> 10:29:22.339 - PulseEffects - DEBUG - MAIN - debug logging enabled
> 10:29:22.346 - PulseEffects - DEBUG - PM - pulseaudio context is connecting
> 10:29:22.347 - PulseEffects - DEBUG - PM - pulseaudio context is authorizing
> 10:29:22.348 - PulseEffects - DEBUG - PM - pulseaudio context is setting name
> 10:29:22.348 - PulseEffects - DEBUG - PM - pulseaudio context is ready
> 10:29:22.348 - PulseEffects - DEBUG - PM - connected to server: unix:/run/user/1000/pulse/native
> 10:29:22.348 - PulseEffects - DEBUG - PM - server protocol version: 32
> 10:29:22.349 - PulseEffects - DEBUG - PM - pulseaudio version: 11.1
> 10:29:22.349 - PulseEffects - DEBUG - PM - default pulseaudio source: alsa_input.pci-0000_00_14.2.analog-stereo
> 10:29:22.349 - PulseEffects - DEBUG - PM - default pulseaudio sink: alsa_output.pci-0000_00_14.2.analog-stereo
> 10:29:22.351 - PulseEffects - DEBUG - PM - default pulseaudio sink audio format: s16le
> 10:29:22.351 - PulseEffects - DEBUG - PM - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
> 10:29:22.352 - PulseEffects - DEBUG - PM - default pulseaudio source audio format: s16le
> 10:29:22.352 - PulseEffects - DEBUG - PM - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
> 10:29:22.352 - PulseEffects - DEBUG - PM - loading Pulseeffects applications sink...
> 10:29:22.354 - PulseEffects - DEBUG - PM - sink owner module index: 34
> 10:29:22.355 - PulseEffects - DEBUG - PM - Pulseeffects apps sink was successfully loaded
> 10:29:22.355 - PulseEffects - DEBUG - PM - Pulseeffects apps sink index:8
> 10:29:22.355 - PulseEffects - DEBUG - PM - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
> 10:29:22.355 - PulseEffects - DEBUG - PM - loading Pulseeffects microphone output sink...
> 10:29:22.359 - PulseEffects - DEBUG - PM - pulseaudio version: 11.1
> 10:29:22.359 - PulseEffects - DEBUG - PM - default pulseaudio source: alsa_input.pci-0000_00_14.2.analog-stereo
> 10:29:22.359 - PulseEffects - DEBUG - PM - default pulseaudio sink: PulseEffects_apps
> 10:29:22.359 - PulseEffects - DEBUG - PM - Pulseeffects mic sink was successfully loaded
> 10:29:22.359 - PulseEffects - DEBUG - PM - Pulseeffects mic sink index:7
> 10:29:22.359 - PulseEffects - DEBUG - PM - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
> 10:29:22.401 - PulseEffects - WARNING - Delay plugin was not found. Disabling it!
> 10:29:22.404 - PulseEffects - WARNING - Stereo Spread plugin was not found. Disabling it!
> 10:29:22.411 - PulseEffects - DEBUG - SIE - limiter wrapper was enabled
> 10:29:22.411 - PulseEffects - DEBUG - SIE - compressor wrapper was enabled
> 10:29:22.411 - PulseEffects - DEBUG - SIE - highpass wrapper was enabled
> 10:29:22.412 - PulseEffects - DEBUG - SIE - lowpass wrapper was enabled
> 10:29:22.412 - PulseEffects - DEBUG - SIE - equalizer wrapper was enabled
> 10:29:22.412 - PulseEffects - DEBUG - SIE - bass enhancer wrapper was enabled
> 10:29:22.412 - PulseEffects - DEBUG - SIE - exciter wrapper was enabled
> 10:29:22.412 - PulseEffects - DEBUG - SIE - stereo enhancer wrapper was enabled
> 10:29:22.413 - PulseEffects - DEBUG - SIE - panorama wrapper was enabled
> 10:29:22.413 - PulseEffects - DEBUG - SIE - stereo spread wrapper was enabled
> 10:29:22.413 - PulseEffects - DEBUG - SIE - reverb wrapper was enabled
> 10:29:22.413 - PulseEffects - DEBUG - SIE - crossfeed wrapper was enabled
> 10:29:22.413 - PulseEffects - DEBUG - SIE - delay wrapper was enabled
> 10:29:22.414 - PulseEffects - DEBUG - SIE - maximizer wrapper was enabled
> 10:29:22.414 - PulseEffects - DEBUG - SIE - output limiter wrapper was enabled
> 10:29:22.414 - PulseEffects - DEBUG - SIE - spectrum wrapper was enabled
> 10:29:22.438 - PulseEffects - DEBUG - SOE - gate wrapper was enabled
> 10:29:22.439 - PulseEffects - DEBUG - SOE - webrtc wrapper was enabled
> 10:29:22.439 - PulseEffects - DEBUG - SOE - limiter wrapper was enabled
> 10:29:22.439 - PulseEffects - DEBUG - SOE - compressor wrapper was enabled
> 10:29:22.439 - PulseEffects - DEBUG - SOE - highpass wrapper was enabled
> 10:29:22.440 - PulseEffects - DEBUG - SOE - lowpass wrapper was enabled
> 10:29:22.440 - PulseEffects - DEBUG - SOE - equalizer wrapper was enabled
> 10:29:22.440 - PulseEffects - DEBUG - SOE - deesser wrapper was enabled
> 10:29:22.440 - PulseEffects - DEBUG - SOE - reverb wrapper was enabled
> 10:29:22.441 - PulseEffects - DEBUG - SOE - pitch wrapper was enabled
> 10:29:22.441 - PulseEffects - DEBUG - SOE - spectrum wrapper was enabled
> 10:29:22.782 - PulseEffects - DEBUG - SIE - compressor bin was enabled
> 10:29:22.785 - PulseEffects - DEBUG - SIE - exciter bin was enabled
> 10:29:22.787 - PulseEffects - DEBUG - SIE - bass enhancer bin was enabled
> 10:29:22.792 - PulseEffects - DEBUG - SIE - maximizer bin was enabled
> 10:29:22.797 - PulseEffects - DEBUG - SIE - equalizer bin was enabled
> 10:29:23.69 - PulseEffects - DEBUG - SIE - spectrum was enabled
> 10:29:23.69 - PulseEffects - DEBUG - SOE - spectrum was enabled
> 10:29:23.167 - PulseEffects - DEBUG - MAIN - using default sink
> 10:29:23.167 - PulseEffects - DEBUG - MAIN - using default source
> 10:29:23.315 - PulseEffects - DEBUG - PM - volume meter stream for app 371 is being created
> 10:29:23.316 - PulseEffects - DEBUG - PM - volume meter stream for app 371 is ready
> 10:29:23.316 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is being created
> 10:29:23.317 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is ready
> 10:29:23.319 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is being created
> 10:29:23.319 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is being created
> 10:29:23.320 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is being created
> 10:29:23.320 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is being created
> 10:29:23.323 - PulseEffects - DEBUG - PM - volume meter stream for app 392 was terminated
> 10:29:23.323 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is ready
> 10:29:23.324 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is ready
> 10:29:23.325 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is ready
> 10:29:23.325 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is ready
> 10:29:23.337 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.337 - PulseEffects - DEBUG - PM - volume meter stream for app 371 is being created
> 10:29:23.339 - PulseEffects - DEBUG - PM - volume meter stream for app 371 is ready
> 10:29:23.345 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.351 - PulseEffects - DEBUG - MAIN - added sink: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1
> 10:29:23.359 - PulseEffects - DEBUG - MAIN - added sink: alsa_output.pci-0000_00_14.2.analog-stereo
> 10:29:23.359 - PulseEffects - DEBUG - MAIN - added source: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1.monitor
> 10:29:23.360 - PulseEffects - DEBUG - MAIN - added source: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
> 10:29:23.360 - PulseEffects - DEBUG - MAIN - added source: alsa_input.pci-0000_00_14.2.analog-stereo
> 10:29:23.361 - PulseEffects - DEBUG - MAIN - input device changed: alsa_input.pci-0000_00_14.2.analog-stereo
> 10:29:23.361 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.362 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.362 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.362 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is being created
> 10:29:23.363 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is ready
> 10:29:23.393 - PulseEffects - DEBUG - SIE - pulsesrc latency-time [us]: 10000
> 10:29:23.393 - PulseEffects - DEBUG - SIE - pulsesrc buffer-time [us]: 100000
> 10:29:23.393 - PulseEffects - DEBUG - SIE - pulsesink latency-time [us]: 10000
> 10:29:23.394 - PulseEffects - DEBUG - SIE - pulsesink buffer-time [us]: 100000
> 10:29:23.483 - PulseEffects - DEBUG - SOE - pipeline state: playing
> 10:29:23.484 - PulseEffects - DEBUG - PM - volume meter stream for app 246 is being created
> 10:29:23.484 - PulseEffects - DEBUG - PM - volume meter stream for app 246 is ready
> 10:29:23.488 - PulseEffects - DEBUG - SOE - pulsesrc latency-time [us]: 45929
> 10:29:23.488 - PulseEffects - DEBUG - SOE - pulsesrc buffer-time [us]: 91859
> 10:29:23.492 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.492 - PulseEffects - DEBUG - PM - volume meter stream for app 392 was terminated
> 10:29:23.494 - PulseEffects - DEBUG - SOE - pulsesink latency-time [us]: 45929
> 10:29:23.494 - PulseEffects - DEBUG - SOE - pulsesink buffer-time [us]: 91859
> 10:29:23.494 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.494 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is being created
> 10:29:23.495 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.495 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is ready
> 10:29:23.499 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.500 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is being created
> 10:29:23.500 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.500 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is ready
> 10:29:23.501 - PulseEffects - DEBUG - PM - volume meter stream for app 392 was terminated
> 10:29:23.503 - PulseEffects - DEBUG - SIE - pipeline state: playing
> 10:29:23.503 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is being created
> 10:29:23.503 - PulseEffects - DEBUG - PM - volume meter stream for app 392 is ready
> **
> ERROR:gstspectrum.c:991:gst_spectrum_transform_ip: assertion failed: (size == 0)
> Aborted (core dumped)
>

**Comment by wwmm** [comment]
The pipeline processing microphone has strange latency and buffer values:

```
10:29:23.494 - PulseEffects - DEBUG - SOE - pulsesink latency-time [us]: 45929
10:29:23.494 - PulseEffects - DEBUG - SOE - pulsesink buffer-time [us]: 91859
```
I think that the way I am auto recovering from crashes related to bad latency values does not work well in every machine. I will have to fix that. In the mean time you may try to reset these values to:

```
buffer: 100000
latency: 10000
```

Do that when there is no audio app shown in PE window

**Comment by WarDogSniper** [comment]
> I think that the way I am auto recovering from crashes related to bad latency values does not work well in every machine. I will have to fix that. In the mean time you may try to reset these values to:
> 
> buffer: 100000
> latency: 10000

So far that seems to do the job with v3.2.3 from PPA

**Comment by WarDogSniper** [comment]
I Take that back it is still crashing

Back to v3.2.0 for me

**Comment by wwmm** [comment]
Is this still a problem in the latest version?

**Comment by WarDogSniper** [comment]
No this is No longer a problem! Sorry for the late response...

Thanks for your Great Work!
