### ISSUE TITLE
[Flatpak] missing pulseeffects-service.desktop for Service

### ISSUE THREAD

**Issue by Amosar** [wwmm/pulseeffects#213]
I have tried to run pulseeffects as a service with the option "Start Service at Login" (I don't know if it work like this) but I have this error : 

> Traceback (most recent call last):
>   File "/app/lib/python3.5/site-packages/PulseEffects/application.py", line 368, in on_enable_autostart_state_set
>     with open(self.autostart_file, 'w') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/amosar/.var/app/com.github.wwmm.pulseeffects/config/autostart/pulseeffects-service.desktop'

I use the flatpak version
This is the complete log with PULSEEFFECT_DEBUG=1
https://pastebin.com/RhpeK9ac

**Comment by wwmm** [comment]
Hi. This function does not work when PE was installed through flatpak because of its sandboxing. You will have to create an autostart file by yourself. What the menu option does is create a file named `pulseeffects-service.desktop` with:

```
[Desktop Entry]
Name=PulseEffects
Comment=PulseEffects Service
Exec=pulseeffects --gapplication-service
Icon=pulseeffects
StartupNotify=false
Terminal=false
Type=Application
```
in the directory `~.config/autostart`. You just have to modify the Exec entry with the flatpak commands used to run an app

**Comment by Amosar** [comment]
Okay thank you, can you add a warning to inform the user if the function not work?
Because the switch seem to work fine until you see that nothing happen.

**Comment by wwmm** [comment]
I will think about it. But I don't know if it will be easy to detect that. If I am not mistaken when using flatpak the file is created in the directory where the app was sandboxed. As there is no error when creating the file I do not have a feedback to give the user a warning.

**Comment by Amosar** [comment]
I think you can check if this line throw an error https://github.com/wwmm/pulseeffects/blob/master/PulseEffects/application.py#L368 and display a popup to inform the user if it not work?

**Comment by wwmm** [comment]
This will not work. The file exists. The problem is that because of flatpak sandboxing it is not created in `~/config/autostart` but in the folder where flatpak install the app files. As far as I understand flatpak creates some kind of custom home folder in the virtual environment it sets for the app.

**Comment by Amosar** [comment]
On my installation the file doesn't exist ("No such file or directory" on my first message), it why I suggest this idea.
This is the structure of the app folder with flatpak: https://pastebin.com/1qkHZDKx and GLib.get_user_config_dir() seems to return /home/<user>/.var/app/com.github.wwmm.pulseeffects/config on flatpak
I think the file haven't been create because the autostart folder doesn't exist on the flatpak container.
https://github.com/flatpak/flatpak/issues/118

**Comment by wwmm** [comment]
Ok. I thought that an autostart folder would be created by flatpak (I don't use flatpak)

**Comment by Amosar** [comment]
No problem it's why I reported the issue and tried to give the best informations. 
I am not very clear when I speak in English: /

**Comment by damian01w** [comment]
I've put manually in the directory ~/.config/autostart/pulseeffects-service.desktop and it works!

```
    [Desktop Entry]
    Name=PulseEffects
    Comment=PulseEffects Service
    #Exec=pulseeffects --gapplication-service
    Exec=flatpak run com.github.wwmm.pulseeffects --gapplication-service 
    Icon=pulseeffects
    StartupNotify=false
    Terminal=false
    Type=Application
```

Maybe it should be the default setup for flapak versión.

**Comment by damian01w** [comment]
I installed AndroidStudio as flatpak with file access permissions host, xdg-run/dconf, ~/.config/dconf:ro, and it writes files in my home dir.
