### ISSUE TITLE
Pulse Effects running in background

### ISSUE THREAD

**Issue by Bla1** [wwmm/pulseeffects#218]
Sorry if this is the wrong place to ask, but I just added your repo and installed PulseEffects. Whenever I close the application, it defaults back to my built in audio. I was wondering if there was a way to get it to always modify my system audio without the application having to always run.

**Comment by wwmm** [comment]
It depends on how you installed. If you are using distribution packages like debian or rpm you can use the `Start Service at Login` option in the main menu:
![screenshot from 2018-05-18 20-32-49](https://user-images.githubusercontent.com/16225172/40261995-7dfa711a-5ada-11e8-8330-ce00d635a035.png)

After a logout/login PE will be started as a service and you will be able to close the window without loosing the effects.

 If you installed using flatpak this function will not work. You will have to make your own autostart service using the approiate options at [Command-Line-Options](https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options)

**Comment by Bla1** [comment]
I followed the installation instructions for Ubuntu listed in the readme, which are these commands.
`sudo add-apt-repository ppa:mikhailnov/pulseeffects -y
sudo apt update
sudo apt install pulseeffects`

When I tick start service at login and then close the app or restart my system, it defaults to my system audio and when I open PE again, the option is unticked.

**Comment by Bla1** [comment]
I don't have a autostart folder in my ~/.config folder. Should I make one and create a pulseeffects.sh which just has: nice -n -9 pulseeffects --gapplication-service ?

The Failed to register: Unable to acquire bus name 'com.github.wwmm.pulseeffects' only happens when I have the GUI application running while I execute the command line command, the command line command works just fine otherwise, but here is the output when I execute the command while the GUI is running with debug

seedship@twin-destinies:~/Desktop$ PULSEEFFECTS_DEBUG=1 pulseeffects --gapplication-service
16:45:30.295 - PulseEffects - DEBUG - MAIN - debug logging enabled
Failed to register: Unable to acquire bus name 'com.github.wwmm.pulseeffects'

**Comment by Bla1** [comment]
Yup I think that did the trick. Adding pulseeffects --gapplication-service to my autostartup commands makes it run on default. Thanks so much for helping me, and for making this cool software! I really enjoy it!

**Comment by wwmm** [comment]
Good to know it is working. I have to remember to make PE create the config folder if it does not exists. I just assumed that everybody would have it

**Comment by Bla1** [comment]
![pe-mic](https://user-images.githubusercontent.com/885667/40393189-11f1ef68-5de4-11e8-89f4-d986a9308605.png)
Sometimes on autostartup, PE defaults to mic, and thus there is no sound. Is there a way to guarantee it will start as app?

**Comment by Bla1** [comment]
Ah good to know, thanks!
