### ISSUE TITLE
Starts with weird defaults which doesn't let the sound output plus other questions

### ISSUE THREAD

**Issue by swingcake** [wwmm/pulseeffects#219]
The output device setting in PulseEffects' Pulseaudio setting tab is set to none(blank) by default. Also, the output setting in Sound settings of the GNOME shell is set to PulseEffects(mic).

Now, the working conditions are also weird. I don't seem to get a hang of it. It works when:

- Sound setting : _PulseEffects(mic)_; PulseEffects' Pulseaudio output device : _alsa_output.pci-0000_00_1f.3.analog-stereo_
- Sound setting : _PulseEffects(apps)_; PulseEffects' Pulseaudio output device : _alsa_output.pci-0000_00_1f.3.analog-stereo_

But most of the time it works with the second one which, I think, is intended. Weird, right?

What effects take place with the _enable all applications_ in the general tab?

My input device is set to _alsa_input.pci-0000_00_1f.3.analog-stereo_ by default. But there is also an option for _alsa_output.pci-0000_00_1f.3.analog-stereo.monitor_. I think the default one is correct in this case.
(My output device has only one option which is _alsa_output.pci-0000_00_1f.3.analog-stereo_)

I'm attaching some screenshots for you to understand better. Thanks in advance.

I'm using Ubuntu 18.04.

![screenshot from 2018-05-23 11-29-58](https://user-images.githubusercontent.com/32037820/40406779-a28d23ee-5e7f-11e8-8874-963eaac6c925.png)

![screenshot from 2018-05-23 11-30-13](https://user-images.githubusercontent.com/32037820/40406780-a2d755c2-5e7f-11e8-8b35-8e7415d74f33.png)

**Comment by swingcake** [comment]
Got to know that this is a known issue. Points 4 and 5 in [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ).

**Comment by wwmm** [comment]
The `Enable All Applications` setting will make PulseEffects process audio output of all applications. All effects currently enabled by the user should take place. this option is there for people that do not want to individually select which applications will have effect or not.

**Comment by wwmm** [comment]
This is very strange. Which device do you have as default sound output? Do not select `PulseEffects(apps)` as default output device for the system. Use `Speakers - Built-in Audio`

**Comment by swingcake** [comment]
Okay, that makes it work as it should. Just to be sure, I have to unload `module-switch-on-connect` on every boot so that the default output device does not switch to `PulseEffects(apps)`, and nothing else right? And that'll get fixed in ver. 12
Also, is this the same as manually selecting the output device as `Speakers - Built-in Audio` after each boot and every plug in/out?

**Comment by wwmm** [comment]
I think that what ubuntu did was adding a line to the file `/etc/pulse/default.pa` that loads the module `module-switch-on-connect`. If you remove this line this module will probably not be loaded and you will be able to use `Start service at login`.

The issue with `module-switch-on-connect` is that it thinks that the null sinks `PulseEffects(apps)` and `PulseEffects(mic)` loaded by PE are real devices like a usb sound card. As the whole purpose of this module is to automatically switch to these kind of devices when they are plugged it totally breaks PE routing. 

Without this module `Speakers - Built-in Audio` will probably be always the default device. No need to reselect it on everey reboot

**Comment by swingcake** [comment]
As of now, I don't think that editing a core file like that is viable. What I'll do is disable `Start service at login` and run `pactl unload-module module-switch-on-connect` after each boot, and then open PulseEffects. 
This should do it, am I right about this?

**Comment by wwmm** [comment]
It should work. Another possibility if you do not want to edit a system file is to copy `/etc/pulse/default.pa` to `~/.config/pulse`. Pulseaudio gives priority to user config over system config. This way you do not have to worry about what could happen after packages updates

**Comment by swingcake** [comment]
Thank you for your patience, and this amazing application. I'll close the issue now.
