### ISSUE TITLE
Dark Mode Not working on KDE

### ISSUE THREAD

**Issue by Zackptg5** [wwmm/pulseeffects#220]
Hi! Got pulseeffects with all of the plugins up and running great on manjaro kde. Only issue I've noticed is that the dark mode doesn't work. What logs/files do you need for this? Here's what I get when I run it:
```
[zack@giga-manjaro ~]$ pulseeffects

(pulseeffects:9421): Gtk-WARNING **: 22:43:12.004: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:9421): Gtk-WARNING **: 22:43:12.004: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:9421): Gtk-WARNING **: 22:43:12.004: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(gst-plugin-scanner:9424): GStreamer-WARNING **: 22:43:12.373: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstopencv.so': libopencv_bgsegm.so.3.4: cannot open shared object file: No such file or directory

(gst-plugin-scanner:9424): GStreamer-WARNING **: 22:43:12.531: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstzbar.so': libzbar.so.0: cannot open shared object file: No such file or directory

(pulseeffects:9421): Gtk-WARNING **: 22:43:14.107: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:9421): Gtk-WARNING **: 22:43:14.107: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:9421): Gtk-WARNING **: 22:43:14.107: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:9421): Gtk-WARNING **: 22:43:14.107: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:9421): Gtk-WARNING **: 22:43:14.107: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:9421): Gtk-WARNING **: 22:43:14.107: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
```

**Comment by wwmm** [comment]
To be honest I have no idea if this feature works in KDE. What it does is asking GTK to apply the dark theme. I don't know if KDE integration of GTK apps makes use of this information. Do you have any other GTK app with a working dark theme mode?

**Comment by Zackptg5** [comment]
That would explain why. Wasn't aware of the gtk vs qt thing. I went to System Settings -> Application Style -> Gnome Application Style, then set the theme I wanted (seemed to be completely separate from the main themeing settings). Then I rebooted and pulseeffects was the theme I selected there (breeze dark). Thanks!
(You might want to put this in a troubleshooting section or something so other users won't ask about it)

**Comment by wwmm** [comment]
Could you add the steps you had to follow to PE [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ)?

**Comment by Zackptg5** [comment]
Sure thing! Just added it. Don't know if this is relevant or not but I'm on Manjaro. FAQ number 6 was needed however the other ones like number 3 was not (I haven't had any issues with sound). I'm still on pulseaudio v11.1-1 and using PulseEffects from AUR (3.2.3-1)

**Comment by flipwise** [comment]
I'd just like to add that dark mode actually works for me on KDE. It seems to me, however, that you maybe need to have a complementary dark theme for the one you're using.

So in my case I am using Adapta and if I turn on dark mode it switches to AdaptaNokto.

It also works with e.g. Breeze and Breeze Dark.
