### ISSUE TITLE
loop traceback

### ISSUE THREAD

**Issue by blackPantherOS** [wwmm/pulseeffects#23]
Hi, The input/output bar is working, spectrum analizer on top does not dislayed (only black) but application is running and logging to terminal this  :

```
(pulseeffects:31480): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)

(pulseeffects:31480): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)
12:58:46.323 - PulseEffects - INFO - pulsesrc latency-time [us]: -1
12:58:46.328 - PulseEffects - INFO - pulsesrc latency-time [us]: -1

(pulseeffects:31480): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)

(pulseeffects:31480): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)

(pulseeffects:31480): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)
```

and this as well:

```Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/PulseEffects/gst.py", line 380, in on_message
    magnitudes = msg.get_structure().get_value('magnitude')
TypeError: unknown type GstValueList
```

And other problem is if muted once (ex.: on youtube) I can't get sound with unmute, just after close pulseeffects application

**Comment by wwmm** [comment]
Hi

The error `TypeError: unknown type GstValueList` is happening because the latest pulseeffects versions need Gstreamer 1.12. In case it is not possible for you to have the latest Gstreamer use version [1.4.1](https://github.com/wwmm/pulseeffects/archive/v1.4.1.tar.gz)

Muting an unmuting youtube is working fine for me. Do you have anything strange in your system log o pulseeffects log when this happens?

**Comment by wwmm** [comment]
I also have the gtk warning about negative content in GtkLevelBar. It is really annoying but it seems to be a problem with the adwaita theme. When I use other themes like adapta for example there is no gtk warning about the GtkLevelBar.

**Comment by blackPantherOS** [comment]
thanks to your suggestions, 1.4.1 working fine with gst 1.10.3, "mute-lock" problem is still presist, I will check pulse logs later
