### ISSUE TITLE
pulseeffects: error while loading shared libraries

### ISSUE THREAD

**Issue by majster95** [wwmm/pulseeffects#230]
Hi, when i try to open pulseeffects in console i get back error `pulseeffects: error while loading shared libraries: libboost_system.so.1.66.0: cannot open shared object file: No such file or directory`
How i can deal new version of boost with PE ?

**Comment by wwmm** [comment]
Just reinstall the package and you will be fine. I had to do this today too when Arch updated boost. This is a downside of aur packages. The user has to rebuild the package on his own in this situtation

**Comment by majster95** [comment]
Ok, thank you ;)
