### ISSUE TITLE
Ubuntu Xenial 16.04

### ISSUE THREAD

**Issue by rootsandculture** [wwmm/pulseeffects#231]
Is there a xenial build or a way to compile it in that ubuntu version. As dar I know there is no ppa for it.

**Comment by wwmm** [comment]
I think flatpak is your only option.

**Comment by mikhailnov** [comment]
You can edit debian/control, remove `>= some version` from all dependencies, rebuild the deb package https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source#debian--ubuntu and install it. If you try and it really works, I will make a PPA build for 16.04.
