### ISSUE TITLE
Flatpak build issues with 4.x

### ISSUE THREAD

**Issue by AsavarTzeth** [wwmm/pulseeffects#232]
I am trying to update the flatpak build at Flathub to the next major version (4.x). My understanding of C++ and related dependencies is quite limited, so I am likely missing something.

Build log: https://paste.fedoraproject.org/paste/PcIbOckE7LCI5k~eULRqlQ
Build manifest: https://github.com/flathub/com.github.wwmm.pulseeffects/blob/pulseeffects4/com.github.wwmm.pulseeffects.yml

Things I have tried, but that made no difference:
- Building dependencies from git or archives, from various official sources.
- Building with **gcc8**, instead of the **gcc6** compiler included in **org.gnome.Sdk**.

Any assistance is greatly appreciated.

**Comment by wwmm** [comment]
Libraries version on meson output seem ok. The only critical difference compared to what I have in Arch is the compiler version:

```
Version: 0.46.1
Source dir: /home/wallace/myfiles/code/cpp/pulseeffects
Build dir: /home/wallace/myfiles/code/cpp/pulseeffects/_build
Build type: native build
Project name: pulseeffects
Native C compiler: cc (gcc 8.1.1 "cc (GCC) 8.1.1 20180531")
Native C++ compiler: c++ (gcc 8.1.1 "c++ (GCC) 8.1.1 20180531")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Native dependency glib-2.0 found: YES 2.56.1
Configuring pulseeffects.cpp using configuration
Native dependency libpulse found: YES 11.1
Native dependency glib-2.0 found: YES 2.56.1
Native dependency glibmm-2.4 found: YES 2.56.0
Native dependency gtk+-3.0 found: YES 3.22.30
Native dependency gtkmm-3.0 found: YES 3.22.2
Native dependency sigc++-2.0 found: YES 2.10.0
Native dependency gstreamer-1.0 found: YES 1.14.1
Native dependency gstreamer-plugins-bad-1.0 found: YES 1.14.1
Native dependency gstreamer-webrtc-1.0 found: YES 1.14.1
Native dependency lilv-0 found: YES 0.24.2
Native dependency libbs2b found: YES 3.1.0
Dependency Boost (system, filesystem) found: YES 1.67
Program meson_post_install.py found: YES (/usr/bin/env python3 /home/wallace/myfiles/code/cpp/pulseeffects/meson_post_install.py)
Build targets in project: 8
Found ninja-1.8.2 at /usr/bin/ninja
```

What is the log when compiling with `gcc8`? The same as with `gcc6`? Based on #229 it seems that gcc `7.3` is able to compile PE. But I don't think that gtkmm, glibmm and sigc++ will like gcc6. And I may have wrote some code that is probably not going to like it too.

In any case the error you have feels like a compiler problem.

**Comment by AsavarTzeth** [comment]
Building with gcc8 solved my issue; not sure what I missed when I last tried it.

There was one other issue that was a bit tricky to figure out at first. Turns out I had to add the `-no-pie` compiler flag. I assume this is due to some incompatibility with some of the default `flatpak-builder` build options.

You can expect an up-to-date distribution on Flathub in no more than a day or two, providing testing passes for arm architectures.
