### ISSUE TITLE
[flatpak] Impossible to import presets on Gnome 3.28.2 because the file chooser does not open

### ISSUE THREAD

**Issue by glaubersm** [wwmm/pulseeffects#236]
Hi
I have pulse effects 4.0.2 installed via flatpak/flathub on two computers, computer 1 runs Gnome 3.28.2 and computer 2 runs KDE Plasma 5.13.
I can import presets on KDE Plasma but I can not do the same on Gnome 3.28.2 because pulse effects does not open the file chooser.

Both computers run Arch Linux and flatpak 0.11.8.2.

**Comment by wwmm** [comment]
Strange. @AsavarTzeth C++ version still uses the native dialog [application_ui.cpp](https://github.com/wwmm/pulseeffects/blob/2cff66c0240eb6e97eb4b1f2ff2868e0855934c2/src/application_ui.cpp#L732). I don't know if something more has to be done when using it through the C api. GTKMM 3.22 does not have the wrappers for the native dialog.

**Comment by wwmm** [comment]
The dialog works fine in gnome when using the native package. So it makes sense that the problem is somewhere in xdg-desktop-portal-gtk

**Comment by AsavarTzeth** [comment]
Yes I think so, since you don't use any wrapper and C sure is supported by Gnome. 

Also, my memory tells me it falls back to the plain GtkFileChooserDialog, which is handled by the app itself.

So what you could do is, whenever it works, verify if an external process is used or not for the file chooser.

**Comment by glaubersm** [comment]
Yes, it's native KDE file chooser.
Pulse effects 4.0.4 installed from AUR opens the file chooser in Gnome.

**Comment by AsavarTzeth** [comment]
Here's an interesting update. I cannot reproduce this.

It works on both of my Arch Linux machines, using Flatpak and Gnome Shell.

@glaubersm I have to ask:

- What version of **xdg-desktop-portal-gtk** is installed?
- Or more importantly, is it even installed?

I see that in Arch **xdg-desktop-portal-kde** and **xdg-desktop-portal-gtk**, both provides **xdg-desktop-portal-impl**.

In other words you are no longer forced to install both when you install flatpak. I think, previously both implementations dependencies of **xdg-desktop-portal**, which is a depenency of **flatpak**.

**Comment by glaubersm** [comment]
xdg-desktop-portal-gtk 0.11 is installed.
I just noticed that the file chooser opens if I have both flatpak and AUR packages installed at the same time. After I uninstall AUR package, the file chooser stops working again.

**Comment by AsavarTzeth** [comment]
Strange, in my case it works with the only installed version being from Flathub. I assume you launched the flatpak via command line, to be sure you did not accidentally run the wrong one?

**Comment by glaubersm** [comment]
Yes, I launched the flatpak via command line,

**Comment by AsavarTzeth** [comment]
Well, I am all out of ideas at the moment. 

Perhaps this is a good time to use the flatpak irc channel or mailing list.

**Comment by flipwise** [comment]
Don't know how to help with this, but are you sure it's using the native chooser in KDE? If so, it should be KDialog, but I'm pretty sure it's using the GNOME/GTK one.

**Comment by glaubersm** [comment]
Here is a screenshot taken on kde plasma

![pulse](https://user-images.githubusercontent.com/15967631/41501979-649eef40-7185-11e8-9e62-cd452bca527e.png)

**Comment by flipwise** [comment]
Thanks for the screenshot. I don't know why mine is using the Gtk chooser, I'll have to look into it.

**Comment by AsavarTzeth** [comment]
@flipwise Do you have the portal backend installed (**xdg-desktop-portal-kde**)?

If not I would guess its working as intended; it could not find the native one so it fell back to another.

**Comment by flipwise** [comment]
I didn't have it installed, but even with it it's still the Gtk chooser:

![image](https://user-images.githubusercontent.com/26850445/41506472-39899d64-7216-11e8-8056-c6f7c5b274a4.png)

Maybe it's because I installed PulseEffects from AUR not flatpak?

**Comment by AsavarTzeth** [comment]
It is without a doubt because you used AUR. [Portals](https://github.com/flatpak/flatpak/wiki/Portals) are only used by Flatpak (and Snap in the future). Its a way to communicate with the host from within a sandbox. Its not at all relevant if a distribution package is used.

Since this issue is specifically related to Flatpak (see the title), I assumed you used that too.

PulseEffects uses the [GtkFileChooserNative](https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html) API. You can find more information there on how this whole process actually works.

**Comment by wwmm** [comment]
Is this still a problem?

**Comment by glaubersm** [comment]
I can't reproduce the bug with flatpak version running on Arch Linux + Gnome 3.30.2.
File chooser opens as expected.
