### ISSUE TITLE
[Question] Rescaling spectrum

### ISSUE THREAD

**Issue by SietsmaRJ** [wwmm/pulseeffects#237]
I absolutely love pulseeffects, now that i got it working after a painfull numpy/scipy experience. I always love to see that spectrum bounce to my music, but the spectrum is quite small...

My question is,
Is there a way to rescale the height of the spectrum? (I'm not displeased if i have to scroll in the application, i just want to see my bars bounce :smiley: )

**Comment by wwmm** [comment]
In version `4.0.6` the user is able to change the spectrum height in the main menu
