### ISSUE TITLE
PulseEffects doesn't recognize presets w/ v4.0.4-3~bionic1

### ISSUE THREAD

**Issue by swingcake** [wwmm/pulseeffects#239]
Ubuntu 18.04
PulseEffects v4.0.4-3~bionic1

The presets are present in `~/.config/PulseEffects`. I do not see them under the `Presets` tab. Was working fine until the update I got today.

**Comment by wwmm** [comment]
If you upgraded from the 3.x versions this is normal. PulseEffects 4 is a total rewrite of the application and the presets format had to change.

Fortunately both formats use a text file. So you can open the old ones in a text editor and take the values from the old presets

**Comment by wwmm** [comment]
I also suggest you use the reset function in PE menu.

**Comment by Hippyjake** [comment]
A bash script to convert the old format to the new one would be super cool. Or have the app do the conversion when importing an old format.

A warning or some mention in the readme would save some time re-addressing the same issue. Like mine lol #33

**Comment by wwmm** [comment]
The warning was in the changelog of version 4. But I agree that not everybody will read that.

Porting the whole application from Python to C++ and implementing new features like arbitrary plugin ordering and configurable number of equalizer bands was way more time consuming and tiring than I had anticipated. I admit that in the end it was easier to let the migration process at the users hands XD

**Comment by swingcake** [comment]
@wwmm On another note, I was using `pactl unload-module module-switch-on-connect` on boot and it was working. Now it doesn't work. Thoughts?

**Comment by wwmm** [comment]
Which desktop do you use? If it is KDE it seems that there are a few issues with pa-plasma that are not solved even when this module is unloaded. See #235. If it is not the same problem open a new issue with the information told at [Reporting Bugs](https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs)
