### ISSUE TITLE
Need to switch Pulseeffects apps manually from pavucontrol to take effect but no permanent.

### ISSUE THREAD

**Issue by shutterPL** [wwmm/pulseeffects#240]
I'm running Manjaro Deepin with Pulseeffects 4.0.4. "Start service at login" is enabled but when I run some music software nothing is happening. I need to turn on "Pulseefects.apps" manually in pavucontrol next to Spotify or any other music software to force Pulseeffects to run. When music plays without my interfere everything works, but a simple manual song change disables "Pulseeffects.apps" and default music output is enabled.

**Comment by wwmm** [comment]
Switch on `Enable All Applications` in the same menu where you have `Start Service at Login`

**Comment by shutterPL** [comment]
I forgot to mention that I have enabled it already.

**Comment by wwmm** [comment]
Provide the information mentioned at [Reporting-Bugs](https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs). If possible get a PulseEffects terminal output when the problem happens

**Comment by shutterPL** [comment]
So here it is:

![zrzut ekranu deepin_wybierz-obszar_20180618003351](https://user-images.githubusercontent.com/40338330/41512763-4e175aae-728f-11e8-9595-92fe9d8fc0fc.png)

Pulseeffects 4.0.4 installed from AUR repository.

1. `pactl list short`

[pactl list short.txt](https://github.com/wwmm/pulseeffects/files/2109450/pactl.list.short.txt)

2. `pacmd list-sinks`

[pacmd list-sinks.txt](https://github.com/wwmm/pulseeffects/files/2109449/pacmd.list-sinks.txt)

3. `pacmd list-sink-inputs`

[pacmd list-sink-inputs.txt](https://github.com/wwmm/pulseeffects/files/2109451/pacmd.list-sink-inputs.txt)

4. `pacmd list-sources`

[pacmd list-sources.txt](https://github.com/wwmm/pulseeffects/files/2109452/pacmd.list-sources.txt)

5. `pacmd list-source-outputs`

[pacmd list-source-outputs.txt](https://github.com/wwmm/pulseeffects/files/2109454/pacmd.list-source-outputs.txt)

This turn often into...
![zrzut ekranu deepin_wybierz-obszar_20180618003103](https://user-images.githubusercontent.com/40338330/41512739-f3c19d9e-728e-11e8-95c1-d890489ba795.png)
----------------
this
![zrzut ekranu deepin_wybierz-obszar_20180618002539](https://user-images.githubusercontent.com/40338330/41512734-f333dd74-728e-11e8-9ecf-cdf90adea92a.png)
----------------
![zrzut ekranu deepin_wybierz-obszar_20180618002635](https://user-images.githubusercontent.com/40338330/41512735-f35096d0-728e-11e8-80fc-f205f998c439.png)
![zrzut ekranu deepin_wybierz-obszar_20180618002709](https://user-images.githubusercontent.com/40338330/41512736-f36c2de6-728e-11e8-933e-f7cdd45a7f56.png)
![zrzut ekranu deepin_wybierz-obszar_20180618002758](https://user-images.githubusercontent.com/40338330/41512737-f386ea50-728e-11e8-9adf-719016badbbc.png)
![zrzut ekranu deepin_wybierz-obszar_20180618002819](https://user-images.githubusercontent.com/40338330/41512738-f3a4084c-728e-11e8-9883-8cb8ee042729.png)

**Comment by wwmm** [comment]
Put also the output of PE running in DEBUG mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Try to trigger the bug in the process

**Comment by shutterPL** [comment]
I run this `G_MESSAGES_DEBUG=pulseeffects pulseeffects` via terminal but I have no idea where to find log file.

**Comment by wwmm** [comment]
It is not saved to a file. It is printed in the terminal. Just copy and paste the lines printed by PE here

**Comment by shutterPL** [comment]
![zrzut ekranu deepin_deepin-terminal_20180618210744](https://user-images.githubusercontent.com/40338330/41556699-cf655ca8-733b-11e8-8cf3-c27bbcd76caf.png)
This is how terminal looks when PE is running. Nothing happens.

**Comment by wwmm** [comment]
Strange. Here I have many lines printed. Maybe you have an instance already running. Try to execute `G_MESSAGES_DEBUG=pulseeffects pulseeffects -q` before trying to run `G_MESSAGES_DEBUG=pulseeffects pulseeffects`

**Comment by shutterPL** [comment]
**So here is printed output.** 

[marcin@marcin-pc ~]$ G_MESSAGES_DEBUG=pulseeffects pulseeffects
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.532: pulse_manager: context is connecting
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.532: pulse_manager: context is authorizing
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.532: pulse_manager: context is setting name
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.532: pulse_manager: context is ready
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.532: pulse_manager: connected to: unix:/run/user/1000/pulse/native
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.532: pulse_manager: protocol version: 32
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.533: pulse_manager: Pulseaudio version: 11.1
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.533: pulse_manager: default pulseaudio source: alsa_input.pci-0000_05_01.0.analog-stereo
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.533: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_05_01.0.analog-surround-51
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.533: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.533: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.533: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.533: pulse_manager: sink loaded
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.534: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.534: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.534: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.534: pulse_manager: sink loaded

(pulseeffects:3683): pulseeffects-WARNING **: 21:17:33.579: maximizer plugin was not found!

(pulseeffects:3683): pulseeffects-WARNING **: 21:17:33.579: delay plugin was not found!
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:33.595: presets_manager: user preset directory already exists: /home/marcin/.config/PulseEffects

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:17:34.088: pulse_manager: failed to move source output 6 to PE
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.106: soe: spectrum enabled

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:17:34.116: pulse_manager: failed to move source output 0 to PE

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:17:34.118: pulse_manager: failed to move source output 1 to PE

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:17:34.120: pulse_manager: failed to move source output 6 to PE
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.123: application_ui: output device changed: alsa_output.pci-0000_05_01.0.analog-surround-51
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.123: application_ui: added sink: alsa_output.pci-0000_05_01.0.analog-surround-51
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.123: application_ui: added source: alsa_output.pci-0000_05_01.0.analog-surround-51.monitor
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.123: application_ui: input device changed: alsa_input.pci-0000_05_01.0.analog-stereo
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.123: application_ui: added source: alsa_input.pci-0000_05_01.0.analog-stereo
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.124: soe: READY
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.124: soe: PAUSED
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.124: soe: pulsesrc latency [us]: 10000
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.124: soe: pulsesrc buffer [us]: 200000
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.124: soe: pulsesink latency [us]: 10000
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.124: soe: pulsesink buffer [us]: 200000
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:34.124: soe: PLAYING

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:17:34.126: pulse_manager: failed to move source output 10 to PE

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:17:45.381: pulse_manager: failed to move source output 11 to PE
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:45.658: sie: READY
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:45.659: sie: PAUSED
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:45.660: sie: equalizer enabled
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:45.662: sie: spectrum enabled

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:17:45.714: pulse_manager: failed to move source output 12 to PE

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:17:45.716: pulse_manager: failed to move source output 14 to PE
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:52.257: sie: READY
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:52.258: sie: PAUSED

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:17:52.258: pulse_manager: failed to move source output 15 to PE
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:52.262: sie: pulsesrc latency [us]: 10000
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:52.262: sie: pulsesrc buffer [us]: 200000
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:52.266: sie: pulsesink latency [us]: 10000
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:52.266: sie: pulsesink buffer [us]: 200000
(pulseeffects:3683): pulseeffects-DEBUG: 21:17:52.298: sie: PLAYING

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:17:52.300: pulse_manager: failed to move source output 17 to PE

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:18:08.798: pulse_manager: failed to move source output 18 to PE
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:22.024: sie: READY
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:22.024: sie: PAUSED
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:22.026: sie: pulsesrc latency [us]: 10000
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:22.026: sie: pulsesrc buffer [us]: 200000

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:18:22.026: pulse_manager: failed to move source output 20 to PE
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:22.032: sie: pulsesink latency [us]: 10000
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:22.032: sie: pulsesink buffer [us]: 200000
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:22.091: sie: PLAYING

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:18:22.093: pulse_manager: failed to move source output 21 to PE

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:18:43.445: pulse_manager: failed to move source output 22 to PE
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.452: sie: READY
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.452: sie: PAUSED
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.453: sie: pulsesrc latency [us]: 10000
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.453: sie: pulsesrc buffer [us]: 200000

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:18:47.456: pulse_manager: failed to move source output 24 to PE
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.468: sie: pulsesink latency [us]: 10000
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.468: sie: pulsesink buffer [us]: 200000
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.503: sie: PLAYING

(pulseeffects:3683): pulseeffects-CRITICAL **: 21:18:47.503: pulse_manager: failed to move source output 25 to PE

**Comment by wwmm** [comment]
The errors `failed to move source output` should not happen. But it is not clear what is causing this. And to let thing even more strange `source outputs` are from applications that record audio like skype and not from media players like spotify. In this case we would have failures with `sink input` in their messages

**Comment by shutterPL** [comment]
`failed to move source output` happens when song is changed. But this...

(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.452: sie: READY
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.452: sie: PAUSED
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.453: sie: pulsesrc latency [us]: 10000
(pulseeffects:3683): pulseeffects-DEBUG: 21:18:47.453: sie: pulsesrc buffer [us]: 200000

is caused by changing manually to Pulseeffects.apps next to music player.

**Comment by shutterPL** [comment]
Now i can't enable any application in PE when pavucontrol window is closed.

**Comment by shutterPL** [comment]
[journalctl-log.txt](https://github.com/wwmm/pulseeffects/files/2125170/journalctl-log.txt)
The last part of this log says what happens when pavucontrol windows is closed and I'm trying to enable my music player in PE with no result.


**cze 21 22:01:44 marcin-pc pulseaudio[2025]: I: [pulseaudio] sink-input.c: Freeing input 16 "Playback Stream"
cze 21 22:01:44 marcin-pc pulseaudio[2025]: I: [pulseaudio] client.c: Freed 24 "PulseEffects"
cze 21 22:01:44 marcin-pc pulseaudio[2025]: I: [pulseaudio] protocol-native.c: Connection died.
cze 21 22:01:44 marcin-pc pulseaudio[2025]: D: [pulseaudio] module-suspend-on-idle.c: Sink PulseEffects_apps becomes idle, timeout in 5 seconds.
cze 21 22:01:44 marcin-pc pulseaudio[2025]: I: [pulseaudio] source-output.c: Freeing output 21 "Record Stream"
cze 21 22:01:44 marcin-pc pulseaudio[2025]: I: [pulseaudio] client.c: Freed 25 "PulseEffects"
cze 21 22:01:44 marcin-pc pulseaudio[2025]: I: [pulseaudio] protocol-native.c: Connection died.**

**Comment by wwmm** [comment]
At some points we have 
`[pulseaudio] sink-input.c: Starting to move sink input 0 from 'alsa_output.pci-0000_05_01.0.analog-surround-51'`
` [pulseaudio] sink-input.c: Successfully moved sink input 0 to PulseEffects_apps.`

This means that at least for a brief moment the application was enabled. But the we have

` [pulseaudio] sink-input.c: Starting to move sink input 0 from 'PulseEffects_apps'`
`[pulseaudio] sink-input.c: Successfully moved sink input 0 to alsa_output.pci-0000_05_01.0.analog-surround-51.`

They mean that the app was disabled. So something is telling Pulseaudio to take the application away from PulseEffects. But it is not clear what could be doing that.

**Comment by wwmm** [comment]
And the `Connection died` errors do not sound good too.

**Comment by shutterPL** [comment]
Maybe Deepin sound settings in Control Center is a cause of the problem. I mean you can't change settings in any other place, becouse Control Center is where settings are in "highest priority"?

![zrzut ekranu deepin_wybierz-obszar_20180624221818](https://user-images.githubusercontent.com/40338330/41823210-8cad8d84-77fc-11e8-842b-fb9a379bc547.png)

**Comment by wwmm** [comment]
At least KDE has an issue #235 where they do an audio routing that conflicts with the ones PE has to do. Maybe Deepin is also doing more than just set the default output device

**Comment by shutterPL** [comment]
> {"Profiles":{"alsa_card.pci-0000_01_00.1":"off","alsa_card.pci-0000_05_01.0":"output:analog-surround-51+input:analog-stereo"},"Sink":"alsa_output.pci-0000_05_01.0.analog-surround-51","Source":"alsa_input.pci-0000_05_01.0.analog-stereo","SinkPort":"analog-output","SourcePort":"analog-input-mic","SinkVolume":1,"SourceVolume":0.81646728515625}

This is how `audio.json` file looks in `~/.config/deepin/dde-daemon` directory. Maybe here is a problem. I'm not sure where should I search for source of this issue.

**Comment by wwmm** [comment]
This file shows only default device setting. The app is disabled when it is moved to another sink. If Deepin is doing this it will not be visible in a file. I think it will be necessary to contact Deepin developers somehow

**Comment by victorcifuentes** [comment]
If you disable audio from dconf (com.deepin.dde.daemon) and restart, PulseEffects will works ok.

**Comment by shutterPL** [comment]
@victorcifuentes Works like a charm ;)

**Comment by wwmm** [comment]
Could you update the [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ) with the steps to fix the problem in Deepin?

In any case we can close this issue

**Comment by shutterPL** [comment]
I think @victorcifuentes  should do that. He solved the problem.
