### ISSUE TITLE
what's with the bleeding edge libs

### ISSUE THREAD

**Issue by prometheanfire** [wwmm/pulseeffects#243]
glib 2.56 isn't even packaged on most distros (we do have gst 1.14.1 at least though).

**Comment by prometheanfire** [comment]
same for other glib things (glibmm)

**Comment by wwmm** [comment]
`Glib::RefPtr` of older glibmm versions do not have the `get` method I use everywhere in PulseEffects. According to its documentation the method was implemented in version `2.56`. As I am not sure if it is  possible or even a good idea to use glibmm with an older glib I decided to increase the minimum version of both libraries.

**Comment by prometheanfire** [comment]
It looks like at least in gentoo we allow older glibs to be used with newer glibmm libs.  Though what the correct minimum version for 2.56 is I don't know.

**Comment by wwmm** [comment]
Maybe it is possible to use it with an older glib. But I do not have how to test this in Arch Linux because both libraries are version `2.56`

**Comment by prometheanfire** [comment]
sure, guess I'll just have to wait before packaging it.  I'm sure other distros are in a similiar situation.

**Comment by wwmm** [comment]
As far as I know there are people in `Mageia` and in `Ubuntu` that were able to compile. I don't know if they had to do non standard procedures

**Comment by mikhailnov** [comment]
Ubuntu 18.04 has glibmm 2.56, and I build PulseEffects for >= 18.04, no non-standard procedures are done.
