### ISSUE TITLE
Calf Multi-Band Compressor  ???

### ISSUE THREAD

**Issue by TheGarageRocks** [wwmm/pulseeffects#246]
Have you thought of incorporating the most excellent Calf Multi-Band Compressor?
It's a 3 band compressor that has absolutely awesome clear sound. Very nice to compress bass, mid, & highs at different rates.
If possible, please consider.
Thanks,
The Garage

**Comment by wwmm** [comment]
It seems possible. I did not think about it before because I didn't need yet so much fine control when compressing.

**Comment by wwmm** [comment]
Implemented in lates PE `4.1.0`. Thank you for the suggestion. It is very nice compressor indeed
