### ISSUE TITLE
Cannot run in Sabayon(Gentoo) linux

### ISSUE THREAD

**Issue by Ygarr** [wwmm/pulseeffects#25]
output:
GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects
01:14:28.471 - PulseEffects - INFO - pulseaudio context started
01:14:28.472 - PulseEffects - INFO - connected to server: /run/user/1000/pulse/native
01:14:28.472 - PulseEffects - INFO - server protocol version: 32
01:14:28.472 - PulseEffects - INFO - pulseaudio version: 10.0
01:14:28.472 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
01:14:28.472 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
01:14:28.473 - PulseEffects - INFO - default pulseaudio sink audio format: s16le. We will use the same format.
01:14:28.473 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
01:14:28.473 - PulseEffects - INFO - (min, max) spectrum frequencies: (27.5625, 19982.8125) these values are sampling rate dependent
Traceback (most recent call last):
  File "./pulseeffects", line 6, in <module>
    a = Application()
  File "/home/user/SOFT/pulseeffects/PulseEffects/application.py", line 55, in __init__
    self.gst = GstEffects(self.pm.default_sink_rate)
  File "/home/user/SOFT/pulseeffects/PulseEffects/gst.py", line 61, in __init__
    self.pipeline = self.build_pipeline()
  File "/home/user/SOFT/pulseeffects/PulseEffects/gst.py", line 172, in build_pipeline
    output_limiter.set_property('input-gain', 0)
AttributeError: 'NoneType' object has no attribute 'set_property'
==============
fresh git pull. Seems all dependencies are satisfied. 
===============
gst-inspect-1.0 | grep -i ladspa 
is EMPTY
===============
eix gst-plugins-bad
[I] media-libs/gst-plugins-bad
     Доступные версии:      
     (0.10) 0.10.23-r4
     (1.0)  1.8.3-r1 1.10.3^t (~)1.10.4^t  - installed
==================

eix swh-plugins
[I] media-plugins/swh-plugins  - installed
====================
python --version
Python 2.7.12

**Comment by wwmm** [comment]
Hi,

The output of the command 'gst-inspect-1.0 | grep -i ladspa' should not be empty. Something is not right in your gstreamer installation or in the installation of the swh-plugins. Also make sure you have python3 installed.

**Comment by Ygarr** [comment]
Just checked all installed regarding to ontopic,  set python 3(python --version
Python 3.4.5).  Didn't help yet. Thinking...

**Comment by wwmm** [comment]
At least in Arch Linux the package gst-plugins-bad has the file `/usr/lib/gstreamer-1.0/libgstladspa.so` and the swh-plugins package the file `/usr/lib/ladspa/fast_lookahead_limiter_1913.so`

**Comment by agates** [comment]
I'm having the same issue here on Gentoo.  I think it has something to do with packaging differences... running python3 and swh-plugins are installed along with gst-plugins-bad.

However, it looks like media-plugins/gst-plugins-ladspa only exists for gstreamer 0.10 and not 1.0.  Trying to find out why...

**Comment by agates** [comment]
I contacted the gstreamer maintainer for Gentoo.  Looks like it was just some confusion regarding ladspa vs lv2 in the migration to 1.0.

They are working on the packaging of gstreamer 1.12 but should get to this within a few weeks!  In the meantime, they said:

"For 1.10 you could play around with a local gst-plugins-ladspa or gst-
plugins-lv2 too, just grab a media-plugins/gst-plugins-* ebuild that
has GST_ORG_MODULE=gst-plugins-bad - for example gst-plugins-opencv as
a base, use gst-plugins-ladspa and gst-plugins-lv2 as the package name,
adjust dependencies as apporpriate for either and should be mostly good
to go."

I'm going to test this out later tonight and report back.

**Comment by wwmm** [comment]
At some point I considered using lv2 instead of ladspa. But for some reason I could not get gstreamer to use any of the lv2 plugins I had installed.

**Comment by jorgicio** [comment]
Hi!

I maintain a Gentoo overlay called as my username, "jorgicio".
Just add it with Layman, and install pulseeffects as usual. I also added the ladspa and lv2 plugins for Gstreamer 1.0 there. Tried there and the problem is fixed.
More information is there, and also you can report issues if any:

http://github.com/jorgicio/jorgicio-gentoo

**Comment by Keepco** [comment]
What are the contents of your /usr/lib/ladspa dir? I only have {amp,delay,filter,noise,side}.so with gstreamer-plugins-bad 1.12.1 ( on exherbo though )

**Comment by agates** [comment]
@jorgicio Awesome!  I already use your overlay for other things, and both the ladspa gstreamer plugin and pulseeffects are working great!  The only caveat is the spectrum seems to be empty, but I don't spend my time looking at that anyway.

**Comment by jorgicio** [comment]
@agates Hi! Thanks for using my overlay. About the caveat you mention, I did not notice this, I'll try to check it later, but if you still have some problems like that, you're welcome to submit an issue.
And thanks again ;)

**Comment by wwmm** [comment]
Spectrum should work with gstreamer equal or above 1.12. In the latest versions of PulseEffects python-numpy and python-scipy will also be needed for the spectrum
