### ISSUE TITLE
Issue with Bluetooth A2DP and PulseEffects 3.2.3

### ISSUE THREAD

**Issue by oblivionnewtonjohn** [wwmm/pulseeffects#250]
I am running PE 3.2.3 on Solus distro, installed from their repository. When streaming via A2DP to my Klipsch soundbar, with PulseEffects enabled, the audio will intermittently glitch out, requiring me to disable Bluetooth, change the Sound preferences from HiFi-Klipsch R-4B, to PulseEffects(apps) to again pass audio through the application. This resolves for a time, but then the issue returns. 
![screenshot from 2018-06-26 11-27-40](https://user-images.githubusercontent.com/13839715/41926555-4ea68fe2-7935-11e8-9ea7-5b5a7ef3c1d1.png)

[PulseEffects DEBUG output.txt](https://github.com/wwmm/pulseeffects/files/2138047/PulseEffects.DEBUG.output.txt)

**Comment by oblivionnewtonjohn** [comment]
[DEBUG_output.txt](https://github.com/wwmm/pulseeffects/files/2138336/DEBUG_output.txt)

**Comment by wwmm** [comment]
Is there any change if you increase buffer latency from `100000 us` to `200000 us`. You can do that in PulseEffects main menu. At least my bluetooth headphones have a lot of issues with lower buffers.

**Comment by oblivionnewtonjohn** [comment]
@wwmm I tried that yesterday upon accident, it glitched pretty heavy at 20K. 
I can test again and report back.

**Comment by wwmm** [comment]
By `20K` you mean `20000 us`? It is too low. With this value even soundcards may glitch if you do not adjust the latency parameter accordingly

**Comment by oblivionnewtonjohn** [comment]
@wwmm I was playing with latency, it went to 20000 us, hung and the audio glitched bad. I had to reset PE as it would not let me change the parameters manually.

**Comment by wwmm** [comment]
Change the buffer but not the latency. Leave it at `10000 us`:
![screenshot from 2018-06-26 18-00-06](https://user-images.githubusercontent.com/16225172/41938970-eadc1d48-796a-11e8-97c3-8e9380f53220.png)
