### ISSUE TITLE
compile with hardening flags

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#256]
Debian's Lintian (tool which checks the validity of packages) reports this on PulseEffects: https://lintian.debian.org/tags/hardening-no-fortify-functions.html 
https://mentors.debian.net/package/pulseeffects

I did not understand well enough how it works, can you please have a look at it, may be hardening options can be enabled in pulseeffects's build system by default.

**Comment by wwmm** [comment]
To be honest I also do not understand. Maybe this post can help you [https://stackoverflow.com/questions/21318235/building-a-trivial-program-with-dpkg-buildflags](https://stackoverflow.com/questions/21318235/building-a-trivial-program-with-dpkg-buildflags)

In any case it seems to be an issue specific to the debian package policies. I am not sure if it is a good idea to have these options by default on other distributions. It may have some side effects. It is better to leave this decision for the distributions.

**Comment by mikhailnov** [comment]
Then let's think that pulseeffects does not work with potentially hackable infornation and so this lintian's recommendation can be passed away
