### ISSUE TITLE
 EQ presets don't work on start

### ISSUE THREAD

**Issue by flipwise** [wwmm/pulseeffects#257]
I noticed that new EQ presets don't work for me when I start the program. It does not matter if PE is started with the equalizer on or off.

Workaround: Wheel button -> Reset equalizer -> now load the desired preset

This workaround has to be applied everytime PE is started. I tried this with a clean user and it's the same.

PE version: 4.1.2 from AUR
OS: Manjaro Linux
DE: Plasma

Debug info is attached
[PEpresetsBUG.txt](https://github.com/wwmm/pulseeffects/files/2168186/PEpresetsBUG.txt)
.

**Comment by wwmm** [comment]
There is a problem indeed. I will take a look.

**Comment by wwmm** [comment]
I released PE `4.1.3`. At least here the problem was fixed. I updated the aur package. Could you test it?

**Comment by flipwise** [comment]
That fixed it, awesome! Thank you :)
