### ISSUE TITLE
Audio going in but nothing seems to be happening

### ISSUE THREAD

**Issue by CharoSW** [wwmm/pulseeffects#26]
I just upgraded from a much older version which was working fine but the current version doesn't seem to be doing anything.  When I try to use any program through pulseeffects everything goes silent and there is no visual activity from within it.  That's what seems to set this apart from the other no sound issue, I am not even getting the spectrum.  I admittedly can't remember which older version I was on, but I did grab a copy of version 1.0 which still works.  If I get a little more time I can go forward through the versions to try and pinpoint where it changed if that would help.

I run Arch, fully updated

**Comment by wwmm** [comment]
What is printed by pulseeffects when you run it from the command line? It would also be useful to see  the playing and recording tab from pavucontrol when pulseeffects is open. If there is no spectrum one possibility is that pulseeffects is no recording from `PulseEffects.monitor` device. Pavucontrol recording tab will show from which device pulseeffects is recording.

**Comment by CharoSW** [comment]
Issue solved because apparently the recorder was muted.  I'm not sure how as I haven't used pavucontrol in a little while never mess with mutes anyway but at least it's a nice easy fix.
