### ISSUE TITLE
Most effects greyed out

### ISSUE THREAD

**Issue by testsieger73** [wwmm/pulseeffects#261]
Hi,

all dependencies are installed but Calf effects are greyed out. The only ones working are Equalizer, Crossfeed and Maximizer.

![image](https://user-images.githubusercontent.com/31756945/42675083-b523af1c-8672-11e8-9ced-5abb97803784.png)

Starting calfjackhost returns an error.

![image](https://user-images.githubusercontent.com/31756945/42675403-32f6ed9a-8674-11e8-84b4-3b9591babc3d.png)

Google didn't help. Any idea?

**Comment by wwmm** [comment]
Take a look at point 6 in PulseEffects [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ). It may help.
