### ISSUE TITLE
convolver spams console

### ISSUE THREAD

**Issue by jtojnar** [wwmm/pulseeffects#263]
When I open the convolver tab and enable the plug-in and music is playing, the console is flooded by the folllowing warnings over and over again:

```
(pulseeffects:10318): pulseeffects-WARNING **: 12:15:17.831: convolver: irs file does not exists or it is empty: 

(pulseeffects:10318): pulseeffects-WARNING **: 12:15:17.832: convolver: we will just passthrough data.

```

I am using Pulseeffects 4.1.5 on NixOS

**Comment by wwmm** [comment]
You have to import an impulse response file and select it:
![screenshot from 2018-07-14 11-33-42](https://user-images.githubusercontent.com/16225172/42725423-8c038cf0-8759-11e8-9734-64549edd8fa5.png)
I am still thinking about how to create some kind of warning for that in the interface

**Comment by jtojnar** [comment]
Yes, I am aware. The console still should not be spammed when there is not file loaded, though. Maybe the codepath could be only active when there are some files?

**Comment by wwmm** [comment]
In a way the code path is already disabled and the plugin enter pass through mode like it is said in the log. I think it is just a matter of calling `util::debug` instead of `util::warning` when show this message. This way it would only be visible when the user runs in debug mode.
