### ISSUE TITLE
PulseEffects crashes each time I start Audacity.  

### ISSUE THREAD

**Issue by dln949** [wwmm/pulseeffects#266]
Ubuntu 17.10, Audacity 2.1.2-2, PulseEffects 3.2.3.  

I have PulseEffect running.  Then, each time I start Audacity, PulseEffects crashes.  

Why does this happen?  How do I fix this?  Or, how do I diagnose what is wrong?  

The crash produces a ~25 MB crash log, but I don't know how to interpret it.  

Thanks for any help.

**Comment by wwmm** [comment]
What is printed in the terminal when you execute PulseEffects as `PULSEEFFECTS_DEBUG=1 pulseeffects` ?

Is there anything special you do in Audacity that triggers the crash? Is it auto loading something? I made a few tests with Audacity and PulseEffects `4.1.6` and I do not have any crash. So it may be a bug in version `3.2.3`

**Comment by dln949** [comment]
I do nothing special in Audacity, nor is it auto loading anything (that I am aware of).  

Here is the output I get in the terminal when I start Audacity:  

`19:38:36.343 - PulseEffects - CRITICAL - PM - context operation  failed!
19:38:36.353 - PulseEffects - CRITICAL - PM - context operation  failed!
19:38:36.363 - PulseEffects - CRITICAL - PM - context operation  failed!
19:38:36.368 - PulseEffects - CRITICAL - PM - context operation  failed!

(pulseeffects:16547): Pango-CRITICAL **: pango_layout_set_width: assertion 'layout != NULL' failed

(pulseeffects:16547): Pango-CRITICAL **: pango_layout_set_alignment: assertion 'layout != NULL' failed

(pulseeffects:16547): Pango-CRITICAL **: pango_layout_set_text: assertion 'layout != NULL' failed
19:38:36.379 - PulseEffects - CRITICAL - PM - context operation  failed!
19:38:36.379 - PulseEffects - CRITICAL - PM - context operation  failed!
19:38:36.383 - PulseEffects - DEBUG - SIE - pipeline state: playing
19:38:36.394 - PulseEffects - DEBUG - PM - volume meter stream for app 279 is being created
19:38:36.396 - PulseEffects - DEBUG - PM - volume meter stream for app 279 has failed. Did you disable this app ?
19:38:36.401 - PulseEffects - DEBUG - SIE - pipeline state: playing
19:38:36.401 - PulseEffects - DEBUG - PM - volume meter stream for app 283 is being created
19:38:36.404 - PulseEffects - CRITICAL - PM - context operation  failed!
19:38:36.404 - PulseEffects - DEBUG - PM - volume meter stream for app 283 has failed. Did you disable this app ?

(pulseeffects:16547): Pango-CRITICAL **: pango_layout_set_width: assertion 'layout != NULL' failed

(pulseeffects:16547): Pango-CRITICAL **: pango_layout_set_alignment: assertion 'layout != NULL' failed

(pulseeffects:16547): Pango-CRITICAL **: pango_layout_set_text: assertion 'layout != NULL' failed
19:38:36.409 - PulseEffects - DEBUG - SIE - pulsesrc latency-time [us]: 10000
19:38:36.409 - PulseEffects - DEBUG - SIE - pulsesrc buffer-time [us]: 100000
19:38:36.413 - PulseEffects - DEBUG - SIE - pulsesink latency-time [us]: 10000
19:38:36.414 - PulseEffects - DEBUG - SIE - pulsesink buffer-time [us]: 100000
19:38:36.434 - PulseEffects - CRITICAL - PM - context operation  failed!
19:38:36.436 - PulseEffects - CRITICAL - PM - context operation  failed!
19:38:36.438 - PulseEffects - CRITICAL - PM - context operation  failed!
19:38:36.453 - PulseEffects - CRITICAL - PM - context operation  failed!
19:38:36.456 - PulseEffects - DEBUG - SOE - pipeline state: playing
19:38:36.466 - PulseEffects - DEBUG - PM - volume meter stream for app 147 is being created
19:38:36.468 - PulseEffects - DEBUG - SOE - pulsesrc latency-time [us]: 25941
19:38:36.468 - PulseEffects - DEBUG - SOE - pulsesrc buffer-time [us]: 77823
19:38:36.468 - PulseEffects - DEBUG - SOE - pulsesink latency-time [us]: 25941
19:38:36.468 - PulseEffects - DEBUG - SOE - pulsesink buffer-time [us]: 77823
19:38:36.468 - PulseEffects - DEBUG - PM - volume meter stream for app 147 is ready
19:38:36.470 - PulseEffects - DEBUG - PM - volume meter stream for app 147 was terminated
19:38:36.472 - PulseEffects - DEBUG - SOE - pipeline state: playing
19:38:36.472 - PulseEffects - DEBUG - PM - volume meter stream for app 151 is being created
Segmentation fault (core dumped)`


Also - I originally installed PulseEffects from the PPA located at [https://launchpad.net/~mikhailnov/+archive/ubuntu/pulseeffects](url) , I thought for sure there was a version on the PPA for Artful.  But, when I look now, there isn't one.  Where should I be looking to have the current version installed that will also be automatically updated?  Thanks.

**Comment by wwmm** [comment]
Lots of critical errors. There is definitely a bug. Something you may try is to reset the latency and buffer values. Default latency is 10000 and the default buffer is 100000

I think that in ubuntu 17 flatpak is you only option to move to the 4.x version.

**Comment by dln949** [comment]
I installed the latest flatpak version of PulseEffects, that appears to have solved the original problem at the start of this thread.  Thanks.
