### ISSUE TITLE
separate libgstpeconvolver.so into gstreamer1.0-convolver

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#269]
Hello, I've come to a thought that `libgstpeconvolver.so` can be separated into another package, e.g. `gstreamer1.0-convolver`, from which PulseEffects will depend. It _may_ allow other programs to reuse this gstreamer plugin without installing full pulseeffects.

What do you think?

**Comment by mikhailnov** [comment]
It will not require any upstream changes, because deb and rpm can easily build multiple binary packages from one source. But probably `libgstpeconvolver.so` can be renamed to `libgstconvolver.so` (or  `libgstpeconvolver.so` may be left and the package may be called `gstreamer1.0-convolver-pulseeffects`.

**Comment by wwmm** [comment]
Hi! I don't see a problem. Like you said there is no need for upstream changes. And the plugin can be used elsewhere. This can be tested with the command `gst-launch-1.0 audiotestsrc blocksize=512 ! peconvolver kernel-path=full_path_to_file ! pulsesink`

Renaming `libgstpeconvolver.so` to `libgstconvolver.so` is not a problem now but can become in the future if GStreamer's developers decide to make a convolver plugin. If this ever happens they will probably name the plugin convolver and we will have a conflict. As we are not part of the GStreamer project I decided to add the prefix `pe` to avoid this situation.

**Comment by mikhailnov** [comment]
Right, came here to write about the same possible conflict. ok, I will split the package.
