### ISSUE TITLE
ImportError: cannot import name 'CubicSpline'

### ISSUE THREAD

**Issue by kevinsmia1939** [wwmm/pulseeffects#27]
kev@kev-ICONIA-W700:~/pulseeffects$ GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects
Traceback (most recent call last):
  File "./pulseeffects", line 4, in <module>
    from PulseEffects.application import Application
  File "/home/kev/pulseeffects/PulseEffects/application.py", line 10, in <module>
    from PulseEffects.gst import GstEffects
  File "/home/kev/pulseeffects/PulseEffects/gst.py", line 7, in <module>
    from scipy.interpolate import CubicSpline
ImportError: cannot import name 'CubicSpline'

I am trying to install on kde neon, I believe I install all the dependency (the instruction is pythongobject but I install python-gobject).

**Comment by wwmm** [comment]
Hi, the latest PulseEffects also needs the packages python-numpy and python-scipy(this is the name in Arch Linux it may be other in Neon). CubicSpline module was implemented in scipy 0.18. So older scipy versions will not work unless someone have backported this module

**Comment by wwmm** [comment]
At least in Arch numpy and scipy are offered for python 2 and 3. Make sure you have the packages for python 3 installed

**Comment by kevinsmia1939** [comment]
I download pulseeffects version 1.4.0 instead. I don't know what I mess up.
kev@kev-ICONIA-W700:~/pulseeffects$ GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects
Traceback (most recent call last):
  File "./pulseeffects", line 6, in <module>
    a = Application()
  File "/home/kev/pulseeffects/PulseEffects/application.py", line 39, in __init__
    self.gst = GstEffects(self.pm.default_sink_rate)
  File "/home/kev/pulseeffects/PulseEffects/gst.py", line 49, in __init__
    self.pipeline = self.build_pipeline()
  File "/home/kev/pulseeffects/PulseEffects/gst.py", line 93, in build_pipeline
    self.audio_src.set_property('client-name', 'PulseEffects')
AttributeError: 'NoneType' object has no attribute 'set_property'

**Comment by wwmm** [comment]
The error `AttributeError: 'NoneType' object has no attribute 'set_property'` is telling you do not have the gstreamer plugin pulsesrc installed. At least in Arch this plugin is in the package gst-plugins-good

**Comment by kevinsmia1939** [comment]
I fix it,  I have already install gstreamer-pulgins-good, what I need is gstreamer1.0-pulseaudio.

**Comment by wwmm** [comment]
I had to remove most of the them when I moved to a 15 bands equalizer. The ones I was using before were built for a 10 bands equalizer. I do not know how to create presets for music styles like rock, pop, techno, etc. If someone that knows send me these presets for 15 bands I will add them to PulseEffects.

**Comment by DroWnThePoor** [comment]
Having a similar problem, but contains more errors than OP.
I've done the actual install not just running the program
pulseeffects 
Traceback (most recent call last):
  File "/usr/local/bin/pulseeffects", line 4, in <module>
    __import__('pkg_resources').run_script('PulseEffects==2.0.3', 'pulseeffects')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.3-py3.5.egg/EGG-INFO/scripts/pulseeffects", line 4, in <module>
    from PulseEffects.application import Application
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.3-py3.5.egg/PulseEffects/application.py", line 17, in <module>
    from PulseEffects.sink_input_effects import SinkInputEffects
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.3-py3.5.egg/PulseEffects/sink_input_effects.py", line 7, in <module>
    from scipy.interpolate import CubicSpline
ImportError: cannot import name 'CubicSpline'

Any ideas? Should I open a separate issue?

**Comment by wwmm** [comment]
Hi, it is the same problem. Scipy is not installed or is installed for python2 and not python 3 or it is installed for python 3 but its version is below 0.18. The module CubicSpline is not present in older scipy versions.

**Comment by DroWnThePoor** [comment]
Okay thanks. Found out Ubuntu 16.04s scipy repo only goes to .17 so I'll have to find a way to get it elsewhere. Any clues? I have pip and easy_install.

**Comment by dx9s** [comment]
@DroWnThePoor you found a solution to getting the correct/good enough Scipy on Ubuntu 16.04 ?

**Comment by dx9s** [comment]
This seems to have worked for me:

$ sudo apt-get install python3-pip
$ pip3 install numpy scipy
$ pip3 install --upgrade pip # (this is optional but I did it)


GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects 

and it is working (after the usual 'glib-compile-schemas share/glib-2.0/schemas/')

**Comment by dx9s** [comment]
Update, it mostly works. The graph (250 point RTA) isn't working.

~/src/pulseeffects$ git status
HEAD detached at v2.1.2
nothing to commit, working directory clean

Probably another problem elsewhere -- the audio is working tho.

**Comment by wwmm** [comment]
@dx9s when you run PulseEffects from the command line is there any error printed?

**Comment by dx9s** [comment]
Yes but I don't remember the details, I can collect them -- not sure where a safe place to dump lots of text is ?! Pasting inline?

**Comment by dx9s** [comment]
where pulseeffects is in my local bin as:
`( cd /home/dx9s/src/pulseeffects ; GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects )`

`$ pulseeffects 
15:56:18.705 - PulseEffects - INFO - pulseaudio context started
15:56:18.705 - PulseEffects - INFO - connected to server: unix:/run/user/1000/pulse/native
15:56:18.705 - PulseEffects - INFO - server protocol version: 30
15:56:18.705 - PulseEffects - INFO - pulseaudio version: 8.0
15:56:18.705 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1f.3.analog-stereo
15:56:18.705 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
15:56:18.706 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
15:56:18.706 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
15:56:18.706 - PulseEffects - INFO - default pulseaudio source audio format: s16le
15:56:18.706 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
15:56:18.706 - PulseEffects - INFO - loading Pulseeffects applications sink...
15:56:18.706 - PulseEffects - INFO - sink owner module index: 40
15:56:18.706 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
15:56:18.707 - PulseEffects - INFO - Pulseeffects apps sink index:17
15:56:18.707 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
15:56:18.707 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
15:56:18.707 - PulseEffects - INFO - sink owner module index: 41
15:56:18.707 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
15:56:18.707 - PulseEffects - INFO - Pulseeffects mic sink index:18
15:56:18.707 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
15:56:18.727 - PulseEffects - INFO - apps pipeline state: ready
15:56:18.728 - PulseEffects - INFO - mic pipeline state: ready
15:56:18.728 - PulseEffects - INFO - test signals pipeline state: ready
15:56:18.863 - PulseEffects - INFO - apps pipeline state: playing
15:56:18.898 - PulseEffects - INFO - pulsesrc latency-time [us]: 10000
15:56:18.898 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
15:56:18.898 - PulseEffects - INFO - pulsesink latency-time [us]: 10000
15:56:18.898 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000
Traceback (most recent call last):
  File "/home/dx9s/src/pulseeffects/PulseEffects/sink_input_effects.py", line 411, in on_message_element
    magnitudes = msg.get_structure().get_value('magnitude')
TypeError: unknown type GstValueList
Traceback (most recent call last):
  File "/home/dx9s/src/pulseeffects/PulseEffects/sink_input_effects.py", line 411, in on_message_element
    magnitudes = msg.get_structure().get_value('magnitude')
TypeError: unknown type GstValueList
Traceback (most recent call last):
[...]
Traceback (most recent call last):
  File "/home/dx9s/src/pulseeffects/PulseEffects/sink_input_effects.py", line 411, in on_message_element
    magnitudes = msg.get_structure().get_value('magnitude')
TypeError: unknown type GstValueList
15:56:36.977 - PulseEffects - INFO - test signals pipeline state: null
15:56:36.979 - PulseEffects - INFO - apps pipeline state: null
15:56:36.979 - PulseEffects - INFO - mic pipeline state: null
15:56:36.979 - PulseEffects - INFO - sinks unloaded
15:56:36.979 - PulseEffects - INFO - disconnecting pulseaudio context
15:56:36.979 - PulseEffects - INFO - pulseaudio context terminated
15:56:36.979 - PulseEffects - INFO - stopping pulseaudio threaded main loop
15:56:36.979 - PulseEffects - INFO - unferencing pulseaudio context object
15:56:36.979 - PulseEffects - INFO - freeing pulseaudio main loop object
`

**Comment by wwmm** [comment]
The error `TypeError: unknown type GstValueList` is happening because only Gstreamer 1.12 or higher has this type defined.

**Comment by dx9s** [comment]
I figured it was Gstream related (version) I just wasn't overly concerned as it only effected the visuals.

**Comment by Lukastos** [comment]
I also have trouble to get it running on Ubuntu 16.04
I couldn't install the 0.18 version of scipy and I have the same error with CubicSpline.

Any suggestion?

**Comment by wwmm** [comment]
As there is nothing I can do about missing dependencies in ubuntu I will close this issue.
