### ISSUE TITLE
No line break in UI

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#273]
![deepinscreenshot_ - _20180718203659](https://user-images.githubusercontent.com/15802528/42902078-10fbc830-8ad6-11e8-8369-3df8ef0b8179.png)

The text in Russian does not fit the wifth and is just cut. There should be a line break.

To run PulseEffects in Russian:
`$ env LANG=ru_RU.utf8 pulseeffects` (you may have to generate this locale)

**Comment by mikhailnov** [comment]
As for the error of loading the file in the top, why is it there while I did not try to load it.

**Comment by wwmm** [comment]
I will take a look. But I have no idea if GTK allows line breaks there.

There is still room for improvements in the convolver error messages. Whenever the convolver is initialized it reads the file path saved in the configuration and tries to load it. Based on the images I would say that this variable had an empty string(that is what someone that never chose a file would have) or a path to a file that was deleted. I will try to remember to add different messages for each case

**Comment by mikhailnov** [comment]
In my case the file had never been chosen

Also, please don't forget about https://github.com/wwmm/pulseeffects/issues/181. There is a lot of spare place in the UI, some guides what the effect does can be placed there. (displaying help when the mouse is over an element of the UI is not a very good idea because it isn't very usable on touchscreens)

**Comment by wwmm** [comment]
I did not found a way to do line break or other solution that wouldn't hide part of the text. So I decided to reduce the original english text to just `Import`.

**Comment by mikhailnov** [comment]
How will users understand what is being imported?

**Comment by wwmm** [comment]
It is not ideal but that dialog is shown after clicking on the `Import Impulse` button.

Usually when this happen on ordinary gtk label the way to go is ellipsize the text. But this would hide the text that doesn't fit. The same as letting it be cut. I tried to find something specific to gtk dialog titles but I found nothing

**Comment by wwmm** [comment]
I also tried to add a `\n` after the word `Import` hoping that this would force a line break but this did not happen

**Comment by wwmm** [comment]
Did the whole title was shown when you increased the dialog window size? If I force a very big english title the text is ellipsized(... at the end and part of the text is cut). But when I resize the dialog window the whole text is shown.

**Comment by wwmm** [comment]
![screenshot from 2018-07-24 15-12-27](https://user-images.githubusercontent.com/16225172/43157538-bb850632-8f53-11e8-9dc4-9b8597898142.png)
![screenshot from 2018-07-24 15-12-21](https://user-images.githubusercontent.com/16225172/43157542-bd0c7986-8f53-11e8-9100-7533a4e2790f.png)

**Comment by wwmm** [comment]
I think it would not be the end of the world for the user to just resize the dialog

**Comment by wwmm** [comment]
With the pt_BR translation a resize is also enough to fix the issue
![screenshot from 2018-07-24 15-19-49](https://user-images.githubusercontent.com/16225172/43157963-d0e95c8e-8f54-11e8-955d-0867d403f4de.png)
![screenshot from 2018-07-24 15-20-01](https://user-images.githubusercontent.com/16225172/43157964-d1098d6a-8f54-11e8-81e4-7880ab31c500.png)

**Comment by wwmm** [comment]
I restored the title text to its original value

**Comment by wwmm** [comment]
Closing as it is just a matter of resizing the window
