### ISSUE TITLE
Button to switch UI to English

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#274]
I've talked to a sound engineer about PulseEffects localization, he says that he does not understand some of the translations because in the professional sphere anglicisms are used.

E.g.
I translated 'limiter' as 'Подстройка уровня звука', but he is used to 'лимитер' which is anglicism and is pronounced as [limiter]. 

I wanted people which are not professional sound engineers like myself to understand the purpose of the effect, but he wanted to see terminology that he is used to.

So, for him it may be better to run PulseEffects in English (`env LANG=c pulseeffects` or `env LANG=POSIX pulseeffects`), but he does not know about this POSIX shell variables.

A button to switch UI to English would be a good solution.

**Comment by wwmm** [comment]
Ok. I will try to find out how this could be done GTK. I never thought about changing the languages on the fly.

**Comment by mikhailnov** [comment]
may be not on the fly, but relaunching with saving the path to the executable (because the executable may be not in `$PATH`) and all environmental variables + adding env `LANG=c`

**Comment by wwmm** [comment]
It seems there isn't much demand for this.
