### ISSUE TITLE
meson_version: '>= 0.46.0'

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#280]
Is `meson_version: '>= 0.46.0'` really needed? If yes, I will have to build meson 0.47 from ubuntu 18.10 in the PPA for ubuntu 18.04 as ubuntu 18.04 has 
```
$ meson --version
0.45.1
```

meson minimal version was changed in https://github.com/wwmm/pulseeffects/commit/6cbf48e91df712b9df1cfdb90516b61b84d9bfaa#diff-969b60ad3d206fd45c208e266ccfed38 , is it really required or you changed it just to be sure that it works?

**Comment by mikhailnov** [comment]
`src/convolver/meson.build:5:7: ERROR: Unknown method "has_link_argument" in object.`
yes, it does not build with meson 0.45

**Comment by mikhailnov** [comment]
well, I can just patch it

**Comment by wwmm** [comment]
we are back to meson `0.40`. Let's see if people will have trouble. But considering that I use quite recent C++ features I think that people with old compilers are not even capable of compiling PulseEffects

**Comment by mikhailnov** [comment]
Thank you. People with old compilers probably don't use newest gtkmm and other required newest dependencies.
