### ISSUE TITLE
duplicates in .po files

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#282]
e.g.
help/ru/ru.po:149
`msgid "<em style=\"strong\">Attack</em>"`
and
po/ru.po:320
`msgid "Attack"`

are the same but with different formatting. It requires tracking manually that the word 'Attack' is translated in the same way in both cases.

**Comment by wwmm** [comment]
Honestly I have no idea about how to deal with this. I never did documentaion translation before. Maybe @AsavarTzeth has some previous experience with this

**Comment by wwmm** [comment]
Up to now what I did was replicating what I found in `gnome-calculator` sources [https://github.com/GNOME/gnome-calculator/tree/master/help](https://github.com/GNOME/gnome-calculator/tree/master/help)

**Comment by wwmm** [comment]
the option ` its:withinText="nested"` helped to fix that

**Comment by wwmm** [comment]
I have just finished the translation to portuguese and I did not notice this problem anymore. I think we can close this

**Comment by mikhailnov** [comment]
Now there are exact duplicates, e.g.
`msgid "Detection Likelihood"`
exactly the same strings in po/ru.po and help/ru/ru.po

**Comment by wwmm** [comment]
As far as I understand the translation framework for help files is totally different from the one used for the app interface. They do not talk to each other. For example Meson exposes different commands to update the templates. For the usual translations it is `pulseeffects-pot` and `pulseeffects-update-po` but for the help files it is `help-pulseeffects-update-po` and `help-pulseeffects-pot`.

In all gnome projects sources that I took a look the situation was the same.
