### ISSUE TITLE
mda-lv2 is not installed

### ISSUE THREAD

**Issue by artxki** [wwmm/pulseeffects#287]
On start, I see a warning (and a non-working plugin):
```
pulseeffects-WARNING **: 18:05:37.250: loudness plugin was not found!
```

I'm using: `Ubuntu 18.04.1 LTS`
`pulseeffects` are installed from: `ppa:mikhailnov/pulseeffects`

Installing `mda-lv2` manually solves the issue:
```
sudo apt install mda-lv2
```

**Comment by wwmm** [comment]
This plugin is optional. So this behavior is expected

**Comment by wwmm** [comment]
Done.
