### ISSUE TITLE
Add an option to easily return to the default settings

### ISSUE THREAD

**Issue by gnomelibre** [wwmm/pulseeffects#29]
After modifying some settings and without thinking of saving my configuration, I didn't find any option to return to the default settings.

**Comment by wwmm** [comment]
Hi

At least for the input limiter, compressor, reverb and equalizer this can be done in their configuration menu. Or are you thinking about the options in the main configuration menu?(where buffer and latency configuration are)

**Comment by gnomelibre** [comment]
Yes, an option in the hamburger menu for all settings, so you don't have to reset them one by one.

**Comment by wwmm** [comment]
ok, I will try to add that in the next version.

**Comment by wwmm** [comment]
I added an option to reset everything in the latest version (1.6.7)

**Comment by gnomelibre** [comment]
You are the best \o/

Thank you very much
