### ISSUE TITLE
Ubuntu package for Xenial plz

### ISSUE THREAD

**Issue by blackoutworm** [wwmm/pulseeffects#291]
Hi there.
Could you ask whoever's running the PPA to add Xenial please?
Because the only distros there now are brand new. 
And a lot of Ubuntu/Debian based distros such as Linux Mint are still on that version.
I doubt that most people even have them yet.
It is my personal opinion that a PPA should have at least the 4 latest distros.
Thank you.

**Comment by wwmm** [comment]
Hi! I think that @mikhailnov didn't have a choice. PulseEffects needs recent versions of a few libraries and plugins. I think that older distributions will have to be supported through flatpak.

**Comment by mikhailnov** [comment]
I'm running the PPA. Yes, pulseeffects can't be built and ran on ubuntu <18.04 and will never be available for 16.04 (xenial) as a fully native deb package.

Linux Mint 19 is already on Ubuntu 18.04 bionic.

**Comment by blackoutworm** [comment]
Oh I see. Is there a way I can run it on Mint 18.3?

**Comment by mikhailnov** [comment]
Try flatpak:
`sudo apt install flatpak`
and then https://github.com/wwmm/pulseeffects/blob/master/README.md#flatpak

**Comment by blackoutworm** [comment]
@mikhailnov Thanks but flatpak install flathub com.github.wwmm.pulseeffects gave me error: fsetxattr(user.ostreemeta): Operation not supported.
Any idea?

**Comment by mikhailnov** [comment]
No. Maybe @AsavarTzeth can help /(he buids Pulseeffects in flatpak)

**Comment by mikhailnov** [comment]
Aa, did you run it as root? `sudo flatpak install flathub com.github.wwmm.pulseeffects`

**Comment by blackoutworm** [comment]
@mikhailnov ah no I didn't.
Silly me 😀
Thanks for your help guys!
Thank you so much :+1:

**Comment by AsavarTzeth** [comment]
You should not need to run it with root privileges, unless your distribution excludes or modifies the flatpak PolicyKit.

If it does, then yes you need to run as root or use sudo. That is as long as use the system-wide (`--system`) installation, which is the default.

Whenever possible, prefer not using `sudo`. It may modify you environment and exclude some variables flatpak relies on, among other things.

**Comment by mikhailnov** [comment]
Ubuntu's default `sudoers` config is OK, needed variables are cleaned and everything will be OK. As far as I remember, flatpak makes system-wide installation unless `--user` is specified.

Debian and Ubuntu have PolicyKit 0.105, but starting from 0.106 PolicyKit has a newr format of rules which are written in javascript and parsed via `mozjs`. In Debian new PolicyKit are only in `Debian experimental`, they are built regularly but even debian sid does not migrate to newer Polkit, I don't know why. 

And I don't know  how flatpak works in Ubuntu 16.04

**Comment by mikhailnov** [comment]
I wanted to say that upstream ftlatpak's policykit rules may just not work in ubuntu

**Comment by AsavarTzeth** [comment]
I never claimed the `sudoers` file was not OK. All I am saying is that, when the environment is changed (cleaned), some env vars that flatpak expects may not be set.

I think Flatpaks PolicyKit rules worked last I tried on Ubuntu. But I always use the flatpak PPA and I don't use 16.04 anymore. So things may indeed have changed.

In any case I would suggest you check the flatpak issue tracker or ask in irc or the mailing list.

**Comment by blackoutworm** [comment]
Okay I solved this like 4 posts ago, so why is the thing still open?

**Comment by wwmm** [comment]
It is not open :-) GitHub allows posts in closed issues

**Comment by AsavarTzeth** [comment]
And sone of us are on vaction, and won't check their email every day ;)

Also 4 days ago? It says you opened it 1 day ago.

**Comment by blackoutworm** [comment]
@wwmm I know. That's weird though.
Kinda defeats the whole purpose of having an open/closed system.
