### ISSUE TITLE
Not an issue: Impulse Convolver Format

### ISSUE THREAD

**Issue by servimo** [wwmm/pulseeffects#294]
As the tittle says: what are the formats accepted? I tried ".wav" and nothing appears to select.

**Comment by servimo** [comment]
OK, I just found the answer to my question in the changelog:
"The impulse response file import dialog also has a filter (.irs). In case your response file is ".wav" just rename it to ".irs"."

**Comment by servimo** [comment]
I just found some Convolver Impulse in this page:
https://www.sjeng.org/foobar2000.html
They are in ".wav" format, some of them are not in stereo, after I convert and rename to "irs", works great, really. 
What a nice effect

**Comment by wwmm** [comment]
Good to know it is working :-) For now only stereo impulses are supported. But as you noticed it is just a matter of converting them to stereo. As most convolvers use the `irs` extension I decided to do the same. This way the user will not try to load an ordinary wav file.

I added the link you found to a section in PE wiki

**Comment by servimo** [comment]
I will upload them to Mega as soon as I finish the conversion

Em qui, 2 de ago de 2018 12:32, Wellington Wallace <notifications@github.com>
escreveu:

**Comment by wwmm** [comment]
Ok. Feel free to update the [wiki](https://github.com/wwmm/pulseeffects/wiki/Impulse-Responses) with the new link

**Comment by servimo** [comment]
I will not upload those Impulse Response because some of them are the same as the ones found on this link (http://vipersaudio.com/blog/?page_id=115) which appear in the page of Impulse Responses from PulseEffects as the first link as "Official IRS Starter Pack".
