### ISSUE TITLE
Limit effects to audio device/Device-specific profiles

### ISSUE THREAD

**Issue by jonas2515** [wwmm/pulseeffects#295]
It would be great if PulseEffects would support device-specific profiles or could turn on and off depending on the output device.

This would be especially useful for people using PulseEffects to adjust the sound of internal speakers on laptops. As soon as a headphone is being used, those adjustments aren't needed anymore and have to be manually turned off at the moment.

**Comment by wwmm** [comment]
As there is a similar issue opened with more discussion I will close this one. Anyone comeing here should follow #398
