### ISSUE TITLE
pulseeffects interferes with audio recorder application

### ISSUE THREAD

**Issue by dln949** [wwmm/pulseeffects#296]
Ubuntu 18.04, gnome shell 3.28.2, pluseeffects 4.2.2 (from the ppa).  

For a long time - years - I have successfully used this application:  "Audio Recorder", found here: [https://launchpad.net/~audio-recorder/+archive/ubuntu/ppa](url)  .  I have the most current version installed, version 2.1.3~bionic.  

This application worked fine at this version before I installed PulseEffects.  Since installing PulseEffects, I have found that for Audio Recorder to work, I must first stop PulseEffects.  If I do not do that, Audio Recorder records nothing.  

How do I go about determining what PulseEffects is doing that would cause it to interefere with Audio Recorder?  

Thanks.

**Comment by dln949** [comment]
I stumbled across a solution, but I don't know if this is how things ought to be.  

I found that when I use Audio Recorder while Pulse Effects is running, I also need to change the source in the Pulse Audio application.  (I do not need to do that when Pulse Effects is not running.)  

I don't know if I should close this - It works, but I don't know if this is how it is supposed to be.  If it is, it can be closed.  If not, then I suppose there is some kind of problem.

**Comment by wwmm** [comment]
Hi! PulseEffects is capable of applying effects to application that records audio at the same time it does that for apps output. So if you have the option `Enable All Applications` turned on in the settings menu PulseEffects will definitely interfere with your app. Something you can do is using the per app switch to turn off effects for your app when it is running 
![screenshot from 2018-08-03 11-18-29](https://user-images.githubusercontent.com/16225172/43647870-472b7ee2-970f-11e8-9b5c-6b2fbe6d6c6a.png)

**Comment by wwmm** [comment]
Click over the mic button at the top left corner of the window to get to the place where you can switch off effects for your app

**Comment by wwmm** [comment]
When you switch off the app it has nothing to do with PE anymore. It now talks directly to pulseaudio. It is the same as closing PulseEffects. So it doesn't matter which values the settings have. If you had noises even with the app switched off something else happened. Maybe the noises were introduced because the device the app was recording from was changed on the fly(that is what the switch button does). Try to disable the `Enable All Applications` in the main menu and see if the app starts disabled.

If you let the app enabled you may have noises depending on the values for buffer and latency in the pulseaudio section of PE main menu. It will depending on your source device.

The main PulseEffects audience has always been the user between the average and the very advanced (musicians audio engineers, etc). But your case should not be problem.

**Comment by dln949** [comment]
Your latest suggestions help me, THANK YOU for your kindness.  

Here is what I discovered:  

Using the "switch" (the microphone button) resulted in very highly distorted output as I described above.  

When I instead disabled the "enable all applications" setting, the output was much better, but still quite unacceptable quality.  

When I left the "enable all applications" setting enabled, but then turned off (in PulseEffects) the application from which the sound was coming, again the output was much better, but still quite unacceptable quality.  

When I disabled the "enable all applications" setting, AND turned off (in PulseEffects) the application from which the sound was coming, the resulting output was perfect.  

Does this result surprise/bother you?  

Well, I now know what I need to do to make audio recording work while PulseEffects is installed and running.  I can live with this, so I leave it up to you if you want to pursue this further (in case you think that this reveals some kind of problem), or if you want to close this issue, I am fine with either decision by you.

**Comment by wwmm** [comment]
I think that your app and your source device need `buffer` and `latency` values that are different than the default. Unless you want PulseEffects to apply effects to the material you are recording the effort to find these "good values" will not be worth

**Comment by dln949** [comment]
thank you again.  I am not going to try that - I don't even know what "buffer" and "latency" mean in the context of audio recording, so I would have no idea of what I was doing.  I agree, it is just easier for me to temporarily "disable" PulseEffects.

**Comment by mikhailnov** [comment]
> I found that when I use Audio Recorder while Pulse Effects is running, I also need to change the source in the Pulse Audio application. (I do not need to do that when Pulse Effects is not running

That's https://github.com/wwmm/pulseeffects/issues/99

PulseAudio 12 is available in a separate PPA (https://github.com/wwmm/pulseeffects/issues/99#issuecomment-401398712) and I will push it into the main pulseeffects PPA today.

**Comment by OvermindDL1** [comment]
> PulseAudio 12 is available in a separate PPA (#99 (comment)) and I will push it into the main pulseeffects PPA today.

Aaaand this broke Kubuntu, please don't do that if possible?  :-(

Specifically KDE's volume GUI plugin requires PA11 (it will be updating in the next major version), and when this PPA updated to PA12 then at the behest of apt (admittedly with a warning about it, not that users always follow that as based on my going around recently fixing people's installations) multiple people updated and their system sound stopped working.

Why is pulseaudio in the PPA for pulseeffects at all I have to ask though...  It caused me so much work fixing multiple people...  :-(

**Comment by mikhailnov** [comment]
> Specifically KDE's volume GUI plugin requires PA11

It does not. It requires pulseaudio-module-gconf, which **was** missing in the PPA builds. It does not require PA 11 directly.

I fixed this issue in the PPA 5 days ago https://gitlab.com/nixtux-packaging/pulseaudio-ubuntu/commit/ef8562fbbd74d715024dc4e5c4b5f9e59830bda2#2e7113fd164303faf37d5e47797c37143dee6aa6_28_28 by building pulseaudio-module-gconf and there are no more conflicts with `plasma-pa` now.

Please update and check.

**Comment by mikhailnov** [comment]
The reason was that I took pulseaudio 12 from ubuntu 18.10 and built it for 18.04, but pulseaudio's upstream deprecated module-gconf and ubuntu 18.10 dropped it in favor of module-gsettings as a replacement. I fixed it by rebuilding pulseaudio with both gconf and gsettings to make everthing happy.

The reason for such a big update was https://github.com/wwmm/pulseeffects/issues/99 which is really annoying.

**Comment by OvermindDL1** [comment]
> Please update and check.

Awesome, I'll unpin one of their systems when they go to lunch and test.  ^.^;

> ubuntu 18.10 dropped it in favor of module-gsettings as a replacement.

Which is really a good thing, gconf is ancient and dead and unmaintained...

> which is really annoying.

Heh, saw that one yeah.  ^.^;

Thanks though, I'll report back if further issues.  I guess they just had really bad timing between the PPA updates at that time (it was indeed last week).  :-)
