### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by mbb78** [wwmm/pulseeffects#3]
Hi!

Just tried it and it's looking very good! Thanks!

I'd just like to make some suggestions:
1. Ability to save/load configs.
2. Ability to apply different configs to different streams.

Cheers,

**Comment by wwmm** [comment]
Hi!

I agree. I think saving/loading configs to/from a folder like "~/.config/PulseEffects" will be easy to implement. Different configs for different streams will be a little more complicated... I will start with the first suggestion. Thanks for testing! :)

**Comment by wwmm** [comment]
I added the option to save/load user defined settings for limiter, compressor, reverberation and equalizer plugins in PulseEffects version 1.1.3 :)

**Comment by mbb78** [comment]
Works perfectly, thanks!
