### ISSUE TITLE
Better installation instructions for Ubuntu 

### ISSUE THREAD

**Issue by thenewnano** [wwmm/pulseeffects#30]
I know this is not an issue but would save me almost an hour if it was added into the readme
`git clone https://github.com/wwmm/pulseeffects.git`
`cd pulseeffects`
`sudo python3 setup.py install`
`sudo cp -r share/* /usr/share/`
`sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`

probably a  sudo apt install "the list of the dependencies" if they are  missing.

**Comment by wwmm** [comment]
Hi I have updated the readme with these steps.

**Comment by thenewnano** [comment]
I just installed this on my main DJing computer, new ubuntu installation and had to check around for all dependencies, this can be added to the guide also recommendation to run pulseeffects from terminal as it will throw error messages that are helpful, I was missing swh-pugins at the last step somehow :
 
sudo apt install swh-plugins gir1.2-gst-plugins-bad-1.0 python-cairo python-gobject python-gobject-2 ladspa-foo-plugins python3-cairo python3-scipy python3-numpy python3-nameparser

**Comment by wwmm** [comment]
Hi,

**Comment by wwmm** [comment]
Hi

As I do not use ubuntu it is complicated for me to know all the details involved to have PulseEffects running in this system. I also don't know if the readme is the best place for a step by step specific for each distro. Would the wiki page be a good place for this? Maybe with a link to it in the readme... In any case I never used this wiki function that github offers so I do not know how good it is for a collaborative guide writing

**Comment by thenewnano** [comment]
@wwmm  I was intending to write there, I mean even if you use Ubuntu you still can't cover all other distros, and distros upgrade and stuff change, I read about your application in OmgUbuntu blog, but still I would like you to enable the Wiki and we users will maintain it. 
swh-plugin for instance is something I saw in your comments for the Gentoo users, so all distros somehow have cross connections and in a Wiki page we will sort it out. 
I know many people use other solutions for DJing but I still prefer the simplicity of PulseAudio as the defauld soluion in my distro than JACK and other solution, I just don't need that performance threre.

**Comment by thenewnano** [comment]
Maybe you open up the wiki for public and see if it works itself out https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by wwmm** [comment]
Ok.  I changed the wiki permissions. It should be public now :-)
