### ISSUE TITLE
No sound when pulse effects is running and audio from FB Messenger in Rambox

### ISSUE THREAD

**Issue by dln949** [wwmm/pulseeffects#302]
Ubuntu 18.04, Pulse Effects 4.2.2 from the Ubuntu repository, and Rambox ( [https://github.com/ramboxapp/community-edition](url) ) 0.5.17.  

Before I ever even began using PulseEffects, audio from within Rambox - e.g., an audio file sent via Facebook Messenger and accessed from within Rambox - worked fine.  

Now with Pulse Effects running, I hear no audio from audio files using Rambox.  

I noticed that in PulseEffects Rambox does not even appear as an application, even though in Pulse Effects I have it set to enable all applications.  

How do I fix this problem?  

Thanks.

**Comment by wwmm** [comment]
Try to paste here the information mentioned at [Reporting Bugs](https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs). For now it is not necessary to use the steps in the advanced section.

If this app is not shown in PulseEffects window it should not have its output intercepted by PulseEffects. If it is then it is shown and removed very fast so you can not see it there

**Comment by wwmm** [comment]
`Rambox` isn't present in the output of PulseEffects or in Pavucontrol window. Was it running when you took the logs?

**Comment by wwmm** [comment]
If possible try to save the logs to a file and attach them here in a similar way you did with the images. This way we will be able to have the logs without too much scroll in the page

**Comment by dln949** [comment]
You are correct, Rambox was not running.  I just followed the instructions, I didn't realize Rambox needed to be running.  So, here it all comes again - as screenshots, as you requested.....  

![3-1](https://user-images.githubusercontent.com/8601150/44314612-d10b9880-a3e0-11e8-8840-67ed90319ea8.png)
![3-2](https://user-images.githubusercontent.com/8601150/44314613-d10b9880-a3e0-11e8-8034-c633f750b2d8.png)
![3-3](https://user-images.githubusercontent.com/8601150/44314614-d10b9880-a3e0-11e8-9adb-3eb155799248.png)
![4-1](https://user-images.githubusercontent.com/8601150/44314615-d10b9880-a3e0-11e8-9bb9-12458ff7a226.png)
![4-2](https://user-images.githubusercontent.com/8601150/44314616-d10b9880-a3e0-11e8-96be-e97305beed35.png)
![4-3](https://user-images.githubusercontent.com/8601150/44314617-d10b9880-a3e0-11e8-8865-63c9d8562f46.png)
![5-1](https://user-images.githubusercontent.com/8601150/44314618-d10b9880-a3e0-11e8-84ea-5eb4d58c1e3a.png)
![5-2](https://user-images.githubusercontent.com/8601150/44314619-d1a42f00-a3e0-11e8-9ea6-7b8460c22000.png)
![5-3](https://user-images.githubusercontent.com/8601150/44314620-d1a42f00-a3e0-11e8-85d5-53a11b01fe89.png)
![5-4](https://user-images.githubusercontent.com/8601150/44314621-d1a42f00-a3e0-11e8-838e-3ea974baba98.png)
![5-5](https://user-images.githubusercontent.com/8601150/44314622-d1a42f00-a3e0-11e8-9136-62353f50494c.png)
![5-6](https://user-images.githubusercontent.com/8601150/44314623-d1a42f00-a3e0-11e8-8e0c-49f6cd7baeb0.png)
![5-7](https://user-images.githubusercontent.com/8601150/44314624-d1a42f00-a3e0-11e8-9706-1bfb4b3653f4.png)
![5-8](https://user-images.githubusercontent.com/8601150/44314625-d1a42f00-a3e0-11e8-8d74-985430f43169.png)
![5-9](https://user-images.githubusercontent.com/8601150/44314626-d1a42f00-a3e0-11e8-86b1-b5a587828533.png)
![5-10](https://user-images.githubusercontent.com/8601150/44314627-d23cc580-a3e0-11e8-8a60-679d41b32ce1.png)
![6](https://user-images.githubusercontent.com/8601150/44314628-d23cc580-a3e0-11e8-8ff0-c9f135ef7faf.png)
![7-1](https://user-images.githubusercontent.com/8601150/44314629-d23cc580-a3e0-11e8-8b76-2c01730e05bc.png)
![7-2](https://user-images.githubusercontent.com/8601150/44314631-d23cc580-a3e0-11e8-92b1-5c8ecd66fb47.png)
![7-3](https://user-images.githubusercontent.com/8601150/44314632-d23cc580-a3e0-11e8-9c53-56a691956e17.png)
![7-4](https://user-images.githubusercontent.com/8601150/44314633-d23cc580-a3e0-11e8-9580-a78819f03fe8.png)
![7-5](https://user-images.githubusercontent.com/8601150/44314634-d23cc580-a3e0-11e8-9887-5d7a38895008.png)
![7-6](https://user-images.githubusercontent.com/8601150/44314635-d23cc580-a3e0-11e8-9cfd-e1126f0fb7b3.png)
![7-7](https://user-images.githubusercontent.com/8601150/44314636-d2d55c00-a3e0-11e8-92d5-c3b30fe8ceac.png)
![7-8](https://user-images.githubusercontent.com/8601150/44314637-d2d55c00-a3e0-11e8-8864-6cf7a0c9db6f.png)
![7-9](https://user-images.githubusercontent.com/8601150/44314638-d2d55c00-a3e0-11e8-97da-3312d555d5b2.png)
![7-10](https://user-images.githubusercontent.com/8601150/44314639-d2d55c00-a3e0-11e8-96be-870c54dcd10c.png)
![7-11](https://user-images.githubusercontent.com/8601150/44314640-d2d55c00-a3e0-11e8-81a7-df1affc46769.png)
![8](https://user-images.githubusercontent.com/8601150/44314641-d2d55c00-a3e0-11e8-9b6f-270fc7011e00.png)
![9-config](https://user-images.githubusercontent.com/8601150/44314642-d2d55c00-a3e0-11e8-9b86-a05034c280c1.png)
![9-input-1](https://user-images.githubusercontent.com/8601150/44314643-d2d55c00-a3e0-11e8-90d9-cec75ee5b292.png)
![9-input-2](https://user-images.githubusercontent.com/8601150/44314644-d36df280-a3e0-11e8-940d-13a9de93e2c8.png)
![9-input-3](https://user-images.githubusercontent.com/8601150/44314645-d36df280-a3e0-11e8-820f-78767cdabf59.png)
![9-input-4](https://user-images.githubusercontent.com/8601150/44314646-d36df280-a3e0-11e8-9527-f175e73ebc0c.png)
![9-output-1](https://user-images.githubusercontent.com/8601150/44314647-d36df280-a3e0-11e8-954c-24f5caffbfe7.png)
![9-output-2](https://user-images.githubusercontent.com/8601150/44314648-d36df280-a3e0-11e8-91aa-0f65ce664209.png)
![9-output-3](https://user-images.githubusercontent.com/8601150/44314649-d36df280-a3e0-11e8-9753-cf440bf1584a.png)
![9-playback](https://user-images.githubusercontent.com/8601150/44314650-d36df280-a3e0-11e8-913e-56cf540d04ab.png)
![9-recording](https://user-images.githubusercontent.com/8601150/44314651-d36df280-a3e0-11e8-9b07-2a7315e2f6ed.png)

**Comment by wwmm** [comment]
Sorry. What I meant was to have the logs in txt file and attached like the images. In any case there is no need to upload them again. I have the images in my e-mail.

**Comment by wwmm** [comment]
How does `Rambox` works? Although it is running there is noentry related to it in in the logs or in pavucontrol playback tab. As far as the info you provided tell there was no audio app active in PulseEffects. When no app is playing audio PulseEffects remains paused. So my guess is that `Rambox` is not like a music or video player and does not plays audio continually.

I don't know how easy is to take logs when `Rambox` is actually playing audio. But this is the only way the logs will be helpful. There is no need to take all the logs again. I think that in your case the output of PulseEffects when executed from the command line and pavucontrol playback tab will be the ones with the most interesting information

**Comment by dln949** [comment]
Thank you for your help.  I fear I've wasted your and my time, I am very sorry about that.  I am quite confused now - Now Rambox produces no audio even when I have not started PulseEffects.  Now I  suspect that the problem with Rambox only coincidentally began when I also started using PulseEffects.  I think I need to close this, and pursue this problem strictly with Rambox.
