### ISSUE TITLE
Building in chroot broken by AppStream verification

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#306]
```
/usr/bin/appstream-util validate-relax data/com.github.wwmm.pulseeffects.appdata.xml
--- stdout ---
data/com.github.wwmm.pulseeffects.appdata.xml: FAILED:
• url-not-found         : <screenshot> failed to connect: Cannot resolve hostname [https://raw.githubusercontent.com/wwmm/pulseeffects/master/images/appdata-screenshot-01.png]
• url-not-found         : <screenshot> failed to connect: Cannot resolve hostname [https://raw.githubusercontent.com/wwmm/pulseeffects/master/images/appdata-screenshot-05.png]
• url-not-found         : <screenshot> failed to connect: Cannot resolve hostname [https://raw.githubusercontent.com/wwmm/pulseeffects/master/images/appdata-screenshot-04.png]
• url-not-found         : <screenshot> failed to connect: Cannot resolve hostname [https://raw.githubusercontent.com/wwmm/pulseeffects/master/images/appdata-screenshot-02.png]
• url-not-found         : <screenshot> failed to connect: Cannot resolve hostname [https://raw.githubusercontent.com/wwmm/pulseeffects/master/images/appdata-screenshot-03.png]
--- stderr ---

```
https://launchpadlibrarian.net/384677539/buildlog_ubuntu-bionic-amd64.pulseeffects_4.2.8-1~bionic1_BUILDING.txt.gz 

@AsavarTzeth

**Comment by mikhailnov** [comment]
Fixed it by adding `--nonet`.

**Comment by AsavarTzeth** [comment]
Well you could just not build the test target, or is Debian tools doing that by default?

**Comment by mikhailnov** [comment]
Debian runs tests by default. That's a good idea to avoid pushing broken packages into the repository (and for 'continious integration').

22 августа 2018 г. 10:58:51 GMT+03:00, Patrik Nilsson <notifications@github.com> пишет:

**Comment by AsavarTzeth** [comment]
Oh I agree that its a good idea, but in this specific case these are the only tests. So here it would work as a workaround.

**Comment by mikhailnov** [comment]
I did not fully understand, what do these requiring network tests do? Thay download screenshots, what for?

22 августа 2018 г. 10:58:51 GMT+03:00, Patrik Nilsson <notifications@github.com> пишет:

**Comment by AsavarTzeth** [comment]
To validate the size and format of the screenshots so that they can displayed properly in frontends such as GNOME Software.

**Comment by AsavarTzeth** [comment]
Basically, a frontend will pull in images from these URL's and unless verified, there is no way for the frontend to know if it will work or look right.

**Comment by AsavarTzeth** [comment]
Although, now that I think about it, these screenshots have so far only ever been updated by me and I do test them well.

If `--nonet` only affects screenshots I suppose it would not be as big of a deal if those were not tested at build time. It just means it will have to be verified manually upon updates.

The man page isn't to clear on what tests `--nonet` disables. I will try to dig some more to find out.

**Comment by AsavarTzeth** [comment]
I agree they need to be updated and ideally unified. And yes there are quite a list of restrictions that are horrible to work with.

I have more questions on that issue. Perhaps I should open an issue about unifying the screenshots? I could add a lot of information and maybe a todo list?

**Comment by wwmm** [comment]
If there are more details to be discussed about the screenshots it is better to open another issue

**Comment by mikhailnov** [comment]
Why can't the screenshots be taken from source code instead of downloading them from GitHub?

**Comment by wwmm** [comment]
good question

**Comment by AsavarTzeth** [comment]
What? I fail to see your reasoning.

The screenshots are stored in the source code, on GitHub. They have to be hosted somewhere, and downloadable from a web server.

Or aare you seriously suggesting that frontends, such as GNOME Software, download and store the entire source just to show a few screenshots? You cannot assume it is available locally already.

**Comment by AsavarTzeth** [comment]
Oh you mean for the verification process? Well think about what I said above.

Checking that the active and link is working is part of the validation.

**Comment by wwmm** [comment]
If that is how it works the online validation makes sense.

**Comment by AsavarTzeth** [comment]
Haha glad I somehow got something through!
