### ISSUE TITLE
Pulseeffects not working after Pulseaudio update

### ISSUE THREAD

**Issue by SzDavidHUN** [wwmm/pulseeffects#307]
Hello!

__TL;DR__ If the app isn't going trough PE it's working, if it going trough, it doesn't. Nothing comes out of speaker, the graph in PE shows nothing, pavucontrol "glitches", and I got a ton of debug messages.

This night I've updated my computer, there was a pulseaudio update and some other audio stuff too. After a restart PE stopped working. Checked with pavucontrol, maybe something easy, but on the recording tab PE is flashing like crazy, there is something PulseEffects(mic) selected, which is a but suspicious, but can't interact with it, disappears and reappears many time a second. Now PulseEffects(App) is selected, but don't know why, still doesn't work. (See screenshot below)
Then I've tried to rollback my config files, reinstall pe, clear .config/pulse, etc (and restart computer after every try), but nothing.
Opened PE in terminal, it complained about not all plugins installed, so I've taken care, and now I only got one message.
`(pulseeffects:2004): GLib-GIO-CRITICAL **: 00:49:22.381: g_settings_bind_with_mapping: assertion 'G_IS_OBJECT (object)' failed`
After starting playing sound, it gives more, I've linked it in the basic logs. It puts quite a lot of, just like in pavucontrol the app showing up and disappearing.
Tested with Firefox, Chromium, and Spotify.

Linux Mint 19 with Cinnamon 3.8.8
Install method: https://github.com/wwmm/pulseeffects/wiki/Package-Repositories#debian--ubuntu
PE Version: 4.2.8

Basic logs are here:
https://gist.github.com/SzDavidHUN/9beddbeaf506757908c1070ff0ef4e6b

Updated packages:
![image](https://user-images.githubusercontent.com/3109204/44434600-54c5b080-a5ac-11e8-88d2-1323bc522c9e.png)

Pavucontrol:
![image](https://user-images.githubusercontent.com/3109204/44434901-f7cafa00-a5ad-11e8-9d63-1006a5bed1e4.png)

Thanks in advance for your help! :)

**Comment by wwmm** [comment]
Hi! The error related to `g_settings_bind_with_mapping` is bad. This function is used a lot in PE and that is probably the reason why you also have `Internal data stream error`. After this stream error happens there will be no sound.

So you have to find out why `g_settings_bind_with_mapping` is failing. It could be because of a problem in your `glib2` package after the system upgrade or because of a problem in PE package. @mikhailnov is everything alright in the package?

Pulseaudio 12 is not the problem. I have been using it in Arch Linux for quite some time with no problems. PulseEffects source is also not the problem. It is fine here.  So the source must be in GTK, glib2 or in ubuntu PulseEffects packages

**Comment by wwmm** [comment]
Another possibility is that one of the required GStreamer packages is corrupted on your machine. A problem with one of the plugins package could also cause `assertion 'G_IS_OBJECT (object)' failed`

**Comment by gobozov** [comment]
Same issue, fresh mint 19 cinnamon.

**Comment by AsavarTzeth** [comment]
Well you could try the Flatpak, if for no other reason than to eliminate the possibility of distribution specific issues. Knowing if its a distribution or application issue is always a good start before reporting an issue.

**Comment by AsavarTzeth** [comment]
Well except for the convolver plugin somehow not being found (will have to look into that) I can' see much wrong.

The original error `assertion 'G_IS_OBJECT (object)' failed` seems gone though? If so, I think you just successfully verified a distribution error :)

The theme warnings might be broken theming, for example if Mint installs some flatpak gtk theme extension (so app windows match mint theming).

**Comment by wwmm** [comment]
The package `gstreamer1.0-convolver-pulseeffects` is not used by the flatpak package but only by the debian package. @AsavarTzeth at least in native package installation PE plugins are installed in the same path as GStreamer plugins `/usr/lib/gstreamer-1.0`. I don't know what happens in flatpak. But if he was able to hear sound then at list PE `peadapter` plugin was successfully installed. This one is always enabled and can't be disabled by the user.

**Comment by wwmm** [comment]
Question for everybody having problems with the debian package. Is the package `gstreamer1.0-adapter-pulseeffects` installed? @mikhailnov it may be a bad idea to split this plugin in a independent package. I forgot to tell you this. Like I said above this plugin has to be present always

**Comment by AsavarTzeth** [comment]
Yeah I know, and in the case of flatpak it is `/app/lib/gstreamer-1.0`, since the app provides it. The thing is am quite sure I made sure it worked with the last version. But I will check again.

**Comment by germanoeich** [comment]
Hello. Installing the package `gstreamer1.0-adapter-pulseeffects` fixed the issue for me.

**Comment by wwmm** [comment]
Ok @germanoeich. @mikhailnov is there a way to add `gstreamer1.0-adapter-pulseeffects` as a mandatory dependency of PulseEffects? This way it would be possible to keep the adapter plugin in a separate package without users having crashes because they forgot to install it(or did not know they had to install it).

**Comment by mikhailnov** [comment]
Done. But recommended dependencies are installed automatically with default apt configuration in Ubuntu, why were they not installed on Mint?

@germanoeich and @SzDavidHUN , please show the output of
`apt-config dump APT::Install-Recommends`
from Linux Mint 19

**Comment by mikhailnov** [comment]
After today it's safe.

23 августа 2018 г. 18:20:55 GMT+03:00, Patrik Nilsson <notifications@github.com> пишет:

**Comment by SzDavidHUN** [comment]
Now with the new dependency it works. Thanks! :)
So this is when we should close the issue, right?

Btw
```
$ apt-config dump APT::Install-Recommends
APT::Install-Recommends "false";
```
Looks like that's the default setting. Or at least I didn't remember changing it.

**Comment by mikhailnov** [comment]
@wwmm most existing Mint users don't have
```
calf-plugins
zam-plugins
rubberband-ladspa
liblilv-0-0
mda-lv2
gstreamer1.0-convolver-pulseeffects
gstreamer1.0-crystalizer-pulseeffects
gstreamer1.0-autogain-pulseeffects
```

By the way, sorry for a bit offtop, calf-plugins have made a new release , where all needed issues are fixed, right? or is git code still needed for all fixes?

**Comment by wwmm** [comment]
I think it is up to them to install or not these packages.

Yes calf `0.90.1` has the patches that fix the memory leak in the limiter
