### ISSUE TITLE
Default icon rendered incorrectly in Qt environments

### ISSUE THREAD

**Issue by flipwise** [wwmm/pulseeffects#308]
Hey, so I know PE got a nice blue new icon recently, but on two of my computers that I tried it's showing up completely white.

![image](https://user-images.githubusercontent.com/26850445/44479906-327e7200-a642-11e8-8d8b-630729463560.png)

I have the flatpak PE version 4.2.7 installed here. On my other computer I'm using the latest version compiled from AUR. 

When I click on 'About PulseEffects', the right icon is shown there, however.

DE is KDE Plasma.

**Comment by wwmm** [comment]
The icon shown in the about window is hardcoded and does not follow the desktop theme. But launcher icon follows the desktop theme. i don't think there is something I can do about this

**Comment by wwmm** [comment]
Now I see that it is the right icon but white. I thought that it was other icon. In any case this does not happen here in my PC with gnome and the adwaita theme. So something is broken in your system. I don't know what could be exactly.

**Comment by flipwise** [comment]
I just installed XFCE, on the same computer. It shows up properly here.

This leads me to the conclusion that the current icon is somehow incompatible with how Plasma renders icons ie. that it's rendered monochrome for some reason. I think the fix should be on this end because I've never experienced Plasma doing this with any other application icon.

**Comment by flipwise** [comment]
If I replace the icon is PE's directory with [this one](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/pulseeffects.svg), it's fine, it has color. This again leads me to believe the current svg has to be modified somehow.

**Comment by wwmm** [comment]
Any ideas @zencubic

**Comment by wwmm** [comment]
Something to have in mind is that most apps use png instead of svg. So there is always the possibility that something may be wrong in how plasma is handling a few types of svg

**Comment by mikhailnov** [comment]
svg are sometimes rendered differently by different rendering engines. Optimizing svgs by `svgcleaner` (https://github.com/RazrFalcon/svgcleaner-gui, https://github.com/RazrFalcon/svgcleaner) sometimes help. If it does, the original icon may be stored in upstream code, and svgcleaner may be included into the build process.

**Comment by flipwise** [comment]
I tried out the icon optimized by svgcleaner but it's still white. On the other hand, when I took the png from [here](https://github.com/wwmm/pulseeffects/issues/73#issuecomment-410367386) and converted it into an svg, I got the right colors. Unfortunately the svg is very choppy, I probably don't know how to make the conversion properly.

If we dig into this a bit more and see nothing can be done with the icon itself, I can submit a bug report on bugs.kde.

**Comment by wwmm** [comment]
I have no idea about what could be changed in the icon to fix this. Are KDE applications like dolphin or gwenview affected too or only plasma?

**Comment by flipwise** [comment]
Ha, Dolphin doesn't preview the icon properly either and Gwenview doesn't render color either. Could be a Qt bug. I will try to dig into this a bit more, it's not too big of a deal, don't waste your time with it :)

**Comment by wwmm** [comment]
Ok. It would be good to report this to KDE developers.

**Comment by wwmm** [comment]
I also have zero experience with this. Let's keep this open for a while and see what happens

**Comment by mikhailnov** [comment]
What is 'tidy over it'?

**Comment by zencubic** [comment]
Tidy is actually a program that keeps your source code easy readable. You can look into the source of the icon and you will hopefully see what I mean

**Comment by flipwise** [comment]
@zencubic do you mean to try out the La Capitaine theme? Tried it out now and Papirus-Adapta as well, both have their own icons for PE and both of these icons render correctly.

**Comment by zencubic** [comment]
@flipwise Yes

**Comment by flipwise** [comment]
Here is a quick way to reproduce the problem without installing Plasma or any bigger Qt apps. 

If you install `lximage-qt` and open the icon in there, it should also show up white.

**Comment by wwmm** [comment]
It happens here with lximage-qt too. At the same time it is fine in eog(eye of gnome). Very strange.

**Comment by wwmm** [comment]
Is this still a problem?

**Comment by flipwise** [comment]
Yeah, still the same with Qt 5.12.

**Comment by damian01w** [comment]
I opened PE icon in Krita, and it rendered correctly. Then, I exported it in a new SVG and voila! the new generated svg shows correctly in dolphin, gwenview and plasma menus.
