### ISSUE TITLE
Close button on About window doesn't work.

### ISSUE THREAD

**Issue by SzDavidHUN** [wwmm/pulseeffects#310]
Hi!

I was checking my version, and wanted to close the window with the close button. It doesn't close it, had to click the X in the window title. Not a big deal, but why not report it :D

Linux Mint 19 with Cinnamon 3.8.8
Install method: https://github.com/wwmm/pulseeffects/wiki/Package-Repositories#debian--ubuntu
PE Version: 4.2.8

Debug (doesn't seem to show anything relevant, but there is it):
https://gist.github.com/SzDavidHUN/7daf802356bfe7af4dadc0385ebc1994

**Comment by wwmm** [comment]
It does not happen on GNOME. I wonder if Cinnamon deals with dialog windows in a different way

**Comment by wwmm** [comment]
should be fixed in PE `4.3.0`.

**Comment by mikhailnov** [comment]
now it works in XFCE, did not work before
