### ISSUE TITLE
Ubuntu 18.04 - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by MadRussianHacker** [wwmm/pulseeffects#314]
Hi!
I'm using Ubuntu 18.04, and I installed pulseeffects via PPA:
```
sudo add-apt-repository ppa:mikhailnov/pulseeffects -y
sudo apt update
sudo apt install pulseeffects
```
But my attempts to launch it are ended with segmentation fault. How can I solve this problem?
PS. Flatpak also doesn't work ;(

**Comment by wwmm** [comment]
Try to get the basic logs as explained in [Reporting Bugs](https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs). But if you can't use both flatpak and the native package something is very wrong in your system

**Comment by MadRussianHacker** [comment]
Ok, problem solved, after restarting my pc it works!
