### ISSUE TITLE
Calf related features not working in Manjaro since update to 4.2.9-1

### ISSUE THREAD

**Issue by fullrich** [wwmm/pulseeffects#316]
Compressor, Limiter, Deesser, Filter (the only ones I'm presently using) are ghosted out and not working now since update. I've tried reinstalling both Calf and Pulseeffects; I've even restored my last Timeshift system backup, which gave me back the previous version of Pulseeffects where all was working. But then did the latest Manjaro update again (which includes latest Pulseeffects update), and I'm right back to above mentioned problem. BTW, thank you very much for Pulseeffects! I rely on it due to certain extreme sound frequency sensitivities that make unequalized audio unbarable. THANKS AGAIN!

**Comment by wwmm** [comment]
This problem is caused by a missing file in the pckage `gst-plugins-bad`. I reported it to the Arch Linux maintainers [https://bugs.archlinux.org/task/59804](https://bugs.archlinux.org/task/59804) but it was not fixed yet. It would be good to have more people commenting there so they understand there is a problem in the package

**Comment by wwmm** [comment]
For now you can download `gst-plugin-bad` [build files](https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/gst-plugins-bad) and use `makepkg` to build a package locally. Install the package `lv2` before trying to build `gst-plugins-bad`

**Comment by wwmm** [comment]
Another temporary fix would be to downgrade `gst-plugins-bad` to the previous version

**Comment by wwmm** [comment]
They fixed the bug

**Comment by fullrich** [comment]
THANKS! I'll just wait for it to come through normal updates then. :)
