### ISSUE TITLE
Unhandled exception in preset manager

### ISSUE THREAD

**Issue by sn0w** [wwmm/pulseeffects#317]
The preset manager does not handle special characters in preset names.

The current way to generate the filename is:
```cpp
auto output_file = presets_dir / fs::path{name + ".json"};
```

I tried saving a preset called `FiiO/HyperX` which generated the path `/home/sn0w/.config/PulseEffects/HyperX/FiiO.json`. There is no `HyperX` folder, so the program crashed (unhandled std::exception). PulseEffects should probably escape special characters or refuse to save such presets.

**Comment by wwmm** [comment]
Ok. I will try to take a look at that before the next release.

**Comment by wwmm** [comment]
PE `4.3.0` does not try to save presets with these special characters in the name.

**Comment by sn0w** [comment]
The patch in ff28d48ac308dc3f0caf4300cfda7ab09847fa75 is not sufficient and/or incomplete.
`: ? " < > |` are valid filename characters on linux.
Only forward slashes and `NUL` (`\0`) are forbidden.

We should probably also check if a user tries to create a preset called `.` or `..` because that will fail too.

**Comment by wwmm** [comment]
ok. I removed them from the illegal string list
