### ISSUE TITLE
PulseEffects doesn't open (4.18.5-arch1-1-ARCH)

### ISSUE THREAD

**Issue by arenmarsden** [wwmm/pulseeffects#318]
Whenever I attempt to open PulseEffects, it sets my audio settings to "PulseEffects (app)" and doesn't actually open the program. I haven't had this issue until this morning and I've tried reinstalling it through `` pakku -Syu pulseefects`` and it still doesn't do anything.

I opened it from the terminal to see the error:
``Assertion 'o' failed at pulse/operation.c:133, function pa_operation_get_state(). Aborting.
Aborted (core dumped)``

**Comment by wwmm** [comment]
Hi! which Pulseaudio version do you have? It seems to me you are affected by point `5` in [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ). But Arch Linux doesn't even load that module.

Another possibility is that you only now made the upgrade from Pulseaudio 11 to 12. In this case a reboot is necessary. In any case this error message reflects a problem in Pulseaudio and not in Pulseeffects

**Comment by arenmarsden** [comment]
> Hi! which Pulseaudio version do you have? It seems to me you are affected by point 5 in FAQ. But Arch Linux doesn't even load that module.

Another possibility is that you only now made the upgrade from Pulseaudio 11 to 12. In this case a reboot is necessary. In any case this error message reflects a problem in Pulseaudio and not in Pulseeffects

I am using pulseaudio 12.2, I haven't received any pulseaudio updates recently.

**Comment by Eonfge** [comment]
Have reproduced, even with rebooting. System:
Ubuntu 18.04
Pulse Audio 12.2
Pulse Effects 4.2.9-1~bionic

Happens both with and without `--gapplication-service`

**Comment by GabrielAlquimia** [comment]
Same here, with or without rebooting, I tried to uninstall and reinstall pulseeffects with no luck. System:
Ubuntu 18.04
Pulse Audio 12.2
Pulse Effects 4.2.9-1~bionic

Happen with and without --gapplication-service

```
Assertion 'o' failed at pulse/operation.c:133, function pa_operation_get_state(). Aborting.
Abortado (`core' generado)

```

**Comment by Kevin-at-Navigram** [comment]
Tested it on a second machine, with the same library configuration:
Ubuntu 18.04
Pulse Audio 12.2
Pulse Effects 4.2.9-1~bionic1

**Here it does work!** There are some minor differences in the config though:
- Output to 'default'
- Enable all applications 'on'

Judging by the changes you made in the last release (saving custom output channels), it seems that the error is somewhere in this functionality change.

**Comment by Eonfge** [comment]
Tested it on a second machine, with the same library configuration:
Ubuntu 18.04
Pulse Audio 12.2
Pulse Effects 4.2.9-1~bionic1

**Here it does work!** There are some minor differences in the config though:
- Output to 'default'
- Enable all applications 'on'

Judging by the changes you made in the last release (saving custom output channels), it seems that the error is somewhere in this functionality change.

**Comment by wwmm** [comment]
`Enable All Applications` off causes no problems here

**Comment by wwmm** [comment]
Just to clarify a few things `pa_operation_get_state` is a Pulseaudio function used by PE in many places. The `pulse/operation.c` file is from Pulseaudio too. The failed assertion happened internally in Pulseaudio when we asked for it to tell the state of a operation. It is not clear to me yet what could cause this assertion to fail deep inside Pulseaudio. But something I know is that the PE code that does this kind of interaction with Pulseaudio didn't have changes in many weeks.

Pulseaudio working without PE does not help much to figure out because it is totally possible for an audio app to play sound without ever calling the `pa_operation_get_state` function. Even pavucontrol working will not tell much because as far as I remember they do not use the threaded Pulseaudio api and as a result do not make calls to `pa_operation_get_state`

**Comment by wwmm** [comment]
It would be good to have the log messages printed by PE when executed in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects` to know if your crashes are happening at the same stage than the one in #327

**Comment by wwmm** [comment]
At least in #327 in this section of the log:
```
pulse_manager: loading Pulseeffects applications output sink...
pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
pulse_manager: default pulseaudio sink audio format: s32le
pulse_manager: sink loaded
pulse_manager: loading Pulseeffects microphone output sink...
pulse_manager: default pulseaudio source sampling rate: 44100 Hz
pulse_manager: default pulseaudio source audio format: s32le
pulse_manager: sink loaded
```
there is no line with `sink loaded`. This means that PE was not capable to load its sinks. That would explain a failure in `pa_operation_get_state`. The question is why in some machines the null sinks are not loading. Still can not reproduce that.

**Comment by Eonfge** [comment]
Yes it does:

> (pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.091: pulse_manager: context is connecting
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.091: pulse_manager: context is authorizing
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.091: pulse_manager: context is setting name
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.091: pulse_manager: context is ready
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.091: pulse_manager: connected to: unix:/run/user/1000/pulse/native
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.091: pulse_manager: protocol version: 32
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.092: pulse_manager: Pulseaudio version: 12.2
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.092: pulse_manager: default pulseaudio source: alsa_input.usb-2516_Sirus_Headset-00.analog-stereo
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.092: pulse_manager: default pulseaudio sink: alsa_output.usb-2516_Sirus_Headset-00.analog-surround-41
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.092: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.092: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.092: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.093: pulse_manager: sink loaded
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.093: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.093: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.093: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:4806): pulseeffects-DEBUG: 17:36:50.093: pulse_manager: sink loaded
Assertion 'o' failed at pulse/operation.c:133, function pa_operation_get_state(). Aborting.
Aborted (core dumped)

**Comment by wwmm** [comment]
In #327 the problem does not happen if PE is executed by another user on the same machine. At least there it seems that the user has permissions problems in the folder `~/.config/pulse/` causing the same error we have here

**Comment by Eonfge** [comment]
@arenmarsden and @GabrielAlquimia see this:
https://github.com/wwmm/pulseeffects/issues/327#issuecomment-417031357

Worked for me.

**Comment by mikhailnov** [comment]
Try `sudo chown -R $(username):$(username) "$HOME"`

**Comment by arenmarsden** [comment]
```(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.669: pulse_manager: context is connecting
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.670: pulse_manager: context is authorizing
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.671: pulse_manager: context is setting name
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.671: pulse_manager: context is ready
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.671: pulse_manager: connected to: unix:/run/user/1000/pulse/native
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.672: pulse_manager: protocol version: 32
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.672: pulse_manager: Pulseaudio version: 12.2
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.672: pulse_manager: default pulseaudio source: alsa_input.pci-0000_00_14.2.analog-stereo
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.672: pulse_manager: default pulseaudio sink: PulseEffects_apps
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.672: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.672: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.672: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.672: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.672: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:28680): pulseeffects-DEBUG: 23:32:27.672: pulse_manager: default pulseaudio source audio format: s16le
Assertion 'o' failed at pulse/operation.c:133, function pa_operation_get_state(). Aborting.
Aborted (core dumped)
```
Here's logs.

Also @Eonfge Didn't work.

**Comment by wwmm** [comment]
@arenmarsden your logs do not have `sink loaded` like the ones in #327. Could you test if the problem persists if you run PulseEffects in a new user account? This way we can rule out any possibility that it is a configuration problem

**Comment by arenmarsden** [comment]
> @arenmarsden your logs do not have sink loaded like the ones in #327. Could you test if the problem persists if you run PulseEffects in a new user account? This way we can rule out any possibility that it is a configuration problem

Yes it does.

**Comment by wwmm** [comment]
In this case  `dconf reset -f /com/github/wwmm/pulseeffects/` should have fixed the issue for the current user. Strange

**Comment by arenmarsden** [comment]
> In this case dconf reset -f /com/github/wwmm/pulseeffects/ should have fixed the issue for the current user. Strange

Works now, I received a update for PulseEffects a few mins ago and it opens after that.

**Comment by ahmed-h-ayyad** [comment]
I still have the same problem on Arch
it happened when I use PE as default device 

version: 4.3.4-1

**Comment by wwmm** [comment]
Do not use PE as default device. Switch on `Enable All Applications` in the configuration menu

**Comment by GabrielAlquimia** [comment]
> @arenmarsden and @GabrielAlquimia see this:
> [#327 (comment)](https://github.com/wwmm/pulseeffects/issues/327#issuecomment-417031357)
> 
> Worked for me.

Apologies for the response timing, I was on holidays. Worked for me too.  Thank you!

**Comment by makefu** [comment]
Thanks all for the investigation. `dconf reset -f /com/github/wwmm/pulseeffects/ ` worked for me!
