### ISSUE TITLE
Remember enabled applications selection

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [wwmm/pulseeffects#319]
At the moment the only two options is to enable all programs for both Input and Output or don't.

The problem is that I'd like to have it be enabled by default on all programs except a few exceptions, but in those same exceptions still have input enabled but not output. Mainly games where the small added audio delay matters but i still want to have my microphone modifications in effect.

Right now i have to manually disabled games in pulseeffects each time i launch them which is very inconvenient. It'd be very nice if it could remember your selections and apply whether the program should be enabled or disabled automatically at next start.

Also having separate "Enable all applications" switches for audio Input and Output would make sense to include

**Comment by wwmm** [comment]
PE `4.3.0` still have one `Enable All` for everything but the user can blacklist apps in the settings menu. Just write the app name as it is shown in the `Applications` entry. In PE manual(help) there is an example
