### ISSUE TITLE
Opening menus creates a slight lag (with the Adapta theme)

### ISSUE THREAD

**Issue by flipwise** [wwmm/pulseeffects#321]
Hi, 

when opening menus in PE i noticed there is a slight lag in the whole UI. This can be best seen by looking at the spectrum, which gets temporarily stuck. If clicking on a menu more than once, the lag is even more prominent.

I made a video to show what I mean: https://youtu.be/WOvChdc5F7M

PulseEffects 4.2.9 from AUR
KDE Plasma 5.13.4 (but tested with XFCE as well)

**Comment by wwmm** [comment]
Hi! At least in gnome I could not reproduce this with any menu. Maybe this is a GTK bug that somehow does not manifest in gnome. I don't see nothing in the way I use GTK that would justify these freezes.

**Comment by wwmm** [comment]
For example there is an open issue here where the about window is not closed that I am not able to reproduce in gnome. It seems to me that either gtk behaves differently in gnome or that gnome silently workaround gtk issues(or maybe even an api misuse that I am unknowingly doing).

**Comment by flipwise** [comment]
Thanks for checking it out! I said what the hell and installed GNOME here just to see :P 

GNOME on X is the same as Plasma on X to me (what I use), but the situation seems a bit better on Wayland versions of both DEs actually. 

I was also thinking it may be a GTK think. Another reason could be a weak graphics card with bad drivers, but I have a fairly mid-range one using amdgpu, which is supposed to be a pretty nice driver (unlike nvidia).

**Comment by wwmm** [comment]
I do not have a computer with an amd gpu. Only nvidia and intel and I never noticed these ui freezes. I don't think it is necessary to have a powerful gpu. There is no explicity call to opengl in PE code. But it may be a driver problem affecting gtk somehow.

There are cases where the glib main loop that updates the ui can freeze if you do not use background threads for long tasks like waiting for a download or disk io. But where we have long tasks in PE (like loading the irs file in the convolver) a secondary thread is used. And showing a menu does not trigger any long task in PE.

**Comment by wwmm** [comment]
If I am not mistaken all the menus in PE are what it is called `gtk popovers`. Maybe the way gtk handles popovers menus is not playing nice with your gpu driver. The are other applications writen in gtk that also use popovers menu like `nautilus` or `gnome calculator`. the problem is that they do not have something like a moving spectrum see. So even if they also have the problem it may not be visible

**Comment by wwmm** [comment]
I found a way to reproduce the lag. I changed the gtk theme from Adwaita(the default gnome theme) to Adapta. It is a gtk theme that follows android material design and has more effects. In my opinion if changing themes causes lags this is a bug in the theme or in gtk

**Comment by flipwise** [comment]
You are 100% right, I cannot believe that did not occur to me. Even with breeze-gtk nothing of this kind happens. 

I will report this upstream to adapta-gtk, you can close this bug or I can when I check with them.
