### ISSUE TITLE
PulseEffects not starting after update: GLib-GIO-ERROR  Settings schema 'com.github.wwmm.pulseeffects' is not installed

### ISSUE THREAD

**Issue by SzDavidHUN** [wwmm/pulseeffects#324]
Hi!

I just updated to the new version, and it didn't started. So I've started it from terminal:
```
$ G_MESSAGES_DEBUG=pulseeffects pulseeffects

(pulseeffects:4332): GLib-GIO-ERROR **: 01:42:22.451: Settings schema 'com.github.wwmm.pulseeffects' is not installed

Trace/breakpoint trap (core dumped)
```

Linux Mint 19 with Cinnamon 3.8.8
Install method: mikhailnov ppa (https://github.com/wwmm/pulseeffects/wiki/Package-Repositories#debian--ubuntu)
PE Version: Version: 4.3.1-1~bionic1

**Comment by wwmm** [comment]
@mikhailnov there is a problem with the latest ubuntu package. The schema is missing or `glib-compile-schemas` was not executed

**Comment by mikhailnov** [comment]
Wait for 4.3.1-2 to build and publish in the PPA.

It's very interesting why `export DH_ALWAYS_EXCLUDE=.git:_build:*.deb` breaks the package. I remember problems with this variable when I only began to build pulseeffects.
