### ISSUE TITLE
Cant load user preset files

### ISSUE THREAD

**Issue by Hippyjake** [wwmm/pulseeffects#33]
I have several curves made and can't load 'em. I first noticed this yesterday after an update.

**Comment by Hippyjake** [comment]
Clicking the open button does nothing and leaves the UI "working". The cancel button has no effect, the main window has to be closed to close the file dialog.

**Comment by wwmm** [comment]
Hi

Presets format changed in version 2.0.0. I had to to this to support presets for input devices. Sorry.

**Comment by Hippyjake** [comment]
Its all good. A warning when trying to load an old curve or update the file to the new standard would be awesome.

As it stands now when trying to load an old curve the app "locks up", making the file chooser unable to close or load the new standard file. Needing to close the main window to close the file chooser. Not sure if you have encountered this.
