### ISSUE TITLE
Unable to install on Debian

### ISSUE THREAD

**Issue by donjajo** [wwmm/pulseeffects#332]
I followed the instruction here https://github.com/wwmm/pulseeffects/wiki/Package-Repositories#debian--ubuntu 
Add the repo and keys, turned out the dependencies were not available in Debian repo. So I met this error

> The following packages have unmet dependencies:
>  pulseeffects : Depends: libboost-filesystem1.65.1 but it is not installable
>                 Depends: libboost-system1.65.1 but it is not installable
>                 Recommends: calf-plugins (>= 0.90.0) but it is not going to be installed
>                 Recommends: zam-plugins but it is not going to be installed
>                 Recommends: rubberband-ladspa but it is not going to be installed
>                 Recommends: mda-lv2 but it is not going to be installed
>                 Recommends: gstreamer1.0-convolver-pulseeffects but it is not going to be installed
>                 Recommends: gstreamer1.0-crystalizer-pulseeffects but it is not going to be installed
>                 Recommends: gstreamer1.0-autogain-pulseeffects but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

Using Debian sid

**Comment by wwmm** [comment]
@mikhailnov

**Comment by mikhailnov** [comment]
It's normal that ubuntu binary package is not binary compatible with Debian and its written in the wiki by the link above.
Build debian package on your localhost, it's very easy and will wok OK on Debian Sid: https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source#debian--10--ubuntu--1804

**Comment by donjajo** [comment]
Built and still faced another dependency issues:

> The following packages have unmet dependencies:
>  pulseeffects-build-deps : Depends: libgstreamer1.0-dev (>= 1.12.5) but it is not going to be installed
>                            Depends: libgstreamer-plugins-bad1.0-dev but it is not going to be installed
>                            Depends: libpulse-dev but it is not going to be installed
>                            Depends: libpango1.0-dev but it is not going to be installed
>                            Depends: libgtk-3-dev but it is not going to be installed
>                            Depends: libglibmm-2.4-dev but it is not going to be installed
>                            Depends: libgtkmm-3.0-dev but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
>

**Comment by mikhailnov** [comment]
That's strange. Show `apt policy libgstreamer1.0-dev` and `sudo apt install libgstreamer1.0-dev`

**Comment by donjajo** [comment]
Thank you. Figured out the issue were these packages:
libpcre3
libpcrecpp0v5

Don't know where the higher version was downloaded from, downgraded from the deb on Debian web repository and everything well till I was building and got this error:

> fatal error: boost/math/interpolators/cubic_b_spline.hpp: No such file or directory
>  #include <boost/math/interpolators/cubic_b_spline.hpp>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
>

**Comment by wwmm** [comment]
You need C++ boost libraries headers to compile pulseeffects. I don't know how this package is called on debian systems.

**Comment by wwmm** [comment]
I guess it is something similar to libboost-dev

**Comment by donjajo** [comment]
It is but not working, I also installed `libboost-all-dev` too but the error still persists

**Comment by wwmm** [comment]
If boost is installed but the compilation fails you must have a boost version that is old and does not have the `cubic_b_spline.hpp`. To be honest I don't know in which boost version this library was implemented

**Comment by wwmm** [comment]
it seems it was on boost `1.65` [https://www.boost.org/doc/libs/1_66_0/libs/math/doc/html/math_toolkit/history1.html](https://www.boost.org/doc/libs/1_66_0/libs/math/doc/html/math_toolkit/history1.html). Which version do you have?

**Comment by donjajo** [comment]
Seems to answer it, the one one Debian repo is 1.62 https://packages.debian.org/sid/libboost-dev
Means I have to compile and build :(

**Comment by wwmm** [comment]
In case doing this is too complicated you can try to install the flatpak package.

**Comment by mikhailnov** [comment]
https://packages.debian.org/search?searchon=contents&keywords=cubic_b_spline.hpp&mode=path&suite=unstable&arch=any
You just needed to install `libboost1.67-dev`

libboost*-dev from https://github.com/wwmm/pulseeffects/blob/master/debian/control are meta-packages that just pool libboost of the default version. It's interesting why such an old version is default in debian while it's newer in Ubuntu and debian does have a newer version, but it's not default. For now I don't know how to fix it in debian/control

> Had to extract and copy out the directory /boost/math and placed it in the src/ directory making it src/boost/math and built. It worked 
Does it run after building? Where will it find libboost.so that it linked against?

**Comment by donjajo** [comment]
Damn, didn't see that version. Thanks still :)

**Comment by mikhailnov** [comment]
@donjajo please try `git pull` and rebuilding on debian sid after https://github.com/wwmm/pulseeffects/pull/333 is merged, it should fix build dependencies for debian sid

**Comment by mikhailnov** [comment]
Or `git clone https://github.com/mikhailnov/pulseeffects.git`

**Comment by wwmm** [comment]
Merge done
