### ISSUE TITLE
Unresizeable UI split wont fit - Linux Mint19 Cinnamon 3.8.9

### ISSUE THREAD

**Issue by Canule** [wwmm/pulseeffects#339]
![pulsesfx](https://user-images.githubusercontent.com/16336062/45567540-5a847e00-b85a-11e8-8bd1-cc3922e6ad6f.png)
The width locked list of sfx on the left wont fit proper in the window.*

psfx 4.3.4
Cinnamon 3.8.9 -Mint-Y-Dark

**Comment by wwmm** [comment]
I am not sure I understand. The scroll bar is not working for you? Depending on the user monitor resolution it may not be possible to show all plugins entries without scroll.

**Comment by Canule** [comment]
*The up/**down** buttons wont fit completely in the sfx list box it's width\

**Comment by wwmm** [comment]
Now I understand. Although I don't see a problem in adding more space this may be a problem with the theme. Here a few screenshots with the Adwaita theme:
![screenshot from 2018-09-15 13-31-47](https://user-images.githubusercontent.com/16225172/45588499-28bbf780-b8ec-11e8-95fe-27af1495d3be.png)
![screenshot from 2018-09-15 13-36-01](https://user-images.githubusercontent.com/16225172/45588515-5143f180-b8ec-11e8-8239-36c053bb8fc6.png)
Only when I put the mouse over the scrollbar the up/down button are partially hidden. But this is normal. GTK scrollbars change its size when the mouse is over it

**Comment by Canule** [comment]
The scrollbar is always viable over here(no hover required).

**Comment by wwmm** [comment]
Your theme or maybe cinnamon is forcing it to be visible. As far as I remember this can be done.

I will increase the space. I just hope that there are no themes out there increasing the scrollbar width. I have no idea if there is a way to measure its width and adjusting accordingly

**Comment by Canule** [comment]
I was searching through the files hoping to find the file to hackish adjust the width to report back to you.
If un-compiled do you have a dir/file pointer for me?

**Comment by wwmm** [comment]
It is not necessary. I have just made a few changes to the master branch. At least here the buttons are visible even when the scrollbar is shown. As long as there is no big differences in the scrollbar width across themes it should work for everybody
