### ISSUE TITLE
5.1 surround - center and subwoofer disabled?

### ISSUE THREAD

**Issue by 5ulo** [wwmm/pulseeffects#34]
I tried Kodi with 5.1 audio - FL, FR, RL, RR are playing perfectly. Center and Subwoofer aren't - they are muted. Haven't found yet how to enable them. If I turn PulseEffects for Kodi off it will play as it should be.

**Comment by wwmm** [comment]
Hi, a few plugins like the input limiter and the compressor only work with stereo streams. So I am asking gstreamer to negotiate a 2 channel stream with pulseaudio.

**Comment by 5ulo** [comment]
Better than nothing :) Thanks for the info.
