### ISSUE TITLE
New Update keeps displaying notification

### ISSUE THREAD

**Issue by flatusv** [wwmm/pulseeffects#340]
I encountered a similar behavior like https://github.com/wwmm/pulseeffects/issues/338. dconf reset -f /com/github/wwmm/pulseeffects/ let me access the gui again, but since i start pulseeffects with pulseeffects --gapplication-service i always get to see the notification "It is recommended to reset its configuration...".
How can i get rid of this?

**Comment by wwmm** [comment]
which desktop are you using? this notification should come with a `yes/no` button. ONce you click in one of them the message is not displayed anymore

**Comment by flatusv** [comment]
I'm using i3wm with dunst as the notification daemon.

**Comment by wwmm** [comment]
In case you are using PulseEffects `4.3.5` a reset from command line `pulseeffects -r` should make the message go away. Another option is to edit the version string in dconf-editor to the PulseEffects verion you installed
![screenshot from 2018-09-19 12-37-00](https://user-images.githubusercontent.com/16225172/45764283-c2471a00-bc08-11e8-95f0-da2f3389da50.png)

I thought that gnotification buttons where shown in any desktop. When I have time I will try to think about how this can be improved

**Comment by VladimirDev93** [comment]
![peek 2018-09-22 12-49](https://user-images.githubusercontent.com/12301022/45916414-1dc21380-be66-11e8-9163-8c75d8deb926.gif)

It never goes away, and I can't even start the application anymore (+ no sound), even though everything was working normal yesterday on a freshly installed Ubuntu 18.04.

**Comment by etsnyman** [comment]
Same here! See attachment. PulseEffects is definitely broken.
![screenshot from 2018-09-22 15-43-16](https://user-images.githubusercontent.com/7977598/45917869-6259a900-be7e-11e8-8494-7f017fde65fe.png)

**Comment by wwmm** [comment]
@VladimirDev93 and @etsnyman your problem seems a little different. For reasons that are not clear yet a few users are having problems after upgrading PulseEffects. Usually executing `pulseeffects -r` or `dconf reset -f /com/github/wwmm/pulseeffects/` fixes this. But before you run any of these commands run `dconf dump /com/github/wwmm/pulseeffects/ > pesettings.txt` and attach the file here so I can take a look at your settings before the reset.

**Comment by flatusv** [comment]
[pesettings.txt](https://github.com/wwmm/pulseeffects/files/2407921/pesettings.txt)
Here is mine

**Comment by wwmm** [comment]
There is a lot of things missing in your dump. This is odd. Specially the absence of the `plugins=` entries. Here is my file
[pesettings.txt](https://github.com/wwmm/pulseeffects/files/2407942/pesettings.txt)

**Comment by wwmm** [comment]
I wonder if `dconf dump` is printing only the keys that were changed at some point.

**Comment by flatusv** [comment]
I'm note sure but i guess that's because i don't have many of those installed. Here is a list of my ladspa plugins
[ladspaPlugins.txt](https://github.com/wwmm/pulseeffects/files/2407953/ladspaPlugins.txt)

**Comment by wwmm** [comment]
I would expect the keys to be there even if the plugins are not installed. dconf is probably showing only the keys that were changed. If you did not have the `plugins` key PE would be totally broken. Can you see this key in dconf-editor?
![screenshot from 2018-09-22 12-59-44](https://user-images.githubusercontent.com/16225172/45919128-6d550f00-be67-11e8-922b-bfd473a5db3e.png)

**Comment by flatusv** [comment]
This is how it looks on my machine
![image](https://user-images.githubusercontent.com/16192241/45919167-c89bf700-be91-11e8-8b26-f9a4bc46c9d7.png)

**Comment by wwmm** [comment]
It is ok. The sad thing is that `dconf dump` is not going to be of much help to find bugs if it only prints the keys that changed =/

As I am still unable to reproduce this "after upgrade crash" in any of my machines we will still have people coming here with the same problem. At least until everybody is on PE > 4.3.4 =/

**Comment by VladimirDev93** [comment]
Sorry for being late.
[pesettings.txt](https://github.com/wwmm/pulseeffects/files/2411556/pesettings.txt)
