### ISSUE TITLE
AUR package is gone?

### ISSUE THREAD

**Issue by flipwise** [wwmm/pulseeffects#341]
Hi,

I haven't been able to find the pulseeffects package these past days in the AUR.

Basically the AUR helper says the package is missing and the package's web link is 404.

**Comment by wwmm** [comment]
Yes. The package is now in Arch community repository. When an Arch maintainer takes the package he removes it from aur.

**Comment by flipwise** [comment]
That's good news. I guess Manjaro still hasn't synced with the latest Arch so that's why PE is missing all together.

**Comment by wwmm** [comment]
In case you need there is a pkgbuild in PulseEffects source that builds directly from git

**Comment by wwmm** [comment]
I could. I just don't know if I want more work :-)

**Comment by flipwise** [comment]
Well I'm sure Manjaro, Antergos and Netrunner will catch up soon, and if the Arch maintainer packages PE well and in a timely manner, there won't be much need for an AUR package.

**Comment by wwmm** [comment]
Antergos already has it because it uses the Arch Linux repositories. In any case that is what I was thinking. It doesn't seem to be necessary to maintain this aur package.
