### ISSUE TITLE
PulseEffects crackling when using programs

### ISSUE THREAD

**Issue by GottaSlay** [wwmm/pulseeffects#344]
After a while of using my pc (mostly when i've done something cpu-heavy) my audio starts crackling. I tried to troubleshoot this and the only thing i found that helped a wee tiny bit was this: sudo renice -10 -p $(pidof pulseeffects)

**Comment by wwmm** [comment]
At least on my ryzen 2700 I never had that. Which was the heavy cpu activity that triggered the crackling?

**Comment by GottaSlay** [comment]
Starting any other program on the side whilst watching twitch/youtube. Now after i lowered priority of pulseeffects the crackling is 80% gone and only appears upon opening tabs and changing volume of whatever is playing.

**Comment by wwmm** [comment]
This reminds me of #222. We never found exactly why that user was having this issue. Teamviewer seemed to contribute but it did not seem the only source of the problem. Try to put here the info listed in the `Basic Logs` section of [Reporting-bugs](https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs)

**Comment by mikhailnov** [comment]
You gave pulseeffects more priority, not less.
Crackling sound is a standart issue when Load Average is high.
Users report that using Zen/Liquorix/Xanmod kernel helps to avoid this.

**Comment by PilotBob42** [comment]
I'm experiencing light/occasional crackling as well. Most of the time everything is fine, but sometimes when I do something fairly routine (like open a new browser tab) I will get some crackle on my media playing in the background. I can recreate this on demand in certain places like using the volume slider in VLC always produces some crackle or navigating to the end of just about any text box such that the system sound plays over and over quickly (lots of crackling there). This happens even with a nice value of -20 for pulse effects and pulse audio. System specs are a quad core Intel Celeron J1900 @2.4Ghz w/ 8Gb of RAM running 18.04.1 LTS

Still, this is a great app and the improved sound quality 99% of the time more than makes up for the occasional crackle.

**Comment by wwmm** [comment]
I also have the problem with the applications volume slider. This one is still a mystery to me. I just don't see a reason for it to happen.

**Comment by wwmm** [comment]
I decided to take a look at Pulseaudio's logs and I see that whenever we change the application volume or the null sink volume a lot of messages about [rewinding](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Rewinding/) are produced. I think that this buffer rewrite while we are recording from the null sink monitor is the one causing the noise.

I will ask Pulseaudio's developers about this. If this is the source of the problem the fix would probably have to be done in Pulseaudio.

**Comment by wwmm** [comment]
Question sent to the Pulseaudio mailing list [https://lists.freedesktop.org/archives/pulseaudio-discuss/2018-October/030548.html](https://lists.freedesktop.org/archives/pulseaudio-discuss/2018-October/030548.html). Now we wait

**Comment by wwmm** [comment]
They answered. The audio crackling when changing volume is being caused by a bug in Pulseaudio. I don't know if this could be also causing the original problem reported in this issue

**Comment by PilotBob42** [comment]
So where does that leave us? The issues they cited were first reported 4 or 5 years ago. Doesn't seem like they are in a hurry to address it.

**Comment by wwmm** [comment]
I think we will have to live with this for a while. This problem is so deep in Pulseaudio that I don't see a way to workaround this in PulseEffects. I can't stop Pulseaudio from doing its rewinds.

That being said there is something that the user could do to minimize this annoyance. But it is not going to please everybody. Enable the `auto gain` and the `limiter` plugins and do not touch the application volume control. Use only the your system master volume. Not everybody will like this because it will change your audio dynamic range. But I do not see any other thing that we could do right now other than not touch the application volume.

**Comment by wwmm** [comment]
Fixed as explained at #350
