### ISSUE TITLE
Do not move output stream when new default sink is chosen

### ISSUE THREAD

**Issue by squigglezworth** [wwmm/pulseeffects#347]
Can we change this behavior or allow a setting?

It would be great to be able to change the default sink after launching PulseEffects without having to manually move the stream back to the sink it was on

**Comment by wwmm** [comment]
If I understood what you want I think it is already possible
![screenshot from 2018-09-29 18-51-03](https://user-images.githubusercontent.com/16225172/46250784-ac133800-c418-11e8-82ac-1e7196b49eb1.png)
Disable the  `Use Default` settings and choose a device. Altough we try to remember the custom device have always in mind that if this device does not exists when PE is starting we will use the default

**Comment by wwmm** [comment]
This is a feature I do not use. So if you find any issue please report :-)

**Comment by squigglezworth** [comment]
Oh, awesome! Thank you :)
