### ISSUE TITLE
How can i set up Virtual Surround Sound?

### ISSUE THREAD

**Issue by GottaSlay** [wwmm/pulseeffects#348]
I've been trying for the whole day and i'm only getting music and no voice when testing by watching a trailer in SMplayer. Are there any plugins for PulseEffects that would allow me to easily set it up or any alternatives?

**Comment by wwmm** [comment]
You will have to tell smplayer to downmix sorround media to stereo. At this moment PulseEffects works only with 2 channels.

Some time ago I thought a little about this but it is not a simple task to give proper support for surround media. Of all the plugins available in PulseEffects I think that only the equalizer accepts more than 2 channels. All the others are only stereo. 

There are other difficulties too. The null sink used by PE (`PulseEffects(apps)`) would have to be reconfigured to multiple channels on the fly and at this moment Pulseaudio does not support that.

**Comment by GottaSlay** [comment]
Lets say if i were to temporarily disable PulseEffects, would i have any alternative ways of enabling Virtual Surround?

**Comment by wwmm** [comment]
If by virtual you mean something like listen to surround sound in a headphone or creating a virtual room speaker I am not aware of any means. If you do not want do downmix the surround source to stereo your only option is to disable PulseEffects, configure Pulseaudio for a multichannel setup and play directly to a surround sound device that has the right number of speakers.

**Comment by Wello6143** [comment]
I'm also interest about this, hopefully it will be a feature on PE soon.

**Comment by richardpl** [comment]
It is already possible with mpv and sofalizer filter.

**Comment by wwmm** [comment]
Exactly what this sofalizer plugin does? It takes a stereo stream and creates virtual surround? If yes I could try to add it to PulseEffects. Like I answered to the issue opener we can only deal with 2 channels for now.

**Comment by richardpl** [comment]
It takes any number of input channels convolves each channel with picked BRIRs/HRIRs from SOFA files and mixes them into stereo to produce spatialization. It can deal with 2 input channels but it is more useful in 7.1 -> stereo scenario.
