### ISSUE TITLE
depends on gnome-builder.css without including it

### ISSUE THREAD

**Issue by jwatte** [wwmm/pulseeffects#352]
Installing the .deb on ubuntu 18.04, and then starting pulseeffects, results in this error:

(pulseeffects:43009): Gtk-WARNING **: 19:19:12.173: Theme parsing error: gtk-main.css:73:38: Failed to import: Error opening file /usr/share/themes/Radiance/gtk-3.20/apps/gnome-builder.css: No such file or directory
Segmentation fault (core dumped)

I'm not sure the Radiance file missing is causing the segv -- creating an empty file of that name does not make the segv go away.

Note that I have Radiance and gnome-builder packages installed.

    [19:21] jwatte@ripper:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 18.04.1 LTS
    Release:	18.04
    Codename:	bionic

    pulseaudio/bionic,now 1:12.2-5~bionic1 amd64 [installed]
      PulseAudio sound server

**Comment by wwmm** [comment]
Strange. We do not force any theme on PulseEffects. I do not have any `Gtk-WARNING` warning in my PC.

Try to reset PE `dconf reset -f /com/github/wwmm/pulseeffects/`. If this does not make the segmentation fault go away you may have a missing dependency. Any ideas about how to check this @mikhailnov ?

**Comment by wwmm** [comment]
inactive
