### ISSUE TITLE
laggy spectrum visualizer

### ISSUE THREAD

**Issue by conceptualspace** [wwmm/pulseeffects#355]
is that normal? is there a way to get the spectrum to display smoothly? setting the buffer and latency to their lowest possible values in settings (1000/100 respectively) makes no difference.

thanks :)

**Comment by wwmm** [comment]
I would not expect these parameters to have visible influence over the spectrum. At least in my computers I only see lag in the spectrum if I choose a blocksize of 4096 or 2048. With other values the spectrum is fine
