### ISSUE TITLE
Elements of GUI are tiny with HiDPI display

### ISSUE THREAD

**Issue by Zackptg5** [wwmm/pulseeffects#356]
Everything is fully functional, but certain parts of the GUI are tiny on my 4k display (despite having it scaled 2x).
Distro: Manjaro Linux KDE 17.1.12 (latest stable release).

Attached are the psettings and a screenshot. Let me know if you need anything else. Thanks!

[pesettings.txt](https://github.com/wwmm/pulseeffects/files/2503295/pesettings.txt)
![screenshot_20181022_162458](https://user-images.githubusercontent.com/5107713/47317603-036f8700-d618-11e8-84ed-f66965f5c631.png)

**Comment by wwmm** [comment]
I don't think there is anything I can do about this. Everything in the interface is standard GTK. No customization. In my opinion this is either are GTK problem or GTK problem when used in KDE. But as I do not have a 4k monitor I don't know if in GNOME the situation is better

**Comment by flipwise** [comment]
I see three potential issues:
- KWin doesn't handle HiDPI CSD windows very well
- The Breeze (Dark) GTK theme has not been optimized for HiDPI yet
- Plasma as a whoel just doesn't handle GTK scaling quite well yet (before you had to scale fonts, icons, the cursor manually - and still do for fractional scaling if you want best results)

For starters I think you can try testing other GTK themes to see if it makes any difference. 

Perhaps you can also try this: https://www.reddit.com/r/kde/comments/7tvp9g/scaling_gtk_application/dtfxmpu/

**Comment by Zackptg5** [comment]
> I see three potential issues:
> 
>     * KWin doesn't handle HiDPI CSD windows very well
> 
>     * The Breeze (Dark) GTK theme has not been optimized for HiDPI yet
> 
>     * Plasma as a whole just doesn't handle GTK scaling quite well yet (before you had to scale fonts, icons, the cursor manually - and still do for fractional scaling if you want best results)
> 
> 
> For starters I think you can try testing other GTK themes to see if it makes any difference.
> 
> Perhaps you can also try this: https://www.reddit.com/r/kde/comments/7tvp9g/scaling_gtk_application/dtfxmpu/

That worked! Thanks man!

@wwmm 
In case you want to add this to the FAQ, here's my steps for HiDPI in KDE:
1: If monitor isn't already scaled, go to system settings -> Display and Monitor -> Displays -> Scale Display and move scale bar to 2. Otherwise, skip to step 2.
2: Run this in terminal so the panel will scale properly: sudo sed -i 's/plasmashell/PLASMA_USE_QT_SCALING=1 plasmashell/g' /etc/xdg/autostart/org.kde.plasmashell.desktop
3: Run this in terminal so GTK apps scale properly: echo -e "GDK_SCALE=2\nGDK_DPI_SCALE=-1" >> ~/.pam_environment

Everything will take effect on next login

**Comment by wwmm** [comment]
I think this would be more visible as a section in the wiki. Could you do it? It could be called `HiDPI Display`

**Comment by Zackptg5** [comment]
Sure thing, I'll add it right now :)

**Comment by Zackptg5** [comment]
Created it: https://github.com/wwmm/pulseeffects/wiki/HiDPI-Display
Only have KDE listed since it's the only thing I've tested on hidpi at this point. My guess is that gnome should work out of the box if wayland is in use but I don't want to list something that's incorrect

**Comment by ncfavier** [comment]
Easyeffects does not seem to respect `GDK_SCALE`, please reopen.

**Comment by wwmm** [comment]
> Easyeffects does not seem to respect `GDK_SCALE`, please reopen.

We do not use gtk anymore. And even if we did these operations are not handled in the application level. It is between the graphical toolkit and the desktop environment that this configuration  happens.

**Comment by ncfavier** [comment]
Thanks, following the instructions in https://doc.qt.io/qt-6/highdpi.html worked.
