### ISSUE TITLE
No "About" window

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#357]

**Comment by mikhailnov** [comment]
In newest versions it's impossible to find out the version of PulseEffects either from GUI the CLI

**Comment by wwmm** [comment]
It is in a different place
![screenshot from 2018-10-24 11-21-56](https://user-images.githubusercontent.com/16225172/47437539-29fc0200-d77f-11e8-9ec3-2ee7f2ee6bbb.png)
GTK developers deprecated the global menu. That is why I moved the about entry.
