### ISSUE TITLE
Assertion 'o' failed at pulse/operation.c:133, function pa_operation_get_state()

### ISSUE THREAD

**Issue by Alexey-Akishin** [wwmm/pulseeffects#359]
PulseEffects used to work for me. However, some time ago after software upgrade it fails to start with the following error:

`Assertion 'o' failed at pulse/operation.c:133, function pa_operation_get_state(). Aborting.`

I'm not the only one affected by this issue, when googling I found [others mentioning having the same problem](https://askubuntu.com/questions/1079086/pulseeffects-doesnt-run).

**Comment by Alexey-Akishin** [comment]
Question linked above does not have an answer (at least for now), but in comments there was a suggestion I did not notice right away, to use dconf. I had to install it first, and after running PulseEffects works again.
```
sudo apt install dconf-cli
dconf reset -f /com/github/wwmm/pulseeffects/
```
I also found similar suggestion here in issue #345, and since my issue is the same, I'm closing it.

**Comment by wwmm** [comment]
This is an issue I was never able to reproduce in any of my machines. As far as I know the reset fixes it but I do not see a reason for it to happen in the first place.
