### ISSUE TITLE
Pulseeffects conflicting with OBS Studio

### ISSUE THREAD

**Issue by OmegaDarkMage** [wwmm/pulseeffects#360]
Wondering if there is a way to make it so the modified (improved audio) comes out only through my speakers but not in the actual recordings in OBS Studio.

**Comment by OmegaDarkMage** [comment]
I tried doing that but didn't seem to stop the recorded files from having the audio effects applied to them. My guess is since Pulse modifies the audio coming from applications, it also makes the audio recorded the same.

**Comment by wwmm** [comment]
hummm... I still think this should not happen when you disable it.  Can you put here an image of pavucontrol recording tab when OBS and PulseEffects are running? Is there any change in this tab when you turn on/off OBS in PE window?

**Comment by OmegaDarkMage** [comment]
Good news I got it to work the way I wanted, when you mentioned pavucontrol and the recording tab it gave me the idea to check it and sure enough that was the culprit, it was recording the same audio from my speakers. I just changed it to monitor of pulseeffects (apps) and now the recordings have the normal non modified audio while my speakers (cheap $20 dollar ones lol) still have the improved audio.

**Comment by ShayBox** [comment]
Why did you close the issue, the problem wasn't fixed, you just found a workaround.

I've had this issue since I started using pulseeffects, every system I use it on, any time obs opens or changes an audio setting it resets.
