### ISSUE TITLE
Community Presets - Perfect EQ

### ISSUE THREAD

**Issue by andrefcorreia** [wwmm/pulseeffects#361]
When I choose perfect eq in the preset the pulseeffect closes and the sound stop.
i am not really hearing diferrence with perfect eq.
any clue?

**Comment by wwmm** [comment]
It seems something is broken with these presets indeed. As I never use them I did not notice. I will take a look

**Comment by wwmm** [comment]
Initially I was abçe to reproduce the lack of sound. But after restarting PE  it is working. Strange =/

**Comment by wwmm** [comment]
I will keep looking. In the meantime try to see if a reset helps `dconf reset -f /com/github/wwmm/pulseeffects/`

**Comment by wwmm** [comment]
The problem is not in the presets. It happens at random when the number of bands is changed.

**Comment by andrefcorreia** [comment]
hum....ok. Thank you. Is there something that i can do to change this?

**Comment by andrefcorreia** [comment]
This is what i am getting when select perfec eq on rpeset

eeffects:24344): glibmm-ERROR **: 10:52:46.990: 
unhandled exception (type std::exception) in signal handler:
what: /home/andre/.config/PulseEffects/Perfect EQ.json(7): expected value

Trace/breakpoint trap

**Comment by wwmm** [comment]
I thought you were using the builtin 10 bands preset in the equalizer menu. There is one there also called "perfect eq". In this case it seems to me that the preset file you downloaded is corrupted or has a bad value in one of the fields.

In any case this made me realize that there are problems somewhere else :-)

**Comment by andrefcorreia** [comment]
I'm sorry if I did you got it wrong.
But in the title I said "Community Presets - Perfect EQ"
:)
