### ISSUE TITLE
CPU Usage is far too high.

### ISSUE THREAD

**Issue by Jake1702** [wwmm/pulseeffects#364]
When enabled it's using 20%+. Checking in top shows python to be the intensive process. The only other alternative (pulseaudio-equalizer) does not have this issue, it barely uses 1%, but then that has a huge issue with distortion. I'm really out of options at this point.

Is there a log you'd like me to provide?

**Comment by wwmm** [comment]
Python?? Which PulseEffects version are you using? I ported it to C++ a long time ago. As I do not have time to fix bugs in the `3.x` series my suggestion is that you upgrade PulseEffects.

If the cpu usage is still high after upgrading to the latest version `4.4.0` something you may try is using less equalizer bands. 10 bands will use less cpu than 30 bands. But as the GStreamer equalizer uses a different algorithm than the one in the Pulseaudio equalizer you may still see a higher cpu usage.

**Comment by Jake1702** [comment]
I'm using the one that shipped with 16.04. There isn't any newer package directly available, how could I upgrade it to the latest version without compiling it from source?

**Comment by sandikata** [comment]
No updates yet?!?! High cpu usage at all, no matter what plugins enabled, even if disabled, -> high cpu usage.
