### ISSUE TITLE
Volume level mismatch Pulseeffects/Standard Output (#235 is back) [SOLVED]

### ISSUE THREAD

**Issue by Dodjob** [wwmm/pulseeffects#366]
So I'm on Ubuntu 18.10 / Pulseaudio 12.2 / last PE from ppa
I noticed that somehow the sound output was everyday a bit lower. At the end, I reached the max volume of my Harman kardon.. and well I had to take action ^^
It seems that the standard output ( Digital Output/SPDIF) AND the Pulseeffects (apps) are both controling the volume output and are totally independant. I don't know if this is normal.
Anyway, somehow, If the Pulseaudio output uses sound maximiser (maybe limiter) it will reduce the output of the Digital Output/SPDIF... and not bringing it back -.-'
Easy workaround is to bring it back manually with PaVu control. but somehow.. I would love to see them linked ^^
One final thing. I don't know if this is related. Some tracks on Mellowplayer + Soundcloud won't play. I mean, it seems that the Pulseeffects doesn't get the audio stream "start" somehow. Clicking on Play/stop a few times solves the problem, this disappear as soon as the normal output is selected. 
Hope this helps somehow. I love my Pulseeffects :) 
Have a nice day!
H.

**Comment by wwmm** [comment]
I am not sure I understand... Did you set `PulseEffects(apps)` as default output device? If yes do not do that. Use your sound card as default device. This way `PulseEffects(apps)` volume level will always be at 100%

**Comment by Dodjob** [comment]
If I select the normal spdif output.. I don't have any post-processing mate -.-' 
Did I make something wrong? 
Actually, I didn't change anything and let the app makes all settings ^^
Regards;
H.

**Comment by Dodjob** [comment]
Thanks!
Sorry for the late reply -.-'
That's excatly how my system is set. I still have independant volume (spdif and pulseeffects) and if I select spdif in the Pavu control menu, I get no pulseeffects processing. 
Regards,
Hadrien

**Comment by Dodjob** [comment]
OK. I have it ^^
You have to first select standard output and THEN start pulseffect and enable it. 
NICE. Thanks a lot! :)

**Comment by wwmm** [comment]
I am glad it is working now! I wish I could make this more automated. But right now Pulseaudio does not offer any way to make the `PulseEffects(apps)` invisible to the user or to make it impossible to set it as default device
