### ISSUE TITLE
Remember values after switching between different sound outputs

### ISSUE THREAD

**Issue by GoodGuyNick** [wwmm/pulseeffects#371]
When someone has two or more sound outputs(headphones, speakers, ...) pulseeffects doesn't remember to use itself instead of Built-in Audio Analog Stereo and doesn't remember volume values. 
When switching, the use of itself sometimes applies for one program but not for another and sometimes it doesn't apply itself at all for any program.
![screenshot_2018-11-13_09-59-23](https://user-images.githubusercontent.com/10221153/48399300-eec07380-e72b-11e8-834f-6a82ce82caa1.png)

**Comment by wwmm** [comment]
I am not sure I understand what you mean by `use itself`. PulseEffects has to use one of your output devices as audio output. Usually it will switch automatically to the current output device unless you have disabled this in its settings.

Looking at the figure above it seems you are thinking about remembering to set your audio application to `PulseEffects(apps)`. Try to switch on `Enable All Applications` in PulseEffects menu. This should force all audio applications to be processed. If you do not switch this on it will be up to Pulseaudio to remember or not this association. In the same way the one who remember volumes is Pulseaudio. We do not do that

**Comment by wwmm** [comment]
If by `use itself` you mean set `PulseEffects(apps)` as default output device do not do that. PulseEffects is not meant to work with `PulseEffects(apps)` set as default output device. This may break its audio routing in a few situations. Use your soundcard or headphone as default device and use `Enable All Applications`

**Comment by GoodGuyNick** [comment]
> Looking at the figure above it seems you are thinking about remembering to set your audio application to PulseEffects(apps).

Yes

> Try to switch on Enable All Applications in PulseEffects menu

Okay, I did this and it's working if I switch in PulseAudio Volume Control. Thank you. I've did some testing and the culprit is https://github.com/yktoo/indicator-sound-switcher. If I switch to Headphones from Speakers in PulseAudio Volume Control then I see `PulseEffects(apps)` being applied but if I switch using `indicator-sound-switcher` I see `Built-in Audio Analog Stereo` and if I am using Speakers, pressing switch for Speakers again will result in `Built-in Audio Analog Stereo`.

**Comment by wwmm** [comment]
It seems to me that this indicator you are using moves all audio applications to the device you selected. More or less the same that `Enable All Applications` does. There will be definitely a conflict. I don't think there is anything I can do about this.

**Comment by GoodGuyNick** [comment]
Thank you
