### ISSUE TITLE
"Presets" button localization

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#373]
this problems is very old, but it's probably the first time I've come across to writing about it.

When PE is launched, the "Presets" button is in English:
![deepinscreenshot_pulseeffects_20181117051500](https://user-images.githubusercontent.com/15802528/48655460-ed42c400-ea27-11e8-8247-f483217f2221.png)

Right after I click on it, it becomes in Russian:
![deepinscreenshot_pulseeffects_20181117051506](https://user-images.githubusercontent.com/15802528/48655465-f92e8600-ea27-11e8-81ed-781e6e6f20af.png)

**Comment by mikhailnov** [comment]
This happens not always.

**Comment by mikhailnov** [comment]
If I click 'Reset settings', the button is in English again
![deepinscreenshot_pulseeffects_20181117051944](https://user-images.githubusercontent.com/15802528/48655493-71954700-ea28-11e8-8a83-e2398fde53b4.png)

**Comment by wwmm** [comment]
Strange. The line that updates this label is here [application_ui.cpp#L1034](https://github.com/wwmm/pulseeffects/blob/0f0ffc078be696df75bf2fc86c8c8f64e16d03b7/src/application_ui.cpp#L1034). It should be being translated unless there is somewhere else in the code also updating this variable without using the translation keyword. I do not remember. As soon as I have time for this I will take a look

**Comment by ardumpl** [comment]
Hi dude, i want to submit my translate file, where can i submit it?

**Comment by wwmm** [comment]
@ardumpl the usual way would be to create a pull request as explained in [Translating-PulseEffects](https://github.com/wwmm/pulseeffects/wiki/Translating-PulseEffects). If for some reason you think the process is too complicated just create a new issue and upload the files

**Comment by ardumpl** [comment]
@wwmm I have been read about the procedure and... yup its too complicated to me. Thank you, i will create new issue for it. Thanks you, wwmm

**Comment by wwmm** [comment]
I think I found the source of the problem @mikhailnov. We are not handling translations for strings in the gsettings schemas. The last used preset name is hardcoded as `Presets` in the schema [com.github.wwmm.pulseeffects.gschema.xml#L187](https://github.com/wwmm/pulseeffects/blob/fc1329fbc59222555fc186406b37a234e9e5fa3a/data/schemas/com.github.wwmm.pulseeffects.gschema.xml#L187).

Honestly I have no idea yet about how to handle translations for strings in these files.

**Comment by wwmm** [comment]
Do you have any idea @AsavarTzeth ?

**Comment by wwmm** [comment]
Based on what is in the description section of this site https://developer.gnome.org/gio/stable/GSettings.html#GSettings.description it is possible to translate default values. But I did not understand exactly how yet

**Comment by wwmm** [comment]
epiphany's schema has a default value translated [org.gnome.epiphany.gschema.xml](https://github.com/GNOME/epiphany/blob/909810b52e4b4a303e3de4500e8668fd1f2a6409/data/org.gnome.epiphany.gschema.xml). Now I have to find how to make this visible to meson

**Comment by wwmm** [comment]
I found out how to do it. At least here everything is now fine after a reset @mikhailnov
