### ISSUE TITLE
PulseEffects - Indonesia localization update

### ISSUE THREAD

**Issue by ardumpl** [wwmm/pulseeffects#377]
I have been created Indonesia translate files. This is not final translate. For next time, i will translate the help file and re edit this main .po. Here is for translated file
[PulseEffects_id.tar.gz](https://github.com/wwmm/pulseeffects/files/2594175/PulseEffects_id.tar.gz)

**Comment by wwmm** [comment]
Ok. I added it to the repository

**Comment by ardumpl** [comment]
Thank you dude, i will check it
