### ISSUE TITLE
Convolver not loading irs file

### ISSUE THREAD

**Issue by zurbran** [wwmm/pulseeffects#378]
Hello everyone, I'm trying to use pulseeffects in Linux Mint 18.03 Sylvia, i installed pulseeffects via flatpak, then when i want to add an irs file for the convolver that shows in the windows: 

![pulseeffects](https://user-images.githubusercontent.com/20207538/48776481-bcc08b80-ecae-11e8-84b2-1463c2f12ea8.png)

A friend of mine has pulseeffects running on Ubuntu 18 and the same irs works fine, so it's not a problem related to the irs file.
Thanks in advance.

**Comment by wwmm** [comment]
Kill the PulseEffects process `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Show here what is printed in the terminal from the moment you execute it till you try to load the file

**Comment by wwmm** [comment]
When you use the `Import Impulse` function in the convolver menu the file should be copied to the impulse folder where PulseEffects searchs for impulse files. What is the output of `ls /home/brussell/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/irs`?

**Comment by zurbran** [comment]
It was empty, i solved by directly copying the impulse response file to that folder.
Thanks for the help!

**Comment by wwmm** [comment]
Maybe the security policies of flatpak are somehow forbiding the import code to work. But if that is the case there isn't much I can do about it.
