### ISSUE TITLE
[Request] Run PulseEffects at same priority level as PulseAudio

### ISSUE THREAD

**Issue by Eonfge** [wwmm/pulseeffects#385]
I found that I occasionally have some stuttering if my PC has to do some IO or something network related. I'm not sure if this is related to #362, #222 or #344, but it has certainly some resemblance. What I also discovered, is that when I put Pulse Effects on the same priority level of Pulse Audio (Very High, -20, drop everything) that I have no such stuttering. 

Audio is always very latency and disturbance dependant, which also explains why Pulse Audio has a max priority. With Pulse Effects' mixers in the middle, it would be really beneficial for older machines to have it at least match the Pulse Audio priority. A user can always deviate from it, but if Pulse Audio runs at -20, it's save to presume that Pulse Effects should have equal priority.

Thus, would this be hard to implement or is it beyond your control? I can of cause change the nice-value myself, or add the right params to the startup script, but I think it would be better if it were intergrated for everybody.

In the interest of fairness, I'm using an older computer I built about 6 years ago:
- Intel i7 3770
- 16 GB DDR3 
- MSI GD-65 Motherboard

**Comment by wwmm** [comment]
Good question. I have no idea about how to set this in the application code. But I think that the kind of priority Pulseaudio uses needs root permissions to be done. This works for Pulseaudio because its instance is not created by the normal user.

**Comment by jrudess** [comment]
At least in arch/kde, pulseaudio is run under the user account rather than root, and is launched with nice=-11 by default:

```
> cat /etc/pulse/daemon.conf | grep nice
; nice-level = -11
```

**Comment by wwmm** [comment]
You are right. I don't know why I though Pulseaudio was executed by a more privileged user. But I still do not understand how they are able to set a `-11` nice level. Doesn't this need root permission?

**Comment by jrudess** [comment]
I have a vague recollection of researching nice levels a few years ago when setting up my system, and the [archwiki](https://wiki.archlinux.org/index.php/realtime_process_management) seems to confirm that only root should be able to go below 0.

This lwn article looks like it outlines the process that pulseaudio goes through to get the higher priority: https://lwn.net/Articles/339316/

Looks like pulse sends a dbus request to RealtimeKit and RealtimeKit in turn is able to elevate the priority of the process.

**Comment by jrudess** [comment]
For reference, the set_scheduler routine in pulseaudio looks to contain the code:
https://github.com/pulseaudio/pulseaudio/blob/4e3a080d7699732be9c522be9a96d851f97fbf11/src/pulse/util.c

**Comment by wwmm** [comment]
I did some work on this that is already in the master branch. At least here on my PC the nice value and real-time priority match the ones used by Pulseaudio. See the threads with `-11` nice level in this image:
![screenshot from 2018-12-22 17-30-42](https://user-images.githubusercontent.com/16225172/50378010-6af18500-060f-11e9-98de-e229ed3be832.png)
I intend to expose the configuration for these values in the interface. But I have to improve this code a little before that. If possible try it and tell me if there is any side effect. People on Arch Linux can use a PKGBUILD available in PulseEffects source that builds directly from the git repository.

**Comment by wwmm** [comment]
You will notice that not all threads have the priority changed. This is because I am following this https://gstreamer.freedesktop.org/documentation/application-development/advanced/threads.html Only the threads that are doing audio processing in the GStreamer pipeline have their priority changed.

**Comment by wwmm** [comment]
Fully implemented in the latest master. By default we do not touch the priorities. It is up to the user to choose if he wants real-time mode or just a change to the niceness value. As real time threads do not use the niceness value this control is disabled when the user chooses real-time mode.

Let me know in case there are problems
