### ISSUE TITLE
Pulseeffects crashing in ubuntu 18 since the update made today (4 december 2018)

### ISSUE THREAD

**Issue by dariofilipe95** [wwmm/pulseeffects#386]

**Comment by dariofilipe95** [comment]
![image](https://user-images.githubusercontent.com/29407123/49436316-bf43da80-f7b0-11e8-9936-3fd82c95f652.png)

**Comment by dariofilipe95** [comment]
Another note: It crashes like from 10 in 10min(maximum) or less.

**Comment by wwmm** [comment]
I need more information. Which ubuntu? How did you install? What is printed by the command `G_MESSAGES_DEBUG=pulseeffects pulseeffects` in the terminal?

Here on Arch Linux I have no problems.

**Comment by dariofilipe95** [comment]
Ubuntu version: Ubuntu 18.04.1 LTS
Installed it with apt-get install pulseeffects (i upgraded too today, just in case there was missing anything, which ain't).

Behaviour: I open pulseeffects, everything ok while doing it. I start listen to music and after 1 song, maximum 2, the program crashes with that message error (in the printscreen above). Not always that message appears on crash.

output of G_MESSAGES_DEBUG=pulseeffects pulseeffects:
![image](https://user-images.githubusercontent.com/29407123/49448677-4ef98100-f7d1-11e8-81f7-c1306318da64.png)
![image](https://user-images.githubusercontent.com/29407123/49448722-620c5100-f7d1-11e8-9c52-119d24823d43.png)

**Comment by wwmm** [comment]
The only error in this log is about the impulse response file. What happens if you disable the convolver?

**Comment by dariofilipe95** [comment]
lol, nice catch... didn't notice that at all. Seems to have fixed the crashes! Thanks! My ears were bleeding already because of lack of EQ/Bass. Cheers

**Comment by wwmm** [comment]
kkk No problems :)
