### ISSUE TITLE
Enableable for all applications

### ISSUE THREAD

**Issue by es20490446e** [wwmm/pulseeffects#388]
https://youtu.be/EzJuKXxDKAQ

**Comment by wwmm** [comment]
This is strange. Which PulseEffects version are you using? I can not reproduce this on `4.4.1` and as far as I remember this has not been a problem for some time. What is printed in the terminal when PulseEffects is executed in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`?

**Comment by es20490446e** [comment]
The version is [4.4.0](https://www.archlinux.org/packages/community/x86_64/pulseeffects/).

**Comment by es20490446e** [comment]
- [Log](https://pastebin.com/RPjgM06x)

**Comment by es20490446e** [comment]
Seems that the root cause of this issue is that [the downstream package isn't updating](https://bugs.archlinux.org/task/61014), even when it's a rolling release distribution.

Could you kindly have a look at the [downstream PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/pulseeffects), and suggest on [their bug report](https://bugs.archlinux.org/task/61014) which changes should go there?

**Comment by wwmm** [comment]
Very strange. I use Arch Linux too and yesterday `4.4.0` was in the repository. Now they downgraded to `4.3.7`. It makes no sense

**Comment by eli-schwartz** [comment]
Okay, @es20490446e please don't submit garbage bug reports, and @wwmm stop making nonsense up about us downgrading anything.

The package is currently on 4.4.0 and it's out of date by exactly 6 days, so there is no need for garbage FUD.

Thanks.

**Comment by wwmm** [comment]
@es20490446e at this moment this is the output of a pacman query `pacman -Ss pulseeffects`:

```
community/pulseeffects 4.3.7-1
    Audio Effects for Pulseaudio Applications
``` 

I am not crazy. Very disrespectful from you to assume I am spreading nonsense

**Comment by eli-schwartz** [comment]
Then your system is out of date: https://www.archlinux.org/packages/community/x86_64/pulseeffects/

**Comment by wwmm** [comment]
My guess is that something wrong is happening in the brazilian server `http://br.mirror.archlinux-br.org/$repo/os/$arch`. After a `pacman -Syyu` I have lots of messages like this `warning: a52dec: local (0.7.4-10) is newer than extra (0.7.4-9)` A few hours ago everything was fine

**Comment by wwmm** [comment]
Just for the record I update my system a few times along the day every day...

**Comment by Scimmia22** [comment]
[   ] lastsync                2018-10-02 03:59

**Comment by eli-schwartz** [comment]
Don't use `-Syyu`, it has never been recommended by the pacman developers and we're not sure where this cargo-culted internet advice originated from.

Using `-Syyu` has the potential to result in a **partial update**, which we don't support.

..

If your current mirror is broken, check the mirror status at https://www.archlinux.org/mirrors/archlinux-br.org/
And consider switching mirrors.

Always look first at the website to see what version is available, as this updates directly from the master repository.

**Comment by es20490446e** [comment]
@wwmm Thanks for your help. I don't know if you did anything but I reinstalled the package, and it seems to be working now?

@eli-schwartz Such an [ace-hole](https://i.gifer.com/C2A.gif).
