### ISSUE TITLE
Pulseeffects cannot find plugins

### ISSUE THREAD

**Issue by CGDoctor8** [wwmm/pulseeffects#393]
I'm have the same issue as #259 On Solus and I'm trying to put together a bug report but I don't exact get whats going on.

It the other issue it says that something is wrong with Gstreamers install because
`gst-inspect-1.0 | grep -i calf` Returns nothing but in my testing on Manjaro that's has all the plugins working it also returns nothing

I have tried removing the cache for gstreamer-1.0 restarting my pc and launching pulse Effects 

```(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.806: limiter plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.806: compressor plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.806: filter plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.809: reverb plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.809: bass_enhancer plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.809: exciter plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.809: crossfeed plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.809: maximizer plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.809: multiband_compressor plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.809: loudness plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.809: gate plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.809: multiband_gate plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.810: deesser plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.810: stereo_tools plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.810: convolver plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.818: limiter plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.818: compressor plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.819: filter plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.820: reverb plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.820: gate plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.820: deesser plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.821: pitch plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.823: multiband_compressor plugin was not found!
(pulseeffects:13417): pulseeffects-WARNING **: 03:39:09.824: multiband_gate plugin was not found!

```

**Comment by wwmm** [comment]
I use Arch and `gst-inspect-1.0 | grep -i calf` returns a lot of things. How di you install on Manjaro? If it was through flatpak it will work even if the system does no has the plugins installed because flatpak has its on libraries embedded in the package.

**Comment by CGDoctor8** [comment]
I didn't do anything special while installing Manjaro and just to be sure i re-did the test in a vm w/Manjaro cinnamon and got slightly different results
![](https://i.imgur.com/3Z25TLK.png)

Then I literally did the same thing again (start a fresh vm with the same settings and installed Manjaro with the same iso) and everything worked fine with gst-inspect seeing calf. 
![](https://cdn.discordapp.com/attachments/507367218070159390/526047217530699807/unknown.png)


Also I don't know how i manged to botch it but with trying flat-pack `flatpak run com.github.wwmm.pulseeffects`

It also don't have most of the plugins (grayed out not clickable)
![ScreenShot](https://i.imgur.com/hYKhKfz.png)

**Comment by wwmm** [comment]
The flatpak package comes with all plugins. So something odd is happening in the installation. Is there any change if you try to reset PulseEffects? You can do this in its settings menu or by giving the command line option `-r`

At least on manjaro you can use the native package in the repository instead of flatpak. In any case this is definitely an installation issue.

**Comment by CGDoctor8** [comment]
That seems to have fixed the flatpak thanks for the help ill go ahead and make a issue over on solus side of things
