### ISSUE TITLE
PulseEffects don't start or stop on music change

### ISSUE THREAD

**Issue by servimo** [wwmm/pulseeffects#394]
PulseEffects don't start or stop on music change. I always have to click in the program minimized and click on the applications menu in pulseefeects to enable

**Comment by wwmm** [comment]
Which music player are you using? Did you switch on `Enable All Applications` in the settings menu?

**Comment by servimo** [comment]
I am using DeadBeef and it is my fault, I din't know about this detail in the configuration. :D
