### ISSUE TITLE
[Feature Request] Change preset automatically depending on which output is used?

### ISSUE THREAD

**Issue by Utini2000** [wwmm/pulseeffects#398]
Hey there,  
I really love this package for Linux. How ever, one thing that makes it a little annoying is the following:  

- I use a preset with "Dolby-Atmos.irs" when using the speakers of my laptop. It greatly increases the sound effects of my speakers.  
- How ever, when I am at home, I will connect my external DAC+AMP+HD800 and for that I for sure do not want any weird preset active with "Dolby-Atmos.irs".  

Could you implement a feature which will automatically swap the presets depending on which output is active / selected in pulseaudio?
Or is there a simple script/server/event that I could run/trigger?

Thanks in advance and btw, great work on this package!!

**Comment by wwmm** [comment]
Hi! I will think about this. It should not be so hard but it will definitely be necessary to create some kind of interface to associate a given preset to an output device.

**Comment by Utini2000** [comment]
@wwmm Well there should already be an interface from Pulseaudio? 
GNOME / Pavucontrol / XFCE (with its Pulse-plugin) allow to show/switch output easily on the fly.
So pulseeffect would need to read the active output as well and then just load the preset that was previously associated with the output?

But I am only a hobby programmer so I am more guessing than knowing :D 

Just as a general question: Does pulseeffect add any delay? Is music now passing through an additonal layer (pulseeffect/pulse/alsa )?

**Comment by wwmm** [comment]
We already ask Pulseaudio to notify us about new `output/input` devices. What we need is the user interface to associate a device to a preset. And of course the code that will trigger the preset loading once the device appears.

Yes. There is a delay introduced. The path is roughly this `audio app -> null sink -> GStreamer pipeline -> output device`. In case you are using a recent PulseEffects version the delay is shown in the headerbar
![screenshot from 2018-12-30 11-07-06](https://user-images.githubusercontent.com/16225172/50547573-4efb6e00-0c23-11e9-92ed-f93e139cca43.png)
In the image above we have a introduced delay of `122 milliseconds`. This value will depend on the value of a few parameters.

**Comment by Utini2000** [comment]
Ah yes I understand. Well, I hope a feature like that is do-able. It would make pulseeffects a lot more comfortable :) 

Thanks for clarifying the chain. I also just saw the delay in the headerbar. Only 5ms... thats nice ;P

**Comment by wwmm** [comment]
I think it can be done. I just have to think about the implementation carefully to avoid bugs when either the preset or the output device is not available. And to avoid possible conflicts when this is trigguered when the applications is starting.

Only 5 ms? Usually I have noises anywhere below 30 ms. But this depends a little on the hardware

**Comment by Utini2000** [comment]
Hmm I checked again and this time its 14-15ms.  

![latency](https://user-images.githubusercontent.com/14877663/50557992-8bde6800-0cea-11e9-8298-9f9c828409c8.png)

However, after deactivating/activating pulseeffect while playing smth in the backround, the latency dropped below 2ms. Maybe the measurement is not correct?

![latency2](https://user-images.githubusercontent.com/14877663/50557998-926cdf80-0cea-11e9-8aa4-43d494fc0e3b.png)

I will try the latency again when I am back home with my external DAC/AMP/HD800S.
Generally speaking, is there anything I could do to improve the latency? I kind of want to have bit-perfect playback on my HD800S. One way would be to disable pulseeffects when I am on my HD800S and use ALSA directly. How ever, I might want to apply EQ settings to fix some trebble on the HD800S :)

**Comment by wwmm** [comment]
The small values you see in the applications sections are the latency between the audio application and our null sink. The value in the headerbar is the total latency between the application and the output device. You can get around `40 ms` by playing a little with the parameters in the `Pulseaudio` section of the settings menu
![screenshot from 2018-12-31 11-15-47](https://user-images.githubusercontent.com/16225172/50560994-7880cc00-0ced-11e9-897b-a1778876f8d3.png)
Smaller values can be obtained decreasing the buffer. But at least here this causes occasional noises. As far as I understand this is a Pulseaudio limitation. It can not get much lower latency values

**Comment by wwmm** [comment]
One more thing to my mental note: it makes no sense to have more than one preset associated to each device. So the implementation has to ensure this does not happen

**Comment by wwmm** [comment]
Implemented in the master branch
![screenshot from 2019-02-09 14-43-57](https://user-images.githubusercontent.com/16225172/52523514-4b72f200-2c79-11e9-9005-776b545ca426.png)

Just click over the button with curved arrows that the preset will be auto loaded whenever the device currently selected as default becomes the default again. As you can see in the image this can be done for input and output devices independently.

I will probably release the new version tomorrow or Monday. If possible try to test it

**Comment by Utini2000** [comment]
Awesome! Will instantly test it when its released :) 

I wonder how it works with my laptop:
- Speakers are always active
- When attaching my headphones the speakers are basically still connected

**Comment by wwmm** [comment]
It will depend if Pulseaudio creates a new default device output for the headphone or not. If the speakers remain as the default device and the headphone are just a port inside the speakers device it won't work. At least here with my usb mic everything is fine. But Pulseaudio creates a new device for it

**Comment by wwmm** [comment]
Pavucontrol will show if a new device is created for the headphone

**Comment by Utini2000** [comment]
Yay it works perfectly fine! Also when both devices are plugged in, pulseeffect will chose the preset depending on the default output I select.
Awesome work!  

Did you also change smth with priority? It seems to me like the latency is lower than before?

**Comment by wwmm** [comment]
Although it was not the primary intention there were some changes that reduced latency for people that do not enable the convolver. As this plugin needs buffer sizes following powers of 2 some buffering has to be done. In older versions this buffering was always done

**Comment by artogahr** [comment]
For everyone coming to this issue like me for the current version under Wayland, under Pipewire tab the "Presets Autoloading" menu does just this.

Thanks @wwmm !

**Comment by A1steaksa** [comment]
For those coming to this issue in 2026, look for a "Presets" button in the top-left corner and then an "Autoload" tab at the top of the presets pop-over
