### ISSUE TITLE
IRS Files Not Loading

### ISSUE THREAD

**Issue by Hedronmx** [wwmm/pulseeffects#399]
I have installed PulseEffects via PPA on Elementary os 5.0 Juno (Based on Ubuntu 18.04)
I get the following error
```
(pulseeffects:15704): pulseeffects-DEBUG: 04:51:34.786: convolver: irs file does not exists or it is empty: (pulseeffects:15704): pulseeffects-DEBUG: 04:51:34.786: convolver: we will just passthrough data.
```
Even though I have the files inside ~./config/PulseEffects/irs/
I even tried loading them through the gui with no avail and I have used plenty of irs files.

![image](https://camo.githubusercontent.com/12c5b8dfd464ecd0cdafcc88f449fd2bbba349c3/68747470733a2f2f692e696d6775722e636f6d2f6b344e417256642e706e67)

**Comment by wwmm** [comment]
It may seem a silly question but did you click on the impulse name? Based on the image above it seems you imported a impulse file but you did not selected it. As the interface isn't that intuitive right now this step may not be obvious

**Comment by Hedronmx** [comment]
Jesus... I feel really stupid now. Thanks....
