### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by pafri** [wwmm/pulseeffects#4]
The localization would be supported?

**Comment by wwmm** [comment]
I was thinking about this a few days ago and then I realized I have no idea about how people implement localization XD I want to support this but I have to learn how to do it first. Is there a good tutorial for python3 + gtk3 applications?

**Comment by wwmm** [comment]
Hi!

I have just added localization support :) For now there is just brazilian portuguese besides standard english. I did some tests running "LC_ALL=pt_BR.utf8 pulseeffects" and it seems everything is ok. Let me know if there is any problem.

**Comment by wwmm** [comment]
closing
