### ISSUE TITLE
py issue

### ISSUE THREAD

**Issue by mfoxdogg** [wwmm/pulseeffects#40]
when i try to launch

mfoxdogg@LINUX-4OBW:~/bin/pulseeffects> pulseeffects 
16:17:58.587 - PulseEffects - INFO - pulseaudio context started
16:17:58.587 - PulseEffects - INFO - connected to server: /run/user/1000/pulse/native
16:17:58.588 - PulseEffects - INFO - server protocol version: 31
16:17:58.588 - PulseEffects - INFO - pulseaudio version: 9.0-rebootstrapped
16:17:58.588 - PulseEffects - INFO - default pulseaudio source: alsa_input.usb-AKM_AK5370-00.analog-mono
16:17:58.588 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
16:17:58.588 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
16:17:58.588 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
16:17:58.589 - PulseEffects - INFO - default pulseaudio source audio format: s16le
16:17:58.589 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
16:17:58.589 - PulseEffects - INFO - loading Pulseeffects applications sink...
16:17:58.589 - PulseEffects - INFO - sink owner module index: 32
16:17:58.591 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
16:17:58.591 - PulseEffects - INFO - Pulseeffects apps sink index:2
16:17:58.591 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
16:17:58.592 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
16:17:58.592 - PulseEffects - INFO - sink owner module index: 33
16:17:58.592 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
16:17:58.592 - PulseEffects - INFO - Pulseeffects mic sink index:3
16:17:58.592 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
Traceback (most recent call last):
  File "/usr/bin/pulseeffects", line 4, in <module>
    __import__('pkg_resources').run_script('PulseEffects==2.0.9', 'pulseeffects')
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.4/site-packages/PulseEffects-2.0.9-py3.4.egg/EGG-INFO/scripts/pulseeffects", line 6, in <module>
    a = Application()
  File "/usr/lib/python3.4/site-packages/PulseEffects-2.0.9-py3.4.egg/PulseEffects/application.py", line 63, in __init__
    self.sie = SinkInputEffects(self.pm.default_sink_rate)
  File "/usr/lib/python3.4/site-packages/PulseEffects-2.0.9-py3.4.egg/PulseEffects/sink_input_effects.py", line 65, in __init__
    self.pipeline = self.build_pipeline()
  File "/usr/lib/python3.4/site-packages/PulseEffects-2.0.9-py3.4.egg/PulseEffects/sink_input_effects.py", line 177, in build_pipeline
    self.output_limiter.set_property('input-gain', 0)
AttributeError: 'NoneType' object has no attribute 'set_property'

opensuse42.2

**Comment by wwmm** [comment]
Hi, gstreamer is not finding swh-plugins. Check if you have a line with `ladspa-fast-lookahead-limiter-1913-so-fastlookaheadlimiter` at the output of the command `gst-inspect-1.0 | grep -i ladspa`.

**Comment by Taubaurt** [comment]
Same problem on Ubuntu gnome 1704 fresh install. 

~/pulseeffects$ pulseeffects
22:33:22.495 - PulseEffects - INFO - pulseaudio context started
22:33:22.495 - PulseEffects - INFO - connected to server: unix:/run/user/1000/pulse/native
22:33:22.495 - PulseEffects - INFO - server protocol version: 32
22:33:22.495 - PulseEffects - INFO - pulseaudio version: 10.0
22:33:22.495 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1f.3.analog-stereo
22:33:22.495 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
22:33:22.496 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
22:33:22.496 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
22:33:22.496 - PulseEffects - INFO - default pulseaudio source audio format: s16le
22:33:22.496 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
22:33:22.496 - PulseEffects - INFO - loading Pulseeffects applications sink...
22:33:22.496 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
22:33:22.496 - PulseEffects - INFO - Pulseeffects apps sink index:5
22:33:22.496 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
22:33:22.497 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
22:33:22.497 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
22:33:22.497 - PulseEffects - INFO - Pulseeffects mic sink index:6
22:33:22.497 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
Traceback (most recent call last):
  File "/usr/local/bin/pulseeffects", line 4, in <module>
    __import__('pkg_resources').run_script('PulseEffects==2.0.9', 'pulseeffects')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.9-py3.5.egg/EGG-INFO/scripts/pulseeffects", line 6, in <module>
    a = Application()
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.9-py3.5.egg/PulseEffects/application.py", line 63, in __init__
    self.sie = SinkInputEffects(self.pm.default_sink_rate)
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.9-py3.5.egg/PulseEffects/sink_input_effects.py", line 65, in __init__
    self.pipeline = self.build_pipeline()
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.9-py3.5.egg/PulseEffects/sink_input_effects.py", line 177, in build_pipeline
    self.output_limiter.set_property('input-gain', 0)
AttributeError: 'NoneType' object has no attribute 'set_property'

I run the command you ask for <gst-inspect-1.0 | grep -i ladspa> but there was no output.

**Comment by mfoxdogg** [comment]
installed swh-plugins and it works

**Comment by Taubaurt** [comment]
I have swh-plugins installed from the beginning. when I run the command <pulseeffects> the sound manager of gnome shows the pulseeffects apps and microphone but the gui is missing, no pulseeffects process running and  also the above terminal output.

**Comment by Taubaurt** [comment]
well finally. I had to download gstreamer1.0-plugins-bad So warning for the Ubuntu friends. This is necessary too. ty for this great app.
