### ISSUE TITLE
Adhere to the GNOME HIG

### ISSUE THREAD

**Issue by vanillajonathan** [wwmm/pulseeffects#401]
Adhere to the [GNOME Human Interface Guidelines](https://developer.gnome.org/hig/stable/) (HIG).

The page on [visual layout](https://developer.gnome.org/hig/stable/visual-layout.html.en) explains the proper spacing around elements.

<img src="https://developer.gnome.org/hig/stable/figures/visual-alignment-spacing.svg" />

**Comment by wwmm** [comment]
I am working on this now. I am laughing a lot with the comments in the phoronix page XD

But seriously. Isn't 18 pixels of space at the borders a little too much? When I look at gnome applications not all of them seem to put so much border space. For example in `gnome-calculator` it seems there is 18 pixels in the menu but not in the main window... Or maybe my eyes are fooling me...

**Comment by wwmm** [comment]
It is also not clear to me exactly where this horizontal space of 12 pixels is supposed to be used. Looking at nautilus headerbar they seem to be using 6 pixels of horizontal space between widgets...

**Comment by wwmm** [comment]
Ah. It seems it is only for labels. I will use 6 pixels on the other cases unless things become hard to read...

**Comment by baerbock** [comment]
@vanillajonathan Stop it you SJW.

**Comment by vanillajonathan** [comment]
I believe 18 pixels around the borders is for dialogs. Maybe not always for the main window, example gedit and GNOME Builder doesn't have 18 pixel padding around the borders on the main window.

You can inspect GTK+ applications with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>D</kbd>.

When a label is placed above the associated widget, I believe 6 pixels of spacing to be adequate.

**Comment by wwmm** [comment]
This sohrtcut did nothing here. I imagine something more is needed to do the inspection
