### ISSUE TITLE
Compile without GStreamer

### ISSUE THREAD

**Issue by antifa-ev** [wwmm/pulseeffects#402]
I consider GStreamer as bloatware and would like to compile PulseEffects without any reference to it.

How can I compile pulsesrc, pulsesink and spectrum statically into PulseEffects?

**Comment by wwmm** [comment]
This is not going to work. All our audio processing is done through a GStreamer pipeline.  You can't have just the plugins you mentioned above. By the way pulsesrc and pulsesink are GStreamer plugins. They are not from pulseaudio sources
