### ISSUE TITLE
Compile error with FreeBSD

### ISSUE THREAD

**Issue by y2kbadbug** [wwmm/pulseeffects#403]
So I am working on a FreeBSD port for Pulse Effects.  For the past 2 weeks I've been using 4.4.1 with a patch to add the plugin fix for /usr/local.  It worked flawlessly for me.

4.4.2, however, fails to build with a linker error.

I've attached the build log.
[pulseeffects-4.4.2.log](https://github.com/wwmm/pulseeffects/files/2717534/pulseeffects-4.4.2.log)

Attaching the Makefile as well:

[Makefile.txt](https://github.com/wwmm/pulseeffects/files/2717535/Makefile.txt)

**Comment by wwmm** [comment]
Based on what I could find I will have to use a few `if/def` preprocessor directives to disable this functionality on freebsd. This system doesn't seem to support this realtime mode

**Comment by y2kbadbug** [comment]
If there is anything I can provide or help, let me know!

**Comment by wwmm** [comment]
I will make some changes to the master branch in a few minutes. IT would be helpful if you tried to compile it. I will post here once the branch is ready

**Comment by wwmm** [comment]
I pushed the changes to the master branch. Are you able to test it?

**Comment by wwmm** [comment]
IT should compile on freebsd now. But the functionality to change the priority and scheduler will probably only work on freebsd if running as root... IF they work at all...

**Comment by y2kbadbug** [comment]
Appears to have the same error.
[pulseeffects-4.4.2.log](https://github.com/wwmm/pulseeffects/files/2717584/pulseeffects-4.4.2.log)

I set the TAGNAME to 401f100 which is the commit you recently made.

**Comment by wwmm** [comment]
Less errors now. I added if/def to more places. Master branch already has the knew code. Now it should be ok XD

**Comment by y2kbadbug** [comment]
So close!
[pulseeffects-4.4.2.log](https://github.com/wwmm/pulseeffects/files/2717589/pulseeffects-4.4.2.log)

**Comment by wwmm** [comment]
Indeed XD but this error is odd. I do not remember have made changes to the file `calibration_mic.hpp`. I don know why it is complaining about this

**Comment by wwmm** [comment]
Try to open the file `include/calibration_mic.hpp` and add this header `#include <iostream>`. Let's see if it makes any difference

**Comment by wwmm** [comment]
In any case as it is compiling I think we can close this. Any errors from this point on will be runtime errors.

I will release a new version with these fixes

**Comment by y2kbadbug** [comment]
I had to finish updating the ports pkg-plist and depends based on the new version, then I will build the pkg, install, test.  I'll follow up with the results.

**Comment by wwmm** [comment]
ok. Version `4.4.3` tarball is already available

**Comment by y2kbadbug** [comment]
Just installed it, all plugins seem to be available.
Tested audio and it sounds good.
![pulseffects-freebsd](https://user-images.githubusercontent.com/6489750/50552513-145cfa00-0c52-11e9-8e3a-89219cc28a70.png)

Thanks for the assistance, I'll be submitting this for review to the FreeBSD ports team now.

**Comment by wwmm** [comment]
I am glad it is working :-)

**Comment by mikhailnov** [comment]
@wwmm as for root required on FreeBSD, I think it may be done via polkit without running the whole application from root

**Comment by wwmm** [comment]
In the first PulseEffects versions we used the `swh` plugins. But that is not the case anymore. So this dependency can be totally removed.

**Comment by y2kbadbug** [comment]
Awesome, removed swh dependency, updated build dependencies, and everything still compiled and ran just fine.  Thanks for the insight @mikhailnov
