### ISSUE TITLE
[Question] PulseEffect stop working and give back to built-in when close the GUI

### ISSUE THREAD

**Issue by Wello6143** [wwmm/pulseeffects#407]
Hi,
As the title, PE stop working and give the sound back to built-in, same with issue #186. I'm using KDE.
What should I do?
P.s. I installed by adding PPA

**Comment by wwmm** [comment]
I need more information. What is printed in the terminal when you execute PulseEffects in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`?

**Comment by Wello6143** [comment]
It's said `(pulseeffects:25047): pulseeffects-DEBUG: 20:44:43.813: application:  destroyed
`

**Comment by Wello6143** [comment]
Seem like something went wrong, isn't it?

**Comment by wwmm** [comment]
It seems you already have an instance running. Try to kill it first `pulseeffects -q`

**Comment by Wello6143** [comment]
Done!

**Comment by wwmm** [comment]
Wait. Unless you start PulseEffects in service mode the effects will be lost once you close the window. Is that the problem? If yes try to run in service mode `pulseeffects --gapplication-service`. Once you have an instance executed like this you can open and close the window without problems. But the service mode should be running automatically

**Comment by Wello6143** [comment]
Ugh...
`Failed to register: Unable to acquire bus name 'com.github.wwmm.pulseeffects'
`

**Comment by Wello6143** [comment]
Ugh...
`Failed to register: Unable to acquire bus name 'com.github.wwmm.pulseeffects'`

**Comment by Wello6143** [comment]
Suddently I logged out and come back in, I had enable start service at login so I login, PE run without UI.

**Comment by Wello6143** [comment]
Seem like I could close this issue, but seem like this error `Failed to register: Unable to acquire bus name 'com.github.wwmm.pulseeffects'` maybe a little trouble. But thanks for your help!

**Comment by wwmm** [comment]
This explains why you were not having service mode since the beginning. We need to interact with dbus for that and for some reason it is failing. IT feels like there is a package installation problem somewhere. If reinstalling PulseEffects and restarting the system does not help my guess is that something in your dbus installation is broken
