### ISSUE TITLE
Installation link for Arch Linux gives a 404 error

### ISSUE THREAD

**Issue by Hassan-Shabbir** [wwmm/pulseeffects#412]
In the README.md file under Installation>Gnu/Linux Packages the Arch Linux link results in a 404 error.

It seems that it got moved to the community repo, since  looking up pulseeffects using pacman (`pacman -Ss pulseeffects`) results in the following:

```
community/pulseeffects 4.4.4-1 [installed]
    Audio Effects for Pulseaudio Applications
```

Here is the correct link:
https://www.archlinux.org/packages/?sort=repo&name=pulseeffects

**Comment by wwmm** [comment]
Thanks! I forgot to update this. Now it is correct
