### ISSUE TITLE
Switch graphic wrong in 4.4.6

### ISSUE THREAD

**Issue by barjac** [wwmm/pulseeffects#414]
Hi again - I just updated our package and am seeing this for all switches:
![pulseeffects_switch](https://user-images.githubusercontent.com/1324702/51214355-92d5bf00-1915-11e9-8db0-a069f9440590.png)
Any ideas?
Our qt is 5.12

Otherwise working fine. :)
Barry

**Comment by wwmm** [comment]
Hi @barjac PulseEffects uses GTK. In any case this happended to me too on Arch Linux after the update to the latest GTK version. Considering that GTK developers have made changes to the switch widgets in the latest version my guess is that this is a GTK bug

**Comment by wwmm** [comment]
I didn't have time to test other themes. Maybe it is a problem with Adwaita

**Comment by barjac** [comment]
OK thanks - I will investigate.

**Comment by wwmm** [comment]
GTK `3.24.3` is the version that causes this issue in Arch Linux. PE `4.4.6` was fine in GTK `3.24.2+7+g43aeb52b73`

**Comment by wwmm** [comment]
The switch is fine in the Adapta theme. It is something in Adwaita

**Comment by wwmm** [comment]
And for some strange reason after going back to Adwaita the switch was fixed
![screenshot from 2019-01-15 22-56-43](https://user-images.githubusercontent.com/16225172/51219643-e990c800-1918-11e9-9145-1ecb78f2f00b.png)
I think that the changes the devs made to Adwaita require some kind of configuration reset
