### ISSUE TITLE
Indonesian Re-edited Locale File

### ISSUE THREAD

**Issue by ardumpl** [wwmm/pulseeffects#415]
Hi, i have been updated Indonesian locale file. But, i wonder about this line

Load a preset. Example: pulseeffects -l music
limiter;compressor;reverberation;equalizer;autovolume;

So, where is string that cannot be translated?
Btw, here for .
[id_ID.zip](https://github.com/wwmm/pulseeffects/files/2767303/id_ID.zip)

po translated file

**Comment by wwmm** [comment]
Master branch updated with the new translation

**Comment by ardumpl** [comment]
Oh man, i thought that if i translate it, it was conflict with the other lines. So i ignore it because it's looked strange lines for me
But the problem that i worrying, it doesn't show. Thanks, dude
