### ISSUE TITLE
Subwoofer support?

### ISSUE THREAD

**Issue by puzzlled** [wwmm/pulseeffects#418]
Hi,
I just found out about this program through a posting on the Netrunner Forum.  I've installed it and looked through all of the applications but can't see any that would facilitate a subwoofer to make stereo output become 2.1.  I wanted to connect a powered subwoofer with no hardware crossover to an otherwise stereo system and so it would be good to have a crossover with adjustable frequency and slope.  If possible it would be nice to select a hardware output for the subwoofer from whatever is available on the machine to accommodate different configurations like USB, Firewire, or built in analog devices.
Perhaps this sort of thing is already possible and I'm missing it?  I've also looked in the KDE settings for connected devices and the on-board audio only shows as stereo even though it has the typical numerous outputs.
Thanks

**Comment by wwmm** [comment]
For now only stereo is supported. As most of the plugins support only 2 channels a very clever rewrite would be needed in order to support more channels without introducing lots of bugs. But I can't start any work on this while Pulseaudio's null sinks do not support reconfiguration on the fly. As they are right now once you load them the sampling rate and the number of channels cannot be changed. This really complicates things and is the reason why #288 is still an open issue

**Comment by puzzlled** [comment]
Okay, thanks.

I have also been thinking about using an older home receiver in a more
flexible way.  These days you can pick up older high quality amplifiers
that have individual channel inputs for next to nothing, or sometimes even
for nothing, on the used market because they don't support HDMI.  As an
example, I got a Yamaha HTR-5170 for free and it has inputs for each of the
5 100W channels, as well as optical and coaxial SPDIF inputs.  With this
kind of capability I was thinking of using it for surround monitoring of my
electronic drums so that each drum sound was placed appropriately in the
sound field when sitting behind the kit.  The most practical way to
implement this would be with four 'satellite' speakers and a subwoofer, but
most receivers don't amplify the sub output so I would use the center
channel for that purpose instead.  When combined with the MIDI and sample
playing capabilities of a Linux box this would make for a pretty deluxe kit
for not much money.  Perhaps this sort of setup would be better suited for
JACK due to the real-time requirements and the fact that it already
requires MIDI.

However, there is a use case for non-performance listening that would also
use the multi-channel input capabilities of these receivers.  I have been
thinking about bi-amping my stereo speakers and running a sub, and this
would also use the 5 available channel inputs and amplifiers, high & low
for each speaker plus a sub.  For this I would need a stereo crossover and
a sub output, which would be lowpass for the sub channel and highpass for
the stereo channels.  Amplifiers have even better performance when working
in a restricted frequency range and active crossovers, when done well, are
much better than passive.

I have to say it again, in terms of audio quality many of these older
receivers are a real bargain for amplification.   When combined with
similar vintage semi-pro audio interfaces (M-Audio FW410 for example) it
can make for great capabilities for very little money.
Thanks again!
