### ISSUE TITLE
[Feature Request] Convolver, option to load separate irs-file for Left and Right channel.

### ISSUE THREAD

**Issue by tnilzon** [wwmm/pulseeffects#419]
Nice if it woud be possible to load separate irs-files for left and right stereo channel. Some irs-files found on the internet are separate Left and Right.

**Comment by wwmm** [comment]
Are these true stereo impulse response files? Or are each of them a mono wave file? Almost all of the impulse files I see on the internet are just a stereo wave file.

**Comment by tnilzon** [comment]
My mistake. When I took a closer look at the files I have found labeled with an "L" and "R" in the filename, they actually are "two-channel mono-to-stereo". So I guess this feature will not be needed. Sorry ;-)
