### ISSUE TITLE
QUESTION about the limiter

### ISSUE THREAD

**Issue by kokoko3k** [wwmm/pulseeffects#42]
I've seen that you use ladspa lookahead limiter.
As far as i know about it, it limits each channel regardless of the other destroying the stereo image.
Is that right? MAybe there are better alternatives?

Thank you for your great work!

**Comment by wwmm** [comment]
Hi, I do not know how the fast lookahead limiter in the swh-plugins works under the hoods(or any of the other plugins). I this is indeed the case it is sad.

Right now only native gstreamer plguins or ladspa plugins can be used nad I think that there is nothing better than this limiter. Maybe there is a lv2 plugin that is better but I just could not find a way to use lv2 plugins in gstreamer.

**Comment by wwmm** [comment]
Now that we can enable/disable all plugins the user can switch off the limiter in case it really destroys the stereo image.
