### ISSUE TITLE
Disable input?

### ISSUE THREAD

**Issue by linkjay** [wwmm/pulseeffects#420]
Hello,

I understand this is kind of a big thing to ask for, but I was hoping maybe there could be a way to disable the whole input side of things? Pulseeffects right now automatically controls all of my input stuff and it gives me some latency issues and sometimes sound doesn't play on that device anymore. 

I am only using pulseeffects for my output, and don't need any effects on my input so is there a way that I could completely disable the input side of pulseeffects?

Thanks.

**Comment by wwmm** [comment]
This will need some changes to the code as the function `Enable All Applications` in the settings menu is applied for both input and output. It is not the end of the world to change this. But I have to think about the best way to reflect this in the interface. So I make no promises :)

All that being said there is something you can do now. Add the applications you do not want to be affected by PulseEffects to the blacklist
![screenshot from 2019-01-27 21-38-16](https://user-images.githubusercontent.com/16225172/51808517-0794eb80-227c-11e9-9423-74c13e5de36e.png)

Write its name as shown in the Applications section. Consider this example with `mpv`
![screenshot from 2019-01-27 21-40-20](https://user-images.githubusercontent.com/16225172/51808528-285d4100-227c-11e9-81c7-a1733162671a.png)
If for some reason we wanted to add it to the blacklist an entry named `mpv Media Player` should be added to the list. Note that there are 2 blacklists in the interface. One for input and other for output effects. Both list are saved to the `user preset` file once you save the preset. Also note that the blacklist takes effects only when the audio app is restarted.

**Comment by wwmm** [comment]
Latest code in master has a reworked `Enable All Apps` functions. It was split in two and it is now possible to apply effects to the output of all apps while not applying effects for the microphone. As long as not app has its switch enabled in the microphone section the input effects pipeline will not be running

**Comment by linkjay** [comment]
Thank you!
