### ISSUE TITLE
High cpu usage when PA server stream pauses/stops

### ISSUE THREAD

**Issue by barjac** [wwmm/pulseeffects#423]
As requested here is a screenshot of top with no transmission present  and the output file from PE debug:
![pe_top](https://user-images.githubusercontent.com/1324702/52072611-3e6d4900-257d-11e9-85a9-a78bd7a23868.png)
[PE_output.txt](https://github.com/wwmm/pulseeffects/files/2818330/PE_output.txt)

**Comment by wwmm** [comment]
Considering that the last line in the log is `PAUSED -> PLAYING -> VOID_PENDING` The stream didn't pause. It is playing. My guess is that there is an audio app playing silence on your system. It could be the one you are using or something else.

**Comment by wwmm** [comment]
Run the command `pactl list sink-inputs` when the high cpu usage happens and your applications is supposed to be paused. It will show us who else is playing audio

**Comment by barjac** [comment]
[baz@localhost ~]$ pactl list sink-inputs
Sink Input #0
        Driver: protocol-native.c
        Owner Module: 9
        Client: 10
        Sink: 1
        Sample Specification: float32le 1ch 8000Hz
        Channel Map: mono
        Format: pcm, format.sample_format = "\"float32le\""  format.rate = "8000"  format.channels = "1"  format.channel_map = "\"mono\""
        Corked: no
        Mute: no
        Volume: mono: 47841 /  73% / -8.20 dB
                balance 0.00
        Buffer Latency: 125000 usec
        Sink Latency: 624 usec
        Resample method: speex-float-1
        Properties:
                media.name = "Airband"
                application.name = "rtl_airband"
                native-protocol.peer = "TCP/IP client from 192.168.1.96:53354"
                native-protocol.version = "32"
                application.process.id = "402"
                application.process.user = "root"
                application.process.host = "fr24air"
                application.process.binary = "rtl_airband"
                application.language = "C"
                application.process.machine_id = "41b2082c495a49eb98535e0841ee519c"
                module-stream-restore.id = "sink-input-by-application-name:rtl_airband"

Sink Input #2
        Driver: protocol-native.c
        Owner Module: 8
        Client: 11
        Sink: 0
        Sample Specification: float32le 2ch 44100Hz
        Channel Map: front-left,front-right
        Format: pcm, format.sample_format = "\"float32le\""  format.channels = "2"  format.rate = "44100"  format.channel_map = "\"front-left,front-right\""
        Corked: no
        Mute: no
        Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        Buffer Latency: 21473 usec
        Sink Latency: 84145 usec
        Resample method: copy
        Properties:
                application.id = "com.github.wwmm.pulseeffects.sinkinputs"
                media.name = "Playback Stream"
                application.name = "PulseEffects"
                native-protocol.peer = "UNIX socket client"
                native-protocol.version = "32"
                application.icon_name = "pulseeffects"
                application.process.id = "11207"
                application.process.user = "baz"
                application.process.host = "localhost.localdomain"
                application.process.binary = "pulseeffects"
                application.language = "en_GB.UTF-8"
                window.x11.display = ":0"
                application.process.machine_id = "8ebef8c1a5964350a88949bdb99c6a75"
                application.process.session_id = "c2"
                module-stream-restore.id = "sink-input-by-application-id:com.github.wwmm.pulseeffects.sinkinputs"
[baz@localhost ~]$

**Comment by wwmm** [comment]
You application is the first in the list `Sink Input #0`. Take a look at the line with `Corked: no`. This is Pulseaudio's way to tell if the stream is running or not. The `no` value means that the stream is playing. `Airband` is playing silence instead of pausing the stream. This is bad because we rely on the `corked` state to `apuse/unpause` PulseEffects pipeline.

There is always the possibility that other unknown issues can be increasing PulseEffects cpu usage. But the first step is making `Airband` stop playing silence. But this is something that `Airband` developers will have to take care of.

**Comment by barjac** [comment]
I have checked the traffic between the machines and it stops when there is no transmission present, but 'Corked: no' is still there. I have asked in the other bug about this. 
BTW the switch icons are now OK again. Not sure what changed :)

**Comment by barjac** [comment]
Slightly off topic, but I would like your comments on the following messages which I see when starting PE in a terminal. I can clear the first block of errors by Requiring linuxsampler as that manifest.ttl is packaged in our lib64linuxsampler5 package. However this causes an issue when building PE for aarch64 as linuxsampler is not available for aarch64. Does this matter and can we ignore the error and drop linuxsampler as a require?

Regarding the missing plugins, I can fix convolver by packaging and BuildRequiring it, but I don't know about the others?

Thanks.

`error: failed to open file /usr/lib64/lv2/linuxsampler.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/lib64/lv2/linuxsampler.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib64/lv2/linuxsampler.lv2/manifest.ttl
error: failed to open file /usr/lib64/lv2/linuxsampler.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/lib64/lv2/linuxsampler.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib64/lv2/linuxsampler.lv2/manifest.ttl

(pulseeffects:24525): pulseeffects-WARNING **: 17:26:04.181: maximizer plugin was not found!

(pulseeffects:24525): pulseeffects-WARNING **: 17:26:04.185: loudness plugin was not found!

(pulseeffects:24525): pulseeffects-WARNING **: 17:26:04.187: pitch plugin was not found!

(pulseeffects:24525): pulseeffects-WARNING **: 17:26:04.195: convolver plugin was not found!

(pulseeffects:24525): pulseeffects-WARNING **: 17:26:04.198: delay plugin was not found!

(pulseeffects:24525): pulseeffects-WARNING **: 17:26:04.216: pitch plugin was not found!`

**Comment by wwmm** [comment]
I do not have `linuxsampler` installed. So at least to PulseEffects it does not matter. And I do not have these error messages here. So I'd say something is not right in your install. Try to remove GStreamer cache `.cache/gstreamer-1.0/registry.x86_64.bin`. Maybe it helps. `lilv_world_load_file` is from the package `lilv`. GStreamer uses it to load `LV2` plugins. So it may be worth to check if something is wrong with the `lilv` install.

`maximizer` is from `ZamAudio` plugins https://www.archlinux.org/packages/community/x86_64/zam-plugins/, `loudness` is from `MDA` https://www.archlinux.org/packages/community/x86_64/mda.lv2/, `pitch` is from `Rubberband` https://www.archlinux.org/packages/community/x86_64/rubberband/ and the `delay` is from `Linux Studio Plugins` https://www.archlinux.org/packages/community/x86_64/lsp-plugins/

**Comment by barjac** [comment]
Thanks for those pointers.
I can see nothing wrong with lilv but I have removed linuxsampler as a require (and from the machine).
I packaged zita-convolver-4.0.3 and then tried to build zam-plugins, but there were undefined symbols which related to convolver. After grepping the sources for zita-convolver 4.0.3 and 3.1.0 it was apparent that those symbols don't exist in 4.0.3. So I reverted to zita-convolver 3.1.0 and zam-plugins builds (albeit with lots of warnings).
However the build of PE built with zita-convolver and zam-plugins all available at run time is not showing any high cpu usage with only the equalizer enabled as before! cpu in top for PE is steady with or without audio (zero_fill) at ~8%.
I will test without zam-plugins installed to narrow down what has made the difference.

In terminal after switching all effect switches ON/OFF
[baz@localhost pulseeffects]$ pulseeffects
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
error: failed to open file /usr/lib64/lv2/linuxsampler.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/lib64/lv2/linuxsampler.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib64/lv2/linuxsampler.lv2/manifest.ttl
error: failed to open file /usr/lib64/lv2/linuxsampler.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/lib64/lv2/linuxsampler.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib64/lv2/linuxsampler.lv2/manifest.ttl

(pulseeffects:9598): pulseeffects-WARNING **: 18:04:29.853: loudness plugin was not found!

(pulseeffects:9598): pulseeffects-WARNING **: 18:04:29.856: pitch plugin was not found!

(pulseeffects:9598): pulseeffects-WARNING **: 18:04:29.870: delay plugin was not found!

(pulseeffects:9598): pulseeffects-WARNING **: 18:04:29.889: pitch plugin was not found!

(pulseeffects:9598): pulseeffects-CRITICAL **: 18:09:44.015: pulse_manager: failed to move sink input: Telegram, idx = 17 to PE

(pulseeffects:9598): pulseeffects-CRITICAL **: 18:09:44.018: pulse_manager: failed to move sink input: Telegram, idx = 18 to PE

(pulseeffects:9598): Pango-CRITICAL **: 18:09:44.023: pango_layout_set_width: assertion 'layout != NULL' failed

(pulseeffects:9598): Pango-CRITICAL **: 18:09:44.023: pango_layout_set_alignment: assertion 'layout != NULL' failed

(pulseeffects:9598): Pango-CRITICAL **: 18:09:44.023: pango_layout_set_text: assertion 'layout != NULL' failed

(pulseeffects:9598): pulseeffects-CRITICAL **: 18:10:54.997: pulse_manager: failed to move sink input: Telegram, idx = 19 to PE

(pulseeffects:9598): pulseeffects-CRITICAL **: 18:10:55.000: pulse_manager: failed to move sink input: Telegram, idx = 20 to PE

(pulseeffects:9598): Pango-CRITICAL **: 18:10:55.005: pango_layout_set_width: assertion 'layout != NULL' failed

(pulseeffects:9598): Pango-CRITICAL **: 18:10:55.005: pango_layout_set_alignment: assertion 'layout != NULL' failed

(pulseeffects:9598): Pango-CRITICAL **: 18:10:55.005: pango_layout_set_text: assertion 'layout != NULL' failed

(pulseeffects:9598): Pango-CRITICAL **: 18:10:55.005: pango_layout_set_width: assertion 'layout != NULL' failed

(pulseeffects:9598): Pango-CRITICAL **: 18:10:55.005: pango_layout_set_alignment: assertion 'layout != NULL' failed

(pulseeffects:9598): Pango-CRITICAL **: 18:10:55.005: pango_layout_set_text: assertion 'layout != NULL' failed

**Comment by wwmm** [comment]
Still happening in `4.5.0`?

**Comment by barjac** [comment]
No - it seems OK now, with and without the extra plugins installed. I have tried to reproduce the high CPU situation in two Mageia Cauldron (Mga7) systems  and while there are differences in load between the two systems, neither is showing the astronomical loads that I was seeing previously.
In a terminal I still see these three messages:
(pulseeffects:5754): Pango-CRITICAL **: 23:54:45.545: pango_layout_set_width: assertion 'layout != NULL' failed

(pulseeffects:5754): Pango-CRITICAL **: 23:54:45.545: pango_layout_set_alignment: assertion 'layout != NULL' failed

(pulseeffects:5754): Pango-CRITICAL **: 23:54:45.545: pango_layout_set_text: assertion 'layout != NULL' failed

If these are harmless then I think we can close this. Many thanks for your help :)

**Comment by wwmm** [comment]
I do not have those errros in my PC. Pango is used to draw the numerical values the spectrum shows you when the mouse moves over it. We do this since forever. So if you did not have this kind of error before my guess is that some kind of regression happended in one of the GTK libraries in your system. Try to reinstall, upgrade or downgrade the packages `pango` and `pangomm`. Maybe something changes
