### ISSUE TITLE
Separate presets for output and mic

### ISSUE THREAD

**Issue by Bleuzen** [wwmm/pulseeffects#424]
Hi, I often change presets for my mic, for example when singing or speaking... the problem is that I don't want to change the effects for apps output everytime.

It would be nice to have separate presets for mic / apps.

Or maybe only load the mic part of the preset if on mic tab, and only load the output part of the preset if on output tab.. this would keep compatibility with the current presets, but would be a messy solution, because users have to remember which presets are for mic and which for output (or put it in the filename, which may also get messy with some presets).
Separate preset files would be better, but may break presets created with older PulseEffects versions. Maybe you have a better idea?

**Comment by wwmm** [comment]
The presets popover menu would have to become more elaborate. Using for example a stack switcher like the settings menu already does in order to show 2 listbox. One for input and other for output. It will require a code refactoring that may not be small and it will break compatibility. But I do not see a way to avoid any of them.

But this is not all that we have to think about. Effects parameters are not the only thing saved to the preset. Spectrum settings and the applications blacklist are also saved to the preset. In case we split input and output something has to be done about this. Maybe we could save these settings to both presets. But it smells like code will be duplicated in the process... I have to think better about this..

**Comment by wwmm** [comment]
Maybe the compatibility will be only partially broken. The preset is a `json` file with seperated sections for input and output. We can load the corresponding section of the unified preset. It shouldn't be a problem.

**Comment by wwmm** [comment]
And in other to not show input and output presets on the same list we would have to save them in different folders. What in turn will require some changes to the code that imports the presets...

Well... It can be done... But some work will be needed...

**Comment by wwmm** [comment]
Implemented in the master branch
![screenshot from 2019-02-09 14-43-57](https://user-images.githubusercontent.com/16225172/52523608-fedbe680-2c79-11e9-890f-518c4fffa17c.png)

I decided to break compatibility XD As you will notice when you try the next release or the master branch I moved from GStreamer equalizer to Linux Studio Plugins equalizer. This change alone required a compatibility break. It is not elegant to do that but it is life. I think that the new features coming in the next release outweigh by far the need to recreate the presets.

It is not total break. With the exception of the equalizer a copy and paste in a text editor is enough to port the old preset to the new structure.

**Comment by Bleuzen** [comment]
Ok, yeah compatibility break is no big deal for me.
Great thank you, seems to be working!

**Comment by wwmm** [comment]
Good to know! I will probably release the next version tomorrow or Monday. Let me know if you find any problem

**Comment by wwmm** [comment]
By the way this is the new equalizer http://lsp-plug.in/?page=manuals&section=para_equalizer_x32_lr

**Comment by Bleuzen** [comment]
I noticed it. Will give it some more testing later today or tomorrow and report back.

**Comment by Bleuzen** [comment]
I used it, switched around between presets... worked so far, seems ready for release :)

**Comment by wwmm** [comment]
Ok! :-)

**Comment by Bleuzen** [comment]
OH NO FUCK WAIT
I found something wrong in translation.. I will fix it soon!

**Comment by wwmm** [comment]
ok. I am still thinking about some changes in the dynamic pipeline.
