### ISSUE TITLE
Hide mic playback device

### ISSUE THREAD

**Issue by DanielRios549** [wwmm/pulseeffects#425]
I don't use PulseEffect for microphone yet, maybe I'll use in the future but not today, is there a way to hiding or disable PulseEffect(mic) playback device?

**Comment by wwmm** [comment]
There isn't. This would complicate too much the code. In the future there will be probably a way to disable the processing #420 of input devices but `PulseEffects(mic)` will remain loaded.

For now what you can do is adding to the blacklist the apps you do not want to have the mic processed

**Comment by wwmm** [comment]
Latest code in master has a reworked `Enable All Apps` functions. It was split in two and it is now possible to apply effects to the output of all apps while not applying effects for the microphone.
