### ISSUE TITLE
On/Off master switch flipped

### ISSUE THREAD

**Issue by Zackptg5** [wwmm/pulseeffects#43]
HI, I'm on manjaro KDE 64 bit. I was very confused at first because the master switch at the bottom right of the app was switched to off except sound worked. When I flipped it on, all sound was muted (but the visualizer still showed sound). Took me a moment but I realized that the on/off switch seems to be backwards. I attached the sink about if that helps at all
[pactl list sinks output.txt](https://github.com/wwmm/pulseeffects/files/1160492/pactl.list.sinks.output.txt)

The first image is with sound working, and the second is with sound not working (see switch and visualizer in it)
![sound working](https://user-images.githubusercontent.com/5107713/28389910-fba2ad18-6ca5-11e7-8c09-c2b2b3e065f1.png)
![sound not working](https://user-images.githubusercontent.com/5107713/28389911-fd65160e-6ca5-11e7-97f2-158a1fe6d147.png)

Thanks

**Comment by wwmm** [comment]
humm... This does not happen here. The switch button is working as it should. If you run PulseEffects from the command line there is any message printed when switching on/off ?  THis is happening to other applications other than Rhythmbox? If you restart pulseaudio the issue persists?

**Comment by Zackptg5** [comment]
Here's the terminal output:
[terminal output.txt](https://github.com/wwmm/pulseeffects/files/1160683/terminal.output.txt)
Yes, it happens with all applications (gpdmp, chrome, etc)

The problem persists after restarts

**Comment by wwmm** [comment]
Nothing strange in the terminal output. Maybe pavucontrol window can offer clues. Can you take a snapshot of pavucontrol playback tab before and after toggling the switch?

**Comment by Zackptg5** [comment]
Well sorry for wasting your time. It does work now, the sound just was decreased in volume so drastically I couldn't hear it once I flipped the switch. Thanks for your time!

**Comment by Zackptg5** [comment]
Actually, I can't adjust the volume any higher or I hear this weird scifi noise. Any ideas?

**Comment by wwmm** [comment]
No problems, it happens XD.

Which volume exactly? By the images above the application volume is already at 100 %

**Comment by Zackptg5** [comment]
The actual audio output device volume. The volume shown in the pulseeffects app appears to be its own. It works, but is not the same as the actual system device's volume level

**Comment by wwmm** [comment]
This is how my volumes are in pavucontrol

![screenshot from 2017-07-19 20-39-00](https://user-images.githubusercontent.com/16225172/28394293-54ee9dfc-6cc2-11e7-8b67-7cb2593fca29.png)
![screenshot from 2017-07-19 20-38-48](https://user-images.githubusercontent.com/16225172/28394294-5554c6fe-6cc2-11e7-9e14-567d66e3c032.png)

**Comment by Zackptg5** [comment]
Mine looks the same. I mean that if I increase system volume with effects on, i get all sorts of weird scifi noises.

**Comment by wwmm** [comment]
It seems that is happening audio clipping. PulseEffects output has a limiter set to 0 dB to avoid saturating the output device. So I am not sure exactly where this problem is.

**Comment by Zackptg5** [comment]
Okay, well the original reason for opening this has been solved so I'll close it and look more into clipping. Thanks
