### ISSUE TITLE
Update pulseeffects 4.5 can't find equalizer plugin

### ISSUE THREAD

**Issue by BERNARDO31P** [wwmm/pulseeffects#432]
Greetings,

There was an update about three days ago which first of all fully destroyed my microphone settings. The equalizer doesn't work at all and when I start it over the terminal there's a message "Could load or find the equalizer module". 
I now just downgraded to 4.4.7 and everything works just as expected.
I'm currently on ArchLinux with the 4.20.7-zen1-1-zen kernel.

If you need any further information from me, please contact me.

Kind regards,
Bernardo de Oliveira

**Comment by wwmm** [comment]
Take a lookt at our changelog https://github.com/wwmm/pulseeffects/blob/master/CHANGELOG.md The features added in this version required a few changes to the preset structure. With the exception of the equalizer settings you can port your old preset to the new structure by doing some copy and past in a text editor.

In version `4.5.0` I moved to the equalizer from Linux Studio PLugins. In arch this package is named `lsp-plugins`. The package maintainer did not add it as a dependency yet

**Comment by BERNARDO31P** [comment]
So, I'll need to wait, or is there any alternative?

Kind regards,
Bernardo de Oliveira

**Comment by wwmm** [comment]
No need to wait. Upgrade to `4.5.0` and install the package `lsp-plugins` manually that the equalizer will work. But as the equalizer was changed you will have to recreate your preset. Open your old preset in a text editor and take the `gain`, `width` and `frequency` value for each band. You can calculate the quality values needed by the new format this way `quality = frequency / width`

**Comment by BERNARDO31P** [comment]
Alright. I'll try and get back to tell if everything works!

Thanks for the really fast support.
Kind regards,
Bernardo de Oliveira

**Comment by BERNARDO31P** [comment]
Everything works now with the [lsp-plugins](https://www.archlinux.org/packages/community/x86_64/lsp-plugins/) package on ArchLinux.
Thank you very much!

Kind regards,
Bernardo de Oliveira
