### ISSUE TITLE
Is it worth to install Pulseaudio 12 in order to have PulseEffects running properly?

### ISSUE THREAD

**Issue by fvroig** [wwmm/pulseeffects#434]
So, I have tried PulseEffects in Ubuntu 18.04 and it is an outstanding application. Unfortunately, it showed the same nasty behaviour already reported by others: it assumes the control of the volume of the system, so for example the hot keys do not work anymore.
I tried the suggested solution of unloading the module-switch-on-connect module from pulseaudio, but this did not fix the issue! Then, a possibility would be to try to upgrade pulseaudio from 11.1 to 12, but I am afraid that in doing such upgrade I screw up other parts of my system.
So my question is if it worth the risk to install pulseadio 12. And if I install it from the ppa repository of mikhailnov, and it actually screw up my system, is there any way to revert to 11.1?
I really would like to have pulseeffects running properly, but I had bad experiences with unsupported software in the past.
Advise is very welcome

**Comment by wwmm** [comment]
Which desktop are you using? KDE? If yes you should unload `module-device-manager` too. As far as I know these too modules are the only ones causing problems for people on Pulseaudio 11 or older.

It is also worth to check if you are using any kind of service or application that tries to automatically manage audio devices. I remember a user had similar problems with these kinds of applications in the past.

As I use Arch Linux I don't know how risk can be upgrading Pulseaudio from a ppa in Ubuntu. You may try to use the flatpak package. But it is a little outdated.

**Comment by fvroig** [comment]
Thanks Wellington for your quick reply. Sorry for not clarifying my configuration: I am using Gnome, with gdm3 and cinnamon desktop. I am aware of the issue with module-device-manager in KDE, but it is not my case. BTW, I also tried unloading both modules, module-switch-on-connect  and  module-device-manager, but it didn't help.
As for the PulseEffects distros, I first tested the flatpak package (which I hated, because it was my first experience with flapak and I found a horrible approach to package management). Then I removed the flatpak package and compiled PE from source. Not only the problem was present in both cases, but in the latter PE also introduced a large distortion and noise in the sound.
So after those failures, I started to think in the possibility to migrate to pulseaudio 12.
I didn't try to make the tests using other display manager (eg. lightdm) or a different desktop (eg. unity), but in principle I do not see why this could lead to a different result.
Now I am thinking that I could try make the tests, including migration to pulseaudio 12, using the Ubuntu LiveCD without compromising my installation. Let's see.

**Comment by wwmm** [comment]
If you are on Gnome and both modules were unloaded before starting PulseEffects using Pulseaudio 11 should not cause our sink to become the default device. This is the reason why your hotkeys are not working as intended. Something is making one of our sinks the default output device. As there is no code in PulseEffects that could do that and the Pulseaudio modules that used to do this are not loaded you have something else installed causing this.

Are you setting `PulseEffects(apps)` as default device in Gnome control center? If yes undo this setting. PulseEffects is intended to be used with your soundcard as default device.

I think it is worth to follow the steps in the `Advanced Pulseaudio Logs` sections https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs and get the logs when your hotkeys stop working. It may give a hint to the source of the problem.

**Comment by fvroig** [comment]
Ok, I am not sure what happened but now it is working! So what did I do?
First, I removed all the packages that flatpak installed when I tested their version of PulseEffects.
The I removed all the packages that were installed when I compiled PulseEffects from source.
At this point, my distribution was the same I had before starting to try using PulseEffects.

Furthermore, I also removed pulseaudio-equalizer and all its related packages.
So I ended with the standard packages that Ubuntu 18.04 installs by default, plus pavucontrol (for some reason, my installation did not have pavucontrol by default, so I have to install it).

Then I manually downloaded the PulseEffects debian packages from Mikhailnov's repository
http://ppa.launchpad.net/mikhailnov/pulseeffects/ubuntu/pool/main/p/pulseeffects/

Note that I got the individual packages instead of including the ppa repository, so I can install PulseEffects without being forced to upgrade to pulseaudio 12. More precisely, the packages I got were:
pulseeffects_4.4.7-1~bionic1_amd64.deb
gstreamer1.0-adapter-pulseeffects_4.4.7-1~bionic1_amd64.deb
gstreamer1.0-autogain-pulseeffects_4.4.7-1~bionic1_amd64.deb
gstreamer1.0-convolver-pulseeffects_4.4.7-1~bionic1_amd64.deb
gstreamer1.0-crystalizer-pulseeffects_4.4.7-1~bionic1_amd64.deb
calf-plugins_0.90.1-1~bionic1_amd64.deb
Then I manually installed all these packages, together with the recommended dependencies.

Finally, I edited /etc/pulse/default.pa and commented (once again) the lines
#.ifexists module-switch-on-connect.so
#load-module module-switch-on-connect
#.endif

Kill and restart pulseaudio (pulseaudio -k ; pulseaudio --start), check that the unwanted module was actually not loaded (pactl list modules short), open Rhythmbox, pavucontrol and PulseEffects, and cha-chan! It works on the fly!

Here are the screenshots of the configuration in pavucontrol while a music is playing in Rythmbox
![captura de tela de 2019-02-14 18-09-57](https://user-images.githubusercontent.com/47616392/52815037-c3c82180-3084-11e9-85bf-997e73e98a97.png)
![captura de tela de 2019-02-14 18-13-51](https://user-images.githubusercontent.com/47616392/52815056-c9be0280-3084-11e9-854e-8bcac1b80966.png)
![captura de tela de 2019-02-14 18-14-03](https://user-images.githubusercontent.com/47616392/52815063-cd518980-3084-11e9-81cf-60fbd7868426.png)
![captura de tela de 2019-02-14 18-14-17](https://user-images.githubusercontent.com/47616392/52815070-d17da700-3084-11e9-9716-ab57496370bd.png)

The only thing I do not understand is why in the Recording tab PulseEffects is recording stream from PulseEffects(app) and if I mute this, all the sound becomes muted. But who cares, it is working and it rocks!

Thanks

**Comment by wwmm** [comment]
Applications output is redirect to `PulseEffects(apps)`. Then we record from this sink monitor to apply effects. This is how it has to be :-)

**Comment by fvroig** [comment]
Aha! Clever trick. Therefore I presume that in order to use the mic to talk (eg Skype or so) I must quit pulseeffects first, right?

**Comment by wwmm** [comment]
It is not necessary. In case you do not want skype input or output to be processed just turn off the corresponding per app switch you see in PulseEffects applications section

**Comment by wwmm** [comment]
You can also add it to the blacklist in PulseEffects settings menu. In our help manual you can see the details to do this
