### ISSUE TITLE
Equalizer is not working

### ISSUE THREAD

**Issue by MarcinW87** [wwmm/pulseeffects#435]
After update of pulseeffects to version 4.5.0-2 equalizer is not working. It seems to bo turned on but there is no effect. 

![zrzut ekranu deepin_pulseeffects_20190216151517](https://user-images.githubusercontent.com/47693241/52901012-dade4f00-31fd-11e9-8eaa-d8e7e83d9439.png)

**Comment by wwmm** [comment]
From version `4.5.0` onward the Linux Studio package is needed for the equalizer to work. At least in Arch Linux this package is named `lsp-plugins`

**Comment by MarcinW87** [comment]
I'm on Manjaro so it should be simple.  What about Calf plugins? Do I need them too?

**Comment by wwmm** [comment]
You only need calf if you want to us e other plugins like the limiter,compressor, bass enhancer,etc. If you only want crystalizer and the equalizer Calf is not necessary.
