### ISSUE TITLE
Nothing work or apply

### ISSUE THREAD

**Issue by orblazer** [wwmm/pulseeffects#436]
Hello,

I have download `PulseEffects V4.5.0-2` an `4.20.10-arch1-1-ARCH` (Antergos) but i have an problem, when i whant change something, that have absolutely no effect.

The settings change on interface but is not changed on my output sound.

Thanks

**Comment by wwmm** [comment]
Did you enable the per application switch or turned on `Process All Outputs` in the settings menu?
![screenshot from 2019-02-18 22-02-11](https://user-images.githubusercontent.com/16225172/52983247-efbb0e00-33c8-11e9-8b18-4f0b8dbecae1.png)

**Comment by orblazer** [comment]
I have found my problem, this is only because i have install /home on NTFS disk... Sorry for the inconvenience.
