### ISSUE TITLE
Who does downmix and where it's done?

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#443]
Hello everyone. First of all, thank you for this great application. I had some annoyance with audio playback in the past on my system (Arch Linux with Plasma 5). With Alsa sometimes volume was low even at the highest level. Solved this with Pulseaudio, but I felt high differences in audio levels across various sources. Sometimes even in the same video playback, some parts were louder, others too quiet, I used to adjust volume level over and over, that was quite annoying. But PulseEffects solved all of this, Auto Gain + Compressor it's the best combo for me. Now I barely touch the volume key buttons.

Anyway, that's something very interesting that I want to point out. It's not really an issue. I have some mkv files with 5.1 audio. I use mpv for reproduction and reading its [documentation,](https://mpv.io/manual/stable/#options-audio-channels) there are some options to set audio output:

> --audio-channels=auto-safe
> Use the system's preferred channel layout. If there is none (such as when accessing a hardware device instead of the system mixer), force stereo. Some audio outputs might simply accept any layout and do downmixing on their own.
> 
> --audio-channels=auto
> Send the audio device whatever it accepts, preferring the audio's original channel layout. 
> 
> --audio-channels=stereo
> Force a plain stereo downmix.

Followed by this warning:

> If the list of channel layouts has only 1 item, the decoder is asked to produce according output. This sometimes triggers decoder-downmix, which might be different from the normal mpv downmix. One consequence is that --audio-channels=stereo triggers decoder downmix, while auto or auto-safe never will, even if they end up selecting stereo.

According to what I read, if I set auto-safe, mpv would output stereo since it picks preferred channel layout and I have a simple laptop with 2 channels, but in reality it outputs 6 channels. I can see it from what is written in the shell and it's even showed in PulseEffects. Seems weird, but I assume that downmix to 2.0 is done after PulseEffects (right? I hope so). Same is when I set audio-channels=auto. Anyway, listen to the audio, its volume level seems a little lower then normal.

Normal I mean when I set audio-channel=2.0 or stereo. In this case the volume is better for my taste and mpv produces 2.0 audio output. I assume it does downmix and setting stereo would trigger the special case when downmix is not done by mpv, but by decoder (if available, see [here](https://mpv.io/manual/stable/#options-ad-lavc-downmix)).

Outputting 6 channels in auto-safe mode is weird to me, but maybe I'm wrong and it's normal, I'm here to ask and learn. I thought this could be caused by PulseEffects, but disabling mpv from application list will output 6 channels the same in the next reproduction startup. Therefore maybe it's Pulseaudio behavior and downmix is done by Pulseaudio itself (after PulseEffects, if mpv is enabled in applications list).

It's just a curiosity. Let me know. Thank you. ;)

**Comment by wwmm** [comment]
This is a necessary downmix done by Pulseaudio. Take a look at the file `/etc/pulse/daemon.conf`. There is an option `; enable-remixing = yes` there. 

As most of the plugins in PulseEffects only accept 2 channels forcing a stereo pipeline was the easiest way to go. Properly supporting surround configurations will require much more work. This is why our sink `PulseEffects(apps)` only has two channels. When Pulseaudio sees that mpv is trying to output 6 channels it does the downmix to 2. This is happening before PulseEffects effects are applied. When the audio buffer arrives at the effects pipeline it is already stereo.

When you force stereo in mpv it will be the one doing the downmix. I think that by default Pulseaudio does not remixes the `lfe` channels. In its config file we have `; enable-lfe-remixing = no`. So this may be the reason why its remixing is sounding different.

**Comment by Digitalone1** [comment]
Didn't know that, thank you. I already changed enable-lfe-remixing to yes, so all tests were done with lfe remixed. It seems that mpv downmix produces a better audio for effects pipeline in PE. Besides I disabled normalization during downmix in mpv (since I enabled auto gain in PE).

Okay, that's all I wanted to know. If there's nothing else for you to reply, you can close this issue. Keep it up for this great work. 

Best regards.
