### ISSUE TITLE
Feature suggestion: drag and drop for item reordering

### ISSUE THREAD

**Issue by lightonflux** [wwmm/pulseeffects#447]
At the moment the up and down arrows in the sidebar work fine if you want to switch two items. But becomes a bit cumbersome when you want to move some items from the bottom to the top or the other way round.

IMHO drag and drop sorting would improve the UX a lot here.
Some time ago there blog post about this with code examples and a [small example app](https://github.com/GNOME/gtk/blob/master/tests/testlist3.c). 

https://blog.gtk.org/2017/06/01/drag-and-drop-in-lists-revisited/

**Comment by wwmm** [comment]
I thought these things were easier to do XD 

This may require some changes to the reordering process. What is done in a drag and drop workflow is more or less the inverse of what is done now. When we click on the up/down arrows an array of strings saved in a GSettings key is updated. And this update triggers(among others) an invalidate signal that forces the listbox sort function to be called. This sort function then reads the new gsettings key value and updates the widgets ordering accordingly.

**Comment by wwmm** [comment]
Implemented in `4.5.9`. Although it is not as elegant as in the gtk blog example. But it works. Just drag a row over another that it will be placed before the target row.
