### ISSUE TITLE
Compressor not working in latest Arch Linux release

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#449]
Hello everyone. Today I updated my Arch Linux and found a new version of pulseeffects from upstream repository.

Listening audio I found out that there's a new compressor. I reset configuration and set up the new one, but it is not working. I also tried to restart the system, but the new compressor is grayed out. The other module Auto Gain which I'm using is working properly. Tried to delete ~/.cache/gstreamer-1.0 from local folder and restart the system, but it's the same.

Reverted to previous 4.5.0-2 version from pacman cache and it's working normally. Any idea? I got installed all optional packages reported here(https://www.archlinux.org/packages/community/x86_64/pulseeffects/): calf, lsp-plugins, mda.lv2, rubberband, zam-plugins.

A useful question when new compressor will work: knee db value are now negative while I used to get positive. If I got 10 db, should I set -10 in new one?

**Comment by wwmm** [comment]
Strange. I have `4.5.2-1` installed on Arch and it is working. Kill the current instance `pulseeffects -q` and run in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. The log printed in the terminal should give a hint.

It is hard to say if  `-10` will have the same effects as the compressors are different. But it would be my first guess. You can read more info about the compressor in our help or here http://lsp-plug.in/?page=manuals&section=compressor_stereo

**Comment by Digitalone1** [comment]
It's working. Don't know why it was not working before, it was even grayd out. -_-
That's OK, thanks for documentation also if it's not explained how values affect knee option, but I assume 0 would be hard knee and lower values soft knee.
