### ISSUE TITLE
Adjust the AutoVolume response time

### ISSUE THREAD

**Issue by descendingnerdliness** [wwmm/pulseeffects#45]
I have tried before to reliably configure a limiter and compressor in pulseaudio.  But success only lasted the session.  Then all had to be reconfigured.  When I began for a method to use with kubuntu 17.04, I found Pulse Effects.  

Thank you!  Wonderful piece of work!

Now for the question. Is there a settings or config file where the AutoVolume can be adjusted?  In my situation, it takes too long to respond to sudden increases and decreases in volume.

**Comment by wwmm** [comment]
Hi

At this moment the autovolume average time and threshold can not be configured by the user. But I can expose these parameters in the main menu in the next release.

**Comment by wwmm** [comment]
Hi, I added auto volume parameters controls to the latest PulseEffects(2.1.1). They are in the main menu
