### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by flipwise** [wwmm/pulseeffects#454]
Hi,

I noticed some sluggishness with my computer and system monitor showed this:

![image](https://user-images.githubusercontent.com/26850445/53866600-324c2f80-3ff2-11e9-8d2e-0168c3431b53.png)

I had used PE last night and then closed it, after which I suspended the PC and resumed with work the next day (but did not open PE).

CPU time is frozen for the most part but will move a bit here and there, but memory usage keeps growing. At the time of writing this it's already grown about 300 MB compared to when I took the screenshot.

<details>
<summary> Details </summary>

```
1. Manjaro Linux, KDE Plasma 5.15.2

2. PE is installed through the package manager as a community package.
Version: 4.5.4-1

3. Messages printed by PulseEffects when executed from command line in debug mode: 
[PEdebug.txt](https://github.com/wwmm/pulseeffects/files/2935202/PEdebug.txt)

4- PulseEffects settings: [pesettings.txt](https://github.com/wwmm/pulseeffects/files/2935169/pesettings.txt)
```
</details>

**Comment by wwmm** [comment]
Based on what I see in the logs you have these plugins enabled `compressor,equalizer,bass enhancer and crystalizer`. Is that how it was before and after suspending? Could you check if there is such a huge leak when no plugin is enabled? Considering that of the plugins above crystalizer is the only one  I have written myself it is my first guess of the problem location.

As far as gnome memory monitor shows I do not have a leak here.  But I will try to run valgrind and see if there is anything odd in crystalizer. Another possibility is that somehow the suspend is triggering some problem I am not aware of. I never suspend my desktop.

**Comment by wwmm** [comment]
Valgrind did not show anything interesting yet. So I decided to do other tests(without valrgind) in service mode this way:
```
1. kill PE `pulseeffects -q`
2. run PE as `pulseeffects --gapplication-service`
3. Make sure there is no audio app running
4. Open a video in mpv and do lots of seeks on it. This forces PE pipeline to be restarted several times.
```
Looking at the system monitor I can see some fluctuations in the memory usage but so far nothing that could explain this 300 mb usage.

**Comment by flipwise** [comment]
Yeah I think this will be tricky to reproduce. First I have to see if PE stays running even after it's closed (it always closed normally), as it did when the memory leak happened. I have to see if suspend played any role, though I do think I closed PE before it... not 100% sure though. Then if it stays running see if the memory is growing. I will try to reproduce the bug again. 

>Based on what I see in the logs you have these plugins enabled compressor,equalizer,bass enhancer and crystalizer. Is that how it was before and after suspending?

Those 4 yes.

**Comment by flipwise** [comment]
Okay nvm I think I know what's going on! Last night I toggled the crystalizer on and off and the sound stopped playing. I didn't think much of this and just started PE again. However...

Now if I toggle on and off until PE stops working, if I exit the program I'm noticing that PE will stay running in the background. Its memory is slowly growing.

**Comment by flipwise** [comment]
Here's a video of it happening: https://youtu.be/NvZO6O9Eqqg

**Comment by wwmm** [comment]
Turning it on and off very fast causes a crash? Strange. I can't reproduce that here. Try that in debug mode so we can see anything interesting is printed when the crash happens.

When you close PE window it will still run in service mode. But as soon as no audio app is playing PE pipeline should pause

**Comment by wwmm** [comment]
Video is unavailable

**Comment by flipwise** [comment]
[PEcrystalizerLeak-2019-03-06_17.48.41.zip](https://github.com/wwmm/pulseeffects/files/2937384/PEcrystalizerLeak-2019-03-06_17.48.41.zip)

Maybe it's not done processing but I put the file in the .zip so that should work. 

PE doesn't crash, just stops playing sound. Sometimes you need to toggle more times, but sometimes turning it off and on again once or twice is enough. In the video it happened instantly.

**Comment by flipwise** [comment]
OK so when this bug doesn't happen PE exits cleanly, it won't run stay running in the background.

I've just tried debug mode and this is the only thing that shows up:
`(pulseeffects:5203): pulseeffects-DEBUG: 18:16:20.628: sie: crystalizer is disabled
(pulseeffects:5203): pulseeffects-DEBUG: 18:16:21.481: sie: crystalizer is enabled
(pulseeffects:5203): pulseeffects-DEBUG: 18:16:21.526: sie: total latency: 133 ms
`
Nothing else shows up if I toggle on and off again. I can actually get audio to work again if I go to Application and uncheck the stream. However after that is done PE  remains completely frozen. No debug message that could help us:

`(pulseeffects:5203): pulseeffects-DEBUG: 18:17:20.762: pulse_manager: sink input: Spotify, idx = 71 removed from PE
`

**Comment by wwmm** [comment]
I see. The leak is probably cause by a flaw in crystalizer initialization logic. As it is now if the initialization fails the setup method will be called again and again without freeing memory. But I still wonder why it is failure in the first place. I would expect a few warnings in this case.

I did small changes to the plugin code. Try to build from git using the aur package. Let's see if anything changes

**Comment by flipwise** [comment]
I toggled on and off about a 100 times and PE didn't stop working this time around. Also, when I close PE it doesn't stay running in the background. I'd say this fixes it. Thanks :)

**Comment by Telavus** [comment]
Also have this issue, with similar plugins installed. Came back today with no audio on my computer & a 100% memory usage. I will come back later with updated results if I can recreate it. It's happened twice by now

**Comment by wwmm** [comment]
Run in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects` so we can see if there is any obvious error. But I suggest you open a new issue. The source of the one above was fixed  in March. Unless you are using a old PE release your leak is being caused by something else. Have also in mind that what matters are the plugins you enabled. Plugins installed but disabled in PE window will do nothing.
