### ISSUE TITLE
No sound, PulseEffects stucked, need to kill pulseeffects on audio stream source change

### ISSUE THREAD

**Issue by Dodjob** [wwmm/pulseeffects#455]
Hey,
I have an issue with pulseeffects on ubuntu 18.10. It seems that I need to kill pulseaudio process and restart it when changing from audio source. I have honestly no idea how to debug this.
If you would tell me what I should do to get you logs? I  would really appreciate it.
I'm on a really close-to-stock ubuntu 18.10, pulse audio 12.2 and pulseefects 4.4.7
Hope you can halp :)
Regards,
H.

**Comment by wwmm** [comment]
Kill pulseeffects by running `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. This will print the log in the terminal.

**Comment by Dodjob** [comment]
Here you go :)
`$ G_MESSAGES_DEBUG=pulseeffects pulseeffects

(pulseeffects:4932): Gtk-WARNING **: 15:48:09.499: Theme parsing error: gtk.css:3:105: Failed to import: Error opening file /home/doh/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-right.css: No such file or directory
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.535: application: PE version: 4.4.7
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.536: pulse_manager: context is connecting
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.536: pulse_manager: context is authorizing
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: context is setting name
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: context is ready
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: connected to: unix:/run/user/1000/pulse/native
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: protocol version: 32
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: Pulseaudio version: 12.2
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: default pulseaudio source: alsa_output.pci-0000_00_1b.0.iec958-stereo.monitor
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1b.0.iec958-stereo
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: default pulseaudio sink sampling rate: 96000 Hz
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: default pulseaudio sink audio format: s32le
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.537: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.538: pulse_manager: default pulseaudio source sampling rate: 96000 Hz
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.538: pulse_manager: default pulseaudio source audio format: s32le
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.561: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.561: sie: using output device: alsa_output.pci-0000_00_1b.0.iec958-stereo

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.561: limiter plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.561: compressor plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.561: filter plugin was not found!
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.568: sie: equalizer is enabled

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.568: reverb plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.568: bass_enhancer plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.568: exciter plugin was not found!
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.572: sie: crossfeed is already disabled
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.574: sie: maximizer is already disabled

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.574: multiband_compressor plugin was not found!
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.579: sie: loudness is already disabled

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.579: gate plugin was not found!
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.581: sie: pitch is already disabled

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.581: multiband_gate plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.582: deesser plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.582: stereo_tools plugin was not found!
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.585: sie: convolver is enabled
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.587: sie: crystalizer is already disabled
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.589: sie: autogain is already disabled

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.589: delay plugin was not found!
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.604: soe: using output device: PulseEffects_mic
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.604: soe: using input device: alsa_output.pci-0000_00_1b.0.iec958-stereo.monitor

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.604: limiter plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.604: compressor plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.604: filter plugin was not found!
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.611: soe: equalizer is already disabled

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.611: reverb plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.611: gate plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.612: deesser plugin was not found!
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.614: soe: pitch is already disabled
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.618: soe: webrtc is already disabled

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.618: multiband_compressor plugin was not found!

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:09.618: multiband_gate plugin was not found!
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:09.624: presets_manager: user preset directory already exists: /home/doh/.config/PulseEffects
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:10.091: convolver_ui: irs directory already exists: /home/doh/.config/PulseEffects/irs
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:10.551: sie: spectrum enabled
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:10.553: soe: spectrum enabled

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:11.317: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:11.317: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:11.317: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:11.317: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:11.317: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:11.317: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:11.318: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:11.318: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:11.320: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:4932): pulseeffects-WARNING **: 15:48:11.320: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.321: sie: sampling rate: 96000 Hz
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.322: sie: using output device: alsa_output.pci-0000_00_1b.0.iec958-stereo
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.322: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_1b.0.iec958-stereo
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.322: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1b.0.iec958-stereo
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.322: soe: using input device: alsa_output.pci-0000_00_1b.0.iec958-stereo.monitor
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.322: pulse_settings_ui: input device changed: alsa_output.pci-0000_00_1b.0.iec958-stereo.monitor
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.322: pulse_settings_ui: added source: alsa_output.pci-0000_00_1b.0.iec958-stereo.monitor
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.322: pulse_settings_ui: added source: alsa_input.pci-0000_00_1b.0.analog-stereo
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.323: sie: NULL -> READY -> PLAYING
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.324: sie: READY -> PAUSED -> PLAYING
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.324: sie: pulsesrc latency [us]: 10000
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.324: sie: pulsesrc buffer [us]: 200000
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.326: sie: equalizer deinterleave pad added: src_0
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.326: sie: equalizer deinterleave pad added: src_1

(pulseeffects:4932): Pango-CRITICAL **: 15:48:11.326: pango_layout_set_width: assertion 'layout != NULL' failed

(pulseeffects:4932): Pango-CRITICAL **: 15:48:11.326: pango_layout_set_alignment: assertion 'layout != NULL' failed

(pulseeffects:4932): Pango-CRITICAL **: 15:48:11.326: pango_layout_set_text: assertion 'layout != NULL' failed
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.332: peadapter: pulseaudio block size 960 frames
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.332: peadapter: we will read in chunks of 512 frames
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.428: sie: pulsesink latency [us]: 10000
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.428: sie: pulsesink buffer [us]: 200000
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.428: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:11.428: sie: total latency: 120 ms
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:12.435: sie: equalizer deinterleave pad removed: src_0
(pulseeffects:4932): pulseeffects-DEBUG: 15:48:12.436: sie: equalizer deinterleave pad removed: src_1
`

**Comment by wwmm** [comment]
There are a few errors that are not related. The one taking away your sound is probably this `sie: using input device: PulseEffects_apps.monitor`. Are you manually selecting this device? IF not then something in your installation is doing this. Take a look at points `3,4 and 5` of our [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ). If this does not help then there is a third party app installed in your PC managing audio devices and breaking our routing

**Comment by Dodjob** [comment]
Thanks a lot wwmm
I had to use the "FAQ 4" --> pactl unload-module module-switch-on-connect
Seems to work now. 
Do I have to use it every time I start my system? Can I include it in the startup command?

**Comment by wwmm** [comment]
You can include this in the startup command
