### ISSUE TITLE
Crackling audio in high band with new cristalizer

### ISSUE THREAD

**Issue by Kevin-at-Navigram** [wwmm/pulseeffects#461]
Ubuntu 18.10
Pulse Audio 4.5.3 (Flatpak)

When I turn on some high quality music and I play around with the crystalizer, I can hear a bit of crackling where that didn't exist before.

# Hot to reproduce:
- Have a descent test setup. I use a Shure 440 headset, and I listen to Parabola of Tool, in flac format. Preferably have a song that also has some quiet moments.
- Set the cristalizer off
- Listen to a sample
- Set the cristalizer to all 0, turn it on
- Listen to the same sample
- Turn it on and off at your own leisure

I discovered a small crackling sound underneath the music. Best heard in the headphone during the silent moments of the song.

**Comment by wwmm** [comment]
This version has this problem. But it should be fixed in the latest version `4.5.5`. I don't know when the flatpak package will be updated to this version

**Comment by wwmm** [comment]
The flatpak package was updated tp version `4.5.8`. Is this still a problem?

**Comment by Kevin-at-Navigram** [comment]
@wwmm Nope, seems fixed
