### ISSUE TITLE
Display red color in level bars when a plugin is saturated

### ISSUE THREAD

**Issue by AlexWayfer** [wwmm/pulseeffects#467]
Hello!

Crystalizer plugin has warn sign when sound is overloading:

![image](https://user-images.githubusercontent.com/6510020/54772207-f501b780-4c17-11e9-85ce-19939d6d2235.png)

But Bass Enhancer plugin doesn't:

![image](https://user-images.githubusercontent.com/6510020/54772277-15ca0d00-4c18-11e9-863d-354effd86ce8.png)

Also, the bars, which are blue at low level and green at slightly less than 0 level, can be red for greater than 0 level.

Thanks.

**Comment by wwmm** [comment]
This is because you did not saturated the bass enhancer. You are saturating the stage that comes after it.

**Comment by wwmm** [comment]
This sign warns when the plugin input is saturated. Enable a plugin after the bass enhancer and the warning will be shown for this plugin

**Comment by wwmm** [comment]
I don't know if I can change the bars color or add more reference level. I have to take a look at GTK levelbar docs

**Comment by wwmm** [comment]
IT will require some work but I think that I can play a little with the level bar offsets and color https://developer.gnome.org/gtk3/stable/GtkLevelBar.html#GTK-LEVEL-BAR-OFFSET-FULL:CAPS

But I wonder if this will have conflicts with the user color theme. As it is now the color theme decides the colors

**Comment by AlexWayfer** [comment]
> Edit: You already did that. In order to see the bass enhancer warning enable a plugin before it and do lots of amplification in this plugin

OK, I got it, thanks.

> But I wonder if this will have conflicts with the user color theme.

I think, colors like green, yellow and red are common for people understanding.

> As it is now the color theme decides the colors

If it has only two options (blue and green currently in my case) — I don't think that this is good kit. Only maybe green can be for negative values, and blue, like something "not so good", for positive values.

But these colors are depending on Gtk theme, so it's not stable.

**Comment by wwmm** [comment]
As time passed I realized that what really matters is the saturation at the last stage. The one sending audio to Pulseaudio. PE `4.8.0` has a global level meter showing this. So red colors for each plugin are not necessary anymore.
