### ISSUE TITLE
lsp-plugins lv2 only?

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#469]
As newest PE needs lsp-plugins, I had to package them (https://github.com/mikhailnov/lsp-plugins), and splitted ladspa, lv2, vst, jack plugins into different packages.
Glancing over PE's source code, I did not understand which of them (ladspa, lv2, vst) are required for PulseEffects?

**Comment by mikhailnov** [comment]
Bases on https://github.com/flathub/com.github.wwmm.pulseeffects/commit/d23273f51b93e4be1d1e4599b174d2e2cb8df240 , I think lv2 is needed.

**Comment by sadko4u** [comment]
Only LV2 is required for pulseeffects. This was discussed at the end of this topic:
https://github.com/sadko4u/lsp-plugins/issues/35

**Comment by wwmm** [comment]
Yes. Only LV2. I use the LV2 versions of the plugins unless GStreamer is not capable of use them. This happens with ZamAudio plugins. For some reason GStreamer can not use its LV2 libraries.

**Comment by wwmm** [comment]
You case you want to see in the sources https://github.com/wwmm/pulseeffects/blob/18d19973a6204cceaa68024067d362d27c8f95a9/src/equalizer.cpp#L21
