### ISSUE TITLE
Improve documentation (and thanks for maximizer)

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#470]
Hello everyone. As I explained in a previous post, I use Autogain and Compressor to get audio at (quite) same volume level across different sources.

But I discovered Maximizer and found out it is an outstanding plugin since it can replace both Autogain and Compressor. My issue is that I didn't understand how it works, and in reality I don't fully understand even now how it works. But it works very good.

Reading documentation at pulseeffects/help/C/maximizer.page: 
> A maximizer is similar to a limiter. It attenuates peaks above the limit(ceiling in our case) but it also boosts peaks that are between the limit and the threshold.

It could have a sense, but reading threshold option:
> If a signal rises above this level it will affect the gain reduction.

That is not correct. Wrote that way It seems that this plugin attenuates signals above the threshold level but it's not what really happen.

Plus, reading on official ZamAudio website:
> ZaMaximX2 - One of the best plugins in the series, this acts as a brickwall limiter for mastering in its default state, but can also be tweaked to raise the average level as a stereo maximizer without ever clipping. Sounds musical even with rough treatment. 

That seemed very contradictory to me. I wrongly thought that It first attenuates signals above the threshold and then It boosts resulting signal to reach the ceiling.

But in reality it works attenuating signals above the ceiling and boosting lower signals (that are below the ceiling) to match the ceiling, so it won't attenuate nothing above the threshold. Besides it seems that the threshold is a relative value based on the ceiling rather than an absolute value relative to db level of the signal. In fact, lower the threshold higher the boosting of signals below the ceiling.

Thus I think that documentation needs a clearer explanation of how this plugin works and what their options do. Founding out what it does (if I'm not wrong), this plugin is very outstanding because it can replace both autogain and downward compression since it attenuates signals above a certain ceiling level and boosts signals below it, but only above threshold level that is relative to the ceiling. And If I think more about it, it works also as an upward compressor, but having a gate that won't boost below a certain level (so it won't boost noise - upward compressor boosts also noise and it's quite annoying). It's amazing! All of that in one plugin. Thanks to you and ZamAudio.

So in the end it could be useful to improve documentation and maybe adding explanation of options inside the GUI because not everyone knows where to read it. I tried to click question mark icon in PulseEffects, I though it could show a little of documentation, but it won't do nothing and I had to come here on GitHub to read something (Maybe it's an issue on mine? Missing a specific package to show documentation inside the GUI? I don't know).

Thank you.

**Comment by wwmm** [comment]
You probably do not have Yelp installed. It is needed to view the builtin help
![Screenshot from 2019-03-24 11-40-07](https://user-images.githubusercontent.com/16225172/54880955-9e6bc780-4e29-11e9-95c3-686277c18244.png)

The description of the threshold is not good indeed. When wrote this I was in a hurry. And writing docs is tiring and boring :-) I may have taken description from another maximizer. I did some tests here with the test signal generator builtin in PulseEffects and this plugin seems to behave a little different than what I thought. Although I disagree that it could replace the autogain. Our auto gain changes level based on preceived loudness accordingly with ebur128 standards. The maximizer is definitely not doing that. But the ceiling parameter works a little different than the usual limit in a limiter. When it is at 0 dB no signal will reach higher than this. When I give it a sine wave with -10 dB and I put the ceiling at -5 dB the signal output decreases to -15 dB. Now if I decrease the threshold the signal is amplified by the magnitude of the threshold value but is kept below the -5 dB set by the ceiling. So the ceiling is a hard brick wall limit like Zam says in its page. But different from what a limiter usually does it attenuates signals that are below the ceiling value when the ceiling is below 0 dB. I did not notice that before as I always use the ceiling at 0 dB.

**Comment by wwmm** [comment]
Just to avoid any misunderstanding I did no code the maximizer. All the credits go to ZamAudio

**Comment by Digitalone1** [comment]
> You probably do not have Yelp installed. It is needed to view the builtin help
> ![Screenshot from 2019-03-24 11-40-07](https://user-images.githubusercontent.com/16225172/54880955-9e6bc780-4e29-11e9-95c3-686277c18244.png)

Yes, you are right, but shouldn't it be in PulseEffects dependencies on Arch Linux (at least optional package)?
Maybe a GNOME user has it installed by default, but I use Plasma and never had it.

I will reply later for maximizer behavior. Thanks.

**Comment by wwmm** [comment]
Maybe. But I am not the package maintainer.

**Comment by Digitalone1** [comment]
> I did some tests here with the test signal generator builtin in PulseEffects and this plugin seems to behave a little different than what I thought. Although I disagree that it could replace the autogain. Our auto gain changes level based on perceived loudness following ebur128 standards. The maximizer is definitely not doing that. But the ceiling parameter works a little different than the usual limit in a limiter. When it is at 0 dB no signal will reach higher than this. So far no difference. But when I give it a sine wave with -10 dB and I put the ceiling at -5 dB the signal output decreases to -15 dB. Now if I decrease the threshold the signal is amplified by the magnitude of the threshold value but is kept below the -5 dB set by the ceiling. So the ceiling is a hard brick wall limit like Zam says in its page. But different from what a limiter usually does it attenuates signals that are below the ceiling value when the ceiling is below 0 dB. I did not notice that before as I always use the ceiling at 0 dB.

I think that the threshold is a relative value based on the ceiling.
Considering a ceiling db value minor than 0:
- When the threshold is higher than the ceiling, the overall signal gets compressed, so the magnitude decreases and the volume is lower.
- When the threshold is lower than the ceiling, the signal gets maximized, but it won't go higher than the specified ceiling db value. Besides the overall signal gets a dynamic range compression, but not in a way a simple downward compressor does: this plugin boosts signals lower than the ceiling to match the ceiling level; the result is a sound with more volume, the dynamic range is decreased because the lower parts get boosted.

If you listen a song and play with the threshold level pushing it down you will notice that parts of the song with lower volume get louder, but always not passing over ceiling db value. So it acts as a volume leveler and a dynamic range compressor, even if autogain and compressor have a different behavior.  

Plus, if you have a track with a little noise and play with the compressor in the upward mode, you will notice that boosting signals below a specified threshold will also boost noise, so you will hear more noise. Maximizer instead can boost signals below the ceiling without boosting noise, it's amazing! 

Do you agree on that? I hope I'm not wrong. Anyway I can help to write better sentences for maximizer documentation.

Obviously, pushing threshold too down results in distorted unacceptable sound, but some levels little below the ceiling are a very good compromise and result in acceptable sound. I replaced autogain and compressor with maximizer and listening through my earphone is much better than before. 

> Maybe. But I am not the package maintainer.

Okay, I'll try to write to the package maintainer.

**Comment by wwmm** [comment]
I mostly agree with you. I am not sure it amplifies the signal to match the ceiling values(I am not a native English speaker so I may be misunderstanding what you mean by match). It seems to amplify by the magnitude of the threshold value and then makes sure no peak is above the ceiling. In the example I gave above the signal reaches the ceiling level of -5 dB only when the threshold is sufficiently high. If we choose smaller values like -1 dB or -2 dB the signal is amplified but remains far from the ceiling.

I agree it feels similar to an upward compressor and that the threshold is probably relative to the ceiling. But it is not clear it does not amplifies noise. Playing with the test signal it seems to amplify the whole signal. In the example above of a sine wave with -10 dB peak and ceiling of -5 dB a threshold of -1 dB seemed to amplify the whole signal by 1 dB. Maybe it has some kind of internal minimal value threshold that somehow avoids noise amplification. But it is not obvious there is such a functionality.

This is one the things that makes it hard to write documentation of third party plugins(most of the ones in PulseEffects). Not all of them have clear docs for us to rely on. This is one of the reasons I have been migrating to Linux Studio Plugins where possible. The documentation is way better than the ones from all the others https://lsp-plug.in/?page=manuals. In the case of the few plugins I wrote myself like the crystalizer I have a pretty good idea of what everything is doing. But in more complex third party plugins with little or no docs it is sometimes hard to understand 100 % of what the plugin is doing. 

Feel free to do pull requests with improved docs or to open issues like these ones with the new files attached in case you do not feel comfortable with pull requests. I would really appreciate some help with this. This way I could keep my focus on the code.

**Comment by Digitalone1** [comment]
> I mostly agree with you. I am not sure it amplifies the signal to match the ceiling values(I am not a native English speaker so I may be misunderstanding what you mean by match). It seems to amplify by the magnitude of the threshold value and then makes sure no peak is above the ceiling. In the example I gave above the signal reaches the ceiling level of -5 dB only when the threshold is sufficiently high. If we choose smaller values like -1 dB or -2 dB the signal is amplified but remains far from the ceiling.

By match I mean to "pair", I think it's "combinar" or "unir" in Portuguese, but maybe it's not the right term. Let's put this way:
When the threshold is lower then the ceiling, the plugin manages two parts of the signal. 
- The part higher than the ceiling: it's limited so it won't go above the ceiling.
- The part lower than the ceiling: it's amplified. The amplification depends by the threshold value. Lower the value from the ceiling, higher the amplification. Anyway, it never goes above the ceiling.

It's like it does downward compression on the first part and upward compression on the second. Lower the threshold from the ceiling, higher the ratio of upward compression, but the resulting output signal never goes above the ceiling.

I'm not native English either, I'm Italian. :)

> I agree it feels similar to an upward compressor and that the threshold is probably relative to the ceiling. But it is not clear it does not amplifies noise. Playing with the test signal it seems to amplify the whole signal. In the example above of a sine wave with -10 dB peak and ceiling of -5 dB a threshold of -1 dB seemed to amplify the whole signal by 1 dB. Maybe it has some kind of internal minimal value threshold that somehow avoids noise amplification. But it is not obvious there is such a functionality.

I am sure. Try to listen the final part of the following song (from 4:00 to 4:07): https://www.youtube.com/watch?v=owTWCbq_nSk
With upward compression I can hear noise. With maximizer set at -1 db ceiling and -30 db threshold (maximum ratio upward compression), I don't hear noise.

> This is one the things that makes it hard to write documentation of third party plugins(most of the ones in PulseEffects). Not all of them have clear docs for us to rely on. This is one of the reasons I have been migrating to Linux Studio Plugins where possible. The documentation is way better than the ones from all the others https://lsp-plug.in/?page=manuals. In the case of the few plugins I wrote myself like the crystalizer I have a pretty good idea of what everything is doing. But in more complex third party plugins with little or no docs it is sometimes hard to understand 100 % of what the plugin is doing.

I got it. In fact it's hard to understand also what "release option" means in this case. Maybe I'll play with it trying to figure out something. Other things I didn't understand are values in the autogain plugin (except target). They are not even in db, don't know what they mean and how they relate to each other. Don't even know why they go from 1 to 100. Maybe they represents percentage?

Anyway, it seems that no other developers made something similar to ZamAudio's Maximizer. 

> Feel free to do pull requests with improved docs or to open issues like these ones with the new files attached in case you do not feel comfortable with pull requests. I would really appreciate some help with this. This way I could keep my focus on the code.

Maybe I'll try to write something.

**Comment by wwmm** [comment]
Ok. I think we are talking the same thing :-) Maybe it does have a minimum level threshold for this amplification.

The autogain target is in decibel but in the LUFS or LU scale if I am not mistaken. The other values are weights. The momentary value is calculated in a time scale around 400 milliseconds. The short term window is somewhere close to 3 seconds and the integrated term uses the whole past info to estimate the loudness. If you want the autogain to react fast increase the weight of the momentary and the short term. If you want it to react slowly to changes in loudness increase the weight of the integrated term.

**Comment by Digitalone1** [comment]
I think that this explanation could be good.

> Maximizer is a versatile plugin that can be tweaked to be a compressor, an amplifier and a limiter. It is basically controlled by only two parameters: ceiling and threshold. Threshold is a relative value representing the amplification of the signal while ceiling is the maximum allowed output peak level. Setting both values different from zero, the plugin will act as an upward compressor with a limiter on the ceiling level (overly amplified signal with ceiling set too low can result in distorted sound even without the presence of clipping). When only threshold is set equal to zero, it reduces the amplitude of the signal. Both values equal to zero mean bypass.

Ceiling
> Maximum allowed peak level of the output signal

Threshold
> Relative value representing the amplification of the signal. Zero is no amplification. Lower values, higher amplification.

Now remains to understand what release really do.

**Comment by wwmm** [comment]
In a typical limiter release would be the time for the attenuation to go back to zero.

I would change `Both values equal to zero mean bypass` to `Both values equal to zero mean that it will act like a limit. If the signal is above 0 dB it will be attenuated so that it remains below 0 dB. If the signal is already below 0 dB nothing is done`. If we only say it is bypassed people could think that a signal above 0 dB would leave the maximizer without being touched. What is not the case. 

In case you want to do a pull request this is the file https://github.com/wwmm/pulseeffects/blob/master/help/C/maximizer.page

**Comment by wwmm** [comment]
When making changes to the docs it is important to run `ninja install` and check if any warning or error is produced when meson is generating the translation for each language. Sometimes I forget to do that... Recently I had to do a bugfix release because what was just a warning in my PC caused a build error for other people.

**Comment by Digitalone1** [comment]
> When making changes to the docs it is important to run `ninja install` and check if any warning or error is produced when meson is generating the translation for each language. Sometimes I forget to do that... Recently I had to do a bugfix release because what was just a warning in my PC caused a build error for other people.

I did the pull request. Never did the `ninja install` thing. It seems that I need a ninja.build file, but I don't see any. 

`ninja: error: loading 'build.ninja': No such file or directory`

Should I compile the overall package to see if meson generates errors/warnings? Sorry for the dumb question, but I never did that before.

**Comment by wwmm** [comment]
Sorry. I assumed you had done this kind of thing before. Inside PulseEffects source folder(where the README is located) run `meson _build --prefix=/tmp/pulseeffects`. Then inside the `_build` folder run `ninja install`

**Comment by wwmm** [comment]
I did the test on my PC. No warnings.
