### ISSUE TITLE
Audio stuttering when using Auto Gain effect

### ISSUE THREAD

**Issue by sispus** [wwmm/pulseeffects#472]
Hi,
My sound stutters when I start a program, especially chromium, while Auto Gain is activated. Disabling Auto Gain corrects the sound. 
I tried Equaliser, Exciter, Bass Enhancer (alone and combining two-three). They were working well.
It is PulseEffects 4.5.6 from official repo in Manjaro XFCE, kernel 5.0.3

**Comment by wwmm** [comment]
I always use the autogain and it doesn't happen to me. As we use most of the features libebur128 offers this plugin may be a little heavy on cpu. What is the CPU usage when this happens?

**Comment by sispus** [comment]
cpu ratio of pulseeffecs without auto gain is 7 to 10%, while total 30. auto gain adds about 15% on it.
cpu peaks to 100% for a while whenever I start chromium, etc. (with or without auto gain). 
my laptop is old one, a compaq cq56.

**Comment by wwmm** [comment]
May it this peak in use when starting chromium together with autogain cpu usage is doing the stuttering. It is the only thing that comes to my mind considering I do not have this problem in my ryzen 2700. Try to increase PulseEffects priority to realtime. Maybe it helps
![Screenshot from 2019-03-26 11-07-04](https://user-images.githubusercontent.com/16225172/55003832-def94b80-4fb7-11e9-8964-b4e69be7c412.png)

**Comment by sispus** [comment]
thank you wwmm, it definitely made a difference. cpu is about 15% max now and sound works opening a chromium window.
think I must close this thread?
