### ISSUE TITLE
Wrong range/unit for maximizer "release" parameter

### ISSUE THREAD

**Issue by ferreum** [wwmm/pulseeffects#473]
The "Release" parameter of the maximizer makes almost no noticeable difference. It is labelled and documented to specify seconds, and its range is 1.0 to 100.0, but the actual release is almost instantaneous regardless of its value.

The parameter of the zam-plugins maximizer seems to be in milliseconds, so I suspect PulseEffect's parameter is interpreted in milliseconds too. The only effect I noticed so far is that at very low values it can cause distortion-like noise at low frequencies, which is another hint that we are working with milliseconds.

I think this control should specify a float value in milliseconds with a larger range (release of gate appears to be 0.01 to 2000.0). It works fine at a value of 10.0. I think the displayed minimum value of 1.0 "second" would be too large to be useful if it were correct.

**Comment by wwmm** [comment]
It can not be done. This is how the release is read by GStreamer:

```
release : Release
                        flags: readable, writable, controllable
                        Float. Range:               1 -             100 Default:        3,162278
```
This range is the one the plugin is telling. Maybe it is in milliseconds. But as the plugin interface http://www.zamaudio.com/?p=976 does not show units it is hard to tell. In any case we are already using the numerical range the plugin expects.

**Comment by wwmm** [comment]
In other words the most we can do is chaging the units in PulseEffects interface

**Comment by ferreum** [comment]
I see, too bad. It's fine for me though as I wasn't looking to increase the release time—I was just confused about the unit, so the label should probably be changed. Thank you.

**Comment by wwmm** [comment]
I am also confused about the units. I did not see anywhere a documentation about it. But thinking about it milliseconds seems to be a better choice. I will change to this.
