### ISSUE TITLE
Pulseeffects crashes when a bluetooth device disconnects

### ISSUE THREAD

**Issue by seedship** [wwmm/pulseeffects#476]
I am on XUbuntu 18.04. I have a bluetooth speaker that turns off periodically if no sound is played.

When I have this bluetooth speaker connected to my computer, every time it auto turns off and I have the pulseeffects window open, pulseeffects crashes. I need to kill it from the terminal via killall pulseeffects and then start it again. I'm not sure if this happens when I don't have the pulseeffects window open, but I imagine it does.

**Comment by wwmm** [comment]
I need more info. Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Make the device disconnect and paste here what is printed in the terminal

**Comment by wwmm** [comment]
Try to test in service mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects --gapplication-service` too. This could be a bug in the interface.

**Comment by seedship** [comment]
Ah sorry, I updated the software on my system and I can't reproduce the crash anymore.

Sorry I opened this bug before updating PulseEffects.
