### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by aggalex** [wwmm/pulseeffects#477]
With a segfault. Shows the notification about resetting configuration (??? pulseaudio -r didn't work too) and then dies.
`PULSEEFFECTS_DEBUG=1` makes no difference.

dmesg:
`[ 1968.898091] pulseeffects[6325]: segfault at 70 ip 000055b8ba91aaf7 sp 00007ffdea2adf00 error 4 in pulseeffects[55b8ba829000+348000]`
`[ 2030.151598] pulseeffects[6644]: segfault at 70 ip 00005630c7fc6af7 sp 00007ffdb23209c0 error 4 in pulseeffects[5630c7ed5000+348000]`
`[ 2062.110618] pulseeffects[6847]: segfault at 70 ip 000055952c53baf7 sp 00007ffd6055a4e0 error 4 in pulseeffects[55952c44a000+348000]`
`[ 2064.353928] pulseeffects[6867]: segfault at 70 ip 0000557db79c9af7 sp 00007ffc21fd1c40 error 4 in pulseeffects[557db78d8000+348000]`
`[ 2122.877929] pulseeffects[11234]: segfault at 70 ip 000055e73061baf7 sp 00007fffbf088ab0 error 4 in pulseeffects[55e73052a000+348000]`
`[ 2131.328772] pulseeffects[11262]: segfault at 70 ip 0000556b9269faf7 sp 00007ffdd561df20 error 4 in pulseeffects[556b925ae000+348000]`
`[ 2132.508827] pulseeffects[11282]: segfault at 70 ip 0000559e0b376af7 sp 00007ffd36a042b0 error 4 in pulseeffects[559e0b285000+348000]`
`[ 2202.808682] pulseeffects[11481]: segfault at 70 ip 000055d2ce0d4af7 sp 00007ffde6596b80 error 4 in pulseeffects[55d2cdfe3000+348000]`
`[ 2207.839821] pulseeffects[11502]: segfault at 70 ip 00005627f3dbbaf7 sp 00007ffdca07b890 error 4 in pulseeffects[5627f3cca000+348000]`
`[ 2209.532159] pulseeffects[11534]: segfault at 70 ip 000055d336dd8af7 sp 00007ffc1155f5b0 error 4 in pulseeffects[55d336ce7000+348000]`
`[ 2210.443550] pulseeffects[11554]: segfault at 70 ip 0000558695e55af7 sp 00007ffec5075830 error 4 in pulseeffects[558695d64000+348000]`
`[ 2211.549051] pulseeffects[11574]: segfault at 70 ip 00005556da908af7 sp 00007ffd591bfa40 error 4 in pulseeffects[5556da817000+348000]`
`[ 2252.448892] pulseeffects[11691]: segfault at 70 ip 000056197c2faaf7 sp 00007fff70b4d780 error 4 in pulseeffects[56197c209000+348000]`
`[ 2485.821355] pulseeffects[12048]: segfault at 70 ip 0000557e754c8af7 sp 00007ffce0f3f9a0 error 4 in pulseeffects[557e753d7000+348000]`
`[ 2490.014989] pulseeffects[12068]: segfault at 70 ip 0000557c821d1af7 sp 00007ffcbd350b10 error 4 in pulseeffects[557c820e0000+348000]`

**Comment by wwmm** [comment]
From version `4.x` onwards debug mode is enabled this way `G_MESSAGES_DEBUG=pulseeffects pulseeffects`.

**Comment by wwmm** [comment]
Inactive
