### ISSUE TITLE
Italian translation and improve documentation

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#478]
Hello, yesterday I tried to run PE on a different user and first it didn't work (it won't output nothing), but I resolved resetting configuration, then I noticed that it were showing in Italian rather than English. On my default user (that I use quite always) PE is in English.

I don't know why it shows in Italian on the other user, I don't even see a language option in PE, but I prefer English even if I'm Italian.

Anyway, I noticed also that Italian translation is very bad in some parts. Maybe I can improve it when I have time, just tell me how I can do it and which files I have to change. Thanks.

**Comment by wwmm** [comment]
We just follow the user locale. There is no language switch in PE. What the command `locale` prints in this other user account? Here I have this
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
and PE is in English.

There is a translation guide here https://github.com/wwmm/pulseeffects/wiki/Translating-PulseEffects and this is the italian file https://github.com/wwmm/pulseeffects/blob/master/po/it_IT.po. In case you feel it is better to create another it_* variant feel free to add another file. Just remember to edit https://github.com/wwmm/pulseeffects/blob/master/po/LINGUAS accordingly.

Unfortunatly the help translations have to be done separately. They are here https://github.com/wwmm/pulseeffects/tree/master/help. In both cases you can use [Poedit](https://poedit.net/) to edit *.po files

**Comment by Digitalone1** [comment]
`locale` prints:

```
LANG=it_IT.UTF-8
LC_CTYPE="it_IT.UTF-8"
LC_NUMERIC="it_IT.UTF-8"
LC_TIME="it_IT.UTF-8"
LC_COLLATE="it_IT.UTF-8"
LC_MONETARY="it_IT.UTF-8"
LC_MESSAGES="it_IT.UTF-8"
LC_PAPER="it_IT.UTF-8"
LC_NAME="it_IT.UTF-8"
LC_ADDRESS="it_IT.UTF-8"
LC_TELEPHONE="it_IT.UTF-8"
LC_MEASUREMENT="it_IT.UTF-8"
LC_IDENTIFICATION="it_IT.UTF-8"
LC_ALL=
```

and fortunately for me, it's in English, but should it be in Italian?

**Comment by Digitalone1** [comment]
A screen

![Screenshot_20190401_170114](https://user-images.githubusercontent.com/25790525/55337927-df09b780-549f-11e9-8958-3d812dac830a.png)

**Comment by wwmm** [comment]
Strange. It should be in Italian. Usually I test `pt_BR` translation by changing the `LANG` variable to Portuguese. I have no idea why this is not happening in your computer...

**Comment by Digitalone1** [comment]
But it happens on the other user. It's not happening in my primary one.

I use PE from November, whereas I started it for the first time yesterday on the other user, maybe this difference is relevant? Was Italian translation added back in November?

**Comment by wwmm** [comment]
I think it was before November. I do not remember.

In any case most of the recent work on the Italian translation was made by @M0Rf30. So I think it would be good you too talked about what needs to be changed to avoid duplicated work. I now nothing about Italian.

**Comment by M0Rf30** [comment]
Hi @Digitalone1 I'm the italian translator. Why my translation is so bad? One of the things that I don't appreciate it's a disruptive attitude and criticism. So please be more detailed. No one paid me for this work, but I take care of quality. So don't throw shit on someone's work. Be detailed on your reports.

**Comment by Digitalone1** [comment]
> Hi @Digitalone1 I'm the italian translator. Why my translation is so bad? One of the things that I don't appreciate it's a disruptive attitude and criticism. So please be more detailed. No one paid me for this work, but I take care of quality. So don't throw shit on someone's work. Be detailed on your reports.

Hello, I didn't want to hurt anybody, it was just my opinion. 
I'll be detailed, but now I can't switch user because I'm working with my laptop and with my primary user PE shows in English.

I'll let you know.

**Comment by Digitalone1** [comment]
Managed to get Italian translation in PulseEffects on every user.
Please @wwmm add this to F.A.Q.:

> Q: PulseEffects is available in my language, but I see it in English. Where do I can switch language?
A: You are probably using PulseEffects under Plasma 5 desktop environment. Sometimes Plasma makes a little mess with locale settings. Just delete `.config/plasma-locale-settings.sh` and restart the session.

**Comment by wwmm** [comment]
Added!

**Comment by Digitalone1** [comment]
Regarding the translation.

**Compressor**
Makeup is _Guadagno_, not Artefatti.
Knee means Ginocchio, yes, but in this context it does not have sense. Maybe _Curvatura_ is better as stated [here](https://it.wikipedia.org/wiki/Compressione_del_livello_audio#Curva_di_compressione).
Sidechan can stay in English, it's used as is [here](https://it.wikipedia.org/wiki/Compressione_del_livello_audio#Side-chain).
Sidechain types also can stay in English.
Look-ahed translation is wrong, it's difficult to find an italian sinonimous, but can stay in English as Adobe does in it's Italian version (see [here](https://helpx.adobe.com/it/audition/using/match-loudness.html), tempo di _look-ahead)._ 

**Deesser**
Title can stay in English, see [here](http://www.homerecording.it/articoli/tecnica/1333-de-esser-cosa-e-come-funziona-quando-usarlo.html).
Laxity should be _Trascuranza_ or better in _Valore di trascuranza_
Makeup is _Guadagno_.
Split mode better in _Modalità Split_ and Split in _Frequenza split_.

**Maximizer**
Same as above, it can stay in its original name since it's not only a maximizer as stated in the documentation.
Besides, Ceiling is better in _Limite_.

**Autogain**
I think _Normalizzatore_ is a better title.
Weights is not Pesi, but _Ampiezze_.
Target should be _Livello_.
Momentary is better in _Momentaneo_, see [here](https://steinberg.help/wavelab_pro/v9.5/it/wavelab/topics/wavelab_concepts/ebu_loudness_recommendation_r128__c.html) (Intensità acustica momentanea).
Loudness should be _Loudness_ since it's a standard measure, it's cited this way in a document of Italian Authority for Communications Guarantees (see [page 27](https://www.agcom.it/documents/10179/1/document/6d682dbd-0e3a-4f1a-9ee5-ee7cb5640dce)) and it's also in the Italian vocabulary ([here](http://www.treccani.it/vocabolario/loudness)). 

**Exciter**
Same as above for the title, can stay in English.
Scope is better in _Soglia_ and Ceiling in _Limite_.

**Bass Enhancer**
Scope is better in _Soglia_ and Floor in _Limite inferiore_.
 
I think there are also others if I look in other plugin. As I said before, it's only my opinion, I did not want to offend or hurt anybody.

**Comment by Digitalone1** [comment]
@M0Rf30 On top of `it_IT.po` file you modified, I've added other improvements. File attached, just rename it removing .txt extension. 

[it_IT.po.txt](https://github.com/wwmm/pulseeffects/files/3037812/it_IT.po.txt)

**Comment by Digitalone1** [comment]
Maybe in the next days I will add some improvements to Italian documentation.

**Comment by Digitalone1** [comment]
I'm fixing the Italian documentation, but I have doubts on some statements:

**Attack**
> Amount of milliseconds the signal has to rise above the threshold before gain reduction starts.

**Release**
> Amount of milliseconds the signal has to fall below the threshold before the reduction is decreased again.

I think they're not fully correct.

> Attack determines how many milliseconds (ms) it takes your compressor to apply a full dose of compression to your audio signal once it passes the threshold. If the signal peaks above the threshold and quickly returns to below the threshold, it may never receive a full dose of compression.

> Release determines how many milliseconds (ms) it takes your compressor to stop attenuating gain once your audio signal drops below the threshold. A fast release will cause your compressor to stop attenuating gain quickly once the signal returns below the threshold. A slow release will cause your compressor to stop attenuating gain slowly once the signal returns below the threshold.

[Source](https://www.blackghostaudio.com/blog/the-ultimate-guide-to-compression)

Should I change English documentation also?

**Comment by wwmm** [comment]
This description was taken from Calf docs https://calf-studio-gear.org/doc/Compressor.html. Eventually I moved to the compressor from Linux Studio Plugins https://lsp-plug.in/?page=manuals&section=compressor_stereo but there isn't a full description there too. I see no problems in using the description in your link. This is probably what is happening. Although it seems that different implementations may differ on the full meaning of attack and release as is commented in this wikipedia link https://en.wikipedia.org/wiki/Dynamic_range_compression#Attack_and_release

**Comment by wwmm** [comment]
Remember to add your link as reference at end of the page together with the others

**Comment by Digitalone1** [comment]
I compiled my forked package to see if Italian translations are showing correctly and everything works in the GUI.

But unfortunately the documentation is not updated because yelp still rely on files under `usr/share/help`. Anyway, I need also some help to understand how po files works. For example

```
#. (itstool) path: page/title
#: C/maximizer.page:9
msgid "Maximizer"
msgstr "Maximizer"
```

What does that **9** mean? The row inside `C/maximizer.page`?
If so, am I forced to produce original row numbers?

I need to understand this because Maximizer Threshold sentence is based on Compressor one, but after the update it's different and I'm looking how to replace the new one.

**Comment by wwmm** [comment]
It is probably just the line number. Don't worry about it.

I forgot to tell you that after changing the English text you have to regenerate the help translation template and updating each language file. Fortunately there is an automated way to do this:
```
cd build_folder
ninja help-pulseeffects-pot
ninja help-pulseeffects-update-po
```
Just run these commands and meson will update the template as well as all the language files. After this you can open the Italian file and do the translation.

**Comment by wwmm** [comment]
In case you do not feel comfortable doing things that write to all language files tell me the new text that I will update the template

**Comment by wwmm** [comment]
I decided to add a developer's guide to the wiki https://github.com/wwmm/pulseeffects/wiki/Developer's-guide

**Comment by Digitalone1** [comment]
OK @wwmm , I pushed the commit on my fork, but now portuguese help (and other langueges) needs uptades for some maximizer and stereo compressor entries. Will you add them?

If you don't want, I can just copy the previous one reading from diff.

**Comment by Digitalone1** [comment]
Made the pull request.
