### ISSUE TITLE
Add black border to window

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#480]
I'm not really against CSD, but can PulseEffects have a black border around its window?

Chromium has a black border with round corners and it looks better even if it's not fully integrated in Plasma.

![Screenshot_20190406_182055](https://user-images.githubusercontent.com/25790525/55672283-b0258400-5899-11e9-9d31-6398c1ad1462.png)

PE does not have borders, neither round corners.
![Screenshot_20190406_181812](https://user-images.githubusercontent.com/25790525/55672313-ee22a800-5899-11e9-82b0-0b43c7306e68.png)

Could at least black border be added? Maybe optional if it's not appreciated by some users. Could be white for dark theme.

**Comment by wwmm** [comment]
Definitely has to be optional. No other GTK app I have installed has this black border. Only Chrome.

In any case I don't see how this could be implemented. The only thing that comes to my mind would be to put `GtkApplicationWindow` inside a `GtkFrame`. But this does not seem possible. Maybe this could be done by a very clever CSS propery override. But I have no idea how.

**Comment by wwmm** [comment]
How other GTK apps look in KDE? If they are like PE the real solution would be to improve KDE integration of GTK apps

**Comment by Digitalone1** [comment]
Other GTK apps I use like Thunderbird and Firefox do not support CSD, so they are drawn with title bar, borders and shadows.

I don't really need title bar, neither shadows in PE, it's just that Chromium border seems better to me.

I though it would be easier to add a border since it is a decoration by client side, but maybe Chromium uses some hacks that are difficult to implement.

Never mind.

**Comment by wwmm** [comment]
Ok. It is not easy because GTK is the one actually doing the client side decoration under the hoods. I just added a headerbar https://developer.gnome.org/gtk3/3.10/GtkHeaderBar.html to the main window and marked a checkbox telling GTK to use client side decorations.

**Comment by Digitalone1** [comment]
Don't worry, you can close the bug.

**Comment by Digitalone1** [comment]
@wwmm Managed to add a border to PE and other GTK apps in Plasma.

Create `~/.config/gtk-3.0/gtk.css` and add the following line:

`decoration {border: 1px solid black;}`

I'll add it to FAQ.

**Comment by wwmm** [comment]
Ok. Good to know there is a way that works for all gtk apps.
