### ISSUE TITLE
cannot activate some modules since update to 19.04

### ISSUE THREAD

**Issue by Dodjob** [wwmm/pulseeffects#489]
Hey there,
just updated to 19.04. Pulseefects seems to have been completely reseted. For example I can't activate the "EQ". it's greyed and I tried about 1000000 time to clik on it without getting it blue (activated)
Did I miss something?
Pulseefects 4.5.9
Regards,
Hadrien
![Screenshot from 2019-04-19 13-22-01](https://user-images.githubusercontent.com/42808575/56422107-2799e100-62a6-11e9-845d-6fc9283b9e3d.png)

**Comment by Dodjob** [comment]
Ok, I solved it by reseting again the plugin :) No idea what it was, and it can be removed :)

**Comment by Dodjob** [comment]
Buuuut the sound signal is not going throught... 
![Screenshot from 2019-04-19 14-20-19](https://user-images.githubusercontent.com/42808575/56423924-751a4c00-62ae-11e9-98a2-d7470b994b65.png)

**Comment by wwmm** [comment]
It seems you do not have the Linux Studio Plugins package installed. At least on Arch Linux it is named lsp-plugins. Newer PulseEffects versions needs it.

**Comment by Dodjob** [comment]
Perfect! it was indeed the problem <3 I had to reinstall pulseeffects from the software center and it works like a charm! thanks and have a nice week-end!
![Screenshot from 2019-04-19 19-34-33](https://user-images.githubusercontent.com/42808575/56435915-72355080-62da-11e9-8653-974b52044966.png)
