### ISSUE TITLE
[Feature Request] Add a 'delay' option to the Crossfeed plugin

### ISSUE THREAD

**Issue by Userwithaname** [wwmm/pulseeffects#491]
I'd like to have an option to delay the feed by a small amount in the Crossfeed plugin (up to a millisecond).
This would serve sort of as a 'stereo widening' effect without needing to use the Convolver.

**Comment by wwmm** [comment]
As I am not the one who wrote the [bs2b](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad-plugins/html/gst-plugins-bad-plugins-bs2b.html) plugin I can't add this feature to it. You will have to be ask to GStreamer developers. I think this could be asked here https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues. 

That being said if all you want is to widen the stereo a bit you could use the `stereo tools` or the `delay` plugins together with the crossfeed. But if it is really necessary to delay the feed of the crossfeed the only solution is to have this implemented in GStreamer `bs2b` plugin.
