### ISSUE TITLE
Ctrl+Q doesn't work

### ISSUE THREAD

**Issue by AlexWayfer** [wwmm/pulseeffects#494]
Hello!

As I know, every GNOME application should have `Ctrl+Q` shortcut for Quit.

https://wiki.gnome.org/Design/OS/KeyboardShortcuts

**Comment by wwmm** [comment]
As I never use this shortcut I didn't think about it. I will try to remember to add this before the next release.

**Comment by wwmm** [comment]
Implemented

**Comment by AlexWayfer** [comment]
Thank you very much! :heart:
