### ISSUE TITLE
Equalizer not working

### ISSUE THREAD

**Issue by marioortizmanero** [wwmm/pulseeffects#495]
I've installed `pulseeffects` with pacman and everything seems to work except for the EQ. I can change the settings and presets but it doesn't change the audio at all. I have also installed every single optional package to check i wasn't missing any but It still doesn't work.

**Comment by wwmm** [comment]
Did you install the `lsp-plugins` package?

**Comment by wwmm** [comment]
Something else you may try is to clear GStreamer cache `rm -rf ~/.cache/gstreamer-1.0`

**Comment by marioortizmanero** [comment]
Cleaning the cache fixed it, thanks

**Comment by gstvchacon** [comment]
very thanks, cleaning the cache fixed it!!

**Comment by THEBOSS619** [comment]
installing lsp-plugins solved it for me after pop os 20 upgrade
