### ISSUE TITLE
No longer works on elementaryos 5

### ISSUE THREAD

**Issue by andrefcorreia** [wwmm/pulseeffects#498]
After the last system updates the pulseeffect does not work anymore. I can not hear any more sound with the pulseeffect open.
When the presseffect is open the elementaryos sound setting does not open as well.

**Comment by wwmm** [comment]
I need more information. Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. This should help us understand what is happening.

**Comment by andrefcorreia** [comment]
I think something is quite wrong. 
I do not find the pulseeffects command on the command line.
I get "pulseeffects: command not found".
I was normally using the pulseeffect. I can not remember how I had installed it before the problem happened. Today, after this problem I uninstalled using "apt purge pulseffects" and reinstalled through the flatpack.
And now the app opens and closes right after. Crazy thing.
Any idea?

**Comment by wwmm** [comment]
When using flatpak you can get the logs running `G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects`

**Comment by andrefcorreia** [comment]
Oh nice, thanks!
The result of G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects:

Gtk-Message: 00:03:10.394: Failed to load module "pantheon-filechooser-module"
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.730: application: PE version: 4.5.9
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.734: pulse_manager: context is connecting
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.734: pulse_manager: context is authorizing
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.735: pulse_manager: context is setting name
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.735: pulse_manager: context is ready
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.735: pulse_manager: connected to: unix:/run/user/1000/pulse/native
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.735: pulse_manager: protocol version: 32
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.735: pulse_manager: Pulseaudio version: 12.2
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.735: pulse_manager: default pulseaudio source: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.736: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.736: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.736: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.736: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.737: pulse_manager: sink loaded
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.737: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.737: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.737: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.738: pulse_manager: sink loaded
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.787: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.787: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.844: sie: limiter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.849: sie: compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.852: sie: filter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.910: sie: equalizer is enabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.915: sie: reverb is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.917: sie: bass_enhancer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.921: sie: exciter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.928: sie: crossfeed is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.932: sie: maximizer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.938: sie: multiband_compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.940: sie: loudness is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.942: sie: gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.956: sie: pitch is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.962: sie: multiband_gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.965: sie: deesser is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.968: sie: stereo_tools is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.978: sie: convolver is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.981: sie: crystalizer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.985: sie: autogain is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.988: sie: delay is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.999: soe: using output device: PulseEffects_mic
(pulseeffects:2): pulseeffects-DEBUG: 00:03:10.999: soe: using input device: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.000: soe: limiter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.001: soe: compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.001: soe: filter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.010: soe: equalizer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.010: soe: reverb is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.011: soe: gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.013: soe: deesser is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.014: soe: pitch is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.027: soe: webrtc is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.028: soe: multiband_compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.029: soe: multiband_gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.033: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.033: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/input
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.033: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/output
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.033: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/autoload
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.411: convolver_ui: irs directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/irs
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.809: sie: spectrum enabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:11.810: soe: spectrum enabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.102: sie: total latency: 0 ms
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.102: sie: compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.102: soe: total latency: 0 ms
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.396: pulse_manager: sink input: Brave, idx = 11 moved to PE
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.399: pulse_manager: sink input: Chromium, idx = 13 moved to PE
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.402: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.402: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.402: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.402: pulse_settings_ui: added source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.402: soe: using input device: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.402: pulse_settings_ui: input device changed: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.402: pulse_settings_ui: added source: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:03:12.407: sie: sampling rate: 44100 Hz

**Comment by andrefcorreia** [comment]
The result of G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects -q:

Gtk-Message: 00:06:03.308: Failed to load module "pantheon-filechooser-module"
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.354: application: PE version: 4.5.9
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.355: pulse_manager: context is connecting
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.355: pulse_manager: context is authorizing
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.355: pulse_manager: context is setting name
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: context is ready
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: connected to: unix:/run/user/1000/pulse/native
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: protocol version: 32
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: Pulseaudio version: 12.2
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: default pulseaudio source: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.356: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.373: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.373: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.392: sie: limiter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.396: sie: compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.398: sie: filter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.451: sie: equalizer is enabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.453: sie: reverb is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.455: sie: bass_enhancer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.457: sie: exciter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.460: sie: crossfeed is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.462: sie: maximizer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.467: sie: multiband_compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.468: sie: loudness is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.471: sie: gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.474: sie: pitch is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.478: sie: multiband_gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.481: sie: deesser is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.484: sie: stereo_tools is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.488: sie: convolver is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.491: sie: crystalizer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.493: sie: autogain is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.498: sie: delay is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.510: soe: using output device: PulseEffects_mic
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.510: soe: using input device: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.511: soe: limiter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.511: soe: compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.512: soe: filter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.519: soe: equalizer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.520: soe: reverb is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.521: soe: gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.522: soe: deesser is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.523: soe: pitch is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.528: soe: webrtc is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.529: soe: multiband_compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.530: soe: multiband_gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.533: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.533: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/input
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.533: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/output
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.533: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/autoload
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.539: application:  destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.539: presets_manager: destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.539: soe: destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.539: soe: multiband_gate destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.539: soe: multiband_compressor destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.539: soe: webrtc destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.540: soe: pitch destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.540: soe: deesser destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.540: soe: gate destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.540: soe: reverb destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.540: soe: equalizer destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.541: soe: filter destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.541: soe: compressor destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.541: soe: limiter destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.541: soe: NULL -> VOID_PENDING
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.542: sie: destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.542: sie: delay destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.542: sie: autogain destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.542: sie: crystalizer destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.542: sie: convolver destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.542: sie: stereo_tools destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.542: sie: deesser destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.543: sie: multiband_gate destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.543: sie: pitch destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.543: sie: gate destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.543: sie: loudness destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.543: sie: multiband_compressor destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.543: sie: maximizer destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.543: sie: crossfeed destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.543: sie: exciter destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.544: sie: bass_enhancer destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.544: sie: reverb destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.544: sie: equalizer destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.544: sie: filter destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.544: sie: compressor destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.544: sie: limiter destroyed
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.544: sie: NULL -> VOID_PENDING
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.546: pulse_manager: unloading PulseEffects sinks...
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.546: pulse_manager: module 27 unloaded
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.547: pulse_manager: module 28 unloaded
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.547: pulse_manager: Context did not need draining
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.547: pulse_manager: disconnecting Pulseaudio context...
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.547: pulse_manager: context was terminated
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.547: pulse_manager: Pulseaudio context was disconnected
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.547: pulse_manager: unreferencing Pulseaudio context
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.547: pulse_manager: stopping pulseaudio threaded main loop
(pulseeffects:2): pulseeffects-DEBUG: 00:06:03.547: pulse_manager: freeing Pulseaudio threaded main loop

**Comment by wwmm** [comment]
Nothing unusual. Are you sure nothing else is printed in the terminal when the crash happens?

**Comment by andrefcorreia** [comment]
Yes, I am sure.
This is the log when I was playing a video from youtube in brave browse. I used the command "G_MESSAGES_DEBUG = pulseeffects flatpak run com.github.wwmm.pulseeffects" and the pulseeffects opened and closed right after. But the process of pulseeffects continued and I had to kill it to sound back to normal. I dont know if anything changes in the log:

Gtk-Message: 19:24:50.215: Failed to load module "pantheon-filechooser-module"
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.264: application: PE version: 4.5.9
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.265: pulse_manager: context is connecting
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.265: pulse_manager: context is authorizing
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.265: pulse_manager: context is setting name
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.266: pulse_manager: context is ready
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.266: pulse_manager: connected to: unix:/run/user/1000/pulse/native
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.266: pulse_manager: protocol version: 32
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.266: pulse_manager: Pulseaudio version: 12.2
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.266: pulse_manager: default pulseaudio source: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.266: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.266: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.266: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.266: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.267: pulse_manager: sink loaded
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.267: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.268: pulse_manager: default pulseaudio source sampling rate: 48000 Hz
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.268: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.268: pulse_manager: sink loaded
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.285: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.285: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.307: sie: limiter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.310: sie: compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.312: sie: filter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.377: sie: equalizer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.380: sie: reverb is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.382: sie: bass_enhancer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.384: sie: exciter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.387: sie: crossfeed is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.388: sie: maximizer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.393: sie: multiband_compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.394: sie: loudness is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.397: sie: gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.401: sie: pitch is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.406: sie: multiband_gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.409: sie: deesser is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.412: sie: stereo_tools is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.415: sie: convolver is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.417: sie: crystalizer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.418: sie: autogain is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.422: sie: delay is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.428: soe: using output device: PulseEffects_mic
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.428: soe: using input device: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.429: soe: limiter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.430: soe: compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.431: soe: filter is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.438: soe: equalizer is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.439: soe: reverb is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.440: soe: gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.441: soe: deesser is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.443: soe: pitch is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.448: soe: webrtc is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.449: soe: multiband_compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.450: soe: multiband_gate is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.451: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.451: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/input
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.451: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/output
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.451: presets_manager: user presets directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/autoload
(pulseeffects:2): pulseeffects-DEBUG: 19:24:50.862: convolver_ui: irs directory already exists: /home/andre/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/irs
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.280: sie: spectrum enabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.281: soe: spectrum enabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.493: sie: total latency: 0 ms
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.493: soe: total latency: 0 ms
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.493: soe: compressor is already disabled
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.906: pulse_manager: sink input: Brave, idx = 55 moved to PE
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.910: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.910: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.910: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.910: pulse_settings_ui: added source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.910: soe: using input device: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.910: pulse_settings_ui: input device changed: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:2): pulseeffects-DEBUG: 19:24:51.910: pulse_settings_ui: added source: alsa_input.pci-0000_00_1f.3.analog-stereo

**Comment by andrefcorreia** [comment]
I was able to check what was going on with the eOS audio config. When I open the PE it disables all available sound outputs and then closes the audio config window. When I close the PE, everything goes back to normal.
[pe log.txt](https://github.com/wwmm/pulseeffects/files/3154596/pe.log.txt)

**Comment by wwmm** [comment]
It could be a configuration. Try to create another user account and test what happens there. It could also be some problem in one of the packages that was updated in your system. At least in Arch Linux everything is fine.

What I know for sure is that there is no code in PE that would try to enable/disable sound outputs. Something else is making them disappear.

**Comment by andrefcorreia** [comment]
Well...I tried. I couldnt create another user account in my system, I dont know why. So, I am using linux mint now and the PE is working fine. The only excepetion is when I select a preset from comunity preset PE closes on Linux mint.

**Comment by wwmm** [comment]
A few of the community presets we're not ported to the new format. This is probably the reason why they are crashing
