### ISSUE TITLE
Idle pulseffects cuts volume by 50%, Ubuntu 18.04

### ISSUE THREAD

**Issue by perwah** [wwmm/pulseeffects#499]
If I enable pulseeffects, but with no actual effects enabled, it still cuts the output volume 50%, or at least a very significant level, sound like 50%. It does not lower any system volume settings, just something in its pipeline that cuts down the processed (or non-processed, since no effects are enabled) output values. Like, reduce all ouput sample values by 50%.

No special circumstances here, it's been like this for years, across Ubuntu versions, just wondering if this is how it is supposed to be?

**Comment by wwmm** [comment]
Does not happen in my computer. No plugins enabled is the same as passthrough. Some latency will be added but no changes to volume.

Take a look at Pavucontrol tabs and see if any of the volume sliders related to PulseEffects virtual devices are in a low value

**Comment by perwah** [comment]
Yep, that was it, thanks.
