### ISSUE TITLE
Tray

### ISSUE THREAD

**Issue by Ixoos** [wwmm/pulseeffects#5]
Could you add option to run Pulseeffects in tray?

**Comment by wwmm** [comment]
I did some research and it seams that the gtk3 api necessary for this has been deprecated [http://stackoverflow.com/questions/41917903/gtk-3-statusicon-replacement](url). I am not against tray icons but at the same time I do not want to use a deprecated api. So for now the answer is no. But I will let this issue open for some time in case anyone comes up with a solution that adds system tray icons for desktops where they make sense without affecting PulseEffects behavior in Gnome.

**Comment by Ixoos** [comment]
https://gist.github.com/pklaus/304963 What about this? *Sorry if it isn't useful :/ *

**Comment by wwmm** [comment]
Hi! No problems.

This example uses gtk.status_icon_new_from_stock. This is the api that was deprecated in gtk 3.14
[https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html](url):

"GtkStatusIcon has been deprecated in 3.14. You should consider using notifications or more modern platform-specific APIs instead. GLib provides the GNotification API which works well with GtkApplication."

Though I doubt that using this api  would be really a problem while we are in gtk3 it has already been removed from gtk4:

[https://mail.gnome.org/archives/commits-list/2016-September/msg10049.html](url)

When the time to move to gtk4 comes all the code based on GtkStatusIcon would have to be removed from PulseEffects =/

**Comment by tadfisher** [comment]
Probably a better option is to turn PulseEffects into a daemon, such that a Gnome extension could be created to talk to it. It would be useful to run PulseEffects without opening the application as well.

**Comment by wwmm** [comment]
This crossed my mind some time ago. It is a possibility but it is going to require big code changes... I will give some thoughts to it but I make no promisses...

**Comment by Ixoos** [comment]
What about this https://api.kde.org/frameworks/knotifications/html/classKStatusNotifierItem.html ?
https://extensions.gnome.org/extension/615/appindicator-support/
This extension will be by default in Ubuntu 17.10

**Comment by wwmm** [comment]
knotifications is for kde/qt applications and what this extension does is showing notification icons of applications that use knotifications/appindicator in gnome.

Maybe this could be done with appindicator but I don't know if I want to use this. It is hard to find examples specially about the integration with the Gtk Application class used in PulseEffects.

**Comment by AsavarTzeth** [comment]
I would personally be against appindicator. It would complicate the Flatpak package quite a bit. Just take [this](https://github.com/flathub/io.github.Pithos/commit/0cf4ba1eed8dd662fdc4cc1da091b43e7897b73d) as an example. Sure I could exclude it but then users that know PulseEffects support it will start to ask for it.

Also I have to ask what purpose this would actually serve? @Ixoos never actually mentioned why, only that you do want it.

- If you want it to run in the background, I second @tadfisher.
- If you just want it out the way, minimize it, or put it in a different workspace.

I am also not sure how well maintained [libappindicator](https://launchpad.net/libappindicator) is or rather if it will improve much more now that Unity is discontinued. Just see the [change history](https://bazaar.launchpad.net/~indicator-applet-developers/libappindicator/trunk.16.10/changes/284?start_revid=284).

As for other desktops, KDE uses it but others, as far as I my experience goes, rely on extensions or applets, and the user experience isn't always great.

**Comment by Ixoos** [comment]
Me and few of my friends want this because we want to run it in the background. I'm using pulseeffects all the time and it would be nice to having it as a daemon.

**Comment by AsavarTzeth** [comment]
I see, as I suspected. Then a tray icon, while perhaps a quick solution, is not itself what ultimately want.

Take [FeedReader](https://jangernert.github.io/FeedReader/) as an example. It has a service that runs in the background and updates your feeds. When you close the app the service/daemon still works in the background.

**Comment by wwmm** [comment]
FeedReader approach would work but from development point of view it adds a lot of complexity as now the graphical interface has to talk to a background service using some protocol. The amount of code I would have to write/rewrite to do that in PulseEffects is insane. And in our case the main motivation is just hiding the window from the user. 

In any case there is something you can do that has a similar effect as having a daemon. Start PulseEffects with the option for hiding the interface [https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options](https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options). You just have to write a `.desktop` file that uses this command line option and copy it to `~/.config/autostart`. Just have in mind that this is not a daemon mode. As soon as you click PulseEffects launcher icon the window will be shown and if you close it it will kill the effects as usual. For people that use the same settings for everything this is enough.
