### ISSUE TITLE
Combine REW filters with PE

### ISSUE THREAD

**Issue by weter11** [wwmm/pulseeffects#500]
REW contain such filters as: Peaking, Low pass, High pass, Low shelf, High shelf, Notch, Modal peaking. 
How that filters corresponding to PE filters? Espepecially Peaking, I mainly use it.

**Comment by wwmm** [comment]
It will depend on the mode you select. For example if you choose `APO (DR)` as mode it will behave like the filters in equalizer APO. You can read more info about the equalizer here https://lsp-plug.in/?page=manuals&section=para_equalizer_x32_lr. But I suggest you try to contact its author in this github page https://github.com/sadko4u/lsp-plugins. He will be able to answer your questions about the filters implementations way better than I can.

**Comment by weter11** [comment]
So, overall as I am correct understand REW uses Bell fiters with biquad filter (at least for miniDSP & Generic (https://www.roomeqwizard.com/help/help_en-GB/html/equaliser.html)). Overall:
REW value → PulseEffects value
Peaking(parametric) → Bell filter
miniDSP & Generic EQ use biquad filters  → APO(DR) digital biquad filters mode
All other filters are the same (Low pass, High pass, Low shelf, High shelf, Notch) in both apps. There are no mode settings in REW like it is in PE.
Thanks for links.
How about adding this info to wiki?

**Comment by wwmm** [comment]
Feel free to add a new section to the wiki about REW. I gave write access to everybody.
