### ISSUE TITLE
Pulseeffects stopped working. 

### ISSUE THREAD

**Issue by sidbmw** [wwmm/pulseeffects#502]
Running the debug command gives me this:

G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.699: application: PE version: 4.5.9
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.700: pulse_manager: context is connecting
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.700: pulse_manager: context is authorizing
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.701: pulse_manager: context is setting name
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.701: pulse_manager: context is ready
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.701: pulse_manager: connected to: unix:/run/user/1001/pulse/native
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.701: pulse_manager: protocol version: 32
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.701: pulse_manager: Pulseaudio version: 12.2
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.701: pulse_manager: default pulseaudio source: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.701: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.701: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.701: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.701: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.702: pulse_manager: sink loaded
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.702: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.703: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.703: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.703: pulse_manager: sink loaded
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.716: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.716: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.730: sie: limiter is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.733: sie: compressor is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.734: sie: filter is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.779: sie: equalizer is enabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.781: sie: reverb is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.782: sie: bass_enhancer is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.784: sie: exciter is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.786: sie: crossfeed is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.787: sie: maximizer is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.790: sie: multiband_compressor is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.791: sie: loudness is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.794: sie: gate is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.796: sie: pitch is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.799: sie: multiband_gate is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.801: sie: deesser is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.802: sie: stereo_tools is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.805: sie: convolver is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.806: sie: crystalizer is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.807: sie: autogain is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.810: sie: delay is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.818: soe: using output device: PulseEffects_mic

(pulseeffects:3): pulseeffects-CRITICAL **: 20:44:40.818: pulse_manager:  failed to get source info:
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.819: soe: limiter is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.819: soe: compressor is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.820: soe: filter is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.826: soe: equalizer is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.827: soe: reverb is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.827: soe: gate is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.828: soe: deesser is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.829: soe: pitch is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.833: soe: webrtc is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.833: soe: multiband_compressor is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.834: soe: multiband_gate is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.835: presets_manager: user presets directory already exists: /home/nsiddharth/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.835: presets_manager: user presets directory already exists: /home/nsiddharth/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/input
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.835: presets_manager: user presets directory already exists: /home/nsiddharth/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/output
(pulseeffects:3): pulseeffects-DEBUG: 20:44:40.835: presets_manager: user presets directory already exists: /home/nsiddharth/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/autoload
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.146: convolver_ui: irs directory already exists: /home/nsiddharth/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/irs
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.492: sie: spectrum enabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.492: soe: spectrum enabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.685: sie: total latency: 0 ms
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.685: sie: gate is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.685: soe: total latency: 0 ms
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.685: soe: limiter is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.685: soe: limiter is already disabled
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.694: sie: sampling rate: 44100 Hz
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.696: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.696: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.696: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.696: pulse_settings_ui: added source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.696: pulse_settings_ui: added source: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.697: sie: NULL -> READY -> PLAYING
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.697: sie: READY -> PAUSED -> PLAYING
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.698: sie: pulsesrc latency [us]: 10000
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.698: sie: pulsesrc buffer [us]: 200000
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.698: sie: total latency: 0 ms
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.937: peadapter: pulseaudio block size 441 frames
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.937: peadapter: we will read in chunks of 512 frames
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.952: sie: total latency: 121 ms
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.953: sie: pulsesink latency [us]: 10000
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.953: sie: pulsesink buffer [us]: 200000
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.954: sie: total latency: 121 ms
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.954: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:3): pulseeffects-DEBUG: 20:44:41.954: sie: total latency: 121 ms

I tried running the git version as well as the flatpak version. As soon as I enable Pulseeffects I stop hearing anything.

I'm on Manjaro Deepin btw.

**Comment by wwmm** [comment]
At least on Arch Linux I have no problems. Your log is fine. So whatever is happening is not shown in it.  Take a print of Pavucontrol tabs when you hear nothing after enabling PulseEffects. Maybe there is a third party app messing with our audio routing. This would be visible in Pavucontrol

**Comment by sidbmw** [comment]
hmm why do I not have that installed....I shall install it now

**Comment by wwmm** [comment]
PulseEffects was working before and suddenly stopped? A long time deepin sound daemon was messing with our routing. It is a long story you can read in #240. I don't know if this manual config to disable this deepin feature is still necessary. I use Gnome.

**Comment by sidbmw** [comment]
Just found out that the audio is audible but it is extremely faint. I have to turn up my volume to almost 100% in order to properly hear the music. Any idea?

**Comment by wwmm** [comment]
A user faced a similar volume problem in #499. After taking a look at Pavucontrol he found out that one of PulseEffects sink volume slider was not at 100 %. The only explanation I have for this is that at some point he set our sink as default device(do not do that) and Pulseaudio saved this smaller volume.

**Comment by sidbmw** [comment]
Everything is at 100%

**Comment by sidbmw** [comment]
Any idea? Solution for #240 doesn't work.

**Comment by wwmm** [comment]
None. Assuming you did not set the equalizer input/output gain to a too low value something else is reducing this volume. Disabling all plugins is the same as pass audio through but adding some latency. Volume levels should be the same as if PulseEffects was not there.

You could try a reset `pulseeffects --reset`. But this would not change things like the volume of the virtual sinks we create. Or you could create a second user account and test if there the problem remain.

I know Manjaro does not use Arch repositories like Antergos but our systems shouldn't be that different. Somewhere a config is wrong. OR there is some kind of issue with Deepin I am not aware of.

**Comment by sidbmw** [comment]
Yeah reset didn't help. Might try creating a new user tomorrow. It was fine until recently I believe. Might have been one of the updates.

**Comment by sidbmw** [comment]
Created a new user and everything seems to be working fine on that account. How can I copy all the audio related files over or maybe just reset all the audio related files on my main account?

**Comment by wwmm** [comment]
If this works but resetting PulseEffects doesn't maybe one of Pulseaudio's config files is corrupted. Try to delete the folder `~/.config/pulse/` and login again.

Depending on how you are using PulseEffects you may or may not have files under `~/.config/PulseEffects/` that could be copied to the new account. But I think it would be better to find out which config is causing this problem instead of moving to the new account.

**Comment by sidbmw** [comment]
Ok, seems to work now. I manually have to select "headphone out (unplugged)"  in pavucontrol for some reason. When I plug in my earphones there isn't a popup in gnome anymore either.
