### ISSUE TITLE
Crashes & no audio output since PulseAudio update

### ISSUE THREAD

**Issue by mauritzn** [wwmm/pulseeffects#503]
Hello, I have been having quite a bit of issues since the last PulseAudio update, when the update first got installed I was unable to use PulseEffects at all, it got audio in but nothing was playing and after trying to switch outputs and inputs around it crashes. I tried to reinstall but no change, I looked for others having the same issue on this repo, but couldn't find anything, I tried to launch PulseEffects with debugging on, and for some reason it stopped crashing, but I still have issues getting it to output audio. I have also tried resetting PulseEffects config both with the first update of PulseAudio and then after the reinstall as well.

I am only using the equalizer in PulseEffects, with a slight modification of the **"ziyad_perfecteq"** preset.

Most recently it crashed in debug mode, but the console output looked fine, just two warning at the end that didn't seem that worrying, the whole log file is 9430 lines, so I am unsure whether or not I should add it *(I have attached the last 500 lines)*?

[pulseeffects_log-last_500_lines.txt](https://github.com/wwmm/pulseeffects/files/3145422/pulseeffects_log-last_500_lines.txt)

*To add a little clarification I have gotten the audio to output sometimes when using in debug mode, but took several minutes of switching the speakers output setting from "Analog Stereo Output" to "Digital Stereo (IEC958) Output + Analog Stereo Input" and to "Off"*

---

### I am running:
**OS:** Kubuntu 18.04.2 *(kernal: 4.15.0-48-generic)* *[default KDE DE]*
**CPU:** AMD Ryzen 7 2700X
**GPU:** NVIDIA GeForce GTX 1080
**RAM:** 32GB

**PulseAudio:** pulseaudio 12.2
**PulseEffects:** 4.6.0-1~bionic1 *(installed using apt)*

**Comment by wwmm** [comment]
For some reason our pipeline is alternating between playing and the pause state without stopping. Which audio are you using?

IT would also be good to see the beginning of the log.

**Comment by mauritzn** [comment]
What exactly do you mean with which audio am I using? Like what type of audio I'm playing on the computer? If so mostly Netflix, YouTube and YouTube Music, so mostly dialog and music.
*(I have attached the full log file below)*

[pulseeffects_log-full.txt](https://github.com/wwmm/pulseeffects/files/3146007/pulseeffects_log-full.txt)

**Comment by wwmm** [comment]
I was thinking about `audio applications` but didn't write it. I asked this because if only one audio app is playing and this app suddendly alternates between between `playing/paused` something similar would happen to the logs. But web browsers are no problem. I use Netflix and YouTube too.

**Comment by wwmm** [comment]
For some reason PE is also trying to update the plugins order multiple times. Lots of lines with `new plugins order`. Inever saw this happening. How did you try to reset PE? Did you use the reset button in the menu or just deleted the folder `~/.config/PulseEffects/`. Just deleting the folder is not enough. A reset could also be done through `pulseeffects -q`.

It feels like some configuration is corrupted.  Try to create another user account and see if PE is also broken there. You could also try to see if when install PE through flatpak the issue remains

**Comment by mauritzn** [comment]
I reset the configuration using the notification provided by PulseEffects when it detected an update to PulseAudio, I also tried resetting it manually through PulseEffects. Haven't tried "pulseeffects --reset", but is it similar to the reset notification provided by PulseEffects?

**Comment by wwmm** [comment]
They do the same. So this is not the problem. Try on another user account. If it does not work then something is wrong in the installation.

**Comment by mauritzn** [comment]
Would trying it on another account have a similar effect as a reinstall would have? Just wondering since I have tried doing a full reinstall and purge of PulseEffects. Asking so I know whether or not to still try it or if it would be futile and I should try to install using flatpak instead.

**Comment by wwmm** [comment]
It is not the same. If PE works on another user account we will know for sure that its installation is fine but some kind of configuration is corrupted in the affected user account. You have already reset PE settings. But maybe there is some kind of corrupt config elsewhere. It could be Pulseaudio or something else that is not obvious to think about in advance. 

In the past some users were having bizarre problems and when they tried in another account everything was fine.

**Comment by mauritzn** [comment]
Sorry it took so long for me to get back to you, had a bit of a hectic time. Two days ago a new PulseAudio update was available, and the update seems to have fixed all the crashing, not sure why exactly, but everything seems to be working fine now

**Comment by wwmm** [comment]
Ok
