### ISSUE TITLE
Pulseeffects randomly freezes when changing srs-file.

### ISSUE THREAD

**Issue by tnilzon** [wwmm/pulseeffects#505]
In the Convolver section and when changing irs-file, Pulseeffects randomly (and quite frequent) freezes. The sound that is playing goes to silence, and Pulseeffects does not react on mouse clicks (it is frozen). The only way to get it going again is to force a shut down, and restart it.
Version: 4.5.9
>System:
  Host: tomas-pc Kernel: 5.0.9-2-MANJARO x86_64 bits: 64 
  Desktop: KDE Plasma 5.15.4 Distro: Manjaro Linux 
Audio:
  Device-1: Intel Cannon Lake PCH cAVS driver: snd_hda_intel 
  Device-2: Z-Star Micro type: USB driver: snd-usb-audio,uvcvideo 
  Sound Server: ALSA v: k5.0.9-2-MANJARO

**Comment by wwmm** [comment]
What is the size of the impulse files you are using? At least here on my computer (Arch Linux) impulse files of `8 MB` take around 2 seconds to load. While this is happening there is silence indeed. But after that PulseEffects continues to play sound with no problems. No need to kill it.

Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Maybe the logs will show what is happening in your system.

**Comment by tnilzon** [comment]
Size of irs files are only about `100-200 kB`. This is an example of a log when Pulseeffects  freezes:
>(pulseeffects:30473): pulseeffects-DEBUG: 09:57:28.980: convolver: irs file: /home/tomas/.config/PulseEffects/irs/srs_hd_audio_lab_01.irs
(pulseeffects:30473): pulseeffects-DEBUG: 09:57:28.980: convolver: irs rate: 44100 Hz
(pulseeffects:30473): pulseeffects-DEBUG: 09:57:28.980: convolver: irs channels: 2
(pulseeffects:30473): pulseeffects-DEBUG: 09:57:28.980: convolver: irs frames: 16383
(pulseeffects:30473): pulseeffects-DEBUG: 09:57:28.980: convolver: irs file does not need resampling
(pulseeffects:30473): pulseeffects-DEBUG: 09:57:28.981: convolver: autogain factor: 0,732889
Segmentation fault (core dumped)

The irs file is below, just change the extension to .irs

[srs_hd_audio_lab_01.txt](https://github.com/wwmm/pulseeffects/files/3168773/srs_hd_audio_lab_01.txt)

Here is another example (with a bit different error):

>(pulseeffects:9801): pulseeffects-DEBUG: 10:09:42.693: convolver: irs file: /home/tomas/.config/PulseEffects/irs/SRS_1_1_Normal_stereo.irs
(pulseeffects:9801): pulseeffects-DEBUG: 10:09:42.693: convolver: irs rate: 44100 Hz
(pulseeffects:9801): pulseeffects-DEBUG: 10:09:42.694: convolver: irs channels: 2
(pulseeffects:9801): pulseeffects-DEBUG: 10:09:42.694: convolver: irs frames: 16384
(pulseeffects:9801): pulseeffects-DEBUG: 10:09:42.694: convolver: irs file does not need resampling
(pulseeffects:9801): pulseeffects-DEBUG: 10:09:42.694: convolver: autogain factor: 0,439214
corrupted double-linked list
Aborted (core dumped)

[SRS_1_1_Normal_stereo.txt](https://github.com/wwmm/pulseeffects/files/3168782/SRS_1_1_Normal_stereo.txt)

Note also that the freezing occurs randomly, not every time with these irs files. Sometimes it works just fine, and sometimes it freezes. I have also experienced this behavior on Manjaro gnome (so it is not related to KDE only).

**Comment by wwmm** [comment]
It is freezing because it is crashing. Lines `Segmentation fault (core dumped)` and `corrupted double-linked list`. For some reason I have a crash only when I alternate irs files multiple times. Sometimes 20 times. Sometimes I have to alternate 50 times.

In any case it seems I am doing something that is making GTK crash when the irs data is plotted in the interface.

**Comment by wwmm** [comment]
I did some changes that seem to ahve fixed this issue. Are you able to test them using this aur package https://aur.archlinux.org/packages/pulseeffects-git/ ?

**Comment by tnilzon** [comment]
I have now tested your new AUR package `(pulseeffects-git 4.5.0.r23.g7e3852cf-1)`.
After trying this multiple times, I can confirm that it seems fixed, no crashes so far!
Very good (and fast) job. I use the Convolver alternating irs files quite frequent, and this has been frustrating.

Once again many thanks, Pulseeffects is really a great audio tool for me in Linux, also using it on my Linux-HTPC connected to a home stereo. The result on audio quality (e.g. Spotify) is amazing!
