### ISSUE TITLE
Applications output help/tips on app

### ISSUE THREAD

**Issue by andrefcorreia** [wwmm/pulseeffects#506]
First of all, I am very noob about audio. So, that said, how about include tips or help about each Applications output? 

I am testing all the options but I am really dont know what I am doing (rsrs). 

Can I get that kind of help/tips in the app for the next versions of the PE? 

Thanks!

**Comment by wwmm** [comment]
I am not sure I understand what you mean by applications output. We already have help for most things
![Screenshot from 2019-05-15 23-12-30](https://user-images.githubusercontent.com/16225172/57821659-ada32d80-7767-11e9-9808-e94b9c9a883c.png)
Press `F1` or click on the help icon at the side of the presets button. But I have to admit it may be a little too technical.

I don't think we are going to have help outside of the manual. So any improvement will have to be done in it.

**Comment by andrefcorreia** [comment]
I am so dumb. Thanks.
