### ISSUE TITLE
Segmentation fault in `load_apps_sink`

### ISSUE THREAD

**Issue by joonatoona** [wwmm/pulseeffects#518]
pulseeffects compiled from source (commit cb09e4de989f88e81bb898dee24e55c20175d1dd)  
`pulseaudio 12.2`

After tracing, looks like the issue originates from `src/pulse_manager.cpp:601`, in the function call `PulseManager::get_sink_info(this=..., name="PulseEffects_apps")`. The callback from `pa_context_get_sink_info_by_name` fails, I can't figure out why though :(

If I remove the check in `get_sink_info`, the application doesn't crash, but no sinks are created.

**Comment by wwmm** [comment]
At least on Arch Linux latest master is running https://circleci.com/gh/wwmm/pulseeffects/139. What PE prints when you run it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`?

**Comment by joonatoona** [comment]
```
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.054: application: PE version: 4.6.1
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.056: pulse_manager: context is connecting
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.057: pulse_manager: context is authorizing
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.057: pulse_manager: context is setting name
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.057: pulse_manager: context is ready
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: connected to: /run/user/1000/pulse/native
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: protocol version: 32
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: Pulseaudio version: 12.2-dirty
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: default pulseaudio source: alsa_output.usb-Schiit_Audio_Schiit_Modi_3-00.iec958-stereo.monitor
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: default pulseaudio sink: alsa_output.usb-Schiit_Audio_Schiit_Modi_3-00.iec958-stereo
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: default pulseaudio sink audio format: s32le
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: Null sinks rewinds will be disabled
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: sink loaded
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.058: pulse_manager: default pulseaudio source audio format: s32le
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.059: pulse_manager: Null sinks rewinds will be disabled
(pulseeffects:30080): pulseeffects-DEBUG: 16:54:27.059: pulse_manager: sink loaded
[1]    30080 segmentation fault (core dumped)  G_MESSAGES_DEBUG=pulseeffects ./src/pulseeffects
````

**Comment by joonatoona** [comment]
Oh, I've found the issue. In `pulse-manager.cpp:537` you check for a `-` in the version, and assume that means pulseaudio 13 is installed. Removing that check fixes it for me, but I'll try and find a proper fix for that.

**Comment by wwmm** [comment]
Ok. thanks. In the latest PE versions I am trying to detect if the user is using a stable Pulseaudio release like `12.2` or if he is using the latest Pulseaudio code compiled from its git repository. The reason is to allow people to benefit from a patch I sent to Pulseaudio devs https://gitlab.freedesktop.org/pulseaudio/pulseaudio/merge_requests/93 that fix this issue #350. On Arch Linux Pulseaudio reports its version as `12.2`. So I assumed this would be the case everywhere. My bad.

**Comment by wwmm** [comment]
It would be good to have a decent way to detect if a git build is being used. I did not find a better idea. And it is unfortunate that on other distributions the version string is modified this way even in a stable build.

**Comment by joonatoona** [comment]
I think I've found a decent solution, I'll open a pull request soon.
