### ISSUE TITLE
Issue - Convolver Plugin not recognizing IR files

### ISSUE THREAD

**Issue by source83** [wwmm/pulseeffects#527]
If I have understood this correctly, it should recognize wav, mp3 and possibly aiff ?
Anyway, when trying to import a new IR, none of the IR files are listed.
Do I have the wrong format?
I also tried to copy the files directly to .config/PulseEffects/irs/ and there were still none listed.

**Comment by wwmm** [comment]
Rename the wav files to `*.irs` mp3 and aiff are not supported

**Comment by source83** [comment]
That needs to be stated somewhere

**Comment by source83** [comment]
Thanks, it worked.
As I stated, there is no indication or mention anywhere what the files must be wav and that they need to have .irs as extension.

I think it'd helt if it is stated in the help document for the program in the convolver section.

**Comment by wwmm** [comment]
I totally agree. But at this moment I have to take care of PulseEffects code and of its documentation almost by myself. And most of the time I have to favor code development and maintenance
