### ISSUE TITLE
Misplaced plugins.

### ISSUE THREAD

**Issue by SR-dude** [wwmm/pulseeffects#528]
No plugins and the and everything is grey. Since I install by source, I have been simply passing --prefix=/usr and --libdir=/usr/lib when building the plugins.  I have build every possible dependency that pulseeffects could want. But, it's not find finding the plugins that it needs.  I think that at configure time, things aren't getting installed at the right spot. 

CALF built  an so library,  in: /usr/lib/calf, but I don't  where it placed it's plugins if it build them at all.
LADSPA is place here:  /usr/lib/ladspa
(Eg.,    /usr/lib/ladspa/filter.so)

LSP gets installed  here: /usr/lib/vst/lsp-plugins-lxvst-1.1.9.
(Eg.,   /usr/lib/vst/lsp-plugins-lxvst-1.1.9/lsp-plugins-vst-sc-limiter-stereo.so)

LV2 creates a bunch of folders in:/usr/lib/lv2.
Each folder is stuff with files with the *.ttl extension.  TTL's 
referring to calf and lsp are in there.
_________________________________________
gst-inspect-1.0 | grep -i calf
&
gst-inspect-1.0 | grep -i lsp
both return nothing.
Removing .cache/gstreamer-1.0 also has been tried.

Some of the missing plugins go: limiter, compressor , filter, equalizer, reverb 
bass_enhancer, exciter, maximizer, loudness, gate, pitch, deesser,
stereo_tools , and delay.

**Comment by wwmm** [comment]
If `gst-inspect-1.0` cannot find the plugins PulseEffects is also not going to be able to find them. Which distribution are you using? BEsides installing the plugins you also need to have the library `lilv` installed. Without it GStreamer can not load Calf or LSP

**Comment by SR-dude** [comment]
lilv-0.24.4 got installed this way with waf:
  Install prefix                         : /usr 
  Default LV2_PATH                       : ~/.lv2:/usr/lib/lv2 
  Utilities                              : yes 
  Dynamic manifest support               : no 
  Python bindings                        : no
_________________________________
the manifest:
- install /usr/include/lilv-0/lilv/lilv.h (from lilv/lilv.h)
- install /usr/include/lilv-0/lilv/lilvmm.hpp (from lilv/lilvmm.hpp)
+ install /usr/lib/pkgconfig/lilv-0.pc (from build/lilv-0.pc)
+ install /usr/lib/liblilv-0.so.0.24.4 (from build/liblilv-0.so)
- symlink /usr/lib/liblilv-0.so (to liblilv-0.so.0.24.4)
- symlink /usr/lib/liblilv-0.so.0 (to liblilv-0.so.0.24.4)
+ install /usr/bin/lilv-bench (from build/utils/lilv-bench)
+ install /usr/bin/lv2info (from build/utils/lv2info)
+ install /usr/bin/lv2ls (from build/utils/lv2ls)
+ install /usr/bin/lv2apply (from build/utils/lv2apply)
+ install /usr/bin/lv2bench (from build/utils/lv2bench)
- install /usr/share/man/man1/lv2apply.1 (from doc/lv2apply.1)
- install /usr/share/man/man1/lv2info.1 (from doc/lv2info.1)
- install /usr/share/man/man1/lv2ls.1 (from doc/lv2ls.1)
- install /usr/etc/bash_completion.d/lilv (from utils/lilv.bash_completion)

**Comment by SR-dude** [comment]
To answer your question, I am a lnux from scratch user.
 gst-inspect-1.0 does return stuff,  about 748 lines ending
in this:
Total count: 188 plugins (1 blacklist entry not shown), 748 features

**Comment by wwmm** [comment]
Do you remember if lilv was installed when you compiled `gst-plugins-bad`? Now I remember that a long time ago Arch Linux `gst-plugins-bad` package had a bug that prevented GStreamer from finding LV2 plugins. At some point they removed a mistake was made and lilv was removed from `gst-plugins-bad` build requirement list.

**Comment by SR-dude** [comment]
I intentionally diabled lv2 (--disable-lv2 ). -bad woudn't compile with it.

**Comment by wwmm** [comment]
So that is the problem. I must have failed because `lilv` was not installed.

**Comment by SR-dude** [comment]
Alright I'll try again.  My gstreamer suite is at version 1.16. I might have to take the matter up with the developers concerning the build error. 
++
OK, I did some additional poking around and indeed both CALF & LSP installed files in /usr/lib/lv2.

**Comment by wwmm** [comment]
I also have `1.16` on Arch Linux. In case it helps this is the PKGBUILD used by Arch maintainers https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gst-plugins-bad

**Comment by SR-dude** [comment]
I've got a lead on what I need to do to fix the build error with gstlv2utils.c.
I get the error attempt to use poisoned "gst_debug_log_valist".  

[https://github.com/RidgeRun/gst-shark/issues/51](url)

**Comment by SR-dude** [comment]
I recompiled gstreamer with the --enable-gst-debug switch. That fixed the disabled  `lilv` support within
 `bad`.  Now `gst-inspect-1.0 | grep -i calf & gst-inspect-1.0 | grep -i lsp` fills out.  The only missing plugins now are maximizer, pitch, and  webrtc.

In spite of me removing `~/.cache/gstreamer-1.0` and killing/restarting pulse,  the behavior of pulseeffects did not change.  It's still grey. 

I get a pop-up box every time I start pulseeffects saying that pulseffects was updated. And it is recommended to restart it's configuration after an update. Every time.
________________
$ gst-inspect-1.0 | grep -i pitch
soundtouch:  pitch: Pitch controller

**Comment by wwmm** [comment]
Kill the current PE instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. This should give some clues.

**Comment by wwmm** [comment]
For webrtc you need the `webrtcdsp` plugin that is also provided by gst-plugins-bad. I think that it also has to be enabled when compiling gst-plugins-bad.

For the pitch plugin you need to install the ladspa rubberband library. `gst-inspect-1.0` shows it as `ladspa-ladspa-rubberband-so-rubberband-pitchshifter-stereo`

The maximizer needs the ladspa library of the ZamAudio plugins http://www.zamaudio.com/?p=976

**Comment by wwmm** [comment]
The popup box should come with `yes/no` buttons so you choose if you want to reset the config or not. At least on gnome these buttons are shown. I am not sure about other desktops. If you do not choose one option the popup will be shown again.

**Comment by SR-dude** [comment]
I do get the yes/no buttons. I'll do some additional work on getting the plugins.

After selecting yes,  ~/.config/PulseEffects/{autoload, input, irs, output} get created **but** no config files are created, ever. The directories are always empty. Isn't something suppose to be there?

**Comment by SR-dude** [comment]
SR-dude [ ~/src ]$ G_MESSAGES_DEBUG=pulseeffects pulseeffects
GLib-GIO-Message: 11:16:12.133: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
: presets_manager: user presets directory already exists: /home/SR-dude/.config/PulseEffects
: presets_manager: user presets directory already exists: /home/SR-dude/.config/PulseEffects/input
: presets_manager: user presets directory already exists: /home/SR-dude/.config/PulseEffects/output
: presets_manager: user presets directory already exists: /home/SR-dude/.config/PulseEffects/autoload
: application: PE version: 4.6.3
: pulse_manager: context is connecting
: pulse_manager: context is authorizing
: pulse_manager: context is setting name
: pulse_manager: context is ready
: pulse_manager: connected to: /tmp/xdg-SR-dude/pulse/native
: pulse_manager: protocol version: 33
: pulse_manager: Pulseaudio version: 12.0-316-gf34ea
: pulse_manager: default pulseaudio source: alsa_output.pci-0000_24_00.3.analog-stereo.monitor
: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_24_00.3.analog-stereo
: pulse_manager: loading Pulseeffects applications output sink...
: pulse_manager: default pulseaudio sink sampling rate: 48000 Hz
: pulse_manager: default pulseaudio sink audio format: s16le
: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_apps sink_properties=device.description="PulseEffects(apps)"device.class="sound" norewinds=1
: pulse_manager: loading Pulseeffects microphone output sink...
: pulse_manager: default pulseaudio source sampling rate: 48000 Hz
: pulse_manager: default pulseaudio source audio format: s16le
: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_mic sink_properties=device.description="PulseEffects(mic)"device.class="sound" norewinds=1
: sie: using input device: PulseEffects_apps.monitor
: sie: using output device: alsa_output.pci-0000_24_00.3.analog-stereo
: sie: limiter is already disabled
: sie: compressor is already disabled
: sie: filter is already disabled
: sie: equalizer is already disabled
: sie: reverb is already disabled
: sie: bass_enhancer is already disabled
: sie: exciter is already disabled
: sie: crossfeed is already disabled
: maximizer plugin was not found!
: sie: multiband_compressor is already disabled
: sie: loudness is already disabled
: sie: gate is already disabled
: pitch plugin was not found!
: sie: multiband_gate is already disabled
: sie: deesser is already disabled
: sie: stereo_tools is already disabled
: sie: convolver is already disabled
: sie: crystalizer is already disabled
: sie: autogain is already disabled
: sie: delay is already disabled
: soe: using output device: PulseEffects_mic
: soe: using input device: alsa_output.pci-0000_24_00.3.analog-stereo.monitor
: soe: limiter is already disabled
: soe: compressor is already disabled
: soe: filter is already disabled
: soe: equalizer is already disabled
: soe: reverb is already disabled
: soe: gate is already disabled
: soe: deesser is already disabled
: pitch plugin was not found!
: webrtc plugin was not found!
: soe: multiband_compressor is already disabled
: soe: multiband_gate is already disabled
: presets_manager: user presets directory already exists: /home/SR-dude/.config/PulseEffects
: presets_manager: user presets directory already exists: /home/SR-dude/.config/PulseEffects/input
: presets_manager: user presets directory already exists: /home/SR-dude/.config/PulseEffects/output
: presets_manager: user presets directory already exists: /home/SR-dude/.config/PulseEffects/autoload
: presets_manager: destroyed
: convolver_ui: irs directory already exists: /home/SR-dude/.config/PulseEffects/irs
: sie: spectrum enabled
: soe: spectrum enabled
: sie: total latency: 0 ms
: soe: total latency: 0 ms
: pulse_settings_ui: added sink: alsa_output.pci-0000_22_00.1.hdmi-stereo
: sie: using output device: alsa_output.pci-0000_24_00.3.analog-stereo
: pulse_settings_ui: output device changed: alsa_output.pci-0000_24_00.3.analog-stereo
: pulse_settings_ui: added sink: alsa_output.pci-0000_24_00.3.analog-stereo
: pulse_settings_ui: added source: alsa_output.pci-0000_22_00.1.hdmi-stereo.monitor
: soe: using input device: alsa_output.pci-0000_24_00.3.analog-stereo.monitor
: pulse_settings_ui: input device changed: alsa_output.pci-0000_24_00.3.analog-stereo.monitor
: pulse_settings_ui: added source: alsa_output.pci-0000_24_00.3.analog-stereo.monitor
; application: Resetting configurations

**Comment by wwmm** [comment]
Those directories will be empty. They are not where most of the configuration is stored. We use gsettings for that. Our configs are stored at `/usr/share/glib-2.0/schemas/` and can be viewd in `dconf-editor`
![Screenshot from 2019-06-13 12-40-11](https://user-images.githubusercontent.com/16225172/59446713-68126880-8dd8-11e9-8c95-e49d150c3ddd.png)

**Comment by wwmm** [comment]
Small correction. Our settings schemas are stored at `/usr/share/glib-2.0/schemas/`. Gsettings probably has per user files saved at each home folder. In any case there is no need to search for them. I never saw gsettings fallback to this `memory` backend. This is not normal.

**Comment by wwmm** [comment]
Maybe these links can help 
https://bugs.launchpad.net/ubuntu/+source/glib2.0/+bug/757866
https://askubuntu.com/questions/558446/my-dconf-gsettings-installation-is-broken-how-can-i-fix-it-without-ubuntu-reins

**Comment by SR-dude** [comment]
You have given me a lot of things to do.  I'll work on it.

**Comment by SR-dude** [comment]
Installing dconf got me off of the `memory` backend. That line in the log is gone.
+++

This is new. Have you seen these before? It repeats 74 times in the log.

> (gst-plugin-scanner:1846): GLib-GObject-CRITICAL **: 12:26:27.525: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed
(gst-plugin-scanner:1846): GLib-GObject-CRITICAL **: 12:26:27.526: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

**Comment by wwmm** [comment]
A few months ago GStreamer started doing this even when just running gst-inspect. In my opinion this is a bug in GStreamer's plugin scanner. In any case it is harmless. PE should still work

**Comment by SR-dude** [comment]
All I could find on rubberband was at the following link. 
It was not found in the ladspa_sdk nor in  the LADSPA
CMT toolkit.

[https://breakfastquay.com/rubberband/](url)

Now the ZamAudio Library, I'll think about paying for it. :)
