### ISSUE TITLE
Textual parameter input

### ISSUE THREAD

**Issue by hollunder** [wwmm/pulseeffects#53]
Hi.

I tried this thing for voice recording, mainly the compressor. Parameters for attack/release and so on are typically set very low for voice recordings and those are next to impossible to set using the current slider. Some textual input would help there.

On a sidenote, this thing needs more documentation, it's non-obvious how it works, especially the routing within PA.

**Comment by wwmm** [comment]
Hi,

I replaced those sliders by spinboxs in latest PulseEffects(2.3.0). It should fix this issue.

I agree that it needs more documentation but unfortunately I don't have time to focus on it it now. What is not clear about the PA routing?

**Comment by hollunder** [comment]
Thanks. I've tried version 2.3.4 and it is better. I can enter values and also see the amount of gain reduction on the compressor. However, those bars move so quickly, it's hard to see how much exactly. But I can see that there is compression going on, e.g. the threshold is about where it should be, which is the important bit. A clipping indicator would be a nice addition.

One design I quite liked was the compressor in the calf-plugins. It gives a good impression of what's going on at a glance.

What confused me at first is the are at the bottom that show pulse streams I guess. Or sinks and sources. Or whatever it is. And that I need to flip the switch in the bottom right to apply the current effect to that thing. It is entirely unlabeled and It's not totally obvious what's going on for someone new to the program.

Thanks for the improvements!
