### ISSUE TITLE
Audio delay when playing new audio tracks

### ISSUE THREAD

**Issue by azsorlex** [wwmm/pulseeffects#530]
Whenever PulseEffects is enabled for an application, the audio takes a moment to process when starting a new audio track, creating a visible/audible delay. Two examples of this problem are when watching YouTube videos through Google Chrome and listening to music on Spotify. With youtube videos, the first frame will load, and then it will buffer for one or two seconds and play once the audio is ready. For Spotify (this one only really occurs when skipping to the next/previous track), the bar at the bottom will begin to move, but the audio is still being processed just like the youtube videos; the result is the first second or two of the song being completely ignored. Once I uncheck the apps in the "Applications" tab, the problems vanish.

I've tried three other things in my troubleshooting. First, instead of disabling the apps, I tried disabling the options (I use Bass Enhancer and Equalizer), which didn't affect the delay at all. Next, I tried testing it on my laptop which has Ubuntu 19.04. I should first mention that my main system has a mix of old and new hardware (MB is a Gigabyte GA-Z68X-UD3H-B3, CPU is a 2600k, other stuff is irrelevant (I think?)), and uses Pop!_OS 19.04, whereas my laptop is an HP Probook 450 G4. Exact same issues occurred. Lastly, since Popos has a different app store to Ubuntu, I thought maybe that was the problem. In the past, I figured out that the Flatpak version of OBS is better than the one in the Pop!_Shop, so after following [these instructions](https://flatpak.org/setup/Ubuntu/) and installing the Flatpak version of PulseEffects, it didn't make a difference.

**Comment by wwmm** [comment]
Which PulseEffects version are you using? Versions older than `4.6.2` will behave like this when only one app is playing audio and you skip tracks or restarted it. The reason was that we were trying to save cpu power too aggressively by stopping our pipeline as soon as no app was playing audio. We still try to save cpu power but now we wait for 5 seconds before taking the decision to stop our pipeline. At least on my computer I see no audio delay when skipping tracks in spotify.

In case you do have the latest version another possibility is that you have big buffer and latency values set in PE config. Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Buffer and latency will be printed when you start an audio app.

**Comment by azsorlex** [comment]
It's 4.5.8. How do I upgrade to the latest?

**Comment by wwmm** [comment]
Then buffer and latency are not the problem. Upgrading to `4.6.2` or later should help or fix this issue. But as I use Arch Linux I am not sure how you can do this. Depending on the ubuntu version you could use a PPA https://github.com/wwmm/pulseeffects/wiki/Package-Repositories. Based on what I saw here https://flathub.org/apps/details/com.github.wwmm.pulseeffects flatpak is still in `4.5.9`. So it won't help. 

A last resort would be to compile our source and install in a place like `/usr/local`. But in my opinion using a distribution package would preferable.

**Comment by azsorlex** [comment]
So before I try moving on to the last resort, installing the PPA isn't working. So, it _installs_, but it doesn't _upgrade_ to the version I need. In addition to uninstalling the previous version of the app, I also tried removing the config folder located in `~/.config`. What am I missing?

Also, can't you update the Flatpak/Snap etc. versions of pulseeffects? Forgive me, I don't know how publishing an open-source application to those places works.

**Comment by azsorlex** [comment]
Update: after trying to remove the store version of pulseeffects and install the PPA version, I somehow broke my packages which in turn broke my system. Don't know how I did it, but I did it. Right now I've put some basic stuff back together including the PPA version of pulseeffects, and it's still version 4.5.8.

**Comment by wwmm** [comment]
I only develop and maintain PulseEffects. Distribution packages are maintained by other volunteers in their free time. You can ask for a flatpak update here https://github.com/flathub/com.github.wwmm.pulseeffects. The PPA is maintained  by @mikhailnov. He can tell you what is going on.

**Comment by mikhailnov** [comment]
4.6.3 is in the PPA (https://launchpad.net/~mikhailnov/+archive/ubuntu/pulseeffects/+packages), show your output of `apt policy pulseeffects` and `which pulseeffects`

**Comment by azsorlex** [comment]
@wwmm Thanks

@mikhailnov 

alex@alex-linux:~$ apt policy pulseeffects
pulseeffects:
  Installed: 4.5.8-1-git20190326~disco1
  Candidate: 4.5.8-1-git20190326~disco1
  Version table:
     4.6.3-1~disco1 500
        500 http://ppa.launchpad.net/mikhailnov/pulseeffects/ubuntu disco/main amd64 Packages
 *** 4.5.8-1-git20190326~disco1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status

alex@alex-linux:~$ which pulseeffects
/usr/bin/pulseeffects

**Comment by mikhailnov** [comment]
run `apt dist-upgrade`

**Comment by azsorlex** [comment]
`alex@alex-linux:~$ sudo apt dist-upgrade`
`Reading package lists... Done`
`Building dependency tree      ` 
`Reading state information... Done`
`Calculating upgrade... Done`
`0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.`
`alex@alex-linux:~$ apt policy pulseeffects`
`pulseeffects:`
`  Installed: 4.5.8-1-git20190326~disco1`
`  Candidate: 4.5.8-1-git20190326~disco1`

**Comment by mikhailnov** [comment]
I've looked once again at your `apt policy pulseeffects` and see that PopOS repo has priority 1001 instead of default 500 of pulseeffects PPA. It means that packages from PopOs repo will always be installed even if there are newer versions in other repos (`man apt_preferences`).

They just copied pulseeffects packages from its ppa to theirs: https://launchpad.net/~system76/+archive/ubuntu/pop/+packages?field.name_filter=pulseeffects&field.status_filter=published&field.series_filter=

Try `grep -inHr 1001 /etc/apt`, it will show where priority 1001 is set, change it to 500, run `sudo apt update; sudo apt dist-upgrade`

**Comment by mikhailnov** [comment]
Or probably it would be better to put priority 1002 for pulseefects PPA alike 1001 for PopOS, because if you decrease 1001 to 500 you will probably loose PopOS's custom builds of kernel, bluez etc, but as you don'y use System76 hardware, I would just decrease 1001 to 500.

**Comment by azsorlex** [comment]
@mikhailnov So I changed the values to 500 (1002 didn't work), and after pulseeffects and some linux kernel stuff got upgraded, and a quick reboot, pulseeffects got updated to 4.6.3, both issues I described earlier got fixed (I was sceptical about the youtube one being fixed), and my system didn't break again. Thanks for all the help!

@wwmm I'll now make a request for the flathub version to be updated. Do you by any chance know where I can go to request the Pop!_Shop version to be updated?

**Comment by mikhailnov** [comment]
It has already been updated in PopOS PPA (25 minutes ago) to 4.6.3

**Comment by azsorlex** [comment]
aaaaaaalrighty then
