### ISSUE TITLE
Only loudness plugin is missing.

### ISSUE THREAD

**Issue by kevinsmia1939** [wwmm/pulseeffects#531]
I got warning 
loudness plugin was not found!

I got all plugins except loudness only.

I believe I install every dependencies.

I use opensuse tumbleweed kde with this repo.
https://build.opensuse.org/project/show/home:drommer:audio:pulseeffects

This is what I have on my system.
gstreamer-plugins-good 
gstreamer-plugins-good 
lsp-plugins          
lsp-plugins-jack   
lsp-plugins-ladspa    
lsp-plugins-lv2    
lsp-plugins-vst     
calf               
lv2-calf           
zam-plugins
mda-lv2
libsamplerate0
libsndfile1
libsndfile1-32bit
libzita-convolver4
libebur128-1

Thanks.

**Comment by wwmm** [comment]
What is the output of the command `gst-inspect-1.0 | grep -i loudness`? It should be something like this `lv2:  drobilla-net-plugins-mda-Loudness: MDA Loudness`. An empty output means GStreamer is not being able to find mda plugins. And as a result PulseEffects won't be able either.

Something you may try is to clear GStreamer cache `rm -rf ~/.cache/gstreamer-1.0` and restart PulseEffects after killing its process `pulseeffects -q`.

**Comment by kevinsmia1939** [comment]
I got nothing from gst-inspect-1.0 | grep -i loudness
Does this suppose to come with the package mda-lv2?

**Comment by wwmm** [comment]
It should have come with mda-lv2. Either this package has a problem or GStreamer cache has to be cleared.

**Comment by kevinsmia1939** [comment]
Pulseeffects dependent package have been added to opensuse official repo, no need for OBS repo, anymore, everything works now.
