### ISSUE TITLE
Asked to reset settings on every startup

### ISSUE THREAD

**Issue by realnc** [wwmm/pulseeffects#532]
Every time I start the application, it asks me (through a KDE Plasma notification) to reset the settings. It happens every time. It doesn't matter if I answer "yes" or "no". In both cases, nothing happens and next time it asks again. This has been happening for many months now, with many versions of PE.

PulseEffects 4.6.3 on Gentoo 64-bit and KDE Plasma 5.16.1.

**Comment by wwmm** [comment]
I wonder if this feature is working as intended only in Gnome. At least I use Gnome and there never was a problem. But it seems that on other desktops something is broken.

I think I will just remove this popup. In the past when I had to do big changes to the presets system this feature made more sense. Nowadays it is not so necessary.

**Comment by realnc** [comment]
It was working fine many months ago. Not sure when it stopped working.

**Comment by wwmm** [comment]
This is normal. Most of the configuration is saved using gsettings. So the `.config` folder is used only for files or things that do not make sense to put in gsettings. You can see our settings in dconf editor
![Screenshot from 2019-06-19 11-43-29](https://user-images.githubusercontent.com/16225172/59775389-828c8c00-9287-11e9-899e-47e02c3ffd97.png)

**Comment by wwmm** [comment]
I released `4.6.4`. The popup was removed.
