### ISSUE TITLE
unhandled exception without pulseaudio in PATH

### ISSUE THREAD

**Issue by Infinisil** [wwmm/pulseeffects#533]
When trying to run pulseeffects in an isolated environment (a systemd service), it throwed this error:
```
(pulseeffects:11143): glibmm-ERROR **: 04:30:30.185:
unhandled exception (type std::exception) in signal handler:
what: execve failed: No such file or directory
```

Reproducible with just
```
PATH="" pulseeffects
```

Explicitly adding pulseaudio to `PATH` makes it work.

I guess it makes sense that this is a dependency, but a better error message and a mention regarding this in some docs might be nice.

**Comment by Infinisil** [comment]
Oh also, this only happens when the GUI is started, no crash with `--gapplication-service` (unless you start the GUI while the service is running)

**Comment by wwmm** [comment]
The error is being produced by glibmm. I have no means to change its message. Only glibmm

**Comment by wwmm** [comment]
Never mind. I think there is something I can do to improve this. This crash is happening when we try to show information about Pulseaudio configuration in the interface. As Pulseaudio does not offer an API for this I had to do a system call to this executable using boost:: process. I imagine that an exception in boost when Pulseaudio exe was not found somehow caused this glibmm exception.

When I have time I will see if boost offers a way to check if it can find the exe before trying to run the commands.

**Comment by wwmm** [comment]
Master branch now handles boost::process exceptions.

**Comment by Infinisil** [comment]
Awesome, thanks!
