### ISSUE TITLE
in linux mint opens and closes soon after

### ISSUE THREAD

**Issue by andrefcorreia** [wwmm/pulseeffects#536]
In the last updates started to give this problem and the sound stops working.
The log is attached s txt. 
[error pe linux mint.txt](https://github.com/wwmm/pulseeffects/files/3322376/error.pe.linux.mint.txt)
Any Help please?

**Comment by wwmm** [comment]
Try to reset PE settings `pulseeffects -r`. There isn't an error in the logs. But the large amount of lines related to attempts to enable/disable plugins is strange.

**Comment by andrefcorreia** [comment]
Ow nice. It worked like a charm
Thank you very much!
