### ISSUE TITLE
Wheezing Noise

### ISSUE THREAD

**Issue by andrefcorreia** [wwmm/pulseeffects#537]
Why am I hearing a noise when the PE is on? Like a "zzzzzz". As if it were a wheezing.
When the PE is off no noise is heard.
This is occurring on the headset with spotify playing music. 
Probably some plugin that I am using wrong.
Any help?

**Comment by wwmm** [comment]
It could be a misconfiguration but I never heard that. Which plugins are enabled? When you disable all of them is there noise?

**Comment by andrefcorreia** [comment]
I researched more and discovered that it could be my headphone.
I'll test more to get a more accurate result.
