### ISSUE TITLE
Pulseeffects wants to be resetted after every reboot

### ISSUE THREAD

**Issue by TimB87** [wwmm/pulseeffects#538]
Hi there,

I created a port for pulseaudio (and some of it's deps) some time ago and still test it - but I haven't got to work around the following:
After every reboot, it asks to be reset after an update (even though it wasn't updated). In addition: I am not able to change any 'effects settings' despite application specific - means I have enabled the equalizer after a reset and I am not able to turn it off after the next reboot for example.

Any idea what makes it that way? What can I provide as additional information? Distribution is CRUX.

Thanks in advance and have a great weekend!

**Comment by wwmm** [comment]
Try to update to the latest PE version. It does not have this popup anymore

**Comment by TimB87** [comment]
True, the popup is gone, still I can not change the settings.
https://i.imgur.com/bWfDpDI.png

**Comment by wwmm** [comment]
Now we have to know if you have all the optional dependencies installed. Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`.

**Comment by TimB87** [comment]
That's weird, it says it can't find the plugins but I do have the deps.
Debug output: http://dpaste.com/0WEME6E

Meson output during build: http://dpaste.com/23QKTF7

**Comment by wwmm** [comment]
Try to remove GStreamer cache `rm -rf ~/.cache/gstreamer-1.0`

**Comment by wwmm** [comment]
If that does not work check if `gst-plugins-bad` was compiled with `lilv`. In case you want the crossfeed `gst-plugins-bad` also has to be compiled with `bs2b` library.

**Comment by TimB87** [comment]
I think that rebuilding `gst-plugins-bad` did the trick for me! I will check a bit - right now I can disable and reenable options even without a reset, which is by far better then before.
Will report back if I find anything - thanks for the help :+1:

**Comment by TimB87** [comment]
Okay, so with the above rebuild of `gst-plugins-bad` I can say (with the three options I use): I can disable and re-enable at will (equalizer and loudness) - but just after killing the daemon once and restarting it will make the limiter not interactable [1].

Looking at the arch package, I see calf is responsible for the limiter? I just assume that it works right since I can enable it after a reset? This is what I used to compile a CRUX package for it: http://sprunge.us/zqDK9V

[1] https://i.imgur.com/idPYB1t.png

**Comment by wwmm** [comment]
`bs2b` is only for the crossfeed. What is the output of `gst-inspect-1.0 | grep -i calf | grep -i limiter`?

**Comment by wwmm** [comment]
When you start PE in debug mode does it say that the limiter was not found? Is there any error?

**Comment by TimB87** [comment]
`gst-inspect-1.0 | grep -i calf | grep -i limiter` does show nothing, indeed.. `gst-plugins-bad` doesn't seem to pick that up.. I'll have a closer look into that port.

It does indeed complain about some stuff, this is the output: http://dpaste.com/1TRCZ13

**Comment by TimB87** [comment]
Alright, so I think it was a problem with my port for `calf` after all, I had to add `--with-lv2-dir` instead of moving it around. Seems like I was mindless! Now it does seem to work the way it's supposed to :smile: :+1: I think this is ready to be closed, I will test my port further and I think I will push it to CRUX contrib repository! Thanks for the help and this software, greatly appreciated!
