### ISSUE TITLE
issue with mic monitor? 

### ISSUE THREAD

**Issue by wilderjds** [wwmm/pulseeffects#54]
Hi, 

 I am running on master [ b04df856618d390d8b33f867b26699b257774aef ] and I get this error

(pulseeffects:3601): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:3601): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:3601): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
12:05:13.228 - PulseEffects - INFO - pulseaudio context started
12:05:13.228 - PulseEffects - INFO - connected to server: unix:/run/user/1000/pulse/native
12:05:13.228 - PulseEffects - INFO - server protocol version: 32
12:05:13.229 - PulseEffects - INFO - pulseaudio version: 10.0
12:05:13.229 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1f.3.analog-stereo
12:05:13.229 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
12:05:13.229 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
12:05:13.229 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
12:05:13.230 - PulseEffects - INFO - default pulseaudio source audio format: s16le
12:05:13.230 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
12:05:13.230 - PulseEffects - INFO - loading Pulseeffects applications sink...
12:05:13.231 - PulseEffects - INFO - sink owner module index: 26
12:05:13.234 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
12:05:13.234 - PulseEffects - INFO - Pulseeffects apps sink index:1
12:05:13.234 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
12:05:13.235 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
12:05:13.236 - PulseEffects - INFO - sink owner module index: 27
12:05:13.236 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
12:05:13.237 - PulseEffects - INFO - Pulseeffects mic sink index:2
12:05:13.237 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
Traceback (most recent call last):
  File "/usr/bin/pulseeffects", line 4, in <module>
    __import__('pkg_resources').run_script('PulseEffects==2.2.1', 'pulseeffects')
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1500, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/EGG-INFO/scripts/pulseeffects", line 6, in <module>
    a = Application()
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/PulseEffects/application.py", line 61, in __init__
    self.sie = SinkInputEffects(self.pm.default_sink_rate)
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/PulseEffects/sink_input_effects.py", line 69, in __init__
    self.pipeline = self.build_pipeline()
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/PulseEffects/sink_input_effects.py", line 124, in build_pipeline
    self.audio_src.set_property('volume', 1.0)
AttributeError: 'NoneType' object has no attribute 'set_property'
(pulseeffects:3601): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:3601): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:3601): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
12:05:13.228 - PulseEffects - INFO - pulseaudio context started
12:05:13.228 - PulseEffects - INFO - connected to server: unix:/run/user/1000/pulse/native
12:05:13.228 - PulseEffects - INFO - server protocol version: 32
12:05:13.229 - PulseEffects - INFO - pulseaudio version: 10.0
12:05:13.229 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1f.3.analog-stereo
12:05:13.229 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
12:05:13.229 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
12:05:13.229 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
12:05:13.230 - PulseEffects - INFO - default pulseaudio source audio format: s16le
12:05:13.230 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
12:05:13.230 - PulseEffects - INFO - loading Pulseeffects applications sink...
12:05:13.231 - PulseEffects - INFO - sink owner module index: 26
12:05:13.234 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
12:05:13.234 - PulseEffects - INFO - Pulseeffects apps sink index:1
12:05:13.234 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
12:05:13.235 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
12:05:13.236 - PulseEffects - INFO - sink owner module index: 27
12:05:13.236 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
12:05:13.237 - PulseEffects - INFO - Pulseeffects mic sink index:2
12:05:13.237 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
Traceback (most recent call last):
  File "/usr/bin/pulseeffects", line 4, in <module>
    __import__('pkg_resources').run_script('PulseEffects==2.2.1', 'pulseeffects')
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1500, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/EGG-INFO/scripts/pulseeffects", line 6, in <module>
    a = Application()
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/PulseEffects/application.py", line 61, in __init__
    self.sie = SinkInputEffects(self.pm.default_sink_rate)
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/PulseEffects/sink_input_effects.py", line 69, in __init__
    self.pipeline = self.build_pipeline()
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/PulseEffects/sink_input_effects.py", line 124, in build_pipeline
    self.audio_src.set_property('volume', 1.0)
AttributeError: 'NoneType' object has no attribute 'set_property'

Any ideas?

**Comment by wwmm** [comment]
hi the errors:

`self.audio_src.set_property('volume', 1.0)`
`AttributeError: 'NoneType' object has no attribute 'set_property'`

are telling that gstreamer could not find the plugin pulsesrc. What is the output of the command `gst-inspect-1.0 | grep -i pulse`? Are you sure that gst-plugins-good is installed?

**Comment by wilderjds** [comment]
I had to install gst-plugins-pulse (on gentoo) to get

gst-inspect-1.0| grep -i pulse                                        
pulseaudio:  pulsesink: PulseAudio Audio Sink
pulseaudio:  pulsesrc: PulseAudio Audio Source
pulseaudio:  pulsedeviceprovider (GstDeviceProviderFactory)

now the error is similar but refers to another object

18:26:19.885 - PulseEffects - INFO - pulseaudio context started
18:26:19.885 - PulseEffects - INFO - connected to server: unix:/run/user/1000/pulse/native
18:26:19.886 - PulseEffects - INFO - server protocol version: 32
18:26:19.887 - PulseEffects - INFO - pulseaudio version: 10.0
18:26:19.887 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1f.3.analog-stereo
18:26:19.887 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
18:26:19.888 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
18:26:19.889 - PulseEffects - INFO - default pulseaudio sink sampling rate: 48000 Hz. We will use the same rate.
18:26:19.890 - PulseEffects - INFO - default pulseaudio source audio format: s16le
18:26:19.890 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
18:26:19.890 - PulseEffects - INFO - loading Pulseeffects applications sink...
18:26:19.891 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
18:26:19.892 - PulseEffects - INFO - Pulseeffects apps sink index:1
18:26:19.892 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
18:26:19.892 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
18:26:19.894 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
18:26:19.894 - PulseEffects - INFO - Pulseeffects mic sink index:2
18:26:19.895 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
Traceback (most recent call last):
  File "/usr/bin/pulseeffects", line 4, in <module>
    __import__('pkg_resources').run_script('PulseEffects==2.2.1', 'pulseeffects')
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1500, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/EGG-INFO/scripts/pulseeffects", line 6, in <module>
    a = Application()
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/PulseEffects/application.py", line 61, in __init__
    self.sie = SinkInputEffects(self.pm.default_sink_rate)
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/PulseEffects/sink_input_effects.py", line 69, in __init__
    self.pipeline = self.build_pipeline()
  File "/usr/lib64/python3.4/site-packages/PulseEffects-2.2.1-py3.4.egg/PulseEffects/sink_input_effects.py", line 179, in build_pipeline
    self.output_limiter.set_property('input-gain', 0)
AttributeError: 'NoneType' object has no attribute 'set_property'

**Comment by wwmm** [comment]
Ok. Now Gstreamer is not finding the swh-plugins. Check if there is a fast lookahead limiter plugin at the output of th command `gst-inspect-1.0 | grep -i ladspa`. You are probably missing the gstreamer package that has support for ladspa plugins

**Comment by wilderjds** [comment]
Ok in order to have the ladspa plugins in gentoo it is a bit more complicated than it should be; now it actually works.
