### ISSUE TITLE
crossfeed plugin was not found

### ISSUE THREAD

**Issue by Vascom** [wwmm/pulseeffects#540]
Need help.
Where should I look for crossfeed plugin?

I mean in what project or plugins-pack.

**Comment by wwmm** [comment]
The situation with the crossfeed plugin is similar to the one with `lilv`. The crossfeed is a built-in plugin in GStreamer that is enabled only when `gst-plugins-bad` is compiled with `bs2b` support.

**Comment by Vascom** [comment]
This?
http://bs2b.sourceforge.net/

**Comment by wwmm** [comment]
Yes.

**Comment by Vascom** [comment]
I will package it next week.
Thanks.

**Comment by Vascom** [comment]
I found that gstreamer already built with bs2b. It in gstreamer1-plugins-bad-free-extras package. I will add it as dependency for pulseeffects package.

Thanks.
