### ISSUE TITLE
sudo apt install pulseeffects in debian 10 buster NOT WORK

### ISSUE THREAD

**Issue by andresgarcia0313** [wwmm/pulseeffects#543]
sudo apt install pulseeffects
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 pulseeffects : Depende: libc6 (>= 2.29) pero 2.28-10 va a ser instalado
                Depende: gstreamer1.0-adapter-pulseeffects pero no va a instalarse
                Recomienda: calf-plugins (>= 0.90.0) pero no va a instalarse
                Recomienda: zam-plugins pero no va a instalarse
                Recomienda: rubberband-ladspa pero no va a instalarse
                Recomienda: mda-lv2 pero no va a instalarse
                Recomienda: lsp-plugins-lv2 pero no va a instalarse o
                            lsp-plugins pero no va a instalarse
                Recomienda: gstreamer1.0-convolver-pulseeffects pero no va a instalarse
                Recomienda: gstreamer1.0-crystalizer-pulseeffects pero no va a instalarse
                Recomienda: gstreamer1.0-autogain-pulseeffects pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.

**Comment by wwmm** [comment]
As far as I can see your system libraries are not new enough. Are you using Ubuntu PPA or something else?

**Comment by wwmm** [comment]
@mikhailnov are the current PPA packages supposed to work in this Debian release?

**Comment by mikhailnov** [comment]
Of course not, they are built on Ubuntu and here @andresgarcia0313 has glibc 2.28 while the package that he is trying to install was built against glibc 2.29, only ubuntu 19.04 and 19.10 have glibc 2.29, try the package from ubuntu 18.04 bionic, but there is no guarantee that it will work, it's better to build and install the package from source: https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source#debian--ubuntu

**Comment by andresgarcia0313** [comment]
thanks for your quick response
I will try to compile at another time
I work with flatpak but it is not optimal; delayed in opening and not working as a service and the download was 1GB
But it has saved my life.

gracias por su pronta respuesta 
Intentare compilar en otro momento
me funciona con flatpak pero no es optimo; demorado en abrir y not trabaja como servicio y la descarga fue de 1gb 
Pero me ha salvado la vida.

**Comment by wwmm** [comment]
It should be possible to run the flatpak package as a service. But you will probably need the workarounds discussed here https://github.com/flathub/com.github.wwmm.pulseeffects/issues/18
