### ISSUE TITLE
minimize to system tray

### ISSUE THREAD

**Issue by andresgarcia0313** [wwmm/pulseeffects#545]
please add the option to minimize to system tray especially for the flatpak package

you are incredible
pulseeffects is a wonder

**Comment by wwmm** [comment]
In a way this is a duplicate of #544. There I explain why it was never implemented.

That being said if all you want is to close the window and having the effects running in background starting PE with `--gapplication-service` is enough. No need for a tray icon.

**Comment by andresgarcia0313** [comment]
Thank you validate the system tray icon in kubutnu lts and what I have tried is spectacular and this super options thank you very much for sharing and I see that you are already achieving that the project in addition to being opensource is profitable for you for which I congratulate you
