### ISSUE TITLE
Pulse Effects has wrong icon in alt+tab menu of KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [wwmm/pulseeffects#546]
Hi
I use pulse effects 4.6.5 on Arch Linux.
This issue affects pulse effects installed from Arch repos and from flathub.

Steps to Reproduce:

    start kde plasma wayland session.
    open pulse effects
    press alt+tab and hold alt key

Actual Results:
The task switcher shows a Wayland generic icon instead of pulse effects icon

Expected Results:
the task switcher shows pulse effects icon

**Comment by wwmm** [comment]
The same actions show no problem in Gnome. I think this is a KDE bug. I have no control of how its task switcher shows our icon.

Maybe KDE is having problems with svg icons. In any case this should be reported to its developers.

**Comment by glaubersm** [comment]
I have reported this isue to KDE devs.
app_id and .desktop file name must match

https://bugs.kde.org/show_bug.cgi?id=409967

**Comment by wwmm** [comment]
I do not understand what he wants. Renaming the file without `.desktop` at the end??? It makes no sense.

Our `.desktop` file is created here https://github.com/wwmm/pulseeffects/blob/98ec74d58cdb7bd8bf29f816b5f6aafe43eafc29/data/meson.build#L63 and is named `com.github.wwmm.pulseeffects.desktop`. Our app_id is set here https://github.com/wwmm/pulseeffects/blob/98ec74d58cdb7bd8bf29f816b5f6aafe43eafc29/src/application.cpp#L11 and is named `com.github.wwmm.pulseeffects`. Honestly I do not see the problem.

**Comment by glaubersm** [comment]
it seems a gtk bug
https://gitlab.gnome.org/GNOME/gtk/issues/2034

**Comment by servimo** [comment]
I have this problem with Xfce running in a X session. It shows no icon in WhiskerMenu and a generic icon in Docky.

**Comment by sispus** [comment]
I have the same problem with Manjaro Xfce.

**Comment by servimo** [comment]
I am on Manjaro too

**Comment by sispus** [comment]
Sorry I have the icon in whisker menu and plank, but have a generic empty icon in alt-tab menu.
