### ISSUE TITLE
[Request]: Enable a choice between "Blacklist" or "Whitelist" in settings.

### ISSUE THREAD

**Issue by tnilzon** [wwmm/pulseeffects#549]
I would like to see an option in the settings to either have a "Blacklist" for applications to exclude from Pulseeffects (as it is implemented now), or to select it as a "Whitelist" for applications to include in Pulseeffects.

In my case I only use Pulseeffects for Spotify, so it would be best for me to select "Whitelist" and add Spotify to that list (instead of using "Blacklist" and having to add all other sound applications than Spotify to that list).

Thanks for a fantastic application, makes wonder to the Linux sound!

**Comment by wwmm** [comment]
We have a blacklist
![Screenshot from 2019-07-27 11-21-34](https://user-images.githubusercontent.com/16225172/61995587-db0e3080-b060-11e9-96aa-e4aef242a9fa.png)
  Let's consider that you want to blacklist `mpv`
![Screenshot from 2019-07-27 11-21-38](https://user-images.githubusercontent.com/16225172/61995594-f11bf100-b060-11e9-9240-de8e65f135d0.png)
 Enter its name as show in the applications section `mpv Media Player`. The next time you open mpv PulseEffects will ignore it.

 I am not sure if a white list is really needed you could disable the `PRocess All Outputs` option in the settings menu
![Screenshot from 2019-07-27 11-22-35](https://user-images.githubusercontent.com/16225172/61995738-bc109e00-b062-11e9-8b9b-2167d169f8da.png)
and use the per app switch to enable effects for spotify.

**Comment by wwmm** [comment]
As Pulseaudio usually remembers the last sink used by the audio app you probably won't need to manually switch spotify on every time you open it. So in the end it would be almost the same as having a whitelist

**Comment by wwmm** [comment]
Oh! I read a little too fast what you wanted XD Anyway the answer above still applies. Alternating between blacklist and a whitelist seems a little redundant when you have a per app switch.

**Comment by tnilzon** [comment]
Hi, thanks for your reply. I am aware of the present "Blacklist". What I was thinking of is a possibility to choose between to use either a "Blacklist" OR a "Whitelist". As in my case I would choose to apply a "Whitelist", and the only application I would add would be Spotify. All other sound applications would then be ignored by Pulseeffects.

No big deal, but I thought it would be nice to have.

**Comment by wwmm** [comment]
Ok :-) Maybe if one day we remove the per app switch a white list would fit better. As long as you do not tell PE to process all apps Spotify will be the only one with effects
