### ISSUE TITLE
Hello Crystallizer not working on 4.6.6 gentoo.

### ISSUE THREAD

**Issue by javashin** [wwmm/pulseeffects#552]
media-sound/pulseeffects-4.6.6::gentoo was built with the following:
USE="bs2b calf mda-lv2 rubberband" ABI_X86="(64)"

**Comment by wwmm** [comment]
THe crystallizer needs the zita convolver. At least on Arch Linux this package is named `zita-convolver`. Did you install the equivalent package on Gentoo?

**Comment by javashin** [comment]
I have That Installed 
[I] media-libs/zita-convolver
     Available versions:  (~)2.0.0-r1 3.1.0 (~)4.0.3(0/4) (~)4.0.3^p[1] {CPU_FLAGS_X86="sse"}
     Installed versions:  4.0.3(0/4)^p[1](10:01:39 AM 06/15/2019)
     Homepage:            https://kokkinizita.linuxaudio.org/linuxaudio
     Description:         C++ library implementing a real-time convolution matrix

**Comment by javashin** [comment]
ok i found something new pulseeffects 

(pulseeffects:83262): pulseeffects-WARNING **: 22:20:10.250: maximizer plugin was not found!

(pulseeffects:83262): pulseeffects-WARNING **: 22:20:11.644: convolver plugin was not found!

(pulseeffects:83262): pulseeffects-WARNING **: 22:20:11.645: crystalizer plugin was not found!

(pulseeffects:83262): pulseeffects-WARNING **: 22:20:11.952: webrtc plugin was not found!

**Comment by javashin** [comment]
ok im recompiling and there is good news meson found 
Library zita-convolver found: YES

**Comment by wwmm** [comment]
Try to remove GStreamer cache `rm -rf ~/.cache/gstreamer-1.0`

**Comment by javashin** [comment]
works now thanks
