### ISSUE TITLE
[Theme] Dark mode "Adwaita-dark" bad contrast and visualizer bars

### ISSUE THREAD

**Issue by Mlocik97-issues** [wwmm/pulseeffects#554]
![Snímka obrazovky z 2019-08-12 21-35-10](https://user-images.githubusercontent.com/31345346/62892678-27d45580-bd49-11e9-9726-c271a1121e3f.png)

can't change back,... in white (Adwaita) mode, I have now dark blue bars instead orange/green/red (based on value).

**Comment by wwmm** [comment]
I am not sure I understand. Do you mean you can not go back to the white theme? Di you disable `Use Dark theme` in the menu?

I have no control over the contrast or anything else in any theme. There is no theme customization in PE. This has to be reported to `Adwaita` developers. Only them can improve this.

**Comment by wwmm** [comment]
When `Use Dark Theme` is changed in the menu all we do is tell GTK to switch between dark and non dark themes
```
settings->bind("use-dark-theme", Gtk::Settings::get_default().get(), "gtk_application_prefer_dark_theme", flag);
```
everything else is done by GTK. Including which dark theme is going to be used.

**Comment by Mlocik97-issues** [comment]
I see, but how I can change it back?
