### ISSUE TITLE
[Feature Request] Reset Integrated value in AutoGain

### ISSUE THREAD

**Issue by Mlocik97-issues** [wwmm/pulseeffects#555]
Create button to reset Integrated value in AutoGain.

it should be fine if user has possibility to reset Integrated value, or set time limit. (For example "last 30 minutes" instead "from start to end").

**Comment by wwmm** [comment]
I wonder if automatically resetting the history when PulseEffects pipeline is paused is enough. I think this would handle most of the cases without the need for manual intervention.

**Comment by wwmm** [comment]
This has a few annoying side effects... I will add a reset button.

**Comment by wwmm** [comment]
Implemented on master branch
![Screenshot from 2019-09-05 15-41-00](https://user-images.githubusercontent.com/16225172/64369953-bd36d280-cff3-11e9-8fc1-84278cef3036.png)
