### ISSUE TITLE
[Feature Request] Reset only one tool/plugin (for example only Compressor settings)

### ISSUE THREAD

**Issue by Mlocik97-issues** [wwmm/pulseeffects#560]
Reset only one tool/plugin (for example only Compressor settings)

it should be fine, if I can reset settings only in one tool/plugin.

**Comment by wwmm** [comment]
One reset button for each plugin will require some work because we have many plugins. So I don't know when I will have time to implement this feature. But one day it will.

While this is not done you can use dconf-editor to view each key default value.

**Comment by wwmm** [comment]
![](trash:///Screenshot%20from%202019-08-22%2011-22-28.png)

**Comment by wwmm** [comment]
![Screenshot from 2019-08-22 11-22-28](https://user-images.githubusercontent.com/16225172/63522870-80d18580-c4cf-11e9-877b-a91bbc7e00f8.png)

**Comment by Digitalone1** [comment]
@Mlocik97-issues @wwmm This has been implemented and can be closed.
