### ISSUE TITLE
[BUG] Short-term value in Autogain

### ISSUE THREAD

**Issue by Mlocik97-issues** [wwmm/pulseeffects#563]
https://youtu.be/dfouO1wbH8Y

When my Momentary value is under -20, then Short-Term value is freezed, when Momentary value again exceed -20, then Short-Term jump to -20, it's fast change in Short-Term value, which cause fast change in output volume. So I must use low Short-Term value to prevent fast changes in volume.
For example https://www.youtube.com/watch?v=1_NTnd4HBLA in 0:25, it change volume so fast... I can hear that change even with 50-30-100 settings (m-s-i)

**Comment by Mlocik97-issues** [comment]
It's happenings with Your settings too (Target -23dB, Weights 1-2-5).

PulseEffects: 4.6.6
Ubuntu: 18.04.3 LTS

**Comment by Mlocik97-issues** [comment]
If I see well, I think https://github.com/wwmm/pulseeffects/commit/68192c1c9cef753fc70ecf30f67076e7236a89e1 I think, silence detect will fix this too. I will wait to time, when update will be published, and confirm it.

**Comment by wwmm** [comment]
It is possible. With silence detection disabled the gain will be updated even if the momentary value is very low.

**Comment by Mlocik97-issues** [comment]
yes, it helped and solved this problem
