### ISSUE TITLE
Block Size position in PE settings

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#570]
I think Block Size form option in settings is not centered.

![Screenshot_20190913_092349](https://user-images.githubusercontent.com/25790525/64844622-963a5b00-d608-11e9-8511-d952e30f2e05.png)

**Comment by wwmm** [comment]
Thanks! I did not pay attention to that when I moved the labesl to the new position. It should be ok now.

**Comment by Digitalone1** [comment]
That's okay now. But I think it's even better if you specify unit measure too. 512 KB, 1 MB, 2MB, etc.

**Comment by wwmm** [comment]
It could be done but the block size in MB isn't really important. The only reason why we have to force a block size is to ensure that each channel in the audio buffer array has a number of components that follows a power of 2. Plugins based on the library zita-convolver needs that. 

In case you want to calculate the total buffer size you have to do `blocksize * 2 * sizeof(float)`. The blocksize value in the menu is just the number of components in one channel.
