### ISSUE TITLE
[BUG] MIC WebRTC freeze "Spectrum"

### ISSUE THREAD

**Issue by Mlocik97-issues** [wwmm/pulseeffects#575]
When I active WebRTC, it freeze "Spectrum", in output it writing values "0 1" and it seems like mic doesn't react on my voice.

**Comment by wwmm** [comment]
Which blocksize are you using? I think that this plugin does not work with values below 512.

**Comment by Mlocik97-issues** [comment]
Oh, I was using default (512), I will try to increase it to 2048

**Comment by Mlocik97-issues** [comment]
With 4096 blocksize it's working.

**Comment by wwmm** [comment]
Weird. Last time I tried 512 worked. I will try to take a look at it again when I have time.

**Comment by Danacus** [comment]
I had the same problem, block size 512 usually does not work (although it did work once). Increasing the block size fixes this problem for me.
