### ISSUE TITLE
All effects greyed out / disabled

### ISSUE THREAD

**Issue by tannercollin** [wwmm/pulseeffects#577]
Hi, I installed pulseeffects with `sudo apt install pulseeffects` on Debian Sid and when I run it, all the effects are greyed out / disabled:

![Screenshot from 2019-09-26 17-59-01](https://user-images.githubusercontent.com/6752449/65732536-a3832b00-e087-11e9-8f5d-3029458a20b9.png)

Here's it running with debug enabled: https://txt.t0.vc/NLES

It also installed these packages: `calf-plugins gir1.2-gst-plugins-bad-1.0 gir1.2-gst-plugins-base-1.0 gir1.2-gstreamer-1.0 gstreamer1.0-adapter-pulseeffects gstreamer1.0-autogain-pulseeffects
  gstreamer1.0-convolver-pulseeffects gstreamer1.0-crystalizer-pulseeffects gstreamer1.0-plugins-bad libc-bin libc-dev-bin libc-l10n libc6 libc6-dev libebur128-1
  libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libilmbase24 libopenexr24 libsrt1 libx265-176 libzita-convolver3 locales mda-lv2 rubberband-ladspa
  zam-plugins`

**Comment by wwmm** [comment]
You also need the Linux Studio Plugins for the `equalizer`, `delay` and `compressor` to work. At least on Arch Linux the package is called `lsp-plugins`.

It may also be worth to remove GStreamer cache `rm -rf ~/.cache/gstreamer-1.0` and restarting PulseEffects.

**Comment by tannercollin** [comment]
Which Linux Studio Plugins version does PulseEffects require?

![Screenshot from 2019-09-26 19-56-41](https://user-images.githubusercontent.com/6752449/65736340-dfbe8780-e097-11e9-8b97-6c0260a16dc8.png)

**Comment by wwmm** [comment]
You need its LV2 libraries. This is how the Arch Linux package is built https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/lsp-plugins

**Comment by tannercollin** [comment]
Downloading lsp-plugins-lv2-1.1.10-Linux-x86_64.tar.gz and installing with `sudo mv lsp-plugins.lv2/ /usr/lib/lv2/` worked! Thanks for the help.

I'd like to suggest an error / warning to the user instead of making the toggle slider do nothing :)
