### ISSUE TITLE
Crackling on Audio Play/Stop/Change

### ISSUE THREAD

**Issue by Utini2000** [wwmm/pulseeffects#580]
Hello again,
I know that this is supposed to be fixed and I can confirm that it has gotten better, but I still have this issue quite frequently.

/etc/pulse/daemon.conf: https://psty.io/p?q=1a0f
/home/user/.config/pulse/daemon.conf: https://psty.io/p?q=a184

DAC: Meier Audio Daccord FF via USB 3.0
Amp: Meier Audio Corda Classic FF
Headphones: Sennheiser HD800S
OS: Archlinux
Pulseaudio: 13.0-2
Pulseeffects: 4.6.7-1
Laptop: Thinkpad X1 Extreme 

So with MPD + Cantata I only seem to get the crackling once when initially starting the first playback. After that it works fine for all songs, play and pauses.
However, when starting a youtube video I get the crackling again.
Also I currently have a bluray played in mpv where I get the cracking whenever I stop/start the playback.

What I notice when the cracking happens is that my DAC shortly flashes the LED for "44kHz" but then instantly goes back to 48kHz. 

Is there anything else I can provide? Any log files?

**Comment by wwmm** [comment]
If this happens when starting a playback the source of the noise could be Pulseaudio suspending the sink when it is idle. At least on my soundcard this causes cracklings. Copy the file `/etc/pulse/default.pa` to `~/.config/pulse`, open `~/.config/pulse/default.pa` in a editor and remove the line `load-module module-suspend-on-idle`. For now this is the only thing that comes to my mind.

**Comment by Digitalone1** [comment]
I'm not having this issue on my system anymore.

But, if the sample rate changes, I think it's something related to the suspend as stated by @wwmm.

**Comment by Utini2000** [comment]
I already had the module loaded. How ever, I now also set "avoid-resampling = true" and the issue seems now to be fixed :)

**Comment by milosb793** [comment]
> I already had the module loaded. How ever, I now also set "avoid-resampling = true" and the issue seems to be fixed now :)

Hey, is this setting located within `default.pa` file or?

**Comment by wwmm** [comment]
You have to put it in the file `daemon.conf`

**Comment by ranolfi** [comment]
Look up https://www.google.com/search?q=speech+dispatcher+crackling+sound and see whether it applies to your case ;)
