### ISSUE TITLE
Process remains active when closing PulseEffects

### ISSUE THREAD

**Issue by testsieger73** [wwmm/pulseeffects#582]
Hi,
I am using PulseEffects with Manjaro Gnome stable. When closing PulseEffects, the process (and all activated effects) remain active. Shouldn't closing the app trigger the process to be terminated?

**Comment by wwmm** [comment]
No. When you close the window PE will keep running as a service in the background. This is the behavior that most of users asked for. Unless something weird is happening no CPU power will be wasted. PE detects when there is no audio app running and pauses its pipeline accordingly. PE cpu usage should be zero in this case.

**Comment by testsieger73** [comment]
Thanks. My issue is not CPU usage. My issue is that the only way to go back to plain sound is either reopening the app and deactivating effects or killing the process manually. This could be improved imo, e.g. by placing an icon in the taskbar.

**Comment by wwmm** [comment]
You could try to disable `Process All Outputs`
![Screenshot from 2019-10-06 13-25-04](https://user-images.githubusercontent.com/16225172/66272179-babad900-e83c-11e9-99e6-38c40eed1825.png)
This way PE will not automatically enable effects for applications. You will have to do that yourself using the corresponding switch.

**Comment by testsieger73** [comment]
That works for me, thanks!
