### ISSUE TITLE
pulseeffects -p  opens GUI

### ISSUE THREAD

**Issue by boomshop** [wwmm/pulseeffects#591]
Hey Wellington,

4.6.9 already made it into Debian sid, so pulseeffectstray is taking care of it now.

Apart from that I encountered something I'd assume is not intentional: `pulseeffects -p` opens the GTK window, but works well otherwise.

Cheers
Markus

**Comment by wwmm** [comment]
Thanks! Only now I saw this. It seems I forgot to add an additional `return EXIT_SUCCESS` to the `int Application::on_handle_local_options` method.

**Comment by boomshop** [comment]
Hope it was no biggie, thanks for taking care of it!

**Comment by wwmm** [comment]
Adding the return fixed it. Code on master branch updated. At least here on my PC the window does not open anymore.

**Comment by boomshop** [comment]
Awesome, thanks a bunch!
