### ISSUE TITLE
Question: how do I stop pulseffect?

### ISSUE THREAD

**Issue by kubrickfr** [wwmm/pulseeffects#592]
Pulseeffect is great and I like it when listening to music, but it introduces latency and uses CPU that I don't want to "pay" for it all the time.
How do I stop pulseeffect?

**Comment by wwmm** [comment]
You could run `pulseeffects -q`. But have in mind that this will kill PE process. In case you want to keep PE alive but just want to use it with music you could disable the option `Process All Outputs` in the settings menu and use the application switch to enable effects only to the apps you want.
