### ISSUE TITLE
How to fix latency, popping and Pulse Effects crashing when I change the priority in the app

### ISSUE THREAD

**Issue by gitnameR** [wwmm/pulseeffects#595]
New Linux user. Downloaded Pulse Effects from flathub and pretty much all settings are in default.

Pulse Effects says the latency is at 125ms which is way too high for me and the audio pops and crackles every 40 seconds or so. Pulse Effects also crashes whenever I change the priority type in the app. Sorry if this is a dumb question, but how do I fix these? Other than that, love Pulse Effects.

**Comment by gitnameR** [comment]
![Screenshot from 2019-12-17 18-58-41](https://user-images.githubusercontent.com/58980776/70997481-66b35700-20ff-11ea-993d-1a76b9311ba8.png)

Don't know if this will be helpful but here's the audio chain

**Comment by wwmm** [comment]
It is not possible to change priority When installing PulseEffects through flatpak https://github.com/wwmm/pulseeffects/issues/445. This works only in a native package. But as far as I remember it also should not crash...

Pops and cracklings are usually related to problems in Pulseaudio or in the sound card driver. PE effects just make them more noticeable. In case you are using a Pulseaudio that is older than 13 changing volumes could also cause cracklings.

Latencies can be tweaked in PE menu
![Screenshot from 2019-12-17 10-04-28](https://user-images.githubusercontent.com/16225172/70998155-655d3c80-20b5-11ea-85e6-e45a8333c80d.png)

Try to play a little with the buffer and latency parameter sizes. But have in mind that lower latencies put more pressure in Pulseaudio and its cpu usage will increase.

Latency can also be considerably reduced by a clever tweak in Pulseaudio settings http://juho.tykkala.fi/Pulseaudio-and-latency. Here there is also related useful info https://github.com/wwmm/pulseeffects/issues/568

**Comment by gitnameR** [comment]
> It is not possible to change priority when installing PulseEffects through flatpak #445. This works only in a native package. But as far as I remember it also should not crash...
> 
> Pops and cracklings are usually related to problems in Pulseaudio or in the sound card driver. PE effects just make them more noticeable. In case you are using a Pulseaudio that is older than 13 changing volumes could also cause cracklings.
> 
> Latencies can be tweaked in PE menu
> ![Screenshot from 2019-12-17 10-04-28](https://user-images.githubusercontent.com/16225172/70998155-655d3c80-20b5-11ea-85e6-e45a8333c80d.png)
> 
> Try to play a little with the buffer and latency parameter sizes. But have in mind that lower latencies put more pressure in Pulseaudio and its cpu usage will increase.
> 
> Latency can also be considerably reduced by a clever tweak in Pulseaudio settings http://juho.tykkala.fi/Pulseaudio-and-latency. Here there is also related useful info #568

Thank you for this! I've managed to substantially decrease the latency but I guess I need to increase the fragment size more since the popping is still noticeable. And yes, the Flatpak app does crash when I change the priority. Zorin OS 15.1 Ubuntu LTS 18.04. By the way, I tried installing Pulse Effects through the readme.md but nothing seemed to happen. Do I need to uninstall the Flatpak app first before installing through the package?

**Comment by wwmm** [comment]
I never used Flatpak. But I think that its install is completely isolated in its sandbox. Maybe you could try to use a PPA. But people on Ubuntu 18 have had problems with it https://github.com/wwmm/pulseeffects/issues/551

**Comment by Snaggly** [comment]
I managed to fix this on my Pop!_OS by updating PulseAudio to v13 and PulseEffects to 4.7.2. At Synaptic Package Manager I disabled System76's Pop PPA to get the later updates from Ubuntu, and only upgraded PulseAudio, PulseEffects and GStreamer. After I restarted I reenabled Pop's PPA. Dunno if this is the right thing to do but it worked for me...
