### ISSUE TITLE
Pulseeffects - Czech localization file

### ISSUE THREAD

**Issue by pafri** [wwmm/pulseeffects#6]
Here is the Czech .po localization file (code cs). Please commit it.

Best regards from **Moravia**.

[pulseeffects_cs.tar.gz](https://github.com/wwmm/pulseeffects/files/935186/pulseeffects_cs.tar.gz)

**Comment by wwmm** [comment]
Hi

Added Czech localization to the latest version (1.1.6). I did a test here running "LC_ALL=cs_CZ.utf-8 pulseeffects" and it seams to be ok. Let me know if there is any problem.

Thanks for the translation :-)
