### ISSUE TITLE
Missing Gain Reduction and Output Level on Maximizer Plugin

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#602]
Hello @wwmm and happy new year. 

I talked about that months ago in a previous closed issue, but it was out of topic and forgot to open a new issue on this subject. As you can see in its [source code](https://github.com/zamaudio/zam-plugins/blob/af338057e42dd5d07cba1889bfc74eda517c6147/plugins/ZaMaximX2/ZaMaximX2Plugin.cpp#L34), Maximizer plugin has two other parameters not exposed inside PulseEffects: **Gain Reduction** and **Output Level**.

I don't know how they work, maybe the first lowers the input level and the second one acts like a makeup parameter on the output signal like in compressors. It would be interesting to test.

Can you add them in the next release? Thanks.

**Comment by wwmm** [comment]
Happy new year, @Digitalone1! :D

It is no visible in this part of the maximizer code but these parameters are readonly. Just take a look at the output of `gst-inspect-1.0 ladspa-zamaximx2-ladspa-so-zamaximx2`. Their values are already shown in the interface. So there is nothing more that can be done.

**Comment by Digitalone1** [comment]
Didn't know that. So that's okay. :)
