### ISSUE TITLE
Add ability to turn on / turn off pulseeffects equalizer profile from command line

### ISSUE THREAD

**Issue by xPrzybyLx** [wwmm/pulseeffects#607]
Please correct me if I am wrong but I can't find a way to turn on / turn off pulseeffects equalizer profile from command line (I know I can load selected profile via command line).

I can only turn on / turn off via GUI by clicking the "toggle" control above the equalizer bands...

**Comment by wwmm** [comment]
It depends on what you mean by turn a profile on/off. If make two user presets where in one of them the equalizer is disabled you can turn on/off the equalizer by switching between these presets.

Latest PE versions also have a `bypass` command line option. But it will bypass all effects. If the equalizer is the only plugin being used the end result will be the same.

If none of this is enough there is a third option. Use `dconf` to run the equalizer on/off:
```
dconf write /com/github/wwmm/pulseeffects/sinkinputs/equalizer/state true
dconf write /com/github/wwmm/pulseeffects/sinkinputs/equalizer/state false
```

I think there is no need to add a command line option only to disable the equalizer.

**Comment by wwmm** [comment]
`pulseeffects -b 1` to enable the global bypass `pulseeffects -b 2` to disable it.

**Comment by xPrzybyLx** [comment]
The `dconf` option is exactly what I was looking for ! Thank You !
