### ISSUE TITLE
POT file is missing a lot of strings

### ISSUE THREAD

**Issue by AsavarTzeth** [wwmm/pulseeffects#61]
If you update your translation from the current POT file [`pulseeffects.pot`](https://github.com/wwmm/pulseeffects/blob/master/po/pulseeffects.pot) in master it will disable a lot of your strings.

The result is that PulseEffects won't use all of the localized strings.

Best guess is that something must have gone wrong when it was regenerated. Presumably related to he new tooling.

**Comment by wwmm** [comment]
Is there non translated strings in PulseEffects interface?

When I added localization support I followed a tutorial that for some reason used the option -a in xgettext. Now that a few strings that were in glade files are in python files I understand that this option adds all strings to the template. Even the ones not marked for translations. So I stopped using the -a option.

**Comment by AsavarTzeth** [comment]
Not currently, but if you update any of the current translations against the current POT file there will be a lot of lines unused. It is quite obvious that strings are missing if you check the mentioned file.

**Comment by AsavarTzeth** [comment]
Oh I see you have started using `gettext` directly in some of your files. Hmm, some of those parts might need to be rethought (currently redundant), now that #62 fixes a much broader issue.

**Comment by AsavarTzeth** [comment]
Well I have one theory. `gettext` is pure python, but glade as I understand it is connected to a c library. Because of this you may have to `locale` module instead of, or in addition to, the `gettext` module.

At least that is what I had to do to get things working with a different locale directory than the default `/usr/share/locale`. If I only used the `gettext` module only a few strings were actually translated when I ran the app.

**Comment by AsavarTzeth** [comment]
I also see all strings related to the appdata and desktop entry file is missing. I am surprised you pushed 023a63011f1d42b67f8d8aedea28baa03f7e65f6 to be honest.

**Comment by wwmm** [comment]
I forgot to use ninja to update the template sorry :(

The only strings moved to python files were the name of each effect in the main ui tabs at the left side. All the others are on glade files and I do not see a reason to not do so. 

I had to move these strings because I am not putting all effects interface controls at the same file anymore. Each tab(effect) has its on glade file and I am inserting each tab interface from python. That is why these strings have to be there now.

**Comment by AsavarTzeth** [comment]
Well I found the main issue. When you move the strings from the glade files you removed the glade files from the `po/POTFILES.po` file. The issue is you did not move all the strings so you effectively removed some of them from the translation all together.

**Comment by AsavarTzeth** [comment]
As part of my testing for 3.0.0 I updated sv.po against pulseeffects.po. I can happily report that no strings were disabled. I also cannot see anything that is not localized when I run it.

So I would consider this solved at this time.
