### ISSUE TITLE
How to totaly delete

### ISSUE THREAD

**Issue by Errahydro** [wwmm/pulseeffects#610]
Hello there,
I'm completely new to linux, i use eOS and i instaled PulseEffets from FlatHub.

I clicked "instal"
![Capture d'écran du 2020-01-11 21 12 16](https://user-images.githubusercontent.com/59776975/72210143-0f629580-34b7-11ea-977f-4bc3270bdba8.png)

And i don't know how to completely remove it.

Regards

**Comment by wwmm** [comment]
I do not use flatpak or flathub. So I can't really guide you. But take a look at this Arch Linux tutorial https://wiki.archlinux.org/index.php/Flatpak#List_installed_runtimes_and_applications. It may help you to remove it.
