### ISSUE TITLE
Minor, global defeat flag on start up

### ISSUE THREAD

**Issue by Befo** [wwmm/pulseeffects#612]
Hi, I have found likely a minor bug, more annoying than an actual bug. I am on Debian 10 testing (bullseye) and at the boot pulseeffects shows the global defeat activated like I left it at shutdown but it is not actually defeated. I need to disable the defeat flag and enable it again for it to actually work.

**Comment by wwmm** [comment]
I imagine you are talking about the global bypass. I took a look at it and it is not being applied after a restart indeed. Thanks for noticing this. I will see what is going on.

**Comment by wwmm** [comment]
I released PE 4.7.1 with a fix for this.

**Comment by Befo** [comment]
Perfect, thank you man. Great software.
