### ISSUE TITLE
"Impulse File"

### ISSUE THREAD

**Issue by magicgoose** [wwmm/pulseeffects#613]
.wav file extension should be accepted for an impulse file.  
If that's impossible, then at least it should be noted somewhere in UI how exactly it wants you to rename your files.  
(it is not shown in file picker and you have to guess or search the web)

**Comment by dotWAVE** [comment]
It seems you can import wave files if you rename them from .wav to .irs

**Comment by magicgoose** [comment]
that's right, but it's a totally unnecessary action and it's also not
indicated anywhere in UI. each time you forget it, you'll need to search
the web, that's bad design.

**Comment by wwmm** [comment]
Well... At the time I wrote the convolver plugin all the impulse files I could find were from the Android community that for some reason renames the wav files to irs. In any case it is not that hard to support wav. Just a matter of adding it to the dialog file type filter here https://github.com/wwmm/pulseeffects/blob/38355f5966f978882d329000c77a859320b63de8/src/convolver_ui.cpp#L241. It is also necessary to make this function https://github.com/wwmm/pulseeffects/blob/38355f5966f978882d329000c77a859320b63de8/src/convolver_ui.cpp#L141 to rename wav files to irs when moving them to PE irs folder. As always patches are welcome.

**Comment by magicgoose** [comment]
I can try it some time soon.

**Comment by wwmm** [comment]
Implemented in the master branch.
