### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [wwmm/pulseeffects#614]
I would like to point out that an identifier like “[`_GstPeadapter`](https://github.com/wwmm/pulseeffects/blob/8e853108b3bdb0e61bc1ea13a0c6dc907ef4fcce/src/adapter/gstpeadapter.hpp#L15 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by wwmm** [comment]
I don't see a problem in changing them. Specially if it is against the C++ convention. I had no idea :-). At the time I was following GStreamer examples and focusing on making the plugin working. I did not try to see if GStreamer requires those structures to be named this way or not. Considering it accepts plugins written in c++ it should be ok to rename these srtuctures.

**Comment by wwmm** [comment]
Done

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/wwmm/pulseeffects/commit/d8e6aee0575274c82d9640b9374cdec997ed09c0 "Renaming of a few identifiers").
