### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [wwmm/pulseeffects#615]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Filter::create_lowpass_kernel](https://github.com/wwmm/pulseeffects/blob/8e853108b3bdb0e61bc1ea13a0c6dc907ef4fcce/src/crystalizer/filter.cpp#L28 "Filter::create_lowpass_kernel function")
- [gst_peconvolver_finish_convolver](https://github.com/wwmm/pulseeffects/blob/8e853108b3bdb0e61bc1ea13a0c6dc907ef4fcce/src/convolver/gstpeconvolver.cpp#L418 "gst_peconvolver_finish_convolver function")

**Comment by wwmm** [comment]
Ok

**Comment by wwmm** [comment]
Done.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/wwmm/pulseeffects/commit/5b40534d67df3afde396e849c2c86caea5aeba0e "Deletion of two unnecessary checks").
