### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [wwmm/pulseeffects#616]
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [Filter::create_bandpass_kernel()](https://github.com/wwmm/pulseeffects/blob/8e853108b3bdb0e61bc1ea13a0c6dc907ef4fcce/src/crystalizer/filter.cpp#L63)
- [read_file()](https://github.com/wwmm/pulseeffects/blob/8e853108b3bdb0e61bc1ea13a0c6dc907ef4fcce/src/convolver/read_kernel.hpp#L93)

**Comment by wwmm** [comment]
Ok

**Comment by wwmm** [comment]
Done. I am using std::vector now.

**Comment by elfring** [comment]
Thanks for your small source code improvement.
* [filter.cpp](https://github.com/wwmm/pulseeffects/commit/fb20bfb88a19fee21c5735d05a2ef80806e6f0f6 "Using std::vector in crystalizer filter")
* [read_kernel.hpp](https://github.com/wwmm/pulseeffects/commits/f21955468ec569b9ce01591c183f4028053a7727/src/convolver/read_kernel.hpp "Using std::vector in read_kernel.hpp")
