### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [wwmm/pulseeffects#618]
I expect that exception handling is usually supported by a C++ program. I wonder why your function “[main](https://github.com/wwmm/pulseeffects/blob/b0c52fa2f52c8a22b3b61be3cc47950afaa6efaf/src/pulseeffects.cpp#L18 "main() function")” does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](https://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling")?

**Comment by wwmm** [comment]
Mostly for 2 reasons. I never studied exceptions as much as I should. So I did not even think about them XD. The other reason is that learning digital signal processing and GStreamer's dynamic pipeline while writing the code really takes away our focus from this kind of thing. And whenever a feature was ready more cool features were suggested. In the end I forgot to think about error handling. I am glad there is someone looking at this now :-).

Just like the other suggestions I do not see a problem in doing it.

**Comment by wwmm** [comment]
Done. Let me know if there is something more that should be there.

**Comment by elfring** [comment]
I suggest to take another look at linked information sources.
Would you like to add a catch-all-clause?
