### ISSUE TITLE
No sound coming out, no input on Pulseeffects either.

### ISSUE THREAD

**Issue by CCaroV** [wwmm/pulseeffects#619]
Hello

I'm running Pulseeffects 4.7.1 on ElementaryOS, it was working fine until I had to change the output on pavucontrol for a Surround 5.1 HDMI (ElementaryOS does not support it on the main settings). I don't remember changing anything else and for some reason everything stop working. Now Pulseeffects doesn't receive any input from any app. 

I changed the main output to the speakers and my headphones and still the same problem.

![imagen](https://user-images.githubusercontent.com/51457651/72853522-a087f800-3c7f-11ea-8609-9ad78e02c374.png)

(Photo above was taken while Spotify was playing music)

Please let me know if you need any other information.

**Comment by wwmm** [comment]
What do you have on the `Grabacion` tab? PE stream should be recording from `PulseEffects(apps)` monitor. Maybe something moved it to another device.

**Comment by CCaroV** [comment]
Yep, the problem was there. Maybe I silenced Pulseeffects on `Grabación` by mistake when I was trying to setup the Surround speakers. After I disabled the silence option everything was working perfect again.

Thanks for your help!

**Comment by wwmm** [comment]
In the past I had a problem where a Feral Game was muting PE sink.  I think it was the latest Tomb Raider. I wish Pulseaudio offered a way to forbid this kind of change to our virtual sinks.
