### ISSUE TITLE
How to save and restore custom presets?

### ISSUE THREAD

**Issue by ratcheer** [wwmm/pulseeffects#624]
I have a custom equalizer curve for my specific headphones, and I created that curve as nearly as I could in the pulseeffects equalizer. It sounded great. Then, I clicked on the Presets button at the top right, gave a name matching my headphones model, added it, and clicked the button that says "Save current settings to this presets file". This all seemed pretty straightforward.

So, to test it, I closed pulseeffects, reopened it, and clicked on the Presets button, then clicked on my named preset, and clicked on the Apply button. But all the equalizer settings remain flat. Did I do this wrong, or is it a bug?

This is on Arch Linux. I installed pulseeffects from the Arch repository.

Also, is there a complete guide to using pulseeffects anywhere?

**Comment by wwmm** [comment]
Strange. Here on my computer the equalizer sliders change when I apply a preset. Maybe it is a bug triggered by something very specific. Kill the current PulseEffects instance with the command `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. This will print lots of things in the terminal and should help to find out what is going wrong.

It is also worth to see if a preset file was actually created in the directory `~/.config/PulseEffects/output/`

If you press the key `F1` or click in the help button next to the preset menu a manual will be opened. But it mostly tells what each control does. Up to now there is only one tutorial.

**Comment by wwmm** [comment]
It is also important to know how PulseEffects was installed. Did you use a Flatpak package or the native package (deb, rpm, etc)?

**Comment by ratcheer** [comment]
pulseeffects was installed from the Arch repository (native package). It is version 4.7.1-2 dated Jan-28-2020.

The preset file is stored at /home/tim/XDG_CONFIG/PulseEffects/output/GS1000e.json

Debug output:

[debug.txt](https://github.com/wwmm/pulseeffects/files/4161486/debug.txt)

**Comment by ratcheer** [comment]
PS - Here is the preset file. I had to copy it to a .txt file so GitHub would let me upload it:

[GS1000e.txt](https://github.com/wwmm/pulseeffects/files/4161512/GS1000e.txt)

**Comment by wwmm** [comment]
Nothing strange in the log. The preset file is loaded `presets_manager: loaded preset: /home/tim/XDG_CONFIG/PulseEffects/output/GS1000e.json`. The preset file also looks normal. The only thing unusual is that the equalizer is disabled `"state": "false"`. `state` should be set to true. Usually this happen when the preset file is saved while the preset switch in the interface is disabled.

When you said `But all the equalizer settings remain flat` did you mean that each band slider remained at `0 dB` or that there was no movement?  As PE remembers the last settings you would see movement in the sliders only when different settings were applied before loading the preset.

**Comment by ratcheer** [comment]
Yes, I meant they all remained at 0. When I created the preset file, I had been fumbling around to figure out how to do so. Maybe I had disabled the equalizer before I did that, but I don't think so. Anyway, I'm going to try to re-create my equalizer settings from scratch, save them, and restart and restore them. I'll let you know how it comes out.

Thanks for your help.

**Comment by ratcheer** [comment]
It still does the same thing. I am 100% certain that this time the equalizer was still enabled when I saved the settings. Then I exited pulseeffects, restarted it, and the equalizer was disabled. Then, I clicked the Presets button and clicked Apply. The equalizer was still disabled and all settings were still at 0 dB.

Also, I verified that the preset file was re-written when I saved it, this time (going by the file's timestamp.

**Comment by wwmm** [comment]
I looked at your preset again and all band gains are set to zero. This explains why they did not move. The question now is why the custom gain values were not saved.

Just to make things clear did you configured the equalizer for output effects or the equalizer for input(microphone) effects. Could you upload screenshots of the PulseEffects window showing in which section the settings were made? A screenshot of the presets menu showing your preset could also help

**Comment by ratcheer** [comment]
I configured it for output effects. I definitely had several frequencies either boosted or cut and I had the equalizer enabled. I could hear a distinct difference in my output. Then, I clicked the Preset button, my preset file is already selected, and I clicked the button that the tool tip says "Save current settings to this preset file". Then I exited pulseeffects, then I restarted it.

It seems to load the Preset file, as it shows when I click the Presets button. But the equalizer comes up disabled and the frequency bands are all at 0 dB. Clicking the Apply button in Presets does not change anything.

**Comment by ratcheer** [comment]
![2020-02-05-165851_1920x1080_scrot](https://user-images.githubusercontent.com/1566160/73891045-f1c7e800-4838-11ea-92e3-68a2129d29d1.png)

**Comment by wwmm** [comment]
That is strange. When a plugin is enabled it should show a `checkbox` sign next to its name in the left panel as it can be seen in this image
![Screenshot from 2020-02-05 20-01-51](https://user-images.githubusercontent.com/16225172/73891211-812dc500-4852-11ea-91a1-5095864c3363.png)

Considering that I also use Arch Linux and everything is fine I am starting to suspect that something may be broken in one of the GTK libraries in your system. I noticed that your configuration folder is `XDG_CONFIG` instead of the usual `.config`. Is there any kind of unusual configuration in your system? Which desktop do you use?

No error was shown in our logs but it seems that GTK GSettings infrasctructure is not working in your computer for some reason.

**Comment by wwmm** [comment]
Install the package `dconf-editor`
![Screenshot from 2020-02-05 20-08-59](https://user-images.githubusercontent.com/16225172/73891642-70318380-4853-11ea-97b6-090bdd0c4cd6.png)
and try to change our parameters through it while PulseEffects window is open. Do you see PulseEffects interface be automatically updated when you change settings in dconf editor? If not there is a problem in one of the GTK libraries.

**Comment by ratcheer** [comment]
I'll try to answer all of that.

I also had noticed no checkmark showing, but since the equalizer is definitely working, I didn't pay much attention to it.

A few years ago, I followed some guidelines to configure and use XDG_CONFIG. It apparently works, as your software and several other packages use it. Others that use it without problems include chromium, darktable, openbox, spotify, and vlc. My desktop is Openbox.

I installed dconf-editor. I ran it and searched for "equalizer". I clicked "input gain" and unselected "Use default value". I typed value "-8.0". When I clicked the return key, the pulseeffects editor did not change, the value in dconf-editor reverted to 0, and "Use default value" reverted to selected.

Again, thank you very much for helping me.

**Comment by wwmm** [comment]
Something is definitely broken in the GSettings infrastructure. The value in PulseEffects interface should have been updated after hitting `enter` or clicking `appliy`. I have no idea if this is being caused by the custom `XDG_CONFIG`. Maybe GSettings needs some kind of custom configuration when used under Openbox. Or maybe it is just a missing package from the GTK/Glib ecosystem that is not being installed when using Openbox. As I use Gnome I don't know what it could be.

**Comment by wwmm** [comment]
Try to repeat the test in dconf-editor but looking at the system logs through `journalctl -fb`. Tun it as root. Maybe this time an error message related to gsettings/dconf will be shown.

**Comment by wwmm** [comment]
Maybe this is related https://askubuntu.com/questions/391465/how-to-start-dconf-and-gconf-in-a-non-gnome-environment

**Comment by ratcheer** [comment]
I cannot even change it directly with gsettings: "gsettings set com.github.wwmm.pulseeffects.sourceoutputs.equalizer input-gain -8.0". There is no error, but no change.

I am looking at your link...

**Comment by ratcheer** [comment]
All I see in the answer is to "export DE=gnome" and "export DESKTOP_SESSION=gnome" before starting dconf-editor. This did not help. Maybe I'm missing something.

Would it help to export those before starting pulseeffects? I'm trying it...

**Comment by wwmm** [comment]
If starting the service did not help I doubt the environment variables will make much difference.

It is almost like you do not have permission to write to the gsettings database. But I do not know what could cause this. Maybe you could create a new user and test if in its account you can change the key values.

**Comment by ratcheer** [comment]
Ok, I'll try with a new user. This might take a few minutes...

**Comment by ratcheer** [comment]
Ok, that was successful. I created a new user and ran pulseeffects under it. I enabled the equalizer and changed a few settings. I saved them to a preset file, exited the application, and restarted it. The settings were restored, properly.

I'm not sure how I'm going to handle this, because I have literally hundreds of things set up under my original user. So, I need to get that user fixed. But pulseeffects is evidently not the problem.

Please let me know if you want me to close this issue. And, thank you very much!

**Comment by wwmm** [comment]
Usually when this kind of thing happens the problem is in the config folder. `XDG_CONFIG` in your case. Try to move a few of the directories and files to a backup place and see what happens. I doubt it is necessary to remove all configurations.
