### ISSUE TITLE
[Feature Request] Add ability to blacklist active streams

### ISSUE THREAD

**Issue by SGOrava** [wwmm/pulseeffects#626]
When adding something to blacklist one has to write full name (or maybe some wildcard would work?) which is tiring.
It would be very useful to have optional list of active stream as dropdown menu in blacklist dialog (also keep the text field to write custom rule).

Best regard.

**Comment by Digitalone1** [comment]
@wwmm I was thinking to add a button for every app in applications list tab to add the app name in the blacklist. Do you think it's a good idea?

Maybe I'll investigate the code and see what could be done.

I was also thinking to improve the function for adding entries in the blacklist in a way that can't be added duplicate entries.

**Comment by wwmm** [comment]
I do not see a problem. In case there is an icon capable of passing the "blacklist idea" without a label it would be better. But if there isn't then the usual button with label will be the way.

Each app in that list is an instance of this class https://github.com/wwmm/pulseeffects/blob/master/src/app_info_ui.cpp. In order to edit the blacklist an addiotanl variable pointing to the schema containing the blacklist has to be created https://github.com/wwmm/pulseeffects/blob/master/data/schemas/com.github.wwmm.pulseeffects.gschema.xml.

**Comment by Digitalone1** [comment]
@wwmm I'm working on it, but during tests I get no audio while an app is blacklisted. Is this normal?

I also tried installing upstream version from Arch Linux repository and it's the same. I never used the blacklist, so I didn't test it so much, anyway I thought the blacklist would redirect the stream to the default sink without processing it, but it's playing silence on my system.

I tried everything. Deleted gstreamer cache, resetted PE, git and upstream version, but with blacklist there's no sound at all.

Maybe there's something wrong with my Pulseaudio configuration?

**Comment by Digitalone1** [comment]
@wwmm I tested it on another system and it's not working the same. I think it's completely broken.

**Comment by wwmm** [comment]
@Digitalone1 I did a few tests on my computer. There is a problem but it is not entirely on our side. Pulseaudio has a feature where it automatically moves the application to the last sink it was using. When we add the app to PE blacklist we do not try to move it anymore. But Pulseaudio is moving it to our sink again once the app starts. If the user has only this app running there is nothing telling PulseEffects to put its pipeline in the playing state as the only app playing was blacklisted. That is why there is no sound.

As we can't control this Pulseaudio feature I think that the only way to improve this is turn the app switch in our application list off before moving it to the blacklist

**Comment by wwmm** [comment]
Considering that there is a plan to add a blacklist button to each app entry I would put this logic in this button callback. And for consistency I would remove the add button from the blacklist menu in PE settings as turning the switch off there will probably be harder.

**Comment by Digitalone1** [comment]
> Considering that there is a plan to add a blacklist button to each app entry I would put this logic in this button callback. And for consistency I would remove the add button from the blacklist menu in PE settings as turning the switch off there will probably be harder.

Are you working on it? I already abstracted the part of code to add an entry inside the blacklist. Maybe I can abstract the part to disable the app so we can keep the add button in blacklist_settings_ui?

I can investigate on the code later.

**Comment by wwmm** [comment]
I am not working on it. You can go ahead. I think all that has to be done is a call like this one https://github.com/wwmm/pulseeffects/blob/fd9707af28667927de328dd25f4575a2e05b44e7/src/app_info_ui.cpp#L63 but setting the argument to false to disable the button. As the switch callback will probably be already in place the corresponding Pulseaudio functions should be called with no further work.

**Comment by wwmm** [comment]
Keeping the add button in the blacklist ui is fine as long as we are able to keep consistency. If the blacklist button in each app disables the switch but the add button in the blacklist ui doesn't will be confusing. And I have the feeling that disabling the app there may require extra work. Or maybe it doesn't bu the users will be confused about where they should be doing the blacklist

**Comment by Digitalone1** [comment]
> Keeping the add button in the blacklist ui is fine as long as we are able to keep consistency. If the blacklist button in each app disables the switch but the add button in the blacklist ui doesn't it will be confusing. And I have the feeling that disabling the app there may require extra work. Or maybe it doesn't but the users may be confused about where they should be doing the blacklist

I'll see what I can do.

The enable/disable switch is temporary. If I disable an app and close it, after when I relaunch it, it is reenabled in PE. The blacklist would mean to make an app permanently disabled. So, to make a switch disabled for a blacklisted app, maybe we can check if it's contained in the blacklist array?

**Comment by wwmm** [comment]
The app is reenabled when relaunched after being switched off because `Process All Outputs` is enabled in PE settings. It is better to keep the switch there as there are users out there that prefer to disable `Process All Outputs` and manually choose which app they want to be enabled.

When an app is blacklist it won't be shown in PE list again the next time it is opened. There is no need to think about its switch as it won't exist.

**Comment by wwmm** [comment]
Things are better on the latest master
![Screenshot from 2020-05-28 12-17-40](https://user-images.githubusercontent.com/16225172/83160174-3f64ab00-a0dd-11ea-837d-7a29d981d085.png)

**Comment by SGOrava** [comment]
That does not look nice, all I wanted is some dropdown list with current active streams/applications in blacklist menu dialog.
Blacklist is not a function you want to have ALWAYS on the eyes.

**Comment by Digitalone1** [comment]
I'm sorry, it's something difficult to do, at least for me, getting all applications processed and showing them inside a drop down menu.

This is faster than writing the application name or selecting it from a menu. If you don't use it, you can ignore the button.

**Comment by SGOrava** [comment]
Difficult, you pulled a good one, I do not know the code base so you are safe.

You don't have to write stream/program name, the list can show when you focus the text input.
This is not a function to be always on the eyes, it can cause more harm than good in current state.

Thanks for adding some shortcut for this function.

**Comment by Digitalone1** [comment]
To decide which names to show inside the drop down menu, you have to pick them somewhere, so you have to write a function.

I don't know and don't want to do it. Hope someone can do it for you. I don't think it will cause more harm than the enable/disable switch always been present. Did you try it? It's acting the same.

**Comment by SGOrava** [comment]
So introduce a function, look I am here as user who wants a nice program.

Yes, I tried the enable/disable switch but it is not persistent, in a moment I quit and start the program again the switch is enabled, I had to add entry into blacklist to make it persistent.

The whole point of this issue was that I had no idea what exactly to write there and I wished for some kind of cheat-sheet (list od current streams).

**Comment by Digitalone1** [comment]
Please, compile the code and try it, you will change idea. It's like the switch. The only thing different is that when you toggle it, the app goes in the blacklist. When you untoggle, it goes out from the blacklist. There's no harm at.

I'm not able to do what you want, I'm not a professional c++ developer, to do this I only reused parts of code already present, didn't write new ones.

**Comment by SGOrava** [comment]
I wonder at that. I do not wish for blacklisted streams to show up in main window.
I am grateful even for this button, it can save a lot of guessing and writing.

**Comment by SGOrava** [comment]
It is very strange.
When you blacklist a stream the enaled/disable toggle button should also be disabled otherwise it is doing some strange things.

**Comment by Digitalone1** [comment]
Apps started after you added them to blacklist won't show in the main window. Try it, you misunderstood how it works.

**Comment by Digitalone1** [comment]
> It is very strange.
> When you blacklist a stream the enaled/disable toggle button should also be disabled otherwise it is doing some strange things.

Indeed it's disabled when blacklisted. Just try it.

**Comment by SGOrava** [comment]
> Indeed it's disabled when blacklisted. Just try it.
I did, I could enable it while blacklisted and this state is problematic. Use should not be able to enable stream while it is on blacklist. So disable the button so user cant enable it.

**Comment by Digitalone1** [comment]
> I did, I could enable it while blacklisted and this state is problematic. Use should not be able to enable stream while it is on blacklist. So disable the button so user cant enable it.

It's not really problematic for PE. And if you leave it inside the blacklist, the next time the app is not processed at all by PE. 

But anyway, maybe something could be done to grey out the switch widget. I'll see what I can do.

**Comment by wwmm** [comment]
```
Yes, I tried the enable/disable switch but it is not persistent, in a moment I quit and start the program again the switch is enabled, I had to add entry into blacklist to make it persistent.
```
@SGOrava it does not seem to me that you need a blacklist. Disable the option `Process All Outputs` in PulseEffects menu and use the application switch to enable effects only to the applications you want.
![Screenshot from 2020-05-28 16-59-49](https://user-images.githubusercontent.com/16225172/83187575-c2e5c280-a104-11ea-9f93-b8f80e153ba7.png)

The blacklist exists for the users that want effects applied to everything except 1 or 2 apps. If you want effects for 1 or 2 it is more practical to disable `Process All Outputs`. Also have in mind that Pulseaudio tries to remember which sink the app was using at its last initialization. So you may have to manually disable a few apps after disabling `Process All Outputs` to force ulseaudio to forget the sink association.

**Comment by wwmm** [comment]
There are lots of things that could have been better in PulseEffects interface. So many I can't  even count them. But honestly a blacklist button is the least of our concerns. And considering that I am a physicist and not someone with a formal education in software design I would say that it is amazing how good the interface is :-)

**Comment by wwmm** [comment]
On a side note disabling the switch after toggling the blacklist button is easy. It is only a matter of setting the button `sensitive property` to false after blacklisting. I think that each gtk widget has a `set_sensitive` method.

**Comment by Digitalone1** [comment]
Anyway, I made the enable switch insensitive when the app is blacklisted and sensitive when it's removed from the blacklist. I'm testing it. 

This will be added if the PR will be accepted.

**Comment by wwmm** [comment]
I see no problems in accepting it :-)

**Comment by Digitalone1** [comment]
@wwmm I forgot that the add button in blacklist_config_ui is not blacklisting an app because the it is not moved to the default sink and Pulseaudio redirects it to PE at the next app restart getting no audio.

You said to remove it and maybe it's preferable, what do you think? The blacklist_config_ui will  be only useful to see which apps are blacklisted and to remove them when the app is not running (I tested this works). The only way to blacklist would be from app list, which is the only working in all cases, even if Process All Output is not enabled.

**Comment by wwmm** [comment]
I think it is better to remove the add button from the blacklist ui. Trying to move sinks there will only add unnecessary complexity.
