### ISSUE TITLE
No sound for enabled apps

### ISSUE THREAD

**Issue by ruvaldak** [wwmm/pulseeffects#628]
I'm sure this issue has been seen multiple times, but I couldn't find any solutions through google or browsing the issues here, so here we go...
Pulseeffects had been working fine, until one day it just suddenly didn't. No updates or anything as far as I know, but now enabling Pulseeffects for an app completely disables sound. 

<details>
<summary>G_MESSAGES_DEBUG=pulseeffects pulseeffects</summary>
<pre>(process:1989): pulseeffects-DEBUG: 12:03:54.420: main: locale directory: /usr/share/locale

(pulseeffects:1989): Gtk-WARNING **: 12:03:54.430: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:54.430: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:54.430: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:54.430: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:54.430: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:54.430: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:54.430: Theme parsing error: gtk.css:83:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.446: presets_manager: user presets directory already exists: /home/tyler/.config/PulseEffects
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.446: presets_manager: user presets directory already exists: /home/tyler/.config/PulseEffects/input
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.446: presets_manager: user presets directory already exists: /home/tyler/.config/PulseEffects/output
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.446: presets_manager: user presets directory already exists: /home/tyler/.config/PulseEffects/autoload
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.448: application: PE version: 4.7.1
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.448: pulse_manager: context is connecting
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.448: pulse_manager: context is authorizing
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.448: pulse_manager: context is setting name
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.449: pulse_manager: context is ready
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.449: pulse_manager: connected to: /run/user/1000/pulse/native
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.449: pulse_manager: protocol version: 33
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.449: pulse_manager: Pulseaudio version: 13.0
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.449: pulse_manager: default pulseaudio source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.449: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.449: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.449: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.449: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.449: pulse_manager:  failed to get sink info: PulseEffects_apps
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.451: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_apps sink_properties=device.description="PulseEffects(apps)"device.class="sound" norewinds=1
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.451: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.452: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.452: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.452: pulse_manager:  failed to get sink info: PulseEffects_mic
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.454: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_mic sink_properties=device.description="PulseEffects(mic)"device.class="sound" norewinds=1
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.465: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.465: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.478: sie: limiter is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.480: sie: compressor is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.481: sie: filter is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.517: sie: equalizer is enabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.518: sie: reverb is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.519: sie: bass_enhancer is enabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.521: sie: exciter is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.522: sie: crossfeed is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.529: sie: maximizer is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.532: sie: multiband_compressor is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.532: sie: loudness is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.534: sie: gate is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.535: sie: pitch is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.538: sie: multiband_gate is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.539: sie: deesser is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.541: sie: stereo_tools is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.543: sie: convolver is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.544: sie: crystalizer is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.544: sie: autogain is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.547: sie: delay is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.553: soe: using output device: PulseEffects_mic
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.553: soe: using input device: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.553: soe: limiter is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.554: soe: compressor is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.554: soe: filter is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.558: soe: equalizer is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.558: soe: reverb is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.559: soe: gate is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.559: soe: deesser is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.560: soe: pitch is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.563: soe: webrtc is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.564: soe: multiband_compressor is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.564: soe: multiband_gate is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.565: presets_manager: user presets directory already exists: /home/tyler/.config/PulseEffects
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.565: presets_manager: user presets directory already exists: /home/tyler/.config/PulseEffects/input
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.565: presets_manager: user presets directory already exists: /home/tyler/.config/PulseEffects/output
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.565: presets_manager: user presets directory already exists: /home/tyler/.config/PulseEffects/autoload
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.565: presets_manager: destroyed
pulseeffects-INFO: 12:03:54.565: application: disabling global bypass
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.565: sie: bypass is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.565: soe: bypass is already disabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.733: convolver_ui: irs directory already exists: /home/tyler/.config/PulseEffects/irs
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.972: sie: spectrum enabled
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:54.972: soe: spectrum enabled

(pulseeffects:1989): Gtk-WARNING **: 12:03:55.009: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:55.009: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:55.009: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:55.009: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:55.009: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:55.009: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:1989): Gtk-WARNING **: 12:03:55.009: Theme parsing error: gtk.css:83:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.152: sie: total latency: 0 ms
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.152: soe: total latency: 0 ms
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.266: sie: sampling rate: 44100 Hz
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.266: pulse_settings_ui: added sink: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra5
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.266: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.266: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.266: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.266: pulse_settings_ui: added source: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra5.monitor
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.266: soe: using input device: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.266: pulse_settings_ui: input device changed: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.266: pulse_settings_ui: added source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.267: sie: NULL -> READY -> PLAYING
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.268: sie: READY -> PAUSED -> PLAYING
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.268: sie: pulsesrc latency [us]: 10000
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.268: sie: pulsesrc buffer [us]: 200000
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:55.268: sie: total latency: 0 ms
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:56.678: peadapter: pulseaudio block size 441 frames
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:56.678: peadapter: we will read in chunks of 512 frames
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:56.689: sie: total latency: 141 ms
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:56.690: sie: pulsesink latency [us]: 10000
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:56.690: sie: pulsesink buffer [us]: 200000
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:56.690: sie: total latency: 141 ms
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:56.690: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:1989): pulseeffects-DEBUG: 12:03:56.690: sie: total latency: 141 ms
(pulseeffects:1989): pulseeffects-DEBUG: 12:04:11.664: pulse_manager: sink input: Chromium, idx = 0 removed from PE
(pulseeffects:1989): pulseeffects-DEBUG: 12:04:18.608: sie: No app wants to play audio. We will pause our pipeline.
(pulseeffects:1989): pulseeffects-DEBUG: 12:04:18.610: sie: PLAYING -> PAUSED -> VOID_PENDING
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.856: application:  destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.856: presets_manager: destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.857: soe: destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.857: soe: multiband_gate destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.857: soe: multiband_compressor destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.857: soe: webrtc destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.857: soe: NULL -> VOID_PENDING
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.857: soe: pitch destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.857: soe: deesser destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.857: soe: gate destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.857: soe: reverb destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.857: soe: equalizer destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: soe: filter destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: soe: compressor destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: soe: limiter destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: delay destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: autogain destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: crystalizer destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: convolver destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: stereo_tools destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: multiband_gate destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: loudness destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: multiband_compressor destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: maximizer destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: crossfeed destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.858: sie: exciter destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.859: sie: bass_enhancer destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.860: sie: NULL -> VOID_PENDING
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: sie: pitch destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: sie: deesser destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: sie: gate destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: sie: reverb destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: sie: equalizer destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: sie: filter destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: sie: compressor destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: sie: limiter destroyed
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: pulse_manager: unloading PulseEffects sinks...
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: pulse_manager: module 32 unloaded
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: pulse_manager: module 33 unloaded
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: pulse_manager: Context did not need draining
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: pulse_manager: disconnecting Pulseaudio context...
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: pulse_manager: context was terminated
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: pulse_manager: Pulseaudio context was disconnected
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.861: pulse_manager: unreferencing Pulseaudio context
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.862: pulse_manager: stopping pulseaudio threaded main loop
(pulseeffects:1989): pulseeffects-DEBUG: 12:07:57.862: pulse_manager: freeing Pulseaudio threaded main loop</pre>
</details>

One thing I noticed when glancing through it was `failed to get sink info: PulseEffects_apps` - maybe this is related?

I tried removing and reinstalling pulseeffects to no avail, and I tried a different kernel just as a "maybe a kernel updated without my consent" kind of thing, but that didn't do anything either. I haven't tried to reinstall pulseaudio, though I did check PulseAudio Volume Control and everything seems to be in order - PE recording from PulseEffects(apps), chromium running through PE apps, PE output as Built-In Audio Analog Stereo. I did notice that PE Spectrum isn't moving, either.

![Screenshot_20200212_120404](https://user-images.githubusercontent.com/15901769/74364206-b2961b80-4d91-11ea-9430-3999b6bb8067.png)
![Screenshot_20200212_121814](https://user-images.githubusercontent.com/15901769/74364228-c2adfb00-4d91-11ea-80f7-fb0a4b868180.png)
![Screenshot_20200212_121837](https://user-images.githubusercontent.com/15901769/74364248-cd689000-4d91-11ea-813c-e7d7975b7468.png)

All these screenshots were taken while music was playing via Youtube - Spotify also doesn't produce sound when PE is enabled.

Sorry if this is an often repeated issue, maybe my google-fu isn't as good as I thought it was

**Comment by wwmm** [comment]
Based on the logs PE pipeline is playing
```
PAUSED -> PLAYING -> VOID_PENDING
total latency: 141 ms
```
And according to the images above PE audio routing is also ok. Usually under these circunstances the source of the problem is an audio stream or sink that was muted by a third party process. IT happened to me a few times that the new Tomb Raider ported by Feral muted PE sinks. An easy way to test this would be to remove the folder `~/.config/pulse/` and login to your desktop again.

Pulseaudio does not offer a way to forbid third party apps from messing with our streams and virtual sinks muted state. This is very unfortunate.

**Comment by ruvaldak** [comment]
That certainly fixed it - renamed `~/.config/pulse/` to `~/.config/pulse.bak/` and rebooted and sound is working now. I wonder what app/s messed with the sinks.. regardless, thanks for the help. Bummer there's no way to forbid it. I don't have enough knowledge of that stuff to really understand why or even suggest anything, but hopefully a solution can be found someday - maybe sometime pulseaudio will make a solution one day.
