### ISSUE TITLE
[Feature Request]- Pulseeffects profiles linked to audio output

### ISSUE THREAD

**Issue by Dodjob** [wwmm/pulseeffects#629]
Hi!
First let me share my abolute love for this piece of soft <3 I install it everywhere and therefore came to a situation which could be enhanced.
I have a laptop with a really "bad" speaker. To compensate this I need to make a special profile called "Laptop-speakers", and the pulseeffects does this just right.
BUT I'm some kind of audiophile. and I mostly connect my laptop to my (diy) boombox or to my main installation throught Bluetooth.
As you imagine, the settings for 2x1" speakers is quite different as the one for my home 2.1, 2KW installation ;)
I have to, every time I connect to my BT, switch manually from my "laptop-speakers" profile to my "Viktoria" boombox settings or to my "main installation" profile if I'm there. 
I think there would bee a huge benefit (for me or anybody having multiple installations) to link the profile to what's connected on the audio output. 
Pulseeffects is a beautiful solution, but it's conceptually linked to the output, not the input like it is today. 
So my proposal (being totally unable to know if it's technically doable) would be to create profiles per audio output (taking the Bluetooth ID/ Internal Audio Output/Headset-jack of the connected device as "Profile-group" and any created profiles then (if multiple needed) should be available for it. 
or. to link audio profile to bluetooth ID. that would be an huge benefit.
Sorry for the long text, that's mostly how I am when I talk about pulseeffects to anybody asking me any informations on it :)
Thanks again for this beautiful thing!
Have a nice week-end,
Hadrien

**Comment by wwmm** [comment]
Hi! :-)

This feature is already available. But I admit it is not obvious to see it. And it is not easy to it more visible... Anyway take a look at the image below
![Screenshot from 2020-02-22 11-11-50](https://user-images.githubusercontent.com/16225172/75093844-34d9c900-5564-11ea-94d4-2e795bd60035.png)
Between the `save` and the `remove` button there is another one with circular arrows. The idea is to click on the arrows button of the desired preset when the output device that should automatically load it is the current default device. In your case when you are using your `laptop-speakers` profile click on its arrows button and when the device that is the current default is clicked again this preset will be automatically loaded.

When your bluetooth device is selected as default output repeat the process but this time click on the circular arrows of the `Viktoria` preset and it will be automatically loaded whenever the bluetooth device becomes the default output device.

**Comment by wwmm** [comment]
Only one preset can be associated to each device. So if `Viktoria` and `main installation` are using the same bluetooth device in the laptop you will have to choose one of them to be automatically loaded.

**Comment by Dodjob** [comment]
<3 OMG <3 It's working!!! That's awesome :)
The story with getting the uuid of the connected device and link it would still be an improvement B U T having the switch like you described it is absolutely enough right now for dual laptop speakers/Bluetooth audio settings. 
Daaamn I'm Happy! 
Thanks a lot and have a nice week-end!
Hadrien
