### ISSUE TITLE
How to change spectrum frequency range ?

### ISSUE THREAD

**Issue by dokuzbir** [wwmm/pulseeffects#630]
How can i change spectrum frequency range? source code or json settings

**Comment by wwmm** [comment]
At this moment there is no user friendly way to do that. If you are willing to compile PE sources you can try chaning the value here https://github.com/wwmm/pulseeffects/blob/e643c4e91cd5c73a789bf9655a4e931cb3603dfc/include/pipeline_base.hpp#L58. But it isn't really enough to make everything right. The scale frequency axis shown in PE window won't be updated as the labels position and values are hard coded. And the values shown when the mouse hovers the spectrum will be wrong too https://github.com/wwmm/pulseeffects/blob/e643c4e91cd5c73a789bf9655a4e931cb3603dfc/src/spectrum_ui.cpp#L197

The way the spectrum frequencies axis is built definitely needs improvement. But there was always something higher on the priority list... Maybe a better way to handle it would be to draw it together with the spectrum through cairo functions.

**Comment by IdreesM0** [comment]
This is something Im also looking forward to. The number of bars(max 1000) displayed are never enough to response to so many frequencies and thus the spectrum looks rather unresponsive to especially the vocal frequencies (mids maybe, im no expert in this). Im really excited to see this improvement coming soon.

**Comment by Mlocik97** [comment]
I just found BUG in 2.7.2/2.7.3,.. I'm not sure, if changes in 2.8.0 fixed it, but it would be fine to look on it.

Btw. Frequency range for spectrum can be set from GUI app in new version, so it closes this issue.

https://www.youtube.com/watch?v=zIbvVZJQL44&feature=youtu.be

**Comment by wwmm** [comment]
@Mlocik97 thanks for noticing that this issue can be closed. About the spectrum "disappearing" what is happening is that the bars get so thin when there are too many points to be displayed that they can not be seen. I don't know if there is much that can be done about it as this effect is dependent on the monitor resolution. And depending on the personal taste the user may want to customize the bars width.

**Comment by Mlocik97** [comment]
I agree, propably not needed to be fixed,.. there will be always problem, that, when You have only 500px avaiable on width of viewport, You will not be able to show more than 500 columns.

**Comment by IdreesM0** [comment]
Hi! Is the ability to change frequency range made available in version
4.8.0? I have version 4.7.2 on ubuntu  20.04 and I can't upgrade to version
4.8.0.

**Comment by wwmm** [comment]
>Is the ability to change frequency range made available in version
4.8.0?

Yes. You need PE `4.8.0`.

**Comment by IdreesM0** [comment]
Ok thanks for letting me know. Is 4.8.0 not going to be made available in
ubuntu 20.04 through the official pulseeffects repository? The updater says
pulseeffects is the latest version but its only 4.7.8.

**Comment by wwmm** [comment]
`4.7.8`? We jumped from `4.7.3` to `4.8.0`. 

PE `4.8.0` requires `lsp-plugins 1.1.24` and `gtkmm 3.24`. Maybe these packages can not be updated yet.

**Comment by IdreesM0** [comment]
I'll keep an eye. The gtk version is 3.24 as per apt-cache policy
libgtk-3-0 output. I'll wait for lsp-plugins though. Thanks for letting me
know. And yes I wrote the version wrong. That was my bad. I must be missing
something because my ubuntu install has version 4.7.2 as the latest version
not even 4.7.3

**Comment by Mlocik97** [comment]
I still have 4.7.2 too. So it's not Your fail.
