### ISSUE TITLE
Spotify fixed audio configuration 

### ISSUE THREAD

**Issue by claudiofgcardoso** [wwmm/pulseeffects#631]
Hello all,

I'm relatively new to pulseeffects, so sorry for potential mistakes. While editing the general audio quality of my ubuntu 18.04 system within the "/etc/pulse/daemon.conf", I noticed that spotify is the only app that doesn't change the audio output format as specified in the pulse configuration file: 

![Screenshot from 2020-02-24 16-22-47](https://user-images.githubusercontent.com/31186692/75170459-0dc8f600-5722-11ea-8b17-74e86a9096c4.png)

I noticed that this is also present in the screenshots displayed at the GitHub pulseeffects page:
![image](https://user-images.githubusercontent.com/31186692/75170547-2fc27880-5722-11ea-979e-af6d0fbaac9f.png)

Is this issue solely related with the spotify app or is there a way of solving this within pulseeffects?

**Comment by wwmm** [comment]
I imagine that you want the Pulseaudio setting `avoid-resampling` to take effect. THis requires Recent PulseEffects versions and at least Pulseaudio 13. The second image above is from a PE version that does not support this feature. Your image has a bypass button. So I am not mistaken it should already support it. But as you are on Ubuntu 18 it is possible that you do not have Pulseaudio 13.

**Comment by wwmm** [comment]
Have also in mind that going from a 16 bits sample format `s16le` to a 32 bits format `s32le or F32LE` does not cause quality loss. Doing the opposite path that is a problem. The only "issue" in your image is the difference in sampling rate. This should be fixed by using recent PulseEffects and Pulseaudio versions.

**Comment by claudiofgcardoso** [comment]
You are right, unfotunately my Pulseaudio version is at 12.2-2. So, I guess I'll have to wait for the update in ubuntu 18.04. Thanks for the assistance!
