### ISSUE TITLE
Changing PulseAudio settings causes PulseEffects not to work

### ISSUE THREAD

**Issue by seedship** [wwmm/pulseeffects#632]
I've been running into issues with music getting harsh (clipping I think) when using many effects (Equalizer, Reverb, Exciter, Crystallizer, Loudness, Bass Enhancer, Filter to be exact). The volume isn't turned super high and I think I can achieve louder sound from PulseAudio alone.

I tried tweaking the PulseAudio settings hoping that might make things better. Namely, I followed this guide: https://forum.level1techs.com/t/improving-linux-audio-updated/134511
I changed my sampling rate from 48000 -> 192000
I changed the pulseaudio audio fromat from s16le -> f32le
I also changed the asound config as described in the forum above.

However, when I rebooted, pulseaudio still worked, but when I routed it via pulseeffects, there was no output. Pulseeffects also showed no waveform.

Is PulseEffects not able to handle f32le input? Or is changing the asound config the culprit? Or a combination of the changes I made? Or is it mathematically hard not to have audio artifacts and clipping when using that many effects?

Thanks!

**Comment by wwmm** [comment]
I suggest you kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. This way we will have an idea about what is going on when you force Pulseaudio to use a sampling rate of 192000 Hz. I do not have audio material recorded at this rate. So it is not tested.

Almost all plugins used by PE work only with the `f32le` format. So forcing Pulseaudio to use `f32le` is definitely not the problem. Something else is going on. Your sound card probably has no support for it. But this shouldn't be a problem either as Pulseaudio automatically falls back to `s32le` if that is the case.

**Comment by wwmm** [comment]
Honestly just remove that `.asound.conf` setting. It makes no sense. Setting your sampling rate to 192 kHz also makes no sense if your audio files use 48 kHz or less. I wonder why there are so many Pulseaudio tutorials out there suggesting these kind of crazy settings. Maybe they were written at the time Pulseaudio was not capable to avoid resampling. Nowadays just set `avoid-resampling = true` and you will be fine.

**Comment by wwmm** [comment]
If you there is audio clipping you are saturating your sound card input. Try to see how high are the levels in the output of the last plugin in your audio chain. Using a limiter as the last plugin in the chain will help to avoid clipping.

**Comment by seedship** [comment]
Ah, I just changed the sound format to f32le and the resample-method = speex-float-10 and now it works.

Thanks!
