### ISSUE TITLE
Opening mic settings and spectrum in new window

### ISSUE THREAD

**Issue by dokuzbir** [wwmm/pulseeffects#633]
Is it possible to analyze and see to mic spectrum in new window ? Or maybe 2 instance of pulseeffects

**Comment by wwmm** [comment]
There is a mic signal analysis window next to the test signals
![Screenshot from 2020-02-25 11-01-29](https://user-images.githubusercontent.com/16225172/75254212-c80e3b00-57be-11ea-8b4e-e8a5d4e837e8.png)
To get to it click on the `sine wave` button at the main window top left corner.

At this moment support for mic analysis is very limited. You can see the raw signal or subtract the background noise from it. It is so hard to get a usb calibrated mic here in Brazil that I could never to properly explore this field. The best mic I could get was a Behringer C-1u. But it is no ideal for room equalization. 

Running two PulseEffects instances is not possible. They would conflict with each other.
