### ISSUE TITLE
Opening settings menu audio changes Pulse Effects listener device

### ISSUE THREAD

**Issue by Eonfge** [wwmm/pulseeffects#637]
I've found an issue with Pulse Effects, and the settings menu in GNOME. In short: When I go to the audio tab of the settings menu, the configuration of Pulse Audio changes, which causes Pulse Effects to stop working.

# Base Setup
- Fedora 31
- Gnome 3.34
- Pulse Effects 4.7.0
- Pulse Audio 13.0
- Lollypop 1.2.23

# Hardware setup
- 4.0 headset + microphone
- GM 204 HDMI Monitor output (Disabled)
- Digital Stereo output IEC958

# Configuration
- 4.0 headset and microphone are default input and output device
- Lollypop sends audio to Pulse Effects (App)
- Pulse Effects records Lollypop, outputting to the Digital Stereo output

In my current configuration, I can use my headset while watching YouTube, Skype, or playing a video game. Music goes to the living room.

# Where it fails
- I go to the settings menu
- I click the audio tab
- The audible music stops, whil lollypop is still outputting to Pulse Effects (App)
- Pulse Effects is recording the audio of my microphone, outputting it to the living room
- Other audio stays functioning

# What goes wrong
My hypothesis, is that Pulse Effects has not properly recorded it's current audio recording device. When I open the audio tab, Pulse Effects thinks the settings have changed and it then loads the wrong input device.

**Comment by wwmm** [comment]
Just to make sure I understand by settings menu in Gnome do you mean this one?
![Screenshot from 2020-03-05 17-40-32](https://user-images.githubusercontent.com/16225172/76023719-75442a00-5f08-11ea-90bb-d78c99202e97.png)

I use the same Gnome and Pulseaudio version on Arch Linux and just opening the Gnome settings window does nothing. But my setup is different from yours. No bluetooth. Only the sound card.

That being said as you can see here https://gitlab.gnome.org/GNOME/gnome-control-center/issues/494 Gnome sound settings has a very questionable feature that breaks custom audio routing. This is so annoying that Pulseaudio developers will add a work around that disables it in Pulseaudio 14. Just search for Gnome in this page https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/14.0/ and you will see.

My guess is that when you open Gnome settings window that annoying feature is being triggered. What it does is moving all streams to the device Gnome wants to set as default. As you want PulseEffects to play to a selected custom device the routing is broken.

By the way are you selecting a custom output device in PE window or did you configured it to use the default device?
![Screenshot from 2020-03-05 17-50-17](https://user-images.githubusercontent.com/16225172/76024413-d4ef0500-5f09-11ea-850c-6538e0aacbd9.png)

**Comment by Eonfge** [comment]
> Just to make sure I understand by settings menu in Gnome do you mean this one?

Yes, that's the culprit

> That being said as you can see here https://gitlab.gnome.org/GNOME/gnome-control-center/issues/494 Gnome sound settings has a very questionable feature that breaks custom audio routing. 

Thanks for explaining the issue. It sucks that this is apparently known but unattended. This does indeed matches my issues and experiences.

> By the way are you selecting a custom output device in PE window or did you configure it to use the default device?

- Output, I selected from Pulse Effects
- Input, I have on default (which is my microphone). 
  I use pavucontrol to select Pulse Audio (apps) as recording device whenever the settings menu wipes my setting.

So, close this issue or keep open until PulseAudio fixes the GNOME audio routing issue? Thanks for explaining the issue though.

**Comment by wwmm** [comment]
I will close it. Fixing the source of this problem is out of my reach.

**Comment by kapouer** [comment]
On debian/sid here, gnome 3.36. I had that issue, and gave a try to pulseaudio 13.99 (in debian experimental). It works correctly now !
