### ISSUE TITLE
Upward compressor broken after new lsp-plugins update on Arch Linux 

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#641]
Hello @wwmm. 
I'm using a preset with compressor in upward mode and noticed that this morning the audio was weird.

After investigating, I found out that compressor plugin is not outputting the right level in upward mode. For example, it shows an output of -1 db, but the next plugin gets an input signal with lower amplitude, quite similar as the original level at the input of the overall pipeline.

With this behaviour, the upward compressor is simply not working at all.

Then I found out that lsp-plugins upstream Arch Linux package was updated yesterday and the [changelog](https://github.com/sadko4u/lsp-plugins/blob/master/CHANGELOG.txt) shows something interesting.

> Fixed upward compressor behaviour: now upward compressor has additional compensation knee that prevents from infinite gain boost on low-level input signals.

Anyway I tried to set strong settings to get a fast response and an higher output gain, but the behaviour is always the same. In this state the plugin is not able to increase the gain and reports a wrong output level in its tab. I think something is broken, maybe in the way PulseEffects is managing the new plugin update.

Please @wwmm, can you investigate more in depth? Thank you.

**Comment by Digitalone1** [comment]
Just downgraded the package and the behaviour returned the previous, so it's definitely something related to the new update.

For now I have blacklisted it in pacman.conf.

**Comment by wwmm** [comment]
How did you get to this `-1 dB` value? I did a quick test and it seems fine. Or at least it is amplifying the signal. If is amplifying on the amount it should be I can not say.
![Screenshot from 2020-03-22 13-03-11](https://user-images.githubusercontent.com/16225172/77254114-cd379c00-6c3d-11ea-9cad-b3a6d9644a01.png)

**Comment by wwmm** [comment]
Oh... It is only looking at the input level on the next plugin we notice the change

**Comment by wwmm** [comment]
Yes. Something seems broken even if not using the upward mode

**Comment by wwmm** [comment]
Running PE in debug mode I saw this `g_object_set_is_valid_property: object class 'lsp-plug-in-plugins-lv2-compressor-stereo' has no property named 'bypass'`

It seems that the property controlling the bypass state has a new name. It makes sense. In my quick test it felt like the plugin was being bypassed.

**Comment by wwmm** [comment]
The `bypass` property now is called `enabled`. And the same change was made to the other LSP plugins. I will fix this today. It was time for an update anyway.

**Comment by wwmm** [comment]
Master branch updated. Test it if possible.

**Comment by Digitalone1** [comment]
Okay, updated lsp-plugins and compiled pulseeffects-git, it's working properly now. Thank you.

**Comment by sadko4u** [comment]
Please look at this topic how you can get a workaround:
https://github.com/sadko4u/lsp-plugins/issues/86

**Comment by wwmm** [comment]
I am fine with forcing lsp `1.1.14` as minimum requirement for PE `4.7.2`. This PE version does not have a major feature that would make everybody want to upgrade now. And most if not all of the distributions willing to make this move probably can update lsp too. A few people may disagree but I don't think it is necessary to add workaround for this :-)

**Comment by sadko4u** [comment]
It's your own decision. Maybe it's right but I suppose that not all Linux distributions are handling changes so quick like Arch Linux.

In the topic mentioned below I show why LV2 standard is non-natural and non-consistent in it's changes. If I followed 'minorVersion' requirement of LV2 then all plugins also would become non-working in your environment since they all are required to change their URIDs. If your plugin wrappers could handle port addition (set default value as described in TTL to not bound ports) and port removal (just ignore them), then the effect of LSP changes would be less destructive.
