### ISSUE TITLE
4.7.2 build fail with boost < 1.72

### ISSUE THREAD

**Issue by Vascom** [wwmm/pulseeffects#645]
I have this build error:
```
../src/pipeline_base.cpp:5:10: fatal error: boost/math/interpolators/cardinal_cubic_b_spline.hpp: No such file or directory
    5 | #include <boost/math/interpolators/cardinal_cubic_b_spline.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
cardinal_cubic_b_spline.hpp present only in Boost 1.72. Is it mean that pulseeffects now can't be build for previous boost versions? It is very bad because even Fedora rawhide has only Boost 1.69.

**Comment by mikhailnov** [comment]
yeah, I also had to package boost 1.72 urgently for the PPA, the latest version even in Debian Sid is 1.71

**Comment by mikhailnov** [comment]
changelog of PE says that depreceated headers of boost were replaced with the ones present in v 1.72, may be they can be restored and used, but I did not try to investigate this, packaging boost 1.72 was easier.

**Comment by Vascom** [comment]
I can wait fresh boost in Fedora.

**Comment by Vascom** [comment]
Also lsp-lugins 1.1.14 has bug important for pulseeffects https://github.com/sadko4u/lsp-plugins/issues/85

**Comment by Vascom** [comment]
@wwmm can you please revert boost 1.69 support?
Because new boost come to Fedora min after 8 month.

**Comment by wwmm** [comment]
Even if there is a warning printed LSP spectrum bug does not after PE. We do not use its spectrum analyzer. We use the one provided by GStreamer.

I really do not like using deprecated api but I will think about the Boost situation... But seriously Fedora why waiting 8 months to update Boost?!? Arch Linux did that in January and up to now I did not see a single problem... This is ridiculous...

**Comment by wwmm** [comment]
Or maybe this commit https://github.com/wwmm/pulseeffects/commit/a363d7fa06003b508b55ba12fa6eab98718d94d6 could be reverted when building the package. I did not try but I think that there would be no conflict.

**Comment by Vascom** [comment]
Because of https://bugzilla.redhat.com/show_bug.cgi?id=1558278#c27

**Comment by Digitalone1** [comment]
Hasn't Fedora something like AUR to build a custom package?

**Comment by mikhailnov** [comment]
Fedora does have Koji and additional repositories there, but @Vascom is maintaining the PulseEffects package in the official Fedora repository

**Comment by Digitalone1** [comment]
4.7.2 is not a main release, so if they not upgrade boost, it's not a big problem staying on 4.7.1.

**Comment by Vascom** [comment]
Fedora rawhide now has Boost 1.73 and PE 4.7.2.
