### ISSUE TITLE
Failed to install on Ubuntu 19.10

### ISSUE THREAD

**Issue by efibutov** [wwmm/pulseeffects#647]
Running the command 
`sudo apt install pulseeffects`

And got this error:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pulseeffects : Depends: gir1.2-gst-plugins-bad-1.0 but it is not installable
                Recommends: calf-plugins (>= 0.90.0) but it is not installable
                Recommends: zam-plugins but it is not installable
                Recommends: rubberband-ladspa but it is not installable
                Recommends: mda-lv2 but it is not installable
                Recommends: lsp-plugins-lv2 (>= 1.1.14) but it is not going to be installed or
                            lsp-plugins (>= 1.1.14) but it is not going to be installed
                Recommends: gstreamer1.0-convolver-pulseeffects but it is not going to be installed
                Recommends: gstreamer1.0-crystalizer-pulseeffects but it is not going to be installed
                Recommends: gstreamer1.0-autogain-pulseeffects but it is not going to be installed`
`

**Comment by wwmm** [comment]
@mikhailnov

**Comment by mikhailnov** [comment]
You probably have some other problems, try for example `sudo apt install gir1.2-gst-plugins-bad-1.0`, what will it show?

**Comment by wwmm** [comment]
Inactive
