### ISSUE TITLE
No Equalizer on Ubuntu 19.10

### ISSUE THREAD

**Issue by Philipp0205** [wwmm/pulseeffects#648]
For some reason I can't activate the equalizer: 

![image](https://user-images.githubusercontent.com/36603238/78590066-85ba2e00-7841-11ea-8fcb-92a47d96d5bc.png)

I use Version 4.6.6 of PulseEffects. Installed with apt. 
Any hints?

Thanks!

**Comment by wwmm** [comment]
Check if you upgraded the `lsp-plugins` package to a version above `1.1.13`. If yes you will need to upgrade PulseEffects to `4.7.2`. If you can't do that downgrade `lsp-plugins` to `1.1.13` or older.

**Comment by wwmm** [comment]
By lsp-plugins I mean `Linux Studio Plugins`

**Comment by Philipp0205** [comment]
That was it! Thanks!
