### ISSUE TITLE
PulseAudio stops processing in Firefox video playback

### ISSUE THREAD

**Issue by Lucchetto** [wwmm/pulseeffects#649]
I've enabled the option to process all the outputs, however when i play a video on YouTube on Firefox and move the scrub bar once, the processing stops. If I move it again, the processing starts again

I'm using Manjaro Deepin with Firefox 75

**Comment by wwmm** [comment]
I have Firefox 75 on Arch Linux and I could not reproduce this. Clicking on random sections of the progress bar or dragging it did nothing unusual.

Kill the current PulseEffects instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Maybe something interesting will be shown in the terminal.

**Comment by wwmm** [comment]
Inactive.
