### ISSUE TITLE
Building source release failed with: dpkg-source: error: can't build with source format '3.0 (git)': doesn't contain a git repository

### ISSUE THREAD

**Issue by descendingnerdliness** [wwmm/pulseeffects#651]
On Ubuntu 18.04, the source release will not build. It ends with the following:
```
dpkg-source -i -b pulseeffects-4.7.1
dpkg-source: error: can't build with source format '3.0 (git)': doesn't contain a git repository
dpkg-buildpackage: error: dpkg-source -i -b pulseeffects-4.7.1 subprocess returned exit status 25
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui -i failed
```
This after 4.7.2 and master will not build because of libboost-filesystem-dev revision.

**Comment by wwmm** [comment]
`4.7.2` needs a recent Boost version. So the libboost error is understandable. About the other @mikhailnov might have some idea.

**Comment by mikhailnov** [comment]
Where did you take the source from so that it does not contain `.git`?
I have added instructions about boost here: https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source/_compare/8c0bee4310ec144edae568e714b6bcc2a5da2454...ec87142c1c1379aa4a9c3bbc385748e2973d0e04

**Comment by descendingnerdliness** [comment]
Hi mikhailnov:
Thanks for the reply!
I got 4.7.1 and 4.7.2 from this page: https://github.com/wwmm/pulseeffects/release.
After adding https://launchpad.net/~mikhailnov/+archive/ubuntu/pulseeffects  
I get this error:
 "E: The repository 'https://launchpad.net/~mikhailnov/+archive/ubuntu/pulseeffects bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default."

**Comment by descendingnerdliness** [comment]
@wwmm @mikhailnov 
Funny, but after I was able to create the build-deps .deb, the master still fails to build for lack of a .git. It is absent from your repo. 
It seems that directory is created only by actually doing a git clone, so how would one use one of your releases?

**Comment by wwmm** [comment]
As I don't use a Debian based distribution I can't explain what has gone wrong in this package building. But the `.git` is not stored in the online repository. That is how git works. You have to clone to have this folder.

**Comment by descendingnerdliness** [comment]
Ok, in building the clone, there seems to be something else missing. I get this error:
`Now running lintian pulseeffects_4.7.2-3_amd64.changes ...
internal error: could not find the source tarball at /usr/share/lintian/collection/src-orig-index line 99.
warning: collect info src-orig-index about package pulseeffects failed
warning: skipping check of source package pulseeffects
E: pulseeffects changes: bad-distribution-in-changes-file unstable
Finished running lintian.

**Comment by descendingnerdliness** [comment]
Even with the error, it did produce .debs. After installing them, the working functions are:
auto gain,
compressor,
equalizer,
loudness,
and maximizer.

**Comment by descendingnerdliness** [comment]
Also, the window can only be resized from the top.

**Comment by wwmm** [comment]
You can have the limiter. Just install the package providing `Calf Studio Plugins`. I don't know its name on Ubuntu. At least on Arch Linux the package is named `calf`.

**Comment by descendingnerdliness** [comment]
Thanks, but I installed calf  before compiling. How would I tell it where to find them?

**Comment by wwmm** [comment]
Plugins are loaded at runtime. You may be facing a GStreamer bug. Try to remove its cache folder `rm -rf ~/.cache/gstreamer-1.0` and restarting PE.

**Comment by descendingnerdliness** [comment]
Thanks. Gstreamer 1.0 is version 1.14.5. 
Removing the cache didn't change things.
calf.so is in /usr/lib/ladspa

**Comment by wwmm** [comment]
`calf.so is in /usr/lib/ladspa` this is your problem. You need the Calf package for the LV2 standard and not LADSPA. Calf deprecated the LADSPA version years ago but for some reason you still see debian packages for it out there.

**Comment by descendingnerdliness** [comment]
Everything works! Thank you!
Now I have to find out what the things I don't use, like a convolver, are good for.

**Comment by descendingnerdliness** [comment]
BTW. The convolver says it cannot load the impulse file. Where is that found?

**Comment by wwmm** [comment]
Impulse response files usually have copyrights so including them with PE is complicated. You can find a few on the web https://github.com/wwmm/pulseeffects/wiki/Impulse-Responses. Searching on the web for impulse files for Viper4Android also helps.

**Comment by wwmm** [comment]
https://en.wikipedia.org/wiki/Convolution_reverb
