### ISSUE TITLE
[Question/BUG] Geometric Mean - AutoGain

### ISSUE THREAD

**Issue by Mlocik97-issues** [wwmm/pulseeffects#652]
Hello, today I updated PulseEffects and I see new feature (Geometric Mean) in AutoGain plugin.
I know what that mean in math, and know that, output (loudness) value will be lover, but what other effects it has on audio/loudness? How does it affect loudness range and output volume? I'm not sure what it's exactly doing with audio signal even after reading source code and documentation of PE.

**Comment by Mlocik97-issues** [comment]
I'm now looking on one thing, which is ugly for me. When I set weight to 1-1-100, and use Geometric Mean, then weights are hiden, but I can see that, weights still affects calculation, and change of these values to 100-100-1 change audio totally different, even in Geometric mean. So why are weights hidden from UI, and how it affect output of audio?

**Comment by wwmm** [comment]
I am not able to reproduce this on my computer. Enabling geometric mean disables the weights as it should.

**Comment by wwmm** [comment]
I don't know if there is a profound interpretation for the geometric mean in this context. In many cases people say that the geometric mean is less sensitive to fluctuations. 

At least on my use cases using the geometric mean has been a more "automated" way of getting what I want without having to play with the weight values. Sudden changes to the momentary value influence the output but not with as much intensity as they would if all the loudness computations had the same weight. 

Without a study it is hard to say which is the overall effect over the loudness range. At least for me the result has been less adjustments to the master volume compared to when I used weights.

**Comment by wwmm** [comment]
Try to run PE in debug mode. You may be facing some kind of installation problem. After doing lots of tests I can still see a clear difference between geometric and weight mean in how the average loudness oscillates.

**Comment by Mlocik97** [comment]
> Try to run PE in debug mode. You may be facing some kind of installation problem. After doing lots of tests I can still see a clear difference between geometric and weight mean in how the average loudness oscillates.

I installed it from repo for Ubuntu. https://github.com/wwmm/pulseeffects/wiki/Package-Repositories#debian--ubuntu

**Comment by Mlocik97-issues** [comment]
Fixed after some plugin updates.
