### ISSUE TITLE
[BUG] AutoGain low level check stopped working in new update.

### ISSUE THREAD

**Issue by Mlocik97-issues** [wwmm/pulseeffects#654]
After updating from 4.6.8 to 4.7.2, low level check in Autogain stopped working.

Btw. I think, it would be nice to change init value of https://github.com/wwmm/pulseeffects/blob/8f21763e611126c0ae72584f67cb9d14a9a2fded/src/autogain/gstpeautogain.cpp#L202
to something better, so at start it would not change volume so fast.

**Comment by wwmm** [comment]
That is weird. I don't think I touched the autogain in the last releases.

**Comment by Mlocik97** [comment]
ok, these was only bug in my PE.

**Comment by Mlocik97-issues** [comment]
ok, this was bug only in my installation.
