### ISSUE TITLE
Add more directory for PulseEffects to look for presets other than ~/.config/PulseEffects

### ISSUE THREAD

**Issue by kevinsmia1939** [wwmm/pulseeffects#657]
Hello,

I'm thinking of making a package for installing PulseEffects presets so presets can be install from linux package manager.

The presets are simply move to ~/.config/PulseEffects, however, most (if not all?) linux package manager don't allow package to be install on user directory.

How about adding /usr/share/PulseEffects for installing presets?

Thanks.

**Comment by Digitalone1** [comment]
Good idea. The proper place would be `/etc/pulseeffects` and, like pulseaudio, the local config folder takes the highest priority.

**Comment by Digitalone1** [comment]
@wwmm Thanks for merging the PR.

Anyway, are you sure to take in consideration only `/etc/xdg/` folder for system configuration? Most of the distributions uses `/etc/`, just like mpv. Maybe we can add `/etc/` to the array and reorder to eliminate duplicates if the environment variable already set it.

I can write the code for this.

**Comment by wwmm** [comment]
I am fine with adding more paths. No problems.

**Comment by Digitalone1** [comment]
Can be closed.
