### ISSUE TITLE
avoid-resampling=yes not working with pulseaudio 13.99.1

### ISSUE THREAD

**Issue by Neo595** [wwmm/pulseeffects#659]
Hello again, 
I 'm still following discussions on my issue;
I 'm moving to ubuntu 20.04 lately
Pulseaudio version :  pulseaudio 13.99.1
Latest build from pulseeffects installed : 4.7.2-3~focal2
From my test, no resampling feature works fine after a pulseffect -q (on the fly)

But when I launch again pulseeffects I see : 
(pulseeffects:3007): pulseeffects-WARNING **: 16:21:08.805: pulse_info: pulseaudio --dump-conf : execve failed: Permission non accordée (permission not granted)

(pulseeffects:3007): pulseeffects-WARNING **: 16:21:08.807: pulse_info: pulseaudio --dump-resample-methods : execve failed: Permission non accordée (permission not granted)

as user, I can get successufully the output of : pulseaudio --dump-conf 
### Lecture à partir du fichier de configuration : /home/neo/.pulse//daemon.conf ###
daemonize = no
fail = yes
high-priority = yes
nice-level = -15
realtime-scheduling = no
realtime-priority = 9
allow-module-loading = yes
allow-exit = yes
use-pid-file = yes
system-instance = no
local-server-type = user
cpu-limit = no
enable-shm = yes
flat-volumes = no
rescue-streams = yes
lock-memory = no
exit-idle-time = -1
scache-idle-time = 20
dl-search-path = /usr/lib/pulse-13.99.1/modules
default-script-file = /home/neo/.pulse//default.pa
load-default-script-file = yes
log-target = 
log-level = notice
resample-method = soxr-vhq
avoid-resampling = yes
enable-remixing = yes
remixing-use-all-sink-channels = yes
remixing-produce-lfe = yes
remixing-consume-lfe = yes
lfe-crossover-freq = 0
default-sample-format = s32le
default-sample-rate = 96000
alternate-sample-rate = 44100
default-sample-channels = 2
default-channel-map = front-left,front-right
default-fragments = 2
default-fragment-size-msec = 48
enable-deferred-volume = yes
deferred-volume-safety-margin-usec = 1
deferred-volume-extra-delay-usec = 0
shm-size-bytes = 0
log-meta = no
log-time = no
log-backtrace = 0
rlimit-fsize = -1
rlimit-data = -1
rlimit-stack = -1
rlimit-core = -1
rlimit-rss = -1
rlimit-as = -1
rlimit-nproc = -1
rlimit-nofile = 256
rlimit-memlock = -1
rlimit-locks = -1
rlimit-sigpending = -1
rlimit-msgqueue = -1
rlimit-nice = 31
rlimit-rtprio = 9
rlimit-rttime = -1

pulseaudio --dump-resample-methods 
trivial
speex-float-0
speex-float-1
speex-float-2
speex-float-3
speex-float-4
speex-float-5
speex-float-6
speex-float-7
speex-float-8
speex-float-9
speex-float-10
speex-fixed-0
speex-fixed-1
speex-fixed-2
speex-fixed-3
speex-fixed-4
speex-fixed-5
speex-fixed-6
speex-fixed-7
speex-fixed-8
speex-fixed-9
speex-fixed-10
ffmpeg
auto
copy
peaks
soxr-mq
soxr-hq
soxr-vhq

I hope it can help to understand why some configurations are working fine and some others not at all.
Can I help doing traces ? what is the command to launch ?

Regards
A.

**Comment by wwmm** [comment]
Did you install through flatpak? This may be the reason why there are permission errors. I don't think that PE can access Pulseaudio executable when package through flatpak.

Are you sure you have to kill PE for the `avoid-resampling` feature to work? How did you test that?

**Comment by Neo595** [comment]
Hello my answers : 
Did you install through flatpak? This may be the reason why there are permission errors. I don't think that PE can access Pulseaudio executable when package through flatpak.
> No, standard PPA access through synaptic

Are you sure you have to kill PE for the avoid-resampling feature to work? How did you test that?
> As you have seen, avoid-resampling is activated in my "daemon.conf" 
> preferred sampling rate are set to 96K and 44.1K
So at start-up PA is active and PE also;
Most of the time PE took 44,1K as reference sampling
Then try to play various files with 44,1Khz, 48, 88,2 96 then look into PE panels (with diifrent players as VLC, SmPlayer based on MPV, internal chrome player,... :
![image](https://user-images.githubusercontent.com/25134439/79722785-f9017c80-82e4-11ea-8cc3-949d98f1190e.png)
play a 48KHz track mpv :
![image](https://user-images.githubusercontent.com/25134439/79722921-36660a00-82e5-11ea-9d7e-5d2b5aca5c1c.png)
play the same with vlc : 
![image](https://user-images.githubusercontent.com/25134439/79722997-57c6f600-82e5-11ea-90fd-e7a6d7b8cbf6.png)
Chrome is resampling any sound to 96K
![image](https://user-images.githubusercontent.com/25134439/79723134-8ba21b80-82e5-11ea-8351-db655f555783.png)
88KHz track with VLC
![image](https://user-images.githubusercontent.com/25134439/79723285-c60bb880-82e5-11ea-8e63-dfe73d7fefcd.png)
![image](https://user-images.githubusercontent.com/25134439/79723329-d7ed5b80-82e5-11ea-9390-ee3cfe86c339.png)
88KHz track with smplayer
![image](https://user-images.githubusercontent.com/25134439/79723369-eb002b80-82e5-11ea-9725-bd917b81493a.png)
Even 96K is resampled (not taking into account  : default-sample-rate = 96000
![image](https://user-images.githubusercontent.com/25134439/79723458-17b44300-82e6-11ea-9ed4-d1b9ead5b039.png)

Then launch pulseefects -q
pkill pulseeffects
Then play with mpv 44.1Khz sample
pacmd list-sink-inputs
_1 sink input(s) available.
    index: 7
	driver: <protocol-native.c>
	flags: 
	state: RUNNING
	sink: 4 <alsa_output.pci-0000_03_05.0.iec958-stereo>
	volume: front-left: 62914 /  96% / -1,06 dB,   front-right: 62914 /  96% / -1,06 dB
	        balance 0,00
	muted: no
	current latency: 232,83 ms
	requested latency: 96,00 ms
	sample spec: float32le 2ch 44100Hz
	channel map: front-left,front-right
	             Stéréo
	**resample method: copy**
	module: 1
	client: 34 <SMPlayer>
	properties:
		media.icon_name = "SMPlayer"
		media.name = "Giorgio Moroder - Chase [Midnight Express] (1978) - mpv"
		application.name = "SMPlayer"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "33"
		application.process.id = "4436"
		application.process.user = "neo"
		application.process.host = "neo-system"
		application.process.binary = "mpv"
		application.language = "C"
		window.x11.display = ":0.0"
		application.process.machine_id = "d077c6961f4141db849369b8649b1d83"
		application.process.session_id = "c1"
		module-stream-restore.id = "sink-input-by-application-name:SMPlayer"_

**Then play 48Khz : pacmd list-sink-inputs**

 _sink input(s) available.
    index: 8
	driver: <protocol-native.c>
	flags: 
	state: RUNNING
	sink: 4 <alsa_output.pci-0000_03_05.0.iec958-stereo>
	volume: front-left: 62914 /  96% / -1,06 dB,   front-right: 62914 /  96% / -1,06 dB
	        balance 0,00
	muted: no
	current latency: 229,08 ms
	requested latency: 96,00 ms
	sample spec: float32le 2ch 48000Hz
	channel map: front-left,front-right
	             Stéréo
	**resample method: copy**
	module: 1
	client: 36 <SMPlayer>
	properties:
		media.icon_name = "SMPlayer"
		media.name = "Infinity Ink - Infinity (Original Mix) - mpv"
		application.name = "SMPlayer"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "33"
		application.process.id = "4781"
		application.process.user = "neo"
		application.process.host = "neo-system"
		application.process.binary = "mpv"
		application.language = "C"
		window.x11.display = ":0.0"
		application.process.machine_id = "d077c6961f4141db849369b8649b1d83"
		application.process.session_id = "c1"
		module-stream-restore.id = "sink-input-by-application-name:SMPlayer"_

**Then play 88.2Khz : pacmd list-sink-inputs**
_1 sink input(s) available.
    index: 9
	driver: <protocol-native.c>
	flags: 
	state: RUNNING
	sink: 4 <alsa_output.pci-0000_03_05.0.iec958-stereo>
	volume: front-left: 62914 /  96% / -1,06 dB,   front-right: 62914 /  96% / -1,06 dB
	        balance 0,00
	muted: no
	current latency: 96,37 ms
	requested latency: 96,00 ms
	sample spec: s32le 2ch 88200Hz
	channel map: front-left,front-right
	             Stéréo
	**resample method: (null)**
	module: 1
	client: 38 <SMPlayer>
	properties:
		media.icon_name = "SMPlayer"
		media.name = "Giorgio by Moroder - mpv"
		application.name = "SMPlayer"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "33"
		application.process.id = "5249"
		application.process.user = "neo"
		application.process.host = "neo-system"
		application.process.binary = "mpv"
		application.language = "C"
		window.x11.display = ":0.0"
		application.process.machine_id = "d077c6961f4141db849369b8649b1d83"
		application.process.session_id = "c1"
		module-stream-restore.id = "sink-input-by-application-name:SMPlayer"_


**Then play 96Khz : pacmd list-sink-inputs**
_1 sink input(s) available.
    index: 10
	driver: <protocol-native.c>
	flags: 
	state: RUNNING
	sink: 4 <alsa_output.pci-0000_03_05.0.iec958-stereo>
	volume: front-left: 62914 /  96% / -1,06 dB,   front-right: 62914 /  96% / -1,06 dB
	        balance 0,00
	muted: no
	current latency: 89,58 ms
	requested latency: 96,00 ms
	sample spec: s32le 2ch 96000Hz
	channel map: front-left,front-right
	             Stéréo
	**resample method: (null)**
	module: 1
	client: 40 <SMPlayer>
	properties:
		media.icon_name = "SMPlayer"
		media.name = "Papa  Was A Rolling Stone - mpv"
		application.name = "SMPlayer"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "33"
		application.process.id = "5319"
		application.process.user = "neo"
		application.process.host = "neo-system"
		application.process.binary = "mpv"
		application.language = "C"
		window.x11.display = ":0.0"
		application.process.machine_id = "d077c6961f4141db849369b8649b1d83"
		application.process.session_id = "c1"
		module-stream-restore.id = "sink-input-by-application-name:SMPlayer"_


**After restarting PE, playing again the same track, then a 48K sampling track :** 

2 sink input(s) available.
    index: 13
	driver: <protocol-native.c>
	flags: START_CORKED 
	state: RUNNING
	sink: 4 <alsa_output.pci-0000_03_05.0.iec958-stereo>
	volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        balance 0,00
	muted: no
	current latency: 35,16 ms
	requested latency: 96,00 ms
	sample spec: float32le 2ch 96000Hz
	channel map: front-left,front-right
	             Stéréo
	**resample method: copy**
	module: 1
	client: 44 <PulseEffects>
	properties:
		application.id = "com.github.wwmm.pulseeffects.sinkinputs"
		media.name = "Playback Stream"
		application.name = "PulseEffects"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "33"
		application.icon_name = "pulseeffects"
		application.process.id = "5479"
		application.process.user = "neo"
		application.process.host = "neo-system"
		application.process.binary = "pulseeffects"
		application.language = "fr_FR.UTF-8"
		window.x11.display = ":0"
		application.process.machine_id = "d077c6961f4141db849369b8649b1d83"
		application.process.session_id = "c1"
		module-stream-restore.id = "sink-input-by-application-id:com.github.wwmm.pulseeffects.sinkinputs"
    index: 14
	driver: <protocol-native.c>
	flags: 
	state: RUNNING
	sink: 7 <PulseEffects_apps>
	volume: front-left: 62914 /  96% / -1,06 dB,   front-right: 62914 /  96% / -1,06 dB
	        balance 0,00
	muted: no
	current latency: 91,33 ms
	requested latency: 50,00 ms
	sample spec: float32le 2ch 48000Hz
	channel map: front-left,front-right
	             Stéréo
	resample method: soxr-vhq
	module: 1
	client: 47 <SMPlayer>
	properties:
		media.icon_name = "SMPlayer"
		media.name = "Infinity Ink - Infinity (Original Mix) - mpv"
		application.name = "SMPlayer"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "33"
		application.process.id = "5858"
		application.process.user = "neo"
		application.process.host = "neo-system"
		application.process.binary = "mpv"
		application.language = "C"
		window.x11.display = ":0.0"
		application.process.machine_id = "d077c6961f4141db849369b8649b1d83"
		application.process.session_id = "c1"
		module-stream-restore.id = "sink-input-by-application-name:SMPlayer"

**Comment by wwmm** [comment]
Sometimes `avoid-resampling` can be a little tricky. The reason is that Pulseaudio is able to change the rate only when the sound card device is idle. If there is anything playing audio it does not change the device rate.

When no app is playing audio PE pauses its pipeline. But it waits 5 seconds before doing this because of another problems we had with mpv in the past when we paused its pipeline as soon as no audio app was active. What may be happening is that you changed tracks before 5 seconds have passed.
