### ISSUE TITLE
Equalizer & other effects not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by nxtof** [wwmm/pulseeffects#661]
Hello,

Just installed PulseEffects. I am able to control the volume / output using it, but any effect (including the equalizer) doesn't seem to have any impact on the output. Note that I _can_ activate effects (including the equalizer) but they just don't do anything.

Any idea?

Ubuntu & kernel versions:

```
$ lsb_release -a && uname -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
Linux (redacted) 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Relevant package versions:

```
$ dpkg -l | grep -E '(pulse|lsp-plugins)'
ii  gstreamer1.0-adapter-pulseeffects:amd64     4.7.2-3~bionic2                                  amd64        Gstreamer adapter
ii  gstreamer1.0-autogain-pulseeffects:amd64    4.7.2-3~bionic2                                  amd64        Gstreamer crystalizer
ii  gstreamer1.0-convolver-pulseeffects:amd64   4.7.2-3~bionic2                                  amd64        Gstreamer convolver
ii  gstreamer1.0-crystalizer-pulseeffects:amd64 4.7.2-3~bionic2                                  amd64        Gstreamer crystalizer
ii  gstreamer1.0-pulseaudio:amd64               1.14.5-0ubuntu1~18.04.1                          amd64        GStreamer plugin for PulseAudio
ii  libcanberra-pulse:amd64                     0.30-5ubuntu1                                    amd64        PulseAudio backend for libcanberra
ii  libpulse-mainloop-glib0:amd64               1:12.2-9~bionic1                                 amd64        PulseAudio client libraries (glib support)
ii  libpulse0:amd64                             1:12.2-9~bionic1                                 amd64        PulseAudio client libraries
ii  libpulsedsp:amd64                           1:12.2-9~bionic1                                 amd64        PulseAudio OSS pre-load library
ii  lsp-plugins                                 1.1.15-1~bionic1                                 all          LSP (Linux Studio Plugins) audio-plugins package
ii  lsp-plugins-jack                            1.1.15-1~bionic1                                 amd64        LSP (Linux Studio Plugins) JACK plugins
ii  lsp-plugins-ladspa                          1.1.15-1~bionic1                                 amd64        LSP (Linux Studio Plugins) LADSPA plugins
ii  lsp-plugins-lv2                             1.1.15-1~bionic1                                 amd64        LSP (Linux Studio Plugins) LV2 plugins
ii  lsp-plugins-vst                             1.1.15-1~bionic1                                 amd64        LSP (Linux Studio Plugins) VST plugins
ii  pulseaudio                                  1:12.2-9~bionic1                                 amd64        PulseAudio sound server
ii  pulseaudio-equalizer                        1:12.2-9~bionic1                                 amd64        Equalizer sink module for PulseAudio sound server
ii  pulseaudio-module-bluetooth                 1:12.2-9~bionic1                                 amd64        Bluetooth module for PulseAudio sound server
ii  pulseaudio-module-gconf                     1:12.2-9~bionic1                                 amd64        GConf module for PulseAudio sound server
ii  pulseaudio-module-zeroconf                  1:12.2-9~bionic1                                 amd64        Zeroconf module for PulseAudio sound server
ii  pulseaudio-utils                            1:12.2-9~bionic1                                 amd64        Command line tools for the PulseAudio sound server
ii  pulseeffects                                4.7.2-3~bionic2                                  amd64        Sound input and output effects for PulseAudio
```

Thank you!

**Comment by Troublicious** [comment]
Hello,
i got the exact same problem here on Ubuntu 20.04 with kernel 5.4.0-25.
The button to activate equaliser is sometimes greyed out, and sometimes not: when it is possible to activate it, it has no effects on sound, and the bar showing ouptut (at the bottom on equaliser screen) is not moving at all.

**Comment by wwmm** [comment]
Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Let's see what is printed in the terminal.

**Comment by zacharyneveu** [comment]
I have an existing install that is running into the same symptoms after running apt updates the past week. Not sure exactly what update broke it, since I usually only run minimal EQ/convolution effects. My debug output does not appear to show any missing plugins or errors of any kind, but all effects are not working (tested by setting drastic changes for each effect that I'd notice). Not sure what exactly I updated about Ubuntu that might have caused this but happy to collect debug info for you @wwmm.

**Comment by wwmm** [comment]
@Troublicious in your case the source of the problem is problem a GStreamer bug where it does not update its cache after plugins install/uninstall. Usually removing its cache solves the problem `rm -rf ~/.cache/gstreamer-1.0`. I suggest you try this too @zacharyneveu

**Comment by wwmm** [comment]
@Troublicious also make sure you have `Linux Studio Plugins` installed.

**Comment by wwmm** [comment]
@zacharyneveu which `Linux Studio Plugins` version do you have installed? Versions higher than `1.1.14` need PulseEffects `4.7.2`. Older PulseEffects versions only work with Linux Studio `1.1.13` or older

**Comment by wwmm** [comment]
Although theequilizer is from Linux Studio the convolver is a built-in PulseEffects plugin. But I think that on Ubuntu repositories our built-in plugins are split in optional packages. Check if you have any of them uninstalled

**Comment by Troublicious** [comment]
Everything is working perfectly, i just forgot to install lsp plugins !
`sudo apt install lsp-plugins` did the trick.

Thank you wwmm !

**Comment by wwmm** [comment]
Giving the command to install lsp-plugins is a hard thing to do because it will depend on the distribution. Maybe a more efficient approach would be to have the package maintainers for each distribution to add lsp-plugins as a non optional dependency.

**Comment by zacharyneveu** [comment]
Finally solved my issue. After multiple uninstalls/re-installs, dependency checking etc., turned out simply resetting my settings fixed it, I must have messed something up in there.

**Comment by mrpickles2000** [comment]
I had a similar problem to @zacharyneveu and simply resetting my settings also fixed it. I had activated process all inputs don't know if that was the thing that caused any problems..

**Comment by jaakkopasanen** [comment]
I was struggling with this problem until I found this issue thread. I was missing lsp-plugins entirely on my fresh 20.04 Ubuntu. The installation instructions do not mention that lsp-plugins are needed at all. It might be a good idea to at least add a mention somewhere in the wiki for this. Obviously the better option would be to have lsp-plugins as a dependency for the package.
