### ISSUE TITLE
rtkit-daemon.service not found, Segmentation fault

### ISSUE THREAD

**Issue by Haywire-dev** [wwmm/pulseeffects#666]
Hello, today I started having an issue with Pulseeffects, most likely after an **apt update** and a reboot.
Launching Pulseeffects works fine but as soon as I try to play a media it crashes. When I launch pulseeffects **from a terminal** I am getting this popping up:

```
(pulseeffects:6841): pulseeffects-WARNING **: 19:32:56.647: sie: rtkit: Failed to connect to system bus: Error calling StartServiceByName for org.freedesktop.RealtimeKit1: Unit rtkit-daemon.service not found.

(pulseeffects:6841): pulseeffects-WARNING **: 19:32:56.861: soe: rtkit: Failed to connect to system bus: Error calling StartServiceByName for org.freedesktop.RealtimeKit1: Unit rtkit-daemon.service not found.
Segmentation fault
```
Here is the **G_Messages_Debug Command Output :** https://pastebin.com/MpVxdvtH

I am using Debian Bullseye x64 with Cinnamon, Pulseaudio 11.1 and Pulseeffects 4.7.1-2+b1 (installed with apt).

**Comment by wwmm** [comment]
It is probably the same that is happening in #660. Debian Bullseye is also the system used there. I still have no idea about what has happened in this Debian update. So far my guess is that one of these packages must have had an installation problem after a update:

```
- glibmm
- rtkit
- dbus
```
At least on #660 the package versions are the same as the ones I have on Arch Linux. So an installation problem after an update seems more probable.

**Comment by wwmm** [comment]
As an workaround try to set `Priority Type` to `None`
![Screenshot from 2020-04-25 17-49-46](https://user-images.githubusercontent.com/16225172/80290661-2d2dd080-871d-11ea-8c12-7557a66800b2.png)

**Comment by Haywire-dev** [comment]
Setting the Priority Type to None seems to have solved the crashing issue, although I don't really know what is happening now, the sound is not outputting anymore, I can see the spectrum moving but no sound.
It doesn't seem that PulseEffects is the default device, so I'm not sure.

I don't really understand what is happening, unfortunate cause everything was working quite well. If I can do anything to help figuring out what is happening feel free to give me some steps.

**Comment by wwmm** [comment]
Take a look at this https://www.reddit.com/r/debian/comments/g46dip/activation_via_systemd_failed_for_unit. It seems that there are other programs affected

**Comment by Haywire-dev** [comment]
Applying the fix from that reddit post solved the issue for the moment.
Here is the steps I've done.
```
sudo cp /usr/lib/x86_64-linux-gnu/systemd/system/rtkit-daemon.service /etc/systemd/system/
sudo systemctl daemon-reload
systemctl enable rtkit-daemon
systemctl start rtkit-daemon
```
Instead of copying the file, I suppose a symlink could also work.
