### ISSUE TITLE
Every time I open an app, pulseeffects blasts my speakers to full volume

### ISSUE THREAD

**Issue by XxxOnlyN** [wwmm/pulseeffects#668]
With pulseeffects on, when I try to play a video or something, it changes my volume from whatever it's set to all the way up to 100%

**Comment by Digitalone1** [comment]
Can you specify when this happens and which applications are you using? Which distro also? This never happened to me.

Do you usually change the application volume or the device one?

Do you have pulseaudio flat-volume option enabled?

**Comment by wwmm** [comment]
`Do you have pulseaudio flat-volume option enabled?` Last time a user came here with this kind of problem `flat-volumes` enabled in Pulseaudio was the cause. PulseEffects does not touch you master volume. Something else is doing that.

**Comment by XxxOnlyN** [comment]
> Can you specify when this happens and which applications are you using? Which distro also? This never happened to me.
> 
> Do you usually change the application volume or the device one?
> 
> Do you have pulseaudio flat-volume option enabled?

I am using Zorin OS 15.2 Lite. When I open my default browser(Cliqz) with PulseEffects running and then when opening a video the volume control will go from whatever it's set to all the way up to 100% immediately. 
I change the volume using the volume keys on my keyboard usually.
I don't know what flat-volume is

**Comment by Digitalone1** [comment]
Post `/etc/pulse/daemon.conf` content.

**Comment by XxxOnlyN** [comment]
> Post `/etc/pulse/daemon.conf` content.

Nevermind I don't believe it's useful considering that the issue is now gone. This morning I reinstalled pulseaudio, pulseeffects, and alsa. So maybe that fixed it I guess

**Comment by roobre** [comment]
I was experiencing the same issue, adding `flat-volumes = no` to `daemon.conf` fixed it for me.
