### ISSUE TITLE
Setup as in Equalizer APO

### ISSUE THREAD

**Issue by wpbloger** [wwmm/pulseeffects#678]
Hello.
Maybe someone knows how to get the same results as in Equalizer APO.
As in the screenshot below:
![Image](https://i.imgur.com/BkvrUSs.png)
[Learn more about this setting. ](https://www.reddit.com/r/headphones/comments/cnrcc7/how_to_get_audeze_lcdlike_subbass_linearity_and/)

**Comment by wwmm** [comment]
These images should point you to the right direction:
![Screenshot from 2020-05-10 11-08-29](https://user-images.githubusercontent.com/16225172/81502170-acd9a480-92b2-11ea-9752-df82407ae9d9.png)
![Screenshot from 2020-05-10 11-37-09](https://user-images.githubusercontent.com/16225172/81502172-ae0ad180-92b2-11ea-9ac3-f7b952e6dedb.png)
![Screenshot from 2020-05-10 11-37-17](https://user-images.githubusercontent.com/16225172/81502174-aea36800-92b2-11ea-8812-f3fb38456086.png)

Under the hoods PulseEffects uses Linux Studio Plugins equalizer https://lsp-plug.in/?page=manuals&section=graph_equalizer_x32_lr. It has APO filters implemented. Just set each band mode to `APO (DR)`. What I am not sure about is what to do with its `slope` and "quality" parameters in the high shelf. Your image suggests that only the slope is set. But as far as I could understand Linux Studio sources the quality parameter is still used when APO filters are calculated. What should be done in this case @sadko4u?

**Comment by sadko4u** [comment]
For APO case, all controls try to reproduce the same control behaviour as APO filters do 'out of the box'. I specially asked @CrocoDuck to do this when he adapted APO's filter calculation routines to the LSP source tree.

According to the picture you've provided, you need to set **Q**uality value to 0.7071 to reproduce the characteristics of the filter.

You also always may launch standalone JACK version of plugins with dummy JACK driver if don't want to find proper JACK drivers on your system and look how these parameters affect the equalization curve.

**Comment by sadko4u** [comment]
For shelving filters I believe something like 0.707 (or sqrt(2)/2) can be used by default.

**Comment by wpbloger** [comment]
@wwmm , @sadko4u Thanks for the detailed explanation and an excellent PulseEffects program.
