### ISSUE TITLE
PulseEffects Equalizer Not Working

### ISSUE THREAD

**Issue by genes1122** [wwmm/pulseeffects#681]
I switched from Fedora to Opensuse Tumbleweed.  In Fedora, PulseEffects equalizer worked fine, but not in Opensuse.  Now, the input and output sliders change the volume, but the frequency band sliders have no effect.  All the switches appear to work, my player is active in Applications, and the equalizer itself is active.  The packages lsp-plugins-common and lv2-lsp-plugins are both installed.  However I get the following warnings when I start in debug mode:

$ pulseeffects -q
$ G_MESSAGES_DEBUG=pulseeffects pulseeffects
...
(pulseeffects:5159): GLib-GObject-WARNING **: 11:57:00.671: g_object_set_is_valid_property: object class 'lsp-plug-in-plugins-lv2-compressor-stereo' has no property named 'bypass'

(pulseeffects:5159): GLib-GObject-WARNING **: 11:57:00.717: g_object_set_is_valid_property: object class 'lsp-plug-in-plugins-lv2-para-equalizer-x32-lr' has no property named 'bypass'

(pulseeffects:5159): GLib-GObject-WARNING **: 11:57:00.777: g_object_set_is_valid_property: object class 'lsp-plug-in-plugins-lv2-comp-delay-x2-stereo' has no property named 'bypass'

(pulseeffects:5159): GLib-GObject-WARNING **: 11:57:00.786: g_object_set_is_valid_property: object class 'lsp-plug-in-plugins-lv2-compressor-stereo' has no property named 'bypass'

(pulseeffects:5159): GLib-GObject-WARNING **: 11:57:00.789: g_object_set_is_valid_property: object class 'lsp-plug-in-plugins-lv2-para-equalizer-x32-lr' has no property named 'bypass'

Is this a problem with the Opensuse build of lsp-plugins, or can you tweak pulseeffects to work around the missing property?

Regards,
Gene

**Comment by genes1122** [comment]
Also, I deleted the folder ~/.cache/gstreamer-1.0 and rebooted.  The same errors appeared afterwards.

Regards,
Gene

**Comment by Digitalone1** [comment]
> Is this a problem with the Opensuse build of lsp-plugins, or can you tweak pulseeffects to work around the missing property?

No, it's a problem with opensuse build of PulseEffects. The updated lsp-plugins without updating PulseEffects to the latest release.

Install from git and it should work.

**Comment by wwmm** [comment]
It is just like Digitalone1 has said. They have to upgrade to the latest PulseEffects version if they want to use lsp-plugins above `1.1.14`

**Comment by kevinsmia1939** [comment]
I'm on openSUSE Tumbleweed, what pulseeffects version are you using.
I have pulseeffects installed from  official repo, and it work just fine.

**Comment by wwmm** [comment]
Hi @kevinsmia1939 !

On Arch Linux I am still on Boost `1.72`. So I can't say for sure. But at first site I do not see a reason for `1.73` to cause problems.

**Comment by genes1122** [comment]
Thanks for all the information.  The only pulseeffects.rpm I found that's current, 4.7.2, is for Mageia Cauldron, so most distributions must not be running the latest lsp-plugins.  I don't have a build system installed yet, so I'll post a bug at opensuse and wait for them to update their build.

Regards,
Gene

**Comment by genes1122** [comment]
I see kevin is looking at fixing this already, so I'm going to reopen it.

Gene

**Comment by DelepY** [comment]
je viens de migrer sous xubuntu 20, et j'ai perdu l'equalizer : il ne veux pas s'activer.
(pulseeffects:6059): pulseeffects-WARNING **: 20:15:51.821: compressor plugin was not found!
(pulseeffects:6059): pulseeffects-WARNING **: 20:15:51.824: equalizer plugin was not found!
(pulseeffects:6059): pulseeffects-WARNING **: 20:15:51.879: delay plugin was not found!
(pulseeffects:6059): pulseeffects-WARNING **: 20:15:51.890: compressor plugin was not found!
(pulseeffects:6059): pulseeffects-WARNING **: 20:15:51.891: equalizer plugin was not found!
j'aurais préféré réduire les basse de mes enceintes... surtout pour les voisins.

**Comment by Digitalone1** [comment]
@DelepY it's not related to this issue, anyway install lsp-plugins package.

**Comment by genes1122** [comment]
@kevinsmia1939 So far, I've been unable to create an openSUSE account!  I'm guessing the server transfer is causing problems.  It would be great if you could file a bug or comment in the forums for me. 

Regards,
Gene

**Comment by genes1122** [comment]
Bug, https://bugzilla.opensuse.org/show_bug.cgi?id=1171896, filed, confirmed, and addressed for PulseEffects.  Now we wait for a boost update.

Regards,
Gene

**Comment by genes1122** [comment]
I have no idea how long we wait for a boost upgrade, but I'll close this issue now since the PulseEffects maintainer is working on it.

Gene

**Comment by Wello6143** [comment]
So hi @genes1122 I have to say that the guy who maintain `pulseeffects` package is a man full of laziness. We'll have to wait him to update it, or have to deal with terrible sound w/o equalizer.
Just move to arch if you need rolling. For me, guess I'll be back to ubuntu and get things done fastly.

**Comment by genes1122** [comment]
Actually, I installed the flatpak and created a new .desktop file in .config/auotstart with the correct command to start flatpak pulseeffects at login.  I found a private repo with boost 1.73 built, but I'm not sure if I can install that without breaking something else.

Gene

**Comment by Wello6143** [comment]
Our trouble is `lsp-plugins`, so `boost` doesn't involved in this issue. No matter what you gonna try to do with `boost*`, the issue's still there.

**Comment by Wello6143** [comment]
I'll try to build with OBS and will let you know ASAP if it's success.

**Comment by kevinsmia1939** [comment]
> Our trouble is `lsp-plugins`, so `boost` doesn't involved in this issue. No matter what you gonna try to do with `boost*`, the issue's still there.

Is it the issue with packaging lsp-plugins or lsp-plugins itself?

**Comment by Wello6143** [comment]
> Is it the issue with packaging lsp-plugins or lsp-plugins itself?

`lsp-plugins*` packages and some of other packages such as `lv2*` or `ladspa*`

**Comment by genes1122** [comment]
I'm sorry, but your are mistaken Wello6143.  While you certainly could downgrade lsp-plugins, you **should** upgrade pulseeffects after upgrading boost.  Otherwise, once boost is upgraded, you will have to upgrade both pulseeffects and lsp-plugins again.

Regards,
Gene

**Comment by Wello6143** [comment]
As wwmm has told to us above, his pulseeffects worked normally no matter what version of boost he's using. He said the main problem is if we want PE work with latest version of lsp-plugins, we need 4.7.2 version of PE since he has fixed the dependencies problems.
I've tried install older version of lsp-plugins from OBS but all of them are 1.1.4+, so there's no luck so far. About I have to upgrade PE after update boost, I had installed both of them at the same time.
I'll leave this issue since I'm not using tumbleweed anymore. This issue is annoying.

**Comment by wwmm** [comment]
As things are right now `Boost >= 1.72` is also necessary when using PE `4.7.1` because Boost deprecated a few headers usage. But if you downgrade PE so a older Boost can be used then using the latest lsp-plugins become a problem as at some point there were some changes in lsp that required changes to PulseEffects code. In my opinion the easiest solution would be to downgrade lsp as less packages depend on it and use a PE version that compiles with the Boost version available in opensuse repositories.

**Comment by wwmm** [comment]
PE `4.7.2` was released so newer lsp versions could be used. There is no critical bug fixed or amazing feature implemented. Most users can stay in `4.7.1` for a while with no problem. And using lsp `1.1.12` is fine. So the less painful solution would be to downgrade it and stay on PE `4.7.2` until a Boost upgrade can be made.

**Comment by genes1122** [comment]
I see that boost 1.74 is being built for openSUSE TW.  Do you see any problems with that for PE ?

Thanks,
Gene

**Comment by wwmm** [comment]
>I see that boost 1.74 is being built for openSUSE TW. Do you see any problems with that for PE 

I did not read Boost 1.74 release notes. So I don't really know. And Arch Linux is still on Boost `1.72`. Once it moves to 1.74 I will see if anything odd happens.

**Comment by genes1122** [comment]
PulseEffects 4.8 has been built for TW now, and everything is working fine with lsp-plugins 1.24.  Closing this one out.

**Comment by StellarisStudio** [comment]
Arf !!! And on Leap 15.2 we have lsp-plugins 1.24 but pulseeffect is still on 4.7.1 !!! what a shame !!
