### ISSUE TITLE
Convolver: Display a more intuitive frequency response?

### ISSUE THREAD

**Issue by torokati44** [wwmm/pulseeffects#684]
Please excuse the personal anecdote:
I wanted to filter out some constant annoying beeps from a regular conference call. Given that PulseEffects has a Convolver plugin, I thought I can do this easily with it.
I went with this instead of the Equalizer or the Filter plugins because I wanted to silence just a few really specific and quite narrow bands.

There are a number of great filter design apps online, but in the end I went with SciPy to produce the impulse response of my choice, using this snippet to compute the kernel, export it into an .irs file, and plot the weights and the spectrum: https://gist.github.com/torokati44/4bdcba8ba512ac9e6ee7363eeec6af49

There might be some mathematical nonsense in it, especially right after the FFT, but the plots make intuitive sense to me, and I can verify (by looking at the output spectrum with a noise source, or listening to a sine sweep or the original problematic audio) that it indeed does exactly what I designed it to do.

These are the plots produced by the script above, in time and frequency domain:

![impulse_response](https://user-images.githubusercontent.com/288816/82615227-3a2dca80-9bca-11ea-93dd-695be4de237e.png)

![frequency_response](https://user-images.githubusercontent.com/288816/82615260-46b22300-9bca-11ea-8c2b-71d0763e38e9.png)

And these are what I'm seeing in PulseEffects instead:

![impulse_response_pe](https://user-images.githubusercontent.com/288816/82615229-3ac66100-9bca-11ea-806c-e4630b701d7a.png)

![frequency_response_pe](https://user-images.githubusercontent.com/288816/82615262-46b22300-9bca-11ea-8d8f-c8c9c82cdf39.png)

The difference between the first ones might be just because of the quite small number of curve points (I think I found a maximum of around 200 hard-coded in the plugin UI code) producing aliasing (also, the logarithmic scale of the Y axis); but the second one in PulseEffects is mostly meaningless to me. Maybe I just don't know what I should be looking for, I'm not that experienced in audio processing.

For this kind of use case at least, I think showing something similar to my second plot in Spectrum mode, with a bit more resolution, would make more sense. What do you think? Would you accept a PR that either changes the current Spectrum mode, or adds a third option?

**Comment by wwmm** [comment]
Maybe I made a mistake when I used GStreamer's function to calculate the FFT. I will take a lookt. In any case feel free to make a PR improving this section

**Comment by torokati44** [comment]
From what I've seen so far, there are indeed some issues with the spectrum calculation.

First, if I'm not mistaken, it is computed from the samples that have already been interpolated to a "plottable" number of points, and even converted to decibels.

Also, I'm not sure windowing should be applied to the samples, because the most interesting bits are often at the very "ends" (even if in my particular case they might be in the middle), and windowing usually scales those samples down to almost zero, potentially losing a lot of information.

Additionally the FFT in GStreamer might not be the exact same algorithm as I've used in SciPy - the latter might be a more specialized variant I chose.

Again, I might be completely wrong on all of this though.

So far, the closest I could get the graph is (with a linear frequency scale at the moment):
![image](https://user-images.githubusercontent.com/288816/82678472-f5e20f00-9c49-11ea-9bc3-b779b864d98b.png)
It's "better": at least I can see the three suppressed frequency bands - but still doesn't seem right.
It's really noisy, and seems like it's inverted somehow?

**Comment by wwmm** [comment]
Now I am asking myself if plotting the amplitudes in decibel scale was a good idea. It has been so long I do not remember exactly why I did that. Maybe it was to make it easier to see small amplitude oscillations as there is no zoom function in that window. But maybe the proper course of action would be to plot the amplitudes in a linear scale and trying to add a zoom control somehow

**Comment by torokati44** [comment]
For the IRS samples, I also think that keeping them linear might make more sense. After all, it's a convolution kernel, so keeping its "shape" on the plot might be better. And in the time domain, I don't think I've ever seen even regular audio samples being plotted on a logarithmic scale. In frequency domain, it's quite different, having one or both axes logarithmic there might indeed make sense.

**Comment by wwmm** [comment]
I am doing a few quick tests on your PR and I think that both plots look better with a vertical linear scale. 

The spectrum already has the frequency axis in a log scale and is probably better to keep it this way.

**Comment by torokati44** [comment]
With #686 merged, I think this issue is resolved.
