### ISSUE TITLE
Stopping after suspend

### ISSUE THREAD

**Issue by timojuez** [wwmm/pulseeffects#690]
Awesome project, thank you! The issue: When I resume my laptop after suspend, pulseeffects are not active. The frequency measurement on top of the program is all black although sound is playing. I have to restart pulseeffects each time after suspend. On Ubuntu 19.10.

**Comment by wwmm** [comment]
At least on my desktop (Arch Linux and Gnome 3.36) suspend does not cause a problem. Everything is fine after resuming. Are you on a laptop? Maybe suspending on a desktop has a different behavior. Or Ubuntu is doing something more when suspending that Arch is not doing.

**Comment by timojuez** [comment]
I get the same effect when I just kill and restart pulseaudio. The blue bars freeze, PulseEffects is responsive but has no effect. Does a pulseaudio restart work for you?

**Comment by wwmm** [comment]
PulseEffects will freeze if Pulseaudio dies. Doing the "Pulseaudio state detection" that Pavucontrol does would be a little harder in our case. So I can see Pulseaudio dying being a problem.

I didn't have to do anything after suspending. Audio came back to life automatically.
