### ISSUE TITLE
"pulseeffects --gapplication-service" Often stops without error - killed in xsession

### ISSUE THREAD

**Issue by danielgul** [wwmm/pulseeffects#691]
Hey, 

I have a very strange issue that hunts me through different distributions, and frankly, I'm surprised that nobody posted about it. I've been occasionally coming here to see if someone experienced something similar to the issue I'm having and decided to change the startup script to the start service with debug (`G_MESSAGES_DEBUG=pulseeffects pulseeffects --gapplication-service`) to hopefully, with your help, solve this ones and for all.

So let me explain, I'm watching a lot of video all the time. YouTube on Brave, Firefox, Chromium, Twitch, VLC. There is always something playing. And occasionally I'm watching a lecture where I'm pausing the video every few minutes to wright things down for my studies. These are the points where the sounds suddenly stops and the service just crushes. I'm resuming the video and.. no sound from the video. Htop -> no Pulseeffects but PulseAudio still there and still does playing system sounds. Starting the window resumes the sound for the media (and the service).  

There were days when it crushed dozens of times, It really depended on the usage.
I'm using Pulseeffects since Mint 18 with Cinnamon all through Mint 19 to Manjaro 19 and now Manjaro 20, It crushed on all of them the same way. The only common denominator (besides the hardware) is that I've been using Cinnamon on all of them (dunno if it matters).

After it crushed today, I checked `coredumpctl list` and `sudo journalctl -xeb` and absolutely nothing mentioning Pulseeffects.
Only thing was in `.xsession-errors`. The process killed itself for no reason.
 
    ~/scripts/debug/pulseeffects/pe_debug.sh: line 3:  6452 Killed                  G_MESSAGES_DEBUG=pulseeffects pulseeffects --gapplication-service >> ~/.my_dump/logs/pulseeffects_service.log

Although, I gotta admit, starting the service like this made it more stable for some reason. It didn't crush Yesterday at all since I've done it. And my session was up since 7am today (until it crushed just before midnight).

This is the debug log the 1 hour before the crush (really shows what kind of a user I am lol):

    (pulseeffects:6452): pulseeffects-DEBUG: 23:01:50.598: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:01:50.611: sie: PAUSED -> PLAYING -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:01:50.612: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:02:12.743: sie: No app wants to play audio. We will pause our pipeline.
    (pulseeffects:6452): pulseeffects-DEBUG: 23:02:12.749: sie: PLAYING -> PAUSED -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:03:41.715: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:03:41.716: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:03:41.717: sie: PAUSED -> PLAYING -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:03:41.717: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:07:52.742: sie: No app wants to play audio. We will pause our pipeline.
    (pulseeffects:6452): pulseeffects-DEBUG: 23:07:52.745: sie: PLAYING -> PAUSED -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:07:52.772: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:07:52.774: sie: PAUSED -> PLAYING -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:07:52.774: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:10:22.743: sie: No app wants to play audio. We will pause our pipeline.
    (pulseeffects:6452): pulseeffects-DEBUG: 23:10:22.745: sie: PLAYING -> PAUSED -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:10:34.489: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:10:34.491: sie: PAUSED -> PLAYING -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:10:34.491: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:11:35.743: sie: No app wants to play audio. We will pause our pipeline.
    (pulseeffects:6452): pulseeffects-DEBUG: 23:11:35.749: sie: PLAYING -> PAUSED -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:16:09.417: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:16:09.427: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:16:09.428: sie: PAUSED -> PLAYING -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:16:09.428: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:16:55.743: sie: No app wants to play audio. We will pause our pipeline.
    (pulseeffects:6452): pulseeffects-DEBUG: 23:16:55.744: sie: PLAYING -> PAUSED -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:18:18.560: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:18:18.562: sie: PAUSED -> PLAYING -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:18:18.562: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:19:47.742: sie: No app wants to play audio. We will pause our pipeline.
    (pulseeffects:6452): pulseeffects-DEBUG: 23:19:47.745: sie: PLAYING -> PAUSED -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:37:09.503: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:37:09.510: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:37:09.511: sie: PAUSED -> PLAYING -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:37:09.511: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:38:33.742: sie: No app wants to play audio. We will pause our pipeline.
    (pulseeffects:6452): pulseeffects-DEBUG: 23:38:33.749: sie: PLAYING -> PAUSED -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:39:42.778: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:39:42.784: sie: PAUSED -> PLAYING -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:39:42.784: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:41:32.742: sie: No app wants to play audio. We will pause our pipeline.
    (pulseeffects:6452): pulseeffects-DEBUG: 23:41:32.749: sie: PLAYING -> PAUSED -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:43:38.687: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:43:38.689: sie: PAUSED -> PLAYING -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:43:38.689: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:53:42.743: sie: No app wants to play audio. We will pause our pipeline.
    (pulseeffects:6452): pulseeffects-DEBUG: 23:53:42.745: sie: PLAYING -> PAUSED -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:54:20.021: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:54:20.023: sie: PAUSED -> PLAYING -> VOID_PENDING
    (pulseeffects:6452): pulseeffects-DEBUG: 23:54:20.024: sie: total latency: 141 ms
    (pulseeffects:6452): pulseeffects-DEBUG: 23:57:52.743: sie: No app wants to play audio. We will pause our pipeline.

Besides the crushing and the annoyance, Pulseeffects works perfectly. No sound quality issues, no lagging, no crackling and all the modules that I'm using works great.  

![cleaned](https://user-images.githubusercontent.com/17614825/82845891-ffd86c00-9eee-11ea-967c-bb2d790f31e4.png)

I've been playing around with the modules a lot these past years and it didn't really mattered which modules I used, the service crushed all the same. 
Btw, It also doesn't matter if the window is open or not, the service stops and if it happens when the window is open, it closes too.  

Despite this issue, This is still one of my absolute favorite Linux programs. It's absolutely amazing and thank you @wwmm for making it and being so active on the issues board.

I hope there is a solution,
Thanks in advance, 
Daniel

**Comment by wwmm** [comment]
It seems this will be a hard one to fix. In these cases I always hope that something useful will come in the output of `coredumpctl info`. But as your installation probably does not have debug symbols it has nothing. 

Does Manjaro still use Arch Linux packages? I am on Arch Linux and I can't remember the last time I saw PulseEffects crashing so easily. In any case it seems that restarting our pipeline a lot is what triggers the crash in your computer somehow.

When PE pipeline starts one of the critical things done is setting thread priorities. Maybe this is not going well on your systems for some unknown reason.
![Screenshot from 2020-05-25 21-09-55](https://user-images.githubusercontent.com/16225172/82848948-1e793b80-9ecc-11ea-91f7-38a702d793f3.png)
Try to run with priority type set to none for a while and see if it makes any difference.

**Comment by danielgul** [comment]
Are you referring to https://www.archlinux.org/packages/?name=gdb when you say debug symbols? 

Yeah, Manjaro is based on Arch. It has pacman and AUR and all that shabang. In terms of package versions, its about a week behind arch. 

I had a feeling that changing the process priority had something to do with that. As I changed the service startup script, it initializes it on normal priority rather then low as the default. Maybe because I initialize it through sh with a script? May explain why the process is a lot more stable then before.

I'm not an expert by any means, I do wonder if running the service under systemd rather then as a process has any benefit. What do you think? 

Changed the priority type anyhow, lets hope it makes a difference. 

Thanks for the reply.

**Comment by wwmm** [comment]
Yes. But as Arch repositories do not have debug symbols you would have to compile PE yourself or somehow force the AUR pkgbuild to compile PE in debug mode when generating the package.

Using a shell script should not change the priority type setting in the image above. That is weird. Unless the user do that in PE window this setting should stay the same no matter how you start PE. Was it executed by the same user in both cases? I ask because from time to time I see people running PE as root.

Trying to run PE as a systemd  service will only bring headaches. The reason is that PE service is not the usual kind of service. The option `--gapplication-service` is provided by GTK. You can think of it as a "poor man" service for apps that have a graphical interface. It is just no showing the window and running in the background. Everything else related to the window is initialized and loaded. So PE can't be initialized before the desktop is loaded for the same reason you can't open any other app that has an interface.

**Comment by danielgul** [comment]
> Yes. But as Arch repositories do not have debug symbols you would have to compile PE yourself or somehow force the AUR pkgbuild to compile PE in debug mode when generating the package.

I see, so I'll have to install `gdb` and build-reinstall Pulseeffects from source to have symbols, right?
https://aur.archlinux.org/packages/pulseeffects-git
Any ideas on what to change in `PKGBUILD` so it would compile with the debug? I have no idea and never worked with build files... 

> Using a shell script should not change the priority type setting in the image above. That is weird. Unless the user do that in PE window this setting should stay the same no matter how you start PE. Was it executed by the same user in both cases? I ask because from time to time I see people running PE as root.

I had never initialized PE service as root, but still it changed the service priority when I started the process with `sh`:
![pe_proc cleaned](https://user-images.githubusercontent.com/17614825/82903366-83cf3a00-9f69-11ea-9cd8-49a5c1de0307.png)

>  Trying to run PE as a systemd service will only bring headaches. The reason is that PE service is not the usual kind of service. The option --gapplication-service is provided by GTK. You can think of it as a "poor man" service for apps that have a graphical interface. It is just no showing the window and running in the background. Everything else related to the window is initialized and loaded. So PE can't be initialized before the desktop is loaded for the same reason you can't open any other app that has an interface.

Alright, no systemd then. Is there any way to make the process persistent or to make it restart unless stopped? 

Thanks in advance.

**Comment by wwmm** [comment]
There is no automatic restart mechanism because it is very unusual to have frequent crashes. We have to find out what is causing this.

You do not need to use gdb if you are not used to it. If PulseEffects is compiled with debug symbols coredumpctl will show something useful. At least it does most of the times. I never tried to make an Arch package with debug symbols. But inside the aur pkgbuild you will see a line with `arch-meson`. This command help shows it accepts `--debug` as option. So try to change the line `36` to `arch-meson --debug`. The question is if you have to edit `/etc/makepkg.conf` too.

The priority shown in your image is fine. Maybe I did not understand what you really meant. The priority setting in PE menu only changes the priority of threads created when our pipeline starts to play. Threads that do not handle audio like the main thread are not touched. So I would expect the main thread to be shown as `Normal`. I don't know if every graphical process monitor shows child threads info. At least on top and htop you can see info for each program thread. Only then you can see those priorities changes in PE menu.

**Comment by danielgul** [comment]
> You do not need to use gdb if you are not used to it. If PulseEffects is compiled with debug symbols coredumpctl will show something useful. At least it does most of the times. I never tried to make an Arch package with debug symbols. But inside the aur pkgbuild you will see a line with arch-meson. This command help shows it accepts --debug as option. So try to change the line 36 to arch-meson --debug. The question is if you have to edit /etc/makepkg.conf too.

Will try that on a VM first to avoid screwing stuff up and ill report back on that, Thanks.

> The priority shown in your image is fine. Maybe I did not understand what you really meant. The priority setting in PE menu only changes the priority of threads created when our pipeline starts to play. Threads that do not handle audio like the main thread are not touched. So I would expect the main thread to be shown as Normal. I don't know if every graphical process monitor shows child threads info. At least on top and htop you can see info for each program thread. Only then you can see those priorities changes in PE menu.

You are absolutely right. How it works totally makes sense now. 
You also made me realize that I don't know anything about process priority and niceness lol.

So I took the time to read about it and how it works. Done some playing around with the process values and reached some kind of a stable point with niceness -11. Why niceness -11? I've seen that PulseAudio had these values and priority so wth, right?

I really wanna test it out until the next crush. Hopefully by then ill sort debug symbols and would be able to provide you with some concrete data.

I've made a video on Youtube to showcase how it works now :-) :
[![PulseEffects on Majaro Linux 20 - Process stress test](http://img.youtube.com/vi/Md8d42mOd6c/0.jpg)](http://www.youtube.com/watch?v=Md8d42mOd6c "PulseEffects on Majaro Linux 20 - Process stress test")

**Comment by danielgul** [comment]
@wwmm 
Alright, 3 days have passed since I changed process priority to -11 niceness and didn't experienced a single crush. I even enable 5 more modules in an attempt to crush the process and its holding on without a hitch.

I guess the problem had to do with the priorities. Thanks for pointing me towards that direction. 
It never DIDN'T crush for so long lol.
