### ISSUE TITLE
Pulseeffects no sound 

### ISSUE THREAD

**Issue by londere** [wwmm/pulseeffects#693]
Hi there, Idk what happens, after installing the app the enhancements work, but after an update the app brakes, as an example if I play sound in Chrome it did not send any output, even the sine wave test didn't work, I need to disable the app on the Pulseeffects, here are some sc.

And here is the result of restart the app in debug mode:

`GG_MESSAGES_DEBUG=pulseeffects pulseeffects

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.450: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.451: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.451: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.451: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.451: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.451: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.451: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.452: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.452: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.452: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.452: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.453: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.453: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.454: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.454: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.455: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.455: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.457: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.457: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.458: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.458: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.460: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.460: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.460: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.460: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.460: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.460: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.461: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.461: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.461: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.461: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.462: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.462: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.462: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.462: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.463: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.463: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.464: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.464: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.464: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.464: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.464: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.464: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.464: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.464: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.465: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.465: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.465: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.465: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.465: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.465: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.465: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.465: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.465: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.465: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.466: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.466: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.466: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.466: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.466: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.466: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.467: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.467: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.467: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.467: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.467: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.467: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.468: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.468: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.468: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.468: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.468: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.468: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.468: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.468: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.469: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.469: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.469: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.469: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.469: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.469: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.469: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.469: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.469: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.469: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.470: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.470: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.470: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.470: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.470: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.470: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.470: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.470: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.471: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.471: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.471: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.471: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.471: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.471: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.471: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.471: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.471: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.471: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.472: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.472: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.472: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.472: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.472: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.472: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.472: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.472: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.473: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.473: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.474: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.474: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.474: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.474: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.475: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.475: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.475: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.475: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.476: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.476: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.478: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.478: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.480: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.480: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.481: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.481: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.481: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.481: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.483: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.483: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.484: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.484: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.485: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.485: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.486: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.486: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.487: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.487: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.488: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.489: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.489: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.489: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.490: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.490: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.492: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.492: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.493: g_param_spec_int: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:5061): GLib-GObject-CRITICAL **: 05:29:22.493: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(pulseeffects:5053): pulseeffects-CRITICAL **: 05:29:22.546: pulse_manager:  failed to get sink info: 

(pulseeffects:5053): pulseeffects-CRITICAL **: 05:29:24.544: sie: Internal data stream error.
`
My Device Setup:
![Captura de pantalla -2020-05-28 05-37-25](https://user-images.githubusercontent.com/47585952/83131431-7028ee00-a0a5-11ea-861d-13530855df56.png)
![Captura de pantalla -2020-05-28 05-37-03](https://user-images.githubusercontent.com/47585952/83131432-71f2b180-a0a5-11ea-9bac-4c59ac2c894a.png)
![Captura de pantalla -2020-05-28 05-36-57](https://user-images.githubusercontent.com/47585952/83131433-728b4800-a0a5-11ea-8cc9-20696838e4f5.png)
![Captura de pantalla -2020-05-28 05-36-09](https://user-images.githubusercontent.com/47585952/83131434-728b4800-a0a5-11ea-80fe-1eb4918695ed.png)

**Comment by wwmm** [comment]
How did you install PulseEffects? Through a flatpak package or apt-get? Usually I recommend people on Ubuntu 18.04 LTS to use flatpak. The old libraries in this Ubuntu version do not play nice with the PulseEffects package in the PPA. Lots of issues in the past...

At some point GStreamer release a version that showed lots of `gst-plugin-scanner` warnings like the yours. But as far as remember they were harmless. Something else must be causing the problem.

**Comment by londere** [comment]
I did install it via apt-get, I will try the flatpak, until them I will mark as resolved.
