### ISSUE TITLE
Playback Stuttering/Slowing when playing a lot of small tracks

### ISSUE THREAD

**Issue by Nonoreve** [wwmm/pulseeffects#694]
When playing a normal constant song like a music and above it using something that generates a lot of short sounds like this game https://orteil.dashnet.org/cookieclicker/ it becomes laggy. The music slows down and starts stuttering. I noticed that it creates a lot of entries in the application panel of PulseEffects. The lag stops as soon as the shorts sounds stops. 
I have this issue since reinstalled linux and switched from pure Ubuntu (probably 18.04) to Mint 18.04

**Comment by wwmm** [comment]
Another issue on Ubuntu 18.04... This Ubuntu version is really a headache... How did you install PulseEffects? Flatpak or apt-get?

How do I make this game generate lots of entries? Clicking on ball at the left side I see only one.

**Comment by Nonoreve** [comment]
When you spam click the cookie (like 10 clicks/second) it makes one sound per click. It installed it with flatpack.

**Comment by wwmm** [comment]
10 clicks/s ?! I don't think I am able to do that :D But I clicked as fast as I could. Somehow there is only one entry.

**Comment by Nonoreve** [comment]
Well I overestimated myself :) I'm around 5 clicks a second.

**Comment by Nonoreve** [comment]
It disapeared after the last pulseaudio update (12.2-2)
