### ISSUE TITLE
Reverberation

### ISSUE THREAD

**Issue by Ixoos** [wwmm/pulseeffects#7]
Everytime when I run pulseeffects, Level in reverberation is not working, it's showing value that I set (0.00) but I have to  change it to other value and back to value that I want, otherwise program thinks that Level in reverberation has default value.

**Comment by wwmm** [comment]
I am not sure I understand. Is reverberation being applied on startup even when PulseEffects was closed with level set to zero? Here it saves the last value and reapplies it on startup. Could you take a look at the reverb-user key in dconf? Here is mine when I set level to zero:

![screenshot from 2017-04-21 13-17-32](https://cloud.githubusercontent.com/assets/16225172/25286722/1e1db98e-2695-11e7-8f69-4115b728b2b9.png)

**Comment by Ixoos** [comment]
When i set it to 0, close and open the program there's showing that it is set to 0 but i hear that it isn't, I have to change it to other value other than 0 and then to 0. In dconf i have same values as yours.

**Comment by wwmm** [comment]
I was able to reproduce the bug here. Please test version 1.2.0 and tell me if it fixed it for you too.

**Comment by Ixoos** [comment]
It's working now. Thank you <3
