### ISSUE TITLE
Pulseeffects freezes on Zoom meeting 

### ISSUE THREAD

**Issue by addeps3** [wwmm/pulseeffects#701]
Hi, during these times of social distancing my usage of conferencing apps has increased. 

One such app is Zoom. I would love to be able to use an equalizer on the output, since sometimes low-end is undesirable. But in every case pulseeffects seems to freeze when Zoom engine is running, and essentially doesn't want to function overall. Attempting to restart the app while zoom is in a "meeting" will also freeze. Thats all there is to report.

Thank you. 

oh, this was in terminal:

```
 pulseeffects 

(pulseeffects:19959): pulseeffects-CRITICAL **: 09:15:26.096: pulse_manager: failed to move sink input: ZOOM VoiceEngine, idx = 1017 to PE

(pulseeffects:19959): pulseeffects-CRITICAL **: 09:15:26.104: pulse_manager: failed to move source output ZOOM VoiceEngine, idx =  to PE

(pulseeffects:19959): pulseeffects-CRITICAL **: 09:15:29.833: pulse_manager: failed to move sink input: ZOOM VoiceEngine, idx = 1017 to PE
```

Terminal also reports:

```
(pulseeffects:19959): pulseeffects-CRITICAL **: 09:15:26.104: pulse_manager: failed to move source output ZOOM VoiceEngine, idx =  to PE

(pulseeffects:20157): pulseeffects-CRITICAL **: 09:29:25.471: pulse_manager: failed to move source output ZOOM VoiceEngine, idx =  to PE

(pulseeffects:20187): pulseeffects-CRITICAL **: 09:30:07.938: pulse_manager: failed to move source output ZOOM VoiceEngine, idx =  to PE

(pulseeffects:20218): pulseeffects-CRITICAL **: 09:31:54.237: pulse_manager: failed to move source output ZOOM VoiceEngine, idx =  to PE`
```

**Comment by addeps3** [comment]
Any way to build a debug version?

**Comment by Digitalone1** [comment]
PulseEffects version and distribution used?

Debug mode can be executed by `G_MESSAGES_DEBUG=pulseeffects pulseeffects`.

**Comment by addeps3** [comment]
> PulseEffects version and distribution used?
> 
> Debug mode can be executed by `G_MESSAGES_DEBUG=pulseeffects pulseeffects`.

Hi. Thanks for bringing your attention to this. 
Im running Pulse 4.7.2 and what used to be Antergos. (they switched the repo's to Arch linux when that distro was abandoned). My distro runs, I would say, as well as an Arch install. 

`5.6.14-zen1-1-zen`

**Comment by addeps3** [comment]
`G_MESSAGES_DEBUG=pulseeffects pulseeffects 
(process:22076): pulseeffects-DEBUG: 11:42:39.835: main: locale directory: /usr/share/locale
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.914: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.914: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects/input
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.914: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects/output
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.914: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects/autoload
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.919: application: PE version: 4.7.2
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.920: pulse_manager: context is connecting
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.920: pulse_manager: context is authorizing
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.920: pulse_manager: context is setting name
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.921: pulse_manager: context is ready
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.921: pulse_manager: connected to: /run/user/1000/pulse/native
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.921: pulse_manager: protocol version: 33
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.921: pulse_manager: Pulseaudio version: 13.0
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.921: pulse_manager: default pulseaudio source: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.921: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_14.2.analog-stereo
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.921: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.922: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.922: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.922: pulse_manager:  failed to get sink info: PulseEffects_apps
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.923: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_apps sink_properties=device.description="PulseEffects(apps)"device.class="sound" norewinds=1
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.924: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.926: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.926: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.926: pulse_manager:  failed to get sink info: PulseEffects_mic
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.927: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_mic sink_properties=device.description="PulseEffects(mic)"device.class="sound" norewinds=1
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.975: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:39.976: sie: using output device: alsa_output.pci-0000_00_14.2.analog-stereo
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.019: sie: limiter is enabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.025: sie: compressor is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.028: sie: filter is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.129: sie: equalizer is enabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.133: sie: reverb is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.136: sie: bass_enhancer is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.140: sie: exciter is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.145: sie: crossfeed is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.154: sie: maximizer is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.161: sie: multiband_compressor is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.163: sie: loudness is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.167: sie: gate is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.172: sie: pitch is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.180: sie: multiband_gate is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.184: sie: deesser is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.188: sie: stereo_tools is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.194: sie: convolver is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.197: sie: crystalizer is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.199: sie: autogain is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.205: sie: delay is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.236: soe: using output device: PulseEffects_mic
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.236: soe: using input device: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.237: soe: limiter is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.238: soe: compressor is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.239: soe: filter is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.251: soe: equalizer is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.252: soe: reverb is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.254: soe: gate is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.255: soe: deesser is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.258: soe: pitch is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.266: soe: webrtc is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.267: soe: multiband_compressor is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.269: soe: multiband_gate is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.272: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.272: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects/input
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.272: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects/output
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.272: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects/autoload
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.272: presets_manager: destroyed
pulseeffects-INFO: 11:42:40.272: application: disabling global bypass
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.272: sie: bypass is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.272: soe: bypass is already disabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:40.669: convolver_ui: irs directory already exists: /home/adam/.config/PulseEffects/irs
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.309: sie: spectrum enabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.310: soe: spectrum enabled
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.815: sie: total latency: 0 ms
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.815: soe: total latency: 0 ms

(pulseeffects:22076): pulseeffects-CRITICAL **: 11:42:41.839: pulse_manager: failed to move sink input: ZOOM VoiceEngine, idx = 1017 to PE

(pulseeffects:22076): pulseeffects-CRITICAL **: 11:42:41.847: pulse_manager: failed to move source output ZOOM VoiceEngine, idx =  to PE
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.850: sie: using output device: alsa_output.pci-0000_00_14.2.analog-stereo
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.850: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_14.2.analog-stereo
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.850: pulse_settings_ui: added sink: alsa_output.pci-0000_00_14.2.analog-stereo
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.850: pulse_settings_ui: added source: alsa_input.usb-046d_09a4_1B611610-02.mono-fallback
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.850: soe: using input device: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.850: pulse_settings_ui: input device changed: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
(pulseeffects:22076): pulseeffects-DEBUG: 11:42:41.850: pulse_settings_ui: added source: alsa_output.pci-0000_00_14.2.analog-stereo.monitor`

**Comment by Digitalone1** [comment]
Let's wait for @wwmm for a better analysis.

Meanwhile try to redirect Zoom to PulseEffects through Pavucontrol. If I'm not mistaken, the issue should be on the stream from microphone not properly redirected from PulseEffects to Zoom. Anyway, check also if Zoom output stream is correctly sent to PE.

**Comment by wwmm** [comment]
>pulse_manager: failed to move sink input: ZOOM VoiceEngine, idx = 1017 to PE

This error is happening because ZOOM passed a flag to Pulseaudio that disables audio routing. In other words for some reason ZOOM developers are forcing Pulseaudio to only allow the default device to be used. This breaks PE. We had the same problem with other apps in the past and unfortunately there is nothing we can do about it. ZOOm developers have to change their code and allow audio routing.

**Comment by addeps3** [comment]
Ok, will you do the honors and close?
