### ISSUE TITLE
PE crashing and background service not working

### ISSUE THREAD

**Issue by SkyKeeper20** [wwmm/pulseeffects#702]
So, hello to everyone.
It started a few days ago. When I opened the PulseAudio Volume Control, it did not show the PE channels, but my bass was still enhanced. On the next day the problem was gone. 
Today, when I booted up my computer and wanted to hear some music over Spotify, there was no audio. Ok, I thought. I am used to problems like these because PE is sometimes a little tricky. (When i connect my headset, PE makes a mess out of my configuration. It wants the audio to be outputted through my mic and the input devices have configuration problems too.) I went in the PA Volume Control but I could not set the output device for Spotify, means the PE service is not running. I started PE. Here is the first problem:

When I want to start PE, it sometimes does not open. When I close PulseAudio, it sometimes starts, but not every time. Here is the terminal output: 

`...

(pulseeffects:2948): Gtk-WARNING **: 10:28:25.250: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:2948): Gtk-WARNING **: 10:28:25.250: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:2948): Gtk-WARNING **: 10:28:25.250: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:2948): Gtk-WARNING **: 10:28:25.250: Theme parsing error: gtk.css:83:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version

(pulseeffects:2948): GLib-CRITICAL **: 10:28:25.292: g_str_has_prefix: assertion 'str != NULL' failed
**
GLib-GObject:ERROR:../../../../gobject/gobject.c:4441:g_weak_ref_set: assertion failed: (weak_locations != NULL)
Abgebrochen (Speicherabzug geschrieben)`

(Which means "Aborted (core dumped)".)

Sometimes I have a Segmentation fault (core dumped), but it disappeared when I restarted.

Here some dmesg info: 

`[   93.382170] pulseeffects[1730]: segfault at 20 ip 00007f88a161ef2f sp 00007fffa69bbf78 error 4 in libgobject-2.0.so.0.5600.4[7f88a15e9000+52000]
[   93.382178] Code: 21 00 48 c1 ed 02 48 8b 34 e8 eb b6 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00 00 31 c0 48 85 ff 74 39 48 8b 17 48 85 d2 74 31 <48> 8b 12 48 81 fa fc 03 00 00 77 2d 48 8d 05 9e d3 21 00 48 c1 ea
[  266.779973] pulseeffects[2057]: segfault at 20 ip 00007fc343dcff2f sp 00007ffdbeb5cb68 error 4 in libgobject-2.0.so.0.5600.4[7fc343d9a000+52000]
[  266.779982] Code: 21 00 48 c1 ed 02 48 8b 34 e8 eb b6 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00 00 31 c0 48 85 ff 74 39 48 8b 17 48 85 d2 74 31 <48> 8b 12 48 81 fa fc 03 00 00 77 2d 48 8d 05 9e d3 21 00 48 c1 ea
[  274.632183] pulseeffects[2078]: segfault at 20 ip 00007f6cbdae4f2f sp 00007ffcaaa3ac58 error 4 in libgobject-2.0.so.0.5600.4[7f6cbdaaf000+52000]
[  274.632192] Code: 21 00 48 c1 ed 02 48 8b 34 e8 eb b6 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00 00 31 c0 48 85 ff 74 39 48 8b 17 48 85 d2 74 31 <48> 8b 12 48 81 fa fc 03 00 00 77 2d 48 8d 05 9e d3 21 00 48 c1 ea
[  503.617434] perf: interrupt took too long (2538 > 2500), lowering kernel.perf_event_max_sample_rate to 78750
[  741.438257] pulseeffects[2722]: segfault at 20 ip 00007fa1fda87f2f sp 00007fffef6a8038 error 4 in libgobject-2.0.so.0.5600.4[7fa1fda52000+52000]
[  741.438265] Code: 21 00 48 c1 ed 02 48 8b 34 e8 eb b6 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00 00 31 c0 48 85 ff 74 39 48 8b 17 48 85 d2 74 31 <48> 8b 12 48 81 fa fc 03 00 00 77 2d 48 8d 05 9e d3 21 00 48 c1 ea
[  754.541122] pulseeffects[2737]: segfault at 20 ip 00007fbf3464af2f sp 00007ffca3806378 error 4 in libgobject-2.0.so.0.5600.4[7fbf34615000+52000]
[  754.541136] Code: 21 00 48 c1 ed 02 48 8b 34 e8 eb b6 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00 00 31 c0 48 85 ff 74 39 48 8b 17 48 85 d2 74 31 <48> 8b 12 48 81 fa fc 03 00 00 77 2d 48 8d 05 9e d3 21 00 48 c1 ea
[  769.271869] pulseeffects[2756]: segfault at 20 ip 00007f8c55390f2f sp 00007ffe60042f38 error 4 in libgobject-2.0.so.0.5600.4[7f8c5535b000+52000]
[  769.271880] Code: 21 00 48 c1 ed 02 48 8b 34 e8 eb b6 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00 00 31 c0 48 85 ff 74 39 48 8b 17 48 85 d2 74 31 <48> 8b 12 48 81 fa fc 03 00 00 77 2d 48 8d 05 9e d3 21 00 48 c1 ea
[  985.131730] perf: interrupt took too long (3180 > 3172), lowering kernel.perf_event_max_sample_rate to 62750
[ 2275.288827] perf: interrupt took too long (3999 > 3975), lowering kernel.perf_event_max_sample_rate to 50000
`

Here is problem number two:

I have the tick for auto startup at login set, but my bass enhancement goes away when I close the GUI. I have the file in my ~/.config/ folder, but it does nothing.

Here the auto start file:

(File name: pulseeffects-service.desktop)
`[Desktop Entry]
Name=PulseEffects
Comment=PulseEffects Service
Exec=pulseeffects --gapplication-service
Icon=pulseeffects
StartupNotify=false
Terminal=false
Type=Application
` 
I really hope you guys can help me...

System specs: 

Kubuntu 18.04 64bit
Kernel 5.3.0-53-generic
PE version 4.7.2-3~bionic2
Installed over apt.

Just some background info: yesterday I played Minecraft with my brother and my system crashed. I had to use the magic SysReq-Buttons. Maybe this is some useful information.

**Comment by wwmm** [comment]
Ubuntu 18.04 libraries are too old for PulseEffects. People have had all sort of Problems when trying to use PulseEffects with it. I think that the best case scenario in your case would be to install PulseEffects through flatpak.

**Comment by SkyKeeper20** [comment]
Ok, thank you.
Btw. after I wrote the post today I left PE open for about 2 to 3 hours. Now everything works like a charm, even if I close the program.
But if you say so, I switch to the flatpak version.
