### ISSUE TITLE
EBU R 128 with autogain?

### ISSUE THREAD

**Issue by RubenKelevra** [wwmm/pulseeffects#705]
How close is the autogain plugin to R128 from EBU when set to target -23?

Is the algorithm comparable?

**Comment by wwmm** [comment]
As I did not do any measurement to compare the results the honest answer is I don't know. In the autogain plugin I use the library [libebur128](https://github.com/jiixyj/libebur128) to estimate the loudness. Then a volume correction factor is calculated based on the difference between the estimated loudness value and the target value. In the last step the audio buffer is multiplied by this factor. Part of this process can be seen in this link https://github.com/wwmm/pulseeffects/blob/d63b8662c1785ae51e9ccc9d555bcd58d9c6b53e/src/autogain/gstpeautogain.cpp#L456

At this moment the estimated loudness comes from an average of momentary, short term and integrated loudness. So when comparing the results with anything else this has to be in mind.

**Comment by RubenKelevra** [comment]
@wwmm alright, cool!

Can we have a R 128 button which sets the settings to R 128 - like a present? :)

**Comment by wwmm** [comment]
What do you mean by `sets the settings to R 128`? Unless there is a bug in libebur128 each of the 3 loudness estimations(momentary, short and integrated terms) should already be following the ebur128 standard.
