### ISSUE TITLE
[Request] Increase audio delay above 1000ms

### ISSUE THREAD

**Issue by user-login-2004** [wwmm/pulseeffects#707]
Hi!
I was wondering if it is possible to increase the audio latency above the 1000ms cutoff? The application I'm using has a large latency between audio and video (1.8s) but due to the cutoff there is still a 0.8s difference.
Thanks.

**Comment by wwmm** [comment]
I think GStreamer allows a higher value. I chose 1000 ms as it seemed enough. But I can increase it in the next PulseEffects release.

**Comment by user-login-2004** [comment]
Thanks! That would be really useful.

**Comment by wwmm** [comment]
@user-login-2004 I am looking at the code and it should be possible to set the latency to 10 seconds. Could you show an image of PE settings window with the values you entered?

**Comment by user-login-2004** [comment]
Sorry, what is the PE settings window?

**Comment by user-login-2004** [comment]
Oh. PE - PulseEffects (how did I not get that). I'm running LMDE 4, and my installation appears to be a Flathub of version 4.6.8. (I simply installed it from the software centre). Might this be the reason why the latency of 10 seconds isn't available?
[![Screenshot.png](https://i.postimg.cc/kX9PwT24/Screenshot.png)](https://postimg.cc/Cdv2xHHT)

**Comment by wwmm** [comment]
Now I see I totally misunderstood what you were doing. I was thinking about the global buffer and latency values in our settings menu but you were adding the delay in the delay plugin. Based on your image you want the same delay to both channels. But in my opinion this plugin is more interesting when we want different delays for each channel.

This is the menu I was talking about 
![Screenshot from 2020-06-14 14-19-03](https://user-images.githubusercontent.com/16225172/84599658-06049d00-ae4a-11ea-904e-6e5b1dffc512.png)
By playing with the buffer and latency values both from the input and the output of the processing chain you will have way more room to add large delays to both channels. And you can still use the delay plugin while doing that.

In this menu buffer and latency are in microseconds. So to have 1 seconds you must put `1000000` as value.

One disadvantage of adding delay through the buffer and latency parameters is that they are global and are not saved to the preset. So remember this when using PulseEffects in situations where the delay is not desirable. You will have to change the buffer and latency values to something smaller. As I did not write this plugin I don't know if higher delays values can be supported. This is something that would have to be asked to its author https://github.com/sadko4u/lsp-plugins

**Comment by wwmm** [comment]
On a second thought playing with the latency and the buffer parameter may not have the same effect if the application or Pulseaudio try to compensate it. Play a little with the values and let me know if it works. IF it doesn't then asking the plugin developer for higher values will be the only option.

**Comment by user-login-2004** [comment]
Thanks for the detailed answer, I didn't notice that menu before. I simply assumed that the Delay plugin was the only delay feature, this now makes much more sense to me. I tried changing the value of the pipeline output, and this was able to fix the sync issues between the video and audio. Thanks again for the help!
