### ISSUE TITLE
NO SOUND ERROR 

### ISSUE THREAD

**Issue by harshgurnani2002** [wwmm/pulseeffects#711]
sound is not comming from pulse effects i dont know what happend i am attaching screenshots
and errors 
(pulseeffects:3022): pulseeffects-WARNING **: 19:06:48.813: compressor plugin was not found!

(pulseeffects:3022): pulseeffects-WARNING **: 19:06:48.815: equalizer plugin was not found!

(pulseeffects:3022): pulseeffects-WARNING **: 19:06:48.853: delay plugin was not found!

(pulseeffects:3022): pulseeffects-WARNING **: 19:06:48.859: compressor plugin was not found!

(pulseeffects:3022): pulseeffects-WARNING **: 19:06:48.860: equalizer plugin was not found!

(pulseeffects:3022): pulseeffects-WARNING **: 19:07:20.452: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:3022): pulseeffects-WARNING **: 19:07:20.452: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:3022): pulseeffects-WARNING **: 19:07:20.454: sie: rtkit: MakeThreadRealtime: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:3022): pulseeffects-WARNING **: 19:07:20.455: sie: rtkit: MakeThreadRealtime: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:3022): pulseeffects-WARNING **: 19:07:20.459: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:3022): pulseeffects-WARNING **: 19:07:20.459: sie: rtkit: MakeThreadRealtime: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.466: g_settings_set_value: value for key 'knee' in schema 'com.github.wwmm.pulseeffects.sinkinputs.compressor' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.467: g_settings_set_value: value for key 'band0-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.468: g_settings_set_value: value for key 'band1-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.469: g_settings_set_value: value for key 'band2-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.469: g_settings_set_value: value for key 'band3-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.469: g_settings_set_value: value for key 'band4-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.470: g_settings_set_value: value for key 'band5-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.470: g_settings_set_value: value for key 'band6-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.471: g_settings_set_value: value for key 'band7-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.471: g_settings_set_value: value for key 'band8-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.472: g_settings_set_value: value for key 'band9-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.473: g_settings_set_value: value for key 'band0-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.474: g_settings_set_value: value for key 'band1-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.475: g_settings_set_value: value for key 'band2-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.477: g_settings_set_value: value for key 'band3-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.478: g_settings_set_value: value for key 'band4-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.479: g_settings_set_value: value for key 'band5-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.481: g_settings_set_value: value for key 'band6-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.483: g_settings_set_value: value for key 'band7-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.484: g_settings_set_value: value for key 'band8-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range

(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.485: g_settings_set_value: value for key 'band9-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range

help me 
![Screenshot_2020-06-18_19-10-04](https://user-images.githubusercontent.com/67070537/85027350-7176a380-b197-11ea-95f4-bef4788deebe.png)

**Comment by wwmm** [comment]
```
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files
```
Are you on Debian? At some point this year they made an update to their RealtimeKit package that broke not only PulseEffects but every app that depended on it. Until you fix this package installation set `Priority Type` to `None` in PulseEffects menu
![Screenshot from 2020-06-18 10-59-10](https://user-images.githubusercontent.com/16225172/85029606-d8259e00-b152-11ea-8068-4f91f8ebb4ac.png)

```
(pulseeffects:3022): GLib-GIO-WARNING **: 19:07:23.485: g_settings_set_value: value for key 'band9-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
```
This error sounds like a corrupt configuration somewhere. Run `pulseeffects -r` in a terminal to reset PulseEffects configuration.

**Comment by harshgurnani2002** [comment]
still the same no sound effect i tried to run everything u sid but no sound i just installed and it worked well for 2 hours till i restart now giving same error i tried running pulseeffects -r but no effect it not even showing the spectrum values(lines)



![Screenshot_2020-06-19_21-49-10](https://user-images.githubusercontent.com/67070537/85155756-c9d0a280-b276-11ea-8bf8-f2cb6dc66ee7.png)

**Comment by wwmm** [comment]
Is the `RealtimeKit1` error present even after setting the priority type to `None`? That is weird.

Which distribution are you using? How did you install PulseEffects? Through Flatpak or using native packages(deb, rpm, etc)? You definitely have a problem in one of the libraries PulseEffects needs to run.

**Comment by harshgurnani2002** [comment]
I m using in kali linux I installed using flatpak

**Comment by wwmm** [comment]
Now the realtimekit error makes sense. It does not work on flatpak.  But I thought disabling realtime would help. Let's try to run PulseEffects in debug mode so we can see more information. Close or kill it and run the command `G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects`. This should print more things.

**Comment by harshgurnani2002** [comment]
when i run this G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects
error: app/com.github.wwmm.pulseeffects/x86_64/master not installed




![Screenshot_2020-06-20_05-24-28](https://user-images.githubusercontent.com/67070537/85186382-5cdcfd00-b2b6-11ea-99d6-0e2a2342dabe.png)

**Comment by wwmm** [comment]
Maybe that is not how flatpak apps are meant to be called from command line. As I do not use flatpak I always forget. I will search in the close issues. At some point someone showed how to execute them.

**Comment by wwmm** [comment]
Strange. It should have worked https://github.com/wwmm/pulseeffects/issues/307. Are you sure it was installed through flatpak? There is an easy way to find out. Try to run `pulseeffects -q` followed by `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. If this works it was not installed through flatpak.

**Comment by harshgurnani2002** [comment]
G_MESSAGES_DEBUG=pulseeffects pulseeffects
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.035: presets_manager: user presets directory already exists: /home/magest/.config/PulseEffects
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.036: presets_manager: user presets directory already exists: /home/magest/.config/PulseEffects/input
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.036: presets_manager: user presets directory already exists: /home/magest/.config/PulseEffects/output
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.036: presets_manager: user presets directory already exists: /home/magest/.config/PulseEffects/autoload
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.128: application: PE version: 4.7.1
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.128: pulse_manager: context is connecting
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.129: pulse_manager: context is authorizing
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.129: pulse_manager: context is setting name
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.130: pulse_manager: context is ready
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.130: pulse_manager: connected to: /run/user/1000/pulse/native
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.130: pulse_manager: protocol version: 33
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.130: pulse_manager: Pulseaudio version: 13.0
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.130: pulse_manager: default pulseaudio source: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.130: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.130: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.130: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.130: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.131: pulse_manager:  failed to get sink info: PulseEffects_apps
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.135: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_apps sink_properties=device.description="PulseEffects(apps)"device.class="sound" norewinds=1
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.135: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.136: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.136: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.137: pulse_manager:  failed to get sink info: PulseEffects_mic
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.140: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_mic sink_properties=device.description="PulseEffects(mic)"device.class="sound" norewinds=1
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.163: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.163: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.169: sie: limiter is already disabled

(pulseeffects:8313): pulseeffects-WARNING **: 20:40:57.170: compressor plugin was not found!
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.172: sie: filter is already disabled

(pulseeffects:8313): pulseeffects-WARNING **: 20:40:57.172: equalizer plugin was not found!
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.174: sie: reverb is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.177: sie: bass_enhancer is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.178: sie: exciter is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.182: sie: crossfeed is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.184: sie: maximizer is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.187: sie: multiband_compressor is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.188: sie: loudness is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.190: sie: gate is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.193: sie: pitch is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.198: sie: multiband_gate is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.200: sie: deesser is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.202: sie: stereo_tools is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.208: sie: convolver is enabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.210: sie: crystalizer is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.212: sie: autogain is already disabled

(pulseeffects:8313): pulseeffects-WARNING **: 20:40:57.212: delay plugin was not found!
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.222: soe: using output device: PulseEffects_mic
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.222: soe: using input device: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.223: soe: limiter is already disabled

(pulseeffects:8313): pulseeffects-WARNING **: 20:40:57.223: compressor plugin was not found!
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.224: soe: filter is already disabled

(pulseeffects:8313): pulseeffects-WARNING **: 20:40:57.224: equalizer plugin was not found!
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.225: soe: reverb is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.226: soe: gate is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.227: soe: deesser is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.228: soe: pitch is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.233: soe: webrtc is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.235: soe: multiband_compressor is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.236: soe: multiband_gate is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.238: presets_manager: user presets directory already exists: /home/magest/.config/PulseEffects
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.238: presets_manager: user presets directory already exists: /home/magest/.config/PulseEffects/input
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.238: presets_manager: user presets directory already exists: /home/magest/.config/PulseEffects/output
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.238: presets_manager: user presets directory already exists: /home/magest/.config/PulseEffects/autoload
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.238: presets_manager: destroyed
pulseeffects-INFO: 20:40:57.238: application: disabling global bypass
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.238: sie: bypass is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.238: soe: bypass is already disabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.525: convolver_ui: irs directory already exists: /home/magest/.config/PulseEffects/irs
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.946: sie: spectrum enabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:57.947: soe: spectrum enabled
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.279: sie: total latency: 0 ms
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.279: soe: total latency: 0 ms
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.453: pulse_manager: sink input: gst-launch-1.0, idx = 177 moved to PE
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.464: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.464: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.464: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.464: pulse_settings_ui: added sink: viper
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.464: pulse_settings_ui: added source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.464: soe: using input device: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.464: pulse_settings_ui: input device changed: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.464: pulse_settings_ui: added source: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.464: pulse_settings_ui: added source: viper.monitor
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.568: sie: NULL -> READY -> PLAYING
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.569: sie: READY -> PAUSED -> PLAYING
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.571: sie: sampling rate: 44100 Hz
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.571: sie: pulsesrc latency [us]: 10000
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.572: sie: pulsesrc buffer [us]: 200000
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:58.572: sie: total latency: 0 ms
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:59.364: peadapter: pulseaudio block size 441 frames
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:59.364: peadapter: we will read in chunks of 512 frames
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:59.383: convolver: irs file does not exists or it is empty: /home/matteo/.config/PulseEffects/irs/Razor Surround ((48k Z-Edition)) 2.Stereo +20 bass.irs
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:59.383: convolver: we will just passthrough data.
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:59.385: sie: total latency: 141 ms
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:59.387: sie: pulsesink latency [us]: 10000
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:59.387: sie: pulsesink buffer [us]: 200000
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:59.388: sie: total latency: 141 ms
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:59.389: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:8313): pulseeffects-DEBUG: 20:40:59.390: sie: total latency: 141 ms
(pulseeffects:8313): pulseeffects-DEBUG: 20:41:01.431: presets_manager: autoloading preset Razer Sorround for device alsa_output.pci-0000_00_1f.3.analog-stereo:analog-output-headphones

(pulseeffects:8313): glibmm-ERROR **: 20:41:01.432: 
unhandled exception (type std::exception) in signal handler:
what: /home/magest/.config/PulseEffects/output/Razer Sorround.json: cannot open file

Trace/breakpoint trap

**Comment by wwmm** [comment]
`what: /home/magest/.config/PulseEffects/output/Razer Sorround.json: cannot open file` PulseEffects is crashing because it is trying to automatically load a preset you do not have anymore. This bug was fixed In PulseEffects `4.7.3` but you are still on `4.7.1`. So the solution to this error will be to remove our autoload folder manually `rm -rf /home/magest/.config/PulseEffects/autoload` and restarting PulseEffects.

**Comment by harshgurnani2002** [comment]
can u just tell me how to delete pulse compeletely including all config and install again from begining 
like first time

**Comment by wwmm** [comment]
As I do not use the same distribution as you I can't guide you on how to uninstall/install. But the command `pulseeffects -r` followed by `rm -rf /home/magest/.config/PulseEffects` will reset all PulseEffects settings. Maybe it will be enough.

**Comment by harshgurnani2002** [comment]
ok i installed ubuntu instead of kali linux because of this error now it is working fine in ubuntu thank you for your precious time have a nice day
