### ISSUE TITLE
No sound when processed (mic)

### ISSUE THREAD

**Issue by CJ1169** [wwmm/pulseeffects#713]
Hey Wellington, 
I have this odd issue when suing PE in that when I enable audio to be processed through the mic section, I get no audio played.

System:
5.6.18-1-MANJARO #1 SMP PREEMPT Wed Jun 10 19:54:00 UTC 2020 x86_64
With KDE (local/plasma-desktop 5.19.1-1)
With PulseEffects (local/pulseeffects 4.7.2-2)
With pulseaudio (local/pulseaudio 13.0-3)

Issue:
(Using discord audio loop to test)

Microphone processing enabled for discord application. Expected to hear the looped audio. No audio played. If I clap really loudly, i can hear a faint looped audio. Very strange.
![SS1](https://user-images.githubusercontent.com/48484105/85212366-942fc600-b317-11ea-8c7a-6cfc35ee630c.png)

Microphone processing disabled for discord application. Expected to hear the looped audio, albeit with no processing. Audio sounds normal.
![SS2](https://user-images.githubusercontent.com/48484105/85212405-effa4f00-b317-11ea-85f5-ec4866934e9d.png)

Troubleshooting steps applied:
I attempted to run pulseffects -r to reset - reset was successful, but did not solve the issue. No console errors received.
Apps audio does not show this issue. It seems to ingest the audio and process it exactly as expected.
Rebooting had no effect.
It **seems** to be routed correctly, but there **seems** to be some issue between when PE ingests the mic audio and receiving the audio in the application.
I've also tried the loop module in pactl with the same effect as discord looping.

**Comment by wwmm** [comment]
Hi! Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. This way we will see if there is any error printed in the terminal. Does the problem happen with other plugins or without any plugin enabled?

**Comment by CJ1169** [comment]
Killed pulseeffects and restarted into debugging mode. 

![SS3](https://user-images.githubusercontent.com/48484105/85232214-df52e300-b3c2-11ea-854d-d7d2b625c195.png)

Copied debugging output. I turned the processing on/off on discord a couple times to get that output too.
[log1.txt](https://github.com/wwmm/pulseeffects/files/4810041/log1.txt)

This seems to happen both without plugins enabled and with. I had a couple enabled before I reset it with the -r switch. The debugging output is without any plugins (for mic) enabled.
Having any plugins enabled or disabled on the apps side does not affect the mic side, as expected.

**Comment by wwmm** [comment]
I am looking at your logs but so far I did not see anything unusual. Both effects pipelines were put in the playing state. And your pavucontrol image shows that discord is recording from `PulseEffects(mic)` sink monitor as it should. What do you have in pavucontrol `Playback` tab. There should be a a PulseEffects stream playing audio on  `PulseEffects(mic)`. Without it discord will record silence.

I did a few tests with discord on Chrome. I do not have its app installed. Everything was fine. I could here my voice in the test. This is how pavucontrol looks like when using discord on Chrome:
![Screenshot from 2020-06-21 18-32-21](https://user-images.githubusercontent.com/16225172/85235851-c52efa00-b3ee-11ea-8add-0d8f231dc178.png)
![Screenshot from 2020-06-21 18-37-09](https://user-images.githubusercontent.com/16225172/85235853-c7915400-b3ee-11ea-8100-12481f8149ce.png)

**Comment by CJ1169** [comment]
Here's screenshots of the playback tab - using the discord app and using chromium.

![SS4](https://user-images.githubusercontent.com/48484105/85237603-bbf15d80-b3ed-11ea-962f-4f5ba43b196d.png)

![SS5](https://user-images.githubusercontent.com/48484105/85237604-be53b780-b3ed-11ea-96b1-9144cbdc6b16.png)

And here's the playback tab without PE controlling input

![image](https://user-images.githubusercontent.com/48484105/85237646-1094d880-b3ee-11ea-890f-c49d94be10cc.png)

**Comment by Digitalone1** [comment]
I have an old laptop where sometimes the stream does not came out from PE even if no issues are shown in the debug mode. I think this is why the load on the CPU is too much and something goes wrong in the gstreamer pipeline without getting noticed from PE side.

This has also occurred rarely on my main laptop which is more powerful, but it resolved closing and restarting the player.

On the other old laptop, I managed to reduce this side effect increasing (doubling) buffer and latency in both input and output pipeline. @CJ1169, try to do the same for Input Effects.

**Comment by wwmm** [comment]
Bluetooth devices usually need higher buffer and latency values. The other kind of devices usually have changes in the cpu usage when we play with these values. But it is worth a try. Play with buffer, latency, and block size values of the mic pipeline
![Screenshot from 2020-06-22 11-24-11](https://user-images.githubusercontent.com/16225172/85298821-eb9a7700-b47a-11ea-8df3-4d58a8594893.png)

**Comment by wwmm** [comment]
This issue is so weird that if it weren't for the pavucontrol images I would think that the `PulseEffects(mic)` sink were muted. Or the corresponding PulseEffects stream sending audio to it.

**Comment by CJ1169** [comment]
No combination of pipeline inputs/outputs and block sizes seemed to have a positive effect. I tried combinations between 2,000 us to 2,000,000 us for the pipeline buffer and 10 to 100,000 for latency.
Adjusting the cpu priority of PE didn't seem to have an affect either.

**Comment by Digitalone1** [comment]
Try to delete gstreamer cache and restart.

`~/.cache/gstreamer-1.0`

**Comment by CJ1169** [comment]
To check the basics, I reset my settings, uninstalled all configs & PE/deps. I built from git and the problem still persists.

![image](https://user-images.githubusercontent.com/48484105/85339141-27e4cc00-b4a9-11ea-997a-c6f7215cd9ab.png)

Closed PE, deleted gstreamer cache, restarted PE and no effect.

Very weird problem indeed. Hopefully I'm not missing something?

**Comment by wwmm** [comment]
The only thing that comes to my mind now would be to delete Pulseaudio's config folder `rm -rf ~/.config/pulse` and login to the desktop again. If that does not help we will have to take a look at Pulseaudio's log. You can get them following the `advanced section` in our wiki https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs.

**Comment by CJ1169** [comment]
Alright, here's the complete basics:

<details>
1. Distribution and Desktop Environment.
Manjaro + KDE
core/manjaro-system 20200427-1
extra/plasma-desktop 5.19.1-1

2. How you installed PulseEffects (Flatpak or native package).
Native community repo. Also have tried git build.
community/pulseeffects 4.7.2-2

3. Messages printed by PulseEffects when executed from command line in debug mode G_MESSAGES_DEBUG=pulseeffects pulseeffects.
[g_messages_debug_log.txt](https://github.com/wwmm/pulseeffects/files/4815882/g_messages_debug_log.txt)

4. The output of the command pactl list short.
[pactl_list_short_log.txt](https://github.com/wwmm/pulseeffects/files/4815891/pactl_list_short_log.txt)

5. The output of the command pacmd list-sinks.
[pacmd_list_sinks_log.txt](https://github.com/wwmm/pulseeffects/files/4815894/pacmd_list_sinks_log.txt)

6. The output of the command pacmd list-sink-inputs.
[pacmd_list_sink_inputs_log.txt](https://github.com/wwmm/pulseeffects/files/4815896/pacmd_list_sink_inputs_log.txt)

7. The output of the command pacmd list-sources.
[pacmd_list_sources.txt](https://github.com/wwmm/pulseeffects/files/4815897/pacmd_list_sources.txt)

8. The output of the command pacmd list-source-outputs.
[pacmd_list_source_outputs.txt](https://github.com/wwmm/pulseeffects/files/4815898/pacmd_list_source_outputs.txt)

9. The output of the command pulseaudio --dump-conf.
[pulseaudio_dump_conf.txt](https://github.com/wwmm/pulseeffects/files/4815899/pulseaudio_dump_conf.txt)

10. Screenshots of Pavucontrol tabs.
This is with processing enabled.

![image](https://user-images.githubusercontent.com/48484105/85342189-9cbb0480-b4af-11ea-8431-a5fc8096e386.png)

![image](https://user-images.githubusercontent.com/48484105/85342198-a2184f00-b4af-11ea-8c01-4200d9c46271.png)

![image](https://user-images.githubusercontent.com/48484105/85342206-a80e3000-b4af-11ea-9d60-45d40769a320.png)

![image](https://user-images.githubusercontent.com/48484105/85342227-b0666b00-b4af-11ea-9cc1-ffe7997b3d6a.png)

![image](https://user-images.githubusercontent.com/48484105/85342236-b4928880-b4af-11ea-9119-87e6dfc96cb5.png)

![image](https://user-images.githubusercontent.com/48484105/85342243-bb210000-b4af-11ea-968a-fcee484dfe64.png)


11. PulseEffects settings. You can save them to a file using the command 
dconf dump /com/github/wwmm/pulseeffects/ > pesettings.txt

[pesettings.txt](https://github.com/wwmm/pulseeffects/files/4815909/pesettings.txt)

</details>

advanced logs
<details>
steps: 
opened terminal
ran pacmd
inside the pacmd cli, ran set-log-level 4
did not have pavucontrol running
ran sudo journalctl -fb | grep -i pulse
started pulseeffects

post processing on & enabled feedback loop from discord
loudly snapped into mic
post processing off & enabled feedback loop from discord
loudly snapped into mic

[advanced_logs.txt](https://github.com/wwmm/pulseeffects/files/4815957/advanced_logs.txt)

</details>

Hopefully thats fully readable since the details markdown seems to mess up formatting.

**Comment by Digitalone1** [comment]
@wwmm can look better than me into log details, but I don't see any relevant errors.

If I'm not wrong, I think that the issue is inside gstreamer.

**Comment by wwmm** [comment]
So far I see nothing wrong in any of these logs. Pulseaudio shows what I already knew. Both PE pipelines are playing the as far as I could see the audio routing is correct. PE records the mic and sends the processed audio to our virtual sink `PulseEffects(mic)`. Then discord records from this virtual sink monitor. But obviously all this processing chain is playing silence. Why I don't know.

As the other pipeline is working I am not confident it is a problem in GStreamer. But there is a way to have an idea if it is having difficulties with this microfone. Kill pulseeffects `pulseeffects -q` and run `gst-launch-1.0 pulsesrc ! queue ! pulsesink`. This will make GStreamer record from the default source(your mic) and play to the default output. Without PE running this would be your sound card. It may be worth do this test with PE running too.

**Comment by CJ1169** [comment]
I'll give that a try tonight. I've been using PE since mid 2019 and it had worked fine for this mic previously, making this entire issue that much more strange.
It is good to repeat that its not quite 'silence' as what I can do is make some super loud noise and I do get a little feedback from PE.
Is it possible to reset all pulseaudio settings as another troubleshooting step I can take?

**Comment by wwmm** [comment]
`pulseeffects -r` should have reset everything already. Other than that the only thing left would be to remove the folder `~/.config/PulseEffects`. But this will only remove your preset files. And If I am not mistaken you already removed Pulseaudio's config folder. So I think that there is nothing more that could be reset. But there is always the possibility of creating a new temporary user just to test that.

**Comment by CJ1169** [comment]
Ah, I misread your https://github.com/wwmm/pulseeffects/issues/713#issuecomment-647791745 post and just removed PE's configs.
I removed the configs via ssh and I'll reload my desktop and test tonight.
With a negative result, I'll try a different user as well.

**Comment by CJ1169** [comment]
Clearing PA's config folder did the trick. Such a weird issue. Thank y'all for your time & efforts!

**Comment by markonius** [comment]
Hey, just wanna add some info, in case anyone else has the same problem. I deleted:
- ~/.cache/gstreamer-1.0
- ~/.config/pulse
- ~/.config/PulseEffects

It still didn't work _until I rebooted_.
Then I returned my ~/.config/PulseEffects (I lied, I actually moved it), and it still works fine.
I suspect it was the gstreamer cache, but that's just a hunch.
