### ISSUE TITLE
Opening System Sound Settings breaks PulseEffects audio

### ISSUE THREAD

**Issue by GottaSlay** [wwmm/pulseeffects#718]
When System Sound Settings is opened. Any audio being played goes muted and I can hear what my microphone is picking up.

For an example, I am listening to Spotify and if I go to my system's Sound Settings, spotify audio mutes itself but for some my microphone begins to send whatever it picks up to my headphones.

Then if I go to PulseEffects and disable any effects I have on for spotify using this toggle: [https://i.imgur.com/7kpM77o.png](url) I am once again able to hear spotify but with the effects disabled. My microphone in this case will still continue sending the audio it picks up to my headphones.

I've only managed to fix this issue by rebooting my PC. This happens on Manjaro and the same bug applies for any audio source, spotify, firefox, etc.

**Comment by Digitalone1** [comment]
What is your desktop environment? XFCE?

I tried sound settings on Plasma and Gnome and that never happened.

**Comment by GottaSlay** [comment]
I'm on Gnome. This has happened on two different Manjaro Gnome installations I've done.

**Comment by Digitalone1** [comment]
> I'm on Gnome. This has happened on two different Manjaro Gnome installations I've done.

So you intend sound tab in system settings, right? Effectively, I never used it, maybe there's something wrong with it.

Can you try to use pavucontrol to see if it's the issue is happening also with that app? Thanks.

**Comment by GottaSlay** [comment]
Sound tab in system settings yes. I tried out pavucontrol and that one works correctly. Could this mean its something wrong on Manjaro's side?

**Comment by Digitalone1** [comment]
> Sound tab in system settings yes. I tried out pavucontrol and that one works correctly. Could this mean its something wrong on Manjaro's side?

No, it's something wrong with Gnome sound settings. I tried also on my system and it's happening the same issue. I never used it, only pavucontrol.

PulseEffects sink is not reproducing sound after Gnome sound settings is opened and the only way to resolve is to stop PE service and restart it.

**Comment by GottaSlay** [comment]
Well that certainly makes me feel better knowing that I'm not the only one with the issue. How should I proceed on reporting this to Gnome? I'm not certain on what kind of information should I be looking for with this issue.

**Comment by Digitalone1** [comment]
Let's wait @wwmm, he can gather more information and report the issue as PulseEffects developer.

**Comment by wwmm** [comment]
Hello!

This is a known gnome settings issue https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/494. It doesn't only set the default device. It forces all applications to be moved to this device in the process. What breaks custom audio routing done by apps like PulseEffects. The next Pulseaudio release will have a workaround that forbids gnome settings of doing that https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/14.0/. Until this happens all we can do is waiting because it does not seem GNOME is removing this "feature" from gnome settings. And I can't disable it from PulseEffects. Pulseaudio's workaround is our only hope here.

**Comment by Digitalone1** [comment]
Reported 1 year ago, nothing happened.

That's worse than Plasma saying PulseEffects is using the microphone. It's ridiculous.
