### ISSUE TITLE
Pulseeffects gui is showing me broken fonts on linux mint 19.3

### ISSUE THREAD

**Issue by Superbug50** [wwmm/pulseeffects#719]
![pulseeffects](https://user-images.githubusercontent.com/25424568/86523722-4477f100-be25-11ea-8df7-fec51c682a1f.png)
**I installed pulseeffects using flatpak and when i ran it, it did show me this. Does anyone know what font it uses?**

**Comment by Digitalone1** [comment]
Did you try to set the font through system settings? Which desktop environment are you using?

**Comment by Superbug50** [comment]
> Did you try to set the font through system settings? Which desktop environment are you using?

Linux Mint 19.3 "Tricia" - Cinnamon (64-bit)

**Comment by Digitalone1** [comment]
> > Did you try to set the font through system settings? Which desktop environment are you using?
> 
> Linux Mint 19.3 "Tricia" - Cinnamon (64-bit)

Never used Cinnamon, but it should have a system settings GUI to set the default font for all applications. Try to change them.

PulseEffects is the only app installed through Flatpak? The others are showing good fonts?

**Comment by Superbug50** [comment]
> > > Did you try to set the font through system settings? Which desktop environment are you using?
> > 
> > 
> > Linux Mint 19.3 "Tricia" - Cinnamon (64-bit)
> 
> Never used Cinnamon, but it should have a system settings GUI to set the default font for all applications. Try to change them.
> 
> PulseEffects is the only app installed through Flatpak? The others are showing good fonts?

Well the other app's  are showing good fonts. Only PulseEffects is showing a missing font.

**Comment by Superbug50** [comment]
Oh nevermind it seems to show up now. ty.

**Comment by wwmm** [comment]
I am glad it is working. Just for the records we do not force any font. GTK uses whatever it thinks it should be used.
