### ISSUE TITLE
AppImage support

### ISSUE THREAD

**Issue by efegurkan** [wwmm/pulseeffects#72]
Hi,

Thank you for pulseeffects it is really awesome.

I would like to suggest adding [AppImage](http://appimage.org) as an option for installing as well. 

Cheers,

**Comment by AsavarTzeth** [comment]
You are free to make one yourself just like I did the flatpak. Although I cannot speak for the developer I know he did not have time to learn how to package for flatpak so I assume the same can be said for AppImages.

Any specific (practical) reason you cannot use the flatpak build?

**Comment by efegurkan** [comment]
There is no specific reason i cannot use flatpak, in fact i am using flatpak version :D Thank you on that.

Let's see if i can manage time for make that happen. I suggest AppImage as well because i know some people don't want to install flatpak, with AppImage it should be possible to just doubleclick and run it. 

Cheers,

**Comment by AsavarTzeth** [comment]
I did suspect that would be your answer. I agree that the strength of AppImage's are in the portability aspect, i.e. that you can just get it and run it.

Simultaniously that is where my main issue with AppImage's is. The combination of how you get it and use it replicates the insecure practive we traditionally see in Windows, where users just download arbitrary binaries, don't verify them and execute them.

Ideally verification of AppImage's would be enforced. They should be signed or at least have checksums. But even then the responsibiltiy to verify it lies with the user. At this point it is not as simple as just running it and I don't see how you could change that without having any pre-requisite dependency.

**Comment by AsavarTzeth** [comment]
Here's a cool idea. What if we could merge the advantages of both formats?

I would like to see AppImage's made OCI (Open Container Initative) compatible. If I understand things correctly you could then in theory use the Flatpak tooling to export a bundle as an OCI container image and use that. It should mean all my work could then be reused and the contents would be identical. It would also eliminate the duplicated maintenance effort.

**Comment by wwmm** [comment]
As I do not have knowledge and time to build appimage's packages I will close this issue.
