### ISSUE TITLE
New parameters in Compressor 

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#727]
Lsp Sidechain Compressor added new parameters in the latest versions. See [here](https://lsp-plug.in/?page=manuals&section=sc_compressor_stereo)

Attack threshold, release threshold, LPF and HPF are missing in PE compressor UI.

I'd like to add them, but I never did that. @wwmm can you explain me how to look for the list of parameters for a specific plugin in gstreamer in order to add them to PE code? Thanks.

**Comment by wwmm** [comment]
First run this command `gst-inspect-1.0 | grep -i lsp`. It will show all lsp plugins that GStreamer were able to load. Including the ones in the LADSPA standard. Of all those entries shown the one corresponding to the compressor used by PE is `lsp-plug-in-plugins-lv2-compressor-stereo`. In order to see the name given by GStreamer to all of its properties as well as its number of channels, sample format, etc run the command `gst-inspect-1.0 lsp-plug-in-plugins-lv2-compressor-stereo`. Use the `up/down` keyboard keys to navigate.

**Comment by wwmm** [comment]
For each property GStreamer will shown a line like this one `flags: readable, writable, controllable`.  If the word `writable` is not there the property is readonly.

**Comment by wwmm** [comment]
It also shows the property type, range and default values. For `float` properties it is something like `Float. Range:           0,001 -            1000 Default:               1`

**Comment by wwmm** [comment]
Properties named like `out-latency` do not work on GStreamer as its wrapper does not have latency reporting functionality implemented to LADSPA/LV2 plugins. Only for its native plugins.

**Comment by Digitalone1** [comment]
These should be the new ones

```
al                  : Attack level
                        flags: leggibile, scrivibile, controllabile
                        Float. Range:           0,001 -               1 Default:         0,25119

rl                  : Release level
                        flags: leggibile, controllabile
                        Float. Range:               0 -              20 Default:               0

rrl                 : Relative release level
                        flags: leggibile, scrivibile, controllabile
                        Float. Range:               0 -               1 Default:               0 


slpf                : Low-pass filter frequency
                        flags: leggibile, scrivibile, controllabile
                        Float. Range:              10 -           20000 Default:           20000 
  slpm                : Low-pass filter mode
                        flags: leggibile, scrivibile, controllabile
                        Enum "lsp-plug-in-plugins-lv2-compressor-stereoslpm" Default: 0, "off"
                           (0): off              - off
                           (1): 12 dB/oct        - 12 dB/oct
                           (2): 24 dB/oct        - 24 dB/oct
                           (3): 36 dB/oct        - 36 dB/oct

shpf                : High-pass filter frequency
                        flags: leggibile, scrivibile, controllabile
                        Float. Range:              10 -           20000 Default:              10 
  shpm                : High-pass filter mode
                        flags: leggibile, scrivibile, controllabile
                        Enum "lsp-plug-in-plugins-lv2-compressor-stereoshpm" Default: 0, "off"
                           (0): off              - off
                           (1): 12 dB/oct        - 12 dB/oct
                           (2): 24 dB/oct        - 24 dB/oct
                           (3): 36 dB/oct        - 36 dB/oct
```

I'll test if I can add them to the code in the next days

**Comment by Digitalone1** [comment]
@wwmm input and output gain can be tweaked between -60 and 60 db, but they are limited to -/+20db. Were they limited in the previous versions or you limited them for a specific reason?

Also, knee bottom level is -23,99, but -23,80 is specified in gettings.

**Comment by Digitalone1** [comment]
Do you understand this parameter?

```
Release Thresh - relative to the Attack Thresh threshold that sets up the threshold of Release Time.
```

This is between -infinite and 0? How can be summarized in the UI? 

```
  rrl                 : Release threshold
                        flags: leggibile, scrivibile, controllabile
                        Float. Range:               0 -               1 Default:               0 
```

**Comment by wwmm** [comment]
>input and output gain can be tweaked between -60 and 60 db, but they are limited to -/+20db. Were they limited in the previous versions or you limited them for a specific reason?

I think I forgot to adjust that when replacing the Calf compressor by the one from LSP. Calf plugin does not have these controls. So I used two instances of the GStreamer volume plugin to implementing them. I think that this volume plugin has that range -/+20db. But as the LSP plugins has these controls built-in the volume plugins are not used in this place anymore.

> This is between -infinite and 0? How can be summarized in the UI?

We could set the lowest value in the interface to something like `-100 dB`. It will correspond to a linear value of `0,00001`. IT seems low enough to me. At least for now I do not think it will be worth to add complexity just to make the linear value to be actually zero

**Comment by wwmm** [comment]
>Do you understand this parameter?

No entirely. I can see that the final release threshold will be dependent on the current attack threshold value. Why it is this way I have no idea.

**Comment by Digitalone1** [comment]
The problem is that 0 is the default and setting the value related to -100 db will change this which is not a good idea.

These are quite advanced parameters and I'd like to not add them in the existing UI. I was thinking to create a new tab called *Advanced* where casual users are recommended to leave all to default.

Here the relative release threshold can be shown in linear scale and the documentation will specify that. What do you think?

**Comment by wwmm** [comment]
< The problem is that 0 is the default and setting the value related to -100 db will change this which is not a good idea.

I doubt it will be a problem to set `0.00001` instead of `0`. But if you really want to worry about this create a custom function for the conversion from decibel to linear scale. Inside this function you can check if the decibel value is `-100 dB`. If yes you force zero as output. You will have to do the binding to this function as shown in this line
https://github.com/wwmm/pulseeffects/blob/b99a03905d790dd3c3e988f39d5ba0d7648b0790/src/compressor.cpp#L157

< These are quite advanced parameters and I'd like to not add them in the existing UI. I was thinking to create a new tab called Advanced where casual users are recommended to leave all to default.

No problems. There are already 2 tabs in the compressor interface. A third one will do no harm.

**Comment by wwmm** [comment]
>Here the relative release threshold can be shown in linear scale and the documentation will specify that. What do you think?

I think it is better to use decibel. This is probably what the built-in plugin interface is doing. The plugin is exposing the value in a linear scale because it is probably more convenient from a implementation point of view. But people wanting to make use of this feature probably will expect to see a decibel value like it is done with threshold, knee, etc.

**Comment by Digitalone1** [comment]
> But if you really want to worry about this create a custom function for the conversion from decibel to linear scale. Inside this function you can check if the decibel value is `-100 dB`. If yes you force zero as output. You will have to do the binding to this function as shown in this line

This will add complexity. Not worth it. ^^

I will set a very low db value and test how it sounds.

**Comment by Digitalone1** [comment]
@wwmm I made the UI and bound the new settings, but can't launch the build because it can't see the news parameters in gsettings.

I followed the steps you recommended, but the application fails to start.

```
cd pe_sources
glib-compile-schemas data/schemas/
meson _build
cd _build
ninja
cd src
source ../../util/environmental_variables.sh
./pulseeffects
```

The only difference is that I installed over `/tmp/pe`. The only way to get it working is to install over the existing upstream package files?

**Comment by wwmm** [comment]
Strange. I never had to overwrite the system package to test development versions. What is the error printed?

**Comment by wwmm** [comment]
I also never needed to run `ninja install`. What is the output of `printenv | grep -i schema` when you execute it after `source ../../util/environmental_variables.sh`? On my computer I have `GSETTINGS_SCHEMA_DIR=../../data/schemas/` this and `glib-compile-schemas data/schemas/` should have been enough.

**Comment by Digitalone1** [comment]
```
(pulseeffects:10335): GLib-GIO-ERROR **: 18:14:20.307: Settings schema 'com.github.wwmm.pulseeffects.sinkinputs.compressor' does not contain a key named 'release-threshold'
```

This is in `data/schemas/com.github.wwmm.pulseeffects.sinkinputs.compressor.gschema.xml`:
```
        <key name="release-threshold" type="d">
            <range min="-200" max="0"/>
            <default>-200</default>
        </key>
```

<details>
<summary> Glade screenshot</summary>

![Schermata del 2020-07-19 18-24-47](https://user-images.githubusercontent.com/25790525/87879911-cb17fb00-c9ed-11ea-8ed4-902449b22ccb.png)

</details>

**Comment by Digitalone1** [comment]
> I also never needed to run `ninja install`. What is the output of `printenv | grep -i schema` when you execute it after `source ../../util/environmental_variables.sh`? On my computer I have `GSETTINGS_SCHEMA_DIR=../../data/schemas/` this and `glib-compile-schemas data/schemas/` should have been enough.

I also have `GSETTINGS_SCHEMA_DIR=../../data/schemas/` but it's wrong because I made build folder outside pulseeffects source folder. It should be `../../pulseeffects/data/schemas/`

**Comment by wwmm** [comment]
Ok. The easier solution would be to make the build folder inside the source folder as both `_build` and `build` are in the `.gitignore` file. Better than editing `environmental_variables.sh`

**Comment by Digitalone1** [comment]
It's not working. I think the only way is to build outside `/tmp`.

Tomorrow I'll try to make a custom PKGBUILD with my repository as source.

**Comment by Digitalone1** [comment]
Resolved. It's working. Changes are in my fork repository. I'll make the pull request after completing the translations and the documentation update.
