### ISSUE TITLE
The .desktop file in flatpak tries to run "pulseeffects" directly instead of through flatpak

### ISSUE THREAD

**Issue by promi** [wwmm/pulseeffects#729]
When installing via flatpak (on Debian sid with GNOME), after restarting the desktop environment a menu item is shown for PulseEffects, but it does not work.

When I look at the .desktop file it has just "pulseeffects" as its run command, but on the command line I have to type:

flatpak run com.github.wwmm.pulseeffects

Is the .desktop file broken?

**Comment by wwmm** [comment]
I am not the maintainer of the flatpak package. It is better to open an issue in this page https://github.com/flathub/com.github.wwmm.pulseeffects

The `.desktop` file in PulseEffects sources is intended for the native packages. I imagine that the flatpak package will need something else.

**Comment by promi** [comment]
Thanks, will do.
