### ISSUE TITLE
cpu usage on intel systems

### ISSUE THREAD

**Issue by sandikata** [wwmm/pulseeffects#731]
Hello, i am in struggle with pulseeffects and it's behavior on intel cpus.
It causing high cpu usage when playback is running(30 - 40%), and even on idle it use about 15% cpu.
Do you have any suggestions? 
Tell me if you need some logs.

**Comment by Digitalone1** [comment]
Please, provide the version you're running and which distribution you're using.

**Comment by wwmm** [comment]
Depending on the cpu generation the use might be high. But even in this case after 5 seconds with no app playing audio PulseEffects should pause its pipeline and the cpu usage should be zero. In case you want to get logs kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`.

It is also important to know how you are measuring the cpu usage. `top` for example has two modes that give different values.

**Comment by sandikata** [comment]
Archlinux based distribution.
pulseeffects 4.7.3

System:    Kernel: 5.7.9-xanmod1-1-xanmod x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: Cinnamon 4.6.6 wm: muffin 
           dm: LightDM 1.30.0 Distro: Artix rolling 
Machine:   Type: Desktop System: Gigabyte product: H110M-S2H v: N/A serial: N/A 
           Mobo: Gigabyte model: H110M-S2H-CF v: x.x serial: N/A UEFI: American Megatrends v: F20 date: 11/08/2016 
CPU:       Topology: Quad Core model: Intel Core i5-7400 bits: 64 type: MCP arch: Kaby Lake rev: 9 L1 cache: 256 KiB 
           L2 cache: 6144 KiB L3 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 24000 
           Speed: 1851 MHz min/max: 800/3500 MHz volts: 1.0 V ext-clock: 100 MHz Core speeds (MHz): 1: 1851 2: 1906 3: 2650 
           4: 1944 
Graphics:  Device-1: Intel HD Graphics 630 vendor: Gigabyte driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:5912 
           Display: server: X.Org 1.20.8 driver: intel resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz s-dpi: 96 
           OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 20.2.0-devel (git-04ea4f1ce4) direct render: Yes 
Audio:     Device-1: Generalplus USB Audio Device type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-4:2 
           chip ID: 1b3f:2008 
           Sound Server: ALSA v: k5.7.9-xanmod1-1-xanmod 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Gigabyte driver: r8169 v: kernel 
           port: e000 bus ID: 01:00.0 chip ID: 10ec:8168 
           IF: eth0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           IF-ID-1: br0 state: up speed: 1000 Mbps duplex: unknown mac: <filter> 
           IF-ID-2: docker0 state: down mac: <filter> 
           IF-ID-3: virbr0 state: up speed: 10 Mbps duplex: unknown mac: <filter> 
           IF-ID-4: virbr0-nic state: down mac: <filter> 
           IF-ID-5: vnet0 state: unknown speed: 10 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 1.15 TiB used: 46.50 GiB (3.9%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 850 EVO 250GB size: 232.89 GiB speed: 6.0 Gb/s serial: <filter> rev: 2B6Q 
           scheme: GPT 
           ID-2: /dev/sdb vendor: Western Digital model: WD10EZEX-00BN5A0 size: 931.51 GiB speed: 6.0 Gb/s rotation: 7200 rpm 
           serial: <filter> rev: 1A01 scheme: GPT 
           ID-3: /dev/sdc type: USB vendor: Lexar model: USB Flash Drive size: 14.55 GiB serial: <filter> rev: 1100 
           scheme: MBR 
Partition: ID-1: / size: 227.94 GiB used: 34.22 GiB (15.0%) fs: ext4 dev: /dev/sda2 
           ID-2: /home size: 915.89 GiB used: 9.52 GiB (1.0%) fs: ext4 dev: /dev/sdb1 
           ID-3: /tmp size: 1.91 GiB used: 14.9 MiB (0.8%) fs: ext4 dev: /dev/zram4 
Swap:      ID-1: swap-1 type: zram size: 1024.0 MiB used: 0 KiB (0.0%) priority: 16383 dev: /dev/zram0 
           ID-2: swap-2 type: zram size: 1024.0 MiB used: 0 KiB (0.0%) priority: 16383 dev: /dev/zram1 
           ID-3: swap-3 type: zram size: 1024.0 MiB used: 0 KiB (0.0%) priority: 16383 dev: /dev/zram2 
           ID-4: swap-4 type: zram size: 1024.0 MiB used: 0 KiB (0.0%) priority: 16383 dev: /dev/zram3 
Sensors:   System Temperatures: cpu: 34.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 256 Uptime: 1d 16h 24m Memory: 15.33 GiB used: 3.97 GiB (25.9%) Init: N/A v: N/A rc: OpenRC v: 0.42.1 
           runlevel: default Compilers: gcc: 10.1.0 clang: 10.0.0 Shell: zsh (sudo) v: 5.8 running in: xfce4-terminal 
           inxi: 3.1.03

**Comment by sandikata** [comment]
i've responded to another issue which exist, i found it after i've opened this one.

**Comment by wwmm** [comment]
Could you upload here an image showing your cpu usage measurment?

**Comment by sandikata** [comment]
Yes, i can. At the moment i've got some progress in reducing cpu usage.

[https://i.imgur.com/nVn0KbF.png](url)

**Comment by wwmm** [comment]
Based on this image I would say that the only odd behavior is using cpu on idle. This should not happen. About the cpu usage `htop` and `top` by default use a scale that goes from `0` to `(number of threads) * 100 %`. Your cpu has 4 threads. So in the image you showed you have `38 %` of `400 %`. If we divide everything by the number of threads we are talking about a total cpu usage(considering all cores) of about `10 %`. I don't know if we can get less than that on this processor. What is the usage when all plugins are disabled? 

As a reference this is what I get on my `Ryzen 3700X` when PulseEffecs is running in the foreground(window opened):
![Screenshot from 2020-07-27 11-13-01](https://user-images.githubusercontent.com/16225172/88552264-471bcf80-cffa-11ea-84e9-b686d83b6c72.png)

`15.1 %` in a scale that goes up to `1600 %`. Dividing by the 16 threads we have approximately `0.9 %`. Roughly ten times less than the value you have. But the difference in cpu power is huge. I had these plugins enabled at the time of this measurement:
![Screenshot from 2020-07-27 11-15-19](https://user-images.githubusercontent.com/16225172/88552460-7fbba900-cffa-11ea-94bd-7b197a24c0b9.png)

**Comment by sandikata** [comment]
well mostly exciter plugin causing intel systems mad.
