### ISSUE TITLE
[BUG] spectrum values doesn't reflect settings of scale (factor), and exp. and spectrum is "broken" in window preview.

### ISSUE THREAD

**Issue by Mlocik97-issues** [wwmm/pulseeffects#733]
https://www.youtube.com/watch?v=G4X7JepiyPw&feature=youtu.be

(sry for audio, bad recording source)

![Snímka obrazovky z 2020-07-22 12-46-27](https://user-images.githubusercontent.com/31345346/88167755-9be5d180-cc19-11ea-8aa4-087b96388592.png)

**Comment by wwmm** [comment]
I noticed this at the time this was implemented. But I am not sure yet about how to handle this problem.

**Comment by Mlocik97-issues** [comment]
Propably, it would be nice to not have values in matrix, but actual value of output in column, where I hover with mouse. It would give even better information for user.

**Comment by wwmm** [comment]
I am almost considering to remove this scaling feature. As it is implemented right now it is impossible to fix the amplitude values shown by the mouse hove because each bar has its own scaling factor.

**Comment by wwmm** [comment]
Or maybe we could not drawing the mouse hover info when the `scaling` and the `exponent` parameters are different than `1`. But I think that this will let the users confused. One day they would notice that the mouse hover "was not working anymore" and would report a bug. What do you think @Digitalone1? I do not use this scaling. And I still do not see a way to fix the wrong mouse hover values when the scaling is active.

**Comment by Digitalone1** [comment]
I never used scaling feature. If this leads to issues that can't be resolved, I agree to remove it. Unfortunately I'm not able to give any help in this case.

**Comment by wwmm** [comment]
And the broken window preview is something that can be fixed only in gnome. I do not see how I could fix this from the application side when gnome mutter is the one doing the preview.

**Comment by wwmm** [comment]
I am thinking about to release what will be PE `4.8.0` tomorrow. I will give more thought to this scaling issue till then. But I will probably remove it.

**Comment by Digitalone1** [comment]
On my side the preview is not broken, but maybe because my screen is little since I use a laptop. I can barely see the whole spectrum.

**Comment by wwmm** [comment]
I can see on my monitor that the small preview at the right side is broken. Maybe it is because it is supposed to be at a very low resolution and mutter imposes quality restrictions there that leads to this. It makes sense considering that the big preview is fine. In any case it is not something I can change.

**Comment by wwmm** [comment]
Scaling removed
