### ISSUE TITLE
PE states sample copy while using different sample rate

### ISSUE THREAD

**Issue by polygonalenippel** [wwmm/pulseeffects#735]
My music is 44.1 kHz and I have `avoid-resampling` turned on in Pulse (with 48k as alternate sample rate). Why is my hardware still set to 48k? I included the output of `pactl list sinks` for the relevant hardware.

As you can see, the 44.1k source is having its samples copied, while the 48k source is actually being resampled even though the hardware is set to 48k? What is going on?

![image](https://user-images.githubusercontent.com/29197220/88478008-1463cf80-cf45-11ea-935e-19b6a8a38927.png)

I have no other applications running which produce sound. The behavior did not change when I opened the application with the 48k audio.

Using
* pulse 13.0-3
* pulseeffects 4.7.3-1
* on Arch with linux-zen 5.7.9.zen1-1 kernel
* through a FiiO K3 DAC

**Comment by polygonalenippel** [comment]
Closing PE, restarting pulse and then starting pulse reverts the sample rate to 44.1k, however now it refuses to change to 48k. I believe this seems like an issue with pulse?

**Comment by wwmm** [comment]
Try to wait at least `5 seconds` after pausing all audio applications. Then start the one that has a different sampling rate. As you can see in #709 there is a Pulseaudio bug preventing `avoid-resampling` from fully working when PulseEffects is running. But automatically alternating between `44.1 kHz` and `48 kHz` should still be possible as long as you give time for all the audio sinks to reach the idle state. Only then Pulseaudio will try to update the rate.

**Comment by polygonalenippel** [comment]
@wwmm Even with 5 seconds of waiting, I cannot get the basic `avoid-resampling` to work. How can I best demonstrate this?

**Comment by wwmm** [comment]
Run `pactl list sinks` before starting the second app and show its output here. If the sound card sink or the `PulseEffects(apps)` state is `RUNNING` Pulseaudio will not try to change the rate.

**Comment by polygonalenippel** [comment]
This is what I get right after opening PE. There are no applications running.

```
Sink #1
        State: IDLE
        Name: alsa_output.usb-FiiO_K3-00.analog-stereo
        Description: K3 Analog Stereo
        Driver: module-alsa-card.c
        Sample Specification: s32le 2ch 48000Hz
        Channel Map: front-left,front-right
        Owner Module: 8
        Mute: no
        Volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
                balance 0,00
        Base Volume: 65536 / 100% / 0,00 dB
        Monitor Source: alsa_output.usb-FiiO_K3-00.analog-stereo.monitor
        Latency: 91924 usec, configured 99954 usec
        Flags: HARDWARE DECIBEL_VOLUME LATENCY 
        Properties:
                alsa.resolution_bits = "32"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = "USB Audio"
                alsa.id = "USB Audio"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "2"
                alsa.card_name = "K3"
                alsa.long_card_name = "FiiO K3 at usb-0000:04:00.0-1, high speed"
                alsa.driver_name = "snd_usb_audio"
                device.bus_path = "pci-0000:04:00.0-usb-0:1:1.0"
                sysfs.path = "/devices/pci0000:00/0000:00:1c.3/0000:04:00.0/usb5/5-1/5-1:1.0/sound/card2"
                udev.id = "usb-FiiO_K3-00"
                device.bus = "usb"
                device.vendor.id = "2972"
                device.vendor.name = "FiiO"
                device.product.id = "0047"
                device.product.name = "K3"
                device.serial = "FiiO_K3"
                device.string = "front:2"
                device.buffering.buffer_size = "35264"
                device.buffering.fragment_size = "8816"
                device.access_mode = "mmap"
                device.profile.name = "analog-stereo"
                device.profile.description = "Analog Stereo"
                device.description = "K3 Analog Stereo"
                alsa.mixer_name = "USB Mixer"
                alsa.components = "USB2972:0047"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-usb"
        Ports:
                analog-output: Analog Output (priority: 9900)
        Active Port: analog-output
        Formats:
                pcm

Sink #4
        State: IDLE
        Name: PulseEffects_apps
        Description: PulseEffects(apps)
        Driver: module-null-sink.c
        Sample Specification: s32le 2ch 44100Hz
        Channel Map: front-left,front-right
        Owner Module: 25
        Mute: no
        Volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
                balance 0,00
        Base Volume: 65536 / 100% / 0,00 dB
        Monitor Source: PulseEffects_apps.monitor
        Latency: 26267 usec, configured 40000 usec
        Flags: DECIBEL_VOLUME LATENCY 
        Properties:
                device.description = "PulseEffects(apps)"
                device.class = "sound"
                device.icon_name = "audio-card"
        Formats:
                pcm
```
![image](https://user-images.githubusercontent.com/29197220/88486220-7986e780-cf7c-11ea-8446-b695f5148ed0.png)

Now I start a 48k source:

```
Sink #1
        State: RUNNING
        Name: alsa_output.usb-FiiO_K3-00.analog-stereo
        Description: K3 Analog Stereo
        Driver: module-alsa-card.c
        Sample Specification: s32le 2ch 48000Hz
        Channel Map: front-left,front-right
        Owner Module: 8
        Mute: no
        Volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
                balance 0,00
        Base Volume: 65536 / 100% / 0,00 dB
        Monitor Source: alsa_output.usb-FiiO_K3-00.analog-stereo.monitor
        Latency: 92387 usec, configured 99954 usec
        Flags: HARDWARE DECIBEL_VOLUME LATENCY 
        Properties:
                alsa.resolution_bits = "32"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = "USB Audio"
                alsa.id = "USB Audio"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "2"
                alsa.card_name = "K3"
                alsa.long_card_name = "FiiO K3 at usb-0000:04:00.0-1, high speed"
                alsa.driver_name = "snd_usb_audio"
                device.bus_path = "pci-0000:04:00.0-usb-0:1:1.0"
                sysfs.path = "/devices/pci0000:00/0000:00:1c.3/0000:04:00.0/usb5/5-1/5-1:1.0/sound/card2"
                udev.id = "usb-FiiO_K3-00"
                device.bus = "usb"
                device.vendor.id = "2972"
                device.vendor.name = "FiiO"
                device.product.id = "0047"
                device.product.name = "K3"
                device.serial = "FiiO_K3"
                device.string = "front:2"
                device.buffering.buffer_size = "35264"
                device.buffering.fragment_size = "8816"
                device.access_mode = "mmap"
                device.profile.name = "analog-stereo"
                device.profile.description = "Analog Stereo"
                device.description = "K3 Analog Stereo"
                alsa.mixer_name = "USB Mixer"
                alsa.components = "USB2972:0047"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-usb"
        Ports:
                analog-output: Analog Output (priority: 9900)
        Active Port: analog-output
        Formats:
                pcm

Sink #4
        State: RUNNING
        Name: PulseEffects_apps
        Description: PulseEffects(apps)
        Driver: module-null-sink.c
        Sample Specification: s32le 2ch 44100Hz
        Channel Map: front-left,front-right
        Owner Module: 25
        Mute: no
        Volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
                balance 0,00
        Base Volume: 65536 / 100% / 0,00 dB
        Monitor Source: PulseEffects_apps.monitor
        Latency: 4264 usec, configured 10000 usec
        Flags: DECIBEL_VOLUME LATENCY 
        Properties:
                device.description = "PulseEffects(apps)"
                device.class = "sound"
                device.icon_name = "audio-card"
        Formats:
                pcm
```

![image](https://user-images.githubusercontent.com/29197220/88486251-bf43b000-cf7c-11ea-8687-1e4ee95a07cc.png)

**Comment by wwmm** [comment]
Even before playing something you card is on `48 kHz`:
`Sample Specification: s32le 2ch 48000Hz`
Strange. Did you set the default sample rate to `48 kHz` too? What do you have in your `daemon.conf` file?

**Comment by polygonalenippel** [comment]
`grep . /etc/pulse/daemon.conf | grep -v '^[;#]'` gives me:
```
high-priority = yes
nice-level = -15
realtime-scheduling = yes
realtime-priority = 9
resample-method = soxr-vhq
avoid-resampling = true
flat-volumes = no
default-sample-format = s32le
default-sample-rate = 44100
alternate-sample-rate = 48000
```
As you can see, the default sample rate is 44.1k

**Comment by polygonalenippel** [comment]
There is a lot of weird stuff happening with my Pulse lately, I'll try to investigate a little.

**Comment by polygonalenippel** [comment]
Here's what I did.

1. I reinstalled pulse with the following config:
```
avoid-resampling = true
flat-volumes = no
default-sample-rate = 44100
alternate-sample-rate = 48000
```

2. I closed PE

3. I continuously checked what the sinks were up to with `watch -n.2 pactl list sinks short`
For a sink to change sample rate, it needs to suspend which usually happens after a few seconds of inactivity.

4. I started PE

This actually worked fine when I was messing around, and PE played along nicely until it messed up big time spazzing out over the sample rate. I saw it wildly change in the terminal for a brief moment. I cannot recall what caused it (I think starting a 192k sample rate file). Restarting Pulse did not help. Using a different DAC also did not help. None of the sinks go back to suspension, instead they are stuck in idle.

**Comment by polygonalenippel** [comment]
**Rebooting** seems to fix the stuck sink states. Now I am using
- the same config as above
- the Topping NX4 DAC

**Before starting PE**, I tested out a 44.1k song and a 192k "song", and I tried every conceivable pattern of playing the files with the intent of reproducing the broken sinks. I couldn't break it. Pulse changed sample rate to whatever the source was, given supported by my DAC.

**After starting PE**, it worked again, however 192k and 96k songs set my DAC to 48k, which is the alternate sample rate I specified in Pulse. Why @wwmm ? Closing PE sets it back to the correct sample rate.

Switching back to the FiiO K3 I'm experiencing the same as with the NX4, so that's good. However I still cannot break Pulse like I did in the previous comment.

**Comment by polygonalenippel** [comment]
After lots of fiddling around, it seems disconnecting a DAC messes up Pulse in a way the sinks refuse to go into suspension, thus preventing the sample rate to be changed. I think this is what happened when I initially used the K3, which has a slightly fragile USB C connection.

Can anyone else confirm this with their DAC?

**Comment by polygonalenippel** [comment]
Upon disbanding my investigation setup I noticed: closing Pavucontrol seems to fix the idling issue... wtf?

**Comment by wwmm** [comment]
>Before starting PE, I tested out a 44.1k song and a 192k "song", and I tried every conceivable pattern of playing the files with the intent of reproducing the broken sinks. I couldn't break it. Pulse changed sample rate to whatever the source was, given supported by my DAC.

This is expected. `avoid-resampling` is working fine with the card sink. The bug mentioned a few posts above is present only in virtual devices (null sinks). And PulseEffects has to use one.

>After starting PE, things still work as expected, except that 192k and 96k songs set my DAC to 48k, which is the alternate sample rate I specified in Pulse. Why @wwmm ? Closing PE sets it back to the correct sample rate.

Probably because Pulseaudio set our virtual sink to `48 kHz` at some point. And because of the bug the sink rate got stuck at this value.

>closing Pavucontrol seems to fix the idling issue... wtf?

I think I never tested  Pulseaudio automatic rate switching with Pavucontrol opened. Interesting. In other to show volume meters Pavucontrol has to run an audio stream that records audio from the sink monitor. My guess is that this recording streaming is keeping the sink busy. And as a result the rate was locked.

In any case have in mind that without Pulseaudio 14(still to be released) you won't have a working solution for any pair of rates different than `(44.1 kHz, 48 kHz)`. PulseEffects needs a virtual device and until the Pulseaudio but is fixed its rate will be locked to 44.1 kHz or 48 kHz.

**Comment by wwmm** [comment]
>...until the Pulseaudio but is fixed...

Just to clarify Pulseaudio has already been patched to fix this bug. We just need to wait for Pulseaudio `14` to be released.

**Comment by polygonalenippel** [comment]
Alright, thanks.
Despite everything is clear now, I still can't reproduce that which I initially opened the issue for (the weird resample thing in the first screenshot). I will leave it as is as I couldn't reproduce it since. We can close this issue now I think.

**Comment by wwmm** [comment]
Ok.
