### ISSUE TITLE
Pipeline output level meter and plugin checkbox

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#737]
I added the global output meter to both pipeline as stated in #724 

I exposed it in application button row.

<details>
<summary>Screenshot</summary>

![Schermata del 2020-08-03 17-03-46](https://user-images.githubusercontent.com/25790525/89199375-be2f0600-d5ae-11ea-99fd-272d1a3f8a75.png)

</details>

Now I should remove notification icons from every plugin in listbox, but I thought to add a checkbox to enable/disable a plugin without entering in its ui.

<details>
<summary>Checkbox</summary>

![Schermata del 2020-08-03 17-21-47](https://user-images.githubusercontent.com/25790525/89199392-c4bd7d80-d5ae-11ea-92e5-0a83cc2091ee.png)

</details> 

What do you think @wwmm?

**Comment by wwmm** [comment]
>I exposed it in application button row.

Interesting. I did not think about this place. As things are right now it is probably the best location.

> I thought to add a checkbox to enable/disable a plugin without entering in its ui.

I think that it would be better to replace the checked icon at the right side by the checkbox. Showing both is not necessary.

**Comment by wwmm** [comment]
And with the checkboxes the on/off switch currently used could also be removed. I think that a few users would be confused by two widgets to turn on/off plugins. Maybe we should have only the checkboxes. This together with a repositioning of each plugin reset button would reduce a little the amount of vertical space the window currently requires.

**Comment by Digitalone1** [comment]
> I think that it would be better to replace the checked icon at the right side by the checkbox. Showing both is not necessary.

Sure, all saturation icons should be deleted

> And with the checkboxes the on/off switch currently used could also be removed. I think that a few users would be confused by two widgets to turn on/off plugins. Maybe we should have only the checkboxes. This together with a repositioning of each plugin reset button would reduce a little the amount of vertical space the window currently requires. What would be welcome.

Maybe in the line where there is  plugin credit.

**Comment by wwmm** [comment]
>Maybe in the line where there is plugin credit.

I think it would be a good place.

**Comment by wwmm** [comment]
Right now I am working on #588 but let me know if need any help with this.

**Comment by Digitalone1** [comment]
Maybe tomorrow or Wednesday I should be able to make the pull request. Then there's to update the documentation, but that can be done later.
