### ISSUE TITLE
Text does not load in window or title bar

### ISSUE THREAD

**Issue by MadmartiganKilmer** [wwmm/pulseeffects#739]
Program seems to load ok except all the text appears as a missing font.

I'm running Linux Mint 19, 64bit, Cinnamon.

![Screenshot from 2020-07-31 12-37-16](https://user-images.githubusercontent.com/69217342/89337808-6943cc00-d650-11ea-9455-57b06427dbd1.png)

**Comment by wwmm** [comment]
It is similar to #719 but I do not know how that user solved this issue. What I can say is that we do not force any font. We let GTK choose whatever system font it considers to be the default.

**Comment by MadmartiganKilmer** [comment]
I had my Default font set to URW Gothic L Book. Setting it to pretty much anything else fixes the problem.

Drat... I loved that as a system font! Out of curiosity, does anyone know why that particular font would cause a problem?

Thanks for the help, btw.

**Comment by wwmm** [comment]
>does anyone know why that particular font would cause a problem?

I have no idea. The text are shown through standard GTK labels with no special formatting.
