### ISSUE TITLE
error during the installation on ARM

### ISSUE THREAD

**Issue by araczkowski** [wwmm/pulseeffects#74]
`flatpak install com.github.wwmm.pulseeffects.flatpakref`

`Installing: com.github.wwmm.pulseeffects/arm/stable
Warning: Can't find dependencies: No entry for app/com.github.wwmm.pulseeffects/arm/stable in remote summary flatpak cache 
Installing: com.github.wwmm.pulseeffects/arm/stable from flathub
error: No such ref 'app/com.github.wwmm.pulseeffects/arm/stable' in remote flathub`

is it possible to run this program on ARM board?

**Comment by wwmm** [comment]
I think that arm architecture does not have a gfortran dependency. See one of the commits in [https://github.com/flathub/com.github.wwmm.pulseeffects](https://github.com/flathub/com.github.wwmm.pulseeffects)

**Comment by AsavarTzeth** [comment]
That is correct. While PulseEffects itself would work on arm the Numpy/Scipy stack it relies upon, and in turn its dependencies, require gfortran.

As long as PulseEffects depends on Scipy and the gfortran extension is unavailable for arm, support will be limited to x86 architectures.

Numpy you can sort of build without lapack and any fortran dependencies, but it is not recommended.

**Comment by wwmm** [comment]
Closing as there is nothing we can do about these missing dependencies

**Comment by AsavarTzeth** [comment]
If anyone is still subscribed to this I thought I would mention that the PulseEffects flatpak is in fact now available for both 32-bit and 64-bit arm architectures.
