### ISSUE TITLE
Road to 4.7.4

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#741]
- [x] Update changelog with new pipeline global output level meter, new `Loudness Compensator` plugin and the ability to change the minimum and maximum frequency in the spectrum
- [x] Implement `Loudness Compensator` documentation
- [x] Removing `mda` optional dependency from PKGBUILD
- [x] Remove `mda.lv2` link from readme
- [x] Let package maintainers know version 4.7.4 will only work with `lsp-plugins` >= 1.1.24 and does not require mda dependency for Loudness plugin 
- [x] Replace the hardcoded spectrum frequency axis by drawings in the cairo canvas
- [x] Allow the user to change the minimum and maximum frequency shown by the spectrum
- [x] Allow the `Stereo Tools` plugin to be used in the mic pipeline
- [x] Allow the `Maximizer` plugin to be used in the mic pipeline

**Comment by wwmm** [comment]
> Let package maintainers know version 4.7.4 will only work with lsp-plugins >= 1.1.24

I have also made `GTKMM 3.24` a required dependency. It finally has a few wrappers for GTK functions that were missing before and I am using them to simplify the code.

**Comment by wwmm** [comment]
I think I will also try to to these improvements before the next release:

```
-[] replace the hardcoded spectrum frequency axis by drawings in the cairo canvas
-[] allow the `stereo tools` plugin to be used in the mic pipeline
```

**Comment by Mlocik97-issues** [comment]
Nice,... I will have ability to use stereo tools for mic... next add maximizer, and it will be really best. Thanks so much for Your work.

Btw. about documentation, 

`PulseEffects > Plugins >> Crystalizer`
contain 

> Aggressive Mode
When this option is enabled sample amplitude dependent amplification will be applied to the signal. Take care to not saturate the next plugin in the processing chain.

So there is info about what is it doing, when aggressive mode is active,... but what about, when it's inactive? It should be good to add this info too.

**Comment by Digitalone1** [comment]
@wwmm are you working on the documentation? I can do it.

**Comment by wwmm** [comment]
>are you working on the documentation? I can do it.

Not yet. If you have time to take a look at it go ahead. Now that the master branch already has the `stereo tools` plugin available for microphone effects I will do the same for the `maximizer`.

**Comment by Digitalone1** [comment]
Before to release the new version, please tell me to make an update to po translation files.

**Comment by wwmm** [comment]
No problems. I do not have a date in mind yet.

**Comment by wwmm** [comment]
First version of the new frequency axis. Its color can already be customized but it is not saved to the presets yet. Code is already available in the master branch.

![Screenshot from 2020-08-11 13-07-46](https://user-images.githubusercontent.com/16225172/89921396-0617e380-dbd4-11ea-9d29-75d57bacfa1a.png)
![Screenshot from 2020-08-11 13-09-29](https://user-images.githubusercontent.com/16225172/89921402-07491080-dbd4-11ea-8b46-8f803491790a.png)

**Comment by Digitalone1** [comment]
I tried to change max/minimum frequency, but it's not changing. Is it working with the new commits? I will compile.

**Comment by Digitalone1** [comment]
It's working. Great!

**Comment by wwmm** [comment]
It is working. But after doing a few tests with the test signal generator I noticed that the frequency shown in the axis for the peak of a sine wave is not right. I will investigate.

**Comment by wwmm** [comment]
And the frequency shown by the mouse hover also has to be corrected...

**Comment by wwmm** [comment]
Master branch updated with a fix for the mouse hover frequency values. The axis values are still wrong...

**Comment by wwmm** [comment]
And depending on the window width the last two labels in the axis may overlap. This also has to be fixed.

**Comment by wwmm** [comment]
The master branch has been updated again. Now the labels seem to be in the correct position.

**Comment by Mlocik97** [comment]
Can Frequencies be written under spectrum bars and not over, like in older version?

**Comment by wwmm** [comment]
>Can Frequencies be written under spectrum bars and not over, like in older version?

I have been thinking about that. It definitely can be done. But as it was clear that this would require a little more work I decided to do something simpler first. In short the code that draws the bars(or lines) has to take the height of the words in the axis into account and do the height shift accordingly. I will try to do that tomorrow.

**Comment by Mlocik97** [comment]
Btw. I think this is road to 4.8.0 and not 4.7.4... when I see how a lot of changes was done, and how a lot of things was changed, and features improved, I think, this deserve to be 4.8.0 version.

![Snímka obrazovky z 2020-08-11 21-35-00](https://user-images.githubusercontent.com/34808350/89940893-8a8d5500-dc1a-11ea-9187-de1fa03fce79.png)

This is nearly new record in count of changed lines.

**Comment by wwmm** [comment]
New version available in the master branch:
![Screenshot from 2020-08-12 11-29-24](https://user-images.githubusercontent.com/16225172/90036427-6de43200-dc99-11ea-81a1-591512af83aa.png)

>I think this is road to 4.8.0 and not 4.7.4

That is something to consider. Specially because there are small changes to the user workflow(enable/disable plugins), new parameters(compressor and limiter) and dependencies changes.

**Comment by Digitalone1** [comment]
It should be also tested on FreeBSD before to be released.

**Comment by Mlocik97** [comment]
I will translate Slovak (and propably Czech) languages today.... I will have some time at ~19:00 CET

**Comment by wwmm** [comment]
PE `4.8.0` released.
