### ISSUE TITLE
Fine-grained slider input control

### ISSUE THREAD

**Issue by polygonalenippel** [wwmm/pulseeffects#743]
I used to be able to use the arrow keys to very precisely adjust slider bars (e.g. the preamp). Updating my systems a few weeks ago removed this functionality across all my instances. Now I would have to either exactly type it into the preset config file, or resize the window to large dimensions so I have the desired granularity.

Is this a theme thing? Can we get the old behavior back otherwise?

"_But you can just hold down the mouse for finer mouse control!_" I hear you say. But this doesn't quite cut the exact control you would have with a keyboard.

**Comment by wwmm** [comment]
>But you can just hold down the mouse for finer mouse control!

No. I usually use the scroll XD

As I never use the keyboard arrows I did not notice this. For some reason it does not work on the equalizer sliders. But I can use the keyboard arrows just fine on other plugins. I wonder if it is because of the smaller step used in the equalizer sliders. But if that is the case it would be a GTK issue.

**Comment by wwmm** [comment]
>it would be a GTK issue

It isn't. For some reason `Step Increment` and `Page Increment` were set to zero in the equalizer interface glade file. I will fix them.

**Comment by polygonalenippel** [comment]
> I usually use the scroll

Didn't know that was possible lol. However it only works on vertical sliders as far as I tested.

**Comment by wwmm** [comment]
I declared victory too soon. Somehow it is working only in the Glade Preview but not when compiling the code. It does not make sense =/

**Comment by wwmm** [comment]
> However it only works on vertical sliders as far as I tested

I use it on horizontal sliders too.

**Comment by polygonalenippel** [comment]
Perhaps it's time to rewrite it in Qt :^)

> I use it on horizontal sliders too.

Very weird. Which horizontal slider did you try? The Input/Output in Equalizer don't budge on scroll.

**Comment by wwmm** [comment]
>The Input/Output in Equalizer don't budge on scroll.

On my computer they work. But now that I am playing with the number of digits in the glade xml file the band gain slider does not work with scroll anymore. Either glade is doing something odd or GTK. I am not sure why yet.

**Comment by wwmm** [comment]
>Perhaps it's time to rewrite it in Qt 

In the past I considered that. A few times to tell the truth. The conclusion was always "it will be a nightmare to rewrite what we have in Qt". Being able put widgets in menu through popovers and in the titlebar is really convenient. Just like is using GSettings to handle presets. And although GStreamer can be used in Qt it is just easier to bind the tons of properties we have when using  GTK. At least to me GObject binding does not seems to be a first class citizen in Qt. It seems alien there. And that is what GStreamer uses to bind properties. 

Somehow the way GTK handles translations seems more straightforward to me. There is also the fact that GTK offers a service mode for free. As much as I know that having a standalone service running in the background would be the correct way to go the amount of work required in this approach is insane.

**Comment by wwmm** [comment]
And bugs are present in all toolkits :P

**Comment by polygonalenippel** [comment]
It's just that my only GUI experience is from the few Qt projects I've had. Unfortunately I can't be of much assistance when it comes to GTK.

**Comment by wwmm** [comment]
No problems :-)

After many tests I think I found something.  If I set the step to something smaller than `1` even the scroll does not work. ON the other plugins the step is `1`. On the equalizer there was need for a more fine grained control so the smallest steps are `0.1` in the band slider and `0.01` in the input/output gain. As far as I remember this wasn't a problem. Sounds like a bug in GTK.

**Comment by polygonalenippel** [comment]
Strange. Hopefully they'll fix it before they [add the filepicker thumbnails](https://gitlab.gnome.org/GNOME/gtk/-/issues/233).

**Comment by wwmm** [comment]
I was finally able to fix this. The bug is in Glade(gtk's answer to qt designer) and not in GTK. It is saving the increments values with comma `0,01` instead of a dot `0.01`. Now I can use both the scroll and the keyboard arrows. I have just updated the master branch with the fix.

**Comment by wwmm** [comment]
At least it seems that the Glade developers have already fixed this bug https://gitlab.gnome.org/GNOME/glade/-/issues/376. So its next version should not have this problem.

**Comment by wwmm** [comment]
But until it is released I will have to remember to edit the xml files manually to fix this whenever I have to edit something in the equalizer xml files =/

**Comment by Digitalone1** [comment]
@wwmm in the commit you saved same increments with the point and same others with the comma.

To avoid this, you have to run Glade from command line prepending `LC_ALL=C`.

**Comment by Digitalone1** [comment]
I make some adjustements to step and page increments in glades. Will make the pull request later.

**Comment by wwmm** [comment]
Ok

**Comment by wwmm** [comment]
Considering that Glade was the real source of the problem I think we can close this.
