### ISSUE TITLE
PulseEffects greyed out /crashing with Ubuntu 20.04.1

### ISSUE THREAD

**Issue by LeonArundell** [wwmm/pulseeffects#748]
PulseEffects is currently preventing sound from reaching my speaker or headphone jacks.

Here is my history:

After updating to Ubuntu 20.04.1 I installed PulseEffects from Ubuntu Software.
The equalizer seemed to remember my previous settings, but it and all other PulseEffects features were greyed out and could not be adjusted.
I found a workaround that installed missing components, and allowed me to use the Equalizer to fully reconfigure my frequency spectrum. I could save equalizer settings, but, as I don't know where on my system they were saved, I could not restore them. In other respects, PulseEffects seemed to be working as intended.

After a reboot, I would get sound for a second or two, and then no sound at all.

After further reboots I get no sound at all. When I open PulseEffects, the user interface crashes after about two seconds.

**Comment by wwmm** [comment]
Kill PulseEffects with the command `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. This way we will know if any obvious error is happening in the initialization.

**Comment by LeonArundell** [comment]
Thanks, wwmm.

After I entered the command "G_MESSAGES_DEBUG=pulseeffects pulseeffects," the terminal responded with a list of outputs, ending with:

(pulseeffects:5328): glibmm-ERROR **: 10:46:45.268: 
unhandled exception (type std::exception) in signal handler:
what: /home/leon/.config/PulseEffects/output/Leon 16 band.json: cannot open file

The only file in that directory is "Sennheiser for Leon.json"

I copied the json file and renamed the copy as "Leon 16 band.json"

The equalizer is now working, and when I click on "Leon 16 band" on the title bar I can choose either of the two presets ("Leon 16 band" or "Sennheiser for Leon."
Managing presets is briefly explained in the "Creating and Importing User Presets" section of the help files.
