### ISSUE TITLE
Not an issue, add mono output

### ISSUE THREAD

**Issue by servimo** [wwmm/pulseeffects#75]
Possible to add mono output? sum of both channels?

**Comment by wwmm** [comment]
If there is a stereo gstreamer or ladspa plugin that add the channels it should be possible.

**Comment by servimo** [comment]
Sometimes I put a sound monitor in another room and if is a music with extreme stereo only the drums or vocals goes out. It could be nice if only a button could do this. I search the Internet and did not found a way. Except for the crossfeed plugin for Gstreamer which is old and does not works, or maybe for what I understand will mix only the same frequency

**Comment by wwmm** [comment]
As I could not find a plugin that does that I will close this issue. Something you may try is using pavucontrol to configure the sound card as mono instead of stereo. I didn't test here but I think it is possible.
