### ISSUE TITLE
Required gtk+ version 3.20, current version is 3.18

### ISSUE THREAD

**Issue by eera5607** [wwmm/pulseeffects#76]
Is it possible that you can lower GTK+ library requirements to 3.18 maybe? I keep getting this error:  Required gtk+ version 3.20, current version is 3.18 on Ubuntu 16.04. As far as I understand v3.20 is not available for Ubuntu 16.04. Thanks.

**Comment by wwmm** [comment]
I will take a look. I decided to use 3.20 as minimum when glade showed me a warning saying that a property of one of the plugins I am using does not exist in gtk < 3.20. 

I think I am not using that property but I have to check. In the mean time could you open the glade files inside the folder `ui` and change the required gtk version at the line with `<requires lib="gtk+" version="3.20"/>`? You can edit these files with a text editor like gedit, kate or vim. I do not have how to test PulseEffects with gtk 3.18 so it would be good if someone else could do that.

**Comment by eera5607** [comment]
Thank you. Is working wine now. Just changed `<requires lib="gtk+" version="3.20"/>` to `<requires lib="gtk+" version="3.18"/>` on `about.blade` `headerbar.glade` `man_ui.glade` `sink_inputs_plugins.glade` and `source_outputs_plugins` on `ui` folder. Everything seems to be working fine now. Thank you again.

**Comment by wwmm** [comment]
ok. I will lower this requirement when I release PulseEffects 3.0
