### ISSUE TITLE
Effects grayed out, no plugins found [SOLVED]

### ISSUE THREAD

**Issue by swilwerth** [wwmm/pulseeffects#771]
Recently I had this issue appearing on my ubuntu 18.04, similar to #488

PulseEffects version: 4.7.2

No Reverberation, No Bass Enhancer
(It shows 'plugin was not found' warning at startup for these) 

**I solved it** by removing calf-ladspa and reinstalling calf from sources.

Some other packages which are needed to be installed/upgraded to make calf compile:

libjack0 (not installed)
libjack-dev (not installed)
lv2core (not installed, not found on the repos, installed from source: https://lv2plug.in/spec/lv2core-6.0.tar.bz2 )

For details of the dependencies needed visit: https://calf-studio-gear.org/

Removing the gstreamer cache did not solve the problem for me.

I'm only here to give a record of the issue.

**Comment by Talkless** [comment]
> **I solved it** by removing calf-ladspa and reinstalling calf from sources.

So it's `calf-ladpsa` package problem/bug in Ubuntu - it's simply not built "good enough"?

**Comment by swilwerth** [comment]
I'm in doubt now.
I reinstalled calf-ladspa_1.1.3-7_amd64.deb 'as is' from the repos again and the thing works now.

When I tried to build calf I got:

```
configure: error: 

Obsolete LADSPA version of the Calf plugins has been detected:
    /usr/lib/ladspa/calf.so

It will interfere with the current version. Please remove the file and try
again.

```

So I removed it, in order to rebuild calf.

Something in the process of rebuild calf made the problem to disappear.

Like when you have a faulty vintage electronic equipment and replace all the electrolytic capacitors, then it starts working.
It might be a component, or it might be various components.

Can it be a lv2core related?
I can't find lv2core on the ubuntu repos, but it seems to be a required dependency of calf.

**Comment by Mlocik97** [comment]
I have 4.7.2 on Ubuntu 18.04 from package provided by mikhailnov (sudo add-apt-repository ppa:mikhailnov/pulseeffects -y)

if You install pulseeffect by this command: sudo apt install pulseeffects, on older version of Ubuntu (18.04 for example) it's problematic and not working correctly. You should use that command before installing, as is written in Wiki:

https://github.com/wwmm/pulseeffects/wiki/Package-Repositories#debian--ubuntu

**Comment by swilwerth** [comment]
I installed it from the mikhailnov repository, but it stopped working somewhere after updates.

**Comment by wwmm** [comment]
I wonder why some distributions are still packaging the LADSPA version of the Calf plugins. They moved to LV2 a long time ago.

**Comment by swilwerth** [comment]
Woah! That might be the problem here.
That package is not a dependency of any other installed on my system, so I'm banning it right now.

For those who might find this thread in the future:

`sudo apt-mark hold calf-ladspa`

This will mark calf-ladspa as non installable, non upgradable

**Comment by Mlocik97** [comment]
OK, so I just get look on what I have installed, because 4.7.2 for Ubuntu 18.04 is working fine for me:

```
calf-plugins/bionic,now 0.90.1-1~bionic1 amd64
rubberband-ladspa/bionic,now 1.8.1-7ubuntu2 amd64
mda-lv2/bionic,now 1.2.2~dfsg0-2 amd64
samplv1-lv2/bionic 0.8.6-1 amd64
so-synth-lv2/bionic 1.4-2 amd64
swh-lv2/bionic 1.0.16+git20160519~repack0-3 amd64
```

**Comment by swilwerth** [comment]
I think I found the reason why it failed. 
I uninstalled all the manually installed packages (calf and lv2core)

Then I queried the package manager for a missing dependency of pulseeffects issuing this command:
```for i in `apt-cache depends pulseeffects | awk -F: '{ print $2 }'`; do apt -q list "$i"; done | grep -v installed```

calf-plugins/bionic,now 0.90.1-1~bionic1 amd64

Is not installed.
Then I started pulseeffects and the issue appears, logically as expected.

I don't know what caused that package to uninstall in first place.
I installed it manually issuing:

`sudo apt install calf-plugins`

And, voila!, the thing works now.

Then I searched for the calf-ladspa reverse dependencies

And I found this:

```
$ apt-cache rdepends calf-ladspa

calf-ladspa
Reverse Depends:
  lmms
```

Both packages (calf-plugins and calf-ladspa) seems to be able to co-exist in the same system, so I removed it from the backlist.

`sudo apt-mark unhold calf-ladspa`

I forced a reinstall of lmms to see if it conflicts with calf-plugins, but no conflicts were found.

I think calf-plugins was somewhat marked as a candidate for the 'autoremove' process.
I can't find in my command history any reference to its deletion.

However there are two versions of calf-plugins available to install:
``` 
$ apt list calf-plugins -a 

calf-plugins/bionic 0.90.1-1~bionic1 amd64
calf-plugins/bionic 0.0.60-5 amd64
```

And its reverse dependencies are:
``` 
$ apt-cache rdepends calf-plugins
calf-plugins
Reverse Depends:
  pulseeffects
  calf-ladspa
  ubuntustudio-audio-plugins
  multimedia-audio-plugins
```

It may got removed automagically or it may got installed in its prehistoric version by calf-ladspa.
I don't know.

**Comment by arighi** [comment]
I'm experiencing this exact problem right now in Ubuntu 20.10, tried to uninstall/reinstall calf-plugins & lsp-plugins-lv2, no success. Any suggestion?

**Comment by wwmm** [comment]
@arighi the first step is getting logs. Kill the current PulseEffects instance with the command `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. As your Ubuntu version is different than the one here I suggest you open a new issue.
