### ISSUE TITLE
Train/Arrows for indicate order of plugins of UI, that will also solve missunderstanding off "Applications" text as "title for plugins column".

### ISSUE THREAD

**Issue by Mlocik97** [wwmm/pulseeffects#772]
@wwmm when I first time opened app, I thought it same as title... Propably because text is placed in box with smaller height. I have one idea... Before names, put dots and arrows from one dot to another. Which will represent order. (Similiar like are using some "Train apps")

https://lh3.googleusercontent.com/cuEAQ8mCs5ze04UNcNKIzSi3oBv9FVxaLwhE4ABFFRAQdT9C11ui9-AxEMeGBPM5Ew=w2000

_Originally posted by @Mlocik97-issues in https://github.com/wwmm/pulseeffects/issues/559#issuecomment-522992166_

(I recreated and exctracted issue as separate issue, and original can be closed, so it's easier to find issue itself)

---

I had idea, that, we already have check boxes, before Plugin name, We can add filled square before "Application" text, and draw arrows from that to first check box, and then from checkbox to another one... close https://github.com/wwmm/pulseeffects/issues/559

**Comment by Digitalone1** [comment]
Are you using the latest released version? The UI was redesigned and now all plugin rows have a checkbutton. They distinguish the plugins from the application tab.

**Comment by Mlocik97** [comment]
> I had idea, that, **we already have** check boxes, before Plugin name..

yes, I'm exactly talking about it... we can use them as points for drawing lines/arrows that will indicate order of plugins.

**Comment by Digitalone1** [comment]
I'm afraid this can't be done looking at what gtk glades offer.

**Comment by Digitalone1** [comment]
> (rough sketch, in GTK, we have native func for drawing arrow, so we can propably use it)

Which one? Can you link them?

**Comment by Mlocik97** [comment]
I think

`#include <gtkmm/arrow.h>`

contain func, that can draw arrows... But because every Plugin list item is own area, I think, it will be little hard to draw it over two these areas.

**Comment by Mlocik97** [comment]
If not arrows, than at least put one filled square point before Application text in line, and set that line to same height as plugins. It should be enought to indicate, it's not title for plugins column.

**Comment by Mlocik97** [comment]
> I'm not mistaken it as title

depend on GTK theme, You use,... in some, it really look like title for column with plugins,... as You can see in https://github.com/wwmm/pulseeffects/issues/559 , I'm not only one that missunderstand that.

**Comment by Mlocik97** [comment]
hm, yeah, that's true... I didn't think about it, but You are right. So Icon should be fine.

**Comment by Digitalone1** [comment]
The headerbar is already filled with lots of buttons and information, I don't think it's really good to write other things on it.

Besides, it was primarily done to advertise the user that the output level is over 0 dB showing a saturation icon. Maybe could be disturbing, but that place is good to make the user know the output stream is clipping. Other places could not be noticed.

Before every plugin had an icon to do that. Now only the application one.

**Comment by Mlocik97** [comment]
Or we can create status bar, but the way, it will not be over column with plugins... so Something like:

![Snímka obrazovky z 2020-09-03 12-45-41](https://user-images.githubusercontent.com/34808350/92105756-974d3500-ede3-11ea-9426-3d57acff07be.png)
