### ISSUE TITLE
Equalizer not working in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by ratcheer** [wwmm/pulseeffects#776]
I have been searching for days on how to get the parametric equalizer working in my openSUSE Tumbleweed system. lsp-plugins is installed and so is lv2-lsp-plugins. The gui functions as if the equalizer was being switched in, and in fact the volume goes down because I have set the input level to -7.2 dB. However, no actual equalization is done.

Just now, I started pulseeffects from the command line, and I got the following among several lines of output:

(pulseeffects:14628): GLib-GObject-WARNING **: 19:24:27.122: g_object_set_is_valid_property: object class 'lsp-plug-in-plugins-lv2-para-equalizer-x32-lr' has no property named 'bypass'

I am afraid there is a software versions mismatch. I have pulseeffects  4.7.1-1.4, lsp-plugins 1.1.24-1.1, and lv2-lsp-plugins 1.1.24-1.1.

Please let me know if there is anything I can do to get the equalizer working. Thank you.

**Comment by wwmm** [comment]
>I am afraid there is a software versions mismatch

Unfortunately that is the reason. You can read the details in our changelog https://github.com/wwmm/pulseeffects/blob/master/CHANGELOG.md. Long story short when lsp-plugins was updated to `1.1.14` it went through changes that required an update on our side. PulseEffects `4.7.1` will only work with older lsp-plugins versions. From PulseEffects `4.7.2` to `4.7.3` the lsp-plugins version has to be betwenn `1.1.14` and `1.1.23`. From PulseEffects `4.8.0` onwards lsp-plugins has to be equal or higher than `1.1.24`.

>Please let me know if there is anything I can do to get the equalizer working

In these situations using a flatpak package is the easiest solution https://flathub.org/apps/details/com.github.wwmm.pulseeffects. You would have to see how to install these kind of packages in OpenSUSE. The downside is that flatpak packages are really big. But that is exactly the reson why they do not have this kind of dependency issue. All the required libraries are shipped within the package.

**Comment by ratcheer** [comment]
Thank you. I will look at using the Flatpak. I had to do that for another application, too. openSUSE calls this a "rolling release", but they don't keep up very well.
