### ISSUE TITLE
Broken package by hosiet.

### ISSUE THREAD

**Issue by Mlocik97** [wwmm/pulseeffects#777]
![Snímka obrazovky z 2020-09-06 13-02-19](https://user-images.githubusercontent.com/34808350/92324364-55212f00-f041-11ea-93c3-804dfaad57a4.png)

In Ubuntu 18.04 I have installed 4.7.2 by ppa:mikhailnov, and with same settings, I input -3db, output -3db (Because Input Gain was set to -3dB, and Limit to -3dB, so it never reached limit, without pre-sampling.

But In Ubuntu 20.04 I have installed 4.7.1 by hosiet, and with these settings, I get input -3dB, but output -6dB. And it should not reduce volume, even in "reducing bar" is 0 value, so whatþs happening?

E: OK, it seems, that, package by hosiet is broken.

![Snímka obrazovky z 2020-09-06 13-10-17](https://user-images.githubusercontent.com/34808350/92324480-63237f80-f042-11ea-8d62-dfd7f91985c3.png)

but still, EQ is working, and has effects on sound, but Iþm not able to change settings.

**Comment by Digitalone1** [comment]
I didn't understand you issue but, anyway, I think it depends on which calf version you are relying. Previous versions had auto-leveling set by default while latest have exposed the option that has been added to PulseEffects UI from 4.8.0.

Why Ubuntu is using such an old version of PulseEffects? Can you please install the latest from Flatpak or install from source by git repository?

**Comment by Mlocik97** [comment]
I have this version of Calf

`calf-plugins/focal,now 0.90.3-1build2 amd64 [installed,automatic]`

I have bad experiences with Flatpak, so I'm not using it.

**Comment by Digitalone1** [comment]
https://github.com/wwmm/pulseeffects/commit/dee734cbb65f6d8edeab70e9cd0e18f7a9def4c6

>   // Calf limiter did automatic makeup gain by the same amount given as limit.
  // See https://github.com/calf-studio-gear/calf/issues/162
  // That is why we reduced the output level accordingly binding both limit and output-gain to the same,
  // gsettings key, but from 0.90.2 version the "auto-level" toggle was introduced, so we expose the
  // output gain as a separate parameter along with the automatic level button.

So if you set limit -3 dB, the output is reduced the same 3 dB. If you get different output levels across versions, it seems one of them is not performing autoleveling while the output is still reduced by the same amount of limit.

**Comment by Mlocik97** [comment]
Oh I see, thanks...
