### ISSUE TITLE
[Request] Channel duplication for professional audio interface users

### ISSUE THREAD

**Issue by spsx** [wwmm/pulseeffects#779]
Some of us have professional audio interfaces, like the [Focusrite Scarlett](https://focusrite.com/en/usb-audio-interface/scarlett/scarlett-solo) or [Behringer UMC202](https://www.behringer.com/product.html?modelCode=P0BCG). These devices typically have two mono microphone inputs and a stereo audio output.

Those devices are treated by Pulseaudio as an "Analog Stereo Duplex" device, with a stereo input and output. However, most people use a mono microphone with such interfaces, and as a result the sound appears (to Pulseaudio) on one channel. The typical fix is to manually remap the specific stereo channel to mono, using Pulseaudio's *module-remap-source* or a similar ALSA command.

It would be nice for Pulseffects to have a setting allowing us to use a single microphone channel for the input, which would duplicate the chosen left or right channel to the other side so it can be filtered properly and show up as a stereo channel to applications. I feel that many broadcasters and streamers use Pulseeffects, and many of those people use audio interfaces. This feature would be a nice touch.

![Screenshot from 2020-09-07 13-25-35](https://user-images.githubusercontent.com/19350831/92409189-b7dffc80-f10d-11ea-9e4c-06ab72c425b4.png)

**Comment by wwmm** [comment]
It seems to me that the `stereo tools` plugin would be enough for this task. Or am I missing something?

**Comment by wwmm** [comment]
I faced a similar problem recently. For some reason when I plug my headset microphone in my onboard card jack its sound was present only in the left channel. I used the stereo tools plugins to make a stereo sound
![Screenshot from 2020-09-07 14-53-27](https://user-images.githubusercontent.com/16225172/92410264-f380c380-f119-11ea-8882-bbcfa52082a3.png)

**Comment by wwmm** [comment]
But this is something that can only be done in PulseEffects `4.8.0`

**Comment by spsx** [comment]
Ah, I only have version 4.7.2 (from Mikhail's PPA), which doesn't have Stereo Tools on the input channel. I tried it on the output though, and the effect performs as advertisted. Guess I'll wait for him to update the PPA.

As an aside, the proper way to do this in Stereo tools though would be to use LR->LL, rather than LR->L+R (Mono Sum) as shown in your screenshot. While the Mono Sum will send the sound to both channels, the volume of the mic will decrease since we're summing a full left channel and an empty right channel. To prevent clipping incase both channels are outputting full scale, the effect will only allow a maximum of 50% of the sound to be provided by one channel. In contrast, directly mapping LR->LL will send the full strength left channel directly to both channels.

![2020-09-07-142929_1413x722_scrot](https://user-images.githubusercontent.com/19350831/92411650-aea75d80-f116-11ea-9a9f-cecc135fec3d.png)
![2020-09-07-142939_1413x722_scrot](https://user-images.githubusercontent.com/19350831/92411651-b109b780-f116-11ea-80fc-0be5943ca9d8.png)

I'm closing this issue, thanks!

**Comment by wwmm** [comment]
>the proper way to do this in Stereo tools though would be to use LR->LL

You are right. I did not even think about this other option. Thanks!
