### ISSUE TITLE
makes sound very scratchy

### ISSUE THREAD

**Issue by karl6994** [wwmm/pulseeffects#78]
Hello, I just installed this program & it right off the bat makes my sound scratchy, I've not even configured it & its all scratchy.. Why??? Guess I have to find a different equalizer...

**Comment by AsavarTzeth** [comment]
Do you care to mention details, like how you installed it?

Currently this issue thread is completely useless. If you don't provide any useful information I recommend this be closed as invalid.

**Comment by karl6994** [comment]
I installed it from the Arch AUR, I don't really know what else I can tell you which is why I created this post.

**Comment by karl6994** [comment]
ooops I didn't mean to click that, sorry

**Comment by wwmm** [comment]
Follow the instructions in the wiki [https://github.com/wwmm/pulseeffects/wiki/Run-Directly-from-Repository](https://github.com/wwmm/pulseeffects/wiki/Run-Directly-from-Repository)

**Comment by AsavarTzeth** [comment]
Yes it is all mentioned in the wiki, which is mentioned in the `READMEmd`. If you like to use the AUR another tip is to check the `PKGBUILD` which often gives you a good idea on how it is built.

**Comment by karl6994** [comment]
Ohhh wow I feel dumb now, I didn't see that wiki thing at the bottom, my apologies! 
So I got it to launch, but its not in my menu list.. How can I make it install so I don't have to run it from the git repo? like, so I don't have to run "GSETTINGS_SCHEMA_DIR=data/ ./pulseeffects.in"
thanks for all of your help, this version doesn't make my sound scratchy like the Arch AUR's one does! 
Is there a way I can update pulseeffects in the AUR so that I can install it & get an icon for it? I'm a total noob, sorry.

**Comment by wwmm** [comment]
If you can try [https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source](https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source). But if you are not used to install programs without using distributions packages I would suggest you wait for an update to the aur package. I did all the major changes I had in mind for PulseEffects 3.0 so it won't take long for a new release. Probably a few days

**Comment by karl6994** [comment]
Yay! Thank you! I'm sorry I'm new to github & I don't always see these links, really sorry to have bothered you guys, this new version rocks!! This really helps me improve my stereo-server & all my other computers too! You guys are awesome thank you so much!!

**Comment by AsavarTzeth** [comment]
From the sound of it what @karl6994 wants is a `pulseeffects-git` package that installs the latest version from git. However this would only be useful for simplifying testing since it would in no way be guaranteed to work after every update.

I could probably provide a PKGBUILD for it, since the nice thing with *-git packages is that you rarely need to update them.

Although if there might be a release soon (one that I look forward to test), I would just wait for that.

If you are interested in learning about desktop entries I would start out [here](I could probably provide a PKGBUILD for it, since the nice thing with *-git packages is that you rarely need to update them.). You would have to change a lot in the [provided file](https://github.com/wwmm/pulseeffects/blob/master/data/com.github.wwmm.pulseeffects.desktop.in) for it to work with your current install though.

**Comment by karl6994** [comment]
So it works on my main PC, but on my stereo-server PC it gives me this:
Traceback (most recent call last):
   File "/usr/local/bin/pulseeffects", line 6, in <module>
      from PulseEffects.application import Application
ModuleNotFoundError: No module named 'PulseEffects'

**Comment by wwmm** [comment]
For some reason PulseEffects Python module was not installed. What commands did you use when installing?

**Comment by karl6994** [comment]
meson _build
cd _build
sudo ninja install

**Comment by AsavarTzeth** [comment]
Right, `/usr/local/lib/python*/site-packages` may not be in the PYTHONPATH. Might have to adjust the wiki a bit with that in consideration.

**Comment by karl6994** [comment]
I got it to install on my main PC but not on my stereo-server PC, which is kind of odd because they're both running Manjaro Linux 64-bit.. I'm gonna try it on my 32-bit netbook running Debian.

**Comment by AsavarTzeth** [comment]
I honestly don't think any distribution has that directory in the PYTHONPATH. Usually a distribution only uses `/usr/lib/python*/site-packages`for all python modules or it uses `/usr/lib/python*/dist-packages` for distributon provided modules (Debian does this) and the former for locally (manually) installed ones.

**Comment by wwmm** [comment]
It seems that this command should show if it is in the path or not `python -c "import sys; print(sys.path)"`. Here I have the output `['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/lib/python3.6/site-packages']`. `/usr/local/*` is not in the path.

**Comment by wwmm** [comment]
@karl6994 Do you have the aur package installed in the machine where the installation `sudo ninja install` worked? If yes it is using the module from the old version installed by the aur package.

**Comment by karl6994** [comment]
I had the AUR one installed on both machines, I uninstalled them both with pacaur then installed it from the github repo

**Comment by karl6994** [comment]
This is what I get when I input that command:
python -c "import sys; print(sys.path)"
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/lib/python3.6/site-packages']

**Comment by karl6994** [comment]
This is what I get when I try to build it in Debian(i686)
meson _build
The Meson build system
Version: 0.37.1
Source dir: /home/kzn/Compiles/pulseeffects
Build dir: /home/kzn/Compiles/pulseeffects/_build
Build type: native build

Meson encountered an error in file meson.build, line 1, column 0:
Not enough arguments to project(). Needs at least the project name and one language

**Comment by AsavarTzeth** [comment]
Meson is quite new. Debian has a much too old version.

On your Manjaro PC you could install with `--prefix=/usr` but then you could get conflicts with package owned files in the future.

Since you already have a meson build directory you would cd into that and run `meson -Dprefix=/usr` then `sudo ninja install` again. But like I said this will cause package ownership conflicts for you to resolve later. I really don't recommend it if you wish to keep your filesystem clean and for your level of experience.

I would prefer a way to append to the python path universally.

**Comment by AsavarTzeth** [comment]
Right now though. Could you please wait until I am fully available, I promise I will make you a PKGBUILD for the git version so you can simply install from the AUR as usual. It would literally take me a minute or two.

**Comment by karl6994** [comment]
Awesome, thank you AsavarTzeth! That'll make things much easier to get it working on my Arch-based PCs! I am however curious how I'm gonna get it to work on my Debian laptop, which version of Meson do I need?

**Comment by AsavarTzeth** [comment]
I am unsure which exact version. I will try to find out about that too. Then we can add it to the main meson.build so instead of failing like above it will tell you what version you need.

**Comment by karl6994** [comment]
I upgraded meson to the latest version in the Sid repo which is version 0.42.1, I'm just gathering some missing dependencies at the moment.

**Comment by karl6994** [comment]
meson _build
The Meson build system
Version: 0.42.1
Source dir: /home/kzn/Compiles/pulseeffects
Build dir: /home/kzn/Compiles/pulseeffects/_build
Build type: native build
Project name: PulseEffects
Build machine cpu family: x86
Build machine cpu: i686
Message: Checking dependencies
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency gtk+-3.0 found: YES 3.22.11
Native dependency pygobject-3.0 found: YES 3.22.0
Native dependency py3cairo found: YES 1.10.0
Native dependency pangocairo found: YES 1.40.5
Native dependency gstreamer-1.0 found: YES 1.12.2
Native dependency gstreamer-plugins-bad-1.0 found: YES 1.12.2
Message: Getting python install path
Message: Installing PulseEffects
Configuring pulseeffects using configuration
Message: Installing data files
Program meson_post_install.py found: YES (/usr/bin/env python3 /home/kzn/Compiles/pulseeffects/meson_post_install.py)
Build targets in project: 5
~Next command:
sudo ninja install
[2/3] Installing files.
Installing subdir /home/kzn/Compiles/pulseeffects/PulseEffects to /usr/local/lib/python3.5/site-packages
Installing subdir /home/kzn/Compiles/pulseeffects/PulseEffectsCalibration to /usr/local/lib/python3.5/site-packages
Installing data/com.github.wwmm.pulseeffects.appdata.xml to /usr/local/share/metainfo/com.github.wwmm.pulseeffects.appdata.xml
Installing data/com.github.wwmm.pulseeffects.desktop to /usr/local/share/applications/com.github.wwmm.pulseeffects.desktop
Installing /home/kzn/Compiles/pulseeffects/_build/pulseeffects to /usr/local/bin
Installing /home/kzn/Compiles/pulseeffects/data/com.github.wwmm.pulseeffects.gschema.xml to /usr/local/share/glib-2.0/schemas
Installing /home/kzn/Compiles/pulseeffects/data/com.github.wwmm.pulseeffects.sinkinputs.gschema.xml to /usr/local/share/glib-2.0/schemas
Installing /home/kzn/Compiles/pulseeffects/data/com.github.wwmm.pulseeffects.sourceoutputs.gschema.xml to /usr/local/share/glib-2.0/schemas
Installing /home/kzn/Compiles/pulseeffects/data/pulseeffects.svg to /usr/local/share/icons/hicolor/scalable/apps
Running custom install script '/usr/bin/python3 /usr/share/meson/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=PulseEffects'
Installing /home/kzn/Compiles/pulseeffects/_build/po/cs.gmo to /usr/local/share/locale/cs/LC_MESSAGES/PulseEffects.mo
Installing /home/kzn/Compiles/pulseeffects/_build/po/de.gmo to /usr/local/share/locale/de/LC_MESSAGES/PulseEffects.mo
Installing /home/kzn/Compiles/pulseeffects/_build/po/fr_FR.gmo to /usr/local/share/locale/fr_FR/LC_MESSAGES/PulseEffects.mo
Installing /home/kzn/Compiles/pulseeffects/_build/po/hr.gmo to /usr/local/share/locale/hr/LC_MESSAGES/PulseEffects.mo
Installing /home/kzn/Compiles/pulseeffects/_build/po/it_IT.gmo to /usr/local/share/locale/it_IT/LC_MESSAGES/PulseEffects.mo
Installing /home/kzn/Compiles/pulseeffects/_build/po/pt_BR.gmo to /usr/local/share/locale/pt_BR/LC_MESSAGES/PulseEffects.mo
Installing /home/kzn/Compiles/pulseeffects/_build/po/sk.gmo to /usr/local/share/locale/sk/LC_MESSAGES/PulseEffects.mo
Installing /home/kzn/Compiles/pulseeffects/_build/po/sv.gmo to /usr/local/share/locale/sv/LC_MESSAGES/PulseEffects.mo
Running custom install script '/usr/bin/env python3 /home/kzn/Compiles/pulseeffects/meson_post_install.py'
Compiling gsettings schemas...
Updating icon cache...
Updating desktop database...
and then it does this -.- :
pulseeffects
Traceback (most recent call last):
  File "/usr/local/bin/pulseeffects", line 6, in <module>
    from PulseEffects.application import Application
ImportError: No module named 'PulseEffects'

**Comment by karl6994** [comment]
and this is what happens when I try to run the pulseeffects.in thing































































































































  GNU nano 2.8.7                                                                         File: pulseeffects                                                                                   

sudo ./pulseeffects.in
DtsGetHWFeatures: Create File Failed
error: XDG_RUNTIME_DIR not set in the environment.
libva error: /usr/lib/i386-linux-gnu/dri/i965_drv_video.so init failed
libva error: /usr/lib/i386-linux-gnu/dri/i965_drv_video.so init failed
13:18:25.564 - PulseEffects - INFO - pulseaudio context started
13:18:25.566 - PulseEffects - INFO - connected to server: unix:/run/user/1000/pulse/native
13:18:25.568 - PulseEffects - INFO - server protocol version: 32
13:18:25.570 - PulseEffects - INFO - pulseaudio version: 10.0
13:18:25.571 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
13:18:25.573 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
13:18:25.586 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
13:18:25.587 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
13:18:25.591 - PulseEffects - INFO - default pulseaudio source audio format: s16le
13:18:25.592 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
13:18:25.593 - PulseEffects - INFO - loading Pulseeffects applications sink...
13:18:25.627 - PulseEffects - INFO - sink owner module index: 25
13:18:25.635 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
13:18:25.636 - PulseEffects - INFO - Pulseeffects apps sink index:1
13:18:25.636 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
13:18:25.637 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
13:18:25.646 - PulseEffects - INFO - sink owner module index: 26
13:18:25.651 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
13:18:25.652 - PulseEffects - INFO - Pulseeffects mic sink index:2
13:18:25.652 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
Traceback (most recent call last):
  File "/home/kzn/Compiles/pulseeffects/PulseEffects/application.py", line 81, in do_startup
    self.sie = SinkInputEffects(self.pm.default_sink_rate)
  File "/home/kzn/Compiles/pulseeffects/PulseEffects/sink_input_effects.py", line 19, in __init__
    EffectsBase.__init__(self, sampling_rate, self.settings)
  File "/home/kzn/Compiles/pulseeffects/PulseEffects/effects_base.py", line 52, in __init__
    self.limiter = Limiter(self.settings)
  File "/home/kzn/Compiles/pulseeffects/PulseEffects/limiter.py", line 26, in __init__
    self.build_bin()
  File "/home/kzn/Compiles/pulseeffects/PulseEffects/limiter.py", line 40, in build_bin
    self.bin.append(self.limiter, self.on_filter_added, None)
TypeError: Argument 1 does not allow None as a value

Traceback (most recent call last):
  File "/home/kzn/Compiles/pulseeffects/PulseEffects/application.py", line 135, in do_shutdown
    self.sie.set_state('null')
AttributeError: 'Application' object has no attribute 'sie

**Comment by AsavarTzeth** [comment]
Please use a pastebin service and edit your messages.

By the way I tested different versions of meson and it appears 0.40.0 is the earliest that works.

**Comment by karl6994** [comment]
I tried using --prefix=/usr but it still gives me the same issue :/ and sometimes I try to use sudo when things aren't working without sudo. I'm not a huge fan of appimages/flatpak, would be nice to be able to install it to the system... and I've never used pastebin before, I have no real experience with it :| ...
It installed on debian but it still gives me the same stupid error as the other one...

**Comment by karl6994** [comment]
When I open up the pulseeffects.in on debian it opens up the equalizer window but theres nothing in the window except at the bottom of the window it shows:
20 Hz  47 Hz  112 Hz   630 Hz  3.5Hz  8.4 kHz  20 kHz

**Comment by AsavarTzeth** [comment]
Trying sudo without understanding it is the defintion of danger on Linux/Unix systems...

I don't feel I can help you the way expect at the moment. Just wait. I am working on it as planned but I can't do that and comment here constantly too.

As for not being a fan of flatpak; given your recent experience with trying to build on different systems you should have an understanding for why they are important...

**Comment by karl6994** [comment]
I can't even make it uninstall on Debian.. I try to do ninja uninstall but it still gives me the same error when I type pulseeffects into the terminal..

**Comment by karl6994** [comment]
Trying "sudo" before running a program is the definition of danger??? Lol ok dude, whatever you say. 
I'll just find a better equalizer then that will actually install without problems if you're gonna be a douche about it, no problem man. This equalizer isn't very good anyways.

**Comment by karl6994** [comment]
And nobody says you have to reply right away either, I was just trying to help you fix your garbage equalizer that won't even install on most Linux distros. Have a nice life, asshole.

**Comment by AsavarTzeth** [comment]
What? You get mad at me even though I keep trying to help you? You seriously don't understand the danger of running things as root without understanding it?

Look if I offended you, I am sorry but you keep commenting and I am getting tired. I do have Aspergers so my communication skills are not the best, but I try.

**Comment by karl6994** [comment]
I don't care if you're autistic, fuck off.

**Comment by AsavarTzeth** [comment]
Seriously grow up.

**Comment by karl6994** [comment]
You first you fucking goof

**Comment by karl6994** [comment]
Your equalizer is garbage anyways.

**Comment by AsavarTzeth** [comment]
@wwmm You may delete all comment on this issue or remove it alltogether...

**Comment by karl6994** [comment]
Thanks for wasting my time, loser. You think you can guilt-trip me because you have asbergers? Who even says shit like that? You're pathetic

**Comment by AsavarTzeth** [comment]
I was trying to help... If you understood what Aspbergers is you would understand that communicating with others and seeing their point of view is difficult to me. Given that fact one could see how I sometimes could appear rude (to some people). It really is not my intention, so I apologized just in case.

I feel you were the one who crossed the line.
