### ISSUE TITLE
Broken svg icon

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#782]
PulseEffects [icon](https://github.com/wwmm/pulseeffects/blob/c931e63c18b840fd4afd9b493eed3f5e2a86ddd1/data/pulseeffects.svg) was updated, but I noticed that it's broken. The central vertical bar is corrupted at the top.

Can we consider to revert back to the previous or replace it with this [one](https://github.com/bikass/korla/blob/37b51680543348a8fefae307aa25d5175f5a954e/korla/apps/scalable/pulseeffects.svg)? I think the second is better, don't know the Gnome Human Interface guidelines, but I think it should be good.

**Comment by wwmm** [comment]
Corrupted?

**Comment by wwmm** [comment]
Oh now I see. You have to increase the image size to see that.

**Comment by wwmm** [comment]
![Screenshot from 2020-09-11 17-25-48](https://user-images.githubusercontent.com/16225172/92969750-eb938d00-f453-11ea-8eab-b40eb5d55a3a.png)

@DefunctLizard could you see why this is happening?

**Comment by Digitalone1** [comment]
It could be fixed by the author, but can the white border be removed?

And since the icon is used to be displayed on small bars also, can the 3 rounded control be enlarged? On Gnome status bar they are barely visible.

**Comment by wwmm** [comment]
>don't know the Gnome Human Interface guidelines

Although I have read the Gnome guidelines I never read the section about the icons. Hopefully @DefunctLizard can explain what they recommend.

**Comment by wwmm** [comment]
>And since the icon is used to be displayed on small bars also, can the 3 rounded control be enlarged? On Gnome status bar they are barely visible.

I think only the colors were changed in the last update. So the size should be the same as before. I do not have a reason to keep the current icon as it is. Another concepts can be explored.

**Comment by Digitalone1** [comment]
If you see the rich diff [here](https://github.com/wwmm/pulseeffects/commit/c931e63c18b840fd4afd9b493eed3f5e2a86ddd1?short_path=5fc00b3#diff-5fc00b3bd08f549d2f3e151796535ba5), the bars and the controls were enlarged.

The concept is good, but I prefer the size of the korla theme without the white border (maybe adding the shadow also there).

 If @DefunctLizard can fix it and enlarge the controls a bit, would be very appreciated.

**Comment by DefunctLizard** [comment]
I'll check it out, probably an error in the path. I'll take a look at it and get back to you

**Comment by DefunctLizard** [comment]
![pulseeffects](https://user-images.githubusercontent.com/45475651/92984814-5d76d100-f46a-11ea-8442-21859079f772.png)

**Comment by DefunctLizard** [comment]
Does this seem better?
![pulseeffects](https://user-images.githubusercontent.com/45475651/92984831-872ff800-f46a-11ea-975b-d2c907f4341f.png)

**Comment by Digitalone1** [comment]
Yes, this version fixes the path.

**Comment by Digitalone1** [comment]
@wwmm korla has updated it with the shadow. I think it's better. 

https://github.com/bikass/korla/blob/18c28441cccaf1458bbb6e439d77f0b53a0cd245/korla/apps/scalable/pulseeffects.svg

Anyway, it's up to you to decide what to choose.

**Comment by wwmm** [comment]
>korla has updated it with the shadow. I think it's better.

It is good indeed. But do we have the author permission to use it in PulseEffects sources?

**Comment by Digitalone1** [comment]
> > korla has updated it with the shadow. I think it's better.
> 
> It is good indeed. But do we have the author's permission to use it in PulseEffects sources?

No worries, it's released under the same license of PulseEffects.

https://github.com/bikass/korla/blob/master/LICENSE

**Comment by wwmm** [comment]
Then we can use korla's icon. And as it belongs from an icon theme used in different kind of systems hopefully it fixes #331. 

Thank you for your work @DefunctLizard. I probably wouldn't have started the icon change without it :-)

**Comment by wwmm** [comment]
Actually #331 can already be closed. The only remaining issue is from another user in other desktop.
