### ISSUE TITLE
Show active presset for output in output section, and input in input section separated.

### ISSUE THREAD

**Issue by Mlocik97** [wwmm/pulseeffects#783]
Now, let's say, I have active in output preset Music. And in input preset ntb_mic.

When I have clicked output, I can't see active output presset, but I see input presset instead.

![Snímka obrazovky z 2020-09-13 20-43-35](https://user-images.githubusercontent.com/34808350/93025874-f8ee7a00-f601-11ea-847a-52bb5aae1694.png)

**Comment by wwmm** [comment]
Code in master branch updated. It now synchronizes the preset menu button label with the section being used by the user. But there is still something that is not right. As the preset menu shows both input and output plugins if the users clicks in a input preset while seeing output effects widgets the button label will show the input preset that was loaded and not the last used output preset. Once the user changes between the input and output widgets view the synchronization kicks in the the button label is updated.

The only way I see to remove this last inconsistency would be to not showing both input and output presets in the menu. But I like being able to change input presets without having to actually going to the input plugins section. So it does not seem the right thing to do.

**Comment by Mlocik97** [comment]
or we can display both active presset on button, with pipe for splitting and with icons for output and input.

**Comment by Digitalone1** [comment]
It's not a real inconsistency, because if users are used to see the latest chosen preset after clicking "load" button, then they may complain that it's not updated properly when the chosen preset is not shown on the label.

Showing both input and output presets on the label is not a good idea. The headerbar is already filled with lots of buttons and information. 

I think it's good as it is now.

**Comment by Digitalone1** [comment]
@wwmm you left the last used preset key on autoload and the application crashes on setting an undefined key:

```
(pulseeffects:12825): GLib-GIO-ERROR **: 12:04:25.351: Settings schema 'com.github.wwmm.pulseeffects' does not contain a key named 'last-used-preset'
Rilevato trace/breakpoint (core dump creato)
```

I'll make a pr to fix.

**Comment by Mlocik97** [comment]
I don't know, but when I have presets named "Voice" in both input and output, but also presset "music" in output, and when I have active Music in output but I see Voice presset as active, it can confuse much more...

**Comment by wwmm** [comment]
Even on big monitors showing both presets in the button label might be bad because some people choose big names for their presets. For now let's stay with the synchronization.

**Comment by Mlocik97** [comment]
![Snímka obrazovky z 2020-09-15 19-43-01](https://user-images.githubusercontent.com/34808350/93245535-c2dd0180-f78b-11ea-9f73-7fa68ece26fa.png)

like this?
