### ISSUE TITLE
PulseEffects 4.8.1

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#786]
I think PulseEffects 4.8.1 should be released before Ubuntu 20.10 will come out.

The situation of PulseEffects on Ubuntu is disappointing as it seems only the old 4.7.2 version is available for 20.04. Since they didn't upgraded it, I suppose the only way to get the new updates is only with 20.10.

4.8.0 was a big release and it would be enough, but the latest improvements to the code and the graphical interface deserve to be available to a distribution with a very large community.

**Comment by wwmm** [comment]
No problems. I can do that today.

**Comment by Digitalone1** [comment]
@wwmm I saw it's released October 22. Maybe you can wait.

**Comment by Digitalone1** [comment]
Maybe a couple of weeks before. It's up to you.

**Comment by wwmm** [comment]
Released.
