### ISSUE TITLE
Any deb or ppa in the future for debian based linuxes?

### ISSUE THREAD

**Issue by gaining** [wwmm/pulseeffects#79]

**Comment by wwmm** [comment]
Unfortunately I do not have time to support packages for distributions other than Arch Linux. Any reason for not using the flatpack package?

**Comment by gaining** [comment]
I'm not familiar with flatpack so that's why I asked. Can you provide tar.gz's with install instructions?

**Comment by wwmm** [comment]
Hi, follow one of the instructions in the [wiki](https://github.com/wwmm/pulseeffects/wiki)

**Comment by gaining** [comment]
ok thanks
