### ISSUE TITLE
Apply APO preset doesn't change filter mode.

### ISSUE THREAD

**Issue by grpan** [wwmm/pulseeffects#791]
Equalizer APO filter import was added recently. According to [this comment](https://github.com/wwmm/pulseeffects/issues/515#issuecomment-496031512) "APO (DR)" should be the right setting. But pulseeffects applies the default "RLC (BT)" when importing the filter file.

**Comment by wwmm** [comment]
Thanks for noticing this! Dealing with APO format was so painful that we forgot about this setting. I will fix it.

**Comment by wwmm** [comment]
Fixed in PE `4.8.2`.
