### ISSUE TITLE
Pulseeffects has no audio output when run

### ISSUE THREAD

**Issue by marvic2409** [wwmm/pulseeffects#797]
Before running pulseeffects I hear audio just fine through my headphones, but when I run pulseeffects, i stop getting any audio. I have restarted pulseaudio and pulseeffects and nothing is working. I am running ubuntu 20.04 and pulseeffects 4.8.2

**Comment by polygonalenippel** [comment]
Open your mixing panel (usually "Volume Control" or `pavucontrol`) and make sure PulseEffects and your sound card aren't muted. Furthermore, make sure PulseEffects is pointing to the correct sound card (and not to itself).

**Comment by polygonalenippel** [comment]
Needless to say your audio source program should be pointing to PulseEffects as well

**Comment by wwmm** [comment]
@marvic2409 kill the current pulseeffects instance with the command `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Then try to play something and show here the lines printed in the terminal. This way we will know if any error is happening.

**Comment by marvic2409** [comment]
@polygonalenippel's advice was the solution
