### ISSUE TITLE
No response or eq visualisation from microphone

### ISSUE THREAD

**Issue by jakob1379** [wwmm/pulseeffects#806]
I really want this to work as the features are quite compelling. Some relevant info:
 - Manjaro 20.1.2
 - PulseAudio V13.0
 - Pulseeffects V4.8.2

I haven't been able to figure out what the `maximizer module" is, hence it is not installed. But is this really enough to not make the microphone modules work?

**Comment by wwmm** [comment]
IS there an application recording audio? You will see activity in the spectrum window only if something is trying to record audio and you enable effects for it in PulseEffects window.

**Comment by andersfylling** [comment]
I'm doing something similar for Discord. But I have no idea how to pipe my mic through pulseeffects and then into Discord.

**Comment by jakob1379** [comment]
> 
> 
> IS there an application recording audio? You will see activity in the spectrum window only if something is trying to record audio and you enable effects for it in PulseEffects window.

Wow.. How did I not notice this. I will try it out and report as soon as I wake up! ETA 9 hours

**Comment by jakob1379** [comment]
You were right. After loading up audacity I would see it in there. Now I just have to configure defaults properly.
