### ISSUE TITLE
Unable to autostart when installed as flatpak

### ISSUE THREAD

**Issue by nilanshu96** [wwmm/pulseeffects#811]
The command 'pulseeffects' doesn't works when installed as flatpak. Due to which the autostart fails as well. To circumvent this issue I created a symlink of the pulseeffect bin file to the /usr/local/bin using the following command.

`sudo ln -s ~/.local/share/flatpak/app/com.github.wwmm.pulseeffects/current/active/export/bin/com.github.wwmm.pulseeffects /usr/local/bin/pulseeffects`

This has fixed the issue but is there any way that this can be performed during the installation process?

**Comment by wwmm** [comment]
I don  know if that is the recommended way to solve this issue. It is better to ask to the flatpak package maintainers in this link https://github.com/flathub/com.github.wwmm.pulseeffects/issues.

**Comment by nilanshu96** [comment]
> I don't know if that is the recommended way to solve this issue. It is better to ask to the flatpak package maintainers in this link https://github.com/flathub/com.github.wwmm.pulseeffects/issues.

Sorry. I wasn't aware that the flatpak manager was different. I see that the issue is already open there. I shall close it here then.
