### ISSUE TITLE
Pulseeffects doesn't start

### ISSUE THREAD

**Issue by qqawsedr8** [wwmm/pulseeffects#812]
** (pulseeffects:345371): ERROR **: 17:11:04.741: 
unhandled exception (type std::exception) in signal handler:
what: sie: Failed to get required plugin: pulsesrc

Trace/breakpoint trap (core dumped)

**Comment by wwmm** [comment]
Which distribution are you using? How did you install PulseEffects?

`pulsesrc` is a required plugin provided by the library `gst-plugins-good`.

**Comment by qqawsedr8** [comment]
Im using Arch linux and if i remember correctly pulse was already installed

**Comment by wwmm** [comment]
I am also n Arch Linux. If `pulsesrc` could not be found something is broken in your GStreamer installation. Try to reinstall the package `gst-plugins-good` to see if it helps.

**Comment by qqawsedr8** [comment]
Same thing

**Comment by qqawsedr8** [comment]
Heres what i found. Downgrading gst-plugins-good to version 1.16.2 makes it work but it receives no input or output

**Comment by qqawsedr8** [comment]
Here's the terminal output
[log.txt](https://github.com/wwmm/pulseeffects/files/5483825/log.txt)

**Comment by wwmm** [comment]
kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. This will give better logs. But based on the errors above I can say there is still something broken in your GStreamer installation. Maybe you have mixed library versions in one of its packages.

**Comment by qqawsedr8** [comment]
[log3.txt](https://github.com/wwmm/pulseeffects/files/5483923/log3.txt)

**Comment by qqawsedr8** [comment]
I just reinstalled arch and everything seems to work. Dont know what the issue was before
