### ISSUE TITLE
[BUG] PE trying to load deleted presets and then crushes without any message

### ISSUE THREAD

**Issue by jebbyk** [wwmm/pulseeffects#817]
I've created some presets before as experiment. Then deleted them and created some new ones. 
Starting PE - ok
Starting some apps - ok
Any of my apps make a sound - I can hear a sound about 1-3 seconds then PE crushes _without any message_ 
I can't pipeline a sound to another output so no sound at all (ubuntu 20.04 settings)
sudo apt purge pulseeffects && sudo apt install pulseeffects doesnt helps

```
pulseeffects:9416): pulseeffects-DEBUG: 18:40:37.828: sie: pulsesink buffer [us]: 200000
(pulseeffects:9416): pulseeffects-DEBUG: 18:40:37.828: sie: total latency: 140 ms
(pulseeffects:9416): pulseeffects-DEBUG: 18:40:37.828: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:9416): pulseeffects-DEBUG: 18:40:37.828: sie: total latency: 140 ms
(pulseeffects:9416): pulseeffects-DEBUG: 18:40:41.162: presets_manager: autoloading preset zs10 8 lines x1.0 for device alsa_output.pci-0000_00_14.2.analog-stereo:analog-output-lineout

(pulseeffects:9416): glibmm-ERROR **: 18:40:41.162: 
unhandled exception (type std::exception) in signal handler:
what: /home/jebbyk/.config/PulseEffects/output/zs10 8 lines x1.0.json: cannot open file

Trace/breakpoint trap (core dumped)
jebbyk@jebbyk-pc-linux:~/Downloads$ ls -la ~/.config/PulseEffects/output/
total 104
drwxrwxr-x 2 jebbyk jebbyk  4096 ноя 11 01:12  .
drwxrwxr-x 6 jebbyk jebbyk  4096 ноя 10 19:41  ..
-rw-rw-r-- 1 jebbyk jebbyk 29768 ноя 11 01:06 'zs10 24 lines x1.0.json'
-rw-rw-r-- 1 jebbyk jebbyk 29844 ноя 11 01:09 'zs10 24 lines x2.0.json'
-rw-rw-r-- 1 jebbyk jebbyk 29816 ноя 11 01:12 'zs 10 24 lines x4.0.json'
jebbyk@jebbyk-pc-linux:~/Downloads$ 

```

**Comment by jebbyk** [comment]
deleting a file from ~/.config/PulseEffects/autoload solves the problem

**Comment by wwmm** [comment]
Which PulseEffects version did you install? This preset autoload bug was supposed to be fixed a few months ago.

**Comment by jebbyk** [comment]
4.7.1

**Comment by wwmm** [comment]
At this moment we are on `4.8.2`. I am not sure at which version this bug was fixed. But it is possible that `4.7.1` still have it.

**Comment by jebbyk** [comment]
ok then how to install the latest version of PE? `sudo apt install pulseeffects` installs exactly this version. And also this version is presented in Ubuntu Software app

**Comment by jebbyk** [comment]
Im using Ubuntu 20.04 TLS

**Comment by wwmm** [comment]
>how to install the latest version of PE

As I do not use Ubuntu I don't know where you can find updated packages for it. I think that @mikhailnov PPA does not support Ubuntu 20.04 anymore.  So using a flatpak package https://flathub.org/apps/details/com.github.wwmm.pulseeffects might be your only option.

**Comment by jebbyk** [comment]
thank you :+1:

**Comment by mikhailnov** [comment]
@wwmm I do support Ubuntu 20.04, see https://launchpad.net/~mikhailnov/+archive/ubuntu/pulseeffects/+packages
Ubuntu 18.04 is not supported any more after last bump of required gtkmm.

Official Ubuntu repo ship version 4.7.1 https://packages.ubuntu.com/search?keywords=pulseeffects
It is supported in DEbian and imported to Ubuntu without changes, not I support it in DEbian, but packaging was based on mine and packages are compatible.

**Comment by wwmm** [comment]
Ok. I misunderstood the message in the commit https://github.com/wwmm/pulseeffects/commit/82021a2cdb2989770c64b4c5c3c7bfdeff13593e.
