### ISSUE TITLE
Reference Signal in Loudness Compenstation Plugin is useless, Input value is not saved to preset

### ISSUE THREAD

**Issue by Mlocik97** [wwmm/pulseeffects#819]
I think, we can remove that reference signal thing, not only PE has already testing signals feature with much more settings, but also, reference signal from Loudness Plugin doesn't work, if there is nothing in input (no App is giving audio to PE).

Input value is not saved to preset.

Limiter docs are not updated (doesn't contain autoleveling feature, but still has things from older version (4.7.x)

**Comment by wwmm** [comment]
One workaround to use the reference signal would be to use our "silence test signal" to force the stream to play. But it sounds like an overkill. I think that it can be removed from the interface.

**Comment by Mlocik97** [comment]
About that limiter, I would like to bring back that "input gain" to it. It helped me with things like I mentoyed in https://github.com/wwmm/pulseeffects/issues/777

even when there were changes in auto-leveling. Now I swapped Limiter and Maximizer to get similiar result, but still it's not what I was able in 4.7.x version. I think that, input gain is not problem to implement and it would help with auto-leveling really much.

**Comment by Digitalone1** [comment]
> About that limiter, I would like to bring back that "input gain" to it. It helped me with things like I mentoyed in #777
> 
> even when there were changes in auto-leveling. Now I swapped Limiter and Maximizer to get similiar result, but still it's not what I was able in 4.7.x version. I think that, input gain is not problem to implement and it would help with auto-leveling really much.

The input gain is still present in the Limiter. The only difference in the new version is that it was moved into the input slider at the bottom of the interface.

**Comment by Mlocik97** [comment]
Oh, I was little confused because with auto-leveling enabled, I needed to set both input and output to -3dB, to reduce volume just by 3dB (while I was supposing, it will reduce by 6dB).

**Comment by Digitalone1** [comment]
Regarding the documentation, I used to update it in the past, but it's very boring.

> Input value is not saved to preset.

You're right. I missed that issue. I'll try to fix it in a next pull request. Maybe I'll remove also test signal button.
