### ISSUE TITLE
[BUG] "Add to Blocklist" add all streams of app to Blocklist, not only one I want to blocklist.

### ISSUE THREAD

**Issue by Mlocik97** [wwmm/pulseeffects#822]
Remember my issue https://github.com/wwmm/pulseeffects/issues/760 ? So OBS has two streams, that are the same name... I wanted to add OBS (Desktop Sound) In Microphone Settings to Blocklist, but it automatically added to Blocklist also OBS (Mic/Aux), that is different stream for same app.

![Snímka obrazovky z 2020-11-12 20-28-09](https://user-images.githubusercontent.com/34808350/98986771-a0662b00-2525-11eb-83af-fc95275678a8.png)

**Comment by Digitalone1** [comment]
The blocklist is made on the application name and the two entries above have the same name.

**Comment by wwmm** [comment]
This is issue may be hard to solve in a generic way. Blocklisting the application name is by far the easier and most reliable thing to do. Applications are not required to set the others like description, media name, etc. So a blocklist based on them will fail for many apps.

**Comment by Mlocik97** [comment]
Is there no way, How to implement description / media name in way, it will save as empty string, or NULL and then if it's one of there situations, only then use blocklisting based on app name for only these apps, and for other apps, that have description / media name, use these properties too?

**Comment by Digitalone1** [comment]
It could be done appending media description to application name string, but it's still unreliable because if I want to blocklist celluloid player, I have to do it every time I play a song because media description is written containing the song title.

Then we have to rely on regular expression to cover all the cases, so it's too difficult to implement. To me it's no, considering that this feature is also rarely used by PulseEffects users.

**Comment by wwmm** [comment]
>I have to do it every time I play a song because media description is written containing the song title

MPV also writes the file name to the description. So combining the app name and the description would fail with it too.

Tags are not the way to fix this. I will think about something else.

**Comment by wwmm** [comment]
Looking at the code it feels like this should be working even with the same app name. Each pipeline has its own blocklist and signals.

**Comment by wwmm** [comment]
Forget the last comment. For some reason I assumed that the streams in the image were in different pipelines

**Comment by wwmm** [comment]
A blocklist would work in this case if one of the OBS streams were in our `output effects` pipeline and the other in the `microphone effects` pipeline. With both streams in the same pipeline solving this with blocklist will be a nightmare. The only difference between these OBS streams is the `media.name`. Only with it we can not solve this without adding rules targeted exclusively to OBS. What is pretty bad...

It is probably not what you want but in this case it is better to use the switch besides the app name and disable effects for it manually.

**Comment by wwmm** [comment]
If an app does not set the media name Pulseaudio adds a generic name to it. If it is a playback stream it writes `Playback Stream` and it is a record stream is writes `Record Stream`. But if the app sets this field it could be anything. OBS does what is in the image above. While mpv, lollypop and spotify do something totally different.

**Comment by Mlocik97** [comment]
Digitalone1 Ouch, then that is really big problem. I will propably contact OBS devs, and instead propose to use different app name for each stream of OBS app.

But I'm not happy with situation, because there are a lot of different apps, that do this, and a lot of different apps, that do that changing of media description per song (like in Music players). So this is really problematic.

Well, I don't know, what would be best solution. Propably having ability to blocklist both based on app name only and on app name, media name, and description properties together. But it will be a lot of code that are not worth it, and it would add another problems.

**Comment by Mlocik97** [comment]
I got one more idea about solving this problem, that would propably be not good at all, but it would fix at least OBS vs Music players things... if we detect at time of adding app to blocklist, that there are registered more than one entries, add it together with other properties, else add only app name as it's now.

Well this is propably bad idea, but I don't get any other idea, than only propose OBS team to rename app name property in audio stream.

**Comment by wwmm** [comment]
>propose to use different app name for each stream

I don't think that this is possible. The application name is a global application option https://github.com/wwmm/pulseeffects/blob/545dad9ddc479d8e66b01a59ec5f7c8f61c272c0/src/application.cpp#L31. All the streams created after that call will have the name that was set. They probably won't want to do that.

**Comment by wwmm** [comment]
> having ability to blocklist both based on app name only and on app name, media name, and description properties together

It won't work. In the end we will have one `if/else` for each app... And once the author decides to put something else in these tags all these workarounds will be useless. Of all the tags the `app name` is the one with the smallest probability of being changed by audio applications authors.

**Comment by wwmm** [comment]
>Well this is propably bad idea

It is XD. For example the user could have opened more than one mpv window. We would have more than one entry from the same app that can or not have different media.name

**Comment by wwmm** [comment]
I am afraid that using the manual switch is the only "decent" solution to this case. Specially because the amount of applications that would benefit from all the added code complexity is really small. Maybe only OBS.

**Comment by Mlocik97** [comment]
Yeah, I really don't know what else can be done to fix this problem.
It's shitty that, media doesn't has something like id by default.

I really have no idea what else we can do.

**Comment by wwmm** [comment]
>It's shitty that, media doesn't has something like id by default.

I agree. Pulseaudio offers an id field that can be set to something unique in each stream. We so that in PulseEffects. Ou microphone pipeline has this:
```
application.id = "com.github.wwmm.pulseeffects.sourceoutputs"
```
while our "output effects" pipeline has:
```
application.id = "com.github.wwmm.pulseeffects.sinkinputs"
```

If all audio applications set this `id` in their streams we could have a much better way to implement a blocklist. But most apps do not care about this `id` because they are not required to use it.
