### ISSUE TITLE
No sound using Pulseeffects on Elementary OS Hera

### ISSUE THREAD

**Issue by CCaroV** [wwmm/pulseeffects#825]
From today I realized no sound was coming out my speakers while using pulseeffects. Sometimes it doesn't work when I log in, `pulseeffects -q` in the terminal, and opening it again solves it. Since this time this didn't work, I tried `pulseeffects -r`, log out and log back in, but nothing happened. Everything seems to be perfect on Pulseaudio Volume Control (I'm attaching a ss) and Pulseeffects seems to recognize what apps are been used, the format, rate, etc... (ss below), but the spectrum, Limiter, etc...  are not working.

I don't remember changing anything, I barely open pulseeffects since I already have some presets. I don't want to mess up anything so I am asking for some help here.

Many thanks in advance!

![Screenshot from 2020-11-13 17 50 39](https://user-images.githubusercontent.com/51457651/99128448-cdbfe100-25d8-11eb-81b0-f5adb1e242e0.png)

![Screenshot from 2020-11-13 17 51 38](https://user-images.githubusercontent.com/51457651/99128485-eb8d4600-25d8-11eb-9ef7-63dd412f6356.png)

![Screenshot from 2020-11-13 17 51 45](https://user-images.githubusercontent.com/51457651/99128492-ef20cd00-25d8-11eb-96f5-336711137593.png)

**Comment by wwmm** [comment]
Sometimes third party softwares decide to mute our virtual devices. Take a look at Pavucontrol `Ouput Devices' tab and see if that is the case. An overkill method in this situation would be to remove `~/.config/pulse` and restart. But with luck it won't be necessary.

If muted devices are not the problem we will need to see some logs. Kill the current PulseEffects instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`.

**Comment by CCaroV** [comment]
I had to remove the `~/.config/pulse` folder. I rebooted my pc and now Pulseeffects is working as usual.

Thank you!
