### ISSUE TITLE
Delay after pipeline resuming

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [wwmm/pulseeffects#826]
After 5 second timeout, when pipeline is paused, if some application tries to play audio pipeline is unpaused immediately, but actual audio output begins 1-2 seconds after this. Application doesn't wait for playback during this period, meaning that these 1-2 seconds of playback are actually lost, as if they were played to some null device. Spectrum bar in PE also doesn't react during delay. 

Sometimes after pipeline is resumed after some time (tens of minutes, maybe even less) - audio doesn't play at all even though log output is the same as usual (spectrum bar is empty / application keeps playing somewhere, all same as in case above). If that happens, the only way to fix this is to restart PE

I tried these buffer settings:

```
input ms (buf, lat) / output ms / block
200, 10 / 200, 10 / 512
200,  3 / 200,  3 / 512
 50, 10 /  50, 10 / 256
 50, 10 /  50, 10 / 512
 40, 10 /  20, 10 / 1024
```
There doesn't seem to be any noticeable difference between any of these.   
I also tried setting process priority to RT with no effect too.  
Any thoughts on what may cause this?

I'm on PE 4.8.2

EDIT: log tells me that `pulseaudio block size 441 frames` so I tried to set lesser block size (256), but no luck

**Comment by wwmm** [comment]
Kill the current instance `pulseefects -q` and restar it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. This way we will know if there is something strange happening.

Some amount of data loss is unavoidable because there isn't a way to tell the audio application it should wait for our pipeline to be ready. And it takes some time for the GStreamer pipeline to come back to the playing state. What should not be happening is being forced to restart PE. This is strange.

**Comment by AbsurdlySuspicious** [comment]
> restart it in debug mode 

Already did, I think there was no other way for me to know when pipeline is paused/unpaused :)

```
sie: spectrum enabled
soe: spectrum enabled
sie: total latency: 0 ms
soe: total latency: 0 ms
sie: using output device: jack_out
pulse_settings_ui: output device changed: jack_out
pulse_settings_ui: added sink: jack_out
pulse_settings_ui: added source: jack_out.monitor
soe: using input device: jack_in
pulse_settings_ui: input device changed: jack_in
pulse_settings_ui: added source: jack_in
sie: rtkit: changed GstQueue:queue0 thread nice value to -10
sie: rtkit: changed GstPulseSrc:source thread nice value to -10
sie: NULL -> READY -> PLAYING
sie: READY -> PAUSED -> PLAYING
sie: rtkit: changed GstPulseSrc:source thread nice value to -10
sie: sampling rate: 44100 Hz
sie: pulsesrc latency [us]: 10000
sie: pulsesrc buffer [us]: 40000
sie: total latency: 0 ms
sie: pulsesink latency [us]: 10000
sie: pulsesink buffer [us]: 20000
sie: total latency: 0 ms
peadapter: pulseaudio block size 441 frames
peadapter: we will read in chunks of 1024 frames
sie: total latency: 103 ms
sie: total latency: 103 ms
sie: PAUSED -> PLAYING -> VOID_PENDING
sie: total latency: 103 ms
sie: No app wants to play audio. We will pause our pipeline.
sie: PLAYING -> PAUSED -> VOID_PENDING
sie: total latency: 103 ms
sie: PAUSED -> PLAYING -> VOID_PENDING
sie: total latency: 103 ms
sie: No app wants to play audio. We will pause our pipeline.
sie: PLAYING -> PAUSED -> VOID_PENDING
```

> jack_out

I also tried to use pulseaudio directly with alsa device, of course, but it doesn't seem to affect anyting

> being forced to restart PE

In this case everything looks like that initial delay hanged forever. Logs are exactly same as above when it happens

**Comment by AbsurdlySuspicious** [comment]
On a side note, if some loss is unavoidable, maybe it's worth to make an option to change the pipeline pause timeout? It's really hard to deal with 5s timeout when you have to, for example, pause video regularly to catch some frames/subtitles

**Comment by wwmm** [comment]
>In this case everything looks like that initial delay hanged forever.

One possible explanation would be the Pulseaudio server being killed. usually you won't notice when Pulseaudio dies because it is able to restart itself. The problem is the PulseEffects is not able to restart itself when Pulseaudio comes back online. There quite a few initializations that are done only when PulseEffects is started. I have thought about how to do the auto resstart that Pavucontrol does but it is hard...

Try ot take a look at the `journalctl` output. It should show if Pulseaudio is dying

**Comment by wwmm** [comment]
>if some loss is unavoidable, maybe it's worth to make an option to change the pipeline pause timeout?

This could be done. I will try to remember to do that before the next release.

**Comment by wwmm** [comment]
>It should show if Pulseaudio is dying

It seems that finding this information is not as easy as I thought. I am looking at my logs and so far I could not see entries related to the Pulseaudio deaths I had in the last weeks...

**Comment by wwmm** [comment]
But what you describe in your second issue could definitely be caused by Pulseaudio dying. Since the last Pulseaudio updated on Arch Linux this has happened to me a few times. And the result is just like the one you described.

**Comment by AbsurdlySuspicious** [comment]
I will try to reproduce it with pulse started manually without `--daemonize` then. I had pavucontrol visible while testing it and I think I'd have noticed the restart, but can't be sure

**Comment by AbsurdlySuspicious** [comment]
Thanks for implementing changeable timeout! If I will ever encounter that other issue I mentioned I'll open separate issue, so I think this one can be closed
