### ISSUE TITLE
Pulseeffects don't close in Linux Mint 19.3 and 20

### ISSUE THREAD

**Issue by amquei** [wwmm/pulseeffects#835]
On Linux Mint Cinnamon 19.3 and 20, Pulseeffects continues to work in background even after we click the close button. This does not happen if Pulseeffects has been started via the terminal. Fix this, please.

**Comment by wwmm** [comment]
This is not a bug. It is a feature that is desired by almost all PulseEffects users. Keeping the window opened when you have already done all your configuration will only waste cpu power and keep one more window in the way.

**Comment by wwmm** [comment]
Our desktop file has the line `Exec=pulseeffects --gapplication-service`. If you do not want PulseEffects to keep running in the background after closing the window you will have to edit this file and remove the `--gapplication-service` option.

**Comment by amquei** [comment]
Ok, but where is this file?

**Comment by wwmm** [comment]
The procedure is a little more elaborated than I remembered. If you enable `Start Service at Login` you will have to edit the file `~/.config/autostart/pulseeffects-service.desktop`. The other file is `/usr/share/applications/com.github.wwmm.pulseeffects.desktop`. But in this one what you will have to do is setting `DBusActivatable` to false. Removing the file `/usr/share/dbus-1/services/com.github.wwmm.pulseeffects.service` may have the same effect.
