### ISSUE TITLE
Allow test signal frequencies up to 22Khz.

### ISSUE THREAD

**Issue by Mlocik97** [wwmm/pulseeffects#837]
Now limit is 20Khz, I would like to be able to set it up to 22Khz. Would it be possible?

**Comment by wwmm** [comment]
It should be. The GStreamer plugin documentation only says that the sampling rate should be at least 2 times higher than the selected frequency https://gstreamer.freedesktop.org/documentation/audiotestsrc/index.html?gi-language=c

**Comment by wwmm** [comment]
Implemented in the master branch. In the future I have to remember to bring the spectrum improvements to the test signals window too.
