### ISSUE TITLE
Deprecation warnings: New with GNOME 3.26 stack

### ISSUE THREAD

**Issue by AsavarTzeth** [wwmm/pulseeffects#84]
GNOME 3.26 is out and Flathub now has a 3.26 version of the gnome runtime available.

The reason why I want rebase on this, other than being up-to-date, is because it also brings the lastest gstreamer. It would be nice if we could trim down the [flatpak manifest](https://github.com/flathub/com.github.wwmm.pulseeffects/blob/master/com.github.wwmm.pulseeffects.json) by removing the need to build and ship gstreamer.

But of course, since it is GNOME, there are deprecation warnings:

https://paste.fedoraproject.org/paste/4PO8uWYbcUE3vo06BJCWEg/raw

Not sure if these are blockers or not, but I thought I would mention it.

**Comment by wwmm** [comment]
Good to know. I am still waiting for gnome 3.26 to hit the stable repository so I will not touch this now. But I did a little test and replacing `GObject.SIGNAL_RUN_FIRST` by `GObject.SignalFlags.RUN_FIRST` caused no harm in gtk 3.24. So I think that moving to the new api should not be a problem.

**Comment by AsavarTzeth** [comment]
Have this been solved? Yesterday I successfully migrated the flatpak build to 3.26, among a lot of other optimizations. Tested on 3b65612160b8e257827532340bcbb9b4c42ff040 and I no longer get any warnings.

**Comment by wwmm** [comment]
It must have been some kind of bug in gtk solved in one of its upgrades. I did not have this warn even after upgrading to gnome 3.26.

In any case I will make a mental note to move the signals the new api.
