### ISSUE TITLE
Create binary files

### ISSUE THREAD

**Issue by hinkali** [wwmm/pulseeffects#840]
Please create binary files for Pulseeffects,  Appimage or deb

**Comment by wwmm** [comment]
Taking care of the source code already consumes a lot of time. And creating packaged is a job better done by people used to it. There are lots of distributions providing packages for Pulseeffects. And a flatpack package too.

**Comment by hinkali** [comment]
Please create Appimage once every six months or a year at least

**Comment by hinkali** [comment]
flatpack not everyone likes

**Comment by wwmm** [comment]
Anyone is free to create an Appimage package. People thought about doing this in the past and I was not against the idea. But I am not the one that is going to do it just like I am not the one providing flatpak packages, debian, rpm, etc. My free time is spent in PulseEffects development.
