### ISSUE TITLE
PulseEffects crashing: locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by samvdkris** [wwmm/pulseeffects#849]
I've been having some issues with PulseEffects since I think two or three days ago. I'm on Arch Linux, and all my packages are up to date (pulseeffects 4.8.3-2).

Here are my error logs:

```
sam@aperture ~  $ pulseeffects 
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
fish: 'pulseeffects' terminated by signal SIGABRT (Abort)
```

```
Dec 12 16:24:50 aperture systemd-coredump[28657]: Process 28655 (pulseeffects) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 28655:
                                                  #0  0x00007fb0509d8615 raise (libc.so.6 + 0x3d615)
                                                  #1  0x00007fb0509c1862 abort (libc.so.6 + 0x26862)
                                                  #2  0x00007fb050d7e86a _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9686a)
                                                  #3  0x00007fb050d8ad9a _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xa2d9a)
                                                  #4  0x00007fb050d8ae07 _ZSt9terminatev (libstdc++.so.6 + 0xa2e07)
                                                  #5  0x00007fb050d8b0ae __cxa_throw (libstdc++.so.6 + 0xa30ae)
                                                  #6  0x00007fb050d81644 _ZSt21__throw_runtime_errorPKc (libstdc++.so.6 + 0x99644)
                                                  #7  0x00007fb050dada2a _ZNSt6locale5facet18_S_create_c_localeERP15__locale_structPKcS2_ (libstdc++.so.6 + 0xc5a2a)
                                                  #8  0x00007fb050d9f67e _ZNSt6locale5_ImplC2EPKcm (libstdc++.so.6 + 0xb767e)
                                                  #9  0x00007fb050da09bb _ZNSt6localeC2EPKc (libstdc++.so.6 + 0xb89bb)
                                                  #10 0x0000557e4b0bd18c n/a (pulseeffects + 0x8a18c)
                                                  #11 0x0000557e4b1f3f0d n/a (pulseeffects + 0x1c0f0d)
                                                  #12 0x00007fb0509c30de __libc_start_main (libc.so.6 + 0x280de)
                                                  #13 0x0000557e4b0bd7de n/a (pulseeffects + 0x8a7de)
```

Someone on the Arch subreddit pointed out that it seems to be an issue with my locale. My locale.conf and locale.gen are configured properly, but for some reason running `locale` still gives an error:

```
sam@aperture ~  $ locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_NL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=en_NL.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

This of course isn't PulseEffects's fault, but I thought y'all might want to know about the program crashing if there's an issue with the locale. I have "fixed" the issue by adding the LC_ALL environment variable to PulseEffects's autostart entry, but that's a bit of a hacky fix.

Also, if anyone has an idea on how to fix the locale thing, that would be very much appreciated :)

**Comment by Digitalone1** [comment]
Thanks for reporting. The latest version comes with some changes showing values out of GTK widgets according to system locale.

Maybe an exception handler is needed to avoid the crash on systems with faulty locale settings.

I don't know how to fix the locale itself. I suggest to read Arch Linux wiki, maybe there should be something. Could also be the desktop environment that is causing some issues. It happened to me in the past when I was using Plasma, but I don't remember how I resolved and now I'm using Gnome. See if setting something related to the locale in the desktop environment settings interface changes anything.

**Comment by shelra** [comment]
@samvdkris I arrived on same issue today on arch, how did you fix it?

**Comment by Digitalone1** [comment]
> @samvdkris I arrived on same issue today on arch, how did you fix it?

`LC_ALL=C pulseeffects`

Anyway, this is my locale, no error thrown:
```
$ locale
LANG=it_IT.UTF-8
LC_CTYPE="it_IT.UTF-8"
LC_NUMERIC="it_IT.UTF-8"
LC_TIME="it_IT.UTF-8"
LC_COLLATE="it_IT.UTF-8"
LC_MONETARY="it_IT.UTF-8"
LC_MESSAGES="it_IT.UTF-8"
LC_PAPER="it_IT.UTF-8"
LC_NAME="it_IT.UTF-8"
LC_ADDRESS="it_IT.UTF-8"
LC_TELEPHONE="it_IT.UTF-8"
LC_MEASUREMENT="it_IT.UTF-8"
LC_IDENTIFICATION="it_IT.UTF-8"
LC_ALL=
```

**Comment by Digitalone1** [comment]
I think this is thrown when a locale is not set at system level, so the application is trying to retrieve the locale by the system, but it fails.

Try to follow this: https://bbs.archlinux.org/viewtopic.php?id=257376

Maybe I can make it work, but it's a workaround, should be fixed by the user to get the proper locale.

**Comment by Digitalone1** [comment]
I added a workaround. Please, test it installing `pulseeffects-git` after @wwmm will accept the pull request.

If you don't want to wait, you can compile and install from [here](https://github.com/Digitalone1/pulseeffects-1).

**Comment by Digitalone1** [comment]
@samvdkris @shelra please install and test `pulseeffects-git` from AUR.

**Comment by samvdkris** [comment]
@Digitalone1 Awesome, that fixed the issue! Thank you so much for the quick reply and fix, really appreciate it!

As for the locale thing on my PC, I double-checked several times that it's configured properly. I think it might be an unrelated issue in another package, I'm not sure.
