### ISSUE TITLE
Equalizer knobs won't showing up

### ISSUE THREAD

**Issue by mthqwork** [wwmm/pulseeffects#855]
When I start up PulseEffects, equalizer knobs aren't there.
I can get it work by clicking to wrench button, enabling and disabling "Split Channels". 
Then they appear as it should.

![pe1](https://user-images.githubusercontent.com/19063751/102171612-3bd91b80-3e97-11eb-9926-e24d66495c64.png)

Version:  4.8.3-3, from Arch community repo.

**Comment by Digitalone1** [comment]
Duplicate of #843 

A new release will be available soon. Meanwhile install `pulseeffects-git` from AUR.

**Comment by mthqwork** [comment]
Thanks for sharing, sorry for duplicate :)
