### ISSUE TITLE
[pipewire]: No bluetooth audio

### ISSUE THREAD

**Issue by baalajimaestro** [wwmm/pulseeffects#856]
First of all, a huge thanks to making pulseeffects very usable with pipewire!

I have switched to pipewire recently, compiled the pipewire branch, and surprisingly bluetooth audio is entirely muted whenever Pulseeffects is running. Tho pulseeffects could list the a2dp sink properly, and manually selecting too doesnt help.

I have it all good if pulseeffects isnt running. I tried playing spotify, then calling pulseeffects from terminal, the audio cut off instantly.

I would be happy to provide logs whatever I can!

**Comment by wwmm** [comment]
Kill the current PulseEffects instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Let's see if there are errors being printed. But my guess is that the source of the problem is in PipeWire or its plugins for GStreamer. If you have a microphone there is a easy way to verify if that is the case. Set your microphone as default source and your bluetooth as default output. Kill PulseEffects and run this command:
```
gst-launch-1.0 -v pipewiresrc ! queue ! audio/x-raw,format=F32LE ! pipewiresink
```

If you are not able to hear your voice in the bluetooth device the issue has to be reported to PipeWire because the GStreamer plugins `pipewiresrc` and `pipewiresink` are developed by PiePeWire and not GStreamer.

The same test can be done in Pulseaudio with this command 
```
gst-launch-1.0 pulsesrc ! queue ! pulsesink
```

**Comment by nloewen** [comment]
I haven't had any issues with PipeWire+PulseEffects+Bluetooth specifically, but it does seem that there are situations where audio isn't being rerouted to the correct outputs properly. It's easy enough to fix manually with pavucontrol.

**Comment by wwmm** [comment]
Sometimes PipeWire is the one messing with routing. Take a look at this issue I opened there https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/498

**Comment by baalajimaestro** [comment]
Finally found whats actually going wrong, its pipewire messing with stuff.
Took me a brief while since I had exams and didnt want to poke into this, but pipewire-pulse specifically doesnt change the default sink when it detects a new source. It sticks to the old sink, a similar issue mentioned to the [bluetooth bug here](https://wiki.archlinux.org/index.php/PipeWire)

![image](https://user-images.githubusercontent.com/34187410/104542595-d0c36600-5649-11eb-8ca9-db55dfbe05f3.png)

It sticks to a dumb copy of Built-in Audio (on screenshot, the one with analog output, idk why this happens), and someone stuck like me, just install pavucontrol and switch your sinks manually until I get to figure how to do this with udev xd.

Closing this issue, since its no way related to pulseeffects.

**Comment by ZerkerEOD** [comment]
@baalajimaestro, did you figure that out? I just started running this and have the same issue. When I connect a Bluetooth headset the default device stays as my HDMI output. I used to have a virtual sink and it would automatically switch but the sink that EE creates doesn't automatically switch.

**Comment by wwmm** [comment]
@ZerkerEOD current EE releases are very different from the one in this issue. It is better to open a new one for your case providing some logs. First kill any instance with `easyeffects -q` and then run it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`.

**Comment by baalajimaestro** [comment]
Hey @ZerkerEOD I remember opening an issue on pipewire gitlab related to this, and it was pretty much fixed soon after. I am using pipewire for months now without this issue. Probably you are having an old version of pipewire?
