### ISSUE TITLE
rnnoise plugin not found in 4.8.3

### ISSUE THREAD

**Issue by Long-FA** [wwmm/pulseeffects#859]
Pulseeffects 4.8.0 was working perfectly on my Fedora 33 KDE computer, but after upgrading to 4.8.3 it refuses to launch. Here is what happened:

**4.8.0:** Double clicking Pulseeffects icon on desktop or start menu opens up Pulseeffects main interface. Pulseeffects-service run at startup if I enable Start service at login. Even after i close Pulseeffects main interface, the service still runs and equalizer is still in effect. Typing `pulseeffects` in terminal bring up the main interface without error.

**4.8.3:** Pulseeffects main interface won't show up when double clicking icon on desktop or start menu. Pulseeffects-service doesn't run at startup. Typing `pulseeffects` in terminal and it returns a `WARNING: rnnoise plugin not found`, but the main interface shows up. Typing `pulseeffects --gapplication-service` in terminal and it returns a `WARNING: rnnoise plugin not found`, but the service is started. However, closing the main interface will stop Pulseeffects altogether, and equalizer or any effect will be disabled.

If you need more details like debug message or screenshot, i will gladly provide.

**Comment by wwmm** [comment]
Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Let's see if there are errors.

The `rnnoise` warning can be ignored. This plugin is optional and PulseEffects works without it. Is `Fedora 33` using Pulseaudio or PipeWire by default?

**Comment by Long-FA** [comment]
Debug log of 4.8.0:

> (process:3310): pulseeffects-DEBUG: 21:26:35.501: main: locale directory: /usr/share/locale
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.511: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.511: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.511: presets_manager: system input presets directory: "/usr/share/kde-settings/kde-profile/default/xdg/PulseEffects/input"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.511: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.511: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.511: presets_manager: system output presets directory: "/usr/share/kde-settings/kde-profile/default/xdg/PulseEffects/output"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.511: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.511: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/input
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.511: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/output
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.511: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/autoload
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.756: application: PE version: 4.8.0
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.756: pulse_manager: context is connecting
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.756: pulse_manager: context is authorizing
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.756: pulse_manager: context is setting name
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.757: pulse_manager: context is ready
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.757: pulse_manager: connected to: /run/user/1000/pulse/native
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.757: pulse_manager: protocol version: 34
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.757: pulse_manager: Pulseaudio version: 14.0-rebootstrapped
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.757: pulse_manager: default pulseaudio source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.757: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.757: pulse_manager: loading Pulseeffects applications output sink...
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.757: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.757: pulse_manager: default pulseaudio sink audio format: s32le
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.757: pulse_manager:  failed to get sink info: PulseEffects_apps
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.762: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_apps sink_properties=device.description="PulseEffects(apps)"device.class="sound" norewinds=1
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.762: pulse_manager: loading Pulseeffects microphone output sink...
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.762: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.762: pulse_manager: default pulseaudio source audio format: s32le
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.762: pulse_manager:  failed to get sink info: PulseEffects_mic
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.767: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_mic sink_properties=device.description="PulseEffects(mic)"device.class="sound" norewinds=1
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.777: sie: using input device: PulseEffects_apps.monitor
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.777: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.791: sie: limiter is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.794: sie: compressor is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.795: sie: filter is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.833: sie: equalizer is enabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.835: sie: reverb is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.836: sie: bass_enhancer is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.838: sie: exciter is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.839: sie: crossfeed is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.841: sie: maximizer is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.844: sie: multiband_compressor is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.846: sie: loudness is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.847: sie: gate is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.849: sie: pitch is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.852: sie: multiband_gate is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.853: sie: deesser is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.855: sie: stereo_tools is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.857: sie: convolver is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.858: sie: crystalizer is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.859: sie: autogain is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.861: sie: delay is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.867: soe: using output device: PulseEffects_mic
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.867: soe: using input device: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.868: soe: limiter is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.868: soe: compressor is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.868: soe: filter is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.872: soe: equalizer is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.873: soe: reverb is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.873: soe: gate is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.874: soe: deesser is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.875: soe: pitch is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.878: soe: webrtc is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.878: soe: multiband_compressor is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.879: soe: multiband_gate is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.879: soe: stereo_tools is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.880: soe: maximizer is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: system input presets directory: "/usr/share/kde-settings/kde-profile/default/xdg/PulseEffects/input"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: system output presets directory: "/usr/share/kde-settings/kde-profile/default/xdg/PulseEffects/output"; 
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/input
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/output
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/autoload
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: presets_manager: destroyed
> pulseeffects-INFO: 21:26:35.881: application: disabling global bypass
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: sie: bypass is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:35.881: soe: bypass is already disabled
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:36.080: convolver_ui: irs directory already exists: /home/admin/.config/PulseEffects/irs
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:36.808: sie: total latency: 0 ms
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:36.808: soe: total latency: 0 ms
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:36.814: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:36.814: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_1f.3.analog-stereo
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:36.814: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1f.3.analog-stereo
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:36.814: soe: using input device: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:36.814: pulse_settings_ui: input device changed: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
> (pulseeffects:3310): pulseeffects-DEBUG: 21:26:36.814: pulse_settings_ui: added source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor

 

 
Debug log of 4.8.3:

> (process:1965): pulseeffects-DEBUG: 21:31:24.544: main: locale directory: /usr/share/locale
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.554: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.554: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.554: presets_manager: system input presets directory: "/usr/share/kde-settings/kde-profile/default/xdg/PulseEffects/input"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.554: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.554: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.554: presets_manager: system output presets directory: "/usr/share/kde-settings/kde-profile/default/xdg/PulseEffects/output"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.554: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.554: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/input
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.554: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/output
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.554: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/autoload
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.803: application: PE version: 4.8.3
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.803: pulse_manager: context is connecting
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.803: pulse_manager: context is authorizing
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.803: pulse_manager: context is setting name
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.803: pulse_manager: context is ready
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.803: pulse_manager: connected to: /run/user/1000/pulse/native
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.803: pulse_manager: protocol version: 34
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.804: pulse_manager: Pulseaudio version: 14.0-rebootstrapped
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.804: pulse_manager: default pulseaudio source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.804: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.804: pulse_manager: loading Pulseeffects applications output sink...
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.804: pulse_manager: default pulseaudio sink sampling rate: 48000 Hz
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.804: pulse_manager: default pulseaudio sink audio format: s32le
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.804: pulse_manager:  failed to get sink info: PulseEffects_apps
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.809: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_apps sink_properties=device.description="PulseEffects(apps)"device.class="sound" norewinds=1
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.809: pulse_manager: changed volume of the sink: PulseEffects_apps
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.809: pulse_manager: loading Pulseeffects microphone output sink...
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.809: pulse_manager: default pulseaudio source sampling rate: 48000 Hz
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.809: pulse_manager: default pulseaudio source audio format: s32le
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.809: pulse_manager:  failed to get sink info: PulseEffects_mic
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.814: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_mic sink_properties=device.description="PulseEffects(mic)"device.class="sound" norewinds=1
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.814: pulse_manager: changed volume of the sink: PulseEffects_mic
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.825: sie: using input device: PulseEffects_apps.monitor
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.825: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.840: sie: limiter is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.843: sie: compressor is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.844: sie: filter is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.883: sie: equalizer is enabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.885: sie: reverb is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.886: sie: bass_enhancer is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.887: sie: exciter is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.888: sie: crossfeed is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.891: sie: maximizer is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.893: sie: multiband_compressor is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.895: sie: loudness is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.896: sie: gate is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.898: sie: pitch is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.901: sie: multiband_gate is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.902: sie: deesser is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.904: sie: stereo_tools is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.906: sie: convolver is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.907: sie: crystalizer is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.908: sie: autogain is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.910: sie: delay is already disabled
> 
> (pulseeffects:1965): pulseeffects-WARNING **: 21:31:24.910: rnnoise plugin was not found!
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.915: soe: using output device: PulseEffects_mic
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.915: soe: using input device: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.915: soe: limiter is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.916: soe: compressor is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.916: soe: filter is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.920: soe: equalizer is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.921: soe: reverb is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.921: soe: gate is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.922: soe: deesser is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.923: soe: pitch is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.927: soe: webrtc is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.928: soe: multiband_compressor is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.928: soe: multiband_gate is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.929: soe: stereo_tools is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.929: soe: maximizer is already disabled
> 
> (pulseeffects:1965): pulseeffects-WARNING **: 21:31:24.929: rnnoise plugin was not found!
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: system input presets directory: "/usr/share/kde-settings/kde-profile/default/xdg/PulseEffects/input"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: system output presets directory: "/usr/share/kde-settings/kde-profile/default/xdg/PulseEffects/output"; 
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/input
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/output
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/autoload
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: presets_manager: destroyed
> pulseeffects-INFO: 21:31:24.931: application: disabling global bypass
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: sie: bypass is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:24.931: soe: bypass is already disabled
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:25.277: convolver_ui: irs directory already exists: /home/admin/.config/PulseEffects/irs
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:25.288: rnnoise_ui: model directory already exists: /home/admin/.config/PulseEffects/rnnoise
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:25.533: rnnoise_ui: model directory already exists: /home/admin/.config/PulseEffects/rnnoise
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:25.991: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:25.991: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_1f.3.analog-stereo
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:25.991: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1f.3.analog-stereo
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:25.991: soe: using input device: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:25.991: pulse_settings_ui: input device changed: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
> (pulseeffects:1965): pulseeffects-DEBUG: 21:31:25.991: pulse_settings_ui: added source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor

**Comment by wwmm** [comment]
So far I see nothing that would justify the service dying when the window is closed. `--gapplication-service` is a GTK feature that helps gui applications to run in background. The part of PulseEffects that uses it haven't changed in at least 1 year. Probably more.

>Pulseeffects main interface won't show up when double clicking icon on desktop or start menu

This feature relies on a DBUS connection defined at `/usr/share/dbus-1/services/com.github.wwmm.pulseeffects.service`. Another thing that hasn't gone through changes in a very long time.

I don't know what has gone wrong when `4.8.3` was packaged for Fedora. The package in Arch Linux repository also does not have `rnnoise` and it works.

**Comment by Long-FA** [comment]
Thanks for the heads up. My gnome-abrt reported that `pulseeffects quit unexpectedly`, the reason is `pulseeffects killed by SIGABRT`. I checked Fedora Bodhi and someone filed a bug report that `pulseeffects killed by SIGSEGV`. God knows what went wrong, guess i have to stay in 4.8.0 for now.
When 4.8.4 or new versions for Fedora arrives, i will test and reply to this issue.
Happy Christmas.

**Comment by IdreesM0** [comment]
Not directly related to the topic at hand but I have problems running PE because of unavailability of rnnoise. I am trying to install and run PE from source (for checking out latest builds thats all). It gives me error at runtime saying `(pulseeffects:15181): GLib-GIO-ERROR **: 02:52:05.581: Settings schema 'com.github.wwmm.pulseeffects.rnnoise' is not installed
Trace/breakpoint trap (core dumped)
`
I tried running `glib-compile-schemas /usr/share/glib-2.0/schemas` but in vain.
Any ideas how I can get past this issue are highly appreciated!

**Comment by wwmm** [comment]
>I have problems running PE because of unavailability of rnnoise

This plugin is optional. The package in the Arch repository works without it. Is there a file named `com.github.wwmm.pulseeffects.rnnoise.gschema.xml` inside `/usr/share/glib-2.0/schemas`? It has to be there for `glib-compile-schemas` to have an effect

**Comment by wwmm** [comment]
If you just want to run PE from its source directory you can set the path to the schemas in the source folder in a similar way as you can see here https://github.com/wwmm/pulseeffects/blob/master/util/environmental_variables.sh

**Comment by IdreesM0** [comment]
Pardon my ignorance but do I need to have pipewire installed and configured for the version 5 to work? And is PE going to abandon pulseaudio with this release? If not, how can I make version 5 work with pulseaudio?

**Comment by wwmm** [comment]
>do I need to have pipewire installed and configured for the version 5 to work?

Yes. The master branch has moved to PipeWire and won't work without it. If you have to stay on Pulseaudio I suggest you use the legacy branch instead https://github.com/wwmm/pulseeffects/tree/pulseaudio-legacy.

>is PE going to abandon pulseaudio with this release?

Yes again. The reason is that the native PipeWire API is totally different from Pulseaudio's. Supporting both in the same code would add lots of complexity. So in a way Pulseaudio is being abandoned. The legacy branch will receive only occasional fixes for really critical bugs.

**Comment by IdreesM0** [comment]
Thats news to me since I have not known anything for audio besides pulseaudio (you can say I am a casual consumer). I dont know how I can configure pipewire with the same settings as I have for pulseaudio(resampler, default sample rate, default format etc) But I can't abandon PE under any circumstance so pipewire it is. 
If you don't mind me asking, Im positive that its justified but what was your motivation behind abandoning pulseaudio (it is mainstream, a lot of documentation, community etc and is the default for casual users) for pipewire?

**Comment by wwmm** [comment]
>what was your motivation behind abandoning pulseaudio

Although PipeWire still has a few rough edges some distributions like Fedora are already discussing making it the default sound server. So it is better to start to port our code to PIpeWire now. While that movement is still beginning. And for the operations PulseEffects has to do relying on PipeWire's compatibility layer for Pulseaudio's applications is not a good idea. At least when I started the port it did not have all the functionality needed to "just use" our Pulseaudio version. Using its native API was clearly the better thing to do. Another disadvantage of not using its native functions is that PulseEffects would only work for Pulseaudio applications. Anything else using PipeWire's native API would not work with us.

>I can't abandon PE under any circumstance so pipewire it is.

Honestly you can stay on Pulseaudio and use the legacy branch. Although I have been using PipeWire daily and almost everything is fine it still has some bugs that are not nice to the end user. Mostly for people using headphones and bluetooth. So unless your distribution forces you to use PipeWire now I do not see a reason to do that yet.

**Comment by Long-FA** [comment]
It appears that the problem is fixed in version 4.8.4 Fedora. Maybe the person in charge screwed up something in 4.8.3.

**Comment by wwmm** [comment]
Ok. If the problem comes back feel free to reopen this issue.
