### ISSUE TITLE
[help] Merge 2 channels (stereo to mono)

### ISSUE THREAD

**Issue by kaynetik** [wwmm/pulseeffects#860]
This might have already been asked, but I didn't manage to find a similar question.
I've recently upgraded my audio setup, which works out of the box on Windows. But I'm having some difficulties setting it up on Arch.
_Setup: Rode ProCaster + Focusrite Scarlett 2i2_

And my question:

Is it possible with Pulseeffects to **merge 2 channels into one**, e.g. Mono, systemwide? And if so, how would I achieve it?

Thanks! :muscle:

**Comment by wwmm** [comment]
Enable the Stereo Tools plugin and select the desired mode in the stereo matrix
![Screenshot from 2020-12-26 13-25-11](https://user-images.githubusercontent.com/16225172/103155352-dda51600-477d-11eb-8fdd-fddc60271481.png)

**Comment by kaynetik** [comment]
Thanks for such a quick reply! Worked like a charm.
