### ISSUE TITLE
PulseEffects installed from Flathub does not allow renice

### ISSUE THREAD

**Issue by leleobhz** [wwmm/pulseeffects#863]
Hello!

I'm running PulseEffects in a Fedora 33 installation with PE installed via Flathub. Change priority to realtime or anything not the default leads PulseEffects to crash.

I suspect it maybe a permission issue. This can be fixed?

Thanks!

**Comment by wwmm** [comment]
Flatpak does not support realtimekit. Without this this feature does not work:

https://github.com/wwmm/pulseeffects/issues/445
https://github.com/flatpak/xdg-desktop-portal/issues/355
