### ISSUE TITLE
No application being shown

### ISSUE THREAD

**Issue by NatanCervinski** [wwmm/pulseeffects#866]
I think after updating my system (5.9.16-1-MANJARO), PulseEffects stop to working, the applications disappear.
![image](https://user-images.githubusercontent.com/53199974/103448629-e3699280-4c7a-11eb-8bfd-b46b06833b16.png)
In the screenshot I am with Firefox and Spotify opened. Before it's just work.
I already reinstalled

Debug (G_MESSAGES_DEBUG=pulseeffects pulseeffects):

(process:13816): pulseeffects-DEBUG: 21:47:52.389: main: locale directory: /usr/share/locale
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.459: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.459: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.459: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.459: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.459: presets_manager: user presets directory already exists: /home/natan/.config/PulseEffects
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.459: presets_manager: user presets directory already exists: /home/natan/.config/PulseEffects/input
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.459: presets_manager: user presets directory already exists: /home/natan/.config/PulseEffects/output
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.459: presets_manager: user presets directory already exists: /home/natan/.config/PulseEffects/autoload
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.462: application: PE version: 5.0.0
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.462: pipe_manager: compiled with pipewire: 0.3.18
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.462: pipe_manager: linked to pipewire: 0.3.18
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.464: pipe_manager: core version: 0.3.18
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.464: pipe_manager: core name: pipewire-0
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.464: pipe_manager: Audio/Sink 40 pulseeffects_sink was added
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.464: pipe_manager: Audio/Sink 45 pulseeffects_source was added
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.464: pipe_manager: connected to the core
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.481: soe: using input device: 40
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.481: soe: using output device: 40
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.486: soe: limiter is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.488: soe: compressor is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.490: soe: filter is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.530: soe: equalizer is enabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.532: soe: reverb is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.533: soe: bass_enhancer is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.535: soe: exciter is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.537: soe: crossfeed is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.541: soe: maximizer is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.544: soe: multiband_compressor is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.546: soe: loudness is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.548: soe: gate is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.550: soe: pitch is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.553: soe: multiband_gate is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.555: soe: deesser is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.557: soe: stereo_tools is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.559: soe: convolver is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.561: soe: crystalizer is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.562: soe: autogain is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.565: soe: delay is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.566: soe: rnnoise is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.571: sie: using input device: 0
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.572: sie: using output device: 45
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.572: sie: limiter is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.573: sie: compressor is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.573: sie: filter is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.578: sie: equalizer is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.578: sie: reverb is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.579: sie: gate is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.580: sie: deesser is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.580: sie: pitch is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.584: sie: webrtc is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.585: sie: multiband_compressor is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.585: sie: multiband_gate is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.586: sie: stereo_tools is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.586: sie: maximizer is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.587: sie: rnnoise is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.588: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.588: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.588: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.588: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.588: presets_manager: user presets directory already exists: /home/natan/.config/PulseEffects
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.588: presets_manager: user presets directory already exists: /home/natan/.config/PulseEffects/input
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.588: presets_manager: user presets directory already exists: /home/natan/.config/PulseEffects/output
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.588: presets_manager: user presets directory already exists: /home/natan/.config/PulseEffects/autoload
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.588: presets_manager: destroyed
pulseeffects-INFO: 21:47:52.589: application: disabling global bypass
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.589: soe: bypass is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:52.589: sie: bypass is already disabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:53.096: convolver_ui: irs directory already exists: /home/natan/.config/PulseEffects/irs
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:53.110: rnnoise_ui: model directory already exists: /home/natan/.config/PulseEffects/rnnoise
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:53.564: rnnoise_ui: model directory already exists: /home/natan/.config/PulseEffects/rnnoise
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:53.611: sie: spectrum enabled
(pulseeffects:13816): pulseeffects-DEBUG: 21:47:53.612: soe: spectrum enabled

**Comment by wwmm** [comment]
>application: PE version: 5.0.0

Our development release moved from Pulseaudio to PipeWire. Check if your PipeWire installation has some issue. PulseEffects logs are not showing your sound card sinks. This is a sign that something is broken in PipeWire.

**Comment by wwmm** [comment]
If you cn not or do not want to use PipeWire yet I suggest you stay on Pulseaudio and install our last release `4.8.4`

**Comment by NatanCervinski** [comment]
I installed last release and now it's working, thank you for the attention
