### ISSUE TITLE
Please add git tag for 4.8.4 release

### ISSUE THREAD

**Issue by RafaelKr** [wwmm/pulseeffects#868]
I just tried to build the flathub package with version 4.8.4. Unfortunately the build fails as there is no such git tag.

```
Fetching full git repo https://github.com/wwmm/pulseeffects.git
remote: Enumerating objects: 28108, done.
remote: Counting objects: 100% (28108/28108), done.
remote: Compressing objects: 100% (5414/5414), done.
remote: Total 27758 (delta 22362), reused 27438 (delta 22048), pack-reused 0
Receiving objects: 100% (27758/27758), 21.49 MiB | 10.33 MiB/s, done.
Resolving deltas: 100% (22362/22362), completed with 231 local objects.
From https://github.com/wwmm/pulseeffects
 * [new branch]        master              -> master
 * [new branch]        pulseaudio-legacy   -> pulseaudio-legacy
 * [new branch]        python              -> python
 * [new branch]        rust                -> rust
 * [new branch]        ww_playground       -> ww_playground
 * [new ref]           refs/pull/107/head  -> refs/pull/107/head
 * [new ref]           refs/pull/108/head  -> refs/pull/108/head

[...]

 * [new tag]           v4.7.3              -> v4.7.3
 * [new tag]           v4.8.0              -> v4.8.0
 * [new tag]           v4.8.1              -> v4.8.1
 * [new tag]           v4.8.3              -> v4.8.3
fatal: ambiguous argument 'v4.8.4': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Failed to download sources: module pulseeffects: Child process exited with code 128
```

Could you please add that tag?

Edit: When this is added I can directly update my PR for the Flathub package to include version 4.8.4
see https://github.com/flathub/com.github.wwmm.pulseeffects/pull/42

cc @AsavarTzeth

**Comment by wwmm** [comment]
Strange. This tag exists https://github.com/wwmm/pulseeffects/releases/tag/4.8.4

**Comment by wwmm** [comment]
Now I see... It is missing  a `v` in the beginning...

**Comment by wwmm** [comment]
Is there an easy way to rename it in git?

**Comment by RafaelKr** [comment]
> Is there an easy way to rename it in git?

stackoverflow tells me this: https://stackoverflow.com/a/5719854/4303873
But I'm not sure if it's better to just add another tag. I don't know if there could be bad consequences when it's renamed

**Comment by wwmm** [comment]
It was definitely easier to just add a new tag

**Comment by wwmm** [comment]
https://github.com/wwmm/pulseeffects/releases/tag/v4.8.4

**Comment by RafaelKr** [comment]
Awesome, thanks!

Are you enough involved in the Pulseeffects project to tell me if I also should add or update some more dependencies here? https://github.com/flathub/com.github.wwmm.pulseeffects/pull/42

**Comment by RafaelKr** [comment]
> Are you enough involved in the Pulseeffects project to tell me...

@wwmm nevermind, I just had a look at the Commit history.. Of course you are! 😂

**Comment by wwmm** [comment]
>nevermind, I just had a look at the Commit history.. Of course you are

hahaha :D Yes. I am its author.

At this moment no other dependency comes to my mind. the minimum versions are already set in our Meson files. IF it does not complain you are fine. There are things that just doesn't work in flatpak like using realtime priorities. But that has to be fixed on flatpak.

**Comment by RafaelKr** [comment]
Awesome! @AsavarTzeth https://github.com/flathub/com.github.wwmm.pulseeffects/pull/43 is ready to merge then.

Thank you all for providing such a great package!
