### ISSUE TITLE
Instantly crashes when opening, launching from terminal yields: failed to load module-null-sink

### ISSUE THREAD

**Issue by CIosure** [wwmm/pulseeffects#878]
Output of launching it through terminal, with full error: [https://pastebin.com/raw/u8q11H7L](https://pastebin.com/raw/u8q11H7L)
I suspect that this is an issue with my new computer's audio setup, because my tower is farther from me and it would be uncomfortable to have my headphone cable stretched far, I'm resorting to using my monitor's headphone port (Audio carried through DisplayPort). The monitor also has onboard speakers. There are no microphones present.

Arch Linux - KDE Plasma 
Installed from Arch community repo
`pactl list short`: [https://pastebin.com/raw/NEYmjd3Z](https://pastebin.com/raw/NEYmjd3Z)
`pacmd list-sinks`: Daemon not responding.
`pacmd list-sink-inputs`: Daemon not responding.
`pacmd list-sources`: Daemon not responding.
`pacmd list-source-outputs`: Daemon not responding.
`pulseaudio --dump-conf`: [https://pastebin.com/raw/zSx1PgsN](https://pastebin.com/raw/zSx1PgsN)

Quick edit, pulseeffects refuses to run at all and outputs 
`terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)`
Unless I do `export LC_ALL=C`.

I'm guessing this is my fault and I borked something while installing Arch.

**Comment by wwmm** [comment]
Pacman probaly installed `pipewire-pulse`. The pulseeffects version in the stable repository works only with Pulseaudio. Ony our development code in the master branch works with PipeWire. Remove pipewire-pulse and thins should work.

I thought that the locale bug had been fixed. What is the output of `locale` in your system?

**Comment by CIosure** [comment]
While `pipewire-pulse` was not installed, I've managed to fix this issue, this was indeed an issue relating to my messed up locales. I had non-English locales set without having them generated.
