### ISSUE TITLE
Equalizer turn on by default for every program

### ISSUE THREAD

**Issue by Ixoos** [wwmm/pulseeffects#88]
I'm using PulseEffects with a lot of programs, every time when I'm using something new I need to turn equalizer for it, its annoying because I have Pulseeffects running with --no-window command, could you add option to turn on equalizer for everything by default?

**Comment by wwmm** [comment]
Now that the infrastructure for command line options is in place it should be possible. I will take a look as soon as I have time to work on PulseEffects code.

**Comment by wwmm** [comment]
I have just added a `--switch-on-all-apps` option. It can be used with or without the `--no-window` option.
