### ISSUE TITLE
Pulse effects doesn't show any applications

### ISSUE THREAD

**Issue by kitty-alt** [wwmm/pulseeffects#881]
Pulseeffects (git version) on Manjaro no longer shows any audio sources, and therefore doesn't intercept any audio and apply effects, or do anything. But hey at least you made the ui labels more "inclusive"...

**Comment by wwmm** [comment]
>But hey at least you made the ui labels more "inclusive"...

In case you did not notice this kind of comment is too offensive for someone seeking help...

**Comment by kitty-alt** [comment]
> > But hey at least you made the ui labels more "inclusive"...
> 
> In case you did not notice this kind of comment is too offensive for someone seeking help...

It's offensive to be annoyed that the latest iteration of a very good application doesn't seem to function anymore, but has refactored its wording for other people who find common terminology offensive? *I apologize.* That aside, [pulseeffects-git](https://aur.archlinux.org/packages/pulseeffects-git/) does seem to be non functional on arch/manjaro currently, at least on my system. This might be out of scope for issues here as it may just be a packaging related issue.

**Comment by wwmm** [comment]
You have the right to be annoyed when an application does not work. No problems with that. But disdain the work made for free by volunteers is not right... Specially when the mentioned work has been done 4 releases ago and has nothing to do with the latest releases...

Since version `5.0.0` we use Pipewire instead of Pulseaudio. My bet is that your system is using Pulseaudio instead of Pipewire as sound server. In that case install `4.8.4` or edit the pkgbuild so it gets the code from our legacy Pulseaudio branch https://github.com/wwmm/pulseeffects/tree/pulseaudio-legacy. This branch will receive bug fixes for critical bugs when necessary.  So if PipeWire is not for you yet staying on the legacy branch is fine.

**Comment by Digitalone1** [comment]
> But hey at least you made the ui labels more "inclusive"...

Please, delete this sentence.

If you're still on plain PulseAudio, `makepkg -sri` on PKGBUILD provided in the branch above by wwmm, or the one in [my repo](https://github.com/Digitalone1/pulseeffects-1) updated on the last rnnoise commit.

If Manjaro will switch on Pipewire, change to `pulseeffects-git` from AUR.

**Comment by wwmm** [comment]
>or the one in my repo updated on the last rnnoise commit

I think it is possible to do a pull request to the legacy branch. If you want to do it feel free to go ahead.

**Comment by Digitalone1** [comment]
@wwmm can you please tell me how to do it? I'm afraid it will go in master branch. Then PKGBUILD should be updated to point to your branch.

**Comment by wwmm** [comment]
I never tried to do that but I did a quick look at the pull request dialog now and I saw that it lets us choose the destination branch. I think that is all you have to do. And even if it goes to the wrong branch I always have the option to deny the merge. So there shouldn't be a problem in trying to see what happens.

**Comment by Digitalone1** [comment]
Did it. Please, specify on master branch readme that who needs PulseEffects on PulseAudio should compile itself from source in legacy branch or pick legacy PKGBUILD.

**Comment by wwmm** [comment]
>specify on master branch readme that who needs PulseEffects on PulseAudio should compile itself from source in legacy branch or pick legacy PKGBUILD

Done.

**Comment by kitty-alt** [comment]
I apologize for being snarky. It's definitely an issue with Manjaro not using Pipewire by default.
