### ISSUE TITLE
Pulseeffects stopped working on Manjaro KDE

### ISSUE THREAD

**Issue by das22** [wwmm/pulseeffects#882]
Hi

Apologies if this was already posted but I didn't notice this exact issue. I've used Pulseeffects without issue (Manjaro KDE, 5.10 kernel) for a year or so but for a few weeks now it doesn't work. Specifically, the version 4.8.3 from the official Manjaro repo doesn't start at all (no GUI) and when I try to lunch from the terminal, I get:

`terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)
`

I've tried installing a 4.8.4 from the AUR and GUI opens up but doesn't "see" sound to process (e.g. if I have audio running from a browser or video player, the app no longer shows up in Pulseeffects). It also doesn't show up as an audio device next to the usual mic/speakers shown by the system's Audio app. 

From googling around, I get the impression this is pipewire related (I see it installed on my system though pipewire-pulse mentioned in some discussions isn't) but I don't understand enough to fix it on my own. Is there a solution?

Thank you!

**Comment by wwmm** [comment]
What is the output of the command `locale` in your system? Recently a user had the same error #878 and the cause was a bad locale configuration.

PipeWire became our server in version `5.0.0`. Anything before that uses Pulseaudio and not PipeWire.

**Comment by wwmm** [comment]
If you install `pipewire-pulse` Pulseaudio will be removed and your system will be on PipeWire. In this case you will need PE `5.0.0`. But I think that you have a locale problem.

**Comment by das22** [comment]
Thanks for the quick reply! Here's my locale output. Its a mess because of using a German laptop (with German keyboard layout) while wanting to retain English as system language so maybe this is indeed the source of the issue. Any idea what/how to fix it?

`locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_DE.UTF-8
LC_CTYPE="en_DE.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_DE.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_DE.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
`

**Comment by wwmm** [comment]
According to the user in #878 the problem was having the locale defined but not generated. Maybe running `sudo locale-gen` is enough.

@Digitalone1 didn't we fix the locale crashes. I do not know why people are having this problem again even on the legacy releases.

**Comment by Digitalone1** [comment]
If they installed `pulseeffects-git`, version 4.8.4 was not installed. `PKGBUILD` on legacy branch should be used.

**Comment by Digitalone1** [comment]
Finally someone did it: https://aur.archlinux.org/packages/pulseeffects-legacy-git/

**Comment by das22** [comment]
Many thanks for the help! I managed to make the 4.8.3-3 version from the Manjaro repo work by setting the locale and formats all to en_GB (all en_US also works). en_DE or any mixture of locales/formats (e.g. time format from a different locale) prevent the GUI from opening.

The 4.8.4 legacy version on AUR will not install due to librnnoise failing to build but I'll try to make due with 4.8.3 and the en_GB workaround.

**Comment by wwmm** [comment]
>The 4.8.4 legacy version on AUR will not install due to librnnoise failing to build

As far as I remember compilation should not fail when rnnoise is not installed. What is the error printed in the terminal?

**Comment by das22** [comment]
Something seems to have changed since yesterday and legacy 4.8.4 from AUR now builds (previously I was getting an error that librnnoise didn't pass a validity check). Pulseeffects now also works with the en_DE locale. I think I'm good. 

Many thanks!

**Comment by wwmm** [comment]
Ok. If necessary feel free to reopen this issue.

**Comment by AlexWayfer** [comment]
Installing `pipewire-pulse` (which replaces `pulseaudio` and related) really helps. Thank you all. Don't forget to reboot! Also notice, that `systemd` units of `pipewire` are `--user`.

I'm actually accept this maintenance policy. I can understand that main dependency switching is very breaking, but there is a major version, so I don't see problems for conservative people, especially with legacy AUR packages.

Thank you @wwmm and others. I hope everything will move from PulseAudio to PipeWire, to unify and simplify this audio layer.

Also a note: output volume became higher, although I had problems with input volume (with external audio card by ASUS, I had to type something like `pactl set-source-volume 58 350%`, and the id is always different, and some applications can reset it to 100%), and it didn't change sadly, but in total sound became better.
