### ISSUE TITLE
equalizer didn't show until I clicked "Reset"

### ISSUE THREAD

**Issue by chrisco23** [wwmm/pulseeffects#884]
For the moment I was just looking for a basic equalizer to help control movies that get really loud every time except when you actually want to hear the dialogue.

I found pulseeffects and I installed every single dependency (25 of them) listed in the AUR page.

I clicked Equalizer but no controls showed up.  A little 2-channel display showed at the bottom.

I googled for a very long time and couldn't find a solution.

Finally, just by chance, I clicked "Reset" and the entire 30-band equalizer suddenly displayed.

Arch Linux - fully-updated 1/23/2021.
i3 window manager.

So my situation appears to be solved but I am posting this in case it can help somebody else.

Thanks for this tool that now I will spend some real time exploring, now that the initial effect (EQ) is working.

**Comment by Digitalone1** [comment]
Duplicate of #843 and #855

This was fixed. Are you sure you're using [pulseeffects-git](https://aur.archlinux.org/packages/pulseeffects-git/) or [pulseeffects-legacy-git](https://aur.archlinux.org/packages/pulseeffects-legacy-git/) from AUR? This issue was in v4.8.3 and [upstream](https://archlinux.org/packages/community/x86_64/pulseeffects/) is still on it.

**Comment by chrisco23** [comment]
You're right I had been using just pulseeffects 4.8.3-3.

I uninstalled pulseeffects and went to install pulseeffects-git but this opens up a big enough can of worms that I think I'll just stay with what I have, only requires remembering that one extra click.  I'll wait for upstream then since this is already a known issue.

**Comment by wwmm** [comment]
If you want to stay on Pulseaudio try `pulseeffects-legacy-git ` instead. Despite the name it is fine to use it.
