### ISSUE TITLE
Configuration file doesn't updated inside PE

### ISSUE THREAD

**Issue by ngergo0831** [wwmm/pulseeffects#888]
I changed /etc/pulse/daemon.conf, saved it, but inside the application it still shows the old version's data. I tried rebooting the system, and kill pulseaudio, but none of them worked.
![image](https://user-images.githubusercontent.com/46540798/106064519-4de6e480-60fa-11eb-8d0b-88d88e472c3c.png)

**Comment by wwmm** [comment]
What this section does is showing the output of `pulseaudio --dump-conf`. Nothing more. What do you see in this command output?

**Comment by ngergo0831** [comment]
I found out the problem was with pulseaudio. For some reason it just crashed everytime. It was Kubuntu 20.04 LTS btw. I just uninstalled Kubuntu, and replaced with 'basic' Ubuntu, and now PulseEffects and the config are working fine.
