### ISSUE TITLE
Keep getting static until I switch Priority Type

### ISSUE THREAD

**Issue by ShayBox** [wwmm/pulseeffects#889]
Keep getting static until I switch Priority Type, only on output, not microphone, any priority type will fix it, the time it lasts varies from seconds to hours

**Comment by wwmm** [comment]
Kill the current instance `pulseeffects -q` and restart it n debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Let's see if the logs show anything unusual.

**Comment by ShayBox** [comment]
[This is the output from opening it](https://paste.nomsy.net/raw/godepimeye) if any of that is useful, i'll post with any more log when the issue comes up if there is any.

**Comment by wwmm** [comment]
Nothing unusual in the logs. The message `rnnoise plugin was not found!` can be ignored because this plugin is optional. But I think that the most interesting logs will be the ones where our pipeline is in the playback state.

**Comment by ShayBox** [comment]
Well I haven't had any issues since making this issue so I guess pipewire fixed whatever it was themselves
