### ISSUE TITLE
Looks like a really nice application, but I have Major sound problems after installing this

### ISSUE THREAD

**Issue by phd21** [wwmm/pulseeffects#89]
Hi wwmm pulse effects,

I read about this in this article below and the great user comments. I installed this using the ".deb" in this link into my Linux Mint KDE 18.1 (Ubuntu 16.04) system.
[http://www.omgubuntu.co.uk/2017/06/install-pulse-effects-ubuntu-ppa](url)

I am using Linux Mint KDE 18.1 (Ubuntu 16.04) on one partition and Linux Mint KDE 17.3 (Ubuntu14.04) on another partition on a Dell Optiplex UltraMini 780 (64-bit) the audio "Intel 82801JD/DO (ICH10 Family) HD Audio Controller". My sound worked perfectly before installing and trying this application in my Linux Mint KDE 18.1 system. Now, my sound is horrible like it is stuck in an echo reverb mode, vocals are distant and barely audible. So I removed the "pulseefects application, rebooted, still sounds bad, powered off and on, still sounds bad. Remove (purged) alsa and pulse audio and reinstalled, still sounds bad. So, I booted into my Linux Mint KDE 17.3 system on a different partition and it too has the same horrible sound now, and I did not install this application in that system??? It is like the actual onboard sound card has somehow been physically altered and is remembering the setting from this "pusleeffects" program?

How can I get my sound card to work as it did before installing this "pulse effects"? Is there a way to reset and or reverse whatever was installed or done by this application, and if so, please explain too me in detail how to do this. 

Thank you,

Phil
phd21

**Comment by wwmm** [comment]
Hi,

Even when installed PulseEffects does nothing unless you open its window. It does not add a background service and it also does not touch Pulseaudio's configuration or the soundcard. 

Can you post here a snapshot of pavucontrol window? The output device tab. If there is no PulseEffects sink this problem is somewhere else
