### ISSUE TITLE
Arch how to use Noise Reduction?

### ISSUE THREAD

**Issue by seedship** [wwmm/pulseeffects#893]
I installed rnnoise from AUR.

```
[seedship@triple-destinies ~]$ pacman -Ql rnnoise
rnnoise-git /usr/
rnnoise-git /usr/include/
rnnoise-git /usr/include/rnnoise.h
rnnoise-git /usr/lib/
rnnoise-git /usr/lib/librnnoise.so
rnnoise-git /usr/lib/librnnoise.so.0
rnnoise-git /usr/lib/librnnoise.so.0.4.1
rnnoise-git /usr/lib/pkgconfig/
rnnoise-git /usr/lib/pkgconfig/rnnoise.pc
rnnoise-git /usr/share/
rnnoise-git /usr/share/doc/
rnnoise-git /usr/share/doc/rnnoise/
rnnoise-git /usr/share/doc/rnnoise/AUTHORS
rnnoise-git /usr/share/doc/rnnoise/COPYING
rnnoise-git /usr/share/doc/rnnoise/README
```

However, when I start PulseEffects, I can't utilize the noise reduction tools. Am I missing something?

**Comment by wwmm** [comment]
Differently from what happens to most of the plugins used in PulseEffects that one must be installed in the system when PulseEffects is compiled. IF you are installing PulseEffects from AUR try to rebuild the package

**Comment by IslandC0der** [comment]
> Differently from what happens to most of the plugins used in PulseEffects that one must be installed in the system when PulseEffects is compiled. IF you are installing PulseEffects from AUR try to rebuild the package

Indeed. It works for me if the dependency is present when compiling.

**Comment by seedship** [comment]
Hm, I tried installing from the official arch repo (version 4.8.3-3) and it doesn't work. I tried building from pulseeffects-legacy, and it appeared to be working, but then pavucontrol didn't register pulseeffects as a sync device. I guess I'll have to try and figure out why

**Comment by wwmm** [comment]
sync device?
