### ISSUE TITLE
Per-application filter switch is stuck to enabled with PipeWire

### ISSUE THREAD

**Issue by quietvoid** [wwmm/pulseeffects#896]
Hi, I just installed pipewire again and using pulseeffects 5.0.0 on Arch.
When starting the app, the configuration doesn't seem to remember the previously enabled apps (unlike pulseeffects-legacy).

So I go to enable the filters for an app, and it works. However it can't be switched back off.
To turn off the filters, I have to disable them individually. Or use bypass.

Also, when switching an app to disabled and muting it, the switch goes back to enabled.
The blocklist also has no effect.

Debug log with `G_MESSAGES_DEBUG=pulseeffects pulseeffects`: [debug.log](https://github.com/wwmm/pulseeffects/files/5929811/debug.log)

The apps I tested this with were Spotify, Discord and Firefox.

**Comment by Digitalone1** [comment]
This could be an interesting read: #696 

Before the logic was "a blocklisted app is an app that I ignore".

But this lead to some issues because of the way PulseAudio works, since it remember the last connection, so there were some situations were you added the app to the blocklist, but then it didn't play at all on the system because PulseAudio redirected it to PE, but PE did not processed it. 

So the logic was changed to "a blocklisted app is an app that I do not ignore, but I disable it".

Unfortunately this seems to be different on Pipewire and has to be reworked in some way.

**Comment by quietvoid** [comment]
The apps seem to be kept in the blocklist just fine, but the filters are still always enabled (after enabling once) even if the app is in the list and/or the switch is disabled.

So there must be something not visible in the UI that's not switching filters off per app, or that fails in doing so.

**Comment by wwmm** [comment]
>When starting the app, the configuration doesn't seem to remember the previously enabled apps (unlike pulseeffects-legacy).

I did not test yet if PipeWire remembers the association between streams and devices. But PulseEffects does not need it. Is `Process All Outputs` enabled in our settings menu? Or you do not want to force effects to all applications? In that case keep `Process All Outputs` enabled and blocklist the applications for which you do not want effects.

>So I go to enable the filters for an app, and it works. However it can't be switched back off.

This is strange. I tested now with mpv and chromium and the switch is working as usual. If I enable it stays enabled and if I disable it stays disabled unless I restart the application. In this case `Process All Outputs` will apply effects to it again.

>Also, when switching an app to disabled and muting it, the switch goes back to enabled.

At least with chromium and mpv I could not reproduce this.

>The blocklist also has no effect.

Somehow I also can not reproduce that.

**Comment by wwmm** [comment]
>The apps I tested this with were Spotify, Discord and Firefox.

Ok. Only now I saw that. I will try with Spotify and Firefox.

**Comment by wwmm** [comment]
No problems with Spotify... I don't know what is happening on your computer...

**Comment by Digitalone1** [comment]
> The apps seem to be kept in the blocklist just fine, but the filters are still always enabled (after enabling once) even if the app is in the list and/or the switch is disabled.
> 
> So there must be something not visible in the UI that's not switching filters off per app, or that fails in doing so.

I thought you mean the en/disable switch of the app instance, but the plugins should not be automatically disabled when the app is toggled.

Anyway you still could en/disable the plugins whenever the app is blocklisted/disabled.

**Comment by wwmm** [comment]
In your logs I see
```
compiled with pipewire: 0.3.20
linked to pipewire: 0.3.21
core version: 0.3.21
```

Could it be the fact that PulseEffects was not recompiled with the current PipeWire version installed?  I usually recompile PulseEffects after a PipeWire update. Maybe that is why I do not see the problem

**Comment by wwmm** [comment]
>I tested now with mpv and chromium and the switch is working as usual. If I enable it stays enabled and if I disable it stays disabled unless I restart the application

And effects are turned on/off accordingly.

**Comment by quietvoid** [comment]
I have tried reinstalling PE but it never recompiles when installing from the Arch community repo.
Maybe that package needs to be updated?

I just installed the -git version, restarted pipewire and it does the same thing. :(
Tested with mpv as well.

**Comment by quietvoid** [comment]
> Anyway you still could en/disable the plugins whenever the app is blocklisted/disabled.
When the app is blocklisted, the switched is forced disabled but the filters are still applied.
Is this normal behavior?

**Comment by wwmm** [comment]
>Another thing I notice is that PE reenables the switch when Spotify playback is paused.

There are some differences in how Pulseaudio and PipeWire report the stream state. Sometimes I see Spotify switch disabled but as soon as it resumes playback the switch state is correctly updated to enabled. As I have `Process All Outputs` enabled this final state is the correct one.

What do you see in Pavucontrol? When the switch is enabled the application stream should be playing to our virtual sink. And when it is off the application should be connected to your sound card.

**Comment by wwmm** [comment]
>When the app is blocklisted, the switch is forced disabled but the filters are still applied.
Is this normal behavior?

No. No effects should be applied to a blocklisted application. The plugins checkbox that are enabled will remain enabled. But the application sound won't be processed.

**Comment by wwmm** [comment]
> sometimes get hard hangs that force me to kill PE

As far as I can see there is only one thing that causes a hang on my computer. Trying to reset the settings while our playback pipeline is active. I have to investigate that. Resetting the settings when all apps are paused is fine.

**Comment by quietvoid** [comment]
> What do you see in Pavucontrol? When the switch is enabled the application stream should be playing to our virtual sink. And when it is off the application should be connected to your sound card.

In pavucontrol, I can switch the app to use the sound card and that works.
PE also reflects the changes by changing the state of the app switch.

So I enable the filters for the app again, and pavucontrol shows it changing to `PulseEffects Sink` and the filters work.
When I try disabling the app through PE again, the sink doesn't change. It remains on PulseEffects Sink.

**Comment by wwmm** [comment]
>When I try disabling the app through PE again, the sink doesn't change. It remains on PulseEffects Sink.

That is not right. I wonder why PipeWire is not allowing the change in the opposite direction...

**Comment by wwmm** [comment]
I decided to take a look at my logs and now I see that there is something strange in yours. After disabling and enabling Spotify I get this
```
pipe_manager: new metadata property: 145, target.node, Spa:Id, 41
pipe_manager: spotify port 100 is connected to alsa_output.pci-0000:0e:00.4.iec958-stereo port 46
pipe_manager: spotify port 103 is connected to alsa_output.pci-0000:0e:00.4.iec958-stereo port 48
pipe_manager: new metadata property: 145, target.node, Spa:Id, 58
pipe_manager: spotify port 103 is connected to pulseeffects_sink port 77
pipe_manager: spotify port 132 is connected to pulseeffects_sink port 50
```

`41` is the id of my sound card and `58` is the id of `pulseeffects_sink`. In you logs sometimes there is a id `0` being used as target. That does not make sense... I do no think any card can have `0` as id.

**Comment by wwmm** [comment]
In your logs your sound card has id `38`. But there is also `using output device: 0`. Something is broken somewhere. I am not sure where yet. If in PulseEffects or in PipeWire...

**Comment by wwmm** [comment]
What is the output of the command `pw-cat -p --list-targets` in your computer?

**Comment by quietvoid** [comment]
```
pw-cat -p --list-targets
Available targets ("*" denotes default): -1
*	38: description="Starship/Matisse HD Audio Controller Analog Stereo" prio=945
	54: description="PulseEffects Sink" prio=-1
```
I was just about to send the whole `pw-cli dump` output, which has `pipewire-0` as id 0.

**Comment by wwmm** [comment]
> I was just about to send the whole pw-cli dump output, which has pipewire-0 as id 0.

I think the dump won't be necessary. I have an idea of what is going on. The current implementation in PulseEffects rely on PipeWire emitting a signal in our startup phase where the current default input and output devices are sent. It always does that on my computer. But maybe in your hardware that is not the case.

Try the following test. While PulseEffects is running open Pavucontrol and set `PulseEffects Sink` as default. Right after that set your sound card again as default device. This should force the signal to be emitted. Now test the per application switch and see if there is any difference.

**Comment by quietvoid** [comment]
That seems to have fixed it!

```
pipe_manager: new metadata property: 0, default.audio.sink, Spa:Id, 38
new default sink: alsa_output.pci-0000:0b:00.4.analog-stereo
soe: NULL -> VOID_PENDING
soe: using output device: 38
sie: webrtc probe is using input device: 38
soe: NULL -> READY -> PLAYING
soe: READY -> PAUSED -> PLAYING
soe: sampling rate: 48000 Hz
soe: total latency: 30 ms
soe: PAUSED -> PLAYING -> VOID_PENDING
soe: total latency: 30 ms
pipe_manager: new metadata property: 88, target.node, Spa:Id, 38
pipe_manager: spotify port 48 is connected to alsa_output.pci-0000:0b:00.4.analog-stereo port 40
pipe_manager: spotify port 114 is connected to alsa_output.pci-0000:0b:00.4.analog-stereo port 42
pipe_manager: new metadata property: 88, target.node, Spa:Id, 50
pipe_manager: spotify port 114 is connected to pulseeffects_sink port 87
pipe_manager: spotify port 68 is connected to pulseeffects_sink port 64
pipe_manager: new metadata property: 88, target.node, Spa:Id, 38
pipe_manager: spotify port 68 is connected to alsa_output.pci-0000:0b:00.4.analog-stereo port 40
pipe_manager: spotify port 80 is connected to alsa_output.pci-0000:0b:00.4.analog-stereo port 42
soe: No app wants to play audio. We will stop our pipeline.
pipe_manager: new metadata property: 88, target.node, Spa:Id, 50
pipe_manager: spotify port 80 is connected to pulseeffects_sink port 87
pipe_manager: spotify port 48 is connected to pulseeffects_sink port 64
```

Maybe this happened because I recently switched motherboard, and didn't reconfigure anything regarding audio.
Thank you!

**Comment by wwmm** [comment]
>That seems to have fixed it!

Permanently? Try a reboot and see if things are still working. Maybe the signal is supposed to always be emitted when a client connects but it wasn't happening because of a default was never set. in this case it is a PipeWire bug I will report to its developer.

**Comment by quietvoid** [comment]
Yes it has persisted after a reboot, the switch works well.

**Comment by wwmm** [comment]
Bug report on PipeWire's page https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/682. Let's see if that signal is supposed to always be emitted or not.

**Comment by quietvoid** [comment]
Hmm, this issue seems to be back after updating to Pipewire 0.3.24.
Now changing the fallback with `pavucontrol` makes no difference.

```
> pw-cat -p --list-targets
Available targets ("*" denotes default): alsa_output.pci-0000_0d_00.4.analog-stereo
*	48: description="Starship/Matisse HD Audio Controller Analog Stereo" prio=881
	78: description="PulseEffects Sink" prio=-1
```

In the debug log when switching an app on/off:
```
(pulseeffects:11489): pulseeffects-DEBUG: 10:41:34.602: pipe_manager: new metadata property: 94, target.node, Spa:Id, 0
(pulseeffects:11489): pulseeffects-DEBUG: 10:41:36.112: pipe_manager: new metadata property: 94, target.node, Spa:Id, 78
(pulseeffects:11489): pulseeffects-DEBUG: 10:42:35.054: pipe_manager: new metadata property: 94, target.node, Spa:Id, 0
(pulseeffects:11489): pulseeffects-DEBUG: 10:42:36.314: pipe_manager: new metadata property: 94, target.node, Spa:Id, 78
```

**Comment by wwmm** [comment]
I can reproduce this issue. Things have changed in the latest PipeWire release. I will have to prepare an update today.

**Comment by wwmm** [comment]
Release `5.0.3' fixes the issues for me. Test it when possible.

**Comment by quietvoid** [comment]
Seems to be fixed for me as well, thanks!
