### ISSUE TITLE
Pulseeffects suddenly stopped playing

### ISSUE THREAD

**Issue by gabrielnemeth** [wwmm/pulseeffects#897]
New linux user here. I'm using PulseEffects for weeks now without an issue, but today it stopped working completely. It displays that application produces audio but I can't hear nothing and also the equalizer part of the app is not animating like usually. I've tried to reinstalling it without a luck. I saw few post there that some users have issues with locales, but I guess mine are fine:

```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```

![pulse](https://user-images.githubusercontent.com/11211316/107085739-2fb76d80-67f9-11eb-8449-049caf5f3d23.png)

I'm on pop_os 20.04 and I'm using PulseEffect 4.7.1. Installed with: `sudo apt install pulseeffects`

**Comment by wwmm** [comment]
Based on your image I would say that PulseEffects pipeline is playing. There were cases in the past where the users fixed problems like this removing Pulseaudio configuration folder `rm -rf ~/.config/pulse/` and rebooting. Sometimes it seems the files in this folder get corrupt somehow.

**Comment by gabrielnemeth** [comment]
Thank you @wwmm everything works now!
