### ISSUE TITLE
Issue getting Pulseeffect running on Opensuse

### ISSUE THREAD

**Issue by Mirppc** [wwmm/pulseeffects#9]
Now this likely could be a PEBKAC issue but i cannot seem to get this awesome looking program setup on opensuse.  It is not in any of the repos nor is it in OpenbuildService ;-;

Current machine being used, Dell Prescision P690 with Opensuse leap 42.2 installed.  All the dependencies where install per the readme.md.  (thanks for the great dependency list :+1: )

Here is what i have done thus far. (i use ~/bin for compiling stuff)

`:~/bin> git clone https://github.com/wwmm/pulseeffects.git
Cloning into 'pulseeffects'...
remote: Counting objects: 595, done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 595 (delta 108), reused 0 (delta 0), pack-reused 394
Receiving objects: 100% (595/595), 2.53 MiB | 1.90 MiB/s, done.
Resolving deltas: 100% (321/321), done.

:~/bin> cd pulseeffects/
:~/bin/pulseeffects> ls
equal_loudness_countours  images  LICENSE.md  MANIFEST.in  po  pulseeffects  PulseEffects  README.md  setup.py  share
:~/bin/pulseeffects> setup.py
If 'setup.py' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf setup.py
:~/bin/pulseeffects> ./setup.py
bash: ./setup.py: Permission denied
:~/bin/pulseeffects> sudo ./setup.py
root's password:
sudo: ./setup.py: command not found
:~/bin/pulseeffects> python setup.py
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    os.makedirs(locale_dir, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
:~/bin/pulseeffects> sudo python setup.py
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    os.makedirs(locale_dir, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
:~/bin/pulseeffects> ./pulseeffects 
Traceback (most recent call last):
  File "./pulseeffects", line 4, in <module>
    from PulseEffects.application import Application
  File "/home/mirp690/bin/pulseeffects/PulseEffects/application.py", line 3, in <module>
    import configparser
ImportError: No module named configparser
:~/bin/pulseeffects> nano README.md 
:~/bin/pulseeffects> sudo glib-compile-schemas /usr/share/glib-2.0/schemas/.
root's password:
:~/bin/pulseeffects> pulseeffects
If 'pulseeffects' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf pulseeffects
:~/bin/pulseeffects> ./pulseeffects
Traceback (most recent call last):
  File "./pulseeffects", line 4, in <module>
    from PulseEffects.application import Application
  File "/home/mirp690/bin/pulseeffects/PulseEffects/application.py", line 3, in <module>
    import configparser
ImportError: No module named configparser
`

I hope this helps.  I really am looking forward to this program running.  Also ignore the crossout's.

**Comment by wwmm** [comment]
Hi

You may try running PulseEffects from the cloned folder. Once in the pulseeffects folder do the following:

glib-compile-schemas share/glib-2.0/schemas/

GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects

With this you can run PulseEffects without installing it. I will add this to the readme.

Thanks for testing :) I hope someone makes a package for opensuse. I use Arch Linux and have no idea about how to do packages for other distributions

**Comment by Mirppc** [comment]
Thanks will test this shortly.  Here are some links i think will help you when it comes to packaging for other distros.

http://openbuildservice.org/  This tool is useful for building packages for multiple distros.

https://wiki.archlinux.org/index.php/Creating_packages_for_other_distributions#openSUSE  Look like it is available on ARCH.

I hope this helps :)

**Comment by wwmm** [comment]
Interesting. I will take a look. About the error:

ImportError: No module named configparser

You will need to install the python package configparser

**Comment by wwmm** [comment]
Another option would be to upgrade to a python version higher than 3.5.0. At least in Arch Python 3.6 comes with configparser

**Comment by Mirppc** [comment]
Tried agian with some help from a socal python member.  my default python is 2.7 but i have python 3 installed.

```~/bin/pulseeffects> python3 setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/lib/python3.4/site-packages/test-easy-install-18248.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/lib/python3.4/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

~/bin/pulseeffects> sudo python3 setup.py install
root's password:
running install
running bdist_egg
running egg_info
creating PulseEffects.egg-info
writing PulseEffects.egg-info/PKG-INFO
writing dependency_links to PulseEffects.egg-info/dependency_links.txt
writing top-level names to PulseEffects.egg-info/top_level.txt
writing manifest file 'PulseEffects.egg-info/SOURCES.txt'
reading manifest file 'PulseEffects.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'PulseEffects.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/PulseEffects
copying PulseEffects/libpulse.py -> build/lib/PulseEffects
copying PulseEffects/application.py -> build/lib/PulseEffects
copying PulseEffects/pulse_manager.py -> build/lib/PulseEffects
copying PulseEffects/gst.py -> build/lib/PulseEffects
copying PulseEffects/__init__.py -> build/lib/PulseEffects
creating build/lib/PulseEffects/ui
copying PulseEffects/ui/about.glade -> build/lib/PulseEffects/ui
copying PulseEffects/ui/about_icon.png -> build/lib/PulseEffects/ui
copying PulseEffects/ui/headerbar.glade -> build/lib/PulseEffects/ui
copying PulseEffects/ui/main_ui.glade -> build/lib/PulseEffects/ui
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/PulseEffects
creating build/bdist.linux-x86_64/egg/PulseEffects/ui
copying build/lib/PulseEffects/ui/main_ui.glade -> build/bdist.linux-x86_64/egg/PulseEffects/ui
copying build/lib/PulseEffects/ui/about.glade -> build/bdist.linux-x86_64/egg/PulseEffects/ui
copying build/lib/PulseEffects/ui/headerbar.glade -> build/bdist.linux-x86_64/egg/PulseEffects/ui
copying build/lib/PulseEffects/ui/about_icon.png -> build/bdist.linux-x86_64/egg/PulseEffects/ui
copying build/lib/PulseEffects/libpulse.py -> build/bdist.linux-x86_64/egg/PulseEffects
copying build/lib/PulseEffects/application.py -> build/bdist.linux-x86_64/egg/PulseEffects
copying build/lib/PulseEffects/pulse_manager.py -> build/bdist.linux-x86_64/egg/PulseEffects
copying build/lib/PulseEffects/gst.py -> build/bdist.linux-x86_64/egg/PulseEffects
copying build/lib/PulseEffects/__init__.py -> build/bdist.linux-x86_64/egg/PulseEffects
byte-compiling build/bdist.linux-x86_64/egg/PulseEffects/libpulse.py to libpulse.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/PulseEffects/application.py to application.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/PulseEffects/pulse_manager.py to pulse_manager.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/PulseEffects/gst.py to gst.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/PulseEffects/__init__.py to __init__.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.4
copying and adjusting pulseeffects -> build/scripts-3.4
changing mode of build/scripts-3.4/pulseeffects from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.4/pulseeffects -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/pulseeffects to 755
copying PulseEffects.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PulseEffects.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PulseEffects.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PulseEffects.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PulseEffects.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/PulseEffects-1.2.5-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing PulseEffects-1.2.5-py3.4.egg
creating /usr/lib/python3.4/site-packages/PulseEffects-1.2.5-py3.4.egg
Extracting PulseEffects-1.2.5-py3.4.egg to /usr/lib/python3.4/site-packages
Adding PulseEffects 1.2.5 to easy-install.pth file
Installing pulseeffects script to /usr/bin

Installed /usr/lib/python3.4/site-packages/PulseEffects-1.2.5-py3.4.egg
Processing dependencies for PulseEffects==1.2.5
Finished processing dependencies for PulseEffects==1.2.5
~/bin/pulseeffects> python3 pulseeffects

(pulseeffects:18265): GLib-GIO-ERROR **: Settings schema 'com.github.wwmm.pulseeffects' is not installed

Trace/breakpoint trap (core dumped)
~/bin/pulseeffects> ```

**Comment by wwmm** [comment]
This error is expected as the setup.py script does not copy the contents of the share folder to the corresponding folder inside /usr/share. Python setuptools documentaion disabled this feature and recommends to perform this task using the distribution package manager.

After copying the files remember to run:

glib-compile-schemas /usr/share/glib-2.0/schemas/

**Comment by Mirppc** [comment]
```~/bin/pulseeffects> sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
root's password:
~/bin/pulseeffects> python3 pulseeffects

(pulseeffects:18446): GLib-GIO-ERROR **: Settings schema 'com.github.wwmm.pulseeffects' is not installed

Trace/breakpoint trap (core dumped)
```

that didnt work :<  Thanks for the spiffy responses.

**Comment by wwmm** [comment]
When trying to run from the cloned folder do the:

glib-compile-schemas share/glib-2.0/schemas/
chmod +x pulseeffects
GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ python3 pulseeffects

**Comment by wwmm** [comment]
The first two commands are only needed once

**Comment by Mirppc** [comment]
Thanks, i was able to get it running, everytime i tried using an audio stream it would take the audio from the USB headset (that needs to have the equalizer) and puts the audio on the default line out from the onboard audio card.  

This was a bit annoying.  Not sure if i sould make a new bug report on that.  It does run though :), i did get some reverb though.

**Comment by wwmm** [comment]
Hi, I am glad it is working :-) By default PulseEffects detects the current pulseaudio default output sink and uses it for sound output. By what you are telling me it seems that your pulseaudio server is configured to use the onboard sound as default output sink. You may try to use pavucontrol (or gnome settings if you use gnome) to set the usb headset as default output device. 

As it is working I will close this issue
