### ISSUE TITLE
Window resizes on track change

### ISSUE THREAD

**Issue by bretter** [wwmm/pulseeffects#90]
![screencast from 10-07-2017 05-04-17 pm](https://user-images.githubusercontent.com/5185415/31311825-91b1e722-ab82-11e7-85af-9c6ebc580b1b.gif)

Problem: PulseEffects window snaps back to it's default height when a track is skipped in Lollypop.

Steps to reproduce:
1) increase the height of the PulseEffects window by dragging the bottom edge down
2) play any track in Lollypop
3) skip to the next track

Other observations: This does not happen when a track naturally progresses to the next track.

Attached: gif shows a natural track progression first, then a skipped track

System information: Arch Linux - Gnome 3.26 - Lollypop 0.9.244 - PulseEffects 3.0.0

**Comment by wwmm** [comment]
In order to find a proper solution to this issue I have to learn more about gtk widgets resizing. Right now what I do is resizing the whole window when a audio application is removed(It really annoys me when the window stays large after a application is removed).

From Pulseaudio's point of view the applications shown in PulseEffects window are sink inputs. For some reason lollypop is building a new sink input whenever a track is skipped. There is nothing I can do about that.

The ideal solution here would be to find a way to shrink a gtk box height to its minimum necessary size when one of its children is removed. But up to now I could not find a way. So I am resizing the main window to its "natural size". In this process the apps_box is shrinked.

**Comment by wwmm** [comment]
Maybe what I can do is detecting when a user manually resizes the window and then disabling the automatic resize when apps are removed

**Comment by bretter** [comment]
What if you detect the manual resize and store that value. Then, instead of resizing to the natural size when an audio application is removed (like you are doing now) you resize to the manually set size?

**Comment by wwmm** [comment]
I think this would work but detecting a user resize in gtk is harder than I thought. Connecting to the `configure-event` I am notified about changes in window size but I have no information about their source. I tried to use button press/release events to identify user resize but for some reason the release event is not called on the window border...

**Comment by wwmm** [comment]
Something that would be easy to do is adding a command line option to disable the automatic window resizing when an app is added removed. Would this be enough?

**Comment by bretter** [comment]
Being able to toggle it manually should do it.

Instead of a command line option, might it make sense to add that to the settings panel?

**Comment by wwmm** [comment]
I could add this to the main menu. No problems. But I am wondering if it wouldn't be better to rework the way audio applications are shown in the main window. Usually people don't have more than 2 or 3 audio applications open. But if they do the window can become very big and ugly...

 Maybe it would be better to have the audio apps list in a tab as we already do for each effect. This way there will be no need to resize the window when apps are removed from the list.

**Comment by bretter** [comment]
I think that it is odd for the size of a window to change absent of direct user interaction (whether growing or shrinking). 

Your idea of placing the active sinks into the main window would certainly solve this problem!

Another possibility might be to add keep the active sinks section at the bottom but keep it bound by the size of the window by adding scrolling to that element. Include space for at least 1 or 2 active sinks in the 'natural' size of the window and have a scroll bar appear after the max size has been exceeded. The main window would never have to grow or shrink.

I think both approaches have positives and negatives. I like having the sinks persistent because it makes toggling app volumes very convenient. However I could see an argument against increasing the minimum size of PulseEffects too.

**Comment by wwmm** [comment]
latest master has a new interface that should not have resize problems

![screenshot from 2017-10-13 11-57-04](https://user-images.githubusercontent.com/16225172/31552462-f8687bf4-b00d-11e7-8aed-3f3a1d76ea7f.png)

**Comment by bretter** [comment]
Working great here!
