### ISSUE TITLE
Input mic is showing as a output in manjaro 5.10 kernel with pulse audio and lasted pulseEffect legacy

### ISSUE THREAD

**Issue by Yato202010** [wwmm/pulseeffects#902]
i have a razer nari ultimate and i have a patch installed to show both output of my headset ( one for chat and one for gaming ) 

with pulse Effect my input mic switch to a output device this is very annoying i had to uninstall pulse effect to revert it back 
i don't know if this bug is the same on other device

acer nitro 5 an512-42 
manjaro kernel 5.10.15.1-manjaro

pulseeffects-legacy 4.8.4-3
razer-nari-pumseaudio-profile 20210210-0 
no other module related to pulseaudio no installed by default

**Comment by wwmm** [comment]
>with pulse Effect my input mic switch to a output device

Something else is going on. It is not possible to convert a Pulseaudio input device to an output device. Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects` so we can see some logs.

**Comment by Yato202010** [comment]
ok after some diging for some reason the package from the official community source have this bug but installing the package from the aur repository work ( the pulseeffects-legacy-git 4.8.4.r11.gd0b5599c-1 ) so i will close this issues this look like more of a unwanted operation made by me than a bug
