### ISSUE TITLE
Crystalizer often not working correctly

### ISSUE THREAD

**Issue by DeeBeeDouble** [wwmm/pulseeffects#908]
If I activate the Crystalizer everything after a short time sounds very strange when I start a new sound (for example click on a video or pause and then continue the video). It sounds like a gun or something like that. I can't really describe it. Everything is also very delayed. If I turn it off everything will go back to normal. This is really annoying and i dont know how to fix that. First i tried reinstall everything (Pulseeffects, LSP-Plugins, Pipewire) but it didn't help. Than I even reinstalled Manjaro and everything else but it still didn't work. It has only appeared since version 5. Please help me. If you need any additional information just ask. This is my first bug report so sorry for all mistakes. Also my main Language isn't english so please don't be angry if i make mistakes because i'm not very good at english. Thanks for all help.

**Comment by wwmm** [comment]
Strange. I use this plugin everyday and so far nothing unusual. But as this plugin is among the few that add latency and PipeWire does automatic latency adjustments this is where something may be going wrong. Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. If this is latency related a print of the output of the command `pw-top` may also help.

**Comment by DeeBeeDouble** [comment]
Okay I started it in debug mode and now the issue accours imidiantly and not just after for example click on a new video. I can click on crystalizer in debug mode and the strange sound appears imidiantly. Here is the output while no Pulseeffects running and sound in the background:
(I cant just copy it because it keeps changing so fast that is is nearly impossible so here is a screenshot)
![No Pulseeffects with sound in background](https://user-images.githubusercontent.com/78625950/109714688-034a0380-7ba3-11eb-9b90-8537703006de.png)
Here is a screenshot with sound in background, Pulseeffects enabled and crystalizer disabled:
![Pulseeffects without Crystalizer](https://user-images.githubusercontent.com/78625950/109715531-08f41900-7ba4-11eb-9e78-5ff0fddc6eb3.png)
And here is a Screenshot when i hear the strange sound:
![Pulseeffects with error](https://user-images.githubusercontent.com/78625950/109715763-52dcff00-7ba4-11eb-8f73-7981ec0f57f0.png)
Hopefully that helps a little.

**Comment by DeeBeeDouble** [comment]
Also i noticed just right now that the option Convolver has exactly the same effect.

**Comment by DeeBeeDouble** [comment]
It seems that the bug after the last update 5.0.1 that I got a few hours ago is strangely no longer there. Thank you for any help and feel free to continue this cool project :D

**Comment by wwmm** [comment]
Strange. If it comes back feel free to reopen this issue.
