### ISSUE TITLE
Not finding rnnoise

### ISSUE THREAD

**Issue by roberttucker** [wwmm/pulseeffects#910]
On Fedora 33:

Dependency gstreamer-controller-1.0 found: YES 1.18.2 (cached)
Dependency gstreamer-audio-1.0 found: YES 1.18.2 (cached)
Found CMake: /usr/bin/cmake (3.18.4)
Run-time dependency rnnoise found: NO (tried pkgconfig and cmake)
Message: could not find the RNNoise library
Program meson_post_install.py found: YES (/usr/bin/python3 /home/rt/Programs/PulseEffects/pulseeffects/meson_post_install.py)
Build targets in project: 14

Found ninja-1.10.2 at /usr/bin/ninja

$ ls /usr/local/lib
cmake  librnnoise.a  librnnoise.la  librnnoise.so  librnnoise.so.0  librnnoise.so.0.4.1  node_modules  pkgconfig  python3.7

**Comment by wwmm** [comment]
The rnnoise plugin is different from the others.  The rnnoise library has to be installed in the system at the moment the PulseEffects package is compiled. This is true both for our Pulseaudio and PipeWire release.

**Comment by roberttucker** [comment]
Methinks I'll have to give the Noise Reduction function a miss for the time being.

**Comment by roberttucker** [comment]
Finally succeeded with install after some help from Vasiliy and a  reddit thread.
https://copr.fedorainfracloud.org/coprs/rtfed/pulseeffects-rnnoise/

Seems to work better for crackly old 78 rpm records than old movies. With the latter it became very stuttery and variable, while Audacity working on the stripped soundtrack does quite a good job.

What's the position python3-keras? Is it or a substitute included in PulseEffects or RNNoise somewhere?

**Comment by wwmm** [comment]
>What's the position python3-keras?

I have never used it. In https://github.com/xiph/rnnoise there is a script that they use for training. Maybe it can generate a file that could be imported. At least the ones created as explained at https://github.com/GregorR/rnnoise-models can be imported in PulseEffects.

**Comment by Vascom** [comment]
rnnoise will be in Fedora soon. Pulseeffects build will support it too.

**Comment by Vascom** [comment]
Issue can be closed?

**Comment by wwmm** [comment]
Probably.
