### ISSUE TITLE
Plugins won't affect audio unless disabled and enabled after boot or reconnection.

### ISSUE THREAD

**Issue by kalebealvs** [wwmm/pulseeffects#938]
I set pulseeffects to load on boot, then enabled some plugins for both input and output. At this point, everything works fine. After rebooting(sometimes when  reconnecting the device in use, headset, mic, or both), the enabled plugin for each device type keeps marked as enabled, but they make no difference at all to the audio. It's only when I disable and enable each plugin, that it really affects the audio. And I have to do that every boot, every reconnection, for every plugin on both input and output.

I use pulseeffects with pipewire on arch. Before migrating to pipewire, this didn't happen.

#### installed packages
```
$ pacman -Qs pipewire | grep -i local
local/gst-plugin-pipewire 1:0.3.23-1
local/pipewire 1:0.3.23-1
local/pipewire-media-session 1:0.3.23-1
local/pipewire-pulse 1:0.3.23-1
local/pulseeffects 5.0.1-1

$ pacman -Qs pulseeffect | grep -i local
local/pulseeffects 5.0.1-1
```

I also tried to get some error messages but I don't know where to look. pipewire and pipewire-pulse systemd user unit does not report any error or warning besides this for firefox, which isn't even the software I used for testing.
```
$ journalctl --user -u pipewire-pulse
-- Boot 632229bfc09f43e68455e5c6a2ac3382 --
abr 01 11:35:05 death-star systemd[1458]: Started PipeWire PulseAudio.
abr 01 11:49:15 death-star pipewire-pulse[1475]: send channel:-1 83, res -1: Broken pipe
abr 01 13:22:35 death-star pipewire-pulse[1475]: pulse-server 0x5624086d96c0: [Firefox] UNDERFLOW channel:1 offset:761856 underrun:8192
abr 01 13:24:11 death-star pipewire-pulse[1475]: 1 events suppressed
abr 01 13:24:11 death-star pipewire-pulse[1475]: pulse-server 0x5624086d96c0: [Firefox] UNDERFLOW channel:3 offset:805328 underrun:7528
```

keep in mind that I tested the audio right after boot, so that broken pipe is probably unrelated as well.

Is this a misconfiguration? Doesn't seem to be, but I might as well have missed something.

**Comment by wwmm** [comment]
>Is this a misconfiguration?

No. It is probably the same as #903. Check if you have `dconf 0.40` installed. It the answer is yes you will need to upgrade to PulseEffects to at least `5.0.2`.

**Comment by IdreesM0** [comment]
I have been having this issue for a few days after upgrading manjaro. I do have dconf 0.40. Is there a work around for this. I have tried switching to pipewire but reverted back to pulseaudio for now because I somehow couldn't get it to work. Plus as of now it lacks a lot of configuration options (or perhaps I lack the knowledge of it) compared to pulseaudio.

**Comment by wwmm** [comment]
>Is there a work around for this

Upgrading PulseEffects is the only way. Switching between Pulseaudio and PipeWire won't solve it because both releases had the same bug. For both of them the users need our latest release for each branch. In Pulseaudio upgrading to `4.8.5` is needed.

**Comment by kalebealvs** [comment]
I can confirm that the problem does not happen on 5.0.3 as well.
