### ISSUE TITLE
Failed to get required plugin: spectrum

### ISSUE THREAD

**Issue by UserCommon** [wwmm/pulseeffects#943]
(pulseeffects:57800): pulseeffects-WARNING **: 16:58:05.302: pipe_manager: Remote error on id:30

(pulseeffects:57800): pulseeffects-WARNING **: 16:58:05.302: pipe_manager: Remote error message:enum params id:2 (Spa:Enum:ParamId:Props) failed

(pulseeffects:57800): pulseeffects-WARNING **: 16:58:05.302: pipe_manager: Remote error on id:31

(pulseeffects:57800): pulseeffects-WARNING **: 16:58:05.302: pipe_manager: Remote error message:enum params id:2 (Spa:Enum:ParamId:Props) failed

** (pulseeffects:57800): ERROR **: 16:58:05.314: 
unhandled exception (type std::exception) in signal handler:
what: soe: Failed to get required plugin: spectrum

[1]    57800 trace trap (core dumped)  pulseeffects

Help, i don't understand what spectrum is and where i can found him.

**Comment by wwmm** [comment]
You are probably missing one of the required dependencies. If I am not mistaken the spectrum plugin comes with the `gst-plugins-good` library.

**Comment by UserCommon** [comment]
Oh, wow, reinstaled this lib and this helped, thanks a lot.
