### ISSUE TITLE
Sound not playing from subwoofer when cart profile is changed

### ISSUE THREAD

**Issue by susonthapa** [wwmm/pulseeffects#953]
So I have this problem where sound wouldn't play from subwoofer when I set the card profile to `output:analog-surround-21+input:analog-stereo`. If I turn off pulseeffects then the sound plays normally through the subwoofer. If I set the card profile to `output:analog-stereo+input:analog-stereo` then the audio plays through subwoofer even when pulseeffects is enabled. 

I have removed all pipewire and pulseeffects related config from `/etc/pipwire`,  `.config/pipewire`, `.config/Pulseeffects` and reinstalled both. But the problem is still there. By the way I'm using `pipewire-pulse`.

Here is my `pipewire-pulse.conf`
```
# PulseAudio config file for PipeWire version "0.3.26" #

context.properties = {
    ## Configure properties in the system.
    #mem.warn-mlock  = false
    #mem.allow-mlock = true
    #mem.mlock-all   = false
    #log.level       = 2
}

context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}

context.modules = [
    {   name = libpipewire-module-rtkit
        args = {
            #nice.level   = -11
            #rt.prio      = 88
            #rt.time.soft = 200000
            #rt.time.hard = 200000
        }
        flags = [ ifexists nofail ]
    }
    {   name = libpipewire-module-protocol-native }
    {   name = libpipewire-module-client-node }
    {   name = libpipewire-module-adapter }
    {   name = libpipewire-module-metadata }

    {   name = libpipewire-module-protocol-pulse
        args = {
            # the addresses this server listens on
            server.address = [
                "unix:native"
                # "tcp:4713"
            ]
            #pulse.min.req = 256/48000              # 5ms
            #pulse.default.req = 960/48000          # 20 milliseconds
            #pulse.min.frag = 256/48000             # 5ms
            #pulse.default.frag = 96000/48000       # 2 seconds
            #pulse.default.tlength = 96000/48000    # 2 seconds
            #pulse.min.quantum = 256/48000          # 5ms
            #pulse.default.format = F32
            pulse.default.position = [ FL FR LFE ]
            # These overrides are only applied when running in a vm.
            vm.overrides = {
                pulse.min.quantum = 1024/48000         # 22ms
            }
        }
    }
]

stream.properties = {
    #node.latency = 1024/48000
    #node.autoconnect = true
    #resample.quality = 4
    channelmix.normalize = true
    channelmix.mix-lfe = true
    channelmix.upmix = true
    channelmix.lfe-cutoff = 250
}
```
Also I don't know why the `channelmix.lfe-cutoff` is not working, as I thought it would only play frequencies below 250Hz from the subwoofer but the subwoofer is playing all the frequencies. 

Previously I was using **pulseeffects-legacy** as I had faced these issues. Today I thought of trying `pipewire` with `pulseeffects` to see if the issues have been resolved but I'm still facing these issues. Though the stability has improved significantly. 

Please can anyone help me ?

**Comment by wwmm** [comment]
>I set the card profile to output:analog-surround-21+input:analog-stereo

As PulseEffects is a stereo application it will send audio to the front-left and front-right channels. PipeWire is the one responsible for the downmixing to the subwoofer channel. I wonder why it does not do that when we are running. Our playback stream stream is just like any other stereo GStreamer application playback stream.

PipeWire's developers are also in a better position to answer about the `lfe-cutoff`. As my system is stereo I did not play with this option yet. I suggest you open an issue there https://gitlab.freedesktop.org/pipewire/pipewire/-/issues. I n case some technical information is need about PulseEffects I can comment there.

**Comment by susonthapa** [comment]
Thank you for pointing me to the right direction. I am closing this issue and thanks for such awesome software. It provides such a great audio experience in linux.
