### ISSUE TITLE
Convolver: "Could Not Load the Impulse File"

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [wwmm/pulseeffects#954]
![Screenshot from 2021-04-26 10-18-48](https://user-images.githubusercontent.com/28505034/116020446-d84ad000-a678-11eb-9b43-c05a11cf5205.png)

![Screenshot from 2021-04-26 10-16-00](https://user-images.githubusercontent.com/28505034/116020386-bf421f00-a678-11eb-9cd1-54de1e7d13a4.png)

**Comment by wwmm** [comment]
`4.7.1` is very old. I suggest you upgrade to a newer release. In any case did you import an impulse file? As they usually have copyrights we can not include them in our sources.
