### ISSUE TITLE
Input processing does not occur for web browsers

### ISSUE THREAD

**Issue by eiglow** [wwmm/pulseeffects#957]
I observed this in both Chrome and Firefox.

[Debug-mode terminal output](https://github.com/wwmm/pulseeffects/files/6409614/pulseeffects.log), testing with Firefox, attempting to record something with https://online-voice-recorder.com/. I have several microphone effects which normally work fine in Discord, but they don't seem to activate for web browser inputs.

Pulseeffects version: 5.0.3
Pipewire version: 0.3.26
Distribution: Fedora 34
Desktop environment: KDE Plasma 5.21.4 Wayland session
[`pactl list short` output](https://github.com/wwmm/pulseeffects/files/6409618/pactl-list-short.log)
[Pulseffects settings](https://github.com/wwmm/pulseeffects/files/6409626/pesettings.txt)

Also another thing. It might be worth updating [this](https://github.com/wwmm/pulseeffects/wiki/Reporting-Bugs) wiki page for Pipewire, because a lot of the commands seem pulseaudio-specific.

**Comment by wwmm** [comment]
Firefox developers decided to set a flag that does not allows us to move their microphone audio stream. In its case you have to use its mic selection window and set `PulseEffects Source` as input.

At least on Chromium I have no problems. I thought it and Chrome behaved the same in this regard.

>Also another thing. It might be worth updating this wiki page for Pipewire, because a lot of the commands seem pulseaudio-specific.

Yes. But I think I will do that after finishing the gtk4 port because some radical changes are being done in that branch.

**Comment by eiglow** [comment]
Just re-tested it in Chromium and I still hear the same lack of effects. but using Pulseffects Source (at least in Firefox where I tested that) is a good enough work-around for me, thanks. Up to you if you want to keep this issue open then.

**Comment by magicgoose** [comment]
Firefox apparently doesn't allow to _choose_ the microphone. It just shows the name of the device and you can either allow or deny.

**Comment by ISSOtm** [comment]
Interestingly, I am now getting the *opposite* problem, where selecting any microphone in Firefox ([you can use this test page](https://mozilla.github.io/webrtc-landing/gum_test.html)) is forcibly redirected to EasyEffects, and no way to change it in `pavucontrol`.

(Firefox 147.0.4, EE 8.1.2, Easy Effects: 8.1.2, PW 1.4.10, Arch Linux)

@magicgoose I do get a selection menu, I believe that Firefox doesn't show it when there's only a single mic (detected, anyway).

**Comment by wwmm** [comment]
>Interestingly, I am now getting the opposite problem, where selecting any microphone in Firefox ([you can use this test page](https://mozilla.github.io/webrtc-landing/gum_test.html)) is forcibly redirected to EasyEffects, and no way to change it in pavucontrol.

Even if you disable `Process all input streams` in EasyEffects preferences window? I would expect what you described when EasyEffects is handling what should or not be moved to its virtual device.
