### ISSUE TITLE
Annoying LSP launchers

### ISSUE THREAD

**Issue by rivanfebrian123** [wwmm/pulseeffects#959]
![Screenshot from 2021-05-05 13-21-08](https://user-images.githubusercontent.com/6300910/117103844-4b54f480-ada5-11eb-885e-93c24d69f584.png)
Hi! Is it possible to make a single app laucher for LSPs instead of those ones?

**Comment by wwmm** [comment]
>Hi! Is it possible to make a single app laucher for LSPs instead of those ones?

As I am not the author of Linux Studio Plugins I can not do that. I suggest you ask in LSP page https://github.com/sadko4u/lsp-plugins. What you may try is to put all of these icons in one folder like the `System Tools` in your image. But I think this won't help when searching for an app. The results will probably be polluted yet.

**Comment by wwmm** [comment]
Have in mind that LSP is not made for PulseEffects. It just happens it is useful for us too. But as it main target are audio engineers and musicians using `Jack` its author may have a good reason to add these launchers. Maybe the package maintainers should create a separate package for these icons.

**Comment by rivanfebrian123** [comment]
> > Hi! Is it possible to make a single app laucher for LSPs instead of those ones?
> 
> As I am not the author of Linux Studio Plugins I can not do that. I suggest you kindly ask in LSP page https://github.com/sadko4u/lsp-plugins. What you may try is to put all of these icons in one folder like the `System Tools` in your image. But I think this won't help when searching for an app. The results will probably be polluted yet.

Thanks for your hint! I'm working on it

> Maybe distributions package maintainers should create a separate package for these icons.

This is the hardest one :D
