### ISSUE TITLE
Linux Studio Plugins EQ: Custom Gain on Specific Band

### ISSUE THREAD

**Issue by Element21** [wwmm/pulseeffects#961]
I know this is not really a bug, but I don't know where else to go. Is there any way to set a custom gain value on an EQ band, without just sliding the slider up and down? Sorry if i'm just dumb!

**Comment by wwmm** [comment]
For now this is the only way. You can use the mouse scroll or the keyboard up/dow keys after clicking over the slider. But in all these cases you have to interact with the slider somehow.

**Comment by beliys** [comment]
You can also edit the preset file in any text editor.

**Comment by Element21** [comment]
Will do, Thanks for the info!
