### ISSUE TITLE
No microphone input 

### ISSUE THREAD

**Issue by kaanyalova** [wwmm/pulseeffects#964]
![Ekran görüntüsü 2021-05-10 15-44-37](https://user-images.githubusercontent.com/76952012/117661150-ab350c00-b1a6-11eb-948a-ae5e32c38d4b.png)
i used discord to test the mic 
when I am recording audio its also silent 
i tried pulseeffects-git from aur and same thing happens

**Comment by AshamedConsequence** [comment]
Can you tell if this bug is fixed? I'm having the exact same problem and I have no idea how to fix it.
