### ISSUE TITLE
Option to not add mic icon to top bar

### ISSUE THREAD

**Issue by AlexWayfer** [wwmm/pulseeffects#965]
Hello.

I was curious where is from in my GNOME top bar microphone icon volume.

And now I finally got it: PulseEffects (version 5.0.3).

When it doesn't work:

![image](https://user-images.githubusercontent.com/6510020/117803462-56a19780-b25f-11eb-9c3d-bd3b9829c398.png)

When I launch PE:

![image](https://user-images.githubusercontent.com/6510020/117803503-628d5980-b25f-11eb-825e-fcbda56fadb3.png)

I don't use any filters/plugins for input, and more I have 400% volume for mic, and sometimes when I try to scroll over output volume icon I miss and change input volume to 100%.

So, I'd like to not add this icon by PulseEffects. Is it possible? I didn't find something related in current settings and existing issues.

**Comment by AlexWayfer** [comment]
> Unfortunately GNOME and KDE developers decided it was a good thing to show a mic icon whenever an audio stream is recording something. Even if it is just a virtual device and not the user microphone =/.

Oh, shi, here we go again…

> I think this kind of thing won't happen anymore once our gtk4 branch is released. As PipeWire filters are being used instead of GStreamer the effects pipeline will be just a chain of filters and virtual devices. There won't be streams anymore.

I'd suggest to add this issue to #904 for closing after release, but I'm going to close it now, because, as I understood, even if #904 will not resolve this, we have no ability to do it in another way (except creating a GNOME's issue like "Please, add an option (API) to hide the mic icon").

**Comment by AlexWayfer** [comment]
Note: it's actually resolved with EE v6.

**Comment by wwmm** [comment]
Cool! I did not consider this problem would be closed by the new approach. But thinking about it now it makes sense. GNOME and KDE are blindly showing the mic icon when any stream is recording something even if it is not the microphone. But now that we are using PipeWire filters we do not have a stream anymore. We just link filters and devices.

**Comment by wwmm** [comment]
>I think this kind of thing won't happen anymore once our gtk4 branch is released. As PipeWire filters are being used instead of GStreamer the effects pipeline will be just a chain of filters and virtual devices. There won't be streams anymore.

Oops... Actually I did consider this would happen :smile: hahaha
