### ISSUE TITLE
Loudness Compensator adds significant latency

### ISSUE THREAD

**Issue by HyperGH** [wwmm/pulseeffects#966]
Enabling the loudness latency adds a significant 0.5-1 second latency to audio playback system-wide. Disabling it solves this issue.
Unsure what kind of information I should provide, but I am using Arch with KDE Plasma and latest pipewire & pulseeffects. Let me know if I should provide any more info!

**Comment by wwmm** [comment]
This plugin latency depends on the `FFT size` selected. As I did not write this plugin there is nothing I can do about this. You can ask its author about the implementation details in this page https://github.com/sadko4u/lsp-plugins. But considering that he usually optimizes his plugins there is a high chance that this is the best that can be done.

**Comment by HyperGH** [comment]
I see! Thank you, closing it then.
