### ISSUE TITLE
pulseeffects-CRITICAL: failed to move sink input: sfml

### ISSUE THREAD

**Issue by Flone-dnb** [wwmm/pulseeffects#968]
Hi. I've started learning SFML for audio and I've noticed that a simple audio playback program causes critical error in pulseeffects.
When I'm starting SFML audio pulseeffects says:

`(pulseeffects:12871): pulseeffects-CRITICAL **: 23:41:42.878: pulse_manager: failed to move sink input: sfml, idx = 86 to PE`
`(pulseeffects:12871): pulseeffects-CRITICAL **: 23:41:42.910: pulse_manager: failed to move sink input: sfml, idx = 87 to PE`

and thus no effects are applied. Any ideas? I can send you the SFML program that causes this, it's like 15 lines of code. :)

Running: Ubuntu 20.04.2 LTS
PulseEffects: 4.8.2

Thanks!

**Comment by wwmm** [comment]
>pulse_manager: failed to move sink input: sfml, idx = 86 to PE

Usually this happens when the audio program, sfml in this case, is setting the `DONT_MOVE` Pulseaudio flag. There are others programs that unfortunately do that too. Firefox(mic stream) is an example.

If the application tells Pulseaudio that no one is allowed to move its stream there is nothing I can do.

**Comment by Flone-dnb** [comment]
I will look into SFML and will investigate if I can remove this flag, thanks for the info!

**Comment by Flone-dnb** [comment]
If anyone stumbles upon this issue in the future, this issue seems to be related to OpenAL audio.

Solution from uTox/uTox#448:
1. Create a new file with the name `.alsoftrc` in your home dir.
2. Put text below into it.
```
[pulse]
allow-moves=yes
```
