### ISSUE TITLE
Pullseeffects source created in debug log but does not appear in patchbay

### ISSUE THREAD

**Issue by ifishtoo** [wwmm/pulseeffects#969]
I just started my deep dive into piipewire a month ago.  I swtiched from Ubuntu to Manjaro Gnome so I could build .3.27.  I have also installed wireplumber.I am  using pulseeffects-git from the aur.   I am impressed with how much is working so well already.  Linux has needed pipewire for a long time.  
Defiiinitely good enough for my everyday use.  I use the patchbay and calf  to make connections. PE provides me with all the control I could wish for if I can just get the source stream working as well as the sink stream does.  Let me know what your focus is and how I can  help.

I see this in the log 
(pulseeffects:14440): pulseeffects-DEBUG: 21:18:05.343: pipe_manager: Audio/Source/Virtual 98 pulseeffects_source was added

but the port does not appear in Carla's patchbay.  This is strange because the sinks appear just fine.  The source also appears in gnome system properties and in pavucontrol but I cannot select it. 
[pe-debug.txt](https://github.com/wwmm/pulseeffects/files/6525817/pe-debug.txt)
file:///home/vreppeto/Documents/sound/pw.dot
journalctl > log.txt && cat log.txt | grep pipewire >  plog.txt && cat log.txt | grep wireplumb > wlog.txt
[log.zip](https://github.com/wwmm/pulseeffects/files/6525865/log.zip)
[dump.txt](https://github.com/wwmm/pulseeffects/files/6525908/dump.txt)

  
I think I am going to switch to arch so I can seek help on  the aur forums.  Which distro are you using to develop PE?
Are you bypassing pipewire-media-manager and using pipe_manager to create your own nodes?  
What tools do I need to learn to use to debug this miissing source node?

**Comment by wwmm** [comment]
>but the port does not appear in Carla's patchbay. This is strange because the sinks appear just fine. 

Looking at your `pw-dump` file I noticed something odd in the `pulseeffects_source` node section. Lines `7083` and `7084`
```
"n-input-ports": 0,
"n-output-ports": 0,
```

That is clearly the reason why you are not being able to use this node. It should have 2 input and 2 output ports. The question is why PipeWire is failing to create them on your computer. On mine the ports are created.

>Which distro are you using to develop PE?

I use `Arch Linux` in all of my computers.

**Comment by wwmm** [comment]
>Are you bypassing pipewire-media-manager and using pipe_manager to create your own nodes?

No. For development purposes I try to keep Pipewire at its default settings. The only thing I removed from my system was `speech-dispatcher` because it has always caused undesired side effects. Pulseaudio included.

I do not create custom nodes. For me the virtual sink and source created by PulseEffects are enough because I am not using Jack apps.

**Comment by wwmm** [comment]
>Are you bypassing pipewire-media-manager and using pipe_manager to create your own nodes?

Maybe I should explain this better. I am using PipeWire API to programatically create my virtual devices. I never tried to do that using its command line tools. The links from the apps to our virtual devices are done through Pipewire's metadata API but the link between filters have to be done using a lower level PipeWire API.

In any case I tihnk something may not be right in your PipeWire install. I do not remember having problems with PipeWire `0.3.27` on Arch Linux. And things are still fine on `0.3.28`

**Comment by ifishtoo** [comment]
I have a fresh install Arch now. I'm going to close this issue. Thank you for the extra explanation.  It's really exciting to see these advancements in the sound architecture.
