### ISSUE TITLE
Add option to toggle --switch-on-all-apps

### ISSUE THREAD

**Issue by zestyr** [wwmm/pulseeffects#97]
It would be great if you could enable this from the UI.

**Comment by wwmm** [comment]
I will think about it. This option was added for people that do not want to open the window (they use the `--no-window` option). So I am not sure if there is a lot of people out there that would use this option in the main window.

**Comment by zestyr** [comment]
Well I can only speak for myself. When using it with the UI I find it very annoying having to manually enable new sources (which included new tabs in a browser), as I want it to act as a system-wide EQ.

**Comment by NitroOxid** [comment]
I agree with zestyr. There is desire to use Pulseeffects as a global equalizer on all system.

**Comment by wwmm** [comment]
You can. See the `--gapplication-service` here [https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options](https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options)

**Comment by NitroOxid** [comment]
Many thanks, I know it. I spoke about the "switch-on-all-apps" button in the section "applications". It would be very convenient.

**Comment by wwmm** [comment]
I will try to expose this option in the interface in the next PE version

**Comment by wwmm** [comment]
Implemented in PE 3.0.9. Open another issue if you have any problems. Closing.
