### ISSUE TITLE
Pulseeffects redirects all sound output to PulseEffects Source

### ISSUE THREAD

**Issue by funnisquares** [wwmm/pulseeffects#977]
I'm trying to setup PulseEffects to process my input audio, and it works great, with the exception that when it is on it makes it so the input transmits all sounds playing on my machine. I'm using discord to listen back to what is being sent through the mic.

**Comment by funnisquares** [comment]
I'm experimenting a bit more now, I don't know if pulseeffects is what is causing this. My mic is doing this whether pulse effects is running or not. What I do know, is that before installing pulseeffects (And changing from pulseaudio to pipewire) yesterday, this was not happening.

**Comment by wwmm** [comment]
Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects` so we can see some logs. Even if PulseEffects is not the cause of the problem maybe its logs will point to the right direction.

**Comment by funnisquares** [comment]
I've ended up switching back to pulseaudio and using the legacy pulseeffects. When I eventually go back to pipewire I'll be sure to do this if the issue still persists. Thanks!
