### ISSUE TITLE
Switch audio sink

### ISSUE THREAD

**Issue by zestyr** [wwmm/pulseeffects#98]
If I want to use speakers instead of headphones, I have to select the speaker sink from `pavucontrol` (or similar) and end pulseeffects, which makes audio sources use the speakers. 
This is pretty inconvenient, so an audio sink dropdown similar to the preset one would be very nice.

**Comment by wwmm** [comment]
I hope to be able to offer this possibility someday. At this moment we just ask Pulseaudio what is the default sink and use it to play audio. If the user changes this default while PulseEffects is running we already have a problem as we do not listen to changes in this default. So this is definitely something that has to be worked on.

**Comment by wwmm** [comment]
Latest code in master is able to automatically switch on the fly to the newest sink/source set in Pavucontrol. No device selection menu yet but this should make use cases like yours a little more comfort. Could you test it?

**Comment by mikhailnov** [comment]
it would be great to read the needed output device from the env variable PULSE_SOURCE / PULSE_SINK (do not know if it is read now) ot the same from command-line options

**Comment by wwmm** [comment]
These variables are not read. I didn't even knew they existed and it does not seem they are defined in my system. What I do is using the libpulse api to ask directly to Pulseaudio the default devices names.

I don't know if environmental variables would be a good fit to PulseEffects code. But I think that allowing these values to be set through command line options should not be difficult to implement.

**Comment by mikhailnov** [comment]
$ man pulseaudio | grep PULSE_ -A5 -B5
       rity/limits.conf. A resource limit of 31 (corresponding with nice level -11) is recommended.

ENVIRONMENT VARIABLES
       The PulseAudio client libraries check for the existence of the following environment variables and change their local configuration accordingly:

       $PULSE_SERVER:  the  server  string  specifying  the server to connect to when a client asks for a sound server connection and doesn't explicitly ask for a specific server. The server string is a list of server addresses separated by whitespace which are
       tried in turn. A server address consists of an optional address type specifier (unix:, tcp:, tcp4:, tcp6:), followed by a path or host address. A host address may include an optional port number. A server address may be prefixed by a string  enclosed  in
       {}. In this case the following server address is ignored unless the prefix string equals the local hostname or the machine id (/etc/machine-id).

       $PULSE_SINK: the symbolic name of the sink to connect to when a client creates a playback stream and doesn't explicitly ask for a specific sink.

       $PULSE_SOURCE: the symbolic name of the source to connect to when a client creates a record stream and doesn't explicitly ask for a specific source.

       $PULSE_BINARY: path of PulseAudio executable to run when server auto-spawning is used.

       $PULSE_CLIENTCONFIG: path of file that shall be read instead of client.conf (see above) for client configuration.

       $PULSE_COOKIE: path of file that contains the PulseAudio authentication cookie. Defaults to ~/.config/pulse/cookie.

       These environment settings take precedence -- if set -- over the configuration settings from client.conf (see above).

**Comment by wwmm** [comment]
Latest master uses the variables PULSE_SINK and PULSE_SOURCE when they are set. Could you test if everything is ok? It seems fine here.

If there is no problem I will make a new release.

**Comment by mikhailnov** [comment]
Yes, it does work, thanks for implementing this. Now I can start integrating PulseEffects with Dumacast)

**Comment by wwmm** [comment]
The code in latest master allows the user to select the output/input device from the main menu.
There are a few rough edges here and there but it is usable. I will polish this in the next versions.
