### ISSUE TITLE
Crashes on start-up after upgrading to Pipewire 0.3.29

### ISSUE THREAD

**Issue by 7RST1** [wwmm/pulseeffects#981]
After updating Pipewire to 0.3.29, Pulseeffects won't start. I use Fedora 34 Workstation. [This auto-generated report](https://retrace.fedoraproject.org/faf/reports/153233/) is given in the Problem Reporting application. The error in the logs seems to be not finding `pipewiresrc`:
```
** (pulseeffects:4617): ERROR **: 18:27:49.463: 
unhandled exception (type std::exception) in signal handler:
what: soe: Failed to get required plugin: pipewiresrc
```
Nothing new and useful appears when enabling debug output either. Only this error.
Users using other distros have fixed it by installing `gst-plugin-pipewire`, but that doesn't exist on dnf. Seeing how this only started occuring after the newest Pipewire update, i don't see how I'm missing any packages either.

**Comment by wwmm** [comment]
Take a look at https://github.com/wwmm/pulseeffects/issues/886#issuecomment-855426253. This is something that has to be handled by Fedora package maintainers.

**Comment by 7RST1** [comment]
Dang, I wrote it off because of Arch in title. Should have checked. Okay, will follow issue there.
