### ISSUE TITLE
Pulseeffects fails to start with newest version of "boost-libs"

### ISSUE THREAD

**Issue by Kneemund** [wwmm/pulseeffects#984]
Pulseeffects doesn't start when using `boost-libs` 1.76.0 (currently the [latest version on Arch](https://archlinux.org/packages/extra/x86_64/boost-libs/)):
```
pulseeffects: error while loading shared libraries: libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory
```

Downgrading to 1.75.0 using the pacman cache fixes the issue (temporarily).

**Comment by wwmm** [comment]
As soon as the Arch Linux packages maintainer recompiles the package with the new boost it will work again. In any case this is something that only the Arch maintainers can fix.

**Comment by thegreatyellow67** [comment]
A temporary fix that works:
sudo cp /usr/lib/libboost_filesystem.so.1.76.0 /usr/lib/libboost_filesystem.so.1.75.0

I'm testing and it seems that is working, waiting for the manteiner's fix!

**Comment by andrhua** [comment]
You just have to recompile (reinstall) pulseeffects package so it links the version installed on system
