### ISSUE TITLE
Control pulseeffect from python

### ISSUE THREAD

**Issue by anna-adamczyk** [wwmm/pulseeffects#985]
Hello,
pulseeffects is just what I need. Is it somehow possible to control it from within python and not via GUI?
That would be awesome!

**Comment by wwmm** [comment]
It is. Take a look at some possible ways showed in this discussion https://github.com/wwmm/pulseeffects/discussions/916

**Comment by anna-adamczyk** [comment]
Thank you so much for the pointer and quick answer!
