### ISSUE TITLE
Activity Timeout

### ISSUE THREAD

**Issue by LGFugler** [wwmm/pulseeffects#989]
Would it be possible to add a checkbox to turn this off? As the max time is currently limited to 3600s/ 1h.

My DAC has a popping sound when it turns back on so if I come back after an hour, then this feature causes a problem.

Thanks :smile:

![activity timeout](https://user-images.githubusercontent.com/86578440/123564325-ed46fb00-d7b0-11eb-97fd-21e4e297556d.png)

**Comment by wwmm** [comment]
>Would it be possible to add a checkbox to turn this off? As the max time is currently limited to 3600s/ 1h.

Although it is possible this is being handled so differently in our gtk4 branch that once it is released any work on the current master branch will be obsolete. The next big version won't even need a timeout.

**Comment by LGFugler** [comment]
installed pipewire and changed device suspend as recommended and it seems to have fixed it- thanks
